### ISSUE TITLE
1.2.499 cannot enter daemon mode - Debian Jessie

### ISSUE THREAD

**Issue by bleomycin** [Flexget/Flexget#1002]
Hello,

flexget 1.2.499 works great on debian jessie (patched and up to date), however when i try to enter daemon mode this happens:

```
/usr/local/bin/flexget -L debug daemon start
2016-04-02 18:49 DEBUG    manager                       Figuring out config load paths
2016-04-02 18:49 DEBUG    manager                       Found config: /home/flexget/.flexget/config.yml
2016-04-02 18:49 DEBUG    manager                       Config file /home/flexget/.flexget/config.yml selected
2016-04-02 18:49 DEBUG    manager                       sys.defaultencoding: ascii
2016-04-02 18:49 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-04-02 18:49 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-04-02 18:49 DEBUG    plugin                        Trying to load plugins from: [u'/home/flexget/.flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2016-04-02 18:49 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-04-02 18:49 DEBUG    deluge                        ConfigManager started..
2016-04-02 18:49 DEBUG    plugin                        Plugin `memusage` requires `ext lib `guppy`` to load.
2016-04-02 18:49 DEBUG    plugin                        Plugins took 0.72 seconds to load
2016-04-02 18:49 VERBOSE  manager                       Creating new database /home/flexget/.flexget/db-config.sqlite ...
2016-04-02 18:49 DEBUG    manager                       Connecting to: sqlite:////home/flexget/.flexget/db-config.sqlite
2016-04-02 18:49 DEBUG    schema                        Initializing plugin feed schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin api_trakt schema version to 3
2016-04-02 18:49 DEBUG    schema                        Initializing plugin make_rss schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin series schema version to 12
2016-04-02 18:49 DEBUG    schema                        Initializing plugin discover schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin seen schema version to 4
2016-04-02 18:49 DEBUG    schema                        Initializing plugin pogcal_acquired schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin archive schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin digest schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin remember_rejected schema version to 3
2016-04-02 18:49 DEBUG    schema                        Initializing plugin queue schema version to 2
2016-04-02 18:49 DEBUG    schema                        Initializing plugin simple_persistence schema version to 4
2016-04-02 18:49 DEBUG    schema                        Initializing plugin myepisodes schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin delay schema version to 1
2016-04-02 18:49 DEBUG    schema                        Initializing plugin failed schema version to 3
2016-04-02 18:49 DEBUG    schema                        Initializing plugin tail schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin api_tvdb schema version to 5
2016-04-02 18:49 DEBUG    schema                        Initializing plugin subtitle_queue schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin movie_queue schema version to 4
2016-04-02 18:49 DEBUG    schema                        Initializing plugin torrent411 schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin api_tmdb schema version to 1
2016-04-02 18:49 DEBUG    schema                        Initializing plugin log_once schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin imdb_lookup schema version to 7
2016-04-02 18:49 DEBUG    schema                        Initializing plugin api_rottentomatoes schema version to 2
2016-04-02 18:49 DEBUG    schema                        Initializing plugin version_checker schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin import_series schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin t411 schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin input_cache schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin telegram_chat_ids schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin tvmaze schema version to 3
2016-04-02 18:49 DEBUG    schema                        Initializing plugin thetvdb_favorites schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin rutracker_auth schema version to 0
2016-04-02 18:49 DEBUG    schema                        Initializing plugin backlog schema version to 1
2016-04-02 18:49 DEBUG    manager                       config_name: config
2016-04-02 18:49 DEBUG    manager                       config_base: /home/flexget/.flexget
2016-04-02 18:49 DEBUG    manager                       New config data loaded.
2016-04-02 18:49 DEBUG    parsing                       setting default movie parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x7f621c3b8b90>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x7f621c3ddad0>})
2016-04-02 18:49 DEBUG    parsing                       setting default series parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x7f621c3b8b90>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x7f621c3ddad0>})
2016-04-02 18:49 INFO     webui                         Not starting webui as it's disabled or not set in the config
2016-04-02 18:49 DEBUG    manager                       Removed /home/flexget/.flexget/.config-lock
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 303, in start
    self.handle_cli()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 327, in handle_cli
    self.daemon_command(command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 393, in daemon_command
    fire_event('manager.daemon.started', self)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 103, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/scheduler.py", line 143, in setup_scheduler
    setup_jobs(manager)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/scheduler.py", line 165, in setup_jobs
    existing_job_ids = [job.id for job in scheduler.get_jobs()]
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 511, in get_jobs
    jobs.extend(store.get_all_jobs())
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 81, in get_all_jobs
    jobs = self._get_jobs()
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 133, in _get_jobs
    for row in self.engine.execute(selectable):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: apscheduler_jobs [SQL: u'SELECT apscheduler_jobs.id, apscheduler_jobs.job_state \nFROM apscheduler_jobs ORDER BY apscheduler_jobs.next_run_time']
```

**Comment by anselal** [comment]
I get the same error. Why did you close this issue ?

**Comment by cvium** [comment]
This was fixed. I think a better question is why you're commenting on an almost 2 year old issue.
