### ISSUE TITLE
Can't upgrade pip or setuptools python error

### ISSUE THREAD

**Issue by steve51184** [Flexget/Flexget#1017]
# pip install --upgrade setuptools
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

# pip install --upgrade pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by cvium** [comment]
This is not a Flexget issue.

**Comment by steve51184** [comment]
could you at least point me in the right direction?

**Comment by cvium** [comment]
Google it. It's a common problem,

**Comment by steve51184** [comment]
I fixed this by replacing python-pip with get-pip which fixed the error but
I'm still unable to update flexget:

# flexget -V
1.2.389
Latest release: 1.2.505
# pip install --upgrade pip
Requirement already up-to-date: pip in
/usr/local/lib/python2.7/dist-packages

**Comment by cvium** [comment]
`pip` is the python package manager. The command `pip install --upgrade pip` only upgrades `pip`. You can upgrade package X by issuing the command `pip install --upgrade X` eg. `pip install --upgrade flexget`.

It would be better if you joined our gitter or irc channel. This is not the right place to discuss the basics of Python/pip.

**Comment by steve51184** [comment]
Oh my goodness how embarrassing I even know the commands but it's been a
very very long week and with trying to get pip working my brain just
stopped working :(

Sorry for going off topic here and thank you very very much for helping..
Everything is working and updated now

Much appreciated :)
On 8 Apr 2016 7:48 pm, "Claus Vium" <notifications@github.com> wrote:

pip is the python package manager. The command pip install --upgrade pip
only upgrades pip. You can upgrade package X by issuing the command pip
install --upgrade X eg. pip install --upgrade flexget.

It would be better if you joined our gitter or irc channel. This is not the
right place to discuss the basics of Python/pip.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Flexget/Flexget/issues/1017#issuecomment-207553202>
