### ISSUE TITLE
Multiple database is locked errors using new entry_list in config

### ISSUE THREAD

**Issue by xathin** [Flexget/Flexget#1018]
I just updated to 1.2.505, and started converting some of my tasks to the new list interface plugin. Everything was fine, until I started using the entry_list to create a series list from trakt. Also, I get the warning for trakt_list not returning a list anytime it runs. Here is the output of a crash log:

```
2016-04-08 11:26 WARNING  input_cache   fetch-series    Input trakt_list did not return a list, cannot cache.
2016-04-08 11:26 VERBOSE  trakt_list    fetch-series    Retrieving `shows` list `series`
2016-04-08 11:26 ERROR    lazy_lookup   fetch-series    Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 114, in lazy_series_actor_lookup
    return self.series_lookup(entry, self.series_actor_map)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/sqlalchemy_utils.py", line 137, in __exit__
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 706, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) database is locked [SQL: u'UPDATE tvdb_series SET actors=? WHERE tvdb_series.id = ?'] [parameters: (u'["Mandy Patinkin", "Diego Klattenhoff", "David Harewood", "Damian Lewis", "Morgan Saylor", "Rupert Friend", "Morena Baccarin", "Claire Danes", "Jackson Pace", "Nazanin Boniadi", "F. Murray Abraham", "Tracy Letts", "Sarita Choudhury", "Laila Robins", "Suraj Sharma", "Nimrat Kaur", "Numan Acar", "Sebastian Koch", "Sarah Sokolovic", "Miranda Otto"]', 247897)]
```

**Comment by xathin** [comment]
I had thetvdb_lookup in the same task as the list_add, which seems to have been causing the issue. Removing thetvdb_lookup from the task got rid of the error, so both cannot be in the same task.

**Comment by liiight** [comment]
This probably relates only to tvdb. Please run with the `-L debug` and `--debug-db-sessions` flags for the task and paste it here

**Comment by xathin** [comment]
Here is the log requested. I get the error for each entry it finds.

```
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8F6FA850 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.0255470275879)
2016-04-08 18:38 DEBUG    template      fetch-series    Merging template global into task fetch-series
2016-04-08 18:38 DEBUG    logfilter     fetch-series    Log filter 139958193030352 added (context "series", term "is already configured in series plugin")
2016-04-08 18:38 DEBUG    logfilter     fetch-series    Log filter 139958193030416 added (context "parser_internal", term "appears to be an episode pack")
2016-04-08 18:38 DEBUG    disable       fetch-series    Disabled built-in plugin(s): entry_operations, scan_imdb, torrent_files, backlog, change_warn, include, nzb_size, retry_failed, template, torrent_cache, torrent_size, metainfo_content_size, proxy, urlrewriting, verbose, dump, urlfix, seen_info_hash, remember_rejected, metainfo_task, torrent, history, seen, details, dump_config, series_db, --try-regexp, metainfo_quality, magnet_btih
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E610B10 opened ('flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E610B10 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.0251879692078)
2016-04-08 18:38 DEBUG    exec          fetch-series    phase cmd: echo "Starting..."
2016-04-08 18:38 VERBOSE  exec          fetch-series    Executing: echo "Starting..."
2016-04-08 18:38 INFO     exec          fetch-series    Stdout: Starting...\n
2016-04-08 18:38 DEBUG    input_cache   fetch-series    cache name: trakt_list_871e06b74ced311c907be93dbb7c6f20 (has: )
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E5A0050 opened ('flexget.utils.cached_input', 129, 'wrapped_func', 'filter(InputCache.added > datetime.now() - self.persist).\\')
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E5A0050 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.0289249420166)
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E5AAE10 opened ('flexget.plugins.api_trakt', 125, 'get_access_token', 'acc = session.query(TraktUserAuth).filter(TraktUserAuth.account == account).first()')
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E5AAE10 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.0285730361938)
2016-04-08 18:38 WARNING  input_cache   fetch-series    Input trakt_list did not return a list, cannot cache.
2016-04-08 18:38 VERBOSE  trakt_list    fetch-series    Retrieving `shows` list `series`
2016-04-08 18:38 DEBUG    utils.requests fetch-series    Fetching https://api-v2launch.trakt.tv/users/me/lists/series/items
2016-04-08 18:38 DEBUG    exec          fetch-series    phase on_input not configured
2016-04-08 18:38 DEBUG    exec          fetch-series    phase on_filter not configured
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E595B10 opened ('flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E595B10 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.0346169471741)
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E595750 opened ('flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Looking up tvdb information for Elementary (2012) 255316
2016-04-08 18:38 WARNING  debug_db_sess fetch-series    Sessions from 2 threads! Transaction 0x7F4A8DCFB750 opened ('flexget.plugins.api_tvdb', 397, 'lookup_series', 'series = session.query(TVDBSeries).filter(TVDBSeries.id == tvdb_id).first()') Already open one(s): {<sqlalchemy.orm.session.SessionTransaction object at 0x7f4a8e595750>: (1460155092.897015, <sqlalchemy.pool._ConnectionFairy object at 0x7f4a8dcfb0d0>, 'flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')}
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Series <name=Elementary (2012),tvdb_id=255316> information restored from cache.
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8DCFB750 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.0900349617004)
2016-04-08 18:38 DEBUG    entry_list    fetch-series    adding entry <Entry(title=Elementary,state=accepted)> to list trakt series
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Looking up tvdb information for Elementary (2012) 255316
2016-04-08 18:38 WARNING  debug_db_sess fetch-series    Sessions from 2 threads! Transaction 0x7F4A8DCE5410 opened ('flexget.plugins.api_tvdb', 397, 'lookup_series', 'series = session.query(TVDBSeries).filter(TVDBSeries.id == tvdb_id).first()') Already open one(s): {<sqlalchemy.orm.session.SessionTransaction object at 0x7f4a8e595750>: (1460155092.897015, <sqlalchemy.pool._ConnectionFairy object at 0x7f4a8dcfb0d0>, 'flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')}
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Series <name=Elementary (2012),tvdb_id=255316> information restored from cache.
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8DCE5410 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.104434013367)
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Looking up tvdb information for Elementary (2012) 255316
2016-04-08 18:38 WARNING  debug_db_sess fetch-series    Sessions from 2 threads! Transaction 0x7F4A8DCE5510 opened ('flexget.plugins.api_tvdb', 397, 'lookup_series', 'series = session.query(TVDBSeries).filter(TVDBSeries.id == tvdb_id).first()') Already open one(s): {<sqlalchemy.orm.session.SessionTransaction object at 0x7f4a8e595750>: (1460155092.897015, <sqlalchemy.pool._ConnectionFairy object at 0x7f4a8dcfb0d0>, 'flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')}
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Series <name=Elementary (2012),tvdb_id=255316> information restored from cache.
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8DCE5510 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.102644920349)
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8E595750 writing ('flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()') new: (<EntryListEntry,title=Elementary,original_url=http://trakt.tv/show/elementary>,) deleted: () dirty: ()
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Looking up tvdb information for Homeland (2011) 247897
2016-04-08 18:38 WARNING  debug_db_sess fetch-series    Sessions from 2 threads! Transaction 0x7F4A8DCD3390 opened ('flexget.plugins.api_tvdb', 397, 'lookup_series', 'series = session.query(TVDBSeries).filter(TVDBSeries.id == tvdb_id).first()') Already open one(s): {<sqlalchemy.orm.session.SessionTransaction object at 0x7f4a8e595750>: (1460155092.897015, <sqlalchemy.pool._ConnectionFairy object at 0x7f4a8dcfb0d0>, 'flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')}
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Series <name=Homeland (2011),tvdb_id=247897> information restored from cache.
2016-04-08 18:38 DEBUG    debug_db_sess fetch-series    Transaction 0x7F4A8DCD3390 closed ('flexget.utils.sqlalchemy_utils', 137, '__exit__', 'self.commit()') (open time 0.0796990394592)
2016-04-08 18:38 DEBUG    entry_list    fetch-series    adding entry <Entry(title=Homeland,state=accepted)> to list trakt series
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Looking up tvdb information for Homeland (2011) 247897
2016-04-08 18:38 WARNING  debug_db_sess fetch-series    Sessions from 2 threads! Transaction 0x7F4A8DCE5450 opened ('flexget.plugins.api_tvdb', 397, 'lookup_series', 'series = session.query(TVDBSeries).filter(TVDBSeries.id == tvdb_id).first()') Already open one(s): {<sqlalchemy.orm.session.SessionTransaction object at 0x7f4a8e595750>: (1460155092.897015, <sqlalchemy.pool._ConnectionFairy object at 0x7f4a8dcfb0d0>, 'flexget.plugins.list.entry_list', 69, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')}
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Series <name=Homeland (2011),tvdb_id=247897> information restored from cache.
2016-04-08 18:38 DEBUG    api_tvdb      fetch-series    Looking up actors for series Homeland
2016-04-08 18:38 DEBUG    util.simple_persistence fetch-series    setting key auth_tokens value {u'default': u'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjAyMDI1NTEsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDYwMTE2MTUxfQ.BjJorcQ4q6YH-8pXdFR_kwst4UesffAadngy8j-T8Dg0TAAYcFqBd0hqs84klYyuekhDnqpmylKib_l5sLWhvAJ4lpTAgJC9Q9sPL_VDEPSqU8kRWQ6ZR7O_dKTSbsimsqb4kvcKoFr0Lmg1u5_ckaTlwXOplA_ruIxLtsxRNAJW6D53FxXRIa8KcP3YdP64HlCzb4B4KLqSoKM00jIw75muLbdGioxY2KAXDGZAjmNtj8bO-VM86ofrUTYpHBXXuN5sXRRKYoDwZn8_vgvCm9gzBde00bjweYIzazkyX5s2gDKHN1cTvVG-Qx2_aZuInS9ehVOC_Rd19hyYyr4Ltw'}
2016-04-08 18:38 DEBUG    utils.requests fetch-series    Fetching https://api-beta.thetvdb.com/series/247897/actors
2016-04-08 18:38 WARNING  debug_db_sess fetch-series    Transaction 0x7F4A8DCE5450 closed ('flexget.utils.sqlalchemy_utils', 141, '__exit__', 'self.close()') (open time 10.6988530159)
2016-04-08 18:38 ERROR    lazy_lookup   fetch-series    Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 114, in lazy_series_actor_lookup
    return self.series_lookup(entry, self.series_actor_map)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/sqlalchemy_utils.py", line 137, in __exit__
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 706, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) database is locked [SQL: u'UPDATE tvdb_series SET actors=? WHERE tvdb_series.id = ?'] [parameters: (u'["Mandy Patinkin", "Diego Klattenhoff", "David Harewood", "Damian Lewis", "Morgan Saylor", "Rupert Friend", "Morena Baccarin", "Claire Danes", "Jackson Pace", "Nazanin Boniadi", "F. Murray Abraham", "Tracy Letts", "Sarita Choudhury", "Laila Robins", "Suraj Sharma", "Nimrat Kaur", "Numan Acar", "Sebastian Koch", "Sarah Sokolovic", "Miranda Otto"]', 247897)]
```
