### ISSUE TITLE
CRITICAL task: queue_from_imdb BUG: Unhandled error in plugin imdb_list: list index out of range

### ISSUE THREAD

**Issue by steve51184** [Flexget/Flexget#1020]
flexget.log:

```
2016-04-09 01:40 CRITICAL task          queue_from_imdb BUG: Unhandled error in plugin imdb_list: list index out of range
2016-04-09 01:40 CRITICAL manager       queue_from_imdb An unexpected crash has occurred. Writing crash report to crash_report.2016.04.09.014038803936.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.505
2016-04-09 01:40 WARNING  task          queue_from_imdb Aborting task (plugin: imdb_list)
```
crash_report.2016.04.09.014038803936.log:
```
2016-04-09 01:40 DEBUG    manager                       Figuring out config load paths
2016-04-09 01:40 DEBUG    manager                       Found config: config.yml
2016-04-09 01:40 DEBUG    manager                       Config file config.yml selected
2016-04-09 01:40 CRITICAL task          queue_from_imdb BUG: Unhandled error in plugin imdb_list: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 201, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 140, in __iter__
    return iter(self.items)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 105, in items
    'title': '%s (%s)' % (row[5], row[11]) if row[11] != '????' else '%s' % row[5],
IndexError: list index out of range
```

**Comment by gazpachoking** [comment]
Hmm, does this happen all the time? Can you try on a different list? Is there perhaps one movie that is causing this?

**Comment by steve51184** [comment]
I just updated to 505 so this is a new bug and yes it's happening all the
time.. In fact 6 more times since I reported this:

2016-04-09 01:40 CRITICAL task          queue_from_imdb BUG: Unhandled
error in plugin imdb_list: list index out of range
2016-04-09 01:40 CRITICAL manager       queue_from_imdb An unexpected crash
has occurred. Writing crash report to
crash_report.2016.04.09.014038803936.log. Please verify you are running the
latest version of flexget by using "flexget -V" from CLI or by using
version_checker plugin at http://flexget.com/wiki/Plugins/version_checker.
You are currently using version 1.2.505
2016-04-09 01:40 WARNING  task          queue_from_imdb Aborting task
(plugin: imdb_list)
2016-04-09 06:20 CRITICAL task          queue_from_imdb BUG: Unhandled
error in plugin imdb_list: list index out of range
2016-04-09 06:20 CRITICAL manager       queue_from_imdb An unexpected crash
has occurred. Writing crash report to
crash_report.2016.04.09.062038478475.log. Please verify you are running the
latest version of flexget by using "flexget -V" from CLI or by using
version_checker plugin at http://flexget.com/wiki/Plugins/version_checker.
You are currently using version 1.2.505
2016-04-09 06:20 WARNING  task          queue_from_imdb Aborting task
(plugin: imdb_list)
2016-04-09 07:25 CRITICAL task          queue_from_imdb BUG: Unhandled
error in plugin imdb_list: list index out of range
2016-04-09 07:25 CRITICAL manager       queue_from_imdb An unexpected crash
has occurred. Writing crash report to
crash_report.2016.04.09.072539172415.log. Please verify you are running the
latest version of flexget by using "flexget -V" from CLI or by using
version_checker plugin at http://flexget.com/wiki/Plugins/version_checker.
You are currently using version 1.2.505
2016-04-09 07:25 WARNING  task          queue_from_imdb Aborting task
(plugin: imdb_list)
2016-04-09 10:41 WARNING  inputs        HD-Movies       Error during input
plugin rss: Unable to download the RSS for task HD-Movies (http://url
HTTPSConnectionPool(host='bla.com', port=443): Read timed out. (read
timeout=60)
2016-04-09 10:41 WARNING  details       HD-Movies       Task didn't produce
any entries. This is likely due to a mis-configured or non-functional input.
2016-04-09 12:30 CRITICAL task          queue_from_imdb BUG: Unhandled
error in plugin imdb_list: list index out of range
2016-04-09 12:30 CRITICAL manager       queue_from_imdb An unexpected crash
has occurred. Writing crash report to
crash_report.2016.04.09.123039148469.log. Please verify you are running the
latest version of flexget by using "flexget -V" from CLI or by using
version_checker plugin at http://flexget.com/wiki/Plugins/version_checker.
You are currently using version 1.2.505
2016-04-09 12:30 WARNING  task          queue_from_imdb Aborting task
(plugin: imdb_list)
2016-04-09 14:05 CRITICAL task          queue_from_imdb BUG: Unhandled
error in plugin imdb_list: list index out of range
2016-04-09 14:05 CRITICAL manager       queue_from_imdb An unexpected crash
has occurred. Writing crash report to
crash_report.2016.04.09.140538106178.log. Please verify you are running the
latest version of flexget by using "flexget -V" from CLI or by using
version_checker plugin at http://flexget.com/wiki/Plugins/version_checker.
You are currently using version 1.2.505
2016-04-09 14:05 WARNING  task          queue_from_imdb Aborting task
(plugin: imdb_list)
2016-04-09 15:25 CRITICAL task          queue_from_imdb BUG: Unhandled
error in plugin imdb_list: 404 Client Error: Not Found for url:
http://www.imdb.com/list/export?list_id=ls006526765&author_id=ur16416164
2016-04-09 15:25 CRITICAL manager       queue_from_imdb An unexpected crash
has occurred. Writing crash report to
crash_report.2016.04.09.152538988704.log. Please verify you are running the
latest version of flexget by using "flexget -V" from CLI or by using
version_checker plugin at http://flexget.com/wiki/Plugins/version_checker.
You are currently using version 1.2.505
2016-04-09 15:25 WARNING  task          queue_from_imdb Aborting task
(plugin: imdb_list)

all 6 crash.log contain the same bug:

2016-04-09 12:30 DEBUG    manager                       Figuring out config
load paths
2016-04-09 12:30 DEBUG    manager                       Found config:
config.yml
2016-04-09 12:30 DEBUG    manager                       Config file
config.yml selected
2016-04-09 12:30 CRITICAL task          queue_from_imdb BUG: Unhandled
error in plugin imdb_list: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438,
in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22,
in __call__
    return self.func(*args, **kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py",
line 201, in on_task_input
    return list(self.get_list(config))
  File
"/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py",
line 140, in __iter__
    return iter(self.items)
  File
"/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py",
line 105, in items
    'title': '%s (%s)' % (row[5], row[11]) if row[11] != '????' else '%s' %
row[5],
IndexError: list index out of range

Hmm, does this happen all the time? Can you try on a different list? Is
there perhaps one movie that is causing this?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Flexget/Flexget/issues/1020#issuecomment-207789848>

**Comment by gazpachoking** [comment]
Can you grab the csv export of your list manually and post it here?

**Comment by steve51184** [comment]
Sure thing:

https://www.sendspace.com/file/tt454x

Can you grab the csv export of your list manually and post it here?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Flexget/Flexget/issues/1020#issuecomment-207793633>

**Comment by liiight** [comment]
@gazpachoking I don't see anything weird with that CSV, year is either year or `????` like expected. there's also no movie that's missing a title, This is very weird. I'll try to add some debug stuff to help use figure out which movie does this.

**Comment by dchubkov** [comment]
I confirm that bug is reproducible on my environment as well with same error message

Here is my list:
> Movies for list imdb_movies_wish_list:
> -------------------------------------------------------------------------------
> Дедушка легкого поведения (2016) [imdb_id=tt1860213]
> Человек (2015) [imdb_id=tt3327994]
> Elser (2015) [imdb_id=tt1708135]
> Лобстер (2015) [imdb_id=tt3464902]
> Игры в полях Господних (1991) [imdb_id=tt0101373]
> Зеленый ад (2013) [imdb_id=tt2403021]
> Выхода нет (2015) [imdb_id=tt1781922]
> Невозможное (2012) [imdb_id=tt1649419]
> Инсайдеры (2010) [imdb_id=tt1645089]
> Простушка (2015) [imdb_id=tt1666801]
> Секретные материалы: Хочу верить (2008) [imdb_id=tt0443701]
> Нервы на пределе (1991) [imdb_id=tt0102032]
> Майор (2013) [imdb_id=tt2594950]
> 7 дней в аду (2015) [imdb_id=tt3895884]
> Одержимость (2014) [imdb_id=tt2582802]
> Возвращение (2003) [imdb_id=tt0376968]
> Край (2010) [imdb_id=tt1706414]
> Неправильные копы (2013) [imdb_id=tt2166616]
> Оливер Твист (2007) [imdb_id=tt1065309]
> Бронсон (2008) [imdb_id=tt1172570]
> Самый пьяный округ в мире (2012) [imdb_id=tt1212450]
> Конгресс (2013) [imdb_id=tt1821641]
> Бобёр (2011) [imdb_id=tt1321860]
> Мальчик в полосатой пижаме (2008) [imdb_id=tt0914798]
> Дэдпул (2016) [imdb_id=tt1431045]
> Мечты Дзиро о суши (2011) [imdb_id=tt1772925]
> Совокупность лжи (2008) [imdb_id=tt0758774]
> Halo: Сумерки (2014) [imdb_id=tt3804114]
> Девушка моих кошмаров (2007) [imdb_id=tt0408839]
> Сотня (2014) [imdb_id=tt2661044]
> Бэтмен против Супермена: На заре справедливости (2016) [imdb_id=tt2975590]



flexget -V
1.2.509
Latest release: 1.2.510

**Comment by lepinkainen** [comment]
Same issue, different list. This time list_reject, that's looking through my rated movies and rejecting them.

```
2016-04-17 14:21 CRITICAL task          movies   BUG: Unhandled error in plugin list_reject: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/list_reject.py", line 33, in on_task_filter
    if entry in thelist:
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 138, in __contains__
    return any(e['imdb_id'] == entry['imdb_id'] for e in self.items)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 106, in items
    'title': '%s (%s)' % (row[5], row[11]) if row[11] != '????' else '%s' % row[5],
IndexError: list index out of range
```

**Comment by liiight** [comment]
Please provide debug logs

**Comment by liiight** [comment]
If someone could provide debug logs of this it would be really useful, as I was unable to reproduce this.

**Comment by steve51184** [comment]
sure I'll do it but how do I do that?

**Comment by liiight** [comment]
Execute with `-L debug`

**Comment by lepinkainen** [comment]
1.2.512 with debug enabled

```
2016-04-19 15:30 DEBUG    manager                       Figuring out config load paths
2016-04-19 15:30 DEBUG    manager                       Found config: /home/shrike/.config/flexget/config.yml
2016-04-19 15:30 DEBUG    manager                       Config file /home/shrike/.config/flexget/config.yml selected
2016-04-19 15:30 INFO     scheduler                     Starting scheduler
2016-04-19 15:30 INFO     webui                         Not starting webui as it's disabled or not set in the config
2016-04-19 15:30 WARNING  web_server                    No password set for web server, create one by using `flexget web passwd <password>`
2016-04-19 15:30 INFO     web_server                    Web interface available at http://127.0.0.1:9090
2016-04-19 15:31 VERBOSE  utils.requests imdb_watchlist  Waiting 2.52 seconds until next request to imdb.com
2016-04-19 15:31 VERBOSE  utils.requests imdb_watchlist  Waiting 4.46 seconds until next request to imdb.com
2016-04-19 15:31 VERBOSE  utils.requests imdb_watchlist  Waiting 4.47 seconds until next request to imdb.com
2016-04-19 15:31 VERBOSE  utils.requests imdb_watchlist  Waiting 4.77 seconds until next request to imdb.com
2016-04-19 15:31 CRITICAL task          imdb_watchlist  BUG: Unhandled error in plugin imdb_list: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 208, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 141, in __iter__
    return iter(self.items)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 106, in items
    'title': '%s (%s)' % (row[5], row[11]) if row[11] != '????' else '%s' % row[5],
IndexError: list index out of range

```

**Comment by lepinkainen** [comment]
Retried with 1.2.515 and no error there. The error seems a bit intermittent.

**Comment by chewy74** [comment]
@liiight Debug log and on version 1.2.515

```
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 56, tt1473832, Tue Jan 26 18:20:53 2016, Tue Jan 26 18:20:53 2016, , Bridget Jones's Baby, Feature Film, Sharon Maguire, , , , 2016, comedy, romance, , 2016-09-15, http://www.imdb.com/title/tt1473832/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 57, tt1648190, Tue Jan 26 18:21:51 2016, Tue Jan 26 18:21:51 2016, , The Dark Tower, Feature Film, Nikolaj Arcel, , , , 2017, fantasy, horror, sci_fi, western, , 2017-02-16, http://www.imdb.com/title/tt1648190/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 58, tt2527336, Thu Jan 28 20:40:56 2016, Thu Jan 28 20:40:56 2016, , Star Wars: Episode VIII, Feature Film, Rian Johnson, , , , 2017, action, adventure, fantasy, sci_fi, , 2017-12-14, http://www.imdb.com/title/tt2527336/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 59, tt2597892, Thu Jan 28 21:16:06 2016, Thu Jan 28 21:16:06 2016, , Viral, Feature Film, Henry Joost, Ariel Schulman, , , 89, 2016, drama, horror, sci_fi, thriller, , 2016-08-10, http://www.imdb.com/title/tt2597892/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 60, tt1458169, Thu Jan 28 21:16:40 2016, Thu Jan 28 21:16:40 2016, , Kidnap, Feature Film, Luis Prieto, , , , 2016, thriller, , 2016-05-13, http://www.imdb.com/title/tt1458169/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 61, tt3702652, Thu Jan 28 21:16:47 2016, Thu Jan 28 21:16:47 2016, , The Other Side of the Door, Feature Film, Johannes Roberts, , 5.4, 96, 2016, horror, 1226, 2016-02-24, http://www.imdb.com/title/tt3702652/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 62, tt1935897, Thu Jan 28 21:17:53 2016, Thu Jan 28 21:17:53 2016, , Amityville: The Awakening, Feature Film, Franck Khalfoun, , , , 2017, horror, thriller, , 2017-01-06, http://www.imdb.com/title/tt1935897/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 63, tt3014866, Thu Jan 28 21:17:58 2016, Thu Jan 28 21:17:58 2016, , Criminal, Feature Film, Ariel Vromen, , 6.6, 113, 2016, action, crime, drama, mystery, sci_fi, thriller, 1128, 2016-04-07, http://www.imdb.com/title/tt3014866/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 64, tt2823054, Thu Jan 28 21:20:10 2016, Thu Jan 28 21:20:10 2016, , Mike and Dave Need Wedding Dates, Feature Film, Jake Szymanski, , , , 2016, comedy, , 2016-07-07, http://www.imdb.com/title/tt2823054/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 65, tt2106651, Thu Jan 28 21:20:52 2016, Thu Jan 28 21:20:52 2016, , Spectral, Feature Film, Nic Mathieu, , , , 2016, action, sci_fi, , 2016-08-11, http://www.imdb.com/title/tt2106651/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 66, tt4160708, Thu Jan 28 21:21:17 2016, Thu Jan 28 21:21:17 2016, , Don't Breathe, Feature Film, Fede Alvarez, , 8.4, , 2016, horror, thriller, 92, 2016-03-12, http://www.imdb.com/title/tt4160708/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 67, tt3458254, Thu Jan 28 21:21:27 2016, Thu Jan 28 21:21:27 2016, , Patient Zero, Feature Film, Stefan Ruzowitzky, , , , 2016, action, drama, horror, , 2016-08-25, http://www.imdb.com/title/tt3458254/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 68, tt4786282, Thu Jan 28 21:21:34 2016, Thu Jan 28 21:21:34 2016, , Lights Out, Feature Film, David F. Sandberg, , , , 2016, horror, , 2016-07-21, http://www.imdb.com/title/tt4786282/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 69, tt1389139, Thu Jan 28 21:21:54 2016, Thu Jan 28 21:21:54 2016, , When the Bough Breaks, Feature Film, Jon Cassar, , , , 2016, drama, horror, mystery, thriller, , 2016-09-16, http://www.imdb.com/title/tt1389139/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 70, tt4361050, Thu Jan 28 21:22:48 2016, Thu Jan 28 21:22:48 2016, , Ouija 2, Feature Film, Mike Flanagan, , , , 2016, horror, thriller, , 2016-10-21, http://www.imdb.com/title/tt4361050/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 71, tt4276820, Thu Jan 28 21:23:47 2016, Thu Jan 28 21:23:47 2016, , The Founder, Feature Film, John Lee Hancock, , , , 2016, biography, drama, history, , 2016-08-05, http://www.imdb.com/title/tt4276820/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 72, tt2283362, Thu Jan 28 21:24:17 2016, Thu Jan 28 21:24:17 2016, , Jumanji, Feature Film, Jake Kasdan, , , , 2017, adventure, family, fantasy, , 2017-07-27, http://www.imdb.com/title/tt2283362/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 73, tt1502397, Thu Jan 28 21:26:09 2016, Thu Jan 28 21:26:09 2016, , Bad Boys 3, Feature Film, Joe Carnahan, , , , 2017, action, comedy, thriller, , 2017-06-01, http://www.imdb.com/title/tt1502397/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 74, tt4500922, Thu Jan 28 21:26:12 2016, Thu Jan 28 21:26:12 2016, , Maze Runner: The Death Cure, Feature Film, Wes Ball, , , , 2017, action, sci_fi, thriller, , 2017-01-27, http://www.imdb.com/title/tt4500922/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 75, tt2404435, Sat Feb  6 11:04:57 2016, Sat Feb  6 11:04:57 2016, , The Magnificent Seven, Feature Film, Antoine Fuqua, , , , 2016, action, western, , 2016-09-22, http://www.imdb.com/title/tt2404435/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 76, tt3470600, Sat Feb  6 11:05:47 2016, Sat Feb  6 11:05:47 2016, , Sing, Feature Film, Garth Jennings, , , , 2016, animation, comedy, musical, , 2016-12-15, http://www.imdb.com/title/tt3470600/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 77, tt1935859, Sat Feb  6 11:06:25 2016, Sat Feb  6 11:06:25 2016, , Miss Peregrine's Home for Peculiar Children, Feature Film, Tim Burton, , , , 2016, adventure, fantasy, , 2016-09-28, http://www.imdb.com/title/tt1935859/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 78, tt3072482, Sun Feb 21 10:52:51 2016, Sun Feb 21 10:52:51 2016, , Hardcore Henry, Feature Film, Ilya Naishuller, , 7.1, 96, 2015, action, adventure, sci_fi, 8595, 2015-09-12, http://www.imdb.com/title/tt3072482/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 79, tt4425200, Sun Feb 21 10:56:39 2016, Sun Feb 21 10:56:39 2016, , John Wick: Chapter Two, Feature Film, Chad Stahelski, , , , 2017, action, thriller, , 2017-02-09, http://www.imdb.com/title/tt4425200/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 80, tt1895484, Tue Feb 23 09:15:36 2016, Tue Feb 23 09:15:36 2016, , Model Minority, Feature Film, Lily Mariye, , 7.8, 94, 2012, drama, 98, 2012-05-11, http://www.imdb.com/title/tt1895484/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 81, tt1878841, Fri Mar  4 09:56:14 2016, Fri Mar  4 09:56:14 2016, , The Darkness, Feature Film, Greg Mclean, , , , 2016, horror, thriller, , 2016-05-13, http://www.imdb.com/title/tt1878841/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 82, tt3289728, Fri Mar  4 09:57:01 2016, Fri Mar  4 09:57:01 2016, , Equals, Feature Film, Drake Doremus, , 6.1, 101, 2015, drama, romance, sci_fi, 484, 2015-09-05, http://www.imdb.com/title/tt3289728/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 83, tt4129870, Sat Mar 12 06:53:28 2016, Sat Mar 12 06:53:28 2016, , White Girl, Feature Film, Elizabeth Wood, , 7.1, 88, 2016, drama, 51, 2016-01-23, http://www.imdb.com/title/tt4129870/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 84, tt3174376, Sun Mar 13 15:29:53 2016, Sun Mar 13 15:29:53 2016, , Before I Wake, Feature Film, Mike Flanagan, , 6.8, , 2016, horror, thriller, 421, 2016-04-07, http://www.imdb.com/title/tt3174376/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 85, tt3960412, Sun Mar 13 15:34:44 2016, Sun Mar 13 15:34:44 2016, , Popstar: Never Stop Never Stopping, Feature Film, Akiva Schaffer, Jorma Taccone, , , , 2016, comedy, music, , 2016-06-03, http://www.imdb.com/title/tt3960412/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 86, tt1293847, Sun Mar 13 15:37:28 2016, Sun Mar 13 15:37:28 2016, , xXx: The Return of Xander Cage, Feature Film, D.J. Caruso, , , , 2017, action, adventure, thriller, , 2017-01-19, http://www.imdb.com/title/tt1293847/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 87, tt3315342, Sun Mar 13 15:37:41 2016, Sun Mar 13 15:37:41 2016, , Untitled Wolverine Sequel, Feature Film, James Mangold, , , , 2017, action, sci_fi, , 2017-03-02, http://www.imdb.com/title/tt3315342/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 88, tt3471098, Fri Mar 18 10:21:52 2016, Fri Mar 18 10:21:52 2016, , Maggie's Plan, Feature Film, Rebecca Miller, , 6.8, 98, 2015, comedy, 290, 2015-09-12, http://www.imdb.com/title/tt3471098/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 89, tt4682786, Fri Mar 18 10:24:11 2016, Fri Mar 18 10:24:11 2016, , Collateral Beauty, Feature Film, David Frankel, , , , 2016, drama, , 2016-12-15, http://www.imdb.com/title/tt4682786/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 90, tt4572514, Fri Mar 18 10:24:22 2016, Fri Mar 18 10:24:22 2016, , Patriots Day, Feature Film, Peter Berg, , , , 2016, drama, history, thriller, , 2016-12-21, http://www.imdb.com/title/tt4572514/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 91, tt3760966, Wed Mar 23 17:01:12 2016, Wed Mar 23 17:01:12 2016, , Food, Feature Film, Daryl Wein, , 4.2, 95, 2015, drama, thriller, 429, 2015-06, http://www.imdb.com/title/tt3760966/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 92, tt3297586, Thu Mar 24 07:32:48 2016, Thu Mar 24 07:32:48 2016, , The Before Time, Feature Film, Miguel Müller, , 4.0, 80, 2014, horror, mystery, thriller, 60, 2014, http://www.imdb.com/title/tt3297586/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 93, tt1726252, Tue Mar 29 22:12:24 2016, Tue Mar 29 22:12:24 2016, , Die dunkle Seite des Mondes, Feature Film, Stephan Rick, , 7.4, 98, 2015, thriller, 911, 2015-09-27, http://www.imdb.com/title/tt1726252/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 94, tt1486683, Tue Mar 29 22:14:01 2016, Tue Mar 29 22:14:01 2016, , Fortified, Feature Film, Spencer T. Folmar, , 8.3, 47, 2008, action, thriller, 531, 2008-07, http://www.imdb.com/title/tt1486683/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 95, tt3835080, Wed Mar 30 08:37:01 2016, Wed Mar 30 08:37:01 2016, , 31, Feature Film, Rob Zombie, , 7.3, 102, 2016, horror, thriller, 186, 2016-01-23, http://www.imdb.com/title/tt3835080/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 96, tt2140479, Wed Mar 30 08:37:20 2016, Wed Mar 30 08:37:20 2016, , The Accountant, Feature Film, Gavin O'Connor, , , 128, 2016, drama, , 2016-10-06, http://www.imdb.com/title/tt2140479/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 97, tt1799527, Sun Apr  3 16:09:57 2016, Sun Apr  3 16:09:57 2016, , Doom, Video Game, John Carmack, Tim Willits, , , , 2016, action, horror, sci_fi, , 2016-05-13, http://www.imdb.com/title/tt1799527/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 98, tt5034082, Sun Apr 17 14:45:08 2016, Sun Apr 17 14:45:08 2016, , The Girl in the Cornfield, Feature Film, Ryan Callaway, , , 81, 2016, horror, mystery, , 2016-05-13, http://www.imdb.com/title/tt5034082/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 99, tt1489889, Sun Apr 17 14:46:14 2016, Sun Apr 17 14:46:14 2016, , Central Intelligence, Feature Film, Rawson Marshall Thurber, , , , 2016, comedy, crime, , 2016-06-15, http://www.imdb.com/title/tt1489889/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 100, tt2005151, Sun Apr 17 14:50:12 2016, Sun Apr 17 14:50:12 2016, , War Dogs, Feature Film, Todd Phillips, , , , 2016, comedy, drama, war, , 2016-08-18, http://www.imdb.com/title/tt2005151/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 101, tt2126235, Sun Apr 17 14:51:16 2016, Sun Apr 17 14:51:16 2016, , Collide, Feature Film, Eran Creevy, , , , 2016, action, thriller, , 2016-04-20, http://www.imdb.com/title/tt2126235/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 102, tt3731562, Sun Apr 17 14:52:27 2016, Sun Apr 17 14:52:27 2016, , Kong: Skull Island, Feature Film, Jordan Vogt-Roberts, , , , 2017, action, adventure, fantasy, , 2017-03-09, http://www.imdb.com/title/tt3731562/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: 103, tt2771200, Sun Apr 17 14:52:40 2016, Sun Apr 17 14:52:40 2016, , Beauty and the Beast, Feature Film, Bill Condon, , , , 2017, fantasy, musical, romance, , 2017-03-16, http://www.imdb.com/title/tt2771200/
2016-04-19 12:40 DEBUG    imdb_list     IMDB            parsing line from csv: <link rel="stylesheet" type="text/css" href="http://i.media-imdb.com/images/SFc25df55df212e779731eda38c3806095/css/min/lists.css" ><link rel="stylesheet" type="text/css" href="http://i.media-imdb.com/images/SFd36761b30ebc061c8d30826d3d211d3c/css2/site/consumer-navbar-mega.css" ><link rel="stylesheet" type="text/css" href="http://i.media-imdb.com/images/SFa88e6ba92e5894e7909b0d2ef5d21e79/css2/site/consumer-navbar-suggestionsearch.css" >
2016-04-19 12:40 CRITICAL task          IMDB            BUG: Unhandled error in plugin imdb_list: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 209, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 142, in __iter__
    return iter(self.items)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 106, in items
    'title': '%s (%s)' % (row[5], row[11]) if row[11] != '????' else '%s' % row[5],
IndexError: list index out of range
```

**Comment by liiight** [comment]
Ah, finally something to work with

**Comment by steve51184** [comment]
Same problem on latest version:

2016-04-21 00:05 DEBUG    manager                       Figuring out config load paths
2016-04-21 00:05 DEBUG    manager                       Found config: /config.yml
2016-04-21 00:05 DEBUG    manager                       Config file /config.yml selected
2016-04-21 00:05 CRITICAL task          queue_from_imdb BUG: Unhandled error in plugin imdb_list: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 209, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 142, in __iter__
    return iter(self.items)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 106, in items
    'title': '%s (%s)' % (row[5], row[11]) if row[11] != '????' else '%s' % row[5],
IndexError: list index out of range

**Comment by liiight** [comment]
It wasn't released yet, should be on 517

**Comment by steve51184** [comment]
Ah ok sorry and thank you very much for the fix we really appreciate it :)
