### ISSUE TITLE
BUG: Unhandled error in plugin subliminal: 'module' object has no attribute 'core'

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1023]
fmf@kodi:~$ flexget -V
1.2.508
You are on the latest release.

2016-04-11 11:02 CRITICAL task          download-subtitles BUG: Unhandled error in plugin subliminal: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/subtitles_subliminal.py", line 124, in on_task_output
    existing_subtitles = set(subliminal.core.search_external_subtitles(entry['location']).values())
AttributeError: 'module' object has no attribute 'core'

**Comment by cvium** [comment]
You need to upgrade Subliminal from Git. `pip install --upgrade https://github.com/Diaoul/subliminal/archive/develop.zip`.

**Comment by effemmeffe** [comment]
Thanks, solved
