### ISSUE TITLE
imdb_list & list_remove

### ISSUE THREAD

**Issue by lostsubstance** [Flexget/Flexget#1025]
I'm on 1.2.509.

```
2016-04-11 20:53 DEBUG    manager       imdb            Traceback:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\output\list_remove.py", line 36, in on_task_output
    thelist -= task.accepted
  File "c:\python27\lib\_abcoll.py", line 356, in __isub__
    self.discard(value)
  File "c:\python27\lib\site-packages\flexget\plugins\list\imdb_list.py", line 173, in discard
    self._items = [i for i in self._items if i['imdb_id'] != entry['imdb_id']]
TypeError: 'NoneType' object is not iterable
```

The remove is successful, but crashes cleaning up cache and interrupts task.

**Comment by liiight** [comment]
Can you paste full debug logs and crash report please?

**Comment by liiight** [comment]
@gazpachoking i think maybe we should invalidate the cache on `discard`, and also use an empty list to invalidate rather than `None`.

**Comment by lostsubstance** [comment]
log:
```
PS C:\> flexget --loglevel debug execute --tasks imdb
2016-04-12 20:43 DEBUG    manager                       Figuring out config load paths
2016-04-12 20:43 DEBUG    manager                       Found config: C:\Users\<user>\flexget\config.yml
2016-04-12 20:43 DEBUG    manager                       Config file C:\Users\<user>\flexget\config.yml selected
2016-04-12 20:43 DEBUG    manager                       sys.defaultencoding: ascii
2016-04-12 20:43 DEBUG    manager                       sys.getfilesystemencoding: mbcs
2016-04-12 20:43 DEBUG    manager                       os.path.supports_unicode_filenames: True
2016-04-12 20:43 DEBUG    plugin                        Trying to load plugins from: [u'C:\\Users\\<user>\\flexget\\plugins', 'c:\\python27\\lib\\site-packages\\flexget\\plugins']
2016-04-12 20:43 DEBUG    safe                          Reading from cache file c:\users\<user>\appdata\local\temp\safe-0.4.words.cache
2016-04-12 20:43 DEBUG    plugin                        Plugin `memusage` requires `ext lib `guppy`` to load.
2016-04-12 20:43 DEBUG    deluge                        Looking for deluge install in C:\Program Files (x86)\Deluge
2016-04-12 20:43 DEBUG    deluge                        Found deluge install in C:\Program Files (x86)\Deluge adding to sys.path
2016-04-12 20:43 DEBUG    deluge                        ConfigManager started..
2016-04-12 20:43 DEBUG    plugin                        Plugins took 2.36 seconds to load
2016-04-12 20:43 DEBUG    manager                       Connecting to: sqlite:///C:\\Users\\<user>\\flexget\\db-config.sqlite
2016-04-12 20:43 DEBUG    manager                       config_name: config
2016-04-12 20:43 DEBUG    manager                       config_base: C:\Users\<user>\flexget
2016-04-12 20:43 DEBUG    manager                       New config data loaded.
2016-04-12 20:43 DEBUG    parsing                       setting default movie parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x046B4C50>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x04DA5290>})
2016-04-12 20:43 DEBUG    parsing                       setting default series parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x046B4C50>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x04DA5290>})
2016-04-12 20:43 DEBUG    cron_env                      Encoding mbcs stored
2016-04-12 20:43 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'mbcs'
2016-04-12 20:43 DEBUG    task_queue                    task queue shutdown requested
2016-04-12 20:43 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-04-12 20:43 INFO     ipc.rpyc                      server started on [127.0.0.1]:52427
2016-04-12 20:43 DEBUG    task          imdb            executing imdb
2016-04-12 20:43 DEBUG    template      imdb            Merging template global into task imdb
2016-04-12 20:43 DEBUG    disable       imdb            Disabled built-in plugin(s): seen
2016-04-12 20:43 DEBUG    headers       imdb            headers to add: {u'Referer': u'http://torcache.net/', u'User-Agent': u'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36'}
2016-04-12 20:43 DEBUG    headers       imdb            Creating new opener and installing it
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 1 seconds between requests to torrenticity.com
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 1 seconds between requests to torrentz.eu
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 1 seconds between requests to kat.cr
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 10 seconds between requests to torcache.net
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 5 seconds between requests to rarbg.com
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 1 seconds between requests to torlock.eu
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 1 seconds between requests to itorrents.org
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 5 seconds between requests to rarbg.to
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 1 seconds between requests to bt-chat.com
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 1 seconds between requests to ezrss.it
2016-04-12 20:43 DEBUG    domain_delay  imdb            Adding minimum interval of 1 seconds between requests to torrentz.me
2016-04-12 20:43 DEBUG    urlrewrite    imdb            Added rewrite torcache
2016-04-12 20:43 DEBUG    remember_rej  imdb            Task config has changed since last run, purging remembered entries.
2016-04-12 20:43 DEBUG    utils.requests imdb            Fetching https://www.imdb.com/ap/signin?...
2016-04-12 20:43 DEBUG    utils.requests imdb            Fetching https://www.imdb.com/ap/signin
2016-04-12 20:43 DEBUG    utils.requests imdb            Fetching http://www.imdb.com/profile
2016-04-12 20:43 DEBUG    utils.requests imdb            Fetching http://www.imdb.com/list/_ajax/watchlist_has
2016-04-12 20:43 DEBUG    utils.requests imdb            Fetching http://www.imdb.com/list/export?...
2016-04-12 20:43 DEBUG    imdb_list     imdb            parsing line from csv: 1, tt1386697, Mon Apr 11 19:05:59 2016, Mon Apr 11 19:05:59 2016, , Suicide Squad, Feature Film, David Ayer, , , , 2016, action, adventure, fantasy, sci_fi, thriller, , 2016-08-03, http://www.imdb.com/title/tt1386697/
2016-04-12 20:43 DEBUG    backlog       imdb            0 entries purged from backlog
2016-04-12 20:43 VERBOSE  details       imdb            Produced 1 entries.
2016-04-12 20:43 VERBOSE  task          imdb            ACCEPTED: `Suicide Squad (2016)` by accept_all plugin
2016-04-12 20:43 DEBUG    urlrewriter   imdb            Checking 1 entries
2016-04-12 20:43 VERBOSE  details       imdb            Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2016-04-12 20:44 DEBUG    utils.requests imdb            Fetching https://www.imdb.com/ap/signin?...
2016-04-12 20:44 DEBUG    utils.requests imdb            Fetching https://www.imdb.com/ap/signin
2016-04-12 20:44 DEBUG    utils.requests imdb            Fetching http://www.imdb.com/profile
2016-04-12 20:44 DEBUG    utils.requests imdb            Fetching http://www.imdb.com/list/_ajax/watchlist_has
2016-04-12 20:44 DEBUG    utils.requests imdb            Fetching http://www.imdb.com/list/_ajax/watchlist_has
2016-04-12 20:44 DEBUG    utils.requests imdb            Fetching http://www.imdb.com/list/_ajax/edit
2016-04-12 20:44 CRITICAL task          imdb            BUG: Unhandled error in plugin list_remove: 'NoneType' object is not iterable
2016-04-12 20:44 DEBUG    manager       imdb            Traceback:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\output\list_remove.py", line 36, in on_task_output
    thelist -= task.accepted
  File "c:\python27\lib\_abcoll.py", line 356, in __isub__
    self.discard(value)
  File "c:\python27\lib\site-packages\flexget\plugins\list\imdb_list.py", line 173, in discard
    self._items = [i for i in self._items if i['imdb_id'] != entry['imdb_id']]
TypeError: 'NoneType' object is not iterable
2016-04-12 20:44 WARNING  task          imdb            Aborting task (plugin: list_remove)
2016-04-12 20:44 DEBUG    backlog       imdb            Remembering all entries to backlog because of task abort.
2016-04-12 20:44 DEBUG    backlog       imdb            Saving Suicide Squad (2016)
2016-04-12 20:44 DEBUG    headers       imdb            Removing urllib2 default opener
2016-04-12 20:44 DEBUG    disable       imdb            Re-enabled builtin plugin(s): seen
2016-04-12 20:44 DEBUG    task_queue                    task imdb aborted: TaskAbort(reason=BUG: Unhandled error in plugin list_remove: 'NoneType' object is not iterable, silent=False)
2016-04-12 20:44 DEBUG    task_queue                    task queue shut down
2016-04-12 20:44 INFO     ipc.rpyc                      listener closed
2016-04-12 20:44 DEBUG    util.simple_persistence                 Flushing simple persistence for task None to db.
2016-04-12 20:44 DEBUG    manager                       Shutting down
2016-04-12 20:44 DEBUG    manager                       Removed C:\Users\<user>\flexget\.config-lock
```
