### ISSUE TITLE
Index out of bounds in imdb_list

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#1029]
On 1.2.508:

```
2016-04-12 20:23 CRITICAL task          imdb_watchlist  BUG: Unhandled error in plugin imdb_list: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 202, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 141, in __iter__
    return iter(self.items)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 106, in items
    'title': '%s (%s)' % (row[5], row[11]) if row[11] != '????' else '%s' % row[5],
IndexError: list index out of range
```

**Comment by liiight** [comment]
Duplicate #1020
