### ISSUE TITLE
input cache error after upgrade 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#1034]
Got this error after upgrading to version 1.2.511 and starting the daemon 

```
pi@raspberrypi:~ $ flexget daemon start -d
2016-04-14 00:13 INFO     manager                       Database upgrade is required. Attempting now.
2016-04-14 00:13 ERROR    schema                        Failed to upgrade database for plugin input_cache: '\xd8'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/db_schema.py", line 113, in upgrade_wrapper
    new_ver = upgrade_func(current_ver, session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 33, in upgrade
    p = pickle.loads(row['entry'])
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '\xd8'
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 302, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 199, in initialize
    fire_event('manager.upgrade', self)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 103, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/db_schema.py", line 121, in upgrade_wrapper
    manager.shutdown(finish_queue=False)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 850, in shutdown
    raise RuntimeError('Cannot shutdown manager that was never initialized.')
RuntimeError: Cannot shutdown manager that was never initialized.
```

**Comment by stevezau** [comment]
Hmm to solve this it would be useful to get a dump of your database table holding input cache items.  

Have you familiar with SQLite? 

If you join us at http://gitter.im/Flexget/FlexgetI can help

**Comment by liiight** [comment]
His DB: https://www.dropbox.com/s/kuewrukmmixquh5/db-config.sqlite?dl=0

**Comment by maxisme** [comment]
This bug is driving me crazy! Why is there no fix for it? I have tried reinstalling twice and deleting everything with no luck...
