### ISSUE TITLE
Flexget throwing RSS error

### ISSUE THREAD

**Issue by nathanexplosionok** [Flexget/Flexget#1037]
```
2016-04-13 21:44 CRITICAL task Torrentz BUG: Unhandled error in plugin rss: request() got an unexpected keyword argument 'raise_status'
2016-04-13 21:44 CRITICAL manager Torrentz An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.04.13.214428777146.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.510
2016-04-13 21:44 WARNING task Torrentz Aborting task (plugin: rss)
2016-04-13 21:44 CRITICAL task KATtv BUG: Unhandled error in plugin rss: request() got an unexpected keyword argument 'raise_status'
2016-04-13 21:44 CRITICAL manager KATtv An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.04.13.214428821304.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.510
2016-04-13 21:44 WARNING task KATtv Aborting task (plugin: rss)
2016-04-13 21:44 CRITICAL task Extratorrent BUG: Unhandled error in plugin rss: request() got an unexpected keyword argument 'raise_status'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in _runplugin
return method(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in call
return self.func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 142, in wrapped_func
response = func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 124, in wrapped_func
return func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/rss.py", line 235, in on_task_input
response = task.requests.get(config['url'], timeout=60, headers=headers, raise_status=False, auth=auth)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 25, in request
resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
TypeError: request() got an unexpected keyword argument 'raise_status'
```

**Comment by stevezau** [comment]
what version are you on?

**Comment by nathanexplosionok** [comment]
1.2.513

**Comment by cvium** [comment]
This is a problem with the rss and the cfscraper plugin. Easy fix is to stop using the cfscraper plugin. I don't have time to fix it right now. I have opened an issue on the cloudflare-scrape github, but he hasn't answered.
