### ISSUE TITLE
BUG: Unhandled error in plugin transmission: No module named request

### ISSUE THREAD

**Issue by shotfirer** [Flexget/Flexget#1042]
After regular update instead of 1.2.513 i've got 2.0.0b2. Transmission is broken. How to fix this or roll back to 1.2?
```
2016-04-17 15:25 DEBUG    manager                       Config file /root/.flexget/config.yml selected
2016-04-17 15:26 CRITICAL task          RARBG           BUG: Unhandled error in plugin transmission: No module named request
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/FlexGet-2.0.0b2-py2.7.egg/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-2.0.0b2-py2.7.egg/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-2.0.0b2-py2.7.egg/flexget/plugins/plugin_transmission.py", line 35, in new_f
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request
```

**Comment by liiight** [comment]
you got 2.0.0b2 just from `pip install flexget --upgrade`?

**Comment by shotfirer** [comment]
no, from `easy_install -U flexget`

**Comment by liiight** [comment]
@stevezau @gazpachoking ...

**Comment by shotfirer** [comment]
I've manually installed 1.2.513 and Transmission error is gone, but now i'm getting this on every feed:
```
2016-04-17 22:01 VERBOSE  task_queue                    There are 7 tasks to execute. Shutdown will commence when they have completed.
/opt/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/opt/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/opt/local/lib/python2.7/site-packages/requests-2.9.1-py2.7.egg/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

**Comment by liiight** [comment]
Look up this error on Google, answered many times

**Comment by shotfirer** [comment]
It's just a warning, so i think i will ignore it for now. It seems, that it doesn't cause any problems.

**Comment by cvium** [comment]
> may cause certain SSL connections to fail

Not fixing it will come back to bite you in the ass, but suit yourself.

**Comment by stevezau** [comment]
Just pushed a commit that fixes this.

@shotfirer we recommend installing via pip as easy_install does not understand beta versions.

If you woud like to continue using the beta and reporting by any issues please feel free as we need more testers.. more info here: http://discuss.flexget.com/t/flexget-v2-0-0-beta-py3-support-testers/2209/4

```
sudo pip2 install --upgrade --pre flexget
```
