### ISSUE TITLE
entry-list show CLI crash if the command is wrong

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1046]
I made a mistake in the CLI, forgetting the <ENTRY> after the show and I got this error:

```
fmf@kodi:~$ flexget entry-list show -l trakt-series
There is a FlexGet process already running for this config, sending execution there.
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 286, in start
    client.handle_cli(self.args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
TypeError: int() argument must be a string or a number, not 'NoneType'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 79, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 330, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/entry_list.py", line 33, in do_cli
    entry_list_show(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/entry_list.py", line 82, in entry_list_show
    entry = get_entry_by_id(entry_list.id, int(options.entry), session=session)
TypeError: int() argument must be a string or a number, not 'NoneType'

fmf@kodi:~$

```

**Comment by liiight** [comment]
Closed with https://github.com/Flexget/Flexget/compare/5c12a8547d76...33b28938be2b
