### ISSUE TITLE
Crash when Executing beta

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#1047]
```
C:\py3_venv\Scripts>flexget.exe execute
Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\Lib\runpy.py", line 170, in _run_module_as_mai
    "__main__", mod_spec)
  File "c:\program files (x86)\python35-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\py3_venv\Scripts\flexget.exe\__main__.py", line 9, in <module>
  File "c:\py3_venv\lib\site-packages\flexget\__init__.py", line 24, in main
    manager = Manager(args)
  File "c:\py3_venv\lib\site-packages\flexget\manager.py", line 145, in __init__
    self.find_config(create=False)
  File "c:\py3_venv\lib\site-packages\flexget\manager.py", line 473, in find_config
    possible.append(bytes(sys.prefix).decode(sys.getfilesystemencoding()))
TypeError: string argument without an encoding
```

**Comment by stevezau** [comment]
should be fixed now
