### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1053]
Hi all,

I face a list related error :

2016-04-19 10:16 CRITICAL task          watchlist       BUG: Unhandled error in plugin imdb_list: list index out of range
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 209, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 142, in __iter__
    return iter(self.items)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 106, in items
    'title': '%s (%s)' % (row[5], row[11]) if row[11] != '????' else '%s' % row[5],
IndexError: list index out of range

**Comment by liiight** [comment]
Duplicate #1020
