### ISSUE TITLE
BUG: Unhandled error in plugin imdb_list

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1055]
Unhandled error with imdb_list :

```
2016-04-19 17:35 CRITICAL task          watchlist       BUG: Unhandled error in plugin imdb_list: HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /ap/signin?openid.return_to=https%3A%2F%2Fwww.imdb.com%2Fap-signin-handler&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=imdb_mobile_us&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2f1c1e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 209, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 142, in __iter__
    return iter(self.items)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 96, in items
    r = self.session.get('http://www.imdb.com/list/export?list_id=%s&author_id=%s' %
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 46, in session
    self.authenticate()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 51, in authenticate
    r = self._session.get('https://www.imdb.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.imdb.com%2Fap-signin-'
  File "/usr/local/flexget/env/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/requests.py", line 232, in request
    result = requests.Session.request(self, method, url, *args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /ap/signin?openid.return_to=https%3A%2F%2Fwww.imdb.com%2Fap-signin-handler&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=imdb_mobile_us&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2f1c1e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

Here is my conf for the watchlist task : 

```
tasks:
  watchlist:
    imdb_list:
      login: '{{ secrets.imdb.usr }}'
      password: '{{ secrets.imdb.pass }}'
      list: watchlist
    accept_all: yes
    list_add:
      - movie_list: watchlist
```

**Comment by chewy74** [comment]
This has already been reported several times. I believe developers are aware of the bug 
https://github.com/Flexget/Flexget/issues/1020

**Comment by cvium** [comment]
This is not related to #1020.
