### ISSUE TITLE
BUG: Unhandled error in plugin imdb_list: HTTPConnectionPool(host='www.imdb.com', port=80): Read timed out.

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1058]
Hi, 

Unhandled error with imdb_list (not #1020 nor #1055) :

```
2016-04-20 08:17 CRITICAL task          watchlist       BUG: Unhandled error in plugin imdb_list: HTTPConnectionPool(host='www.imdb.com', port=80): Read timed out.
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 209, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 142, in __iter__
    return iter(self.items)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 102, in items
    for row in csv.reader(lines):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/requests/models.py", line 702, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/requests/models.py", line 667, in generate
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='www.imdb.com', port=80): Read timed out.
```

**Comment by crawln45** [comment]
Fixed #1070
