### ISSUE TITLE
python3: sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by Jonybat** [Flexget/Flexget#1059]
Last lines of flexget --debug --debug-db-sessions execute --now --discover-now --no-cache

```
2016-04-20 14:06 DEBUG    entry_list    fill-series-list adding entry <Entry(title=Game of Thrones,state=accepted)> to list trakt-series
2016-04-20 14:06 DEBUG    api_tvdb      fill-series-list Looking up tvdb information for Game of Thrones (2011) 121361
2016-04-20 14:06 WARNING  debug_db_sess fill-series-list Sessions from 2 threads! Transaction 0x7F8C39148A20 opened ('flexget.plugins.api_tvdb', 414, 'lookup_series', 'series = session.query(TVDBSeries).filter(TVDBSeries.id == tvdb_id).first()') Already open one(s): {<sqlalchemy.orm.session.SessionTransaction object at 0x7f8c3914b898>: (1461157586.664333, <sqlalchemy.pool._ConnectionFairy object at 0x7f8c39151550>, 'flexget.plugins.list.entry_list', 95, '_db_list', 'return session.query(EntryListList).filter(EntryListList.name == self.config).first()')}
2016-04-20 14:06 DEBUG    api_tvdb      fill-series-list Series <name=Game of Thrones (2011),tvdb_id=121361> information restored from cache.
2016-04-20 14:06 DEBUG    api_tvdb      fill-series-list Looking up actors for series Game of Thrones
2016-04-20 14:06 DEBUG    api_tvdb      fill-series-list Authenticating to TheTVDB with api_key
2016-04-20 14:06 DEBUG    utils.requests fill-series-list Fetching https://api.thetvdb.com/login
2016-04-20 14:06 DEBUG    util.simple_persistence fill-series-list setting key auth_tokens value {'default': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NjEyNDM5NzMsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDYxMTU3NTczfQ.kth3rXGOWM6b9aSlOQUrHSsYGpkrD2WyhdniSdUV5tADMl87x3icAzVLgvloydjvBQL9_sTWPz2-ZVcS4JAYxJ8Sly08n8pamB9BfXQxwXoL8zEBQcPzIT1GnIK2vbIjA7bvPpvftnicgnlQcpvITt9zBlbvaWwKklz_CO9ZDbYOOTpGVLz-SJGRZc4Xp8y7s4x8uFyd1Ww9w0EfstOAZEq7FVl4B-ZMOIiTwEIosd_DXqnAMF8WNkFe2wPm8k8BWaUPrUCsk0VQZUcwSPPANJfZdzdPb8CDE6JFRdoAEmh9kVOCr3K0Sfl9eolqYVRd4ipVTOy3_Z8sWobvi-Hcmw'}
2016-04-20 14:06 DEBUG    utils.requests fill-series-list Fetching https://api.thetvdb.com/series/121361/actors
2016-04-20 14:06 WARNING  debug_db_sess fill-series-list Transaction 0x7F8C39148A20 closed ('flexget.utils.sqlalchemy_utils', 145, '__exit__', 'self.close()') (open time 11.844423055648804)
2016-04-20 14:06 ERROR    lazy_lookup   fill-series-list Unhandled error in lazy lookup plugin
2016-04-20 14:06 CRITICAL manager       fill-series-list An unexpected crash has occurred. Writing crash report to /home/kurushi/.flexget/crash_report.2016.04.20.140639003115.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.0b8
2016-04-20 14:06 DEBUG    manager       fill-series-list Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flexget/utils/lazy_dict.py", line 38, in __getitem__
    func(self.store)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 116, in lazy_series_actor_lookup
    return self.series_lookup(entry, self.series_actor_map)
  File "/usr/lib/python3.5/site-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/utils/sqlalchemy_utils.py", line 141, in __exit__
    self.commit()
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 184, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 706, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'UPDATE tvdb_series SET actors=? WHERE tvdb_series.id = ?'] [parameters: ('["Ian McElhinney", "Ed Skrein", "Jonathan Pryce", "Alexander Siddig", "Harry Lloyd", "Richard Madden", "Jacob Anderson", "Michelle Fairley", "Isaac Hempstead-Wright", "Alfie Allen", "Pedro Pascal", "Nikolaj Coster-Waldau", "Thomas Sangster", "Sean Bean", "Aidan Gillen", "Natalie Dormer", "Gemma Whelan", "Jason Momoa", "Stephen Dillane", "Jack Gleeson", "Conleth Hill", "Nell Tiger Free", "Rose Leslie", "Nathalie Emmanuel", "Emilia Clarke", "Nonso Anozie", "Paul Kaye", "Carice van Houten", "Gethin Anthony", "Esm\\u00e9 Bianco", "John Bradley", "James Cosmo", "Donald Sumpter", "Kristian Nairn", "Liam Cunningham", "Joe Dempsie", "Natalia Tena", "Iain Glen", "Sophie Turner", "Patrick Malahide", "Peter Vaughan", "Kate Dickie", "Oona Chaplin", "Michiel Huisman", "Gwendoline Christie", "Peter Dinklage", "Kit Harington", "Lena Headey", "Aimee Richardson", "Lino Facioli", "Ron Donachie", "Eugene Simon", "Amrita Acharia", "Hannah Murray", "Charles Dance", "Rory McCann", "Ellie Kendrick", "Mackenzie Crook", "Indira Varma", "Art Parkinson", "Michael McElhatton", "Maisie Williams", "Tom Wlaschiha", "Jerome Flynn", "Kerry Ingram", "Iwan Rheon", "Mark Addy", "Finn Jones", "Sibel Kekilli", "Dean-Charles Chapman", "Kristofer Hivju", "Ciar\\u00e1n Hinds", "Diana Rigg", "Julian Glover", "Tobias Menzies", "Brenock O\'Connor", "Anton Lesser"]', 121361)]
```

**Comment by stevezau** [comment]
Hey,

any chance i can get a copy of your config? I can't re-produce this..

**Comment by Jonybat** [comment]
https://github.com/Jonybat/flexget_config

Also, that error doesn't stop execution, so it doesn't seem to be affecting anything (other than the crash report spam that is)

**Comment by stevezau** [comment]
cool, big config you got there.. good for tests.. i'll take a look at this again tomorrow.

**Comment by stevezau** [comment]
@Jonybat are you still getting db locks on the latest version?

We have made several changes to try limit db locks.

**Comment by Jonybat** [comment]
Just gave it a go and that error does not seem to occur anymore ;)

**Comment by stevezau** [comment]
Closing :-)
