### ISSUE TITLE
list_accept crash and duplicate accepted entries

### ISSUE THREAD

**Issue by dj-nitehawk** [Flexget/Flexget#1063]
just upgraded flexget to the latest version 1.2.517 and upgraded my config.yml to be compatible with it. then ran a `flexget execute --no-cache` after adding a new movie to my imdb watchlist just to test things out.

i got the same movie torrent added to my deluge twice but from two different trackers. 

also got a crash log file in the .flexget directory.

here's the relevant lines from the crash log: 

    2016-04-21 08:18 VERBOSE  task          MOVIES          ACCEPTED: `Three.Brothers.1981.720p.BluRay.x264-GHOULS` by list_accept plugin
    2016-04-21 08:18 VERBOSE  task          MOVIES          ACCEPTED: `Three Brothers 1981 720p BluRay x264-GHOULS` by list_accept plugin
    2016-04-21 08:18 INFO     download      MOVIES          Downloading: Three.Brothers.1981.720p.BluRay.x264-GHOULS
    2016-04-21 08:18 INFO     download      MOVIES          Downloading: Three Brothers 1981 720p BluRay x264-GHOULS
    2016-04-21 08:18 VERBOSE  details       MOVIES          Summary - Accepted: 2 (Rejected: 142 Undecided: 47 Failed: 0)
    2016-04-21 08:18 INFO     deluge        MOVIES          Connecting to daemon at localhost:54321..
    2016-04-21 08:18 INFO     deluge        MOVIES          Connected to daemon at 127.0.0.1:54321..
    2016-04-21 08:18 VERBOSE  deluge        MOVIES          Adding Three.Brothers.1981.720p.BluRay.x264-GHOULS to deluge.
    2016-04-21 08:18 VERBOSE  deluge        MOVIES          Adding Three Brothers 1981 720p BluRay x264-GHOULS to deluge.
    2016-04-21 08:18 INFO     deluge        MOVIES          Three.Brothers.1981.720p.BluRay.x264-GHOULS successfully added to deluge.
    2016-04-21 08:18 INFO     deluge        MOVIES          Three Brothers 1981 720p BluRay x264-GHOULS successfully added to deluge.
    2016-04-21 08:18 INFO     deluge        MOVIES          Connection lost to daemon at localhost:54321 reason: Connection was closed cleanly.
    2016-04-21 08:18 INFO     exec          MOVIES          Stdout:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n...
    2016-04-21 08:18 VERBOSE  list_accept   MOVIES          removing accepted entries from imdb_list - {u'list': u'watchlist', u'login': u'xxxxx', u'password': u'xxxxx', u'force_language': u'en-us'}
    2016-04-21 08:18 CRITICAL task          MOVIES          BUG: Unhandled error in plugin list_accept: 'NoneType' object is not iterable
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
        return method(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
        return self.func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/list_accept.py", line 68, in on_task_learn
        thelist -= task.accepted
      File "/usr/lib/python2.7/_abcoll.py", line 356, in __isub__
        self.discard(value)
      File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 183, in discard
        self._items = [i for i in self._items if self._items and i['imdb_id'] != entry['imdb_id']]
    TypeError: 'NoneType' object is not iterable

my config.yml can be found [here](http://flexget.com/wiki/Cookbook/Users/djnitehawk)

please look in to it guys...

cheers!

**Comment by liiight** [comment]
Duplicate #1025
