### ISSUE TITLE
TVDB sqlite3.IntegrityError

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#1065]
```
2016-04-21 18:02 ERROR    flexget.api                   Exception on /tvdb/series/True Detective/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_restful\__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flask_restplus\resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Flexget\flexget\utils\database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "C:\Flexget\flexget\plugins\api\tvdb_lookup.py", line 84, in get
    result = lookup_series(name=search, session=session)
  File "C:\Flexget\flexget\utils\database.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "C:\Flexget\flexget\plugins\api_tvdb.py", line 446, in lookup_series
    _update_search_strings(series, session, search=name)
  File "C:\Flexget\flexget\plugins\api_tvdb.py", line 378, in _update_search_strings
    func.lower(TVDBSearchResult.search) == name).first()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2634, in first
    ret = list(self[0:1])
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2457, in __getitem__
    return list(res)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2735, in __iter__
    self.session._autoflush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1293, in _autoflush
    self.flush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush
    self._flush(objects)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush
    flush_context.execute()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    uow
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1116, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 447, in do_executemany
    cursor.executemany(statement, parameters)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) column id is not unique [SQL: u'INSERT INTO tvdb_genres (id) VALUES (?)'] [parameters: ((u'Crime',), (u'Drama',), (u'Mystery',))]
```

**Comment by stevezau** [comment]
i can't re-produce this on my box.. are you able to re-produce?

**Comment by stevezau** [comment]
was there a task running at the time? There have been a few reports of this and i'm trying to track down in what situation this happens as i can't reproduce it.

**Comment by Mirgolth** [comment]
These logs were 30 min after the last scheduled task : no task running.

I can reproduce just by browsing series section in the webui. Any  advice to provide you better infos ?

**Comment by stevezau** [comment]
does it happen every time?? I can't seem to make it happen on mine, is it possible to get a copy of your db so i can troubleshoot?

**Comment by Mirgolth** [comment]
I don't have a method to reproduce on demand but it pops up some time to times.
I restarted the deamon with `-L debug --debug-db-sessions` for future times it happens.

My db:
[db-config.zip](https://github.com/Flexget/Flexget/files/236237/db-config.zip)

**Comment by stevezau** [comment]
ok i managed to re-produce the issue.. i suspect it might be due to multiple calls to tvdb api both trying to write to the database at the same time.. i'll need some time to dig into it tho.

**Comment by stevezau** [comment]
actually, this is different to your error @Mirgolth opening your issue back up..

**Comment by liiight** [comment]
Hasn't reproduces in a long time, probably due to me removing the actors call from the default api call.
