### ISSUE TITLE
python3: plugin transmission: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Jonybat** [Flexget/Flexget#1066]
Just realized its not downloading anything because transmission is also crashing.

```
2016-04-22 07:40 CRITICAL task          download-series-rss BUG: Unhandled error in plugin transmission: 'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/plugin_transmission.py", line 298, in on_task_output
    self.add_to_transmission(self.client, task, config)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/plugin_transmission.py", line 402, in add_to_transmission
    filedump = base64.b64encode(f.read()).encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by stevezau** [comment]
are you running from git?

**Comment by Jonybat** [comment]
no, from pip
2.0.0b8

**Comment by stevezau** [comment]
ok, i just pushed a new version. give that a go

**Comment by Jonybat** [comment]
```
2016-04-22 13:33 CRITICAL task          download-series-discover BUG: Unhandled error in plugin transmission: endswith first arg must be bytes or a tuple of bytes, not str
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/plugin_transmission.py", line 298, in on_task_output
    self.add_to_transmission(self.client, task, config)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/plugin_transmission.py", line 403, in add_to_transmission
    r = cli.add_torrent(filedump, 30, **options['add'])
  File "/usr/lib/python3.5/site-packages/transmissionrpc/client.py", line 392, in add_torrent
    if torrent.endswith('.torrent') or torrent.startswith('magnet:'):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by stevezau** [comment]
yeah, fixing that. I made a mistake.

**Comment by stevezau** [comment]
try now.. upgrade

**Comment by Jonybat** [comment]
Same thing :(

Even uninstalled and installed, checked no pyc files in install dir and deleted db

```
2016-04-22 14:20 CRITICAL task          download-series-rss BUG: Unhandled error in plugin transmission: endswith first arg must be bytes or a tuple of bytes, not str
2016-04-22 14:20 CRITICAL manager       download-series-rss An unexpected crash has occurred. Writing crash report to /home/kurushi/.flexget/crash_report.2016.04.22.142032030564.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.0b11
2016-04-22 14:20 DEBUG    manager       download-series-rss Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/plugin_transmission.py", line 298, in on_task_output
    self.add_to_transmission(self.client, task, config)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/plugin_transmission.py", line 403, in add_to_transmission
    r = cli.add_torrent(filedump, 30, **options['add'])
  File "/usr/lib/python3.5/site-packages/transmissionrpc/client.py", line 392, in add_torrent
    if torrent.endswith('.torrent') or torrent.startswith('magnet:'):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by stevezau** [comment]
i'll take another look, don't have transmission to check..

feel free to join us at http://github.com/Flexget/Flexget

**Comment by stevezau** [comment]
hmm, what version are you on?

**Comment by Jonybat** [comment]
it says there in the log
2.0.0b11

**Comment by stevezau** [comment]
Hmm, i think this might be a bug with transmissionrpc

https://bitbucket.org/blueluna/transmissionrpc/issues/81/py3-typeerror-endswith-first-arg-must-be

**Comment by gazpachoking** [comment]
I took a peek, looks like transmissionrpc is expecting text for that parameter, no mater whether it's a filename or a dump. That doesn't really make sense to me.... but it does explain the behavior.
