### ISSUE TITLE
python3: can't execute flexget

### ISSUE THREAD

**Issue by Bruny07** [Flexget/Flexget#1072]
OS: Windows 10 1511
py version: 3.5.1
flexget version: 2.0.0b15

When I try to execute flexget I get the following errors

```
C:\Users\Bruno>flexget -V
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.5.3 (c:\python35\lib\site-packages), Requirement.parse('python-dateutil<2.5.2'), {'guessit'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\Scripts\flexget-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2927, in <module>
    @_call_aside
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python35\lib\site-packages\pkg_resources\__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.5.3 (c:\python35\lib\site-packages), Requirement.parse('python-dateutil<2.5.2'), {'guessit'})
```

**Comment by stevezau** [comment]
This is due to guessit (third party lib) not allowing the latest version of python-dateuitl

https://github.com/guessit-io/guessit/issues/291

**Comment by stevezau** [comment]
please try again,

**Comment by Bruny07** [comment]
All good on 2.0.2. Thank you for the fix

**Comment by Toilal** [comment]
I just released guessit without any constraint on python-dateutil. (guessit>=2.1.0)
