### ISSUE TITLE
BUG: Unhandled error in plugin discover: search() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by thalamus** [Flexget/Flexget#1074]
The when using the rarbg discover plugin, a TypeError is being thrown which is resulting in a crash since I upgraded to Flexget 2.0.1 with Python 3.5:

```
2016-04-24 08:03 DEBUG    manager                       Figuring out config load paths
2016-04-24 08:03 DEBUG    manager                       Found config: /home/thalamus/.flexget/config.yml
2016-04-24 08:03 DEBUG    manager                       Config file /home/thalamus/.flexget/config.yml selected
2016-04-24 08:03 VERBOSE  task_queue                    There are 2 tasks to execute. Shutdown will commence when they have completed.
2016-04-24 08:03 VERBOSE  details       monitor feeds   Produced 108 entries.
2016-04-24 08:03 VERBOSE  details       monitor feeds   Summary - Accepted: 0 (Rejected: 0 Undecided: 108 Failed: 0)
2016-04-24 08:03 VERBOSE  transmission  monitor feeds   Torrent "Harry Enfields Television Programme S1": status: "stopped" - ratio: 3.6553 -  date added: 2015-08-26 15:33:10 - date done: 1970-01-01 01:00:00
2016-04-24 08:03 VERBOSE  transmission  monitor feeds   Torrent "Harry Enfield's TV Programme - Series 2": status: "stopped" - ratio: 2.6841 -  date added: 2015-08-26 15:33:10 - date done: 1970-01-01 01:00:00
2016-04-24 08:03 VERBOSE  transmission  monitor feeds   Torrent "Harry Enfield TV program series 2 part 1.avi": status: "stopped" - ratio: 2.651 -  date added: 2015-08-26 15:33:10 - date done: 1970-01-01 01:00:00
2016-04-24 08:03 VERBOSE  discover      search series   Discovering 12 titles ...
2016-04-24 08:03 INFO     task          search series   Plugin discover has requested task to be ran again after execution has completed.
2016-04-24 08:03 VERBOSE  discover      search series   Searching for `Top Gear S22E10` with plugin `torrentz` (1 of 9)
2016-04-24 08:03 VERBOSE  discover      search series   Searching for `Top Gear S22E10` with plugin `rarbg` (1 of 9)
2016-04-24 08:03 WARNING  discover      search series   Search plugin rarbg does not support latest search api.
2016-04-24 08:03 CRITICAL task          search series   BUG: Unhandled error in plugin discover: search() missing 1 required positional argument: 'config'
Traceback (most recent call last):
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 144, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugin.py", line 122, in wrapped_func
    return func(*args, **kwargs)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugins/search/rarbg.py", line 120, in search
    query = normalize_scene(search_string)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/utils/search.py", line 55, in normalize_scene
    normalize('NFKD', text).encode('ASCII', 'ignore'))
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 277, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 148, in execute_searches
    search_results = search.search(entry, plugin_config)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugin.py", line 122, in wrapped_func
    return func(*args, **kwargs)
TypeError: search() missing 1 required positional argument: 'config'
```

**Comment by gazpachoking** [comment]
Looks like somewhere is setting the `search_strings` field to contain a bytestring. We'll need to suss out where that is.

**Comment by gazpachoking** [comment]
Looks like this could be the culprit: https://github.com/Flexget/Flexget/blob/787d5f75a7ae98dfe09cda2d43f08c1cdbb858df/flexget/plugins/search/rss.py#L24

**Comment by stevezau** [comment]
The traceback shows it's coming from rarbg.py though?

**Comment by gazpachoking** [comment]
> The traceback shows it's coming from rarbg.py though?

Yeah, but look what it's calling. It's calling a utility function that requires text using the contents from the entries 'search_strings' field. The actual bug is the plugin that populated the search_strings with bytes. A quick search reveals search_rss is the likely culprit.

**Comment by gazpachoking** [comment]
I take it back about search_rss being the likely culprit, that's not storing anything to the entry.

**Comment by gazpachoking** [comment]
@thalamus What's the config for this task?

**Comment by thalamus** [comment]
Here we are, it's nothing too exciting. I've tried with different parameters for the rarbg search task, but it still crashes.

```
templates:
  tv:
    transmission:
      addpaused: Yes
    clean_transmission:
      min_ratio: 1.50
    pushbullet:
      apikey: xxxxxxxxxxxxxx
      device: xxxxxxxxxxxxxx
      channel: xxxxxxxxxxxxx
          
    series:
      settings:
        shows:
          timeframe: 24 hours
          target: 720p hdtv+
          propers: 24 hours
          set:
            path: /mnt/storage/Torrents/TV/{{series_name}}/
            exists_series: /mnt/storage/Torrents/
            allow_different_qualities: better
            ratio: 1.50

      shows:
        - CSI Cyber:
            exact: yes
        - Chicago Fire
        - Chicago PD
        - Chicago Med
        - Great British Railway Journeys:
            tracking: no
        - Great Continental Railway Journeys:
            tracking: no
        - Homeland
        - Air Crash Investigation
        - Top Gear:
            exact: yes
        - QI
        - Hannibal
        - Mr. Robot

tasks:
  monitor feeds:
    inputs:
      - rss:
          url: http://showrss.info/feeds/all.rss
          all_entries: no
      - rss:
          url: http://kat.cr/usearch/DIMENSION%20category%3Atv/?rss=1
          all_entries: no
      - rss:
          url: http://kat.cr/usearch/ettv%20category:tv/?rss=1
          all_entries: no
    template: tv
  
  search series:
    template: tv
    discover:
      what:
        - emit_series: yes
      from:
        - torrentz: verified
        - rarbg:
            category: [41, 18]
            use_tvdb: true
        - kat:
            category: tv
            verified: yes
      interval: 30 minutes
```

**Comment by cvium** [comment]
Does it crash if you don't use `use_tvdb`?

**Comment by thalamus** [comment]
Nope, as I said, I tried various parameters for the rarbg task and it crashed regardless.

**Comment by stevezau** [comment]
@thalamus is this still an issue for you? want to check before i look into it.

**Comment by thalamus** [comment]
Rarbg is still broken - different error now though:

`thalamus@ulysses ~ % cat /home/thalamus/.flexget/crash_report.2016.07.09.093917654711.log
2016-07-09 09:39 DEBUG    manager                       Figuring out config load paths
2016-07-09 09:39 DEBUG    manager                       Found config: /home/thalamus/.flexget/config.yml
2016-07-09 09:39 DEBUG    manager                       Config file /home/thalamus/.flexget/config.yml selected
2016-07-09 09:39 VERBOSE  task_queue                    There are 2 tasks to execute. Shutdown will commence when they have completed.
2016-07-09 09:39 VERBOSE  discover      search series   Discovering 12 titles ...
2016-07-09 09:39 INFO     task          search series   Plugin next_series_episodes has requested task to be ran again after execution has completed. Reason: Look for next season
2016-07-09 09:39 VERBOSE  discover      search series   Discover interval of 30 minutes not met for 12 entries. Use --discover-now to override.
2016-07-09 09:39 VERBOSE  details       search series   Task didn't produce any entries.
2016-07-09 09:39 VERBOSE  details       search series   Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)
2016-07-09 09:39 INFO     task          search series   Rerunning the task in case better resolution can be achieved.
2016-07-09 09:39 VERBOSE  discover      search series   Discovering 10 titles ...
2016-07-09 09:39 VERBOSE  discover      search series   Searching for `QI S14E01` with plugin `torrentz` (1 of 6)
2016-07-09 09:39 VERBOSE  discover      search series   Searching for `QI S14E01` with plugin `rarbg` (1 of 6)
2016-07-09 09:39 CRITICAL task          search series   BUG: Unhandled error in plugin discover: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 272, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 143, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugin.py", line 120, in wrapped_func
    return func(*args, **kwargs)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/plugins/search/rarbg.py", line 120, in search
    query = normalize_scene(search_string)
  File "/home/thalamus/.local/lib/python3.5/site-packages/flexget/utils/search.py", line 55, in normalize_scene
    normalize('NFKD', text).encode('ASCII', 'ignore'))
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
thalamus@ulysses ~ % 
`

**Comment by cvium** [comment]
Looks like this issue (and the rarbg one) has been fixed. Please open a new issue if it happens again.
