### ISSUE TITLE
Swagger API docs error

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#1075]
New version of FlexGet is unable to open the Swagger API documentations (ip:port/api).

```
2016-04-24 12:10 ERROR    flexget.api                   Exception on /swagger.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 583, in get
    return self.api.__schema__
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 73, in __get__
    value = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 327, in __schema__
    self._schema = Swagger(self).as_dict()
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 224, in as_dict
    paths[extract_path(url)] = self.serialize_resource(ns, resource, url)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 346, in serialize_resource
    operations[method] = self.serialize_operation(doc, method)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 352, in serialize_operation
    'responses': self.responses_for(doc, method) or None,
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 430, in responses_for
    description, model = (response, None) if isinstance(response, string_types) else response
TypeError: 'NoneType' object is not iterable
```

UI and it's endpoints are working for your information.

**Comment by liiight** [comment]
Can't believe we missed this one @stevezau :laughing:
