### ISSUE TITLE
Subliminal not working: "AttributeError: 'module' object has no attribute 'core'"

### ISSUE THREAD

**Issue by niawag** [Flexget/Flexget#1082]
Hi, I'm running flexget 2.0.1, with subliminal 1.0.1 as stated in the wiki and I'm facing this issue:
```
2016-04-24 20:43 VERBOSE  details       subtitles_h     Produced 1 entries.
2016-04-24 20:43 VERBOSE  task          subtitles_h     ACCEPTED: `my_show_name_S06E66` by accept_all plugin
2016-04-24 20:43 VERBOSE  details       subtitles_h     Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2016-04-24 20:43 CRITICAL task          subtitles_h     BUG: Unhandled error in plugin subliminal: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/output/subtitles_subliminal.py", line 125, in on_task_output
    existing_subtitles = set(subliminal.core.search_external_subtitles(entry['location']).values())
AttributeError: 'module' object has no attribute 'core'
```
I tried with different subliminal version (latest 1.1.1 and dev 2.0rc1) without any luck, I'd be glad to provide more information if needed.

**Comment by cvium** [comment]
The rc version should work.

**Comment by niawag** [comment]
Hi and thanks for your answer, I've tried it again witout any luck, here is my config:
```
  subtitles_h:     
    template: no_global
    disable: [retry_failed]
    seen: local
    subtitle_queue: emit
    accept_all: yes
    subliminal:
      exact_match: no
      languages:
        - fr
      providers: 
        - addic7ed 
        - opensubtitles 
        - podnapisi 
        - tvsubtitles 
        - thesubdb
```
And here is the resulting crash:
```
2016-04-24 20:54 VERBOSE  details       subtitles_h     Produced 1 entries.
2016-04-24 20:54 VERBOSE  task          subtitles_h     ACCEPTED: `my_show.S01E08` by accept_all plugin
2016-04-24 20:54 VERBOSE  details       subtitles_h     Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2016-04-24 20:54 CRITICAL task          subtitles_h     BUG: Unhandled error in plugin subliminal: 'module' object has no attribute 'core'
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/output/subtitles_subliminal.py", line 125, in on_task_output
    existing_subtitles = set(subliminal.core.search_external_subtitles(entry['location']).values())
AttributeError: 'module' object has no attribute 'core'
```
Do you have an idea of what could cause that?

**Comment by cvium** [comment]
Well, try uninstalling subliminal and reinstall it. Also, are you running flexget as daemon?

**Comment by stevezau** [comment]
Looks like you are running in a virutal env.

make sure you installed subliminal in the venv. 

/usr/local/flexget/env/pip install --upgrade subliminal

re-open the ticket if it's still an issue

**Comment by niawag** [comment]
@cvium yes, I'm running flexget as daemon and subliminal is returning the right thing:

> /volume1/@appstore/flexget/env/bin]>subliminal --version
> subliminal, version 2.0.rc1

@stevezau I'm not running flexget in a virtual environnement, I'm on a Synology NAS and I installed it using pip (pip install flexget)

Well, I don't know what happened since yesterday but I didn't touch anything and subliminal is not crashing flexget anymore so... ticket can be closed!

Thanks a lot for your help
