### ISSUE TITLE
Bug with plugin handlers

### ISSUE THREAD

**Issue by mstrandbo** [Flexget/Flexget#1085]
After I updated to v2 from v1.2-something, I keep getting these errors

______________________________ Task: MOVIES ______________________________
Task 'MOVIES' was aborted because: BUG: Unhandled error in plugin inputs: must be unicode, not str

**Comment by liiight** [comment]
Please paste entirety of the log

**Comment by mstrandbo** [comment]
Sorry, didn't expect you to be this quick;
2016-04-25 01:30 CRITICAL task          MOVIES          BUG: Unhandled error in plugin inputs: must be unicode, not str
2016-04-25 01:30 CRITICAL manager       MOVIES          An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.04.25.013015767266.log. Please verify you are running the latest version of flexget by us$
2016-04-25 01:30 WARNING  task          MOVIES          Aborting task (plugin: inputs)

from crash_log:
2016-04-25 03:00 CRITICAL rss           SERIES          Received content is HTML page, not an RSS feed
2016-04-25 03:00 CRITICAL task          SERIES          BUG: Unhandled error in plugin inputs: must be unicode, not str
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/inputs.py", line 50, in on_task_input
    result = method(task, input_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 164, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 123, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/rss.py", line 311, in on_task_input
    self.process_invalid_content(task, content, config['url'])
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/rss.py", line 180, in process_invalid_content
    f.write(data)
TypeError: must be unicode, not str

Sometimes I do get an error when fetching an rss-feed, which then presents me with a html-page. Next time flexget runs, it's fixed.. It depends on the load on the remote server it appears.

**Comment by stevezau** [comment]
just checking, do you have ascii: true in your rss config?

**Comment by mstrandbo** [comment]
No, I do not have any such setting.

**Comment by stevezau** [comment]
ok, i think i know where the issue is but i need to confirm the rss url you are using? is it just a standard rss feed over http?

**Comment by mstrandbo** [comment]
I'd say quite standard. It's using https and a passkey

**Comment by stevezau** [comment]
That should of fixed it, please re-open if not.
