### ISSUE TITLE
Ascii error in imdb_list

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1087]
Log:
```
2016-04-25 14:16 DEBUG    scheduler                     task finished executing: watchlist
2016-04-25 14:16 DEBUG    manager       watchlist       Not running db cleanup, last run 2016-04-18 18:17:04
2016-04-25 14:16 DEBUG    task          watchlist       executing watchlist
2016-04-25 14:16 DEBUG    utils.requests watchlist       Fetching https://www.imdb.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.imdb.com%2Fap-signin-handler&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=imdb_mobile_us&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
2016-04-25 14:16 VERBOSE  utils.requests watchlist       Waiting 3.76 seconds until next request to imdb.com
2016-04-25 14:16 DEBUG    utils.requests watchlist       Fetching https://www.imdb.com/ap/signin
2016-04-25 14:16 VERBOSE  utils.requests watchlist       Waiting 4.22 seconds until next request to imdb.com
2016-04-25 14:16 DEBUG    utils.requests watchlist       Fetching http://www.imdb.com/profile
2016-04-25 14:16 VERBOSE  utils.requests watchlist       Waiting 4.51 seconds until next request to imdb.com
2016-04-25 14:16 DEBUG    utils.requests watchlist       Fetching http://www.imdb.com/list/_ajax/watchlist_has
2016-04-25 14:16 VERBOSE  utils.requests watchlist       Waiting 4.62 seconds until next request to imdb.com
2016-04-25 14:16 DEBUG    utils.requests watchlist       Fetching http://www.imdb.com/list/export?list_id=ls000306550&author_id=ur1345105
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 1, tt1321870, Tue Jul  3 02:44:29 2012, Tue Jul  3 02:44:29 2012, , Gangster Squad, Feature Film, Ruben Fleischer, , 6.7, 113, 2013, action, crime, drama, thriller, 170997, 2013-01-07, http://www.imdb.com/title/tt1321870/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 2, tt1212419, Thu Jul  5 05:40:53 2012, Thu Jul  5 05:40:53 2012, , Hereafter, Feature Film, Clint Eastwood, , 6.5, 129, 2010, drama, fantasy, 79283, 2010-09-12, http://www.imdb.com/title/tt1212419/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 3, tt1480656, Thu Jul  5 05:45:19 2012, Thu Jul  5 05:45:19 2012, , Cosmopolis, Feature Film, David Cronenberg, , 5.0, 109, 2012, drama, 37149, 2012-05-25, http://www.imdb.com/title/tt1480656/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 4, tt1446192, Thu Jul  5 05:49:28 2012, Thu Jul  5 05:49:28 2012, , Rise of the Guardians, Feature Film, Peter Ramsey, , 7.3, 97, 2012, animation, adventure, family, fantasy, 120274, 2012-10-10, http://www.imdb.com/title/tt1446192/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 5, tt1623205, Sun Jul 15 10:48:18 2012, Sun Jul 15 10:48:18 2012, , Oz the Great and Powerful, Feature Film, Sam Raimi, , 6.4, 130, 2013, adventure, family, fantasy, 172820, 2013-02-14, http://www.imdb.com/title/tt1623205/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 6, tt2223842, Tue Jul 24 13:38:44 2012, Tue Jul 24 13:38:44 2012, , The Prototype, Feature Film, Andrew Will, , , , ????, action, sci_fi, , , http://www.imdb.com/title/tt2223842/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 7, tt2097307, Tue Aug  7 12:44:36 2012, Tue Aug  7 12:44:36 2012, , Hit and Run, Feature Film, David Palmer, Dax Shepard, , 6.1, 100, 2012, action, comedy, romance, 28838, 2012-08-02, http://www.imdb.com/title/tt2097307/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 8, tt1905041, Tue May  7 23:20:16 2013, Tue May  7 23:20:16 2013, , Fast & Furious 6, Feature Film, Justin Lin, , 7.2, 130, 2013, action, crime, thriller, 294713, 2013-05-07, http://www.imdb.com/title/tt1905041/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 9, tt1583421, Sun Jul 28 04:40:55 2013, Sun Jul 28 04:40:55 2013, , G.I. Joe: Retaliation, Feature Film, Jon M. Chu, , 5.8, 110, 2013, action, adventure, sci_fi, thriller, 143440, 2013-03-11, http://www.imdb.com/title/tt1583421/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 10, tt2167202, Wed Aug 21 14:05:15 2013, Wed Aug 21 14:05:15 2013, , Getaway, Feature Film, Courtney Solomon, , 4.4, 90, 2013, action, crime, thriller, 19171, 2013-08-26, http://www.imdb.com/title/tt2167202/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 11, tt1821694, Wed Aug 21 14:05:50 2013, Wed Aug 21 14:05:50 2013, , RED 2, Feature Film, Dean Parisot, , 6.7, 116, 2013, action, comedy, crime, thriller, 121564, 2013-07-18, http://www.imdb.com/title/tt1821694/
2016-04-25 14:16 DEBUG    imdb_list     watchlist       parsing line from csv: 12, tt1253863, Wed Aug 21 14:09:03 2013, Wed Aug 21 14:09:03 2013, , 300: Rise of an Empire, Feature Film, Noam Murro, , 6.2, 102, 2014, action, drama, fantasy, war, 219116, 2014-03-04, http://www.imdb.com/title/tt1253863/
2016-04-25 14:16 CRITICAL task          watchlist       BUG: Unhandled error in plugin imdb_list: 'ascii' codec can't encode character u'\xe0' in position 81: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 222, in on_task_input
    return list(self.get_list(config))
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 155, in __iter__
    return iter(self.items)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 112, in items
    for row in csv.reader(lines):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 81: ordinal not in range(128)
```

The task:
```
tasks:
  watchlist:
    priority: 1
    imdb_list:
      login: '{{ secrets.imdb.usr }}'
      password: '{{ secrets.imdb.pass }}'
      list: watchlist
    accept_all: yes
    list_add:
      - movie_list: watchlist
```

**Comment by gazpachoking** [comment]
Looks like csv module needs bytes read in on python 2, and text on python 3. We'll probably have to add a bit of branching to handle this properly. We'll also need to decode the return from csv reader on python 2.

**Comment by liiight** [comment]
Couldn't we just split(',')? Isn't that all csv is?

**Comment by gazpachoking** [comment]
@liiight There's escaping stuff to worry about
