### ISSUE TITLE
flexget.api : OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1095]
Browsing the webui causes these errors on the api:
```
2016-04-26 07:50 ERROR    flexget.api                   Exception on /tvdb/series/The Last Ship/ [GET]
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask_restplus/resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api/tvdb_lookup.py", line 85, in get
    result = lookup_series(name=search, session=session)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tvdb.py", line 446, in lookup_series
    _update_search_strings(series, session, search=name)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tvdb.py", line 378, in _update_search_strings
    func.lower(TVDBSearchResult.search) == name).first()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2735, in __iter__
    self.session._autoflush()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO tvdb_series (id, last_updated, expired, name, language, rating, status, runtime, airs_time, airs_dayofweek, content_rating, network, overview, imdb_id, zap2it_id, banner, first_aired, aliases, actors, posters) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (269533, 1461605396, 0, u'The Last Ship', u'en', 8.5, u'Continuing', 45, u'9:00 PM', u'Sunday', u'TV-14', u'TNT', u"Their mission is simple: Find a cure. Stop the virus. Save the world. When a global pandemic wipes out eighty percent of the planet's population, the crew of a lone naval destroyer must find a way to pull humanity from the brink of extinction. Executive Producer Michael Bay presents The Last Ship, starring Eric Dane, Rhona Mitra and Adam Baldwin.", u'tt2402207', u'EP01741727', u'graphical/269533-g.jpg', '2014-06-22 00:00:00.000000', u'[]', None, None)]
2016-04-26 07:50 ERROR    flexget.api                   Exception on /tvdb/series/True Detective/ [GET]
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask_restplus/resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api/tvdb_lookup.py", line 85, in get
    result = lookup_series(name=search, session=session)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tvdb.py", line 446, in lookup_series
    _update_search_strings(series, session, search=name)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tvdb.py", line 378, in _update_search_strings
    func.lower(TVDBSearchResult.search) == name).first()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2735, in __iter__
    self.session._autoflush()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO tvdb_series (id, last_updated, expired, name, language, rating, status, runtime, airs_time, airs_dayofweek, content_rating, network, overview, imdb_id, zap2it_id, banner, first_aired, aliases, actors, posters) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (270633, 1461390623, 0, u'True Detective', u'en', 9.0999999999999996, u'Continuing', 60, u'9:00 PM', u'Sunday', u'TV-MA', u'HBO', u'An anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.', u'tt2356777', u'SH01814225', u'graphical/270633-g7.jpg', '2014-01-12 00:00:00.000000', u'[]', None, None)]
2016-04-26 07:50 ERROR    flexget.api                   Exception on /tvdb/series/Suits/ [GET]
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flask_restplus/resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api/tvdb_lookup.py", line 85, in get
    result = lookup_series(name=search, session=session)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tvdb.py", line 446, in lookup_series
    _update_search_strings(series, session, search=name)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tvdb.py", line 378, in _update_search_strings
    func.lower(TVDBSearchResult.search) == name).first()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2735, in __iter__
    self.session._autoflush()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO tvdb_series (id, last_updated, expired, name, language, rating, status, runtime, airs_time, airs_dayofweek, content_rating, network, overview, imdb_id, zap2it_id, banner, first_aired, aliases, actors, posters) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (247808, 1461481941, 0, u'Suits', u'en', 8.9000000000000004, u'Continuing', 45, u'10:00 PM', u'Wednesday', u'TV-14', u'USA Network', u"Suits follows college drop-out Mike Ross, who accidentally lands a job with one of New York's best legal closers, Harvey Specter. They soon become a winning team with Mike's raw talent and photographic memory, and Mike soon reminds Harvey of why he went into the field of law in the first place.", u'tt1632701', u'EP01407658', u'graphical/247808-g9.jpg', '2011-06-23 00:00:00.000000', u'[]', None, None)]
```

**Comment by stevezau** [comment]
duplicate #1065

**Comment by Mirgolth** [comment]
Reproduced this morning with  `-L debug --debug-db-sessions`. I just went on the series tab on the webui. It seems to happen when series are marked as expired and need a tvdb refresh.

Is at line 513 :
[flexget.log.error.zip](https://github.com/Flexget/Flexget/files/237950/flexget.log.error.zip)

**Comment by liiight** [comment]
This should be resolved now. Please test.
