### ISSUE TITLE
movie-list add (CLI and API)

### ISSUE THREAD

**Issue by subzero79** [Flexget/Flexget#1116]
This is a command trying to add a movie to the movie-list

```
flexget movie-list add  -i tt3882082 -l imdblist -t "The Boy"
There is a FlexGet process already running for this config, sending execution there.
Adding movie with title The Boy to list imdblist
Adding identifiers [None] to movie The Boy
Traceback (most recent call last):
  File "/usr/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 38, in main
    manager.start()
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 292, in start
    client.handle_cli(self.args)
  File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
AttributeError: 'NoneType' object has no attribute 'items'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python2.7/site-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/lib/python2.7/site-packages/flexget/ipc.py", line 80, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 336, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/cli/movie_list.py", line 35, in do_cli
    movie_list_add(options)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/cli/movie_list.py", line 96, in movie_list_add
    movie_exist.ids = get_db_movie_identifiers(identifier_list=identifiers, session=session)
  File "/usr/lib/python2.7/site-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/movie_list.py", line 273, in get_db_movie_identifiers
    for key, value in identifier.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

The api responds 

```
{
  "message": "The browser (or proxy) sent a request that this server could not understand."
}
```

With this payload

```
{
  "movie_identifiers": [
    {'imdb_id':'tt3882082'}
  ],
  "movie_name": "The Boy",
  "movie_year": 2016,
  "original_url": "http://www.imdb.com/title/tt3882082/?ref_=nv_sr_2",
  "title": "The Boy"
}
```

Python version is 2.7.11 and flexget version 2.0.8

**Comment by subzero79** [comment]
Sorry for the confusion it should be 

flexg movie-list add  -i imdb_id="tt3882082" -l imdblist -t "The Boy

**Comment by liiight** [comment]
Yeah, we should. Definitely a bug

**Comment by liiight** [comment]
Fixed for CLI. Your API request failed because JSON doesn't like single quotes.
