### ISSUE TITLE
Exception on discover rerun "'NoneType' object has no attribute '__getitem__'" 

### ISSUE THREAD

**Issue by henriksjodahl** [Flexget/Flexget#1118]
Every time, when discover plugin do a rerun, flexget crashes with this error. 

I've had this issue for a while, just hadn't had the time to deal with it. Updated flexget yesterday, still there. 

```
2016-05-01 09:00 VERBOSE  details       Series-GetFollowing Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)
2016-05-01 09:00 INFO     task          Series-GetFollowing Rerunning the task in case better resolution can be achieved.
2016-05-01 09:00 VERBOSE  discover      Series-GetFollowing Discovering 31 titles ...
2016-05-01 09:00 CRITICAL task          Series-GetFollowing BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    def __call__(self, *args, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 274, in on_task_input
    estimation_mode = config['release_estimations']
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 190, in estimated
    result = []
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    ):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 51, in estimate
    log.debug('{0}: {1}'.format(k, v))
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    if kwargs.get('session'):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 517, in episode_lookup
    
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 464, in series_lookup
    log.debug('forcing cache for series {0}'.format(series.name))
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 412, in get_show
    return show_main_info(maze_id, embed=embed)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 464, in _get_show_by_search
    country = None
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 441, in _get_show_with_qualifiers
    shows = get_show_list(show_name)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by liiight** [comment]
What version of pytvmaze you have installed?

**Comment by henriksjodahl** [comment]
```
pip2 show pytvmaze
---
Metadata-Version: 2.0
Name: pytvmaze
Version: 1.5.1
```

**Comment by iruyanka** [comment]
```
2016-05-03 13:24 ERROR    lazy_lookup   TVshows         Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/lazy_dict.py", line 38, in __getitem__
    func(self.store)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/metainfo/tvmaze_lookup.py", line 131, in lazy_series_lookup
    series = series_lookup(**lookupargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tvmaze.py", line 471, in series_lookup
    return series
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tvmaze.py", line 429, in prepare_lookup_for_pytvmaze
    prepared_params['tvrage_id'] = lookup_params.get('tvrage_id') or lookup_params.get('trakt_series_tvrage_id')
UnicodeEncodeError: 'ascii' codec can't encode character u'\ub610' in position 0: ordinal not in range(128)
```

**Comment by liiight** [comment]
@iruyanka please open a new issue with that error

**Comment by iruyanka** [comment]
@liiight https://github.com/Flexget/Flexget/issues/1097

but closed.

**Comment by liiight** [comment]
If it still exist on latest version reopen that issue please.
