### ISSUE TITLE
SceneAccess: '<class 'bs4.element.Tag'>' object has no attribute '__next__'

### ISSUE THREAD

**Issue by qvazzler** [Flexget/Flexget#1119]
**Version**
```
flexget -V
2.0.8
You are on the latest release.
```

**config.yml snippet**
```
  get_series:
    priority: 6
    #verify_ssl_certificates: no
    configure_series:
      settings:
        #quality: 720p hdtv+
        timeframe: 6 hours
        target: 720p hdtv
        identified_by: ep
        exact: yes
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          account: '{{ secrets.trakt.account }}'
          list: 1-b-shows-b-follow
          type: shows
          #strip_dates: yes
        #listdir:
          #- /volume1/Disk1/Library/TV Shows
    #template: download-show
    template:
      - get_series_standards
      - download-show
```

**template snippets**
```
  get_series_standards:
    domain_delay:
      sceneaccess.eu: 8 seconds
      sceneaccess.org: 8 seconds
    #verify_ssl_certificates: no
    content_size:
      max: 5000
      min: 60
    regexp:
      reject:
        - FASTSUB #French
        - VOSTFR #French
        - Subtitulado #Spanish
        - Special-Wicked #Special trailer episodes from Once Upon a Time
        - Magazine #No magazines on Arrow, thank you.
        - NLsubs
    content_filter:
      reject:
        - '*.avi' #Uhgg Jak!
```

```
  download-show:
    #verify_ssl_certificates: no
    discover:
      what:
        - emit_series: yes
            #from_start: yes backfill: no
      from:
        - sceneaccess:
            username: '{{ secrets.sceneaccess.username }}'
            password: '{{ secrets.sceneaccess.password }}'
            gravity_multiplier: 200
            category:
              browse:
                - TV/HD-x264
      release_estimations: strict #only download those with air dates
    set:
      content_filename: "{{ series_name }} - {{ series_id }} ({{ quality|upper }})"
    template:
      - transmit-series
      #- transmit-manual-download
```

**crash_report**
```
2016-05-01 13:14 VERBOSE  discover      get_series      No search results for `Suits (2011) S01E01`
2016-05-01 13:14 VERBOSE  discover      get_series      Searching for `Marvel's Daredevil (2015) S02E03` with plugin `sceneaccess` (5 of 10)
2016-05-01 13:14 VERBOSE  utils.requests get_series      Waiting 7.16 seconds until next request to sceneaccess.eu
2016-05-01 13:14 VERBOSE  utils.requests get_series      Waiting 4.93 seconds until next request to sceneaccess.eu
2016-05-01 13:14 VERBOSE  utils.requests get_series      Waiting 6.71 seconds until next request to sceneaccess.eu
2016-05-01 13:14 VERBOSE  utils.requests get_series      Waiting 7.22 seconds until next request to sceneaccess.eu
2016-05-01 13:14 VERBOSE  discover      get_series      No search results for `Marvel's Daredevil (2015) S02E03`
2016-05-01 13:14 VERBOSE  discover      get_series      Searching for `Marvel's Agents of S.H.I.E.L.D. (2013) S03E18` with plugin `sceneaccess` (6 of 10)
2016-05-01 13:14 VERBOSE  utils.requests get_series      Waiting 6.54 seconds until next request to sceneaccess.eu
2016-05-01 13:15 VERBOSE  utils.requests get_series      Waiting 5.67 seconds until next request to sceneaccess.eu
2016-05-01 13:15 VERBOSE  utils.requests get_series      Waiting 5.19 seconds until next request to sceneaccess.eu
2016-05-01 13:15 CRITICAL task          get_series      BUG: Unhandled error in plugin discover: '<class 'bs4.element.Tag'>' object has no attribute '__next__'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 277, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 144, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 120, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/search/sceneaccess.py", line 281, in search
    size = result.find('td', attrs={'class': 'ttr_size'}).__next__
  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 1003, in __getattr__
    "'%s' object has no attribute '%s'" % (self.__class__, tag))
AttributeError: '<class 'bs4.element.Tag'>' object has no attribute '__next__'
```

**Comment by cvium** [comment]
This has nothing to do with discover. The problem is in `sceneaccess` - https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/search/sceneaccess.py#L281

I don't have access to sceneaccess, so you're on your own here.

**Comment by stevezau** [comment]
not sure why __next__ was used.. but anyway that commit should fix it.. let me know.

**Comment by qvazzler** [comment]
@stevezau works! Thanks!
