### ISSUE TITLE
Bug: make_html not working - TypeError: must be unicode, not str

### ISSUE THREAD

**Issue by msj33** [Flexget/Flexget#1123]
Make_HTML have been broken for some time locally, but with upgrade to 2.0.8, it now completely fails to run:

2016-05-01 21:03 VERBOSE  make_html     Film            Writing output html to /home/admin/flexget.html
2016-05-01 21:03 CRITICAL task          Film            BUG: Unhandled error in plugin make_html: must be unicode, not str
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/output/html.py", line 44, in on_task_output
    f.write(template.encode('utf-8'))
TypeError: must be unicode, not str

**Comment by stevezau** [comment]
that should fix it, re-open if not.
