### ISSUE TITLE
imdb_list fails consistently

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#1124]
flexget.log:

```
2016-05-01 23:21 CRITICAL plugin        MYTASKNAME   Login to imdb failed. Check your credentials.
2016-05-01 23:21 WARNING  task          MYTASKNAME   Aborting task (plugin: list_reject)
```

crashlog:

```
2016-04-30 18:50 CRITICAL task          MYTASKNAME   BUG: Unhandled error in plugin list_reject: 404 Client Error: Not Found for url: http://www.imdb.com/list/export?list_id=ratings&author_id=ur1250180
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/list_reject.py", line 33, in on_task_filter
    if entry in thelist:
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 148, in __contains__
    return any(e['imdb_id'] == entry['imdb_id'] for e in self.items)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/imdb_list.py", line 103, in items
    (self.list_id, self.user_id))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/requests.py", line 239, in request
    result.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://www.imdb.com/list/export?list_id=ratings&author_id=ur1250180
```

Yet the link works perfectly when opened from a different IP. So this is an issue with IMDB throttling incoming connections.

Is there a sane way to limit the frequency which Flexget uses to fetch stuff from IMDB?

**Comment by liiight** [comment]
It's already limited via domain limiter. @gazpachoking i think we can cache  cookie and try to avoid login every time

**Comment by liiight** [comment]
Duplicate #1109
