### ISSUE TITLE
Could not start manager: 'ascii' codec can't encode character u'\xe0' in position 18: ordinal not in range(128)

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1127]
I'm trying to have my movie-list on a file so I used the following cli:
fmf@kodi:~/.flexget$ flexget movie-list list -l trakt-movies > /home/fmf/Dropbox/Temp/trakt-movies.txt
Could not start manager: 'ascii' codec can't encode character u'\xe0' in position 18: ordinal not in range(128)

========= Remote Traceback (2) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 80, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 336, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/movie_list.py", line 31, in do_cli
    movie_list_list(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/movie_list.py", line 70, in movie_list_list
    console(_str + _ids)
  File "/usr/local/lib/python2.7/dist-packages/flexget/logger.py", line 119, in console
    print(text, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 46, in write
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 52, in flush
    self.writer(self.buffer, end='')
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 18: ordinal not in range(128)

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 104, in exposed_console
    console(text, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/logger.py", line 119, in console
    print(text, *args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 18: ordinal not in range(128)

fmf@kodi:~/.flexget$

What I don't get is that if I run the same cli without the redirection I get the whole movie-list without any error.

I managed to discover that the list is actually printed until it founds a movie named "Senza nessuna pietà", and the character "à" that make it crash is 0xE0 ascii.

**Comment by paranoidi** [comment]
Ah, good old redirecting to a file changes default encoding issue ...

**Comment by effemmeffe** [comment]
I don't understand what you mean.
Should I do something on my system to avoid this?

**Comment by paranoidi** [comment]
Redirecting to a file changes how python does certain encoding handling. Not much you can do.

**Comment by liiight** [comment]
note that you can use the API: `http://localhost:5050/api/movie_list/1/movies/`

**Comment by effemmeffe** [comment]
The problem doesn't occour only with redirection, also piping it to more or to less.
@liiight I know that, but I'd like to have it in a file for future reference. I guess I'll have to copy and paste from the API... :(

**Comment by liiight** [comment]
you can curl:
`curl -X GET --header "Accept: application/json" "http://localhost:5050/api/movie_list/1/movies/" > output.txt`

**Comment by effemmeffe** [comment]
fmf@kodi:~$ cat output.txt
{
    "message": "The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."
}

**Comment by liiight** [comment]
lol, you need to be logged in, create a cookie: http://discuss.flexget.com/t/flexget-rest-api/

**Comment by effemmeffe** [comment]
This is out of my league. I tried to use the autentication first with the POST as described, but still can't get it work, I'll pass.
Thanks.

**Comment by dernalis** [comment]
Here's a workaround that work's for me.
http://blog.mathieu-leplatre.info/python-utf-8-print-fails-when-redirecting-stdout.html
I was piping the output.
