### ISSUE TITLE
Python Upgrade (2.7 -> 3.5) leads to errors attempting to upgrade (ASCII codec can't decode...)

### ISSUE THREAD

**Issue by Anaerin** [Flexget/Flexget#1133]
When attempting to execute flexget, I get the following error:
````
C:\Users\Robert>flexget execute --debug
2016-05-03 23:09 INFO     manager                       Database upgrade is required. Attempting now.
2016-05-03 23:09 ERROR    schema                        Failed to upgrade database for plugin simple_persistence: 'ascii' codec can't decode byte 0xe0 in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\db_schema.py", line 150, in upgrade_wrapper
    new_ver = upgrade_func(current_ver, session)
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\utils\simple_persistence.py", line 60, in upgrade
    p = pickle.loads(row['value'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\db_schema.py", line 150, in upgrade_wrapper
    new_ver = upgrade_func(current_ver, session)
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\utils\simple_persistence.py", line 60, in upgrade
    p = pickle.loads(row['value'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\robert\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\robert\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python35\Scripts\flexget.exe\__main__.py", line 9, in <module>
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\__init__.py", line 42, in main
    manager.start()
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\manager.py", line 310, in start
    self._shutdown()
  File "c:\users\robert\appdata\local\programs\python\python35\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\manager.py", line 752, in acquire_lock
    yield
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\manager.py", line 308, in start
    self.initialize()
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\manager.py", line 205, in initialize
    fire_event('manager.upgrade', self)
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\db_schema.py", line 158, in upgrade_wrapper
    manager.shutdown(finish_queue=False)
  File "c:\users\robert\appdata\local\programs\python\python35\lib\site-packages\flexget\manager.py", line 857, in shutdown
    raise RuntimeError('Cannot shutdown manager that was never initialized.')
RuntimeError: Cannot shutdown manager that was never initialized.

C:\Users\Robert>
````

This is pretty serious, for fairly obvious reasons, though I have no idea what is causing it or how to fix it.

Any suggestions?

**Comment by stevezau** [comment]
Is it a db from py2? Try upgrade in py2 first, so just run flexget so it will upgrade the db then run again with py3

**Comment by paranoidi** [comment]
That's a inconvenient workaround. This should work better.

**Comment by stevezau** [comment]
@paranoid I suspect this happend as it was on the older version of flexget where we used pickles. We migrated to JSON which happens as part of the db upgrade. 

From memory Python2 pickles are incomparable with py3. Wasn't sure if it was worth the effort figuring out a solution as I was hoping this would be a rare case.

**Comment by paranoidi** [comment]
Then reset simple persistence if upgrade fails
