### ISSUE TITLE
Trakt API lookup errors

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#1143]
When trying to call the flexget API for trakt lookup, these errors occurs.
Some useful info might be that it does not occur on all all the calls (in the UI, when loading 1 page of the movie list, 3/10 do succeed to load)
```
2016-05-06 10:15 ERROR    flexget.api                   Exception on /trakt/movie/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api/trakt_lookup.py", line 120, in get
    return jsonify(result.to_dict())
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_trakt.py", line 786, in to_dict
    "actors": list_actors(self.actors),
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_trakt.py", line 838, in actors
    self._actors[:] = get_db_actors(self.id, 'movie')
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1155, in __setslice__
    values = [__set(self, value) for value in values]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1045, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 717, in fire_append_event
    item, initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 941, in fire_append_event
    initiator or self._append_token or self._init_append_token())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 46, in append
    sess._save_or_update_state(item_state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1607, in _save_or_update_state
    self._save_or_update_impl(st_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1861, in _save_or_update_impl
    self._update_impl(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1854, in _update_impl
    self.identity_map.add(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/identity.py", line 132, in add
    % (key, ))
AssertionError: A conflicting state is already present in the identity map for key (<class 'flexget.plugins.api_trakt.TraktImages'>, (1,))
```

**Comment by crawln45** [comment]
I have no idea about the ui. But all my lookups so far have come back without an issue. Need more information to proceed.

**Comment by liiight** [comment]
Use the ui then, it'll generate a lot of api calls

**Comment by crawln45** [comment]
I've used the UI now. Seems all of the calls for either series or tv shows Throw many many errors. Probably has something to do with the fact that it's sending 500 calls in 1 second. In short. It's a UI error not a plugin error. 1 thing hasn't finished before another is requested.

**Comment by crawln45** [comment]
My suggestion would be to build a request queue for things like this. Allowing the queue to go 1 at a time until completed. Probably has more to do with threads than anything.

**Comment by crawln45** [comment]
Or better yet. Build it into the UI properly to make a call wait for results. Not slam the api with 500 calls on lookups that might not be there already and have to be made.

**Comment by Tommatheussen** [comment]
I'm not sure where you're getting that many calls, since the movies (and series) page are limited to 10 items per page. 

I also want to mention that the lookup calls worked before the latest update to the trakt lookup endpoint. And the series page calls the TVDB or Tvmaze (don't know which one it currently is), which seems to handle this very well.

Also I've included the debug log, maybe it holds some more information?

```
2016-05-07 10:34 DEBUG    movie_list                    retrieving movie lists
2016-05-07 10:34 DEBUG    movie_list                    fetching list with id 1
2016-05-07 10:34 DEBUG    api_trakt                     movie `The Lost` age 7 expires in 37 days
2016-05-07 10:34 DEBUG    api_trakt                     movie `The Social Network` age 6 expires in 32 days
2016-05-07 10:34 DEBUG    api_trakt                     movie `The Croods 2` age 0 expires in 2 days
2016-05-07 10:34 DEBUG    api_trakt                     movie `Rape Zombie: Lust of the Dead 3` age 3 expires in 17 days
2016-05-07 10:34 DEBUG    api_trakt                     Searching with params: tmdb=256522
2016-05-07 10:34 DEBUG    api_trakt                     Searching with params: tmdb=223702
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/search
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/search
2016-05-07 10:34 DEBUG    api_trakt                     Searching with params: tmdb=175168
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/search
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/156459
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/137261
2016-05-07 10:34 DEBUG    api_trakt                     Searching with params: tmdb=325348
2016-05-07 10:34 DEBUG    api_trakt                     movie `Jaws 2` age 38 expires in 192 days
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/search
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/111210
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/156459/people
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/137261/people
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/221309
2016-05-07 10:34 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/111210/people
2016-05-07 10:35 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/221309/people
2016-05-07 10:35 DEBUG    api_trakt                     Searching with params: tmdb=284303
2016-05-07 10:35 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/search
2016-05-07 10:35 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/181547
2016-05-07 10:35 ERROR    flexget.api                   Exception on /trakt/movie/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api/trakt_lookup.py", line 120, in get
    return jsonify(result.to_dict())
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_trakt.py", line 786, in to_dict
    "actors": list_actors(self.actors),
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_trakt.py", line 838, in actors
    self._actors[:] = get_db_actors(self.id, 'movie')
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1155, in _setslice__
    values = [__set(self, value) for value in values]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1045, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 717, in fire_append_event
    item, initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 941, in fire_append_event
    initiator or self._append_token or self._init_append_token())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 46, in append
    sess._save_or_update_state(item_state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1607, in _save_or_update_state
    self._save_or_update_impl(st_)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1861, in _save_or_update_impl
    self._update_impl(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1854, in _update_impl
    self.identity_map.add(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/identity.py", line 132, in add
    % (key, ))
AssertionError: A conflicting state is already present in the identity map for key (<class 'flexget.plugins.api_trakt.TraktImages'>, (1, ))
```

**Comment by cvium** [comment]
This error is probably because the same actor is added to the actor table multiple times. I encountered a similar error on a plugin I'm working on.

**Comment by liiight** [comment]
So I guess the first thing to try is shorter sessions?

**Comment by cvium** [comment]
If the sessions are overly long, sure. Otherwise I'd probably just make sure that the same actor isn't added to the same movie/series more than once.

**Comment by crawln45** [comment]
Problem isn't the plugin. I do the checks to make sure that nothing matching is re entered. Problem is <Thread A> calls call1 <Thread B><Plugin> | <Thread B> <Plugin> starts call1 | <Thread A> calls call 2 <Thread B><Plugin>| <Thread B><Plugin> call1 hasn't finished but still start call2 and so on and so forth. This type of usage is why we implemented the task.queue system for the daemon mode. But we don't use the task queue system we call the plugin directly.

**Comment by liiight** [comment]
well, I changed the default lookup to exclude `actors` by default which hid this issue under the rug. The question is it still worth to mess around with this.

**Comment by liiight** [comment]
I guess not :smile:
