### ISSUE TITLE
BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by binamov** [Flexget/Flexget#1146]
I was on 2.0.9 and went up to 2.0.13 and started seeing problems. So then I downgraded back to 2.0.9, made sure everything was working, then revved up to 2.0.13 one release at a time. This seems to have fixed. Feel free to close with wontfix or such.

```
# flexget -V
2.0.13
You are on the latest release.
```
started seeing this:

```
more /luser/.flexget/crash_report.2016.05.07.023509631014.log
2016-05-07 02:35 DEBUG    manager                       Figuring out config load paths
2016-05-07 02:35 DEBUG    manager                       Found config: /luser/.flexget/config.yml
2016-05-07 02:35 DEBUG    manager                       Config file /luser/.flexget/config.yml selected
2016-05-07 02:35 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-05-07 02:35 VERBOSE  discover      bumps Discovering 47 titles ...
2016-05-07 02:35 INFO     discover      bumps Ignoring interval because of --discover-now
2016-05-07 02:35 INFO     task          bumps Plugin discover has requested task to be ran again after execution has completed.
2016-05-07 02:35 CRITICAL task          bumps BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 276, in on_task_input
    entries = self.estimated(entries, estimation_mode)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 192, in estimated
    est_date = estimator.estimate(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released.py", line 29, in estimate
    estimate = estimator(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 53, in estimate
    episode = lookup(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 399, in episode_lookup
    series = APITVMaze.series_lookup(session=session, only_cached=only_cached, **lookup_params)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 360, in series_lookup
    series = TVMazeSeries(tvmaze_show, session)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 102, in __init__
    self.update(series, session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 139, in update
    self.original_image = series['image'].get('original')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by liiight** [comment]
Fixed with https://github.com/Flexget/Flexget/commit/52a0338882a6d01e9ce01dfcfcd6a7c68263304c
