### ISSUE TITLE
SSLError: bad handshake

### ISSUE THREAD

**Issue by gbrito** [Flexget/Flexget#1160]
Flexget Version 2.0.16
Python Version 2.7.3

Flexget executed with:
```
flexget -L debug execute --tasks clean-movie-queue --dump --now
```

Config:
```
##### Remove manually movies downloaded from the movie queue and trakt list
#
  clean-movie-queue:
    priority: 11
    interval: 2 hour
    verify_ssl_certificates: no
    template:
      - disable-seen-retry
      - movies-metainfo
    filesystem:
      path: '{{secrets.folders.root}}{{secrets.folders.movies}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    list_remove:
      - movie_list: trakt-movies
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          username: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.movies}}'

```

Error:
```
2016-05-10 11:47 DEBUG    backlog       clean-movie-queue 0 entries purged from backlog
2016-05-10 11:47 VERBOSE  details       clean-movie-queue Produced 152 entries.
2016-05-10 11:47 DEBUG    urlrewriter   clean-movie-queue Checking 152 entries
2016-05-10 11:47 VERBOSE  details       clean-movie-queue Summary - Accepted: 152 (Rejected: 0 Undecided: 0 Failed: 0)
2016-05-10 11:47 VERBOSE  list_remove   clean-movie-queue removing accepted entries from movie_list - trakt-movies
2016-05-10 11:47 DEBUG    parser_guessit clean-movie-queue Parsing movie: `The.5th.Wave.2016.1080p.BluRay.x264-[YTS.AG]` [options: {}]
2016-05-10 11:47 DEBUG    parser_guessit clean-movie-queue Parsing result: <GuessitParsedMovie(name=The 5th Wave,year=2016,quality=1080p bluray h264)> (in 40.0 ms)
2016-05-10 11:47 DEBUG    utils.requests clean-movie-queue Fetching https://api.themoviedb.org/3/configuration
2016-05-10 11:47 ERROR    lazy_lookup   clean-movie-queue Unhandled error in lazy lookup plugin
2016-05-10 11:47 CRITICAL manager       clean-movie-queue An unexpected crash has occurred. Writing crash report to /home/goncalo/.flexget/crash_report.2016.05.10.114751625854.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.16
2016-05-10 11:47 DEBUG    manager       clean-movie-queue Traceback:
Traceback (most recent call last):
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/utils/lazy_dict.py", line 38, in __getitem__
    func(self.store)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/metainfo/tmdb_lookup.py", line 64, in lazy_loader
    entry.update_using_map(self.field_map, movie)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/entry.py", line 272, in update_using_map
    v = value(source_item)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/metainfo/tmdb_lookup.py", line 42, in <lambda>
    'tmdb_posters': lambda movie: [poster.url for poster in movie.posters],
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/api_tmdb.py", line 145, in url
    return get_tmdb_config()['images']['base_url'] + 'original' + self.file_path
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/api_tmdb.py", line 32, in get_tmdb_config
    _tmdb_config = tmdb_request('configuration')
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/api_tmdb.py", line 39, in tmdb_request
    return requests.get(full_url, params=params).json()
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/utils/requests.py", line 269, in get
    return request('get', url, **kwargs)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/utils/requests.py", line 249, in request
    return s.request(method=method, url=url, **kwargs)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/utils/requests.py", line 234, in request
    result = requests.Session.request(self, method, url, *args, **kwargs)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
2016-05-10 11:47 DEBUG    movie_list    clean-movie-queue trying to match movie based off id imdb_id: tt2304933
2016-05-10 11:47 DEBUG    movie_list    clean-movie-queue trying to match movie based off id tmdb_id: 299687
```

**Comment by gbrito** [comment]
This error appears on the screen and the other one on the flexget.log and on a crash report
They should be connected

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 850, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 723, in format
    return fmt.format(record)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/logger.py", line 162, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType
Logged from file movie_list.py, line 174
```

**Comment by stevezau** [comment]
can u run the below and try again

```
pip install requests[security]
```

**Comment by gbrito** [comment]
It was already installed, i upgraded, but still the same error

**Comment by gbrito** [comment]
If I run this command
```
openssl s_client -connect api.themoviedb.org:443
```

This is the result I get
```
Verify return code: 20 (unable to get local issuer certificate)
```

If I run this
```
 openssl s_client -connect api.themoviedb.org:443 -CAfile `python -c 'import requests; print(requests.certs.where())'`
```

I get this
```
 Verify return code: 0 (ok)
```

Is it possible to force the flexget to verify the certificate  with the one we provide in requests.certs.where()

**Comment by gbrito** [comment]
On the file /flexget/plugins/api_tmdb.py I changed the Line 39 from this

```
    return requests.get(full_url, params=params).json()
```

to this

```
    return requests.get(full_url, params=params, verify=False).json()
```

Is it possible to make this as an option instead of hardcoded?

Like this I have no problems and no more crash reports

**Comment by stevezau** [comment]
you can do this in config

http://flexget.com/wiki/Plugins/verify_ssl_certificates

I am keeping this open as we should catch these errors and suggest fixes

**Comment by gbrito** [comment]
I have that config already but it seams that it doesn't get passed to api_tmdb

**Comment by gbrito** [comment]
I tried in a different machine with Python 3.4.2 and have no errors. 
There is any way I can check the packages installed in both machines to see if I find any difference? except in the python version.

**Comment by cvium** [comment]
Well, if it's debian/ubuntu, then `dpkg --get-selections | grep -v deinstall`. `pip freeze` for Python packages.

**Comment by gbrito** [comment]
It looks like you can remove this as a flexget bug, i check in the new machine with a virtualenv with python 2.7.9 and have zero errors or crash.

I can only assume that the python 2.7.3 is making some conflict
