### ISSUE TITLE
list_remove fails with imdb_list on certain movies

### ISSUE THREAD

**Issue by ddman2** [Flexget/Flexget#1164]
```
2016-05-12 01:18 VERBOSE  utils.requests MYTASKNAME Waiting 4.89 seconds until next request to imdb.com
2016-05-12 01:18 CRITICAL task          MYTASKNAME BUG: Unhandled error in plugin list_remove: 400 Client Error: Bad Request for url: http://www.imdb.com/list/_ajax/watchlist_has
2016-05-12 01:18 CRITICAL manager       MYTASKNAME An unexpected crash has occurred. Writing crash report to {{CRASH_REPORT_LOCATION}}. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.19
2016-05-12 01:18 WARNING  task          MYTASKNAME Aborting task (plugin: list_remove)
```

The plugin seems to be crashing consistently on certain movie names.  When I remove one offending movie name from the search, it will crash consistently on another after several successful lookups of other movie names.  I suspect the task is crashing on values which it cannot locate in IMDB.  Examples of offending values are "7 Days in Hell (2015)", "Batman Under the Red Hood (2010)" and "Batman Apocalypse (2010)".

**Comment by liiight** [comment]
Can you paste the crash log?

**Comment by ddman2** [comment]
''''
2016-05-12 10:31 CRITICAL task          clean_movie_list BUG: Unhandled error in plugin list_remove: 400 Client Error: Bad Request for url: http://www.imdb.com/list/_ajax/watchlist_has
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/flexget/task.py", line 442, in __run_plugin
    return method(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/flexget/plugins/output/list_remove.py", line 41, in on_task_output
    thelist -= task.accepted
  File "/usr/lib/python2.7/_abcoll.py", line 356, in __isub__
    self.discard(value)
  File "/home/pi/.local/lib/python2.7/site-packages/flexget/plugins/list/imdb_list.py", line 185, in discard
    status = self.session.post('http://www.imdb.com/list/_ajax/watchlist_has', data=data).json()
  File "/home/pi/.local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/flexget/utils/requests.py", line 241, in request
    result.raise_for_status()
  File "/home/pi/.local/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request for url: http://www.imdb.com/list/_ajax/watchlist_has
''''

**Comment by liiight** [comment]
This isn't good. Seems imdb changed something. Checking

**Comment by liiight** [comment]
I cannot reproduce this. does this happen all the time for you?
please post debug log of the task

**Comment by ddman2** [comment]
```
2016-05-16 08:35 VERBOSE  utils.requests MYTASKNAME Waiting 4.90 seconds until next request to imdb.com
2016-05-16 08:36 CRITICAL task          MYTASKNAME BUG: Unhandled error in plugin list_remove: 400 Client Error: Bad Request for url: http://www.imdb.com/list/_ajax/watchlist_has
2016-05-16 08:36 CRITICAL manager       MYTASKNAME An unexpected crash has occurred. Writing crash report to /home/pi/.config/flexget/crash_report.2016.05.16.083604611559.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.23
2016-05-16 08:36 WARNING  task          MYTASKNAME Aborting task (plugin: list_remove)
2016-05-16 08:36 INFO     performance                   Performance results for task MYTASKNAME:
2016-05-16 08:36 INFO     performance                   urlrewriting    took 3.36 sec (0 queries)
2016-05-16 08:36 INFO     performance                   list_remove     took 331.12 sec (6441 queries)
2016-05-16 08:36 INFO     performance                   seen            took 7.55 sec (691 queries)
2016-05-16 08:36 INFO     performance                   remember_rejected took 0.13 sec (6 queries)
2016-05-16 08:36 INFO     performance                   imdb_lookup     took 0.81 sec (0 queries)
2016-05-16 08:36 INFO     performance                   metainfo_content_size took 1.02 sec (0 queries)
2016-05-16 08:36 INFO     performance                   retry_failed    took 4.92 sec (691 queries)
2016-05-16 08:36 INFO     performance                   version_checker took 0.16 sec (1 queries)
2016-05-16 08:36 INFO     performance                   accept_all      took 1.76 sec (0 queries)
2016-05-16 08:36 INFO     performance                   filesystem      took 4.94 sec (0 queries)
2016-05-16 08:36 INFO     performance                   backlog         took 30.92 sec (1387 queries)
```

**Comment by liiight** [comment]
This isn't a debug log, please run with `-L debug`

**Comment by ddman2** [comment]
Below is a log run with `-L debug`

```
2016-05-18 08:16 VERBOSE  utils.requests clean_movie_list Waiting 4.89 seconds until next request to imdb.com
2016-05-18 08:16 CRITICAL task          MYTASKNAME BUG: Unhandled error in plugin list_remove: 400 Client Error: Bad Request for url: http://www.imdb.com/list/_ajax/watchlist_has
2016-05-18 08:16 CRITICAL manager       MYTASKNAME An unexpected crash has occurred. Writing crash report to CRASHLOG. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.25
2016-05-18 08:16 WARNING  task          clean_movie_list Aborting task (plugin: list_remove)
```

**Comment by liiight** [comment]
Please paste entire log. I wanna see which entry crashed it.

**Comment by ddman2** [comment]
Have you tried the examples I posted above?  

"Examples of offending values are "7 Days in Hell (2015)", "Batman Under the Red Hood (2010)" and "Batman Apocalypse (2010)"."

**Comment by drwyrm** [comment]
These are all movies that started being found by my PR that adds (TV Movie) and (Video) results from imdb searches, so it may be related somehow.
7 Days in Hell (2015) (TV Movie)
Batman: Under the Red Hood (2010) (Video)
Superman/Batman: Apocalypse (2010) (Video)

**Comment by liiight** [comment]
Hmm, important detail. I'll try to reproduce.

**Comment by drwyrm** [comment]
Just a guess, without actually looking at the code... Maybe the imdb lookup fail that was previously cached (assuming your DB is older than the code that made these results be found) is confusing the imdb_list plugin?

**Comment by liiight** [comment]
Maybe. Maybe the api call for imdb to remove these movies should be different.

**Comment by ddman2** [comment]
I put the entries in quotes because that's how they exist in the directory with pathscrub: windows and the {{movie_title}} {{movie_year}} naming convention.  

Drwyrm, since you mentioned you've changed the code, I think I've figured out the issue but I have not yet tested a possible solution.

The files were saved, I presume, when the old code was in effect.  The lookup was made and the files were named.  New look ups to IMDb based on the IMDb movie code will work (the watchlist).  This would explain why the first lookup to IMDb works.  But the filesystem plugin is looking at a directory named with the "old code".  Which is why the filesystem plugin crashes.

I was aware from prior testing that changing "Batman Apocalypse (2010)" to "Superman Batman Apocalypse (2010)" prevents a crash at this value.  I expect that manually correcting the offending values might be a sufficient workaround for me because the current code drwyrm described should prevent offending values from being created in the future. 

However, please let me know if you would like me to do anything else to help squash the bug rather than workaround it.

**Comment by liiight** [comment]
try doing `flexget database reset-plugin imdb_lookup` and trying again (this will clear all the imdb cache). I think it's a long shot but worth checking. i'll test using a real watchlist with these movies shortly

**Comment by liiight** [comment]
Couldn't reproduce manually. movies are removed with no issue.
Please attach full debug logs for the task or issue will be closed.

**Comment by drwyrm** [comment]
I do think its the failed cache that is causing issues... The local(filesystem) entry was previously cached as failed and a bogus request somehow made it to imdb api.

If your movie collection is big and you want to avoid the full imdb_lookup reset, you can clear just the failed entries cache with 'echo "delete from imdb_search where failed = 1;" | sqlite3 db-config.sqlite'. You should provide us a full debug log as liiight requested first. I wasn't able to reproduce the issue here either.

**Comment by ddman2** [comment]
@drwyrm,
`echo "delete from imdb_search where failed = 1;" | sqlite3 db-config.sqlite`
returns:
`-bash: sqlite3: command not found`

I did try `flexget database reset-plugin imd_lookup` but this did not work either.

**Comment by liiight** [comment]
Gimme the exact offending files names please

**Comment by liiight** [comment]
Make sure the log level is before the execute command: `flexget - L debug execute - - tasks TASKNAME`
