### ISSUE TITLE
Unhandled error in lazy lookup plugin

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#1175]
```
2016-05-14 12:46 VERBOSE  exec          Series_Collection_EN Executing: echo "autoStart=TRUE" >> "C:\Users\manue\AppData\Local\JDownloader v2.0/folderwatch/Game.of.Silence.S01E04.The.Uninvited.1080p.WEB-DL.DD5.1.H.264-BS.crawljob"
2016-05-14 12:46 VERBOSE  exec          Series_Collection_EN Executing: echo "forcedStart=TRUE" >> "C:\Users\manue\AppData\Local\JDownloader v2.0/folderwatch/Game.of.Silence.S01E04.The.Uninvited.1080p.WEB-DL.DD5.1.H.264-BS.crawljob"
2016-05-14 12:46 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:46 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124658847000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:47 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:47 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124709875000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:47 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:47 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124722124000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:47 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:47 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124733016000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:47 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:47 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124745376000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:47 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:47 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124755770000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:48 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:48 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124807927000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:48 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:48 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124818313000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:48 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:48 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124830035000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:48 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:48 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124840503000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:48 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:48 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124852685000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:49 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:49 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124903074000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:49 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:49 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124915228000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:49 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:49 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124925606000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:49 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:49 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124937741000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:49 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
2016-05-14 12:49 CRITICAL manager       Series_Collection_EN An unexpected crash has occurred. Writing crash report to C:\Users\manue\flexget\crash_report.2016.05.14.124948127000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.0.21
2016-05-14 12:50 ERROR    lazy_lookup   Series_Collection_EN Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\utils\lazy_dict.py", line 38, in __getitem__
    func(self.store)
  File "c:\python27\lib\site-packages\flexget\plugins\metainfo\thetvdb_lookup.py", line 113, in lazy_series_lookup
    return self.series_lookup(entry, self.series_map)
  File "c:\python27\lib\site-packages\flexget\utils\database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\metainfo\thetvdb_lookup.py", line 105, in series_lookup
    session=session
  File "c:\python27\lib\site-packages\flexget\utils\database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\api_tvdb.py", line 446, in lookup_series
    _update_search_strings(series, session, search=name)
  File "c:\python27\lib\site-packages\flexget\plugins\api_tvdb.py", line 378, in _update_search_strings
    func.lower(TVDBSearchResult.search) == name).first()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\query.py", line 2634, in first
    ret = list(self[0:1])
  File "c:\python27\lib\site-packages\sqlalchemy\orm\query.py", line 2457, in __getitem__
    return list(res)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\query.py", line 2735, in __iter__
    self.session._autoflush()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "c:\python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 1293, in _autoflush
    self.flush()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush
    self._flush(objects)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush
    flush_context.execute()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    uow
  File "c:\python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "c:\python27\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "c:\python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO tvdb_series (id, last_updated, expired, name, language, rating, status, runtime, airs_time, airs_dayofweek, content_rating, network, overview, imdb_id, zap2it_id, banner, first_aired, aliases, actors, posters) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (271653, 1443966400, 0, u'The Art of', u'en', 10.0, u'Continuing', 30, u'8:00 PM', u'Thursday', u'', u'Ovation TV', u'A look at creative fields that are outside the traditional definition of art.\x80\x9d  Each week, a new artistic medium is explored through profiles of boundary-pushing artists. Focusing on the celebrated as well as the undiscovered, this series explores the creative process behind each featured art form and uncovers how and why these artists do what they do. From graffiti artists and breakdancers to mixologists and comedians, each week "The Art Of" reveals the passion that keeps these artists motivated and inspired.', u'tt3168986', u'', u'graphical/271653-g.jpg', '2013-05-27 00:00:00.000000', u'[]', None, None)]
```

**Comment by Jonybat** [comment]
Same here
http://pastebin.com/pn0uV2Du

**Comment by marine1988** [comment]
I having same issue

http://pastebin.com/F1Miskjd

**Comment by cvium** [comment]
@crack00r There are some changes to the lookup plugins in the next release. Please attempt to recreate the bug in the next release. I need to know if the changes I made regarding another bug fixed your problem.

**Comment by crack00r** [comment]
Still a error
https://nopaste.me/view/5e63e909

**Comment by cvium** [comment]
That is not the same error.

**Comment by liiight** [comment]
yeah, not even remotely related. Closing this, open a new issue @crack00r

**Comment by cvium** [comment]
There is already an issue open on this. #847
