### ISSUE TITLE
RuntimeError: Cannot shutdown manager that was never initialized.

### ISSUE THREAD

**Issue by rafaelcgs10** [Flexget/Flexget#1176]
I'm try to run flexget daemon start -d but I aways get this error:

```
2016-05-14 17:45 INFO     manager                       Database upgrade is required. Attempting now.
2016-05-14 17:45 ERROR    schema                        Failed to upgrade database for plugin simple_persistence: value
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/db_schema.py", line 150, in upgrade_wrapper
    new_ver = upgrade_func(current_ver, session)
  File "/usr/lib/python2.7/site-packages/flexget/utils/simple_persistence.py", line 42, in upgrade
    for row in session.execute(select([table.c.id, table.c.plugin, table.c.key, table.c.value])):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 211, in __getattr__
    raise AttributeError(key)
AttributeError: value
Traceback (most recent call last):
  File "/usr/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 309, in start
    self.initialize()
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 206, in initialize
    fire_event('manager.upgrade', self)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/db_schema.py", line 158, in upgrade_wrapper
    manager.shutdown(finish_queue=False)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 858, in shutdown
    raise RuntimeError('Cannot shutdown manager that was never initialized.')
RuntimeError: Cannot shutdown manager that was never initialized.
```

**Comment by paranoidi** [comment]
Schema upgrade failures should be handled better.

**Comment by everthis** [comment]
same here.

```
2016-08-28 12:53 VERBOSE  check                         Pre-checked 28 configuration lines
2016-08-28 12:53 INFO     manager                       Database upgrade is required. Attempting now.
2016-08-28 12:53 ERROR    schema                        Failed to upgrade database for plugin simple_persistence: value
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/db_schema.py", line 150, in upgrade_wrapper
    new_ver = upgrade_func(current_ver, session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/simple_persistence.py", line 42, in upgrade
    for row in session.execute(select([table.c.id, table.c.plugin, table.c.key, table.c.value])):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: value
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 311, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 208, in initialize
    fire_event('manager.upgrade', self)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/db_schema.py", line 158, in upgrade_wrapper
    manager.shutdown(finish_queue=False)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 874, in shutdown
    raise RuntimeError('Cannot shutdown manager that was never initialized.')
RuntimeError: Cannot shutdown manager that was never initialized.

```

**Comment by anonimoaveces** [comment]
None solution yet? Here another affected :(

**Comment by anonimoaveces** [comment]
I've just remove db-config.sqlite from .flexget/ dir... and now the flexget tries to execute my tasks...

I hope my experience can help other people ;)
