### ISSUE TITLE
Swagger API crash on py3.5

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#1182]
```
2016-05-15 14:38 ERROR    flexget.api                   Exception on /swagger.json [GET]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask_restful\__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask_restplus\resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask_restplus\api.py", line 583, in get
    return self.api.__schema__
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\werkzeug\utils.py", line 73, in __get__
    value = self.func(obj)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask_restplus\api.py", line 327, in __schema__
    self._schema = Swagger(self).as_dict()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask_restplus\swagger.py", line 224, in as_dict
    paths[extract_path(url)] = self.serialize_resource(ns, resource, url)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask_restplus\swagger.py", line 346, in serialize_resource
    operations[method] = self.serialize_operation(doc, method)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask_restplus\swagger.py", line 352, in serialize_operation
    'responses': self.responses_for(doc, method) or None,
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\flask_restplus\swagger.py", line 430, in responses_for
    description, model = (response, None) if isinstance(response, string_types) else response
TypeError: 'NoneType' object is not iterable
```

**Comment by liiight** [comment]
@stevezau seem the issue originates from [this endpoints](https://github.com/liiight/Flexget/blob/b92f47a265db04e8e4ec8dd2bff7a54b1a6f1581/flexget/api/schema.py#L25) , not exactly sure as to why though.

**Comment by liiight** [comment]
Ok it seems that all response decorators that do not have a `description` set cause this crash, `schema` was just the first one. 
We can solve this by adding description to all but i'm not sure as to why it crashes at all and only in py3, so not doing anything for now.

Not to mention we're on 0.8.6 for now, so this issue could be moot already.
