### ISSUE TITLE
Trakt API image delete issue

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#1191]
```
2016-05-18 09:50 DEBUG    api_trakt                     movie `X-Men: Apocalypse` age 0 expires in 2 days
2016-05-18 09:50 DEBUG    api_trakt                     Searching with params: tmdb=246655
2016-05-18 09:50 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/search
2016-05-18 09:50 DEBUG    utils.requests                 Fetching https://api-v2launch.trakt.tv/movies/149999
--------------------------------------------------------------------------------
ERROR in app [c:\python27\lib\site-packages\flask\app.py:1423]:
Exception on /trakt/movies/X-Men: Apocalypse/ [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\flask_restful\__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "c:\python27\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "c:\python27\lib\site-packages\flask_restplus\resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\utils\database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\utils\sqlalchemy_utils.py", line 141, in __exit__
    self.commit()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 801, in commit
    self.transaction.commit()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 392, in commit
    self._prepare_impl()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 372, in _prepare_impl
    self.session.flush()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush
    self._flush(objects)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush
    flush_context.execute()
  File "c:\python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 487, in execute
    self.dependency_processor.process_saves(uow, states)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\dependency.py", line 1092, in process_saves
    secondary_update, secondary_delete)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\dependency.py", line 1113, in _run_crud
    result.rowcount)
StaleDataError: DELETE statement on table 'trakt_image_movie' expected to delete 1 row(s); Only 2 were matched.
```
Happened on API call, probably due to movie expiration

**Comment by crawln45** [comment]
That entire mess says nothing at all without context of what it's actually trying to do and where it's doing it.

**Comment by liiight** [comment]
That's hard to do. All I did was load the movies ui. I can try to reproduce it with debug db sessions I guess

**Comment by crawln45** [comment]
I know. It was more a comment on how flask generates the traceback lol

**Comment by liiight** [comment]
I think both images and translations can br used as association proxies, like @gazpachoking did in tmdb

**Comment by guaycuru** [comment]
I'm also seeing this error, but in my case it happens on lazy_lookup:

```
2016-07-24 22:20 ERROR    lazy_lookup   Fill movie queue Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/trakt_lookup.py", line 318, in lazy_watched_lookup
    item = lookup(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_trakt.py", line 1135, in lookup_movie
    if not session.query(TraktMovieSearchResult).filter(TraktMovieSearchResult.search == title.lower()).first():
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2760, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 487, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/dependency.py", line 1092, in process_saves
    secondary_update, secondary_delete)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/dependency.py", line 1113, in _run_crud
    result.rowcount)
StaleDataError: DELETE statement on table 'trakt_image_movie' expected to delete 4 row(s); Only 5 were matched.
```

**Comment by crawln45** [comment]
ugh I really hate this plugin right now.
