### ISSUE TITLE
colon in string inside array throwing config check error

### ISSUE THREAD

**Issue by qvazzler** [Flexget/Flexget#1197]
### Expected behaviour:
Find string in array
### Actual behaviour:
Flexget complains about malformed config
### Steps to reproduce:
- Step 1:
```
      - irc_category in ['abc']: accept
```

to

```
      - irc_category in ['ab:c']: accept
```

#### Config:
```
irc:
  tracker_qvazzler:
    tracker_file: '{{ secrets.irc_tracker_qvazzler.trackerfile }}'
    nickname: '{{ secrets.irc_tracker_qvazzler.nickname }}'
    rsskey: '{{ secrets.irc_tracker_qvazzler.rsskey }}'
    invite_nickname: abc
    invite_message: '!invite abc'
    task: tracker_qvazzler
```
  
#### Log:
```
2016-05-19 19:34 CRITICAL manager                       mapping values are not allowed here in "<unicode string>", line 43, column 37: - irc_category in '['a b: c']': accept ^

-------------------------------------------------------------------------------
 Malformed configuration file (check messages above). Common reasons:
-------------------------------------------------------------------------------

 o Indentation error
 o Missing : from end of the line
 o Non ASCII characters (use UTF8)
 o If text contains any of :[]{}% characters it must be single-quoted (eg. value{1} should be 'value{1}')

 Reason: mapping values are not allowed here

 ----> MOST LIKELY REASON: Missing : from end of the line!

 Check configuration near line 42, column 36

 Fault is almost always in this or previous line

2016-05-19 19:34 CRITICAL manager                       Failed to load config file: Config file is not valid YAML
2016-05-19 19:34 DEBUG    manager                       Removed /home/qvazzler/.config/flexget/irc_daemon/.config-lock
Traceback (most recent call last):
  File "/home/qvazzler/.config/flexget/irc_daemon/env/lib/python2.7/site-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/home/qvazzler/.config/flexget/irc_daemon/env/lib/python2.7/site-packages/flexget/manager.py", line 309, in start
    self.initialize()
  File "/home/qvazzler/.config/flexget/irc_daemon/env/lib/python2.7/site-packages/flexget/manager.py", line 195, in initialize
    self.load_config()
  File "/home/qvazzler/.config/flexget/irc_daemon/env/lib/python2.7/site-packages/flexget/manager.py", line 576, in load_config
    raise ValueError('Config file is not valid YAML')
ValueError: Config file is not valid YAML
```

### Additional information:

- Flexget Version: cvium's magical IRC fork
- Python Version: 2.7.9
- Installation method: pip & cvium
- OS and version: Raspbian
- Link to crash log: MIA

Please verify that the following checkboxes are checked and data is present before submitting your issue:

- [x] Paste or link to a paste service ([pastebin](http://pastebin.com/) for example) of relevant config (preferably full config including templates if present. Remember to redact any personal information!
- [x] Paste or link to a paste service of debug level logs of relevant task/s. Use `flexget -L debug execute --tasks <Task_name>`
- [x] Flexget version (Use `flexget -V` to get it).
- [x] Full Python version (`2.7.11` for example). Run `python -V` to get it.
- [x] Installation method (`pip`, git install, etc.)
- [x] OS and version
- [x] Attach crash log if available

**Comment by qvazzler** [comment]
Intended behaviour. To fix it, wrap in quotes.

```
if:
   - "irc_category in ['ab:c']": accept
```
