### ISSUE TITLE
Pushbullet plugin crash on py3.5

### ISSUE THREAD

**Issue by oguska** [Flexget/Flexget#1225]
```
2016-06-06 03:30 CRITICAL task          anime-series    BUG: Unhandled error in plugin pushbullet: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flexget/plugins/output/pushbullet.py", line 98, in on_task_output
    self.send_push(task, apikey, title, body, url, device, 'device_iden')
  File "/usr/local/lib/python3.5/site-packages/flexget/plugins/output/pushbullet.py", line 134, in send_push
    'Authorization': 'Basic %s' % base64.b64encode(api_key),
  File "/usr/local/lib/python3.5/base64.py", line 62, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'

```

### Additional information:

- Flexget Version: Lastest

**Comment by bfqrst** [comment]
Hey guys,

I might (or not) have another crash related to this issue. I'll paste the crash log in this comment. Please advise as to whether I should open a dedicated issue for this one... 

Issue is present on latest 2.1.0 / Python 3.5 but also on the version before that. 2.1.0 on Python 2.7 is fine. I'm running FlexGet out of a Docker container (if this is of any interest). Also I'd be happy to provide more input if needed.

This is the Pushbullet template:
````
pushbullet:
      apikey: '{{ secrets.pb_apikey }}'
      title: >
        {% if title is defined %}{{ title }} processed.
        {% endif %}
      body: >
        '{{ filename }}'
````
Thanks in advance.

```
2016-06-24 06:27 CRITICAL task          flicks          BUG: Unhandled error in plugin pushbullet: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/output/pushbullet.py", line 102, in on_task_output
    self.send_push(task, apikey, title, body, url)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/output/pushbullet.py", line 153, in send_push
    error = json.loads(response.content)['error']
  File "/usr/lib/python3.5/site-packages/flexget/utils/json.py", line 112, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by gazpachoking** [comment]
Looks like a separate issue, should be an easy fix though. If this line
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/pushbullet.py#L153
Gets changed to
`error = response.json()['error']`

**Comment by liiight** [comment]
i would do it @gazpachoking, but it's suspicious that you didn't, so i'll leave it alone ;-)
