### ISSUE TITLE
html plugin crash on py 3.4

### ISSUE THREAD

**Issue by scarpedon** [Flexget/Flexget#1227]
### Expected behaviour:
Working as it did with python 2.7. 
### Actual behaviour:
html plugin is crashing with any version of python3
### Steps to reproduce:
Running the html plugin on py3.4-py3.5 crashes every time. Tested on Debian and Windows as well with py 3.4 and py 3.5

#### Config:
    html:
      url: https://ncore.cc/torrents.php?oldal={{i}}&tipus=xvidser
      increment:
        from: 1
        to: 3
        entries_count: 50000
#### Log:
```
2016-06-07 11:19 CRITICAL task          nCore task SD   BUG: Unhandled error in plugin html: 'module' object has no attribute 'splitquery'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/utils/cached_input.py", line 164, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugin.py", line 120, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/input/html.py", line 112, in on_task_input
    new_entries = self._request_url(task, config, url, auth, dump_name)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/input/html.py", line 139, in _request_url
    return self.create_entries(url, soup, config)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/input/html.py", line 222, in create_entries
    from_url = self._title_from_url(url)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/input/html.py", line 152, in _title_from_url
    parts = parse.splitquery(url[url.rfind('/') + 1:])
AttributeError: 'module' object has no attribute 'splitquery'
```

### Additional information:

- Flexget Version: 2.0.41
- Python Version: 3.4.2 
- Installation method: pip
- OS and version: Debian Jessie (Kernel 4.5)
- Link to crash log:

**Comment by liiight** [comment]
Did you test if the same config works for you using py2?

**Comment by scarpedon** [comment]
Yes, the same config was working properly with py2. 
Switched between py2 and py3 with update-alternatives keeping the config file the same.
