### ISSUE TITLE
pogcal_acquired plugin not working. 

### ISSUE THREAD

**Issue by holmdahl31** [Flexget/Flexget#1245]
### Expected behaviour:
Check watched in pogcal site.
http://flexget.com/wiki/Plugins/pogcal_acquired
### Actual behaviour:
Dosent even login
### Steps to reproduce:
- Step 1:  Enable the plugin and get one download

#### Config:
Only username and pass

  
#### Log:
```
2016-06-18 16:37
ERROR
pogcal_acquired
test
task Username/password for pogdesign calendar appear to be incorrect.
```

### Additional information:
Pogcal has changed stuff on their site. The login path has changed.
https://github.com/Flexget/Flexget/issues/1198
Should affect all versions off flexget, phyton and OS

Please verify that the following data is present before submitting your issue:

-Paste or link to a paste service ([pastebin](http://pastebin.com/) for example) of relevant config (preferably full config including templates if present. Remember to redact any personal information!
- Paste or link to a paste service of debug level logs of relevant task/s. Use `flexget -L debug execute --tasks <Task_name>`
- Flexget version (Use `flexget -V` to get it).
- Full Python version (`2.7.11` for example). Run `python -V` to get it.
- Installation method (pip, git install, etc.)
- OS and version
- Attach crash log if available

**Comment by holmdahl31** [comment]
Tryed to modify the url, added /login
And got a crash

2016-06-18 19:45 DEBUG    manager                       Figuring out config load pa$2016-06-18 19:45 DEBUG    manager                       Found config: /home/pi/.fle$2016-06-18 19:45 DEBUG    manager                       Config file /home/pi/.flexg$2016-06-18 19:45 INFO     manager                       Daemonizing...
2016-06-18 19:45 INFO     manager                       Daemonize complete. New PID$2016-06-18 19:45 INFO     scheduler                     Starting scheduler
2016-06-18 19:45 INFO     web_server                    Web interface available at $2016-06-18 20:57 INFO     download      test task       Downloading: Orange Is the $2016-06-18 20:57 INFO     transmission  test task       "Orange Is the New Black S0$2016-06-18 20:57 CRITICAL task          test task       BUG: Unhandled error in plu$Traceback (most recent call last):                                                    File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 443, in __run$    return method(*args, **kwargs)                                                    File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __cal$    return self.func(*args, **kwargs)                                                 File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/services/pogcal_acqu$    show_id = self.find_show_id(entry['series_name'], task.session)                   File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/services/pogcal_acqu$    show_re = name_to_re(None, show_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_commo$    if name.endswith(')'):
AttributeError: 'NoneType' object has no attribute 'endswith'
