### ISSUE TITLE
Unhandled error in plugin discover: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by fabrizio5680** [Flexget/Flexget#1251]
Unhandled error in plugin discover: cannot use a string pattern on a bytes-like object...
Issue appears when using discover with several search plugins and specified categories

Snippet of my discover plugin
```
discover:
      what:
        - emit_movie_queue: true
      from:
        - piratebay:
            category: "highres movies"
            sort_by: seeds
        - rarbg:
            category: [17, 44, 45, 42, 46]
        - torrentz: good
        - kat:
            category: movies
```
```
Unhandled error in plugin discover: cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/opt/lib/python3.5/site-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/opt/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/opt/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 272, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/opt/lib/python3.5/site-packages/flexget/plugins/input/discover.py", line 143, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/opt/lib/python3.5/site-packages/flexget/plugin.py", line 120, in wrapped_func
    return func(*args, **kwargs)
  File "/opt/lib/python3.5/site-packages/flexget/plugins/search/rarbg.py", line 120, in search
    query = normalize_scene(search_string)
  File "/opt/lib/python3.5/site-packages/flexget/utils/search.py", line 55, in normalize_scene
    normalize('NFKD', text).encode('ASCII', 'ignore'))
  File "/opt/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
```

### Additional information:

- Flexget Version: Latest 2.1.0
- Python Version: python 2.7.11
- Installation method: pip install
- OS and version: Android 4.4 busybox Amlogic 805

**Comment by gazpachoking** [comment]
Looks like you uncovered a bug with the search normalization utility.

This bit (the `.encode('ASCII', 'ignore')`) is causing the issue, I believe the intention is to strip out non-ascii characters, but it's also turning the text into bytes.
https://github.com/Flexget/Flexget/blob/develop/flexget/utils/search.py#L55

This other bit is rather suspect as well, though not causing your crash. I think it should probably be removed when we fix.
https://github.com/Flexget/Flexget/blob/develop/flexget/utils/search.py#L46-L47

**Comment by fabrizio5680** [comment]
Still occurring 2.1.3

**Comment by cvium** [comment]
Well, it hasn't been fixed yet...

**Comment by gustavi** [comment]
Similar problem : 

```
2016-08-11 13:19 ERROR    urlrewriter   fooseries task cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flexget/plugins/plugin_urlrewriting.py", line 70, in url_rewrite
    urlrewriter.instance.url_rewrite(task, entry)
  File "/usr/lib/python3.5/site-packages/flexget/plugins/urlrewrite/torrent411.py", line 421, in url_rewrite
    match = re.search(r"<a href=\"/torrents/download/\?id=(\d*?)\">.*\.torrent</a>", rawdata)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by fabrizio5680** [comment]
any update or workaround? still can't use discover plugin because of this issue
