### ISSUE TITLE
CRITICAL BUG: Unhandled error in plugin aria2: 'MetainfoSeries' object has no attribute 'guess_series'

### ISSUE THREAD

**Issue by complib2891** [Flexget/Flexget#1259]
### Expected behaviour:
aria2c to start downloading after '''flexget execute'''
### Actual behaviour:
log shows critical error

### Steps to reproduce:
- Step 1: ...

#### Config:
```
http://pastebin.com/w8Vx9cqx
```
  
#### Log:
```
$ cat *eport.2016.06.29.152007151466.log
2016-06-29 15:19 DEBUG    manager                       Figuring out config load paths
2016-06-29 15:19 DEBUG    manager                       Found config: /var/tmp/fget/config.yml
2016-06-29 15:19 DEBUG    manager                       Config file /var/tmp/fget/config.yml selected
2016-06-29 15:19 WARNING  manager                       Your locale declares ascii as the filesystem encoding. Any plugins reading filenames from disk will not work properly for filenames containing non-ascii characters. Make sure your locale env variables are set up correctly for the environment which is launching FlexGet.
2016-06-29 15:19 INFO     manager                       Test mode, creating a copy from database ...
2016-06-29 15:19 INFO     manager                       Test database created
2016-06-29 15:20 VERBOSE  task_queue                    There are 2 tasks to execute. Shutdown will commence when they have completed.
2016-06-29 15:20 VERBOSE  details       kat_tv          Produced 25 entries.
2016-06-29 15:20 INFO     series        kat_tv          identified_by has locked in to type `ep` for zoo
2016-06-29 15:20 VERBOSE  task          kat_tv          ACCEPTED: `Zoo S02E01E02 HDTV x264-LOL[ettv]` by series plugin because target quality
2016-06-29 15:20 VERBOSE  details       kat_tv          Summary - Accepted: 1 (Rejected: 0 Undecided: 24 Failed: 0)
2016-06-29 15:20 INFO     aria2         kat_tv          Connected to daemon at http://localhost:6800/rpc.
2016-06-29 15:20 CRITICAL task          kat_tv          BUG: Unhandled error in plugin aria2: 'MetainfoSeries' object has no attribute 'guess_series'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_aria2.py", line 246, in on_task_output
    guess_series = metainfo_series.instance.guess_series
AttributeError: 'MetainfoSeries' object has no attribute 'guess_series'
```

### Additional information:

- Flexget Version: 2.1.2
- Python Version:2.7.10
- Installation method: pip, follows website recommendation
- OS and version:  Ubuntu 15.10
- Link to crash log:

Please verify that the following data is present before submitting your issue:

-Paste or link to a paste service ([pastebin](http://pastebin.com/) for example) of relevant config (preferably full config including templates if present. Remember to redact any personal information!
- Paste or link to a paste service of debug level logs of relevant task/s. Use `flexget -L debug execute --tasks <Task_name>`
- Flexget version (Use `flexget -V` to get it).
- Full Python version (`2.7.11` for example). Run `python -V` to get it.
- Installation method (pip, git install, etc.)
- OS and version
- Attach crash log if available

**Comment by cvium** [comment]
Is this still relevant? This plugin doesn't seem to have worked for years and no one has reported this bug until now. It seems to be lacking a maintainer.

@tubedogg, @sergiogiogio, @wicast, @Sasasu ?

**Comment by wicast** [comment]
I'm not using this software for years,but the plugin has worked since commit 355b1847800e8b47a3a96a5374ec8b21992dce00.

**Comment by cvium** [comment]
Plugin broke after this commit https://github.com/Flexget/Flexget/commit/5f5e1018ed3ff426a8dfd3a3569d5a73438ca114#diff-4c4e00b79165b8bc5cbd98690b87abf9L45

**Comment by paranoidi** [comment]
Aria2 rewrite takes care of this.
