### ISSUE TITLE
BUG: Unhandled error in plugin list_match: u'movie_year'

### ISSUE THREAD

**Issue by PhoneixS** [Flexget/Flexget#1266]
### Expected behaviour:

Run without crashing.

### Actual behaviour:

An error is raised. `BUG: Unhandled error in plugin list_match: u'movie_year'`

### Steps to reproduce:
- Step 1: Run the task "descargar peliculas" like `flexget --debug execute --tasks "descargar peliculas"`.

#### Config:
```
templates:
  newpct:
    manipulate:
      - title:
          replace:
            format: ''
            regexp: Temporada \d+
      - title:
          replace:
            format: \1x\2
            regexp: Cap.(\d?\d)(\d\d)
    regexp:
      reject:
        - V\.O\. Subt\.
        - Español Latino
tasks:
  listar pelis:
    priority: 1
    trakt_list:
      username: ***
      account: ***
      list: pelisadescargar
      type: movies
    accept_all: yes
    list_add:
      - movie_list: Pelis de trakt
    seen: local # We don't want accepted movies on this feed to affect actual download feed
  descargar peliculas:
    priority: 10
    list_match:
      from:
        - movie_list: Pelis de trakt
    quality:
      - hdtv+
      - 720p+ !bdscr !dvdscr !cam
    parsing:
      movie: guessit
    manipulate:
      - movie_name:
          from: title
          extract: ([^\[]+)
    template: newpct
    regexp:
      reject:
        - \d?\dx\d\d
    rss: http://feeds.feedburner.com/newpctorrent?format=xml
    qbittorrent:
      host: localhost
      path: /media/descargas/Descargas/Películas/
      port: 9091
      label: Películas
```
  
#### Log:

[More complete log](http://pastebin.com/kZQTFF1w) although I have cut some part.

Relevant part:

```
2016-07-03 22:46 VERBOSE  task          descargar peliculas REJECTED: `Motive -  [HDTV][3x10][Español Castellano]` by regexp plugin because regexp '\d?\dx\d\d' matched field 'title'
2016-07-03 22:46 DEBUG    regexp        descargar peliculas regexp '\d?\dx\d\d' matched field 'title' for Motive -  [HDTV 720p][3x10][AC3 5.1 Español Castellano]
2016-07-03 22:46 VERBOSE  task          descargar peliculas REJECTED: `Motive -  [HDTV 720p][3x10][AC3 5.1 Español Castellano]` by regexp plugin because regexp '\d?\dx\d\d' matched field 'title'
{'_hooks': {u'accept': [<functools.partial object at 0x7fc06e950f18>,
                        <functools.partial object at 0x7fc06cdf0470>],
            u'complete': [],
            u'fail': [<functools.partial object at 0x7fc06e9eee68>,
                      <functools.partial object at 0x7fc06ce2cd60>,
                      <functools.partial object at 0x7fc06cdf0520>],
            u'reject': [<functools.partial object at 0x7fc06e950fc8>,
                        <functools.partial object at 0x7fc06cf6f730>,
                        <functools.partial object at 0x7fc06cdf04c8>]},
 '_state': u'undecided',
 'snapshots': {u'after_input': {u'author': u'Diego10',
                                u'description': u'<img alt="Se\xf1ora Doubtfire 1993 [BRrip X264 MKV][Castellano]" class="float: left; margin: 0px 4px 4px 0px;" src="http://images.newpct.com/banco_de_imagenes//m/0000001.jpg" /> T\xedtulo original\nMrs. Doubtfireaka \nAKA\nPap\xe1 por siempre\nSra. Doubtfire, pap\xe1 de por vida\nA\xf1o\n1993\nDuraci\xf3n\n125 min.\nPa\xeds\nEstados Unidos Estados Unidos\nDirector\nChris Columbus\nGui\xf3n\nRandi Mayem Singer, Leslie Dixon\nM\xfasica\nHoward Shore\nFotograf\xeda\nDonald McAlpine\nReparto\nRobin Williams, Sally Field, Pierce Brosnan, Mara Wilson, Harvey Fierstein, Lisa Jakub, Polly Holliday, Robert Prosky, Matthew Lawrence, Anne Haney\nProductora\n20th Century Fox\nG\xe9nero\nComedia. Drama | Familia. Televisi\xf3n. Cine familiar\nSinopsis\nDaniel Hillard es padre y esposo. Sus hijos lo consideran un padre maravilloso, pero su mujer est\xe1 cansada de que se comporte como si tambi\xe9n \xe9l fuera un ni\xf1o. Tras un accidentado divorcio, aunque lucha con todas sus fuerzas para conseguir la custodia de los ni\xf1os, el juez no se la concede. Decide entonces hacerse pasar por una se\xf1ora mayor para poder ser, al menos, la canguro de sus hijos.\n\nPremios\n1993: Oscar: Mejor maquillaje\n1993: 2 Globos de Oro: Mejor pel\xedcula comedia/musical, actor comedia (R. Williams)\n1994: Nominada BAFTA: Mejor maquillaje y peluquer\xeda<img alt="" height="1" src="http://feeds.feedburner.com/~r/newpctorrent/~4/w-X6MOtzWeY" width="1" />',
                                u'original_url': u'http://www.newpct.com/descargar-pelicula/sea-ora-doubtfire-1993/blurayrip/',
                                u'rss_pubdate': datetime.datetime(2016, 7, 3, 12, 6, 24),
                                u'title': u'Se\xf1ora Doubtfire 1993 [BRrip X264 MKV][Castellano]',
                                u'url': u'http://www.newpct.com/descargar-pelicula/sea-ora-doubtfire-1993/blurayrip/'}},
 'store': {u'author': u'Diego10',
           u'description': u'<img alt="Se\xf1ora Doubtfire 1993 [BRrip X264 MKV][Castellano]" class="float: left; margin: 0px 4px 4px 0px;" src="http://images.newpct.com/banco_de_imagenes//m/0000001.jpg" /> T\xedtulo original\nMrs. Doubtfireaka \nAKA\nPap\xe1 por siempre\nSra. Doubtfire, pap\xe1 de por vida\nA\xf1o\n1993\nDuraci\xf3n\n125 min.\nPa\xeds\nEstados Unidos Estados Unidos\nDirector\nChris Columbus\nGui\xf3n\nRandi Mayem Singer, Leslie Dixon\nM\xfasica\nHoward Shore\nFotograf\xeda\nDonald McAlpine\nReparto\nRobin Williams, Sally Field, Pierce Brosnan, Mara Wilson, Harvey Fierstein, Lisa Jakub, Polly Holliday, Robert Prosky, Matthew Lawrence, Anne Haney\nProductora\n20th Century Fox\nG\xe9nero\nComedia. Drama | Familia. Televisi\xf3n. Cine familiar\nSinopsis\nDaniel Hillard es padre y esposo. Sus hijos lo consideran un padre maravilloso, pero su mujer est\xe1 cansada de que se comporte como si tambi\xe9n \xe9l fuera un ni\xf1o. Tras un accidentado divorcio, aunque lucha con todas sus fuerzas para conseguir la custodia de los ni\xf1os, el juez no se la concede. Decide entonces hacerse pasar por una se\xf1ora mayor para poder ser, al menos, la canguro de sus hijos.\n\nPremios\n1993: Oscar: Mejor maquillaje\n1993: 2 Globos de Oro: Mejor pel\xedcula comedia/musical, actor comedia (R. Williams)\n1994: Nominada BAFTA: Mejor maquillaje y peluquer\xeda<img alt="" height="1" src="http://feeds.feedburner.com/~r/newpctorrent/~4/w-X6MOtzWeY" width="1" />',
           u'movie_name': u'Se\xf1ora Doubtfire 1993',
           u'original_url': u'http://www.newpct.com/descargar-pelicula/sea-ora-doubtfire-1993/blurayrip/',
           u'quality': <Quality(resolution=unknown,source=bluray,codec=h264,audio=unknown)>,
           u'rss_pubdate': datetime.datetime(2016, 7, 3, 12, 6, 24),
           u'task': 'descargar peliculas',
           u'title': u'Se\xf1ora Doubtfire 1993 [BRrip X264 MKV][Castellano]',
           u'url': u'http://www.newpct.com/descargar-pelicula/sea-ora-doubtfire-1993/blurayrip/'},
 'task': <flexget.task.Task object at 0x7fc0759dbe90>,
 'traces': [(None, None, u'None of configured reject regexps matched')]}
2016-07-03 22:46 CRITICAL task          descargar peliculas BUG: Unhandled error in plugin list_match: u'movie_year'
2016-07-03 22:46 CRITICAL manager       descargar peliculas An unexpected crash has occurred. Writing crash report to /home/phoneixs/.flexget/crash_report.2016.07.03.224657888583.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.1.4
2016-07-03 22:46 DEBUG    manager       descargar peliculas Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 443, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/list_match.py", line 40, in on_task_filter
    result = thelist.get(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/movie_list.py", line 226, in get
    match = self._find_entry(entry=entry, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/movie_list.py", line 196, in _find_entry
    name, year = entry['movie_name'], entry['movie_year']
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 71, in __getitem__
    item = self.store[key]
KeyError: u'movie_year'
2016-07-03 22:46 WARNING  task          descargar peliculas Aborting task (plugin: list_match)
2016-07-03 22:46 DEBUG    backlog       descargar peliculas Remembering all entries to backlog because of task abort.
2016-07-03 22:46 DEBUG    backlog       descargar peliculas Saving Señora Doubtfire 1993 [BRrip X264 MKV][Castellano]
2016-07-03 22:46 DEBUG    backlog       descargar peliculas Saving Los Borgia 2006 [BRrip X264 MKV][Castellano]
```

### Additional information:

- Flexget Version: 2.1.4
- Python Version: 2.7.12
- Installation method: pip install
- OS and version: Ubuntu 16.04
- Link to crash log: [crashlog.log](http://pastebin.com/qsdhGh0H)

I have modified the file `movie_list.py`  when running flexget to get the information of the entry with the followin code change:

```
        # Fall back to title/year match
        if not entry.get('movie_name'):
            self._parse_title(entry)

        import pprint # THIS WAS ADDED BY ME
        pprint.pprint(vars(entry)) # THIS WAS ADDED BY ME

        if entry.get('movie_name'):
            name, year = entry['movie_name'], entry['movie_year']
        else:
            log.warning('Could not get a movie name, skipping')
            return
```

**Comment by liiight** [comment]
You somehow got `movie_name` but not `movie_year` which I didn't think was possible. I'll try and reproduce this soon. 
In the meantime, you should be able to workaround this by adding `metainfo_movie: yes` to the task.
