### ISSUE TITLE
flexget.plugins.api.movie_queue

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#1275]
C:\Users\Manuel>flexget -V
2.1.12
You are on the latest release.
C:\Users\Manuel>
C:\Users\Manuel>flexget execute
2016-07-15 07:15 CRITICAL plugin                        Exception while loading plugin flexget.plugins.api.movie_queue
2016-07-15 07:15 ERROR    plugin                        module 'html5lib.treebuilders' has no attribute '_base'
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\flexget\plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "c:\python35\lib\site-packages\flexget\plugins\api\movie_queue.py", line 12, in <module>
    from flexget.plugins.filter import movie_queue as mq
  File "c:\python35\lib\site-packages\flexget\plugins\filter\movie_queue.py", line 15, in <module>
    from flexget.utils.imdb import extract_id
  File "c:\python35\lib\site-packages\flexget\utils\imdb.py", line 10, in <module>
    from bs4.element import Tag
  File "c:\python35\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "c:\python35\lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "c:\python35\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\flexget.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\flexget\__init__.py", line 42, in main
    manager.start()
  File "c:\python35\lib\site-packages\flexget\manager.py", line 310, in start
    self.initialize()
  File "c:\python35\lib\site-packages\flexget\manager.py", line 182, in initialize
    plugin.load_plugins(extra_dirs=[os.path.join(self.config_base, 'plugins')])
  File "c:\python35\lib\site-packages\flexget\plugin.py", line 431, in load_plugins
    _load_plugins_from_dirs(extra_dirs)
  File "c:\python35\lib\site-packages\flexget\plugin.py", line 387, in _load_plugins_from_dirs
    __import__(module_name)
  File "c:\python35\lib\site-packages\flexget\plugins\api\movie_queue.py", line 12, in <module>
    from flexget.plugins.filter import movie_queue as mq
  File "c:\python35\lib\site-packages\flexget\plugins\filter\movie_queue.py", line 15, in <module>
    from flexget.utils.imdb import extract_id
  File "c:\python35\lib\site-packages\flexget\utils\imdb.py", line 10, in <module>
    from bs4.element import Tag
  File "c:\python35\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "c:\python35\lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "c:\python35\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

C:\Users\Manuel>

**Comment by crack00r** [comment]
https://bugs.launchpad.net/beautifulsoup/+bug/1603299

**Comment by crack00r** [comment]
https://github.com/html5lib/html5lib-python/commit/19891c55261fef1ee24c1b591502f120e93a6b22

**Comment by liiight** [comment]
Fixed with https://github.com/Flexget/Flexget/compare/3bd988a4d5d2...5495786f04a0
Upgrade to latest
