### ISSUE TITLE
flexget commands fail after Ubuntu 16.04 upgrade with "TypeError: the JSON object must be str, not 'NoneType'"

### ISSUE THREAD

**Issue by jordanade** [Flexget/Flexget#1315]
### Expected behaviour:
Commands execute properly

### Actual behaviour:
```
$ flexget execute
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python3.5/dist-packages/flexget/manager.py", line 311, in start
    self.initialize()
  File "/usr/local/lib/python3.5/dist-packages/flexget/manager.py", line 211, in initialize
    fire_event('manager.startup', self)
  File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/simple_persistence.py", line 183, in load_taskless
    SimplePersistence.load()
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/simple_persistence.py", line 145, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/database.py", line 139, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/json.py", line 112, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```
### Steps to reproduce:
- Step 1: ...
Upgrade Ubuntu from 15.10 to 16.04. Run flexget execute or other command.

#### Config:
N/A

#### Log:
```
$ flexget -L debug execute
2016-08-07 21:36 DEBUG    manager                       Figuring out config load paths
2016-08-07 21:36 DEBUG    manager                       Found config: /home/jordan/.flexget/config.yml
2016-08-07 21:36 DEBUG    manager                       Config file /home/jordan/.flexget/config.yml selected
2016-08-07 21:36 DEBUG    manager                       sys.defaultencoding: utf-8
2016-08-07 21:36 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2016-08-07 21:36 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-08-07 21:36 DEBUG    plugin                        Trying to load plugins from: ['/home/jordan/.flexget/plugins', '/usr/local/lib/python3.5/dist-packages/flexget/plugins']
2016-08-07 21:36 DEBUG    plugin                        ('Plugin `%s` requires `%s` to load.', 'memusage', 'ext lib `guppy`')
2016-08-07 21:36 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-08-07 21:36 DEBUG    plugin                        Plugins took 1.88 seconds to load. 260 plugins in registry.
2016-08-07 21:36 DEBUG    manager                       Connecting to: sqlite:////home/jordan/.flexget/db-config.sqlite
2016-08-07 21:36 DEBUG    manager                       config_name: config
2016-08-07 21:36 DEBUG    manager                       config_base: /home/jordan/.flexget
2016-08-07 21:36 DEBUG    manager                       New config data loaded.
2016-08-07 21:36 DEBUG    schema                        current flexget version already exist in db 2.2.11
2016-08-07 21:36 DEBUG    manager                       Removed /home/jordan/.flexget/.config-lock
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python3.5/dist-packages/flexget/manager.py", line 311, in start
    self.initialize()
  File "/usr/local/lib/python3.5/dist-packages/flexget/manager.py", line 211, in initialize
    fire_event('manager.startup', self)
  File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/simple_persistence.py", line 183, in load_taskless
    SimplePersistence.load()
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/simple_persistence.py", line 145, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/database.py", line 139, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/json.py", line 112, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

### Additional information:

- Flexget Version: 2.2.11
- Python Version: 3.5.2
- Installation method: pip
- OS and version: Xubuntu 16.04.1

**Comment by jordanade** [comment]
Please let me know if there's any additional information I can provide.

**Comment by cvium** [comment]
Did you only upgrade OS or also Flexget? If so, what was the old version of Flexget?

**Comment by jordanade** [comment]
I did try several things before posting this bug, including upgrading flexget to the latest version. (Unfortunately I don't have a way of determining what the older version was--something from several months to a year ago.) But the bug was present in the older version of flexget as well. It seems that something in the OS upgrade caused this.

**Comment by crawln45** [comment]
older database before the simple persistance migration from what it looks like. easiest fix would be to drop the simple persistance table have it recreated from what I can see.

**Comment by jordanade** [comment]
OK. How do I do that? I tried:
```sudo pip install flexget --upgrade --force-reinstall```
Then when running ```flexget execute``` I got a slight variation on the above error:
```
$ flexget execute
2016-08-13 04:58 INFO     manager                       Database upgrade is required. Attempting now.
2016-08-13 04:58 INFO     schema                        Plugin tvmaze database is not upgradable. Flushing data and regenerating.
2016-08-13 04:58 INFO     schema                        Plugin api_tmdb database is not upgradable. Flushing data and regenerating.
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 9, in <module>
    load_entry_point('FlexGet==2.2.17', 'console_scripts', 'flexget')()
  File "/usr/local/lib/python3.5/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python3.5/dist-packages/flexget/manager.py", line 311, in start
    self.initialize()
  File "/usr/local/lib/python3.5/dist-packages/flexget/manager.py", line 211, in initialize
    fire_event('manager.startup', self)
  File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/simple_persistence.py", line 183, in load_taskless
    SimplePersistence.load()
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/simple_persistence.py", line 145, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/database.py", line 139, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/usr/local/lib/python3.5/dist-packages/flexget/utils/json.py", line 112, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

**Comment by macmadness86** [comment]
I have the same JSON error running under python 3.5.

```
~/py-352/bin $ ./flexget -L debug execute
2016-09-10 08:58 DEBUG    manager                       Figuring out config load paths
2016-09-10 08:58 DEBUG    manager                       Found config: /home/flexget/.config/flexget/config.yml
2016-09-10 08:58 DEBUG    manager                       Config file /home/flexget/.config/flexget/config.yml selected
2016-09-10 08:58 DEBUG    manager                       sys.defaultencoding: utf-8
2016-09-10 08:58 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2016-09-10 08:58 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-09-10 08:58 DEBUG    plugin                        Trying to load plugins from: ['/home/flexget/.config/flexget/plugins', '/home/flexget/py-352/lib/python3.5/site-packages/flexget/plugins']
2016-09-10 08:58 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-09-10 08:58 DEBUG    plugin                        ('Plugin `%s` requires `%s` to load.', 'memusage', 'ext lib `guppy`')
2016-09-10 08:58 DEBUG    plugin                        Plugins took 1.13 seconds to load. 257 plugins in registry.
2016-09-10 08:58 DEBUG    manager                       Connecting to: sqlite:////home/flexget/.config/flexget/db-config.sqlite
2016-09-10 08:58 DEBUG    manager                       config_name: config
2016-09-10 08:58 DEBUG    manager                       config_base: /home/flexget/.config/flexget
2016-09-10 08:58 DEBUG    manager                       New config data loaded.
2016-09-10 08:58 DEBUG    schema                        current flexget version already exist in db 2.3.21
2016-09-10 08:58 DEBUG    manager                       Removed /home/flexget/.config/flexget/.config-lock
Traceback (most recent call last):
  File "./flexget", line 11, in <module>
    sys.exit(main())
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/manager.py", line 311, in start
    self.initialize()
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/manager.py", line 211, in initialize
    fire_event('manager.startup', self)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/utils/simple_persistence.py", line 183, in load_taskless
    SimplePersistence.load()
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/utils/simple_persistence.py", line 145, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/home/flexget/py-352/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/utils/database.py", line 139, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/utils/json.py", line 112, in loads
    return json.loads(*args, **kwargs)
  File "/home/flexget/py-352/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

**Comment by cvium** [comment]
Easiest solution is to run `flexget database reset-plugin simple_persistence`. It will drop the simple persistence table.

**Comment by macmadness86** [comment]
Nice try.
```
./flexget database reset-plugin simple_persistence
Traceback (most recent call last):
  File "./flexget", line 11, in <module>
    sys.exit(main())
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/manager.py", line 311, in start
    self.initialize()
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/manager.py", line 211, in initialize
    fire_event('manager.startup', self)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/utils/simple_persistence.py", line 183, in load_taskless
    SimplePersistence.load()
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/utils/simple_persistence.py", line 145, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/home/flexget/py-352/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/utils/database.py", line 139, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/home/flexget/py-352/lib/python3.5/site-packages/flexget/utils/json.py", line 112, in loads
    return json.loads(*args, **kwargs)
  File "/home/flexget/py-352/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

**Comment by cvium** [comment]
Use `sqlite3` then

`sqlite3 db-config.sqlite`

`sqlite> DROP TABLE simple_persistence;`

**Comment by macmadness86** [comment]
Ok doing that got rid of the error. Something else with encoding came up. It is likely an unrelated problem.

For the record, here is what I did:
```
sqlite3 ./.config/flexget/db-config.sqlite
SQLite version 3.14.1 2016-08-11 18:53:32
Enter ".help" for usage hints.
sqlite> DROP TABLE simple_persistence
   ...> ;
sqlite> .exit
```

**Comment by cvium** [comment]
What version of flexget is this? And can you post the full stack trace?

**Comment by macmadness86** [comment]
flexget v2.3.21

After running `./flexget --debug-warnings execute`, I realized my local py-352 install did not have transmissionrpc installed. I did that. Now I am getting:

`ERROR    task          monitor_showRSS Warning during plugin all_series: bad escape \w`

which leads me to think this is a `~/.config/flexget/config.yml` problem for me now. If I cannot solve this in 10 minutes, I will setup a full trace. I have never done that in Python before.

**Comment by cvium** [comment]
Looks like a bad rss feed. What's your config + feed?

**Comment by macmadness86** [comment]
Snippet:
```
tasks:
  monitor_showRSS:
    #get list of magnets from showrss
    rss: http://showrss.info/user/66880.rss?magnets=true&namespaces=true&name=clean&quality=null&re=null
    # fetch all the feed series because showrss does filtering, no need for series: filter.
    all_series: yes
    template: outlet_tv
```

**Comment by cvium** [comment]
Works fine for me with py 3.5.2 on Windows 10.

**Comment by macmadness86** [comment]
You're right, it does work. Now I just have to get my systemd unit file working correctly. Thank for the help! The issue has been solved for me!
