### ISSUE TITLE
Series plugin crash with guessit parser

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#1326]
```
2016-08-12 04:55 VERBOSE  series        Series_Collection_DE Found different quality for The.Player.2015.S01E05.House.Rules.German.DD20.Dubbed.DL.1080p.iTunesHD.AVC-TVS. Was 1080p dd5.1, overriding with 1080p.
2016-08-12 04:55 VERBOSE  series        Series_Collection_DE Found different quality for The.Player.2015.S01E02.Das.Spiel.beginnt.German.DD20.Dubbed.DL.720p.iTunesHD.AVC-TVS. Was 720p dd5.1, overriding with 720p.
2016-08-12 05:19 CRITICAL task          Series_Collection_DE BUG: Unhandled error in plugin series: list index out of range
2016-08-12 05:19 CRITICAL manager       Series_Collection_DE An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.08.12.051923693217.log. Please verify you are running the latest version of flexget $
2016-08-12 05:19 WARNING  task          Series_Collection_DE Aborting task (plugin: series)
2016-08-12 05:22 VERBOSE  trakt_list    Series_Watchlist Retrieving `shows` list `watchlist`
2016-08-12 05:22 WARNING  trakt_list    Series_Watchlist No data returned from trakt for shows list watchlist.
2016-08-12 05:22 VERBOSE  trakt_list    Series_Watchlist Retrieving `shows` list `watchlist`
2016-08-12 05:22 VERBOSE  utils.requests Series_Watchlist Waiting 1.78 seconds until next request to trakt.tv
2016-08-12 05:22 WARNING  trakt_list    Series_Watchlist No data returned from trakt for shows list watchlist.
2016-08-12 05:22 WARNING  configure_series Series_Watchlist Input trakt_list did not return anything
2016-08-12 05:22 VERBOSE  discover      Series_Watchlist Ignored duplicate title `Eureka S01E01`
2016-08-12 05:22 VERBOSE  discover      Series_Watchlist Discovering 346 titles ...
2016-08-12 05:22 VERBOSE  discover      Series_Watchlist Searching for `iZombie S01E01` with plugin `search_rss` (1 of 346)

```

```
2016-08-12 04:55 VERBOSE  series        Series_Collection_DE Found different quality for The.Player.2015.S01E02.Das.Spiel.beginnt.German.DD20.Dubbed.DL.720p.iTunesHD.AVC-TVS. Was 720p dd5.1, overriding with 720p.
2016-08-12 05:19 CRITICAL task          Series_Collection_DE BUG: Unhandled error in plugin series: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flexget/task.py", line 444, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/filter/series.py", line 1129, in on_task_metainfo
    self.parse_series(task.entries, series_name, series_config)
  File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/filter/series.py", line 1251, in parse_series
    populate_entry_fields(entry, parsed, config)
  File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/filter/series.py", line 876, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/parsers/parser_common.py", line 553, in pack_identifier
    return self.identifier
  File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/parsers/parser_common.py", line 544, in identifier
    return self.identifiers[0]
IndexError: list index out of range

```

**Comment by crack00r** [comment]
Config: https://github.com/crack00r/Flexget-Config

**Comment by crack00r** [comment]
i deactivate guessit, and give it a try

**Comment by gazpachoking** [comment]
Pretty sure I fixed this, if there was another instance re-opening with the title of the release that was causing the crash will help.
