### ISSUE TITLE
BUG: Unhandled error in plugin rtorrent  ( while loading Magnet ) 

### ISSUE THREAD

**Issue by hitokiri8x** [Flexget/Flexget#1328]
### Expected behaviour:
add torrents obtained from showrss to rTorrent via scgi

### Actual behaviour:
a critical error is generated, flexget does not add torrent and terminate

### Steps to reproduce:
flexget execute

#### Config:
```
tasks:
  showrss task:
    rss: http://showrss.info/user/xxx
    all_series: yes
    rtorrent:
      uri: scgi://localhost:5000
      path: /nas/{{series_name}}
```
  
#### Log:
```
2016-08-12 09:40 VERBOSE  details       showrss task    Summary - Accepted: 10 (Rejected: 1 Undecided: 0 Failed: 0)
2016-08-12 09:40 CRITICAL task          showrss task    BUG: Unhandled error in plugin rtorrent: expected bytes or bytearray, not str
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flexget/task.py", line 444, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/plugin_rtorrent.py", line 473, in on_task_output
    self.add_entry(client, entry, options, start=config['start'], mkdir=config['mkdir'])
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/plugin_rtorrent.py", line 584, in add_entry
    resp = client.load(torrent_raw, fields=options, start=start, mkdir=mkdir)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/plugin_rtorrent.py", line 261, in load
    params = ['', xmlrpc_client.Binary(raw_torrent)]
  File "/usr/lib/python3.4/xmlrpc/client.py", line 391, in __init__
    data.__class__.__name__)

```

### Additional information:

- Flexget Version:  2.2.15
- Python Version: 3.4.2
- Installation method:  pip3
- OS and version:  raspbian jessy

**Comment by hitokiri8x** [comment]
with a quick inspection the problem is that raw_torrent is a magnet uri and not a bitearray.
not sure about a quick solving or if it is a future feature, limit of rtorrent  or bug
