### ISSUE TITLE
BUG: Discover/Piratebay: "'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by wtluke** [Flexget/Flexget#1359]
This has been happening to me on `2.3.3` - can't see it mentioned, but sorry if it's a dupe!

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 472, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 290, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 155, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/sites/piratebay.py", line 151, in search
    entry['content_size'] = parse_filesize(size.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

Config:

```
  moviesPBHQ:
    verify_ssl_certificates: no
    discover:
      what:
        - movie_list:
            list_name: allmyfilms
            strip_year: yes
      from:
        - piratebay:
            category: movies
    template: movietemplate
    priority: 80
    seen: local
    quality:
      - 720p+
      - webrip+
```

**Comment by cvium** [comment]
Can you provide your movie_list as well? `flexget movie-list list allmyfilms`

**Comment by wtluke** [comment]
```
┌159 Movies in movie list: `allmyfilms`─────────────────────────┬────────────┬────────────────┬───────────┬─────────┬───────────┐
│ Movie Name                                                    │ Movie year │ trakt_movie_id │ imdb_id   │ tmdb_id │ bluray_id │
├───────────────────────────────────────────────────────────────┼────────────┼────────────────┼───────────┼─────────┼───────────┤
│ Same Kind of Different as Me                                  │ 2017       │                │ tt1230168 │         │           │
│ Adolf Hitler: The Greatest Story Never Told                   │ 2013       │                │ tt3526810 │         │           │
│ Gimme Danger                                                  │ 2016       │                │ tt1714917 │         │           │
│ Battle of Soho                                                │ 2016       │                │ tt4318548 │         │           │
│ Sour Grapes                                                   │ 2016       │                │ tt5728684 │         │           │
│ GrassRoots: The Cannabis Revolution                           │ 2016       │                │ tt5650964 │         │           │
│ The Good Neighbor                                             │ 2016       │                │ tt2262315 │         │           │
│ Split                                                         │ 2017       │                │ tt4972582 │         │           │
│ Operation Chromite                                            │ 2016       │                │ tt4939066 │         │           │
│ In a Valley of Violence                                       │ 2016       │                │ tt3608930 │         │           │
│ Swallows and Amazons                                          │ 2016       │                │ tt1227183 │         │           │
│ Arrival                                                       │ 2016       │                │ tt2543164 │         │           │
│ XOXO                                                          │ 2016       │                │ tt4855748 │         │           │
│ Dunkirk                                                       │ 2017       │                │ tt5013056 │         │           │
│ Manchester by the Sea                                         │ 2016       │                │ tt4034228 │         │           │
│ The Death of Stalin                                           │ 2017       │                │ tt4686844 │         │           │
│ Tulip Fever                                                   │ 2017       │                │ tt0491203 │         │           │
│ Euphoria                                                      │ 2017       │                │ tt5698320 │         │           │
│ Submergence                                                   │ 2017       │                │ tt3563262 │         │           │
│ Genius                                                        │ 2016       │                │ tt1703957 │         │           │
│ Café Society                                                  │ 2016       │                │ tt4513674 │         │           │
│ La La Land                                                    │ 2016       │                │ tt3783958 │         │           │
│ A Monster Calls                                               │ 2016       │                │ tt3416532 │         │           │
│ Doctor Strange                                                │ 2016       │                │ tt1211837 │         │           │
│ Sully                                                         │ 2016       │                │ tt3263904 │         │           │
│ The Light Between Oceans                                      │ 2016       │                │ tt2547584 │         │           │
│ Hell or High Water                                            │ 2016       │                │ tt2582782 │         │           │
│ A German Life                                                 │ 2016       │                │ tt5135434 │         │           │
│ David Brent: Life on the Road                                 │ 2016       │                │ tt3137630 │         │           │
│ Hostiles                                                      │ 2017       │                │ tt5478478 │         │           │
│ HHhH                                                          │ 2016       │                │ tt3296908 │         │           │
│ American Pastoral                                             │ 2016       │                │ tt0376479 │         │           │
│ T2: Trainspotting 2                                           │ 2017       │                │ tt2763304 │         │           │
│ Mr. Burberry                                                  │ 2016       │                │ tt5620080 │         │           │
│ Thrilla in Manila                                             │ 2008       │                │ tt1330059 │         │           │
│ Absolutely Fabulous: The Movie                                │ 2016       │                │ tt2112096 │         │           │
│ Logan Lucky                                                   │            │                │ tt5439796 │         │           │
│ Bridge of Spies: U-2 Spy Plane                                │ 2016       │                │ tt5443826 │         │           │
│ A Case of the Cold War: 'Bridge of Spies'                     │ 2016       │                │ tt5443804 │         │           │
│ Spy Swap: Looking Back on the Final Act of 'Bridge of Spies'  │ 2016       │                │ tt5443846 │         │           │
│ Complete Unknown                                              │ 2016       │                │ tt4230700 │         │           │
│ Secret History of Religion: Knights Templar                   │ 2006       │                │ tt0785018 │         │           │
│ I, Daniel Blake                                               │ 2016       │                │ tt5168192 │         │           │
│ The Accountant                                                │ 2016       │                │ tt2140479 │         │           │
│ Suburbicon                                                    │ 2017       │                │ tt0491175 │         │           │
│ A Beautiful Planet                                            │ 2016       │                │ tt2800050 │         │           │
│ Only the Dead                                                 │ 2015       │                │ tt3587396 │         │           │
│ Limmy's Show!                                                 │ 2009       │                │ tt1495848 │         │           │
│ The Day Before Disclosure                                     │ 2010       │                │ tt1807036 │         │           │
│ Collide                                                       │ 2016       │                │ tt2126235 │         │           │
│ Untitled George Clooney Project                               │            │                │ tt2547350 │         │           │
│ The Director                                                  │            │                │ tt3471206 │         │           │
│ The Tunnels                                                   │            │                │ tt4158104 │         │           │
│ The Boy Who Kicked the Hornet's Nest                          │            │                │ tt2366792 │         │           │
│ Untitled Jimi Hendrix Project                                 │            │                │ tt1496028 │         │           │
│ Agent Storm                                                   │            │                │ tt3910816 │         │           │
│ Ready Player One                                              │ 2017       │                │ tt1677720 │         │           │
│ Speaking Is Difficult                                         │ 2016       │                │ tt5424742 │         │           │
│ The Mystery of Flight 777                                     │ 2016       │                │ tt2046153 │         │           │
│ Salt and Fire                                                 │ 2016       │                │ tt4441150 │         │           │
│ Free Fire                                                     │ 2016       │                │ tt4158096 │         │           │
│ My Scientology Movie                                          │ 2015       │                │ tt5111874 │         │           │
│ Catching the Sun                                              │ 2015       │                │ tt1698654 │         │           │
│ Billion Dollar Bully                                          │ 2016       │                │ tt4645636 │         │           │
│ Vente a Las Vegas, nena: Un retrato de Rebeca Linares         │ 2009       │                │ tt1566002 │         │           │
│ Florence Foster Jenkins                                       │ 2016       │                │ tt4136084 │         │           │
│ Tawai                                                         │ 2016       │                │ tt3638960 │         │           │
│ Patient Zero                                                  │ 2016       │                │ tt3458254 │         │           │
│ In Darkness                                                   │            │                │ tt5164184 │         │           │
│ Shepherds and Butchers                                        │ 2016       │                │ tt4627352 │         │           │
│ Alone in Berlin                                               │ 2016       │                │ tt3026488 │         │           │
│ Felt                                                          │ 2017       │                │ tt5175450 │         │           │
│ Free Speech Fear Free                                         │ 2016       │                │ tt4462056 │         │           │
│ Untitled Kathryn Bigelow Project                              │ 2017       │                │ tt5390504 │         │           │
│ The True American                                             │            │                │ tt3731964 │         │           │
│ Untitled Bowe Bergdahl Project                                │            │                │ tt4523790 │         │           │
│ The Jihadis Next Door                                         │ 2016       │                │ tt5366234 │         │           │
│ Lo and Behold, Reveries of the Connected World                │ 2016       │                │ tt5275828 │         │           │
│ Almost Holy                                                   │ 2015       │                │ tt3080844 │         │           │
│ Things That Fall from the Sky                                 │ 2016       │                │ tt4932106 │         │           │
│ FlySpy                                                        │ 2016       │                │ tt4551300 │         │           │
│ The Condemned                                                 │ 2013       │                │ tt3164988 │         │           │
│ Our Kind of Traitor                                           │ 2016       │                │ tt1995390 │         │           │
│ Official Secrets                                              │            │                │ tt5431890 │         │           │
│ The Land of the Enlightened                                   │ 2016       │                │ tt2338774 │         │           │
│ When Two Worlds Collide                                       │ 2016       │                │ tt5278932 │         │           │
│ Nuts!                                                         │ 2016       │                │ tt5236900 │         │           │
│ Life, Animated                                                │ 2016       │                │ tt3917210 │         │           │
│ Sonita                                                        │ 2015       │                │ tt5278928 │         │           │
│ A United Kingdom                                              │            │                │ tt3387266 │         │           │
│ How to Talk to Girls at Parties                               │ 2016       │                │ tt3859310 │         │           │
│ Baby Driver                                                   │ 2017       │                │ tt3890160 │         │           │
│ Billionaire Boys Club                                         │ 2016       │                │ tt5179598 │         │           │
│ Collateral Beauty                                             │ 2016       │                │ tt4682786 │         │           │
│ The Promise                                                   │ 2016       │                │ tt4776998 │         │           │
│ War Machine                                                   │ 2016       │                │ tt4758646 │         │           │
│ Flying Horse                                                  │ 2016       │                │ tt2983414 │         │           │
│ Deepwater Horizon                                             │ 2016       │                │ tt1860357 │         │           │
│ Fantastic Beasts and Where to Find Them                       │ 2016       │                │ tt3183660 │         │           │
│ Five Seconds of Silence                                       │ 2016       │                │ tt3640424 │         │           │
│ Miss Peregrine's Home for Peculiar Children                   │ 2016       │                │ tt1935859 │         │           │
│ Magik                                                         │ 2016       │                │ tt1713496 │         │           │
│ Mapplethorpe: Look at the Pictures                            │ 2016       │                │ tt5275838 │         │           │
│ The Blackout Experiments                                      │ 2016       │                │ tt5222646 │         │           │
│ Tickled                                                       │ 2016       │                │ tt5278506 │         │           │
│ The Lovers and the Despot                                     │ 2016       │                │ tt5278868 │         │           │
│ Swiss Army Man                                                │ 2016       │                │ tt4034354 │         │           │
│ Billy Lynn's Long Halftime Walk                               │ 2016       │                │ tt2513074 │         │           │
│ Bridget Jones's Baby                                          │ 2016       │                │ tt1473832 │         │           │
│ Silence                                                       │ 2016       │                │ tt0490215 │         │           │
│ An Electric Samurai in London                                 │ 2016       │                │ tt4666326 │         │           │
│ All the Wild Horses                                           │ 2016       │                │ tt2636480 │         │           │
│ Attacking the Devil: Harold Evans and the Last Nazi War Crime │ 2014       │                │ tt3779818 │         │           │
│ Walking Man                                                   │ 2014       │                │ tt3211206 │         │           │
│ Thrilla in Manila                                             │ 2018       │                │ tt5259188 │         │           │
│ Hector                                                        │ 2015       │                │ tt3917118 │         │           │
│ Heart of a Dog                                                │ 2015       │                │ tt4935446 │         │           │
│ Like Air                                                      │ 2015       │                │ tt4045146 │         │           │
│ The Longest Cocktail Party                                    │            │                │ tt1653086 │         │           │
│ The Modern Ocean                                              │            │                │ tt3848080 │         │           │
│ Lion                                                          │ 2016       │                │ tt3741834 │         │           │
│ Una                                                           │ 2016       │                │ tt2315582 │         │           │
│ The Secret Scripture                                          │ 2016       │                │ tt3344694 │         │           │
│ This Changes Everything                                       │ 2015       │                │ tt1870548 │         │           │
│ Something Better to Come                                      │ 2014       │                │ tt4188338 │         │           │
│ Exotica, Erotica, Etc.                                        │ 2015       │                │ tt4517578 │         │           │
│ Censored Voices                                               │ 2015       │                │ tt3457376 │         │           │
│ The Challenge                                                 │ 2016       │                │ tt4428892 │         │           │
│ Made You Look                                                 │ 2015       │                │ tt3996014 │         │           │
│ Londinium                                                     │            │                │ tt4351540 │         │           │
│ A Syrian Love Story                                           │ 2015       │                │ tt4684410 │         │           │
│ Downsizing                                                    │ 2017       │                │ tt1389072 │         │           │
│ The Great Wall                                                │ 2016       │                │ tt2034800 │         │           │
│ Winter                                                        │ 2015       │                │ tt2902126 │         │           │
│ Asylum                                                        │ 2016       │                │ tt4964772 │         │           │
│ The Banksy Job                                                │ 2016       │                │ tt4406572 │         │           │
│ Voyage of Time                                                │ 2016       │                │ tt1945228 │         │           │
│ The Circle                                                    │ 2016       │                │ tt4287320 │         │           │
│ Ithaca                                                        │ 2015       │                │ tt3501590 │         │           │
│ Leavey                                                        │ 2016       │                │ tt4899370 │         │           │
│ Everest                                                       │            │                │ tt2420740 │         │           │
│ Snowden                                                       │ 2016       │                │ tt3774114 │         │           │
│ Planetarium                                                   │ 2016       │                │ tt4680196 │         │           │
│ Weightless                                                    │ 2016       │                │ tt2062700 │         │           │
│ Jackie                                                        │ 2017       │                │ tt1619029 │         │           │
│ An Open Secret                                                │ 2014       │                │ tt3677412 │         │           │
│ Return to Timbuktu                                            │            │                │ tt3578650 │         │           │
│ Every Last Child                                              │ 2014       │                │ tt4121958 │         │           │
│ The Lost Symbol                                               │            │                │ tt1422137 │         │           │
│ Utopia                                                        │ 2015       │                │ tt3095238 │         │           │
│ The Barefoot Bandit Documentary                               │ 2015       │                │ tt1884273 │         │           │
│ Reckoning with Torture                                        │ 2016       │                │ tt2252270 │         │           │
│ Queen of Katwe                                                │ 2016       │                │ tt4341582 │         │           │
│ Lange                                                         │ 2017       │                │ tt2008681 │         │           │
│ Strangers                                                     │            │                │ tt0455788 │         │           │
│ The Reincarnation of Peter Proud                              │ 2016       │                │ tt1544871 │         │           │
│ London Fields                                                 │ 2016       │                │ tt1273221 │         │           │
│ Expedition: Northern California                               │ 2015       │                │ tt4046844 │         │           │
│ Between Snow and Stars                                        │ 2015       │                │ tt4103060 │         │           │
└───────────────────────────────────────────────────────────────┴────────────┴────────────────┴───────────┴─────────┴───────────┘
```

**Comment by cvium** [comment]
A little more than I anticipated. Do you know which movie it fails on?

**Comment by liiight** [comment]
If you'd add `--table-type github` to that command, it'll produce a github style table. Just sayin :winking:

**Comment by wtluke** [comment]
It errors _after_ "Walking Man". So it could be that one. http://www.imdb.com/title/tt3211206

**Comment by lostsubstance** [comment]
I now get this in my tv task (flexget 2.3.5)

```
2016-08-23 23:09 CRITICAL task          get-tv          BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 472, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 290, in on_task_input
    return self.execute_searches(config, entries, task)
  File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 155, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "c:\python27\lib\site-packages\flexget\plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\sites\piratebay.py", line 151, in search
    entry['content_size'] = parse_filesize(size.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by cvium** [comment]
What does it choke on?

**Comment by lostsubstance** [comment]
I just ran it manually with trace logging and it didn't fail (including a --discover-now)  But i have two crash files from earlier today.  Since it didn't fail in the manual run I don't know what entry it choked on.

**Comment by cvium** [comment]
Well, I can't really fix it until someone tells me how to reproduce it.

**Comment by lostsubstance** [comment]
It may have just been an unexpected response.

**Comment by lostsubstance** [comment]
I added a log to the line just before the crash... hopefully i'll have something by tomorrow
```
if not size:
    log.error("No size for %s" %  entry['title'])
    continue
```

**Comment by Tommatheussen** [comment]
You might also want to consider placing a log on the size in between these 2 lines:
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/sites/piratebay.py#L148-L149

That way we don't only have the title from the entry, but also the size as extracted from the page (since the regex might be wrong). If that size is also None then we know the extract is somehow incorrect.

**Comment by lostsubstance** [comment]
i got a hit. the first line is where you suggested putting an additional log, second line is my original log.

```
2016-08-26 19:09 ERROR    piratebay     get-tv          Size doesnt match: Uploaded 
2016-08-26 19:09 ERROR    piratebay     get-tv          No size for Dark Matter S02E09 2016 HDTV x264 - RARBG
```

**Comment by cvium** [comment]
It would be better to log `link.find_next(attrs={'class': 'detDesc'}).contents`

**Comment by Tommatheussen** [comment]
Could this be becuase of how it finds the links? I noticed that newer torrents get added with the following uploaded string: `Uploaded <b>26 minutes ago</b> ...`

Noticed the bold tags, maybe that's where it chokes on?
