### ISSUE TITLE
Seen search "list assignment index out of range"

### ISSUE THREAD

**Issue by Meliox** [Flexget/Flexget#1373]
### Expected behaviour:
Return that "xxxxxxxxxx" cannot be found

### Actual behaviour:
IndexError: list assignment index out of range

### Steps to reproduce:
- Step 1: Use seen search and search for an item that you are sure isn't in your db.
- Step 2: flexget -c autodl.yml seen search "xxxxxxxxxx" 

#### Config:
```
Use any config with any database
```
  
#### Log:
```
flexget -c autodl.yml seen search "xxxxxxxxxx"
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    load_entry_point('FlexGet==2.3.8', 'console_scripts', 'flexget')()
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 312, in start
    self.handle_cli()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 339, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/seen.py", line 18, in do_cli
    seen_search(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/seen.py", line 60, in seen_search
    del table_data[-1]
IndexError: list assignment index out of range

```

### Additional information:

- Flexget Version: 2.3.8
- Python Version: Python 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04.1 LTS
- Link to crash log: NA

**Comment by liiight** [comment]
Do you get that with all search terms?

**Comment by Meliox** [comment]
Only for search terms I don't have in my database. For search terms I do
have, the result is returned.

Den 27. aug. 2016 07.56 skrev "Or Carmi" <notifications@github.com>:

**Comment by liiight** [comment]
Ah, important bit :wink:
