### ISSUE TITLE
Seriejunkies rewrite crashing

### ISSUE THREAD

**Issue by kasperj** [Flexget/Flexget#1409]
I commented line 168 to 171 and all works fine,
no time to have a deeper look right now,
maybe someone else has

```
2016-09-16 21:34 DEBUG    urlrewriter   serienjk_de_local Checking 2 entries
2016-09-16 21:34 DEBUG    urlrewriter   serienjk_de_local Url rewriting http://serienjunkies.org/gotham/gotham-staffel-2-blu-ray-sd720p1080p/
2016-09-16 21:34 DEBUG    utils.requests serienjk_de_local Fetching http://serienjunkies.org/gotham/gotham-staffel-2-blu-ray-sd720p1080p/
2016-09-16 21:34 DEBUG    serienjunkies serienjk_de_local Title seems to describe multiple episodes
2016-09-16 21:34 DEBUG    plugin        serienjk_de_local decorator caught ValueError. handled traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/sites/serienjunkies.py", line 116, in parse_downloads
    if not self.check_language(episode_lang):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/sites/serienjunkies.py", line 169, in check_language
    languages = languages[:languages.index("+")]
ValueError: substring not found
2016-09-16 21:34 WARNING  urlrewriter   serienjk_de_local URL rewriting serienjunkies failed: substring not found
```

**Comment by cvium** [comment]
The string it's looking for has changed. It's not longer separate by a +. Also not very nice code. Would be better to just do `languages.split('+', 1)[0]`
