### ISSUE TITLE
AlphaRatio plugin bug?

### ISSUE THREAD

**Issue by mannionpatrick** [Flexget/Flexget#1420]
### Expected behaviour:
next_series_episodes starts to get torrents from Alpharatio

### Actual behaviour:
Crash. 
CRITICAL task          downloads_search BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'group'

### Steps to reproduce:
- Step 1: ... heck if I know. It's consistent with my configuration, so probably my fault...

#### Config:
http://pastebin.com/1XwQe4Dt
  
#### Log:
```
2016-09-23 07:49 DEBUG    alpharatio    downloads_search requesting: https://alpharatio.cc/torrents.php?searchstr=The+Flash+S01E01&order_by=seeders&order_way=desc&search_submit=1&action=basic&freeleech=0
2016-09-23 07:49 CRITICAL task          downloads_search BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'group'
2016-09-23 07:49 CRITICAL manager       downloads_search An unexpected crash has occurred. Writing crash report to /Users/patrick/.config/flexget/crash_report.2016.09.23.074930380420.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.3.27
2016-09-23 07:49 DEBUG    manager       downloads_search Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flexget/task.py", line 478, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 290, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 155, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/sites/alpharatio.py", line 209, in search
    e['content_size'] = parse_filesize(size.group(0))
AttributeError: 'NoneType' object has no attribute 'group'
2016-09-23 07:49 WARNING  task          downloads_search Aborting task (plugin: discover)
2016-09-23 07:49 DEBUG    task_queue                    task downloads_search aborted: TaskAbort(reason=BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'group', silent=False)
2016-09-23 07:49 DEBUG    task_queue                    task queue shut down
```
### Additional information:

- Flexget Version: 2.3.27
- Python Version: 2.7.11
- Installation method: pip
- OS and version: macOS 10.12
- Link to crash log: http://pastebin.com/6cAn7Tdp

**Comment by cvium** [comment]
This is not related to the bug, but I think you've misunderstood what the rsskey is in the TL search plugin.

**Comment by liiight** [comment]
Dunno, working for me:
```
2016-09-25 11:35 DEBUG    alpharatio    alpha_test      requesting: https://alpharatio.cc/torrents.php?order_way=desc&order_by=seeders&searchstr=The+Flash+S01E01&freeleech=0&action=basic&search_submit=1
2016-09-25 11:35 DEBUG    discover      alpha_test      Discovered 1 entries from alpharatio
2016-09-25 11:35 DEBUG    backlog       alpha_test      0 entries purged from backlog
2016-09-25 11:35 VERBOSE  details       alpha_test      Produced 1 entries.
2016-09-25 11:35 VERBOSE  task          alpha_test      ACCEPTED: `The.Flash.2014.S01E01.WEB.x264-XXXX` by accept_all plugin
```

**Comment by cvium** [comment]
I added some logging. Upgrade to 2.3.36 when it's released and post the crash log if it happens again.

**Comment by mannionpatrick** [comment]
OK - back from business trip. Updated to 2.3.37, still having the issue. Debug log [here](http://pastebin.com/5n2Db7c8), crash log [here](http://pastebin.com/tFqcGV2m).
