### ISSUE TITLE
Torrent Alive crashing

### ISSUE THREAD

**Issue by waynethomas69** [Flexget/Flexget#1434]
Torrent alive keeps crashing in what appears to be a very similar issue to #1117. Was working fine for quite a while with zero issues, but has suddenly started doing this (I'm guessing because of the particular torrent it has encountered). As a result no torrents are downloaded and the affected task has ground to a halt (others that don't use torrent alive are fine).

flexget version 2.3.39, python version 2.7.9

```
2016-10-05 20:40 DEBUG    torrent_alive search series   Checking for seeds for Greys.Anatomy.S10E01E02.720p.HDTV.X264-DIMENSION:
2016-10-05 20:40 DEBUG    torrent_alive search series   Checking for seeds from http://piratebg.com/scrape.php?pid=af38b3a5251647561a543d4a892d5e66&i$
2016-10-05 20:40 DEBUG    utils.requests search series   Fetching http://piratebg.com/scrape.php?pid=af38b3a5251647561a543d4a892d5e66&info_hash=%C0p%$
2016-10-05 20:40 CRITICAL task          search series   BUG: Unhandled error in plugin torrent_alive: 'generator' object is not an iterator
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 245, in on_task_output
    seeds = get_tracker_seeds(tracker, info_hash)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 162, in get_tracker_seeds
    return get_http_seeds(url, info_hash)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 138, in get_http_seeds
    data = bdecode(requests.get(url).content).get('files')
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/bittorrent.py", line 139, in bdecode
    data = decode_item(functools.partial(next, src), next(src))  # pylint:disable=E1101
  File "/usr/local/lib/python2.7/dist-packages/future/builtins/newnext.py", line 62, in newnext
    iterator.__class__.__name__))
TypeError: 'generator' object is not an iterator
```

**Comment by chewy74** [comment]
I'm getting crashes from this plugin as well 

Flexget Version: 2.5.4 

If you need a debug log let me know. Thanks 
```
2016-10-27 15:47 WARNING  tmdb_lookup   passthepopcorn  TMDB lookup failed for Robin Williams Remembered [2014] by Steve Boettcher - x264 / HDTV / MKV / 720p
2016-10-27 16:01 WARNING  tmdb_lookup   passthepopcorn  TMDB lookup failed for "The American Experience" Tesla [2016] - x264 / HDTV / MKV / Other
2016-10-27 16:02 INFO     download      passthepopcorn  Downloading: You Will Kill [2015] by Marwan Mokbel - x264 / Blu-ray / MKV / Other / Scene / Freeleech!
2016-10-27 16:02 INFO     transmission  passthepopcorn  "You Will Kill [2015] by Marwan Mokbel - x264 / Blu-ray / MKV / Other / Scene / Freeleech!" torrent added to transmission
2016-10-27 16:43 WARNING  task          trash           Task doesn't have any input plugins, you should add (at least) one!
2016-10-27 16:43 WARNING  task          trash           Task does not have any filter plugins to accept entries. You need at least one to accept the entries you  want.
2016-10-27 16:43 WARNING  task          trash           Task doesn't have any output plugins, you should add (at least) one!
2016-10-27 18:02 WARNING  tmdb_lookup   passthepopcorn  TMDB lookup failed for Avida [2006] by Benoît Delépine and Gustave Kervern - XviD / DVD / AVI / Other
2016-10-27 18:32 WARNING  tmdb_lookup   passthepopcorn  TMDB lookup failed for Grim Reapers [2014] by Cade Saint - x264 / WEB / MP4 / Other / Freeleech!
2016-10-27 18:42 ERROR    api_bluray    movies          Error refreshing movie details for Underworld: Blood Wars from blu-ray.com, cached info being used.
2016-10-27 18:42 ERROR    rarbg         movies          Error code 5: Too many requests per second. Maximum requests allowed are 1req/2sec Please try again later!
2016-10-27 18:42 INFO     content_size  movies          Entry `Hacker.2015.720p.WEB-DL.DD5.1.H264-FGT[EtHD]` too big, rejecting
2016-10-27 18:42 INFO     content_size  movies          Entry `Hacker.2015.720p.WEB-DL.DD5.1.H264-FGT` too big, rejecting
2016-10-27 18:44 INFO     urlrewriter   movies          Entry 'Halo 4 - Forward Unto Dawn 2012 BRRip 720p MKV-ESCORT' URL rewritten to http://extratorrent.cc/download/3471606/Halo+4+-+Forward+Unto+Dawn+2012+BRRip+720p+MKV-ESCORT.torrent (with extratorrent)
2016-10-27 18:44 INFO     urlrewriter   movies          Entry 'The.Last.Film.Festival.2016.HDRip.XviD.AC3-EVO[PRiME]' URL rewritten to http://extratorrent.cc/download/5252149/The.Last.Film.Festival.2016.HDRip.XviD.AC3-EVO%5BPRiME%5D.torrent (with extratorrent)
2016-10-27 18:44 INFO     urlrewriter   movies          Entry 'Hacker 2015 720p WEBRip 800 MB - iExTV' URL rewritten to http://extratorrent.cc/download/5255866/Hacker+2015+720p+WEBRip+800+MB+-+iExTV.torrent (with extratorrent)
2016-10-27 18:44 INFO     download      movies          Downloading: Halo 4 - Forward Unto Dawn 2012 BRRip 720p MKV-ESCORT
2016-10-27 18:44 INFO     download      movies          Downloading: The.Last.Film.Festival.2016.HDRip.XviD.AC3-EVO[PRiME]
2016-10-27 18:44 INFO     download      movies          Downloading: Hacker 2015 720p WEBRip 800 MB - iExTV
2016-10-27 18:44 ERROR    torrent_alive                 UDP Port Error, port was None
2016-10-27 18:44 ERROR    torrent_alive                 UDP Port Error, port was None
2016-10-27 18:44 WARNING  requests.packages.urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x721d1870>: Failed to establish a new connection: [Errno 111] Connection refused',)': /scrape?info_hash=P%CE%9B%7Dt%82%3D%D8%90D%9D6n%E0%ED%FEj%A8z%AF
2016-10-27 18:44 WARNING  requests.packages.urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x6fd70230>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /scrape?info_hash=P%CE%9B%7Dt%82%3D%D8%90D%9D6n%E0%ED%FEj%A8z%AF
2016-10-27 18:44 WARNING  requests.packages.urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x721d1390>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /scrape?info_hash=P%CE%9B%7Dt%82%3D%D8%90D%9D6n%E0%ED%FEj%A8z%AF
2016-10-27 18:44 WARNING  torrent_alive                 Socket Error: [Errno -2] Name or service not known
2016-10-27 18:44 WARNING  torrent_alive                 Socket Error: [Errno -2] Name or service not known
2016-10-27 18:44 WARNING  torrent_alive                 Socket Error: [Errno -2] Name or service not known
2016-10-27 18:44 WARNING  torrent_alive                 Socket Error: [Errno 111] Connection refused
2016-10-27 18:44 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:44 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:44 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 WARNING  requests.packages.urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x6fd70bf0>, 'Connection to 94.228.192.98 timed out. (connect timeout=30)')': /scrape?info_hash=P%CE%9B%7Dt%82%3D%D8%90D%9D6n%E0%ED%FEj%A8z%AF
2016-10-27 18:45 INFO     remember_rej  movies          Remembering rejection of `Halo 4 - Forward Unto Dawn 2012 BRRip 720p MKV-ESCORT` for 60 minutes
2016-10-27 18:45 INFO     task          movies          Plugin torrent_alive has requested task to be ran again after execution has completed. Reason: Not enough seeds
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: [Errno -2] Name or service not known
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 INFO     remember_rej  movies          Remembering rejection of `The.Last.Film.Festival.2016.HDRip.XviD.AC3-EVO[PRiME]` for 60 minutes
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: [Errno -2] Name or service not known
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 WARNING  torrent_alive                 Socket Error: timed out
2016-10-27 18:45 INFO     transmission  movies          "Hacker 2015 720p WEBRip 800 MB - iExTV" torrent added to transmission
2016-10-27 18:45 INFO     task          movies          Rerunning the task in case better resolution can be achieved.
2016-10-27 18:46 INFO     urlrewriter   addie_movies    Entry 'Pixars.BURN-E.2008.720p.BluRay.x264-VOA' URL rewritten to http://extratorrent.cc/download/1577082/Pixars.BURN-E.2008.720p.BluRay.x264-VOA.torrent (with extratorrent)
2016-10-27 18:46 INFO     download      addie_movies    Downloading: Pixars.BURN-E.2008.720p.BluRay.x264-VOA
2016-10-27 18:46 CRITICAL task          addie_movies    BUG: Unhandled error in plugin torrent_alive: 'generator' object is not an iterator
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 245, in on_task_output
    seeds = get_tracker_seeds(tracker, info_hash)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 162, in get_tracker_seeds
    return get_http_seeds(url, info_hash)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 138, in get_http_seeds
    data = bdecode(requests.get(url).content).get('files')
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/bittorrent.py", line 139, in bdecode
    data = decode_item(functools.partial(next, src), next(src))  # pylint:disable=E1101
  File "/usr/local/lib/python2.7/dist-packages/future/builtins/newnext.py", line 62, in newnext
    iterator.__class__.__name__))
TypeError: 'generator' object is not an iterator

```
