### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by ssshake** [Flexget/Flexget#1442]
My flexget config has been working fine for years. Suddenly this week when I run flexget it just says, killed.

If I create a new bare bones config file from scratch it also just says 'Killed'

If I run it in a directory without config.yml, I get 

 flexget
2016-10-10 23:11 CRITICAL manager                       Failed to find configuration file config.yml
2016-10-10 23:11 INFO     manager                       Tried to read from: /media/home/flexget/config_test/adf, /home/flexget/.flexget, /home/flexget/.config/flexget
Could not instantiate manager: No configuration file found.

It seems to be 

### Actual behaviour:
flexget@Linuxbox:~$ flexget --debug exec --task BITME
2016-10-10 23:07 DEBUG    manager                       Figuring out config load paths
2016-10-10 23:07 DEBUG    manager                       Found config: /media/home/flexget/config.yml
2016-10-10 23:07 DEBUG    manager                       Config file /media/home/flexget/config.yml selected
2016-10-10 23:07 DEBUG    manager                       sys.defaultencoding: ascii
2016-10-10 23:07 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-10-10 23:07 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-10-10 23:07 DEBUG    plugin                        Trying to load plugins from: [u'/media/home/flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2016-10-10 23:07 DEBUG    plugin                        Plugin `memusage` requires `ext lib `guppy`` to load.
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_idnumber = guessit.transfo.guess_idnumber:GuessIdnumber')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_bonus_features = guessit.transfo.guess_bonus_features:GuessBonusFeatures')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_date = guessit.transfo.guess_date:GuessDate')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('expected_title = guessit.transfo.expected_title:ExpectedTitle')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('expected_series = guessit.transfo.expected_series:ExpectedSeries')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('split_path_components = guessit.transfo.split_path_components:SplitPathComponents')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_properties = guessit.transfo.guess_properties:GuessProperties')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_release_group = guessit.transfo.guess_release_group:GuessReleaseGroup')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('split_explicit_groups = guessit.transfo.split_explicit_groups:SplitExplicitGroups')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_episode_details = guessit.transfo.guess_episode_details:GuessEpisodeDetails')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_episodes_rexps = guessit.transfo.guess_episodes_rexps:GuessEpisodesRexps')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_weak_episodes_rexps = guessit.transfo.guess_weak_episodes_rexps:GuessWeakEpisodesRexps')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_episode_info_from_position = guessit.transfo.guess_episode_info_from_position:GuessEpisodeInfoFromPosition')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('split_on_dash = guessit.transfo.split_on_dash:SplitOnDash')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_movie_title_from_position = guessit.transfo.guess_movie_title_from_position:GuessMovieTitleFromPosition')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_video_rexps = guessit.transfo.guess_video_rexps:GuessVideoRexps')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_country = guessit.transfo.guess_country:GuessCountry')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_language = guessit.transfo.guess_language:GuessLanguage')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_website = guessit.transfo.guess_website:GuessWebsite')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_year = guessit.transfo.guess_year:GuessYear')
2016-10-10 23:07 DEBUG    stevedore.extension                 found extension EntryPoint.parse('guess_filetype = guessit.transfo.guess_filetype:GuessFiletype')
Killed

### Steps to reproduce:
Unknown 

#### Log:
empty
### Additional information:

- Flexget Version:
- Python Version: 2.7.6
- Installation method: easyinstall
- OS and version: ubuntu 14.04

**Comment by ssshake** [comment]
upon pip uninstall/reinstall i get

`
2016-10-10 23:14 CRITICAL plugin                        Plugin `flexget.plugins.parsers.parser_guessit` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_guessit.py", line 10, in <module>
    from guessit.rules import rebulk_builder
ImportError: No module named rules
usage: flexget [-h] [-V] [--test] [-c CONFIG] [--logfile LOGFILE]
               [--loglevel LEVEL] [--bugreport] [--profile [OUTFILE]] [--cron]
               [--debug-db-sessions] [--debug-warnings]
               <command> ...
`

**Comment by ssshake** [comment]
A pip install --upgrade guessit resolved the last issue.

Really curious how it got into a messed up state to begin with though. I haven't touched any software on my server in the past week (since flexget last worked), unless something caused an issue with an unattended-upgrade cron. But that should only address security patches.
