### ISSUE TITLE
Sickbeard crash on quality

### ISSUE THREAD

**Issue by mgaulton** [Flexget/Flexget#1443]
### Expected behaviour:

Sickrage/Sickbeard should download the selected quality.
### Actual behaviour:

Error occurs and crash occurs
### Steps to reproduce:
- Step 1: ...
#### Config:

```


  Sickrage:
    configure_series:
      from:
       sickbeard:
         base_url: http://localhost
         port: 8182
         api_key: API
         include_ended: true
         only_monitored: true
         include_data: true


  Sickrage2:
    verify_ssl_certificates: no
    all_series:
      quality: sdtv+ <=720p
      tracking: backfill
      propers: 12 hours
    download: /home/torrentflux
    inputs:
      - rss: http://thepiratebay.org/rss/new/205
      - rss: http://thepiratebay.org/rss/top100/205
      - rss: https://api.nzbgeek.info/rss?t=-11&dl=1&seekid=144199&num=200&r=API
      - rss: https://api.nzbgeek.info/rss?t=-11&dl=1&seekid=145759&num=200&r=API



```
#### Log:

``````
2016-10-12 13:45 CRITICAL task          Sickrage        BUG: Unhandled error in plugin configure_series: u'quality_details'
2016-10-12 13:45 CRITICAL manager       Sickrage        An unexpected crash has occurred. Writing crash report to /root/crash_report.2016.10.12.134548095908.log. Please v
erify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker.
You are currently using version 2.3.43

```2016-10-12 13:45 CRITICAL task          Sickrage        BUG: Unhandled error in plugin configure_series: u'quality_details'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/operate/configure_series.py", line 71, in on_task_start
    result = method(task, input_config)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/input/sickbeard.py", line 106, in on_task_input
    fg_qualities = self.quality_requirement_builder(show_json['data']['quality_details']['initial'])
KeyError: u'quality_details'


### Additional information:

- Flexget Version:2.3.43
- Python Version: Python 2.7.12
- Installation method: pip
- OS and version: Opensuse Leap 42.1
``````

**Comment by liiight** [comment]
Please wait for v2.4.0 and run task with debug logs. I cant seem to reproduce this.

**Comment by mgaulton** [comment]
So checking the logs today, i found this.

2016-10-31 06:40 CRITICAL task          Sickrage        BUG: Unhandled error in plugin configure_series: 'FlexGetLogger' object has no attribute 'deubg'
2016-10-31 06:40 CRITICAL manager       Sickrage        An unexpected crash has occurred. Writing crash report to /root/crash_report.2016.10.31.064017697464.log. Please verify you are running the l
atest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.5.7
2016-10-31 06:40 WARNING  task          Sickrage        Aborting task (plugin: configure_series)


2016-10-31 06:40 CRITICAL task          Sickrage        BUG: Unhandled error in plugin configure_series: 'FlexGetLogger' object has no attribute 'deubg'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/operate/configure_series.py", line 71, in on_task_start
    result = method(task, input_config)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/input/sickbeard.py", line 107, in on_task_input
    log.deubg('processing show data: {}'.format(show_json['data']))
AttributeError: 'FlexGetLogger' object has no attribute 'deubg'

**Comment by liiight** [comment]
upgrade to latest, this was already fixed

**Comment by liiight** [comment]
Reopen of still relevant.
