### ISSUE TITLE
CP fail on   if movie['status'] == 'active':

### ISSUE THREAD

**Issue by mgaulton** [Flexget/Flexget#1444]
### Expected behaviour:

Couchpotato grabber should get list of pending moves and then download
### Actual behaviour:

Crash occurs when parsing data returned from Couchpotato
### Steps to reproduce:
- Step 1: ...
#### Config:

```

  queue_movies_couchpotato:
    verify_ssl_certificates: no
    couchpotato_list:
      base_url: http://localhost
      port: 5050
      api_key: API
      include_data: yes
    accept_all: yes
    list_add:
      - movie_list: couchlist


  queue_movies_couchpotato2:
    inputs:
      - rss: http://thepiratebay.org/rss/new/201
      - rss: https://thepiratebay.org/rss/top100/201
      - rss: https://thepiratebay.org/rss/new/207
      - rss: https://thepiratebay.org/rss//top100/200
      - rss: https://api.nzbgeek.info/rss?t=-11&dl=1&seekid=144440&num=200&r=API
    quality:
      - "<720p"
    imdb_lookup: yes
    list_match:
      from:
        - movie_list: couchlist
    download: /home/torrentflux
    # template:
    #   - torrents-template
```
#### Log:

```
CP LOG
2016-10-12 10:47 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-10-12 10:47 VERBOSE  couchpotato_list queue_movies_couchpotato Connecting to CouchPotato to retrieve movie list.
2016-10-12 10:47 VERBOSE  couchpotato_list queue_movies_couchpotato Connecting to CouchPotato to retrieve profile data.
2016-10-12 10:47 CRITICAL task          queue_movies_couchpotato BUG: Unhandled error in plugin couchpotato_list: u'status'
2016-10-12 10:47 CRITICAL manager       queue_movies_couchpotato An unexpected crash has occurred. Writing crash report to /root/crash_report.2016.10.12.104721788205.log. Please verify you are running the la
test version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.3.42
2016-10-12 10:47 WARNING  task          queue_movies_couchpotato Aborting task (plugin: couchpotato_list)



CP crash

2016-10-12 10:46 DEBUG    manager                       Figuring out config load paths
2016-10-12 10:46 DEBUG    manager                       Found config: /root/config.yml
2016-10-12 10:46 DEBUG    manager                       Config file /root/config.yml selected
2016-10-12 10:47 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-10-12 10:47 VERBOSE  couchpotato_list queue_movies_couchpotato Connecting to CouchPotato to retrieve movie list.
2016-10-12 10:47 VERBOSE  couchpotato_list queue_movies_couchpotato Connecting to CouchPotato to retrieve profile data.
2016-10-12 10:47 CRITICAL task          queue_movies_couchpotato BUG: Unhandled error in plugin couchpotato_list: u'status'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 242, in on_task_input
    return list(CouchPotatoSet(config))
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 195, in __iter__
    return (entry for entry in self.movies)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 180, in movies
    self._movies = CouchPotatoBase.list_entries(self.config)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 115, in list_entries
    if movie['status'] == 'active':
KeyError: u'status'
```
### Additional information:
- Flexget Version:2.3.43
- Python Version: Python 2.7.12
- Installation method: pip
- OS and version: Opensuse Leap 42.1

**Comment by liiight** [comment]
I Added some debug logs. Please wait for next release and then paste debug logs of task execution

**Comment by mgaulton** [comment]
Will do.

**Comment by liiight** [comment]
Reopen of still relevant.

**Comment by mgaulton** [comment]
I am still receiving this as of this morning. v2.6.7
2016-11-29 10:27 CRITICAL task          queue_movies_couchpotato BUG: Unhandled error in plugin couchpotato_list: u'status'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 243, in on_task_input
    return list(CouchPotatoSet(config))
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 196, in __iter__
    return (entry for entry in self.movies)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 181, in movies
    self._movies = CouchPotatoBase.list_entries(self.config)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 116, in list_entries
    if movie['status'] == 'active':
KeyError: u'status'

**Comment by liiight** [comment]
you haven't pasted debug logs, please do so

**Comment by mgaulton** [comment]
working on that

**Comment by mgaulton** [comment]
where will i find the debug logs?

**Comment by liiight** [comment]
`flexget --debug execute --tasks <TASK_NAME>`

**Comment by mgaulton** [comment]
So this is the halt portion, The debug logging  looks huge and does appear to work for a bunch of entries then hits this.
I can provide the full dump if you want it.

2016-11-29 10:44 DEBUG    couchpotato_list queue_movies_couchpotato quality requirement is 720p r5|ts|dvdrip|cam|dvdscr|tc
2016-11-29 10:44 DEBUG    couchpotato_list queue_movies_couchpotato returning entry <Entry(title=East Lynne,state=undecided)>
2016-11-29 10:44 DEBUG    couchpotato_list queue_movies_couchpotato movie data: {u'_t': u'property', u'releases': [], u'_rev': u'000c2529', u'profile_id': u'cde3bbdae2e247ddb5fbb0afb0028318', u'value': u'1384713000', u'identifier': u'messages.last_check', u'_id': u'0efa075f18c149478746f868f78a1c8c'}
2016-11-29 10:44 CRITICAL task          queue_movies_couchpotato BUG: Unhandled error in plugin couchpotato_list: u'status'
2016-11-29 10:44 CRITICAL manager       queue_movies_couchpotato An unexpected crash has occurred. Writing crash report to /root/crash_report.2016.11.29.104417284796.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.6.7
2016-11-29 10:44 DEBUG    manager       queue_movies_couchpotato Traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 243, in on_task_input
    return list(CouchPotatoSet(config))
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 196, in __iter__
    return (entry for entry in self.movies)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 181, in movies
    self._movies = CouchPotatoBase.list_entries(self.config)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/couchpotato_list.py", line 116, in list_entries
    if movie['status'] == 'active':
KeyError: u'status'
2016-11-29 10:44 WARNING  task          queue_movies_couchpotato Aborting task (plugin: couchpotato_list)

**Comment by liiight** [comment]
this is good enough to go on

**Comment by mgaulton** [comment]
Version 40577904 (11/15/2016, 3:07:33 AM)
working on the log, it exceeds pastebins limit.

**Comment by liiight** [comment]
paste just the cp plugin data then

**Comment by mgaulton** [comment]
try https://gist.github.com/mgaulton/6519c34801b5a1c76cc412f3fe1fa10b

**Comment by liiight** [comment]
honestly this looks like corrupt cp data. that version is different than mine, are you running cp from git? 
my version is 3.0.1

**Comment by mgaulton** [comment]
Yes i am running from git. I can try rebuilding the DB again.

**Comment by mgaulton** [comment]
I'm running the most recent commit, my init script does  a git pull before launching.
https://github.com/CouchPotato/CouchPotatoServer/commit/405779047035723bd015fdd51b19379884f53b36

**Comment by mgaulton** [comment]
Thanks again.

**Comment by liiight** [comment]
just ended up doing a mindless check of this, since i believe this is corrupt CP data. let me know if it doesn't work

**Comment by mgaulton** [comment]
will do.
