### ISSUE TITLE
lazy_lookup crash

### ISSUE THREAD

**Issue by mfonville** [Flexget/Flexget#1466]
### Expected behaviour:
To run without a crash

### Actual behaviour:
It does crash

#### Config:
```
tasks:
  Series-NPO:
    npo_watchlist:
      email: 'xxxx@xxxxl.com'
      password: 'xxxxxxxxx'
      max_episode_age_days: 5
    plugin_priority:
      thetvdb_lookup: 500
      trakt_lookup: 250
    thetvdb_lookup:
      language: nl
    trakt_lookup:
      account: xxxxxxx
      username: xxxxxxxx
    accept_all: yes
    if:
      - "trakt_watched": reject
    exec:
      fail_entries: yes
      auto_escape: yes
      on_output:
        for_accepted:
          - download-npo xxxxxxxxxxxxxx
```
  
#### Log:
```
DEBUG    util.simple_persistence Series-NPO      setting key auth_tokens value {u'default': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
DEBUG    utils.requests Series-NPO      Fetching https://api.thetvdb.com/series/84596/episodes/query
DEBUG    thetvdb_lookup Series-NPO      Error looking up tvdb episode information for Knechtschaft (KN_1685479): Error looking up episode from TVDb (404 Client Error: Not Found for url: https://api.thetvdb.com/series/84596/episodes/query?firstAired=2016-10-24)
DEBUG    api_trakt     Series-NPO      show `Pumuckl` age 34 expires in 172 days
DEBUG    utils.requests Series-NPO      Fetching https://api-v2launch.trakt.tv/shows/30554/people
DEBUG    api_trakt     Series-NPO      show `Pumuckl` age 34 expires in 172 days
DEBUG    api_trakt     Series-NPO      No user ratings found in cache.
INFO     plugin        Series-NPO      Account maartenfonville has not been authorized. See `flexget trakt auth -h` on how to.
DEBUG    api_tvdb      Series-NPO      Looking up tvdb information for Rundfunk 84596
DEBUG    api_tvdb      Series-NPO      Series <name=Rundfunk,tvdb_id=84596> not found in cache, looking up from tvdb.
DEBUG    util.simple_persistence Series-NPO      setting key auth_tokens value {u'default': u'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
DEBUG    utils.requests Series-NPO      Fetching https://api.thetvdb.com/series/84596
DEBUG    api_tvdb      Series-NPO      {u'invalidLanguage': u'Incomplete or no translation for the given language'}
2016-10-26 12:03 ERROR    lazy_lookup   Series-NPO      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 124, in lazy_series_lookup
    return self.series_lookup(entry, language, self.series_map)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 116, in series_lookup
    session=session
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 527, in lookup_series
    _update_search_strings(series, session, search=name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 455, in _update_search_strings
    search.lower()] if search else []
AttributeError: 'NoneType' object has no attribute 'lower'
```

### Additional information:
The problem started to appear since version 2.5.1 (but might also be related to the timing of the specific broadcast)

- Flexget Version: 2.5.3

**Comment by liiight** [comment]
I don't know how tvdb even allows its DB to hold shows with no name, but it does;
```json
{
  "data": {
    "id": 84596,
    "seriesName": null,
    "aliases": [],
    "banner": "graphical/84596-g.jpg",
    "seriesId": "",
    "status": "Ended",
    "firstAired": "1982-09-24",
    "network": "BR",
    "networkId": "",
    "runtime": "30",
    "genre": [
      "Animation",
      "Children"
    ],
    "overview": null,
    "lastUpdated": 1467637945,
    "airsDayOfWeek": "",
    "airsTime": "",
    "rating": "TV-Y",
    "imdbId": "tt0082732",
    "zap2itId": "",
    "added": "2009-01-14 12:45:39",
    "addedBy": 6220,
    "siteRating": 8.4,
    "siteRatingCount": 5
  },
  "errors": {
    "invalidLanguage": "Incomplete or no translation for the given language"
  }
}
```
