### ISSUE TITLE
flexget.plugins.daemon.web_server fails config check 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#1467]
### Expected behaviour:
Config to pass schema 

### Actual behaviour:
Error prevents config to pass checks 

### Steps to reproduce:
- Step 1: ...
Start, reload or check config

#### Config:

http://pastebin.com/LaCt6BT2
  
#### Log:
```
pi@raspberrypi:~ $ flexget --debug daemon start -d
2016-10-26 16:02 DEBUG    manager                       Figuring out config load paths
2016-10-26 16:02 DEBUG    manager                       Found config: /home/pi/.flexget/config.yml
2016-10-26 16:02 DEBUG    manager                       Config file /home/pi/.flexget/config.yml selected
2016-10-26 16:02 DEBUG    manager                       sys.defaultencoding: ascii
2016-10-26 16:02 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-10-26 16:02 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-10-26 16:02 DEBUG    plugin                        Trying to load plugins from: [u'/home/pi/.flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2016-10-26 16:02 DEBUG    plugin                        (u'Plugin `%s` requires `%s` to load.', u'memusage', u'ext lib `guppy`')
2016-10-26 16:02 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-10-26 16:02 CRITICAL plugin                        Plugin `flexget.plugins.daemon.web_server` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 7, in <module>
    from flask_login import login_user, LoginManager, current_user, current_app
ImportError: cannot import name current_app
2016-10-26 16:02 DEBUG    plugin                        Plugins took 9.90 seconds to load. 259 plugins in registry.
2016-10-26 16:02 DEBUG    manager                       Connecting to: sqlite:////home/pi/.flexget/db-config.sqlite
2016-10-26 16:02 DEBUG    manager                       config_name: config
2016-10-26 16:02 DEBUG    manager                       config_base: /home/pi/.flexget
2016-10-26 16:02 CRITICAL manager                       [/] The key `web_server` is not valid here.
2016-10-26 16:02 DEBUG    manager                       invalid config, rolling back
2016-10-26 16:02 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
2016-10-26 16:02 DEBUG    manager                       Removed /home/pi/.flexget/.config-lock
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 325, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 202, in initialize
    self.load_config()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 621, in load_config
    self.update_config(config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 632, in update_config
    self.config = self.validate_config(config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 690, in validate_config
    raise err
ValueError: Did not pass schema validation.
```

### Additional information:

- Flexget Version: 2.5.3
- Python Version: Python 2.7.9
- Installation method: PIP
- OS and version: Raspbian Jessy 
- Link to crash log:

**Comment by cvium** [comment]
Have you tried updating `flask_login`?

**Comment by cvium** [comment]
Never mind. Downgrade to flask_login 0.3.2. Apparently they made some breaking changes in 0.4.0

**Comment by cvium** [comment]
I've temporarily fixed it by locking the version so updating flexget won't cause issues. We'll have to look into what changed in flask-login.

**Comment by chewy74** [comment]
OK so don't downgrade my flask_login version?

**Comment by cvium** [comment]
Downgrade to 0.3.2 and it'll work.

**Comment by omaralvarez** [comment]
I know this is closed, but I am getting a similar issue after upgrading to 2.7.1:

2016-12-03 10:40 CRITICAL plugin                        Plugin `flexget.plugins.daemon.web_server` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker  # noqa
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 8, in <module>
    from flask_login.utils import current_app, login_user, current_user
ImportError: No module named utils

This happens when running flexget check. I tried downgrading flask-login to 0.3.2 but it did not work.

**Comment by liiight** [comment]
maybe another change. please open a new issue
