### ISSUE TITLE
Plugin `flexget.plugins.daemon.web_server` failed to import dependencies

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#1468]
2016-10-27 04:56 CRITICAL plugin                        Plugin `flexget.plugins.daemon.web_server` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 7, in <module>
    from flask_login import login_user, LoginManager, current_user, current_app
ImportError: cannot import name current_app

**Comment by liiight** [comment]
Duplicate #1467
