### ISSUE TITLE
Unable to launch webserver after flask-login upgrade

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1469]
### Behaviour:
I ran a pip upgrade on the flexget package that led to an upgrade of Flask-Login from Flask-Login-0.3.2 
to  flask-login-0.4.0. Flexget version was not changed

A restart right after without a config change would fail because of a wrong YAML declaration for web_server despite being correct.

The deamon can start with an error if webserver is commented.

#### Log:
The upgrade:
```
admin@Strawberry:~$ ./upgrade.sh
Requirement already up-to-date: flexget in /volume1/@appstore/flexget/env/lib/python2.7/site-packages
Collecting flask-login>=0.3.2 (from flexget)
  Downloading Flask_Login-0.4.0-py2.py3-none-any.whl
Requirement already up-to-date: guessit<=2.0.4 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: jsonschema>=2.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: flask-restful>=0.3.3 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: path.py>=8.1.1 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: colorclass>=2.2.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: beautifulsoup4>=4.5 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: jinja2 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: flask>=0.7 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: PyYAML in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: Safe>=0.4 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: FeedParser>=5.2.1 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: pynzb in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: pyparsing>=2.0.3 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: pathlib>=1.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: rpyc in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: cherrypy>=3.7.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: PyRSS2Gen in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: requests<3.0,>=2.8.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: terminaltables>=3.1.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: html5lib>=0.11 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: apscheduler>=3.2.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: future>=0.15.2 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: SQLAlchemy<1.999,>=1.0.9 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: flask-restplus==0.8.6 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: flask-cors>=2.1.2 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: python-dateutil>=2.5.3 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: flask-compress>=1.2.1 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flexget)
Requirement already up-to-date: babelfish>=0.5.5 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from guessit<=2.0.4->flexget)
Requirement already up-to-date: rebulk>=0.7.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from guessit<=2.0.4->flexget)
Requirement already up-to-date: functools32; python_version == "2.7" in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from jsonschema>=2.0->flexget)
Requirement already up-to-date: aniso8601>=0.82 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flask-restful>=0.3.3->flexget)
Requirement already up-to-date: pytz in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flask-restful>=0.3.3->flexget)
Requirement already up-to-date: six>=1.3.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flask-restful>=0.3.3->flexget)
Requirement already up-to-date: MarkupSafe in /volume1/@appstore/python/lib/python2.7/site-packages (from jinja2->flexget)
Requirement already up-to-date: click>=2.0 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flask>=0.7->flexget)
Requirement already up-to-date: Werkzeug>=0.7 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flask>=0.7->flexget)
Requirement already up-to-date: itsdangerous>=0.21 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from flask>=0.7->flexget)
Requirement already up-to-date: setuptools in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from pynzb->flexget)
Requirement already up-to-date: plumbum in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from rpyc->flexget)
Requirement already up-to-date: webencodings in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from html5lib>=0.11->flexget)
Requirement already up-to-date: funcsigs; python_version == "2.7" in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from apscheduler>=3.2.0->flexget)
Requirement already up-to-date: tzlocal>=1.2 in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from apscheduler>=3.2.0->flexget)
Requirement already up-to-date: futures; python_version == "2.7" in /volume1/@appstore/flexget/env/lib/python2.7/site-packages (from apscheduler>=3.2.0->flexget)
Installing collected packages: flask-login
  Found existing installation: Flask-Login 0.3.2
    Uninstalling Flask-Login-0.3.2:
      Successfully uninstalled Flask-Login-0.3.2
Successfully installed flask-login-0.4.0
```
The failing start with webserver: 
```
admin@Strawberry:~$ ./restart.sh
FlexGet is not running
Starting FlexGet ...
2016-10-27 10:53 CRITICAL plugin                        Plugin `flexget.plugins.daemon.web_server` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/api/core/authentication.py", line 7, in <module>
    from flask_login import login_user, LoginManager, current_user, current_app
ImportError: cannot import name current_app
2016-10-27 10:53 CRITICAL manager                       [/] The key `web_server` is not valid here.
2016-10-27 10:53 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
Could not start manager: Did not pass schema validation.
```
 
The error if webserver is commented

```
admin@Strawberry:~$ ./restart.sh
FlexGet is not running
Starting FlexGet ...
2016-10-27 10:57 CRITICAL plugin                        Plugin `flexget.plugins.daemon.web_server` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/api/core/authentication.py", line 7, in <module>
    from flask_login import login_user, LoginManager, current_user, current_app
ImportError: cannot import name current_app
2016-10-27 10:57 INFO     manager                       Daemonizing...
2016-10-27 10:57 INFO     manager                       Daemonize complete. New PID: 20455
```

### Additional information:

- Flexget Version: 2.5.3
- Python Version: 2.7.11
- Installation method: Pip
- OS and version: Raspberry
- Link to crash log:

**Comment by liiight** [comment]
Duplicate #1467. Upgrade to latest, just released 2.5.4.
