### ISSUE TITLE
TypeError: not enough arguments for format string Logged from file discover.py, line 111

### ISSUE THREAD

**Issue by dunfy** [Flexget/Flexget#1471]
### Expected behaviour:
For it to run. 

### Actual behaviour:
Crashes and never runs 
Running  /usr/local/bin/flexget --cron execute crashes with the error

### Steps to reproduce:
- Step 1: run /usr/local/bin/flexget --cron execute

#### Config:
This https://github.com/jawilson/dotfiles/blob/master/flexget/config.yml 
- with the paths changed to my own. 
  
#### Log:

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/lib/python2.7/dist-packages/flexget/logger.py", line 140, in format
    return logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file discover.py, line 111

### Additional information:

- Flexget Version: 2.5.5 (latest at time) 
- Python Version: 2.7.12
- Installation method: pip
- OS and version: "Ubuntu 16.04.1 LTS"
- Link to crash log:

**Comment by dunfy** [comment]
Nice one! When will the pip upgrade be available?

**Comment by cvium** [comment]
24 hours give or take
