### ISSUE TITLE
Rarbg crash from lazy_series_lookup language arg addition.

### ISSUE THREAD

**Issue by lostsubstance** [Flexget/Flexget#1481]
```
2016-11-02 07:09 CRITICAL task          get-tv          BUG: Unhandled error in plugin discover: lazy_series_lookup() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 290, in on_task_input
    return self.execute_searches(config, entries, task)
  File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 155, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "c:\python27\lib\site-packages\flexget\plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\sites\rarbg.py", line 144, in search
    plugin.get_plugin_by_name('thetvdb_lookup').instance.lazy_series_lookup(entry)
TypeError: lazy_series_lookup() takes exactly 3 arguments (2 given)
```

The rarbg plugin needs updating, or lazy_series_lookup needs to assign language default value?

**Comment by liiight** [comment]
bah, that's one of the reasons hard coded internal lookups suck... 
i'll fix this, but this is bad design.
