### ISSUE TITLE
BUG: Unhandled error in plugin clean_transmission: 'NoneType' object has no attribute 'search'

### ISSUE THREAD

**Issue by fabrizio5680** [Flexget/Flexget#1497]
### Expected behaviour:
clean transmission
### Actual behaviour:
exception 

### Steps to reproduce:
Run flexget execute or daemon as normally, only started to happen since updating from  **2.5.11 to 2.5.19**

#### Config:
```
_transmission: &transmission
        enabled: yes
        host: 127.0.0.1
        port: 2206

clean_transmission:
      <<: *transmission
      finished_for: 1 days
```
  
#### Log:
```
 CRITICAL task          tvshow_search_task BUG: Unhandled error in plugin clean_transmission: 'NoneType' object has no attribute 'search'

Traceback (most recent call last):
  File "/opt/lib/python3.5/site-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/opt/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/opt/lib/python3.5/site-packages/flexget/plugins/clients/transmission.py", line 680, in on_task_exit
    is_preserve_tracker_matching = preserve_tracker_re or any(preserve_tracker_re.search(host) for host in tracker_hosts)
  File "/opt/lib/python3.5/site-packages/flexget/plugins/clients/transmission.py", line 680, in <genexpr>
    is_preserve_tracker_matching = preserve_tracker_re or any(preserve_tracker_re.search(host) for host in tracker_hosts)
AttributeError: 'NoneType' object has no attribute 'search'
```

### Additional information:

- Flexget Version: 2.5.19
- Python Version: 3.5.1
- Installation method: pip install
- OS and version: Android 4.4

**Comment by cvium** [comment]
Already fixed in the next release.
