### ISSUE TITLE
Crash when SSL certificate fails to validate

### ISSUE THREAD

**Issue by bbeck** [Flexget/Flexget#1507]
### Expected behaviour:
No exception thrown when connecting to a site with a SSL certificate.

### Actual behaviour:
Exception is thrown.

### Steps to reproduce:
Run `flexget trakt refresh <account>`

#### Config:
No config necessary.  A workaround is to add `verify_ssl_certificates: no` to the config.
  
#### Log:
```
BUG: Unhandled error in plugin configure_series: 'Extensions' object has no attribute 'get_extension_for_class'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 477, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/operate/configure_series.py", line 71, in on_task_start
    result = method(task, input_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 148, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/trakt_list.py", line 325, in on_task_input
    return list(TraktSet(config))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/trakt_list.py", line 90, in __iter__
    return iter(self.items)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/list/trakt_list.py", line 141, in items
    result = self.session.get(get_api_url(endpoint))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/requests.py", line 240, in request
    result = super(Session, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
```

### Additional information:

- Flexget Version: 2.6.0
- Python Version: 2.7.10
- Installation method: pip
- OS and version: Ubuntu Linux 15.10

**Comment by cvium** [comment]
https://github.com/kennethreitz/requests/issues/3710
