### ISSUE TITLE
telegram plugin

### ISSUE THREAD

**Issue by skyway22** [Flexget/Flexget#1511]
#### Config:
```
templates:
  telegram:
    telegram:
      bot_token: '{{secrets.telegram.bot_token}}'
      recipients:
        - username: '{{secrets.telegram.username}}'
      template:  |+
        {%if task in ["dl_filme",]%}*New movie added to queue*
        {%else%}*Download Started from task:
        *{{task|replace("_", "-")}}
        {%endif%}
        {% if series_name is defined -%}*New show episode added to queue*
        *{{series_name}}* - {{series_id}} - {{quality|d('')}}
        *{{tvmaze_episode_name|d(tvdb_ep_name)|d('')}}*
        [Image]({{tvmaze_series_original_image|replace("_", "%5F")}})
        [Show page]({{tvmaze_series_url|replace("_", "%5F")}})
        {% elif imdb_name is defined -%}
        *{{imdb_name}}* - ({{imdb_year}})
        {{quality|d('')}}
        {{imdb_score}}/10 - {{imdb_votes}} votes
        {{imdb_genres|join(', ')|title}} 
        *Plot:* {{imdb_plot_outline}}
        [Image]({{tmdb_posters[0]|replace("_", "%5F")}})
        [Movie Page]({{imdb_url|d('')}})
        {% else -%}
        {{title}}
        {%- endif -%}

```
  
#### Log:
```
2016-11-20 22:36 WARNING  plugin        dl_seriale      missing python-telegram-bot pkg
2016-11-20 22:36 VERBOSE  list_add      dl_seriale      adding accepted entries into entry_list - seriale
2016-11-20 22:36 VERBOSE  api_tvdb      dl_seriale      Data for The Exorcist has expired, refreshing from tvdb
2016-11-20 22:36 VERBOSE  api_tvdb      dl_seriale      Data for Scorpion has expired, refreshing from tvdb
osmc@osmc:~$ sudo pip install python-telegram-bot
Requirement already satisfied: python-telegram-bot in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: future>=0.15.2 in /usr/local/lib/python2.7/dist-packages (from python-telegram-bot)
Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (from python-telegram-bot)
Requirement already satisfied: urllib3>=1.10 in /usr/local/lib/python2.7/dist-packages (from python-telegram-bot)

```

### Additional information:

- Flexget Version: 2.5.20
- Python Version: 2.7
- Installation method: pip
- OS and version: osmc

**Comment by liiight** [comment]
what version you of python-telegram-bot you have?

**Comment by skyway22** [comment]
Name: python-telegram-bot
Version: 5.2.0

**Comment by liiight** [comment]
works for me. are you're sure your running flexget and using the same pip? maybe py3 or virtualenv somewhere? did this work before?

**Comment by skyway22** [comment]
this is the 1st time i'm trying to use telegram. Used pushbullet before..
`` are you're sure your running flexget and using the same pip? ``
How to check that ?

**Comment by liiight** [comment]
from the same path do:
`pip show flexget`
`pip show python-telegram-bot`
also, are are you running flexget?

**Comment by skyway22** [comment]
[https://bpaste.net/raw/5580ad6cc587](url)

**Comment by liiight** [comment]
did you restart daemon after installing `python-telegram-bot`?

**Comment by skyway22** [comment]
yup

**Comment by rchovan** [comment]
I have similiar problem. 
Telegram does not send any message

`python-telegram-bot: 5.2.0
flexget 2.7.1
Python 2.7.9
`

**Comment by rchovan** [comment]
config:
`tasks:
  notify:
    rss:  http://showrss.info/user/72275.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    accept_all: yes
    download: /tmp/
    notify_task:
      to:
        - telegram:
            bot_token: '<token>'
            message: "{{title}}"
            parse_mode: markdown
            recipients:
              - username: 'coudy'
              - group: 'nasko'`

crashlog:  
`2016-12-11 21:45 CRITICAL task          showrss         BUG: Unhandled error in plugin telegram: urlopen() got multiple values for keyword argument 'body'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 456, in on_task_output
    plugin.get_plugin_by_name('notify').instance.send_notification(task, notify_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notify.py", line 152, in send_notification
    notifier.notify(**notification_data)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 188, in notify
    chat_ids = self._real_init(Session(), telegram_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 223, in _real_init
    chat_ids = self._get_chat_ids_n_update_db(session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 279, in _get_chat_ids_n_update_db
    chat_ids, has_new_chat_ids = self._get_chat_ids(session, usernames, fullnames, groups)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 317, in _get_chat_ids
    new_chat_ids = list(self._get_new_chat_ids(usernames, fullnames, groups))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 374, in _get_new_chat_ids
    upd_usernames, upd_fullnames, upd_groups = self._get_bot_updates()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 412, in _get_bot_updates
    ups = self._bot.getUpdates(last_upd, limit=100)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 124, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1233, in getUpdates
    result = self._request.post(url, data, timeout=urlopen_timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 205, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'
`

flexget: 2.8.2
python: 2.7.9
python-telgram-bot: 5.2.0

**Comment by rchovan** [comment]
my config is now working, maybe this will help you: https://github.com/python-telegram-bot/python-telegram-bot/issues/481
