### ISSUE TITLE
`series show` crashes depending on terminal size

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#1521]
From what I gather, if the max length of the release title for a series is wider than the window size it will crash. Also the error should be updated to make more sense: 'using it given data' -> 'using the given data'.

    $ flexget series show westworld
    Least important column `Proper` removed due terminal size
    Least important column `Release Quality` removed due terminal size
    Least important column `Latest age` removed due terminal size
    Traceback (most recent call last):
    File "/tmp/bin/flexget", line 9, in <module>
        load_entry_point('FlexGet', 'console_scripts', 'flexget')()
    File "/tmp/flexget/flexget/__init__.py", line 42, in main
        manager.start()
    File "/tmp/flexget/flexget/manager.py", line 326, in start
        self.handle_cli()
    File "/tmp/flexget/flexget/manager.py", line 353, in handle_cli
        options.cli_command_callback(self, command_options)
    File "/tmp/flexget/flexget/plugins/cli/series.py", line 37, in do_cli
        display_details(options)
    File "/tmp/flexget/flexget/plugins/cli/series.py", line 242, in display_details
        table = TerminalTable(options.table_type, table_data, table_title, drop_columns=[4, 3, 1])
    File "/tmp/flexget/flexget/terminal.py", line 77, in __init__
        self.init_table()
    File "/tmp/flexget/flexget/terminal.py", line 86, in init_table
        self.table = self._resize_table()
    File "/tmp/flexget/flexget/terminal.py", line 198, in _resize_table
        raise TerminalTableError('Table could not be rendered correctly using it given data')
    flexget.terminal.TerminalTableError: Table could not be rendered correctly using it given data

* Flexget Version: 2.6.6
* Python Version: 2.7.12
* Installation method: git
* OS and version: OS X

**Comment by liiight** [comment]
thanks for noticing the typo, this issue will be fixed shortly. duplicate #1520
