### ISSUE TITLE
flexget.plugins.daemon.web_server ImportError on config check

### ISSUE THREAD

**Issue by omaralvarez** [Flexget/Flexget#1531]
### Expected behaviour:

No errors during config check.

### Actual behaviour:

ImportError raised.

### Steps to reproduce:
- Step 1: Install flexget.
- Step 2: ```flexget check```
  
#### Log:
```
2016-12-03 11:55 CRITICAL plugin                        Plugin `flexget.plugins.daemon.web_server` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker  # noqa
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 8, in <module>
    from flask_login.utils import current_app, login_user, current_user
ImportError: No module named utils
2016-12-03 11:55 VERBOSE  check                         Pre-checked 49 configuration lines
2016-12-03 11:55 VERBOSE  check                         Checking config file `/home/srvsal/.flexget/config.yml`
2016-12-03 11:55 VERBOSE  check                         Config passed check.
```

### Additional information:

- Flexget Version: 2.7.1
- Python Version: 2.7.12
- Installation method: ```pip install flexget```
- OS and version: Ubuntu Server 16.04 
- Link to crash log:

**Comment by liiight** [comment]
I can't seem to reproduce this, not on py2.7 or 3.5...

**Comment by omaralvarez** [comment]
```
Name: Flask-Login
Version: 0.3.2
Summary: User session management for Flask
Home-page: https://github.com/maxcountryman/flask-login
Author: Matthew Frazier
Author-email: leafstormrush@gmail.com
License: MIT
Location: /home/srvsal/.local/lib/python2.7/site-packages
Requires: Flask
```

It may be an issue on my system, I upgraded from 1.2.x to 1.7.1, but no errors were raised and followed upgrade instructions.

**Comment by Tommatheussen** [comment]
First off all, I suppose you upgraded to 2.7.1 (since 1.7.1 doesn't exist :D)

The code in flexget is already updated to accommodate the new flask-login. So installing the latest flask-login version should make this work, did you already try with the latest version?

**Comment by omaralvarez** [comment]
Hey, sorry for the mistake, yeah I upgraded to 2.7.1 from 1.2.x 😞 

Yep, the first thing I tried was the latest version of Flask login, which gave me a slightly different version of the same error. I can install it again and report it.

**Comment by Tommatheussen** [comment]
No problem ;) 

Please do report with the latest version, since (like @liiight) mentioned, it works for me as well on the latest version.

**Comment by omaralvarez** [comment]
```
2016-12-05 12:51 CRITICAL plugin                        Plugin `flexget.plugins.daemon.web_server` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker  # noqa
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 8, in <module>
    from flask_login.utils import current_app, login_user, current_user
ImportError: No module named utils
```

```
Name: Flask-Login
Version: 0.4.0
Summary: User session management for Flask
Home-page: https://github.com/maxcountryman/flask-login
Author: Matthew Frazier
Author-email: leafstormrush@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: Flask
```

**Comment by Tommatheussen** [comment]
Hmm, strange, just to confirm, did you restart flexget after upgrading (or installing the newer flask_login version?)

**Comment by omaralvarez** [comment]
I don't run Flexget as a daemon. I verified that it was not running, updated and used flexget check to validate config.

**Comment by Tommatheussen** [comment]
Might be a corrupt installation, try to remove flask_login and reinstalling it

**Comment by omaralvarez** [comment]
Removed flask_login and reinstalled using --no-cache-dir. Still get the same error.

**Comment by liiight** [comment]
then you're probably running a flexget instance that is not using the same pip. maybe different paths, virtualenv, python versions, etc.
In anyway, this is not a bug.

**Comment by omaralvarez** [comment]
Thanks anyway for the quick response. If I finally figure out what is going on I'll let you guys know.

**Comment by VuokkoVuorinnen** [comment]
Got a similar issue:

Ubuntu 14.04
installed using pip install
flexget 2.8.4
flask-plugin: 0.4.0

```
2016-12-14 09:17 CRITICAL plugin                        Exception while loading plugin flexget.plugins.daemon.web_server
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker  # noqa
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 87, in <module>
    class LoginAPI(APIResource):
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 90, in LoginAPI
    @api.response(200, 'Login successful', model=base_message_schema)
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/app.py", line 205, in response
    return super(API, self).response(code_or_apierror, description, model=model, **kwargs)
AttributeError: 'super' object has no attribute 'response'
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 325, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 188, in initialize
    plugin.load_plugins(extra_dirs=[os.path.join(self.config_base, 'plugins')])
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 457, in load_plugins
    _load_plugins_from_dirs(extra_dirs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 395, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/daemon/web_server.py", line 8, in <module>
    from flexget.api import api_app
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/__init__.py", line 4, in <module>
    from .core import authentication, cached, database, plugins, server, tasks, user, format_checker  # noqa
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 87, in <module>
    class LoginAPI(APIResource):
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/core/authentication.py", line 90, in LoginAPI
    @api.response(200, 'Login successful', model=base_message_schema)
  File "/usr/local/lib/python2.7/dist-packages/flexget/api/app.py", line 205, in response
    return super(API, self).response(code_or_apierror, description, model=model, **kwargs)
AttributeError: 'super' object has no attribute 'response'
```

**Comment by liiight** [comment]
that's not a similar issue at all. 
what version of `flask-restplus` are you using?

**Comment by VuokkoVuorinnen** [comment]
@liiight flask-restplus (0.9.2)

I figured it was similar, because when I downgrade the flask-plugins it kinda works again

**Comment by liiight** [comment]
We support flask restplus 0.8.7. Did you upgrade manually?

**Comment by dajhorn** [comment]
I got this bug after an upgrade from Trusty to Xenial.  The solution for me was:

1. Purge all `python2-*` packages.
1. `$ rm -fr /usr/local/bin/pip /usr/local/lib/python*` .
1. `$ apt-get install python3-pip`
1. `$ pip3 install pip`
1. `$ pip install flexget`
