### ISSUE TITLE
BUG: notify_crash

### ISSUE THREAD

**Issue by rchovan** [Flexget/Flexget#1532]
### Expected behaviour:
should send message over telegram

### Actual behaviour:
plugin notify_crash crashes 

### Steps to reproduce:
- Step 1: invoke crash

#### Config:
```
templates:
  global:
    notify_crash:
      to:
        - telegram:
            bot_token: <token>
            parse_mode: markdown
            recipients:
              - username: coudy
              - group: nasko
  tg:
    telegram:
      bot_token: <token>
      message: "teeesting"
      parse_mode: markdown
      recipients:
        - username: coudy
        - group: nasko

tasks:
  tgexec:
    apple_trailers:
      quality: 720p
      genres: ['Science Fiction']
    accept_all: yes
    download: /data/trailers
    template:
      - tg
```
  
#### Log:
```
emby@nas:/home/flexget$ flexget --loglevel debug execute --task tgexec
2016-12-03 22:01 DEBUG    manager                       Figuring out config load paths
2016-12-03 22:01 DEBUG    manager                       Found config: /home/flexget/config.yml
2016-12-03 22:01 DEBUG    manager                       Config file /home/flexget/config.yml selected
2016-12-03 22:01 DEBUG    manager                       sys.defaultencoding: ascii
2016-12-03 22:01 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-12-03 22:01 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-12-03 22:01 DEBUG    plugin                        Trying to load plugins from: [u'/home/flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2016-12-03 22:01 DEBUG    plugin                        (u'Plugin `%s` requires `%s` to load.', u'memusage', u'ext lib `guppy`')
2016-12-03 22:01 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-12-03 22:01 DEBUG    deluge                        ConfigManager started..
2016-12-03 22:01 DEBUG    plugin                        Plugins took 0.80 seconds to load. 264 plugins in registry.
2016-12-03 22:01 DEBUG    manager                       Connecting to: sqlite:////home/flexget/db-config.sqlite
2016-12-03 22:01 DEBUG    manager                       config_name: config
2016-12-03 22:01 DEBUG    manager                       config_base: /home/flexget
2016-12-03 22:01 DEBUG    manager                       New config data loaded.
2016-12-03 22:01 DEBUG    schema                        current flexget version already exist in db 2.7.1
2016-12-03 22:01 DEBUG    parsing                       setting default movie parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x7f08fd1a8810>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x7f08fd686110>})
2016-12-03 22:01 DEBUG    parsing                       setting default series parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x7f08fd1a8810>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x7f08fd686110>})
2016-12-03 22:01 DEBUG    cron_env                      Encoding UTF-8 stored
2016-12-03 22:01 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'UTF-8'
2016-12-03 22:01 DEBUG    task_queue                    task queue shutdown requested
2016-12-03 22:01 INFO     ipc.rpyc                      server started on [127.0.0.1]:44363
2016-12-03 22:01 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-12-03 22:01 DEBUG    task          tgexec          executing tgexec
2016-12-03 22:01 DEBUG    template      tgexec          Merging template tg into task tgexec
2016-12-03 22:01 DEBUG    template      tgexec          Merging template global into task tgexec
2016-12-03 22:01 DEBUG    input_cache   tgexec          cache name: apple_trailers_d3b178b1d625d9dad4ab3de88c8c9d70 (has: )
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/home/rss/newtrailers.rss with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/paramount/officechristmasparty/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/feeds/data/17813.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    apple_trailers tgexec          Config genre(s) do not match movie genre(s)
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/universal/frank-lola/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/feeds/data/18187.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    apple_trailers tgexec          Config genre(s) do not match movie genre(s)
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/independent/100-streets/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/feeds/data/18186.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    apple_trailers tgexec          Config genre(s) do not match movie genre(s)
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/independent/paterson/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/feeds/data/18183.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    apple_trailers tgexec          Config genre(s) do not match movie genre(s)
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/oscilloscope/always-shine/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/feeds/data/18085.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    apple_trailers tgexec          Config genre(s) do not match movie genre(s)
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/fox_searchlight/jackie/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/feeds/data/18037.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    apple_trailers tgexec          Config genre(s) do not match movie genre(s)
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/magnolia/the-eyes-of-my-mother/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    utils.requests tgexec          Fetching URL http://trailers.apple.com/trailers/feeds/data/17895.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-03 22:01 DEBUG    apple_trailers tgexec          Config genre(s) do not match movie genre(s)
2016-12-03 22:01 CRITICAL task          tgexec          BUG: Unhandled error in plugin apple_trailers: u'movie_url'
2016-12-03 22:01 CRITICAL manager       tgexec          An unexpected crash has occurred. Writing crash report to /home/flexget/crash_report.2016.12.03.220143617110.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.7.1
2016-12-03 22:01 DEBUG    manager       tgexec          Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 148, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/apple_trailers.py", line 120, in on_task_input
    movie_data = trailers['movie_url']['json']
KeyError: u'movie_url'
2016-12-03 22:01 WARNING  task          tgexec          Aborting task (plugin: apple_trailers)
2016-12-03 22:01 DEBUG    notify_crash  tgexec          sending crash notification
2016-12-03 22:01 DEBUG    notify        tgexec          successfully rendered `title` to Task tgexec has crashed!
2016-12-03 22:01 DEBUG    notify        tgexec          failed to render: Error during string replacement: not all arguments converted during string formatting. Trying to fall back to default
2016-12-03 22:01 WARNING  notify        tgexec          default dict failed to render: Error during string replacement: not all arguments converted during string formatting. Reverting to original value.
2016-12-03 22:01 DEBUG    notify        tgexec          successfully rendered `message` to Reason: BUG: Unhandled error in plugin apple_trailers: u'movie_url'
2016-12-03 22:01 DEBUG    notify        tgexec          failed to render: Error during string replacement: not all arguments converted during string formatting. Trying to fall back to default
2016-12-03 22:01 DEBUG    notify        tgexec          failed to render: Error during string replacement: not all arguments converted during string formatting. Trying to fall back to default
2016-12-03 22:01 DEBUG    notify        tgexec          failed to render: Trying to render non string template or unrecognized template format, got [{u'username': u'coudy'}, {u'group': u'nasko'}]. Trying to fall back to default
2016-12-03 22:01 DEBUG    notify        tgexec          Sending a notification to `telegram`
2016-12-03 22:01 DEBUG    telegram      tgexec          token=<token>, parse_mode=markdown, tmpl=Reason: BUG: Unhandled error in plugin apple_trailers: u'movie_url', usernames=[u'coudy'], fullnames=[], groups=[u'nasko']
2016-12-03 22:01 DEBUG    telegram.bot  tgexec          Entering: getMe
2016-12-03 22:01 DEBUG    telegram.bot  tgexec          {'username': u'NasFlexgetBot', 'first_name': u'Flexget', 'last_name': '', 'type': '', 'id': 283764751}
2016-12-03 22:01 DEBUG    telegram.bot  tgexec          Exiting: getMe
2016-12-03 22:01 DEBUG    telegram      tgexec          loading cached chat ids
2016-12-03 22:01 DEBUG    telegram      tgexec          found 0 cached chat_ids: []
2016-12-03 22:01 DEBUG    telegram      tgexec          loading new chat ids
2016-12-03 22:01 DEBUG    telegram.bot  tgexec          Entering: getUpdates
2016-12-03 22:01 CRITICAL task          tgexec          BUG: Unhandled error in plugin notify_crash: urlopen() got multiple values for keyword argument 'body'
2016-12-03 22:01 CRITICAL manager       tgexec          An unexpected crash has occurred. Writing crash report to /home/flexget/crash_report.2016.12.03.220143895560.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.7.1
2016-12-03 22:01 DEBUG    manager       tgexec          Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notify_crash.py", line 37, in on_task_abort
   plugin.get_plugin_by_name('notify').instance.send_notification(task, notify_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notify.py", line 141, in send_notification
    notifier.notify(**notification_data)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 188, in notify
    chat_ids = self._real_init(Session(), telegram_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 223, in _real_init
    chat_ids = self._get_chat_ids_n_update_db(session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 279, in _get_chat_ids_n_update_db
    chat_ids, has_new_chat_ids = self._get_chat_ids(session, usernames, fullnames, groups)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 317, in _get_chat_ids
    new_chat_ids = list(self._get_new_chat_ids(usernames, fullnames, groups))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 374, in _get_new_chat_ids
    upd_usernames, upd_fullnames, upd_groups = self._get_bot_updates()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 412, in _get_bot_updates
    ups = self._bot.getUpdates(last_upd, limit=100)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 124, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1233, in getUpdates
    result = self._request.post(url, data, timeout=urlopen_timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 205, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'
2016-12-03 22:01 WARNING  task          tgexec          Aborting task (plugin: notify_crash)
2016-12-03 22:01 ERROR    task          tgexec          abort handlers aborted:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 618, in _execute
    self.__run_task_phase('abort')
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 453, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 516, in __run_plugin
    self.abort(msg, traceback=traceback)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 370, in abort
    raise TaskAbort(reason, silent=silent)
TaskAbort
2016-12-03 22:01 DEBUG    task_queue                    task tgexec aborted: TaskAbort(reason=BUG: Unhandled error in plugin notify_crash: urlopen() got multiple values for keyword argument 'body', silent=False)
2016-12-03 22:01 DEBUG    task_queue                    task queue shut down
2016-12-03 22:01 INFO     ipc.rpyc                      listener closed
2016-12-03 22:01 DEBUG    util.simple_persistence                 Flushing simple persistence for task None to db.
2016-12-03 22:01 INFO     ipc.rpyc                      server has terminated
2016-12-03 22:01 DEBUG    manager                       Shutting down
2016-12-03 22:01 DEBUG    manager                       Removed /home/flexget/.config-lock


```

### Additional information:

- Flexget Version: 2.7.1
- Python Version: 2.7.9
- Installation method: pip
- OS and version: debian 8.6
- Link to crash log:

**Comment by liiight** [comment]
what version of `python-telegram-bot` you on?

**Comment by rchovan** [comment]
Hi, latest version 5.2.0

Dňa 4.12.2016 0:14 používateľ "Or Carmi" <notifications@github.com> napísal:

**Comment by liiight** [comment]
apple trailers is not really maintain anymore. the only other issue seems to me to be with telegram lib and not our code. I'll try to reproduce

**Comment by liiight** [comment]
i cannot get that telegram error, 
Are you able to get any telegram notification correctly?

**Comment by rchovan** [comment]
No, I can't get any telegram message.

Dňa 5.12.2016 14:58 používateľ "Or Carmi" <notifications@github.com>
napísal:

**Comment by liiight** [comment]
hmm. did you init the Bot?

**Comment by rchovan** [comment]
yes, 
as mentioned in description on http://flexget.com/Plugins/Notifiers/telegram

![image](https://cloud.githubusercontent.com/assets/6713920/20900998/d13fe030-bb30-11e6-9ea9-2e598227080c.png)


![image](https://cloud.githubusercontent.com/assets/6713920/20900966/ae7e10c6-bb30-11e6-8e45-e59bcc27529e.png)

**Comment by liiight** [comment]
this is a weird one. you consistently get that error?

**Comment by rchovan** [comment]
yes, 
here is my test config
``` cat tg.yml
templates:
  global:
    notify_crash:
      to:
        - telegram:
            bot_token: <token>
            parse_mode: markdown
            recipients:
              - username: coudy
              - group: nasko

  tg:
    telegram:
      bot_token: <token>
      message: "teeesting"
      parse_mode: markdown
      recipients:
        - username: coudy
        - group: nasko

tasks:
  notify:
    accept_all: yes
    apple_trailers:
      quality: 720p
      genres: ['Science Fiction']
    download: /data/trailers
    template:
      - tg
```

and here is crashlog:
```
emby@nas:/home/flexget$ flexget --loglevel debug -c tg.yml execute --task notify
2016-12-05 21:37 DEBUG    manager                       Figuring out config load paths
2016-12-05 21:37 DEBUG    manager                       Found config: /home/flexget/tg.yml
2016-12-05 21:37 DEBUG    manager                       Config file /home/flexget/tg.yml selected
2016-12-05 21:37 DEBUG    manager                       sys.defaultencoding: ascii
2016-12-05 21:37 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-12-05 21:37 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-12-05 21:37 DEBUG    plugin                        Trying to load plugins from: [u'/home/flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2016-12-05 21:37 DEBUG    plugin                        (u'Plugin `%s` requires `%s` to load.', u'memusage', u'ext lib `guppy`')
2016-12-05 21:37 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-12-05 21:37 DEBUG    deluge                        ConfigManager started..
2016-12-05 21:37 DEBUG    plugin                        Plugins took 0.80 seconds to load. 264 plugins in registry.
2016-12-05 21:37 DEBUG    manager                       Connecting to: sqlite:////home/flexget/db-tg.sqlite
2016-12-05 21:37 DEBUG    manager                       config_name: tg
2016-12-05 21:37 DEBUG    manager                       config_base: /home/flexget
2016-12-05 21:37 DEBUG    manager                       New config data loaded.
2016-12-05 21:37 DEBUG    schema                        current flexget version already exist in db 2.7.1
2016-12-05 21:37 DEBUG    parsing                       setting default movie parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x7f2efcbab850>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x7f2efd100150>})
2016-12-05 21:37 DEBUG    parsing                       setting default series parser to internal. (options: {u'internal': <flexget.plugins.parsers.parser_internal.ParserInternal object at 0x7f2efcbab850>, u'guessit': <flexget.plugins.parsers.parser_guessit.ParserGuessit object at 0x7f2efd100150>})
2016-12-05 21:37 DEBUG    cron_env                      Encoding UTF-8 stored
2016-12-05 21:37 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'UTF-8'
2016-12-05 21:37 DEBUG    task_queue                    task queue shutdown requested
2016-12-05 21:37 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-12-05 21:37 INFO     ipc.rpyc                      server started on [127.0.0.1]:43257
2016-12-05 21:37 DEBUG    task          notify          executing notify
2016-12-05 21:37 DEBUG    template      notify          Merging template tg into task notify
2016-12-05 21:37 DEBUG    template      notify          Merging template global into task notify
2016-12-05 21:37 DEBUG    remember_rej  notify          Task config has changed since last run, purging remembered entries.
2016-12-05 21:37 DEBUG    input_cache   notify          cache name: apple_trailers_d3b178b1d625d9dad4ab3de88c8c9d70 (has: )
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/home/rss/newtrailers.rss with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/paramount/officechristmasparty/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/feeds/data/17813.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    apple_trailers notify          Config genre(s) do not match movie genre(s)
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/universal/frank-lola/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/feeds/data/18187.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    apple_trailers notify          Config genre(s) do not match movie genre(s)
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/independent/100-streets/ with args () and kwargs {'allow_redirect
s': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/feeds/data/18186.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    apple_trailers notify          Config genre(s) do not match movie genre(s)
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/independent/paterson/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/feeds/data/18183.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    apple_trailers notify          Config genre(s) do not match movie genre(s)
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/oscilloscope/always-shine/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/feeds/data/18085.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    apple_trailers notify          Config genre(s) do not match movie genre(s)
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/fox_searchlight/jackie/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/feeds/data/18037.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    apple_trailers notify          Config genre(s) do not match movie genre(s)
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/magnolia/the-eyes-of-my-mother/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    utils.requests notify          Fetching URL http://trailers.apple.com/trailers/feeds/data/17895.json with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2016-12-05 21:37 DEBUG    apple_trailers notify          Config genre(s) do not match movie genre(s)
2016-12-05 21:37 CRITICAL task          notify          BUG: Unhandled error in plugin apple_trailers: u'movie_url'
2016-12-05 21:37 CRITICAL manager       notify          An unexpected crash has occurred. Writing crash report to /home/flexget/crash_report.2016.12.05.213757252693.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.7.1
2016-12-05 21:37 DEBUG    manager       notify          Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 148, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/apple_trailers.py", line 120, in on_task_input
    movie_data = trailers['movie_url']['json']
KeyError: u'movie_url'
2016-12-05 21:37 WARNING  task          notify          Aborting task (plugin: apple_trailers)
2016-12-05 21:37 DEBUG    notify_crash  notify          sending crash notification
2016-12-05 21:37 DEBUG    notify        notify          successfully rendered `title` to Task notify has crashed!
2016-12-05 21:37 DEBUG    notify        notify          failed to render: Error during string replacement: not all arguments converted during string formatting. Trying to fall back to default
2016-12-05 21:37 WARNING  notify        notify          default dict failed to render: Error during string replacement: not all arguments converted during string formatting. Reverting to original value.
2016-12-05 21:37 DEBUG    notify        notify          successfully rendered `message` to Reason: BUG: Unhandled error in plugin apple_trailers: u'movie_url'
2016-12-05 21:37 DEBUG    notify        notify          failed to render: Error during string replacement: not all arguments converted during string formatting. Trying to fall back to default
2016-12-05 21:37 DEBUG    notify        notify          failed to render: Error during string replacement: not all arguments converted during string formatting. Trying to fall back to default
2016-12-05 21:37 DEBUG    notify        notify          failed to render: Trying to render non string template or unrecognized template format, got [{u'username': u'coudy'}, {u'group': u'nasko'}]. Trying to fall back to default
2016-12-05 21:37 DEBUG    notify        notify          Sending a notification to `telegram`
2016-12-05 21:37 DEBUG    telegram      notify          token=<token>, parse_mode=markdown, tmpl=Reason: BUG: Unhandled error in plugin apple_trailers: u'movie_url', usernames=[u'coudy'], fullnames=[], groups=[u'nasko']
2016-12-05 21:37 DEBUG    telegram.bot  notify          Entering: getMe
2016-12-05 21:37 DEBUG    telegram.bot  notify          {'username': u'NasFlexgetBot', 'first_name': u'Flexget', 'last_name': '', 'type': '', 'id': 283764751}
2016-12-05 21:37 DEBUG    telegram.bot  notify          Exiting: getMe
2016-12-05 21:37 DEBUG    telegram      notify          loading cached chat ids
2016-12-05 21:37 DEBUG    telegram      notify          found 0 cached chat_ids: []
2016-12-05 21:37 DEBUG    telegram      notify          loading new chat ids
2016-12-05 21:37 DEBUG    telegram.bot  notify          Entering: getUpdates
2016-12-05 21:37 CRITICAL task          notify          BUG: Unhandled error in plugin notify_crash: urlopen() got multiple values for keyword argument 'body'
2016-12-05 21:37 CRITICAL manager       notify          An unexpected crash has occurred. Writing crash report to /home/flexget/crash_report.2016.12.05.213757609272.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.7.1
2016-12-05 21:37 DEBUG    manager       notify          Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notify_crash.py", line 37, in on_task_abort
    plugin.get_plugin_by_name('notify').instance.send_notification(task, notify_config)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notify.py", line 141, in send_notification
    notifier.notify(**notification_data)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 188, in notify
    chat_ids = self._real_init(Session(), telegram_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 223, in _real_init
    chat_ids = self._get_chat_ids_n_update_db(session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 279, in _get_chat_ids_n_update_db
    chat_ids, has_new_chat_ids = self._get_chat_ids(session, usernames, fullnames, groups)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 317, in _get_chat_ids
    new_chat_ids = list(self._get_new_chat_ids(usernames, fullnames, groups))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 374, in _get_new_chat_ids
    upd_usernames, upd_fullnames, upd_groups = self._get_bot_updates()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/telegram.py", line 412, in _get_bot_updates
    ups = self._bot.getUpdates(last_upd, limit=100)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 124, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 1233, in getUpdates
    result = self._request.post(url, data, timeout=urlopen_timeout)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 205, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 132, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'
2016-12-05 21:37 WARNING  task          notify          Aborting task (plugin: notify_crash)
2016-12-05 21:37 ERROR    task          notify          abort handlers aborted:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 618, in _execute
    self.__run_task_phase('abort')
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 453, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 516, in __run_plugin
    self.abort(msg, traceback=traceback)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 370, in abort
    raise TaskAbort(reason, silent=silent)
TaskAbort
2016-12-05 21:37 DEBUG    task_queue                    task notify aborted: TaskAbort(reason=BUG: Unhandled error in plugin notify_crash: urlopen() got multiple values for keyword argument 'body', silent=False)
2016-12-05 21:37 DEBUG    task_queue                    task queue shut down
2016-12-05 21:37 INFO     ipc.rpyc                      listener closed
2016-12-05 21:37 INFO     ipc.rpyc                      server has terminated
2016-12-05 21:37 DEBUG    util.simple_persistence                 Flushing simple persistence for task None to db.
2016-12-05 21:37 DEBUG    manager                       Shutting down
2016-12-05 21:37 DEBUG    manager                       Removed /home/flexget/.tg-lock
```

p.s.: I'm currently on IRC #flexget, we can talk directly

**Comment by rchovan** [comment]
working with this help: https://github.com/python-telegram-bot/python-telegram-bot/issues/481
