### ISSUE TITLE
Crashes during execution Series-NPO plugin

### ISSUE THREAD

**Issue by mfonville** [Flexget/Flexget#1540]
### Expected behaviour:
Execute the regular tasks with Series-NPO

### Actual behaviour:
It crashes during execution; see log below:

### Steps to reproduce:
Execute with version 2.7.2 it crashes
But works correctly with 2.6.9 installed

#### Config:
```
templates:
  tv:
    configure_series:
      settings:
        # Configure all the series options to your taste
        quality: 720p+
#        path: /my/shows//Season /  # This will sort your downloads if you are using one of the output plugins which supports it
      from:
        trakt_list:
          account: xxxxxxxxxxxxxxx
          list: My TV Shows
          type: shows

tasks:
  Series-NPO:
    npo_watchlist:
      email: 'xxxxxxxxxxxxxxxxxxxxxxx'
      password: 'xxxxxxxxxxxxxxxxxxxx'
      max_episode_age_days: 3
    plugin_priority:
      thetvdb_lookup: 500
      trakt_lookup: 250
    thetvdb_lookup:
      language: nl
    trakt_lookup:
      account: xxxxxxxxx
      username: xxxxxxxx
    if:
      - "tvdb_series_name and trakt_watched": reject
    exec:
      fail_entries: yes
      auto_escape: yes
      on_output:
        for_accepted:
```
  
#### Log:
```
2016-12-05 19:26 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-12-05 19:26 INFO     search_npo    Series-NPO      Retrieving npo.nl episode watchlist for xxxxxxxx
2016-12-05 19:26 INFO     search_npo    Series-NPO      Retrieving npo.nl favorite series for xxxxxxxxx
2016-12-05 19:26 INFO     search_npo    Series-NPO      Retrieving new episodes for Toren C
2016-12-05 19:26 INFO     search_npo    Series-NPO      Retrieving new episodes for VPRO Tegenlicht
2016-12-05 19:26 INFO     search_npo    Series-NPO      Retrieving new episodes for Als de dijken breken
2016-12-05 19:26 VERBOSE  backlog       Series-NPO      Added 1 entries from backlog
2016-12-05 19:26 VERBOSE  details       Series-NPO      Produced 4 entries.
2016-12-05 19:27 VERBOSE  api_trakt     Series-NPO      Received 94 record(s) from trakt.tv xxxxxxxxx watched history
2016-12-05 19:27 VERBOSE  task          Series-NPO      ACCEPTED: `Toren C Sint Special (VPWON_1240466)` by accept_all plugin
2016-12-05 19:27 VERBOSE  task          Series-NPO      ACCEPTED: `Black Lives Matter (VPWON_1257589)` by accept_all plugin
2016-12-05 19:27 VERBOSE  task          Series-NPO      ACCEPTED: `Een hart onder de riem (VPWON_1243429)` by accept_all plugin
2016-12-05 19:27 VERBOSE  task          Series-NPO      ACCEPTED: `Sint Special (VPWON_1240466)` by accept_all plugin
2016-12-05 19:27 VERBOSE  details       Series-NPO      Summary - Accepted: 4 (Rejected: 0 Undecided: 0 Failed: 0)
2016-12-05 19:27 VERBOSE  api_trakt     Series-NPO      Received 82 record(s) from trakt.tv xxxxxxxxxxxxxxxxxxxx shows user ratings
2016-12-05 19:27 WARNING  api_trakt     Series-NPO      No collection data returned from trakt.
2016-12-05 19:27 WARNING  api_trakt     Series-NPO      No collection data returned from trakt.
2016-12-05 19:27 CRITICAL task          Series-NPO      BUG: Unhandled error in plugin exec: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/exec.py", line 194, in phase_handler
    self.execute(task, 'on_' + phase, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/exec.py", line 142, in execute
    cmd = render_from_entry(cmd, entrydict)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/template.py", line 212, in render_from_entry
    variables['task_name'] = variables.get('task', entry.task.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

### Additional information:

- Flexget Version: 2.7.2
- Python Version: 2.7.12+
- Installation method: pip
- OS and version: Ubuntu 16.10

**Comment by liiight** [comment]
Probably same as #1538
