### ISSUE TITLE
BUG: Unhandled error in plugin rtorrent: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by CryogenicPilot** [Flexget/Flexget#1546]
### Expected behaviour:
add torrent to torrent remote host with data path
### Actual behaviour:
unhandled exception
### Steps to reproduce:
- Step 1: flexget execute

#### Config:
```
rtorrent:
      uri: http://xxxxxxxx
      username: xxxxxxxx
      password: xxxxxxxxx
      path: /files/{{ series_name }}/Season {{series_season}}/
      custom1: TV
```
  
#### Log:
```
2016-12-10 19:00 CRITICAL task          search          BUG: Unhandled error in plugin rtorrent: 'NoneType' object has no attribute 'name'
2016-12-10 19:00 CRITICAL manager       search          An unexpected crash has occurred. Writing crash report to /home/alby/.flexget/crash_report.2016.12.10.190020880324.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.7.1
2016-12-10 19:00 DEBUG    manager       search          Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/rtorrent.py", line 525, in on_task_output
    options = self._build_options(config, entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/rtorrent.py", line 431, in _build_options
    options[opt_key] = entry.render(config_value)
  File "/usr/local/lib/python2.7/dist-packages/flexget/entry.py", line 294, in render
    return render_from_entry(template, self)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/template.py", line 212, in render_from_entry
    variables['task_name'] = variables.get('task', entry.task.name)
AttributeError: 'NoneType' object has no attribute 'name'
2016-12-10 19:00 WARNING  task          search          Aborting task (plugin: rtorrent)
```

### Additional information:

- Flexget Version: 2.8.1
- Python Version: 2.7.11
- Installation method: pip
- OS and version: Ubuntu 14.04.4 LTS
- Link to crash log:

**Comment by cvium** [comment]
#1545
