### ISSUE TITLE
local pip install problem (SOURCES.txt)

### ISSUE THREAD

**Issue by Andy2244** [Flexget/Flexget#1566]
I got this error while trying to install my local dev version, this worked a few days ago?

For some reason the sources.txt has those entries in it?
```
flexget/templates/entries/default.template
flexget/templates/entries/default.template/
flexget/templates/task/accepted.template
flexget/templates/task/default.template
flexget/templates/task/failed.template
flexget/templates/task/html.template
flexget/templates/task/rss.template
flexget/templates/task/accepted.template/
flexget/templates/task/default.template/
flexget/templates/task/failed.template/
flexget/templates/task/html.template/
flexget/templates/task/rss.template/
```

Any idea what caused this?

```
pip install -e .
Obtaining file:///Z:/GitHub/Flexget
    Complete output from command python setup.py egg_info:
    running egg_info
    writing requirements to FlexGet.egg-info\requires.txt
    writing dependency_links to FlexGet.egg-info\dependency_links.txt
    writing entry points to FlexGet.egg-info\entry_points.txt
    writing top-level names to FlexGet.egg-info\top_level.txt
    writing FlexGet.egg-info\PKG-INFO
    reading manifest file 'FlexGet.egg-info\SOURCES.txt'
    c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\dist.py:332: UserWarning: Normalizing '2.8.5.dev' to '2.8.5.dev0'
      normalized_version,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "Z:\GitHub\Flexget\setup.py", line 56, in <module>
        "Programming Language :: Python :: Implementation :: PyPy",
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 279, in run
        self.find_sources()
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 306, in find_sources
        mm.run()
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 533, in run
        self.add_defaults()
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 576, in add_defaults
        self.read_manifest()
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\sdist.py", line 205, in read_manifest
        self.filelist.append(line)
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 475, in append
        path = convert_path(item)
      File "c:\users\andy\appdata\local\programs\python\python35-32\lib\distutils\util.py", line 127, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'flexget/templates/entries/default.template/' cannot end with '/'
```

**Comment by Andy2244** [comment]
Seems this only happens if i clone the repo to a samba network drive and only for those template files?
Is there anything special about those files and why they generate duplicated entries in the source.txt?

**Comment by paranoidi** [comment]
Samba has limitations that might come into play in weird places ...

This comes from distutils so ... you're on your own with this one. If you figure something we can improve open new ticket.
