### ISSUE TITLE
BUG: Unhandled error in plugin series: unorderable types: Episode() < Episode()

### ISSUE THREAD

**Issue by lamski** [Flexget/Flexget#1592]
Noticed that a lot of crash logs were being generated by flexget beginning on the 24th of December.
Apparently, when I updated to flexget 2.8.x at that time, Python has a problem with the series plugin:
```
if ep < ep.series.begin: <-- python 3.4 could not sort these objects
    for entry in entries:
        entry.reject('Episode `%s` is before begin value of `%s`' %
            (ep.identifier, ep.series.begin.identifier))
    continue
```
For the moment, I put the whole statement above in a try-catch-all until this is fixed.

### Steps to reproduce:
- Step 1: Configure the latest version of flexget to run under python 3.4
- Step 2: Execute a series task and it will produce the crash logs.

#### Log:
```
2016-12-28 15:00 CRITICAL manager       TVRSS           An unexpected crash has occurred. Writing crash report to /shares/conf/flexget/crash_report.2016.12.28.150039161653.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.8.x
```

### Additional information:

- Flexget Version: 2.8.14
- Python Version: 3.4.3
- Installation method: pip
- OS and version: Ubuntu 14.04.5 LTS (server)

**Comment by lamski** [comment]
Apologies, I deleted all of them earlier. Now, I've removed the try-catch statement and ran in test mode but it's not crashing. I'll attach as soon as new crash logs are generated.

**Comment by lamski** [comment]
It's been 3 days, updated to the latest version (2.8.15), and the crash is no longer occurring.
I think it has something to do with the version of flexget that is running as a daemon.
From what I remember from the crash logs, even though I've updated to 2.8.x, the crash says the version is 2.5.0. I was able to consistently reproduce the crash then. But when I restarted the machine, that's when the crash stopped happening.

I guess there is a need to restart the flexget daemon after updating the software to avoid potential conflicts.

**Comment by liiight** [comment]
not restarting daemon after upgrade basically means you're running the old code. Also, always kill your daemon before upgrading.

**Comment by pedro-MD11** [comment]
I'm having the same problem. I've attached the crash log.
[crash_report.2017.01.02.164414291199.log.txt](https://github.com/Flexget/Flexget/files/681318/crash_report.2017.01.02.164414291199.log.txt)

**Comment by tkngdwn** [comment]
I'm encountering the same issue as well. It started appearing around the same time. I think I have isolated the reason why though, and I suspect the same was occurring for lamski as well given the time it began.

I had it fire off some print statements before comparing the values. Here is what it spat out just before it errored out:

<Episode(id=516,identifier=s10 christmas the return of doctor mysterio ntb,season=None,number=None)>
<Episode(id=37,identifier=S10E01,season=10,number=1)>

It seems like there's no catch for it comparing those values when they're not in a sane format.

**Comment by sloniu82** [comment]
I'm experiencing this bug too, afrer upgrade flexget to 2.9.3.
```
2017-01-13 09:03 VERBOSE  task          torrentsite    REJECTED: `Kidnapped.The.Search.For.Tommy.2015.1080p.HDTV.x264-PLUTONiUM` by regexp plugin because regexp '1080p' matched field 'title'
2017-01-13 09:03 DEBUG    series        torrentsite    adding episode S04E10 into series the.blacklist
2017-01-13 09:03 DEBUG    series        torrentsite    -> added <Episode(id=None,identifier=S04E10,season=4,number=10)>
2017-01-13 09:03 DEBUG    series        torrentsite    adding release <SeriesParser(data=The.Blacklist.S04E10.HDTV.x264-KILLERS,name=the.blacklist,id=None,season=4,episode=10,quality=hdtv h264,proper=0,status=OK)> into episode
2017-01-13 09:03 DEBUG    series        torrentsite    -> added <Release(id=None,quality=hdtv h264,downloaded=None,proper_count=0,title=The.Blacklist.S04E10.HDTV.x264-KILLERS)>
2017-01-13 09:03 DEBUG    series        torrentsite    adding release <SeriesParser(data=The.Blacklist.S04E10.720p.HDTV.x264-KILLERS,name=the.blacklist,id=None,season=4,episode=10,quality=720p hdtv h264,proper=0,status=OK)> into episode
2017-01-13 09:03 DEBUG    series        torrentsite    -> added <Release(id=None,quality=720p hdtv h264,downloaded=None,proper_count=0,title=The.Blacklist.S04E10.720p.HDTV.x264-KILLERS)>
2017-01-13 09:03 DEBUG    series        torrentsite    start with episodes: ['The.Blacklist.S04E10.720p.HDTV.x264-KILLERS', 'The.Blacklist.S04E10.HDTV.x264-KILLERS']
2017-01-13 09:03 CRITICAL task          torrentsite    BUG: Unhandled error in plugin series: unorderable types: Episode() < Episode()
2017-01-13 09:03 CRITICAL manager       torrentsite    An unexpected crash has occurred. Writing crash report to /opt/flexuser/.flexget/crash_report.2017.01.13.090302388711.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.9.3
2017-01-13 09:03 DEBUG    manager       torrentsite    Traceback:
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/flexget/task.py", line 490, in __run_plugin
    return method(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/flexget/plugins/filter/series.py", line 1251, in on_task_filter
    self.process_series(task, series_entries, series_config)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/flexget/plugins/filter/series.py", line 1333, in process_series
    if ep < ep.series.begin:
TypeError: unorderable types: Episode() < Episode()
```

**Comment by liiight** [comment]
i think this is an issue of a special episode that had no number being compared to a begin episode. Do any of you happen to have the exact episode title?

**Comment by liiight** [comment]
It's funny, the reason it happened to so many people at the same time is Christmas specials

**Comment by arthurwolf** [comment]
I have the same problem:

```
2025-01-21 00:17:40 CRITICAL task          nyaanonen       BUG: Unhandled error in plugin series: '<' not supported between instances of 'Episode' and 'Episode'
Traceback (most recent call last):
   
  File "/home/arthur/.pyenv/versions/3.10.15/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x759ab26faf80>
    └ <Thread(task_queue, started daemon 129307177387712)>
  File "/home/arthur/.pyenv/versions/3.10.15/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x759ab26facb0>
    └ <Thread(task_queue, started daemon 129307177387712)>
  File "/home/arthur/.pyenv/versions/3.10.15/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 129307177387712)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 129307177387712)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x759aacadbf10>>
    └ <Thread(task_queue, started daemon 129307177387712)>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x759aaf8e0790>
    │    └ <flexget.task.Task object at 0x759aac74c5e0>
    └ <flexget.task_queue.TaskQueue object at 0x759aacadbf10>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 88, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x759aac74c5e0>
           └ <function Task.execute at 0x759aaf8e0700>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 717, in execute
    self._execute()
    │    └ <function Task._execute at 0x759aaf8e0670>
    └ <flexget.task.Task object at 0x759aac74c5e0>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 686, in _execute
    self.__run_task_phase(phase)
    │                     └ 'filter'
    └ <flexget.task.Task object at 0x759aac74c5e0>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 515, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x759aac74c5e0>, [{'Kaguya-Sama': {'alternate_name': ['Kaguya-sama wa Kokurasetai? Tensai-tachi...
               │                 │       └ 'filter'
               │                 └ <PluginInfo(name=series)>
               └ <flexget.task.Task object at 0x759aac74c5e0>
> File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 548, in __run_plugin
    result = method(*args, **kwargs)

```
