### ISSUE TITLE
Can't delete movie from movie-list using cmdline

### ISSUE THREAD

**Issue by drwyrm** [Flexget/Flexget#1606]
### Actual behaviour:
```
$ ./bin/flexget movie-list del "movies queue" "The Fantastic Four 2"
Traceback (most recent call last):
  File "./bin/flexget", line 9, in <module>
    load_entry_point('FlexGet==2.8.17.dev', 'console_scripts', 'flexget')()
  File "/home/wyrm/flexget/flexget/__init__.py", line 42, in main
    manager.start()
  File "/home/wyrm/flexget/flexget/manager.py", line 327, in start
    self.handle_cli()
  File "/home/wyrm/flexget/flexget/manager.py", line 354, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/home/wyrm/flexget/flexget/plugins/cli/movie_list.py", line 76, in do_cli
    movie_list_del(options)
  File "/home/wyrm/flexget/flexget/plugins/cli/movie_list.py", line 181, in movie_list_del
    title, year = split_title_year(options.movie_title)
  File "/home/wyrm/flexget/flexget/options.py", line 157, in __getattr__
    return getattr(self.__parent__, key)
  File "/home/wyrm/flexget/flexget/options.py", line 158, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (type(self).__name__, key))
AttributeError: 'ScopedNamespace' object has no attribute 'movie_title'
```

**Comment by chewy74** [comment]
I can confirm this on version 2.8.18  
Crashes when trying to delete a title from your movie-list. 

Debug log
`
pi@raspberrypi:~ $ flexget --debug movie-list del vic_movies "Split (2017)"
2017-01-04 23:32 DEBUG    manager                       Figuring out config load paths
2017-01-04 23:32 DEBUG    manager                       Found config: /home/pi/.flexget/config.yml
2017-01-04 23:32 DEBUG    manager                       Config file /home/pi/.flexget/config.yml selected
2017-01-04 23:32 DEBUG    manager                       sys.defaultencoding: ascii
2017-01-04 23:32 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2017-01-04 23:32 DEBUG    manager                       flexget detected io encoding: utf-8
2017-01-04 23:32 DEBUG    manager                       os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2017-01-04 23:32 DEBUG    manager                       Sending command to running FlexGet process: [u'--debug', u'movie-list', u'del', u'vic_movies', u'Split (2017)']
2017-01-04 23:32 DEBUG    movie_list                    returning list with name vic_movies
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 310, in start
    client.handle_cli(self.args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
AttributeError: 'ScopedNamespace' object has no attribute 'movie_title'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 85, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 354, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/movie_list.py", line 76, in do_cli
    movie_list_del(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/movie_list.py", line 181, in movie_list_del
    title, year = split_title_year(options.movie_title)
  File "/usr/local/lib/python2.7/dist-packages/flexget/options.py", line 157, in __getattr__
    return getattr(self.__parent__, key)
  File "/usr/local/lib/python2.7/dist-packages/flexget/options.py", line 158, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (type(self).__name__, key))
AttributeError: 'ScopedNamespace' object has no attribute 'movie_title'

`

**Comment by liiight** [comment]
sorry about this, you can delete by id as a workaround. ill address this asap

**Comment by antivirtel** [comment]
It also happens to me too, with version 2.9.9.
