### ISSUE TITLE
"sqlalchemy.exc.DatabaseError: database disk image is malformed" on CLI command

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#1626]
### Expected behaviour:
show the result of the CLI command

### Actual behaviour:
```logtalk
$ flexget series show "Some Show"
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 326, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 200, in initialize
    self.init_sqlalchemy()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 729, in init_sqlalchemy
    Base.metadata.create_all(bind=self.engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 3848, in create_all
    tables=tables)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1920, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1529, in _run_visitor
    **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 712, in visit_metadata
    [t for t in tables if self._can_create_table(t)])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 687, in _can_create_table
    table.name, schema=effective_schema)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 1183, in has_table
    connection, "table_info", table_name, schema=schema)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 1569, in _get_table_pragma
    cursor = connection.execute(statement)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed [SQL: u'PRAGMA table_info("episode_releases")']
```
The daemon seems to be running and doing its job...

### Steps to reproduce:
- Step 1: execute a CLI command

#### Config:
```
series:
[...]
  - Some Show
```
  
#### Log:
See above.

### Additional information:

- Flexget Version: 2.9.3 (also 2.8.24)
- Python Version: 2.7.9
- Installation method: pip
- OS and version: Raspbian 8

**Comment by liiight** [comment]
did you happen to stop a db upgrade process?

**Comment by antivirtel** [comment]
No, I also always use `screen` during any upgrade...

**Comment by antivirtel** [comment]
Seems to be fixed after running:
```sql
sqlite> pragma integrity_check;
```
Got `ok` as a response, then everything worked.
[Source](http://froebe.net/blog/2015/05/27/error-sqlite-database-is-malformed-solved/) - thanks.

[These](http://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed) didn't help.

**Comment by liiight** [comment]
Awesome. Thanks for giving the answer!

**Comment by antivirtel** [comment]
It has been returned. The SQL query could be executed via sqlite3 CLI client, it will not fail. The DB ntegrity is ok. `fsck` shows no error. Could it be Flexget related?

**Comment by antivirtel** [comment]
The `journal_mode` was `delete` again. Is #328 working well? ( @gazpachoking ?)  It is the second time, I switch it on manually.

**Comment by gazpachoking** [comment]
@antivirtel We had to back out that WAL, as it was causing other problems (I can't remember what though.) We don't set the journal_mode at all anymore.

**Comment by antivirtel** [comment]
Thanks for the info! What else can cause this? If I use CLI `sqlite3`, it won't throw an error on the same query. Is that possible, that there were a schema update, that was not executed? (As I already wrote, there was no interrupted upgrade.)

**Comment by gazpachoking** [comment]
I'm not really sure what could be causing it, perhaps it's WAL mode? Maybe this is the reason we took that out. Have you set the journal mode to WAL before these errors started happening?

**Comment by antivirtel** [comment]
No, I just enabled that, since I read [this](https://www.sqlite.org/howtocorrupt.html#_disk_drives_that_do_not_honor_sync_requests):
```
There is no way for SQLite to detect that either is lying and that writes might be occurring out-of-order. However, SQLite in WAL mode is far more forgiving of out-of-order writes than in the default rollback journal modes. In WAL mode, the only time that a failed sync operation can cause database corruption is during a checkpoint operation.
```
It seemed, that WAL would be better for me, since it is a SD.

**Comment by liiight** [comment]
Not sure there's anything to do with that

**Comment by antivirtel** [comment]
@liiight it is still happening. At the moment I'm at version 2.10.32. I have a process how to fix this, when I want to run some CLI commands:
```bash
DB_NAME=db-config.sqlite; cd ~/.flexget/; echo '.dump'|sqlite3 $DB_NAME|sqlite3 repaired_$DB_NAME && mv $DB_NAME corrupt_$DB_NAME && mv repaired_$DB_NAME $DB_NAME
```

When I start the daemon, it will make the DB malformed after some task runs. How it is possible? I still can't figure it out.

**Comment by gazpachoking** [comment]
Haven't heard on this in a while, hoping this was specific to your setup, or that it was fixed.
