### ISSUE TITLE
Running without specifying command crashes

### ISSUE THREAD

**Issue by Devils0411** [Flexget/Flexget#1633]
After update Flexget to 2.9.4, and some command in config file is incorrect.
A little path of config.yml

```
tasks:
  Movie:
    priority: 2
    inputs:
      - rss: '{? RRSUrls.url1 ?}'
      - rss: '{? RRSUrls.url2 ?}'
      - rss: '{{ secretfile.RRSUrls.url3 }}'
```

error:
2017-01-16 14:16 CRITICAL manager [/tasks/Movie/inputs/2/rss] '{{ secretfile.RRSUrls.url3 }}' is not valid under any of the given schemas

If i change like this:

```
tasks:
  Movie:
    priority: 2
    inputs:
      - rss: '{? RRSUrls.url1 ?}'
      - rss: '{? RRSUrls.url2 ?}'
      - rss: '{? RRSUrls.url3 ?}'
```

error:
```
2017-01-16 14:19 INFO manager Test database created
Traceback (most recent call last):
File "/opt/bin/flexget", line 11, in 
sys.exit(main())
File "/opt/lib/python3.5/site-packages/flexget/__init__.py", line 42, in main
manager.start()
File "/opt/lib/python3.5/site-packages/flexget/manager.py", line 327, in start
self.handle_cli()
File "/opt/lib/python3.5/site-packages/flexget/manager.py", line 345, in handle_cli
command_options = getattr(options, command)
TypeError: getattr(): attribute name must be string
```
In secretfile.yml:
RRSUrls:
url2: http://nnmclub.to/forum/rss2.php?f=954&uk
url3: http://nnmclub.to/forum/rss2.php?f=227&uk

**Comment by paranoidi** [comment]
What command did you run? Did you remember to shutdown the daemon before upgrading.

**Comment by Devils0411** [comment]
Yes. Daemon is shutdown, when i upgrade.
Command
`flexget --test`

**Comment by Devils0411** [comment]
upgrade to 2.9.5 solved the problem.

**Comment by liiight** [comment]
No it didn't, The problem is that we enable running flexget with no command if a manager argument is passed.

**Comment by paranoidi** [comment]
I think I made some ugly hacks for this .. open new ticket if this is happening.
