### ISSUE TITLE
my_anime_list plugin crashes with KeyError exception

### ISSUE THREAD

**Issue by hlissner** [Flexget/Flexget#1640]
### Expected behaviour:

1. `flexget execute`
2. Series info gets scraped from myanimelist
3. Downloads unseen episodes

### Actual behaviour:

`flexget execute`

```
2017-01-17 07:58 CRITICAL task          anime           BUG: Unhandled error in plugin configure_series: '0'
2017-01-17 07:58 CRITICAL manager       anime           An unexpected crash has occurred. Writing crash report to ~/.config/flexget/crash_report.2017.01.17.075808482439.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.9.6
2017-01-17 07:58 WARNING  task          anime           Aborting task (plugin: configure_series)
```

#### Config:
```
tasks:
  anime:
    rss: "http://tokyotosho.info/rss.php?filter=1&zwnj=0"
    configure_series:
      from:
        my_anime_list:
          username: vnought
          type:
            - series
          status:
            - watching
            - plan_to_watch
```
  
#### Log:
```
2017-01-17 07:48 CRITICAL task          anime           BUG: Unhandled error in plugin configure_series: '0'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flexget/task.py", line 490, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/operate/configure_series.py", line 71, in on_task_start
    result = method(task, input_config)
  File "/usr/lib/python3.6/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/utils/cached_input.py", line 148, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/input/my_anime_list.py", line 81, in on_task_input
    anime_type = ANIME_TYPE[item.findtext('series_type', 1)]
KeyError: '0'
```

### Additional information:

- Flexget Version: 2.9.6
- Python Version: 3.6.0
- Installation method: `pip install flexget`
- OS and version: Arch Linux 4.8.13

**Comment by Nyoroon** [comment]
Same problem here
### Config
```
tasks:
  horrible:
    make_rss: /var/www/rss.xml
    horriblesubs: yes
    cfscraper: yes
    my_anime_list:
      username: Nyoroon
      status:
        - watching
    quality: 720p+
```
### Crash log
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flexget/task.py", line 490, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flexget/utils/cached_input.py", line 148, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flexget/plugins/input/my_anime_list.py", line 81, in on_task_input
    anime_type = ANIME_TYPE[item.findtext('series_type', 1)]
KeyError: '6'
```
### Additional information
- Flexget Version: 2.9.6
- Python Version: 3.6.0
- Installation method: `pip install flexget`
- OS and version: `python:alpine` docker container (Alpine Linux 3.4)
