### ISSUE TITLE
Exception occurs on .config-lock

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#1644]
### Expected behaviour:
No exception should occur

### Actual behaviour:
Exception being thrown when starting Flexget after forcefully killing it (using htop for example)

### Steps to reproduce:
- Step 1: Start Flexget daemon
- Step 2: Kill using kill command
- Step 3: Start daemon again
  
#### Log:
```
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 328, in start
    self._shutdown()
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 808, in acquire_lock
    self.release_lock()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 821, in release_lock
    os.remove(self.lockfile)
OSError: [Errno 2] No such file or directory: '/home/tom/.flexget/.config-lock’
```

### Additional information:

- Flexget Version: 2.8.24
- Python Version: 2.7.6
- Installation method: pip
- OS and version: ubuntu 14.04

**Comment by liiight** [comment]
Should we catch the error and continue or exit flexget? @paranoidi @gazpachoking

**Comment by evgsd** [comment]
I think need continue run app

**Comment by Lukeid** [comment]
Hello,

I'm having the same problem in a Synology NAS:

Starting FlexGet ...
2018-04-04 22:57 INFO     manager                       Daemonizing...
2018-04-04 22:57 INFO     manager                       Daemonize complete. New PID: 1176
Traceback (most recent call last):
  File "/usr/local/flexget/env/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/manager.py", line 332, in start
    self._shutdown()
  File "/usr/local/python/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/manager.py", line 812, in acquire_lock
    self.release_lock()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/manager.py", line 825, in release_lock
    os.remove(self.lockfile)
OSError: [Errno 2] No such file or directory: '/volume1/config/.config-lock'

But the file exists:
$ ls -l /volume1/config/.config-lock
-rw-rw-rw- 1 flexget users 48 Apr  5 00:58 /volume1/config/.config-lock

What should I do?

Flexget Version: 2.13.6

Thank you in advance.
