### ISSUE TITLE
`$ flexget plugins` crashes

### ISSUE THREAD

**Issue by haarts** [Flexget/Flexget#1650]
### Expected behaviour:
`$ flexget plugins` should return a list of available plugins.

### Actual behaviour:
It crashes:
```
$ flexget plugins
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/home/harm/.local/lib/python3.5/site-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/home/harm/.local/lib/python3.5/site-packages/flexget/manager.py", line 327, in start
    self.handle_cli()
  File "/home/harm/.local/lib/python3.5/site-packages/flexget/manager.py", line 354, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/home/harm/.local/lib/python3.5/site-packages/flexget/plugins/cli/plugins.py", line 20, in plugins_summary
    for plugin in sorted(get_plugins(phase=options.phase, interface=options.interface)):
  File "/home/harm/.local/lib/python3.5/site-packages/flexget/options.py", line 157, in __getattr__
    return getattr(self.__parent__, key)
  File "/home/harm/.local/lib/python3.5/site-packages/flexget/options.py", line 158, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (type(self).__name__, key))
AttributeError: 'ScopedNamespace' object has no attribute 'interface'
```
### Steps to reproduce:
- Step 1: Install via pip.
- Step 2: `$ flexget plugins`.

#### Config:
None.
  
#### Log:

See for stdout (ran with `-L trace`): http://sprunge.us/NTJd
The stderr is under the header .Actual behaviour'.

### Additional information:

- Flexget Version: 2.9.8
- Python Version: 3.5.2
- Installation method: pip3
- OS and version: Ubuntu 16.04
- Link to crash log: http://sprunge.us/NTJd

**Comment by gazpachoking** [comment]
Oops, looks like I missed renaming https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/cli/plugins.py#L54 for #1555

**Comment by liiight** [comment]
Right. I'll fix it later if you won't beat me to it
