### ISSUE TITLE
Bug in T411 plugin

### ISSUE THREAD

**Issue by karma007** [Flexget/Flexget#1679]
### Expected behaviour:
No bug  in t411 plugin

### Actual behaviour:
bug -> task abort

### Steps to reproduce:
1 to 5 times per day (rest of time : works)

#### Config:
```
t411 plugin
```
  
#### Log:
```
Task has aborted : Reason: BUG: Unhandled error in plugin t411:

logs : 
2017-02-10 10:00 DEBUG    t411_api      get_tvshowshd_411 Resolving terms : [u'VOSTFR']
2017-02-10 10:00 DEBUG    t411_api      get_tvshowshd_411 None API token. Authenticating with "westenk" account...
2017-02-10 10:00 DEBUG    utils.requests get_tvshowshd_411 Fetching URL http://api.t411.li/auth with args () and kwargs {'json': None, 'data': {u'username': u'xxxxxxxxxxxxxx', u'password': u'xxxxxxxxxxxx'}, u'timeout': 30}
2017-02-10 10:00 ERROR    t411_api      get_tvshowshd_411 1040 - SQLSTATE[HY000] [1040] Too many connections
2017-02-10 10:00 CRITICAL task          get_tvshowshd_411 BUG: Unhandled error in plugin t411: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/sites/t411.py", line 75, in on_task_input
    return proxy.search(query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 663, in search
    json_results = self.rest_client.search(client_query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 169, in wrapper
    assert self.is_authenticated()
AssertionError

```

### Additional information:

- Flexget Version: 2.9.17
- Python Version: 2.7.9
- Installation method:
- OS and version: raspbian jessie
- Link to crash log: none

thanks

**Comment by karma007** [comment]
hello, any news ? thanks

**Comment by lildadou** [comment]
I'm sorry but I can not devote time to this error: '(

**Comment by cvium** [comment]
Dead site
