### ISSUE TITLE
BUG: unhandled error in plugin discover: "Nonetype object has no attribute 'group' : Plugin Alpharatio

### ISSUE THREAD

**Issue by chaos9099** [Flexget/Flexget#1690]
### Expected behaviour:
I've just started using Flexget and got a friend to set me up. He's running the same script and for him this seems to be working.  There might be some errors trying to get my  series to download but thats not the issue I'm trying to tackle at the moment. Whenever the series or Movie  task finds something to download and tries to do so it throws up the following Bug / errors. 

### Actual behaviour:
I've tried searching what this could be but all I could find where some layout issue's that appearently were fixed a while ago.  Find it so weird that the exact same script could work on one computer but not on mine.  I've tried downgrading he flexget version to the one my friend is running and even straight copying his alpharatio plugin and didn't seem to fix the issue.  Any ideas what it could be?

#### Config:
```
variables: secrets.yml

schedules:
  - tasks: '*'
    interval:
      minutes: 5
    
templates:
  global:
    no_entries_ok: yes
    regexp:
      reject:
        - (P2P|3D|HSBS|Half-SBS|remux|HDCAM|CROPPED|DTS|DD5|WEB-DL|DVDRip)
  tv:
    thetvdb_lookup: yes
    configure_series:
      settings:
        quality: 720p+
        timeframe: 0 minutes
        propers: 1 days
        target: hdtv+ 1080p
      from:
        trakt_list:
          account: "{? trakt.account ?}"
          list: "{? trakt.series ?}"
          type: shows
    deluge:
      path: "{? deluge.download ?}"
      movedone: "{? deluge.series ?}/{? series_name ?}/Season {? series_season ?}/"
      label: series
      queuetotop: yes

  movies:
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 1080p
    deluge:
      path: "{? deluge.download ?}"
      movedone: "{? deluge.movies ?}/"
      label: movies
      queuetotop: yes
    
  music:
    regexp:
      accept:
        - Hitzone
        - Trivium
        - Five Finger Death Punch
        - SLAM ADE
        - SLAM_ADE
    download: "{? folder.root ?}{? folder.music ?}"
    
    
tasks:
  follow show from ep:
    priority: 1
    seen: local
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: episodes
    accept_all: yes
    set_series_begin: yes

  get shows:
    priority: 2
    template:
      - global
      - tv
    discover:
      what:
        - next_series_episodes: yes
      from:
        - alpharatio:
            username: "{? ar.username ?}"
            password: "{? ar.password ?}"
            scene: yes
            category: tvhd
            order_by: time
            order_desc: yes
            leechstatus: normal
  
  movie fill:
    priority: 3
    trakt_list:
      account: "{? trakt.account ?}"
      list: "{? trakt.movies ?}"
      type: movies
      strip_dates: yes
    accept_all: yes
    list_add:
      - movie_list: trakt-movies
      
  movie download:
    priority: 4
    template:
      - global
      - movies
    discover:
      interval: 15 minutes
      release_estimations: loose
      what:
        - movie_list: 
            list_name: trakt-movies
            strip_year: yes
      from:
        - alpharatio: 
            username: "{? ar.username ?}"
            password: "{? ar.password ?}"
            scene: yes
            category: moviehd
            order_by: time
            order_desc: yes
            leechstatus: either
    list_match:
      from:
        - movie_list: trakt-movies
    list_remove:
      - trakt_list:
          account: "{? trakt.account ?}"
          list: "{? trakt.movies ?}"
          type: movies
  

```
  
#### Log:
```
2017-02-16 09:08 DEBUG    manager                       Figuring out config load paths
2017-02-16 09:08 DEBUG    manager                       Found config: C:\Users\Philip\flexget\config.yml
2017-02-16 09:08 DEBUG    manager                       Config file C:\Users\Philip\flexget\config.yml selected
2017-02-16 09:08 INFO     manager                       Test mode, creating a copy from database ...
2017-02-16 09:08 INFO     manager                       Test database created
2017-02-16 09:08 VERBOSE  task_queue                    There are 4 tasks to execute. Shutdown will commence when they have completed.
2017-02-16 09:08 VERBOSE  trakt_list    follow show from ep Retrieving `episodes` list `series`
2017-02-16 09:08 WARNING  trakt_list    follow show from ep No data returned from trakt for episodes list series.
2017-02-16 09:08 VERBOSE  trakt_list    follow show from ep Retrieving `episodes` list `series`
2017-02-16 09:08 WARNING  trakt_list    follow show from ep No data returned from trakt for episodes list series.
2017-02-16 09:08 VERBOSE  details       follow show from ep Task didn't produce any entries.
2017-02-16 09:08 VERBOSE  details       follow show from ep Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)
2017-02-16 09:08 VERBOSE  trakt_list    get shows       Retrieving `shows` list `series`
2017-02-16 09:08 WARNING  trakt_list    get shows       No data returned from trakt for shows list series.
2017-02-16 09:08 VERBOSE  trakt_list    get shows       Retrieving `shows` list `series`
2017-02-16 09:08 WARNING  trakt_list    get shows       No data returned from trakt for shows list series.
2017-02-16 09:08 WARNING  configure_series get shows       Input trakt_list did not return anything
2017-02-16 09:08 INFO     configure_series get shows       Did not get any series to generate series configuration
2017-02-16 09:08 WARNING  discover      get shows       Input next_series_episodes did not return anything
2017-02-16 09:08 VERBOSE  discover      get shows       Discovering 0 titles ...
2017-02-16 09:08 VERBOSE  details       get shows       Task didn't produce any entries.
2017-02-16 09:08 VERBOSE  details       get shows       Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)
2017-02-16 09:08 INFO     deluge        get shows       Connecting to daemon at localhost:58846..
2017-02-16 09:08 INFO     deluge        get shows       Connected to daemon at 127.0.0.1:58846..
2017-02-16 09:08 INFO     deluge        get shows       Connection lost to daemon at localhost:58846 reason: Connection was closed cleanly.
2017-02-16 09:08 VERBOSE  trakt_list    movie fill      Retrieving `movies` list `watchlist`
2017-02-16 09:08 VERBOSE  details       movie fill      Produced 1 entries.
2017-02-16 09:08 VERBOSE  task          movie fill      ACCEPTED: `Cross Wars` by accept_all plugin
2017-02-16 09:08 VERBOSE  details       movie fill      Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2017-02-16 09:08 VERBOSE  list_add      movie fill      adding accepted entries into movie_list - trakt-movies
2017-02-16 09:08 VERBOSE  discover      movie download  Discovering 1 titles ...
2017-02-16 09:08 VERBOSE  api_bluray    movie download  Searching from blu-ray.com `Cross Wars`
2017-02-16 09:08 VERBOSE  discover      movie download  Searching for `Cross Wars` with plugin `alpharatio` (1 of 1)
2017-02-16 09:08 VERBOSE  utils.requests movie download  Waiting 4.48 seconds until next request to alpharatio.cc
2017-02-16 09:08 CRITICAL task          movie download  BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 290, in on_task_input
    return self.execute_searches(config, entries, task)
  File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 155, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "c:\python27\lib\site-packages\flexget\plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\sites\alpharatio.py", line 210, in search
    e['content_size'] = parse_filesize(size.group(0))
AttributeError: 'NoneType' object has no attribute 'group'

```

### Additional information:

- Flexget Version: 2.9.23
- Python Version: 2.7.13
- Installation method: 
- OS and version: Pip Running on windows 7
- Link to crash log:

**Comment by cvium** [comment]
Cannot reproduce. I have made sure it won't crash anymore and added some more logging. Please update to 2.10.2 tomorrow and test it again. It should log something like this `No size found! Please create a Github issue. Size received: ...`.

**Comment by chaos9099** [comment]
thanks for working on this. Just got back from a trip and got the chance of testing. it returns: 
"Size Received: 6 days ago"

Strangely it gives me this a few lines lower:
ValueError: Invalid literal for long() with base 10: '6.56 GB'

**Comment by cvium** [comment]
Looks like the order of the columns of the site changed, but it worked for me. Weird.

**Comment by liiight** [comment]
@cvium maybe a specific torrent has an additional column or attributed fucking up the divs. I had something like this with another plugin, torrents that had a FL token fucked up the column order

**Comment by cvium** [comment]
@chaos9099 silly question, but do you stop the daemon when you upgrade Flexget?

**Comment by chaos9099** [comment]
Yes. I do. 

I got it to work sort of by going into the plugin and changing the column numbers so it gets the right one. Seems to be working, getting a little error now and then but nothing that major crashes the system.

If I remember correctly I added one with every column above 4. So 4 changed to 5, 5 to 6 etc.  So weird that its only on my computer.. 

Only error I'm getting every once in a while is:
Error searching with alpharatio: invalid literal for long() with base 10: '1.069
But that looks like it's something that has nothing to do with my changes

**Comment by rmontagud** [comment]
Looks like the regex is failing but the column is right one 

2017-03-25 12:59 ERROR    alpharatio    alpharatio      No size found! Please create a Github issue. Size received: 1 month ago
2017-03-25 12:59 ERROR    discover      alpharatio      Error searching with alpharatio: invalid literal for long() with base 10: '2.62 GB'

Last time i patched somehow the plugin, but i'm a bit clueless on how to do it right now

Flexget: 2.10.21
Python: 2.7.9
OS: Debian Jessie

**Comment by cvium** [comment]
`Size received: 1 month ago`... that's not the right column.
