### ISSUE TITLE
Plugin `flexget.plugins.sites.freshon` failed to import dependencies

### ISSUE THREAD

**Issue by volsk** [Flexget/Flexget#1696]
### Actual behaviour:
When running `flexget execute` I run into the following error message:
```
2017-02-17 16:06 DEBUG    plugin                        Trying to load plugins from: ['/Users/<me>/.flexget/plugins', '/usr/local/lib/python3.6/site-packages/flexget/plugins']
2017-02-17 16:06 DEBUG    plugin                        ('Plugin `%s` requires `%s` to load.', 'memusage', 'ext lib `guppy`')
2017-02-17 16:06 CRITICAL plugin                        Plugin `flexget.plugins.sites.freshon` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flexget/plugin.py", line 396, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python3.6/site-packages/flexget/plugins/sites/freshon.py", line 7, in <module>
    from urlparse import urlsplit, parse_qs
ModuleNotFoundError: No module named 'urlparse'
```

It is unclear to me what functionality breaks, because `flexget` seems to work.

### Additional information:

- Python Version: Python 2.7.13
- Flexget Version: 2.10.0
- Installation method: `pip3 install flexget`
- OS and version: macOS 10.12.3 (16D32)

**Comment by cvium** [comment]
Fixed by #1693. Available in next release.
