### ISSUE TITLE
BUG: Unhandled error in plugin torrent_size: string indices must be integers

### ISSUE THREAD

**Issue by DickVicious** [Flexget/Flexget#1697]
### Expected behaviour:
I started using the convert_magnet plugin, which I would expect to convert the magnet url into a torrent file and then proceed as normal.
### Actual behaviour:
When I add in the convert_magnet plugin, the task crashes apparently due to the torrent_size plugin.
### Steps to reproduce:
- Step 1: Add convert_magnet: yes to a task with transmission
- Step 2: Run the task
#### Config:
```
variables: yes
templates:    
  movies-global:
    # Fill in extra info
    imdb_lookup: yes
    trakt_lookup: yes
    set:
      path: "{? transmission.basepath ?}/Movies/{{imdb_name}} ({{imdb_year}})"
        
  transmission-download:
    free_space:
      path: '{? transmission.basepath ?}'
      space: 20000
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}                    # Block any subbed/dubbed/etc videos
        - \bspanish\b: {from: title}                          # Spanish releases kept cropping up
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} # Block series, only accept one at a time
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bR5\b: {from: title}                               # The following are poor quality types that somehow got through the quality
        - \bWEBSCR\b: {from: title}                           # features usually due to the title including a keyword like "720p" as well
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}                              # The following are groups with poor quality releases
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \[facepalm\]: {from: title}
        - \bASAP\b: {from: title}
    torrent_alive: 5
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mpg'
        - '*.mp4'
      reject:
        - 'password.txt'
        - '*.wmv'
    convert_magnet: yes
    #  timeout: 5 minutes
    #  force: yes
    limit_new: 5
    transmission:
      host: localhost
      port: 9091
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'
      path: '{? transmission.basepath ?}'
      addpaused: no
      main_file_only: yes
      main_file_ratio: 0.70
      magnetization_timeout: 300
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*[sS]ample*'
        - '*.txt'
        - '*.ac3'
        - '*[sS]creenshot*'
        - 'ETRG.mp4'
        - 'RARBG.com.mp4'        
        
  # This template uses the movie queue to download movies from various sources
  movies-queued:
    # Remove from list if accepted
    list_match:
      from:
        - movie_list: Trakt Movie Download Queue
    discover:
      release_estimations: loose
      what:
        - movie_list: Trakt Movie Download Queue
      from:
        - piratebay:
            category: "highres movies"
            sort_by: seeds
      interval: 1 hour
    #seen: local

tasks:
  Download-Movies-1080p-test:
    priority: 130
    template: 
      - movies-global
      - movies-queued
      - transmission-download
    quality: 1080p+ bluray+ h264+
```
  
#### Log:
```
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Successfully retrieved Cube (1997) 1080p BrRip x264 - YIFY from file:///home/ubuntu/flexget1/converted/Cube (1997) [1080p].torrent
2017-02-17 10:32 INFO     download      Download-Movies-1080p-test Downloading: American.Psycho.2000.1080p.BrRip.x264.YIFY
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Downloading url 'file:///home/ubuntu/flexget1/converted/American Psyco (2000) 1080p.torrent'
2017-02-17 10:32 DEBUG    utils.requests Download-Movies-1080p-test No adaptor, passing off to urllib
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test American.Psycho.2000.1080p.BrRip.x264.YIFY field file set to: /tmp/tmp1JiQpU/7743fcfdc53225ac4b9f356229f46ddf
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Mimetype guess for application/x-bittorrent is ['.torrent'] 
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test No filename - setting from url: American Psyco (2000) 1080p.torrent
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Finishing download_entry() with filename American Psyco (2000) 1080p.torrent
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Successfully retrieved American.Psycho.2000.1080p.BrRip.x264.YIFY from file:///home/ubuntu/flexget1/converted/American Psyco (2000) 1080p
.torrent
2017-02-17 10:32 INFO     download      Download-Movies-1080p-test Downloading: Kill Bill: Vol. 1 (2003) 1080p BrRip x264 - YIFY
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Downloading url 'file:///home/ubuntu/flexget1/converted/Kill Bill Vol 1 (2003) [1080p].torrent'
2017-02-17 10:32 DEBUG    utils.requests Download-Movies-1080p-test No adaptor, passing off to urllib
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Kill Bill: Vol. 1 (2003) 1080p BrRip x264 - YIFY field file set to: /tmp/tmpfINUc4/8a2ce4b7c825b5cc37f08c4ea2418be8
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Mimetype guess for application/x-bittorrent is ['.torrent'] 
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test No filename - setting from url: Kill Bill Vol 1 (2003) [1080p].torrent
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Finishing download_entry() with filename Kill Bill Vol 1 (2003) [1080p].torrent
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Successfully retrieved Kill Bill: Vol. 1 (2003) 1080p BrRip x264 - YIFY from file:///home/ubuntu/flexget1/converted/Kill Bill Vol 1 (2003
) [1080p].torrent
2017-02-17 10:32 INFO     download      Download-Movies-1080p-test Downloading: Eyes Wide Shut (1999) 1080p BrRip x264 - YIFY
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Downloading url 'file:///home/ubuntu/flexget1/converted/Eyes Wide Shut (1999) [1080p].torrent'
2017-02-17 10:32 DEBUG    utils.requests Download-Movies-1080p-test No adaptor, passing off to urllib
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Eyes Wide Shut (1999) 1080p BrRip x264 - YIFY field file set to: /tmp/tmpzzQVOk/47a3535d0964e25e63111cb12802d003
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Mimetype guess for application/x-bittorrent is ['.torrent'] 
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test No filename - setting from url: Eyes Wide Shut (1999) [1080p].torrent
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Finishing download_entry() with filename Eyes Wide Shut (1999) [1080p].torrent
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Successfully retrieved Eyes Wide Shut (1999) 1080p BrRip x264 - YIFY from file:///home/ubuntu/flexget1/converted/Eyes Wide Shut (1999) [1
080p].torrent
2017-02-17 10:32 INFO     download      Download-Movies-1080p-test Downloading: Ace Ventura: Pet Detective (1994) 1080p BrRip x264 - YIFY
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Downloading url 'file:///home/ubuntu/flexget1/converted/Ace Ventura: Pet Detective (1994) [1080p].torrent'
2017-02-17 10:32 DEBUG    utils.requests Download-Movies-1080p-test No adaptor, passing off to urllib
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Ace Ventura: Pet Detective (1994) 1080p BrRip x264 - YIFY field file set to: /tmp/tmpd5_n2A/1df1adc6b2931fa29dcc8f937edff4dd
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Mimetype guess for application/x-bittorrent is ['.torrent'] 
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test No filename - setting from url: Ace Ventura: Pet Detective (1994) [1080p].torrent
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Finishing download_entry() with filename Ace Ventura: Pet Detective (1994) [1080p].torrent
2017-02-17 10:32 DEBUG    download      Download-Movies-1080p-test Successfully retrieved Ace Ventura: Pet Detective (1994) 1080p BrRip x264 - YIFY from file:///home/ubuntu/flexget1/converted/Ace Ventura:
 Pet Detective (1994) [1080p].torrent
2017-02-17 10:32 VERBOSE  details       Download-Movies-1080p-test Summary - Accepted: 5 (Rejected: 1650 Undecided: 33 Failed: 0)
2017-02-17 10:32 DEBUG    modif_torrent Download-Movies-1080p-test Cube (1997) 1080p BrRip x264 - YIFY seems to be a torrent
2017-02-17 10:32 DEBUG    entry         Download-Movies-1080p-test trying to debug key `torrent` value threw exception: 'unicode' object has no attribute 'get'
2017-02-17 10:32 ERROR    modif_torrent Download-Movies-1080p-test 'unicode' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/plugins/modify/torrent.py", line 61, in on_task_modify
    entry['torrent_info_hash'] = torrent.info_hash
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 292, in info_hash
    info_data = encode_dictionary(self.content['info'])
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 170, in encode_dictionary
    items = list(data.items())
AttributeError: 'unicode' object has no attribute 'items'
2017-02-17 10:32 DEBUG    modif_torrent Download-Movies-1080p-test American.Psycho.2000.1080p.BrRip.x264.YIFY seems to be a torrent
2017-02-17 10:32 DEBUG    entry         Download-Movies-1080p-test trying to debug key `torrent` value threw exception: 'unicode' object has no attribute 'get'
2017-02-17 10:32 ERROR    modif_torrent Download-Movies-1080p-test 'unicode' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/plugins/modify/torrent.py", line 61, in on_task_modify
    entry['torrent_info_hash'] = torrent.info_hash
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 292, in info_hash
    info_data = encode_dictionary(self.content['info'])
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 170, in encode_dictionary
    items = list(data.items())
AttributeError: 'unicode' object has no attribute 'items'
2017-02-17 10:32 DEBUG    modif_torrent Download-Movies-1080p-test Kill Bill: Vol. 1 (2003) 1080p BrRip x264 - YIFY seems to be a torrent
2017-02-17 10:32 DEBUG    entry         Download-Movies-1080p-test trying to debug key `torrent` value threw exception: 'unicode' object has no attribute 'get'
2017-02-17 10:32 ERROR    modif_torrent Download-Movies-1080p-test 'unicode' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/plugins/modify/torrent.py", line 61, in on_task_modify
    entry['torrent_info_hash'] = torrent.info_hash
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 292, in info_hash
    info_data = encode_dictionary(self.content['info'])
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 170, in encode_dictionary
    items = list(data.items())
AttributeError: 'unicode' object has no attribute 'items'
2017-02-17 10:32 DEBUG    modif_torrent Download-Movies-1080p-test Eyes Wide Shut (1999) 1080p BrRip x264 - YIFY seems to be a torrent
2017-02-17 10:32 DEBUG    entry         Download-Movies-1080p-test trying to debug key `torrent` value threw exception: 'unicode' object has no attribute 'get'
2017-02-17 10:32 ERROR    modif_torrent Download-Movies-1080p-test 'unicode' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/plugins/modify/torrent.py", line 61, in on_task_modify
    entry['torrent_info_hash'] = torrent.info_hash
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 292, in info_hash
    info_data = encode_dictionary(self.content['info'])
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 170, in encode_dictionary
    items = list(data.items())
AttributeError: 'unicode' object has no attribute 'items'
2017-02-17 10:32 DEBUG    modif_torrent Download-Movies-1080p-test Ace Ventura: Pet Detective (1994) 1080p BrRip x264 - YIFY seems to be a torrent
2017-02-17 10:32 DEBUG    entry         Download-Movies-1080p-test trying to debug key `torrent` value threw exception: 'unicode' object has no attribute 'get'
2017-02-17 10:32 ERROR    modif_torrent Download-Movies-1080p-test 'unicode' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/plugins/modify/torrent.py", line 61, in on_task_modify
    entry['torrent_info_hash'] = torrent.info_hash
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 292, in info_hash
    info_data = encode_dictionary(self.content['info'])
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 170, in encode_dictionary
    items = list(data.items())
AttributeError: 'unicode' object has no attribute 'items'
2017-02-17 10:32 CRITICAL task          Download-Movies-1080p-test BUG: Unhandled error in plugin torrent_size: string indices must be integers
Traceback (most recent call last):
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/plugins/metainfo/torrent_size.py", line 21, in on_task_modify
    size = entry['torrent'].size / 1024 / 1024
  File "/home/ubuntu/flexget1/local/lib/python2.7/site-packages/flexget/utils/bittorrent.py", line 263, in size
    for item in self.content['info']['files']:
TypeError: string indices must be integers
```

### Additional information:

- Flexget Version: 2.10.0
- Python Version: Python 2.7.12
- Installation method: pip + virtualenv
- OS and version: Ubuntu 16.04.2
- Link to crash log:

**Comment by DickVicious** [comment]
Not sure what the cause was, but I am no longer having this problem. If its of any value I ended up moving to a new system and didn't encounter the error again.
