### ISSUE TITLE
BUG: Unhandled error in plugin series_premiere: Series flagged invalid

### ISSUE THREAD

**Issue by NewFolk** [Flexget/Flexget#1717]
### Actual behaviour:
```
BUG: Unhandled error in plugin series_premiere: Series flagged invalid
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/filter/series_premiere.py", line 63, in on_task_metainfo
    if guess_entry(entry, allow_seasonless=allow_seasonless, config=group_settings):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/metainfo/series.py", line 47, in guess_entry
    populate_entry_fields(entry, parsed, config)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/filter/series.py", line 941, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/parsers/parser_common.py", line 555, in pack_identifier
    return self.identifier
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/parsers/parser_common.py", line 546, in identifier
    return self.identifiers[0]
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/parsers/parser_common.py", line 531, in identifiers
    raise Exception('Series flagged invalid')
Exception: Series flagged invalid
```
### Steps to reproduce:
flexget execute --tasks HDClub

#### Config:
http://pastebin.com/X2VVWVey
  
#### Log:
http://pastebin.com/0mPtf6bn

### Additional information:

- Flexget Version: 2.10.10
- Python Version: 2.7.13
- GuessIt 2.0.4   
- Installation method: pip
- OS and version: Synology DSM 6.1
- Link to crash log:  http://pastebin.com/8PEab1UN

**Comment by cvium** [comment]
Duplicate of #1098. The best you can do is stop using guessit. The maintainer of that plugin is too busy to fix it apparently.

**Comment by NewFolk** [comment]
Hello, thank you for reply.
#1098 was closed as duplicate of #735, and it was closed with **Unable to reproduce** 
So I did not find info that this is known bug. Should I refer this Issue on guessit GitHub?

**Comment by cvium** [comment]
No, we'll just let this issue stand. Don't get your hopes up though.

**Comment by alneven** [comment]
I had this with the 7x1 from GoT :-(
No word since that from the dev of guessit?
