### ISSUE TITLE
BUG: Unhandled error in plugin series: '<' not supported between instances of 'Episode' and 'Episode'

### ISSUE THREAD

**Issue by wariw** [Flexget/Flexget#1725]
### Actual behaviour:

Bug started to occur about 2 weeks ago for some series, before everything was working fine.

```
2017-03-08 20:28 CRITICAL task          discover-anime-hs BUG: Unhandled error in plugin series: '<' not supported between instances of 'Episode' and 'Episode'
2017-03-08 20:28 CRITICAL manager       discover-anime-hs An unexpected crash has occurred. Writing crash report to /home/x/.config/flexget/crash_report.2017.03.08.202817293427.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.11
2017-03-08 20:28 DEBUG    manager       discover-anime-hs Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/filter/series.py", line 1251, in on_task_filter
    self.process_series(task, series_entries, series_config)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/filter/series.py", line 1333, in process_series
    if ep < ep.series.begin:
TypeError: '<' not supported between instances of 'Episode' and 'Episode'
2017-03-08 20:28 WARNING  task          discover-anime-hs Aborting task (plugin: series)

```

### Steps to reproduce:
- flexget execute --task discover-anime-hs --discover-now

#### Config:
```
variables: secrets.yml

templates:

  torrent-ratio:
    set:
      ratio: 1.500
      removeatratio: yes

  list-anime-hs:
    series:
      settings:
        anime:
          identified_by: sequence
          begin: 1
          quality: 720p+
      anime:
        - One Piece
        - "Mob Psycho 100"
        - "Kono Subarashii Sekai ni Shukufuku wo! 2"
        - Youjo Senki
        - Kobayashi-san Chi no Maid Dragon

  download:
    no_entries_ok: yes
    imdb_lookup: yes
    thetvdb_lookup: yes
    rtorrent:
      uri: /home/x/.rtorrent.sock
      path: /home/x/Pobrane/.pobierane

  notifications:
    notify:
      entries:
        title: >
          {% if series_name is defined %}{{ tvdb_series_name|d(series_name) }} - {{series_id}}
          {% elif imdb_name is defined %}{{ imdb_name }} ({{ imdb_year }})
          {% else %}{{ title }}
          {% endif %}
        message: >
          {% if series_name is defined %}{{ tvdb_series_name|d(series_name) }} - {{ tvdb_ep_id|d(series_id) }} - {{ tvdb_ep_name|d('') }}{% if quality is defined %} ({{ quality }}){% endif %}
          {% elif imdb_name is defined %}{{ imdb_name }} ({{ imdb_year }}){% if quality is defined %} ({{ quality }}){% endif %}
          {% else %}{{title}}{% if quality is defined %} ({{quality}}){% endif %}
          {% endif %}
          {% if tvdb_ep_overview is defined %}{{ tvdb_ep_overview }}{% endif %}
        via:
          - pushbullet:
              api_key: '{? pushbullet.key ?}'
              url: '{{ imdb_url }}'

schedules:
  - tasks: '*'
    interval:
      hours: 1
  - tasks: [discover-*]
    interval:
      minutes: 30

tasks:

  discover-anime-hs:
    discover:
      release_estimations: loose
      interval: 1 hours
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - btn: '{? btn.api ?}'
        - nyaa:
            category: anime eng
            filter: trusted only
    set:
      path: "/mnt/newer/Wideo/Anime/.non-seed/"
      label: anime
      custom1: anime
    template:
      - list-anime-hs
      - notifications
      - torrent-ratio
      - download
```
  
#### Log:

[http://pastebin.com/APAk7Cj7](http://pastebin.com/APAk7Cj7)

### Additional information:

- Flexget Version: 2.10.11
- Python Version:  3.6.0
- Installation method: pip
- OS and version: x86_64 Linux 4.9.7-1-ARCH
- Link to crash log: [http://pastebin.com/ES5YsNbp](http://pastebin.com/ES5YsNbp)

**Comment by cvium** [comment]
Dupe #1592
