### ISSUE TITLE
Flexget on Pypi seems to be missing Angular packages

### ISSUE THREAD

**Issue by cardonator** [Flexget/Flexget#1731]
### Expected behaviour:
UI works fine.

### Actual behaviour:
UI doesn't work with errors in Chrome devtools:
```
vendor.js:46651 Uncaught TypeError: angular.module(...).info is not a function
    at vendor.js:46651
    at vendor.js:46992
```
```
vendor.js:9883 Uncaught Error: [$injector:modulerr] Failed to instantiate module flexget due to:
Error: [$injector:modulerr] Failed to instantiate module ngCookies due to:
Error: [$injector:nomod] Module 'ngCookies' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.11/$injector/nomod?p0=ngCookies
    at http://10.3.20.6:5050/scripts/vendor.js:9883:12
    at http://10.3.20.6:5050/scripts/vendor.js:11948:17
    at ensure (http://10.3.20.6:5050/scripts/vendor.js:11872:38)
    at module (http://10.3.20.6:5050/scripts/vendor.js:11946:14)
    at http://10.3.20.6:5050/scripts/vendor.js:14484:22
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
    at http://10.3.20.6:5050/scripts/vendor.js:14485:40
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=ngCookies&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngCookies'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3DngCookies%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A9883%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11948%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11872%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11946%3A14)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14484%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14485%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)
    at http://10.3.20.6:5050/scripts/vendor.js:9883:12
    at http://10.3.20.6:5050/scripts/vendor.js:14507:15
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
    at http://10.3.20.6:5050/scripts/vendor.js:14485:40
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
    at createInjector (http://10.3.20.6:5050/scripts/vendor.js:14390:19)
    at doBootstrap (http://10.3.20.6:5050/scripts/vendor.js:11624:20)
    at Object.bootstrap (http://10.3.20.6:5050/scripts/vendor.js:11645:12)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=flexget&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20ngCookies%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngCookies'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3DngCookies%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A9883%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11948%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11872%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11946%3A14)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14484%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14485%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fmodulerr%3Fp0%3DngCookies%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'ngCookies'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.11%252F%2524injector%252Fnomod%253Fp0%253DngCookies%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A9883%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A11948%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A11872%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A11946%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A14484%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A10140%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A14468%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A14485%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A10140%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A14468%253A5)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A9883%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14507%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14485%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14390%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11624%3A20)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11645%3A12)
    at http://10.3.20.6:5050/scripts/vendor.js:9883:12
    at http://10.3.20.6:5050/scripts/vendor.js:11948:17
    at ensure (http://10.3.20.6:5050/scripts/vendor.js:11872:38)
    at module (http://10.3.20.6:5050/scripts/vendor.js:11946:14)
    at http://10.3.20.6:5050/scripts/vendor.js:14484:22
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
    at http://10.3.20.6:5050/scripts/vendor.js:14485:40
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=ngCookies&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngCookies'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3DngCookies%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A9883%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11948%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11872%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11946%3A14)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14484%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14485%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)
    at http://10.3.20.6:5050/scripts/vendor.js:9883:12
    at http://10.3.20.6:5050/scripts/vendor.js:14507:15
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
    at http://10.3.20.6:5050/scripts/vendor.js:14485:40
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
    at createInjector (http://10.3.20.6:5050/scripts/vendor.js:14390:19)
    at doBootstrap (http://10.3.20.6:5050/scripts/vendor.js:11624:20)
    at Object.bootstrap (http://10.3.20.6:5050/scripts/vendor.js:11645:12)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=flexget&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20ngCookies%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngCookies'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3DngCookies%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A9883%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11948%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11872%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11946%3A14)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14484%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14485%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fmodulerr%3Fp0%3DngCookies%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'ngCookies'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.11%252F%2524injector%252Fnomod%253Fp0%253DngCookies%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A9883%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A11948%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A11872%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A11946%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A14484%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A10140%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A14468%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A14485%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A10140%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F10.3.20.6%253A5050%252Fscripts%252Fvendor.js%253A14468%253A5)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A9883%3A12%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14507%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0A%20%20%20%20at%20http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14485%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A10140%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14468%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A14390%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11624%3A20)%0A%20%20%20%20at%20Object.bootstrap%20(http%3A%2F%2F10.3.20.6%3A5050%2Fscripts%2Fvendor.js%3A11645%3A12)
    at http://10.3.20.6:5050/scripts/vendor.js:9883:12
    at http://10.3.20.6:5050/scripts/vendor.js:14507:15
    at forEach (http://10.3.20.6:5050/scripts/vendor.js:10140:20)
    at loadModules (http://10.3.20.6:5050/scripts/vendor.js:14468:5)
    at createInjector (http://10.3.20.6:5050/scripts/vendor.js:14390:19)
    at doBootstrap (http://10.3.20.6:5050/scripts/vendor.js:11624:20)
    at Object.bootstrap (http://10.3.20.6:5050/scripts/vendor.js:11645:12)
    at HTMLDocument.<anonymous> (http://10.3.20.6:5050/scripts/app.js:55:21)
    at fire (http://10.3.20.6:5050/scripts/vendor.js:3187:31)
    at Object.fireWith [as resolveWith] (http://10.3.20.6:5050/scripts/vendor.js:3317:7)
```
### Steps to reproduce:
- Step 1: Start the service with config file and web_server: yes

#### Config:
```
web_server: yes
```
  
#### Log:
```
Nothing interesting in log file
```

### Additional information:

- Flexget Version: 2.10.12
- Python Version: 2.7.12
- Installation method: pip
- OS and version: Ubuntu 16.04.2
- Link to crash log:

**Comment by Tommatheussen** [comment]
Confirmed, initial testing shows both Angular 1.5.11 and 1.6.3 get installed, which is causing these issues.
Will need to investigate further

**Comment by furier** [comment]
I can confirm this behaviour after installing flexget version 2.10.12

**Comment by Tommatheussen** [comment]
Related to https://github.com/angular/material/issues/10484
