### ISSUE TITLE
BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by safi78** [Flexget/Flexget#1740]
### Expected behaviour:
download my stuff

### Actual behaviour:
not downloading my stuff

### Steps to reproduce:
- Step 1: flexget execute

#### Config:
```
tasks:
  download_dingen:
    npo_watchlist:
      email: ******@***.***
      password: *********
      remove_accepted: yes
      max_episode_age_days: 7
    accept_all: yes
    exec:
      fail_entries: yes
      auto_escape: yes
      on_output:
        for_accepted:
          - /usr/local/bin/download-npo -cc -o "/media/media/TV Shows/{{series_name_plain}}" -f "{serie_titel} - {datum} {aflevering_titel}" -t {{url}}
```  
#### Log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 326, in on_task_input
    entries += self._get_favorites_entries(task, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 318, in _get_favorites_entries
    series_info = self._get_series_info(task, config, series_name, url)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 180, in _get_series_info
    series_info['npo_url'] = tvseries.find('a', itemprop='url')['href']
AttributeError: 'NoneType' object has no attribute 'find'
```
### Additional information:

- Flexget Version:
2.10.17
- Python Version:
Python 2.7.9
- Installation method:
pip
- OS and version:
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

**Comment by edd3a** [comment]
I have the same error.
2017-03-19 10:44 CRITICAL task          tv-journaal     BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 318, in on_task_input
    entries += self._get_favorites_entries(task, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 310, in _get_favorites_entries
    series_info = self._get_series_info(task, config, series_name, url)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 176, in _get_series_info
    series_info['npo_url'] = tvseries.find('a', itemprop='url')['href']
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by liiight** [comment]
upgrade to latest release and report back

**Comment by safi78** [comment]
It works again, thanks!

**Comment by edd3a** [comment]
latest release of?

**Comment by safi78** [comment]
```
$ flexget -V
2.10.18
You are on the latest release.
```

```
$ download-npo -v
download-npo 2.7, 2017-03-19
http://code.arp242.net/download-npo
```
