### ISSUE TITLE
unhandled error in plugin transmission utf8

### ISSUE THREAD

**Issue by sean3589** [Flexget/Flexget#1750]
### Expected behaviour:
flexget execute runs 

### Actual behaviour:
After downloading the torrent files, the following error is thrown when trying to pass to transmission:
BUG: Unhandled error in plugin transmission: 'utf8' codec can't decode byte 0x84 in position 0: invalid start byte

### Steps to reproduce:
Not sure. Installed flexget via PIP and ensured fully updated
ensured that plugin is fully updated
Transmission GUI installed on Synology NAS using download centre install

#### Config: http://pastebin.com/e781m2KV
```
tasks:
  task-a:
    rss: https://revolutiontt.me/rss.php?feed=dl&bookmarks=on&passkey=*****
    accept_all: yes
    transmission:
      host: 172.16.
      port: 51413
      username: ****
      password: ****
    download: /volume1/Torrents/Torrents/

schedules:
  - tasks: 'task-a'
    interval:
      minutes: 15
```
#### Log:
```
2017-03-23 20:04 DEBUG    manager                       Figuring out config load paths
2017-03-23 20:04 DEBUG    manager                       Found config: /volume1/homes/admin/config.yml
2017-03-23 20:04 DEBUG    manager                       Config file /volume1/homes/admin/config.yml selected
2017-03-23 20:04 INFO     manager                       Test mode, creating a copy from database ...
2017-03-23 20:04 INFO     manager                       Test database created
2017-03-23 20:05 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2017-03-23 20:05 INFO     transmission  task-a          Trying to connect to transmission...
2017-03-23 20:05 CRITICAL task          task-a          BUG: Unhandled error in plugin transmission: 'utf8' codec can't decode byte 0xa6 in position 3: inva$
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/clients/transmission.py", line 141, in on_task_start
    self.client = self.create_rpc_client(config)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/clients/transmission.py", line 75, in create_rpc_client
    cli = transmissionrpc.Client(config['host'], config['port'], user, password)
  File "/usr/lib/python2.7/site-packages/transmissionrpc-0.11-py2.7.egg/transmissionrpc/client.py", line 169, in __init__
    self.get_session()
  File "/usr/lib/python2.7/site-packages/transmissionrpc-0.11-py2.7.egg/transmissionrpc/client.py", line 828, in get_session
    self._request('session-get', timeout=timeout)
  File "/usr/lib/python2.7/site-packages/transmissionrpc-0.11-py2.7.egg/transmissionrpc/client.py", line 247, in _request
    http_data = self._http_query(query, timeout)
  File "/usr/lib/python2.7/site-packages/transmissionrpc-0.11-py2.7.egg/transmissionrpc/client.py", line 205, in _http_query
    result = self.http_handler.request(self.url, query, headers, timeout)
  File "/usr/lib/python2.7/site-packages/transmissionrpc-0.11-py2.7.egg/transmissionrpc/httphandler.py", line 82, in request
    return response.read().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa6 in position 3: invalid start byte

```

### Additional information:

- Flexget Version: 2.10.19
- Python Version: 2.7.12 & 3.5.1
- Installation method: CLI using PIP
- OS and version: Synology DSM 6.1
- Link to crash log: http://pastebin.com/KngNng6E

**Comment by macmadness86** [comment]
I have the same issue running Arch on a NUC.

**Comment by viggy96** [comment]
I have posted a solution to this in #2055. I didn't know where else to post a solution, as I couldn't find a repo for the transmission plugin.

**Comment by cvium** [comment]
But this _is_ the repo... https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/clients/transmission.py

**Comment by viggy96** [comment]
Ah, lol, well, I guess I'll submit a pull request at some point.

**Comment by opicron** [comment]
Any change the fix can be pulled in?

**Comment by gazpachoking** [comment]
Thinking this may be solved by our new transmission-rpc library.
