### ISSUE TITLE
Telegram plugin error

### ISSUE THREAD

**Issue by Aokromes** [Flexget/Flexget#1768]
### Expected behaviour:
send telegram notification

### Actual behaviour:
it gives error
https://gist.github.com/Aokromes/5a9ac727bf17cbc2f89b1bc50df8ae08

### Steps to reproduce:
- Step 1: flexget execute

#### Config:
https://gist.github.com/Aokromes/3253f1b7a1e8c15b78a28d0932971a13
```code
# i tried username with and without ' myusername and Myusername and @Myusername
```
  
#### Log:
https://gist.github.com/Aokromes/5a9ac727bf17cbc2f89b1bc50df8ae08

### Additional information:
Notice, pushover notification works.
- Flexget Version:
flexget -V
2.10.26
You are on the latest release.

- Python Version:
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2

- Installation method:
virtualenv

- OS and version:
Debian 8 x64

- Link to crash log: https://gist.github.com/Aokromes/5a9ac727bf17cbc2f89b1bc50df8ae08

**Comment by sippeangelo** [comment]
I'm still getting this after your fix.
I'm using python-telegram-bot version 5.3.0. Which version is it supposed to work with?

#### Log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/notify.py", line 103, in send_notification
    send_notification(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/notification_framework.py", line 117, in send_notification
    notifier.notify(title, message, rendered_config)  # TODO: Update notifiers for new api
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 176, in notify
    chat_ids = self._real_init(Session(), config)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 210, in _real_init
    chat_ids = self._get_chat_ids_n_update_db(session)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 266, in _get_chat_ids_n_update_db
    chat_ids, has_new_chat_ids = self._get_chat_ids(session, usernames, fullnames, groups)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 304, in _get_chat_ids
    new_chat_ids = list(self._get_new_chat_ids(usernames, fullnames, groups))
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 361, in _get_new_chat_ids
    upd_usernames, upd_fullnames, upd_groups = self._get_bot_updates()
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 411, in _get_bot_updates
    chat = update.message.chat if update.message else update.edited_message.chat
AttributeError: 'NoneType' object has no attribute 'chat'

```

### Additional information:

- Flexget Version: 2.10.31
- Python Version: 3.6
- Installation method: pip
- OS and version: Arch Linux
