### ISSUE TITLE
series_premiere plugin crashing on season packs

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#1775]
This is obviously caused by the new support for season packs:
```
2017-04-05 22:50 DEBUG    parser_internal tv_premieres   Parsing series: `My.Love.from.Another.Star.S01.The.Beginning.HDTV.AAC2.0.x264-SAM` kwargs: {'identified_by': u'auto', 'name': None, 'allow_seasonless': True}
2017-04-05 22:50 DEBUG    parser_internal tv_premieres   Parsing result: <SeriesParser(data=My.Love.from.Another.Star.S01.The.Beginning.HDTV.AAC2.0.x264-SAM,name=My Love From Another Star,id=S1,season=1,season_pack=True,episode=None,quality=hdtv h264 aac,proper=0,status=OK)> (in 3.017 ms)
2017-04-05 22:50 CRITICAL task          tv_premieres   BUG: Unhandled error in plugin series_premiere: u'series_episode'
2017-04-05 22:50 CRITICAL manager       tv_premieres   An unexpected crash has occurred. Writing crash report to /tmp/.flexget/crash_report.2017.04.05.225036904002.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.27
2017-04-05 22:50 DEBUG    manager       tv_premieres   Traceback:
Traceback (most recent call last):
  File "/tmp/flexget/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/tmp/flexget/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/tmp/flexget/flexget/plugins/filter/series_premiere.py", line 64, in on_task_metainfo
    if entry['series_season'] == 1 and entry['series_episode'] in desired_eps:
  File "/tmp/flexget/flexget/utils/lazy_dict.py", line 71, in __getitem__
    item = self.store[key]
KeyError: u'series_episode'
```

### Additional information:

- Flexget Version: 2.10.27
- Python Version: 2.7.13
- Installation method: git
- OS and version: osx 10.11.6

**Comment by liiight** [comment]
Paste config please

**Comment by grr** [comment]
As shown in the above example, when encountering a season pack for season 1, the entry doesn't have a series_episode field. This is an obvious fix for an obvious bug:

    diff --git a/flexget/plugins/filter/series_premiere.py b/flexget/plugins/filter/series_premiere.py
    index 42b11c4cd..65a0cd064 100644
    --- a/flexget/plugins/filter/series_premiere.py
    +++ b/flexget/plugins/filter/series_premiere.py
    @@ -61,7 +61,7 @@ class FilterSeriesPremiere(FilterSeriesBase):
            guessed_series = {}
            for entry in task.entries:
                if guess_entry(entry, allow_seasonless=allow_seasonless, config=group_settings):
    -                if entry['series_season'] == 1 and entry['series_episode'] in desired_eps:
    +                if entry['series_season'] == 1 and entry.get('series_episode') in desired_eps:
                        normalized_name = normalize_series_name(entry['series_name'])
                        db_series = task.session.query(Series).filter(Series.name == normalized_name).first()
                        if db_series and db_series.in_tas

**Comment by cvium** [comment]
Then create a PR.
