### ISSUE TITLE
use of alternate_name in series group lists results in crashes on season_packs merge on dict vs. unicode typing

### ISSUE THREAD

**Issue by buffyg** [Flexget/Flexget#1781]
Wild guess: either there's a parser ordering problem (child elements from the group membership list need to be parsed first), or season_keys sorting is naive about possible states of the parse tree and resulting type handling needs (the merge sort needs to allow for child elements by using the parent key for the sort when it encounters a dict).

### Expected behaviour:

With alternate_name specified for a series group list, config parser either flags additional config elements as illegal or parses happily at runtime. 

### Actual behaviour:

Config elements pass check but parser crashes tasks with merge on key season_packs errors at runtime. Workaround available by using ability to specify optional name extensions with parentheses in the list rather than using alternate_names (i.e. "The Americans (2013)" for below config).

### Steps to reproduce:

Note: I've tried to extract a minimal config that reflects the changes that introduced the crashes and removed them once reversed. I have not tried to reproduce the issue with just what's here, but I can do so if what I've provided is insufficient.

- Set up group templates for series and enumerate members into groups with lists while adding additional config elements for an elements (as per https://flexget.com/Plugins/series/per_group_settings)
- Run check
- Load the config change

#### Config:
```  
templates:
[snip]
  freshon-serial-tv:
    series:
      settings:
        720p_h264_hifi:
          quality: 720p h264 dd5.1|dts
          season_packs: always
        720p_h264:
          quality: 720p h264
          season_packs: always

      720p_h264_hifi:
[snip]
        - The Americans
            alternate_name: The Americans 2013
[snip]
      720p_h264:
[snip]
```
  
#### Log:
```
2017-04-06 19:43 INFO     manager                       Reloading config from disk.
2017-04-06 19:43 INFO     manager                       Config successfully reloaded from disk.
2017-04-06 19:43 VERBOSE  rss           freshon         Not processing entries from last run.
2017-04-06 19:43 VERBOSE  backlog       freshon         Added 42 entries from backlog
2017-04-06 19:43 VERBOSE  details       freshon         Produced 42 entries.
2017-04-06 19:43 CRITICAL task          freshon         BUG: Unhandled error in plugin series: u"Merging key season_packs failed, conflicting datatypes 'unicode' vs. 'dict'."
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 483, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1454, in on_task_filter
    config = self.prepare_config(config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1338, in prepare_config
    config = self.apply_group_options(config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1302, in apply_group_options
    merge_dict_from_to(group_settings, series_settings)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/tools.py", line 173, in merge_dict_from_to
    k, type(v).__name__, type(d2[k]).__name__))
MergeException: u"Merging key season_packs failed, conflicting datatypes 'unicode' vs. 'dict'."
```

### Additional information:

- Flexget Version: 2.10.28
- Python Version: 2.7.9
- Installation method: pip
- OS and version: Debian jessie
- Link to crash log: see above

**Comment by liiight** [comment]
Similar cause as #1774
