### ISSUE TITLE
T411 plugin returns an error

### ISSUE THREAD

**Issue by Danelem** [Flexget/Flexget#1783]
### Expected behaviour:
The plugin to return the right entries

### Actual behaviour:
The plugin returns an error. Used two work a few days ago. I know the API may have changed.

### Steps to reproduce:
Execute with the attached config file (Note: you'll need t411 credentials)

#### Config:
```
templates:
  global:
    deluge:
      host: (hidden)
      port: (hidden)
      username: (hidden)
      password: (hidden)
  series-tv:
    t411:
      category: Série TV
    set:
      path: (hidden)
tasks:
  tv-emissions:
    t411:
      category: Emission TV
    regexp:
      accept:
        - show 1
        - show 2
        - show 3
    set:
      path: (hidden)
```
  
#### Log:
```
2017-04-08 20:43 DEBUG    manager                       Figuring out config load paths
2017-04-08 20:43 DEBUG    manager                       Found config: (hidden)/.flexget/config.yml
2017-04-08 20:43 DEBUG    manager                       Config file (hidden)/.flexget/config.yml selected
2017-04-08 20:43 DEBUG    manager                       sys.defaultencoding: ascii
2017-04-08 20:43 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2017-04-08 20:43 DEBUG    manager                       flexget detected io encoding: utf-8
2017-04-08 20:43 DEBUG    manager                       os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2017-04-08 20:43 DEBUG    manager                       Sending command to running FlexGet process: [u'-L', u'debug', u'execute', u'--tasks', u'tv-emissions']
2017-04-08 20:43 DEBUG    cron_env                      Encoding UTF-8 stored
2017-04-08 20:43 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'UTF-8'
2017-04-08 20:43 DEBUG    task          tv-emissions    executing tv-emissions
2017-04-08 20:43 DEBUG    template      tv-emissions    Merging template global into task tv-emissions
2017-04-08 20:43 DEBUG    t411_api      tv-emissions    None cached data. Synchronizing...
2017-04-08 20:43 DEBUG    t411_api      tv-emissions    T411Proxy start database synchronization with T411
2017-04-08 20:43 DEBUG    t411_api      tv-emissions    None API token. Authenticating with "(hidden)" account...
2017-04-08 20:43 DEBUG    utils.requests tv-emissions    Fetching URL https://api.t411.ai/auth with args () and kwargs {'json': None, 'data': {u'username': u'(hidden)', u'password': u'(hidden)'}, u'timeout': 30}
2017-04-08 20:43 DEBUG    plugin        tv-emissions    decorator caught ValueError. handled traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/sites/t411.py", line 75, in on_task_input
    return proxy.search(query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 662, in search
    client_query = self.friendly_query_to_client_query(query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 480, in wrapper
    self.synchronize_database()
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 541, in synchronize_database
    category_tree = self.rest_client.retrieve_category_tree()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 168, in wrapper
    self.auth()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 211, in auth
    json_response = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-04-08 20:43 CRITICAL plugin        tv-emissions    Expecting value: line 1 column 1 (char 0)
2017-04-08 20:43 WARNING  task          tv-emissions    Aborting task (plugin: t411)

```

### Additional information:

- Flexget Version: 2.10.29
- Python Version: 2.7

**Comment by Icesenator** [comment]
Hi, same error here.

**Comment by poulpito** [comment]
Have the same error, i reccently moved the api from http to https to follow t411.ai change but it seems something else have change.
i'll try to have a look

**Comment by Danelem** [comment]
It looks like the API is not available for now: https://forum.t411.ai/discussion/45826/bugs-informations-demandes#Item_40

**Comment by poulpito** [comment]
waiting for t411 api to work again, you could use the old plugin as a discover source. 
in my case, i've recreate a part of my config  in a new config file 

for example

```
templates:
  tv:
    series:
      - The Expanse:
          upgrade: no
          quality: 1080p h264
          begin: S01E10
  t411-series-discover:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - torrent411:
            username: xxxxxxxxx
            password: yyyyyyyyyy
            category: Serie-TV
            sub_category:
              - VOSTFR
      interval: 1 hour
    max_reruns: 3
```

documentation is available with cli 
 > flexget doc torrent411

**Comment by liiight** [comment]
A ton of people  use this site huh? If someone could PM me credentials via gitter I could take a look at what can be done in a few days

**Comment by Danelem** [comment]
@poulpito Thanks for the trick!

@liiight They just said that they are working on their API and that it's not working now. Not sure there is anything we can do for now.

**Comment by liiight** [comment]
Well at the very least the plugin shouldn't crash like this, I'll look into that easily though

**Comment by Danelem** [comment]
It looks like the API is available again, and everything works fine. 

I'm closing the issue.
