### ISSUE TITLE
TypeError: the JSON object must be str, not 'NoneType'

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [Flexget/Flexget#1788]
### Expected behaviour:
Config file pass check validation
### Actual behaviour:
Config file does not pass check validation.
### Steps to reproduce:
Execute with attached config file

#### Config:
```
tasks:
  test:
    rss: http://mysite.com/myfeed.rss
    all_series: yes
```
  
#### Log:
```
2017-04-11 16:29 VERBOSE  check                         Pre-checked 4 configuration lines
Traceback (most recent call last):
  File "c:\users\will\appdata\local\programs\python\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\will\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Will\AppData\Local\Programs\Python\Python35\Scripts\flexget.exe\__main__.py", line 9, in <module>
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\__init__.py", line 42, in main
    manager.start()
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\manager.py", line 326, in start
    self.initialize()
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\manager.py", line 217, in initialize
    fire_event('manager.startup', self)
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\utils\simple_persistence.py", line 183, in load_taskless
    SimplePersistence.load()
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\utils\simple_persistence.py", line 145, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\sqlalchemy\orm\attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\utils\database.py", line 139, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "c:\users\will\appdata\local\programs\python\python35\lib\site-packages\flexget\utils\json.py", line 112, in loads
    return json.loads(*args, **kwargs)
  File "c:\users\will\appdata\local\programs\python\python35\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
```

### Additional information:

- Flexget Version: 2.10.30
- Python Version: 3.5.3
- Installation method: pip
- OS and version: Windows 10 Pro 64bits v1703 (build 15063.13)

On a clean install, basic test config file does not pass validation.

**Comment by liiight** [comment]
Did you copy db from a python 2 to a python 3 execution?

**Comment by UjCbFwtBayFM** [comment]
It's a clean install : I removed all files (Flexget scripts & config files then uninstalled older Python versions) before installing Python 3.5 and reinstalling Flexget from scratch.

**Comment by UjCbFwtBayFM** [comment]
I backed up the complete folder (%UserProfile%\.flexget) before deleting all contents.

**Comment by liiight** [comment]
so, did you move you db from python 2 to python or didnt you?
