### ISSUE TITLE
Telegram plugin error

### ISSUE THREAD

**Issue by sippeangelo** [Flexget/Flexget#1795]
### Expected behaviour:
Same as #1768

### Actual behaviour:
Telegram plugin exception, see log.
Same as #1768

### Steps to reproduce:
python-telegram-bot version 5.3.0
Same as #1768

#### Config:
```
notify:
  entries:
    message: Message goes here
    via:
      - telegram:
        bot_token: (token)
        parse_mode: markdown
        recipients:
          - username: (username)
```
  
#### Log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/notify.py", line 103, in send_notification
    send_notification(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/notification_framework.py", line 117, in send_notification
    notifier.notify(title, message, rendered_config)  # TODO: Update notifiers for new api
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 176, in notify
    chat_ids = self._real_init(Session(), config)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 210, in _real_init
    chat_ids = self._get_chat_ids_n_update_db(session)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 266, in _get_chat_ids_n_update_db
    chat_ids, has_new_chat_ids = self._get_chat_ids(session, usernames, fullnames, groups)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 304, in _get_chat_ids
    new_chat_ids = list(self._get_new_chat_ids(usernames, fullnames, groups))
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 361, in _get_new_chat_ids
    upd_usernames, upd_fullnames, upd_groups = self._get_bot_updates()
  File "/usr/lib/python3.6/site-packages/flexget/plugins/notifiers/telegram.py", line 411, in _get_bot_updates
    chat = update.message.chat if update.message else update.edited_message.chat
AttributeError: 'NoneType' object has no attribute 'chat'

```

### Additional information:

- Flexget Version: 2.10.31
- Python Version: 3.6
- Installation method: pip
- OS and version: Arch Linux
- Link to crash log:

**Comment by cvium** [comment]
If it's the exact same issue, then why open a new one? Unnecessary clutter.

**Comment by liiight** [comment]
it's not the same issue, similar though.
@sippeangelo pm me on [gitter](https://gitter.im/Flexget/Flexget) please, i want to debug using your credentials
