### ISSUE TITLE
t411 plugin not working (domain and cloudflare error)

### ISSUE THREAD

**Issue by scoony** [Flexget/Flexget#1814]
### Expected behaviour:
should work
### Actual behaviour:
not working
### Steps to reproduce:
- Step 1: simply execute

#### Config:
using the add-auth feature for the plugin
  
#### Log:

dl-series-fr
Error searching with t411: RequestException: hostname 'api.t411.ai' doesn't match either of 'ssl439599.cloudflaressl.com', '*.t411.al', 't411.al'
2017-05-07 08:03
ERROR
requests.packages.urllib3.connection

### Additional information:

- Flexget Version: 2.10.40
- Python Version: 2.7
- Installation method: pip install flexget
- OS and version: Ubuntu 16.04.2

I've tried to change the api file to the new domain "t411.al" and even compiled the .pyc using "python2.7 -m compileall file" ... no improvements

**Comment by scoony** [comment]
updated to flexget 2.10.41 ... same issue

**Comment by scoony** [comment]
log using --debug:

2017-05-07 08:50 DEBUG    utils.requests dl-series-fr    Fetching URL https://api.t411.ai/auth with args () and kwargs {'json': None, 'data': {u'username': u'scoonydeus', u'password': u'Marcello080873'}, u'timeout': 30}
2017-05-07 08:50 DEBUG    plugin        dl-series-fr    decorator caught RequestException. handled traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/sites/t411.py", line 99, in search
    search_result = proxy.search(query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 663, in search
    json_results = self.rest_client.search(client_query)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 168, in wrapper
    self.auth()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_t411.py", line 210, in auth
    response = self.web_session.post(auth_url, self.credentials)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/requests.py", line 240, in request
    result = super(Session, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: hostname 'api.t411.ai' doesn't match either of 'ssl439599.cloudflaressl.com', '*.t411.al', 't411.al'
2017-05-07 08:50 ERROR    discover      dl-series-fr    Error searching with t411: RequestException: hostname 'api.t411.ai' doesn't match either of 'ssl439599.cloudflaressl.com', '*.t411.al', 't411.al'

**Comment by cvium** [comment]
Are you using the daemon? If so, stop it and start it again.

**Comment by scoony** [comment]
using the webui started in rc.local

I've also tried using the command... same result

**Comment by scoony** [comment]
ok i've stopped the daemon... working perfectly now.

Thanks for the advice :)
