### ISSUE TITLE
Downloading torrents from nyaa.si (one of the nyaa replacements) raises the exception 'SyntaxError: trailing junk'

### ISSUE THREAD

**Issue by perHub** [Flexget/Flexget#1821]
### Expected behaviour:

Flexget should download torrents from the nyaa.si rss properly.
### Actual behaviour:
While trying to download a torrent from the nyaa.si RSS, the exception 'SyntaxError: trailing junk' is raised at bittorrent.py (note that if python 3.5.3 is used it's still able to download the torrent but raising the exception, but if Python 2.7.x is used then it can't download the torrent at all)

### Steps to reproduce:
It happens trying to download anything from the feed of nyaa.si, I'll paste an example config file.

#### Config:
```
tasks:                                                    
  Nyaa v2:
    rss: https://nyaa.si/?page=rss
    template:
      - test
    download: C:\torrents\
templates:
  test:
    series:
      - Little Witch Academia:
          season_packs: yes
```
  
#### Log:
```
2017-05-14 19:54 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2017-05-14 19:54 VERBOSE  details       Nyaa v2         Produced 75 entries.
2017-05-14 19:54 VERBOSE  task          Nyaa v2         REJECTED: `[Ohys-Raws] Little Witch Academia (2017) - 19 (BS11 1280x720 x264 AAC).mp4` by series plugin because season pack support is turned off
2017-05-14 19:54 VERBOSE  details       Nyaa v2         Summary - Accepted: 0 (Rejected: 1 Undecided: 74 Failed: 0)
2017-05-14 19:55 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2017-05-14 19:55 VERBOSE  details       Nyaa v2         Produced 75 entries.
2017-05-14 19:55 VERBOSE  task          Nyaa v2         ACCEPTED: `[Ohys-Raws] Little Witch Academia (2017) - 19 (BS11 1280x720 x264 AAC).mp4` by series plugin because choosing best available quality
2017-05-14 19:55 INFO     download      Nyaa v2         Downloading: [Ohys-Raws] Little Witch Academia (2017) - 19 (BS11 1280x720 x264 AAC).mp4
2017-05-14 19:55 VERBOSE  details       Nyaa v2         Summary - Accepted: 1 (Rejected: 0 Undecided: 74 Failed: 0)
2017-05-14 19:55 ERROR    modif_torrent Nyaa v2         'SyntaxError' object has no attribute 'message'
Traceback (most recent call last):
  File "c:\users\vm\appdata\local\programs\python\python35\lib\site-packages\flexget\plugins\modify\torrent.py", line 54, in on_task_modify
    torrent = Torrent(data)
  File "c:\users\vm\appdata\local\programs\python\python35\lib\site-packages\flexget\utils\bittorrent.py", line 211, in __init__
    self.content = bdecode(content)
  File "c:\users\vm\appdata\local\programs\python\python35\lib\site-packages\flexget\utils\bittorrent.py", line 141, in bdecode
    raise SyntaxError("trailing junk")
  File "<string>", line None
SyntaxError: trailing junk

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vm\appdata\local\programs\python\python35\lib\site-packages\flexget\plugins\modify\torrent.py", line 56, in on_task_modify
    entry.fail('%s - broken or invalid torrent file received' % e.message)
AttributeError: 'SyntaxError' object has no attribute 'message'
2017-05-14 19:55 INFO     download      Nyaa v2         File `C:\torrents\torrent` already exists and is not identical, download failed.
2017-05-14 19:55 ERROR    entry         Nyaa v2         Failed [Ohys-Raws] Little Witch Academia (2017) - 19 (BS11 1280x720 x264 AAC).mp4 (File `C:\torrents\torrent` already exists and is not identical.)
2017-05-14 19:55 INFO     task          Nyaa v2         Plugin retry_failed has requested task to be ran again after execution has completed.
2017-05-14 19:55 VERBOSE  task          Nyaa v2         FAILED: `[Ohys-Raws] Little Witch Academia (2017) - 19 (BS11 1280x720 x264 AAC).mp4` by download plugin because file `C:\torrents\torrent` already exists and is not identical.
2017-05-14 19:55 INFO     task          Nyaa v2         Rerunning the task in case better resolution can be achieved.
2017-05-14 19:55 VERBOSE  input_cache   Nyaa v2         Restored 75 entries from cache
2017-05-14 19:55 VERBOSE  details       Nyaa v2         Produced 75 entries.
2017-05-14 19:55 VERBOSE  task          Nyaa v2         REJECTED: `[Ohys-Raws] Little Witch Academia (2017) - 19 (BS11 1280x720 x264 AAC).mp4` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: File `C:\torrents\torrent` already exists and is not identical.)
2017-05-14 19:55 VERBOSE  details       Nyaa v2         Summary - Accepted: 0 (Rejected: 1 Undecided: 74 Failed: 0)
```

### Additional information:

- FlexGet version: 2.10.44
- Python version: 3.5.3 (also tried with 2.7.12)
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Windows 10 (also tried with on Windows 7)

**Comment by liiight** [comment]
the torrent is malformed, the exception need to be handled though
