### ISSUE TITLE
lazy_lookup  crash

### ISSUE THREAD

**Issue by pluskal** [Flexget/Flexget#1839]
### Expected behaviour:
Not to crash...

### Actual behaviour:
Crash

### Steps to reproduce:
Run full config at https://github.com/pluskal/flexget/blob/master/config.yml

#### Config:
```
  disable-seen-retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed

  series-metainfo:
    trakt_lookup: yes
    imdb_lookup: yes
    metainfo_series: yes
    thetvdb_lookup: yes

  fill-series-list:
    priority: 3
    template:
      - disable-seen-retry
      - series-metainfo
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: shows
    accept_all: yes
    set:
      title: "{{ tvdb_series_name|escape|replace('&#39;', '') }}"
    list_add:
      - entry_list: trakt-series
```
  
#### Log:
```
2017-05-24 19:52 ERROR    lazy_lookup   fill-series-list Unhandled error in lazy lookup plugin
2017-05-24 19:52 CRITICAL manager       fill-series-list An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2017.05.24.195223061436.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.52
2017-05-24 19:52 DEBUG    manager       fill-series-list Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flexget/utils/lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/metainfo/trakt_lookup.py", line 212, in lazy_series_actor_lookup
    entry.update_using_map(self.series_actor_map, series)
  File "/usr/local/lib/python2.7/site-packages/flexget/utils/sqlalchemy_utils.py", line 142, in __exit__
    self.commit()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 467, in do_executemany
    cursor.executemany(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: trakt_actors.id [SQL: u'INSERT INTO trakt_actors (id, name, slug, tmdb, imdb, biography, birthday, death, homepage) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ((200576, u'George Blagden', u'george-blagden', 1256160, u'nm4491241', None, None, None, u''), (560638, u'Stuart Bowman', u'stuart-bowman', 1532375, None, None, None, None, None), (642027, u'Maddison Jaizani', u'maddison-jaizani', 1630124, None, None, None, None, None), (7172, u'Joe Sheridan', u'joe-sheridan', 12983, u'nm0792190', None, None, None, None), (15763, u'Pip Torrens', u'pip-torrens', 36666, u'nm0868476', u'From Wikipedia, the free encyclopedia.\xa0\n\nPip Torrens\xa0(born June 2, 1960) is an English actor.\xa0He studied English Literature at Trinity Co ... (692 characters truncated) ... cework for Valiant.\n\n\xa0Description above from the Wikipedia article Pip Torrens, licensed under CC-BY-SA, full list of contributors on Wikipedia.', None, None, None), (45183, u'Evan Williams', u'evan-williams', 59600, u'nm0930570', None, None, None, u''), (64148, u'Elisa Lasowski', u'elisa-lasowski', 1027457, u'nm2489799', None, None, None, None), (180610, u'Steve Cumyn', u'steve-cumyn', 188634, u'nm0192056', None, None, None, None)  ... displaying 10 of 19 total bound parameter sets ...  (552114, u'Gilly Gilchrist', u'gilly-gilchrist', 1475236, None, None, None, None, None), (568571, u'No\xe9mie Schmidt', u'noemie-schmidt', 1573867, None, None, '1990-11-18', None, u''))]
```

### Additional information:

- FlexGet version: 2.10.52
- Python version: Python 2.7.12
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Arch
- Link to crash log: https://pastebin.com/sNdsCgEB

**Comment by liiight** [comment]
Does this consistently fail for you?

**Comment by pluskal** [comment]
Yes, every time that the task runs.

**Comment by cvium** [comment]
Can you find out which particular series causes this? Otherwise we can't really fix it.

**Comment by tubedogg** [comment]
Strongly guessing [Versailles](http://www.imdb.com/title/tt3830558/fullcredits?ref_=tt_ov_st_sm) based on the combination of actors in the log.

**Comment by pluskal** [comment]
Confirmed... It is a [Versailes](https://trakt.tv/shows/versailles-2015)

**Comment by cvium** [comment]
But is Versailles itself enough to trigger this?

**Comment by pluskal** [comment]
Can you give me a hint how to do that? I`m very sorry, but I do not have time to find on my own in next two weeks.

**Comment by liiight** [comment]
`flexget database reset-plugin api_trakt`

**Comment by pluskal** [comment]
Ok, tested and it crashes still with only Versailles in the list.

**Comment by cvium** [comment]
Works for me, so I'm guessing it's not just Versailles causing this.

**Comment by liiight** [comment]
What does it matter @cvium? There's obviously an issue here

**Comment by pluskal** [comment]
Well... the error is `IntegrityError` so something must have added one of actors before.  Maybe race condition, missing check fox item existence,or something.

I guess that the  `IntegrityError`  is collision in ID or other column if there is some index in the trakt_actors table.

**Comment by cvium** [comment]
You can't fix an error you can't reproduce. I'm not saying there isn't a problem, I'm just saying it works for me.

**Comment by crawln45** [comment]
check actors because there are times when a single actor actually has multiple id's so there might be an issue there not sure.
