### ISSUE TITLE
Error message: Could not start manager on discover plugin [movie task] 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#1851]
### Expected behaviour:

Task to execute and run discover plugin for movies 

### Actual behaviour:
It exits with message **Could not start manager:** and does not start the task 
### Steps to reproduce:
- Step 1: execute task for movies 

#### Config:
https://pastebin.com/Hte5jZtA
  
#### Log:
```
pi@raspberrypi:~ $ flexget --debug execute --tasks movies --discover-now --now
2017-05-31 01:01 DEBUG    manager                       Figuring out config load paths
2017-05-31 01:01 DEBUG    manager                       Found config: /home/pi/.flexget/config.yml
2017-05-31 01:01 DEBUG    manager                       Config file /home/pi/.flexget/config.yml selected
2017-05-31 01:01 DEBUG    manager                       sys.defaultencoding: ascii
2017-05-31 01:01 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2017-05-31 01:01 DEBUG    manager                       flexget detected io encoding: utf-8
2017-05-31 01:01 DEBUG    manager                       os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2017-05-31 01:01 DEBUG    manager                       Sending command to running FlexGet process: [u'--debug', u'execute', u'--tasks', u'movies', u'--discover-now', u'--now']
2017-05-31 01:01 DEBUG    cron_env                      Encoding UTF-8 stored
2017-05-31 01:01 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'UTF-8'
2017-05-31 01:01 VERBOSE  manager                       There is a task already running, execution queued.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 310, in start
    client.handle_cli(self.args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 467, in sync_request
    raise socket.timeout
timeout
```

### Additional information:

- Flexget Version: 2.10.56
- Python Version: Python 2.7.9
- Installation method: PIP
- OS and version: Raspbian Jessy 
- Link to crash log:

**Comment by liiight** [comment]
Is this consistent for you?

**Comment by chewy74** [comment]
No, it seems to be sporadic. It started working again and 2 hours later I got the error again.

**Comment by chewy74** [comment]
OK, so it's doing the same thing for all tasks, even one's without the discover plugin

**Comment by liiight** [comment]
yeah, this has nothing to do with any plugin, this is the process that enables the daemon.
did you try restarting the daemon?

**Comment by chewy74** [comment]
Yes, I tried restarting it and even rebooted the Pi completely and same issue. 

Here's the debug for the tv task 

```
pi@raspberrypi:~ $ flexget --debug execute --tasks tv_shows
2017-06-01 15:20 DEBUG    manager                       Figuring out config load paths
2017-06-01 15:20 DEBUG    manager                       Found config: /home/pi/.flexget/config.yml
2017-06-01 15:20 DEBUG    manager                       Config file /home/pi/.flexget/config.yml selected
2017-06-01 15:20 DEBUG    manager                       sys.defaultencoding: ascii
2017-06-01 15:20 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2017-06-01 15:20 DEBUG    manager                       flexget detected io encoding: utf-8
2017-06-01 15:20 DEBUG    manager                       os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2017-06-01 15:20 DEBUG    manager                       Sending command to running FlexGet process: [u'--debug', u'execute', u'--tasks', u'tv_shows']
2017-06-01 15:20 DEBUG    cron_env                      Encoding UTF-8 stored
2017-06-01 15:20 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'UTF-8'
2017-06-01 15:20 VERBOSE  manager                       There is a task already running, execution queued.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 310, in start
    client.handle_cli(self.args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 467, in sync_request
    raise socket.timeout
timeout
```

**Comment by mdentremont** [comment]
I'm seeing this 100% of the time on my end - same debug log as @chewy74

**Comment by tubedogg** [comment]
Hurray for dependency breakage. @liiight

**Comment by liiight** [comment]
Motherf...

**Comment by liiight** [comment]
Closed with https://github.com/Flexget/Flexget/pull/1867/commits/50e31a8a6b0d9e26e311c4f4f7ac9aae4d18d00f
