### ISSUE TITLE
Overflow error in retry_failed plugin

### ISSUE THREAD

**Issue by Mirgolth** [Flexget/Flexget#1852]
Hi, 

I had a pending entrie stuck with an error : 
```
2017-05-31 12:23 INFO     entry         music-ELITE     Tried to reject immortal The.Cranberries.No.Need.To.Argue.1994.WebRip.MP3.320Kbps-Moh (Has already failed 1751 times in the past. (failure reason: File /tmp/tmpWwDlFc/f1faa951aaa601015670bb5052d948e0 is 0 bytes in size))
2017-05-31 12:23 INFO     entry         music-ELITE     Tried to reject immortal The.Cranberries.No.Need.To.Argue.1994.WebRip.MP3.320Kbps-Moh (Entry with title `The.Cranberries.No.Need.To.Argue.1994.WebRip.MP3.320Kbps-Moh` is already marked seen in the task music-ELITE at 2017-05-11 17:52)
2017-05-31 12:23 INFO     download      music-ELITE     Downloading: The.Cranberries.No.Need.To.Argue.1994.WebRip.MP3.320Kbps-Moh
2017-05-31 12:23 ERROR    entry         music-ELITE     Failed The.Cranberries.No.Need.To.Argue.1994.WebRip.MP3.320Kbps-Moh (File /tmp/tmpjq4ylO/f1faa951aaa601015670bb5052d948e0 is 0 bytes in size)
2017-05-31 12:23 CRITICAL task          music-ELITE     BUG: Unhandled error in plugin transmission: (34, 'Numerical result out of range')
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/clients/transmission.py", line 283, in on_task_download
    download.instance.get_temp_files(task, handle_magnets=True, fail_html=True)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/output/download.py", line 179, in get_temp_files
    self.get_temp_file(task, entry, require_path, handle_magnets, fail_html, tmp_path)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/output/download.py", line 132, in get_temp_file
    error = self.process_entry(task, entry, url, tmp_path)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/output/download.py", line 199, in process_entry
    self.download_entry(task, entry, url, tmp_path)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/output/download.py", line 291, in download_entry
    entry.fail('File %s is 0 bytes in size' % datafile)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/entry.py", line 161, in fail
    self.run_hooks('fail', reason=reason, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/entry.py", line 80, in run_hooks
    func(self, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/filter/retry_failed.py", line 163, in add_failed
    retry_time = self.retry_time(item.count, config)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/filter/retry_failed.py", line 137, in retry_time
    retry_secs = base_retry_secs * (config['retry_time_multiplier'] ** fail_count)
OverflowError: (34, 'Numerical result out of range'
```
It got solved by removing the pending entrie from the list.

Here are the part of the conf involved, pretty straight forward: 

```
templates:
  torrents:
    transmission:
      host: '{? transmission.host ?}'
      port: 9091 
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'

[...]

  music-ELITE:
    rss: <some valid url>
    priority: 20
    pending_approval: yes
    transmission:
      path: /volume1/Music/
    template:
      - pushbullet
      - torrents
      - ratio
```

**Comment by liiight** [comment]
The issue template is there for a reason, please do not ignore it.
Add the missing parts from it please

**Comment by Mirgolth** [comment]
Fair enough ;)

### Expected behaviour:



### Actual behaviour:
Err

### Steps to reproduce:
Was a first time issue. I don't know how to get back in that state after I worked around it.

#### Config:
I don't really feel it's a conf issue as my conf is  basic pending_approval

```
templates:
  torrents:
    transmission:
      host: '{? transmission.host ?}'
      port: 9091 
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'

[...]

  music-ELITE:
    rss: <some valid url>
    priority: 20
    pending_approval: yes
    transmission:
      path: /volume1/Music/
    template:
      - pushbullet
      - torrents
      - ratio
```
  
#### Log:
```
paste log output
use paste service like http://dpaste.de or http://pastebin.com if log is too long
```

### Additional information:

- FlexGet version: I discovered it on Flexget 2.10.54 but the message state it failed 1751 times. As my scheduler runs once every 30 minutes, it probably started around 2.10.40
- Python version: Python 2.7.12
- Installation method: pip 9.0.1 from /usr/local/flexget/env/lib/python2.7/site-packages (python 2.7)
- Using daemon (yes/no): yes
- OS and version: Linux Strawberry 3.2.40 #15101 SMP Mon May 22 10:02:20 CST 2017 armv7l GNU/Linux synology_armadaxp_ds214
- Link to crash log: See 1st post

**Comment by liiight** [comment]
you could also workaround this by reseting `failed` plugin.
retrying an entry for 1751 times is ridiculous, we probably just need to cap that.
