### ISSUE TITLE
Newpct - Form plugin error

### ISSUE THREAD

**Issue by javichu666** [Flexget/Flexget#1871]
### Expected behaviour:
Login to rss feed (http://feeds2.feedburner.com/newpctorrent) in order to download torrents from url http://www.newpct.com/entrar/

#### Config:
    rss: http://feeds2.feedburner.com/newpctorrent
    form:
      url: http://www.newpct.com/entrar/
      userfield: userName
      passfield: userPass
      username: myuser
      password: mypassword
  
#### Log:
2017-06-10 18:00 CRITICAL task          series_sigo     BUG: Unhandled error in plugin form: unexpected '[' char in declaration
Traceback (most recent call last):
  File "/home/pi/flexget-dev/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/home/pi/flexget-dev/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/pi/flexget-dev/flexget/plugins/operate/formlogin.py", line 77, in on_task_start
    for form in br.forms():
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 420, in forms
    return self._factory.forms()
  File "/usr/lib/python2.7/dist-packages/mechanize/_html.py", line 557, in forms
    self._forms_factory.forms())
  File "/usr/lib/python2.7/dist-packages/mechanize/_html.py", line 237, in forms
    _urlunparse=_rfc3986.urlunsplit,
  File "/usr/lib/python2.7/dist-packages/mechanize/_form.py", line 844, in ParseResponseEx
    _urlunparse=_urlunparse,
  File "/usr/lib/python2.7/dist-packages/mechanize/_form.py", line 981, in _ParseFileEx
    fp.feed(data)
  File "/usr/lib/python2.7/dist-packages/mechanize/_form.py", line 760, in feed
    raise ParseError(exc)
ParseError: unexpected '[' char in declaration 

### Additional information:

- FlexGet version: 2.10.61.dev
- Python version: 2.7.9
- Installation method: GIT checkout
- Using daemon (yes/no): NO
- OS and version:Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux , Raspbian GNU/Linux 8 (jessie)
- Link to crash log:

**Comment by cvium** [comment]
Different parse error but why open a new issue?

**Comment by javichu666** [comment]
I opened a new issue because the last one was fixed with new version, and this one gives a new parse error. My apologies if it was not the right thing
