### ISSUE TITLE
Crash in lazy_lookup

### ISSUE THREAD

**Issue by tremby** [Flexget/Flexget#1877]
I'm getting a crash repeatedly.

I was getting it with 2.10.33 and just updated to 2.10.61 where the issue remains.

In my log file:

```
2017-06-18 20:29 ERROR    lazy_lookup   mytask    Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 125, in lazy_series_lookup
    return self.series_lookup(entry, language, self.series_map)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 117, in series_lookup
    session=session
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 542, in lookup_series
    tvdb_id = find_series_id(name, language=language)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 457, in find_series_id
    title = split_title_year(n)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
  
### Additional information:

- FlexGet version: 2.10.61
- Python version: 2.7.12
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu 16.04

It looks to be very similar to #1466

**Comment by liiight** [comment]
Possible. Can you add debug logs?

**Comment by tremby** [comment]
Is this enough?

```
...
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Looking up tvdb information for Ginormous Food None
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Series <name=Ginormous Food,tvdb_id=None> information restored from cache.
2017-06-18 21:47 DEBUG    regexp        mytask    regexp '^food$' matched field 'tvdb_genres' for Ginormous Food - S02E08 [ 2017 ] [ TS | H.264 | HDTV | 720p | FastTorrent | Internal ] [ Uploader: Anonymous ]  [ Ginormous.Food.S02E08.Pittsburgh.Bacon.and.Burger.Bonanza.720p.HDTV.DD5.1.H.264-NTb ]
2017-06-18 21:47 VERBOSE  task          mytask    REJECTED: `Ginormous Food - S02E08 [ 2017 ] [ TS | H.264 | HDTV | 720p | FastTorrent | Internal ] [ Uploader: Anonymous ]  [ Ginormous.Food.S02E08.Pittsburgh.Bacon.and.Burger.Bonanza.720p.HDTV.DD5.1.H.264-NTb ]` by regexp plugin because regexp '^food$' matched field 'tvdb_genres'
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Looking up tvdb information for Misc Sports None
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Series <name=Misc Sports,tvdb_id=None> not found in cache, looking up from tvdb.
2017-06-18 21:47 DEBUG    utils.requests mytask    Fetching URL https://api.thetvdb.com/search/series with args () and kwargs {'json': None, 'params': {'name': u'Misc Sports'}, u'timeout': 30, 'headers': {u'Accept-Language': u'en', u'Authorization': u'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTc5MDc1MzYsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDk3ODIxMTM2fQ.TvuNCb-sHb5tnQTvvxHxYKq42AITc-ZOrBKcDMsV0JpWEmYyV2jtmqZE6u1Jjj9JaK9WUu_tvT1BOv72bZ7qyP9UxH2cFBRncqfe0ej6hUIAwN998NzZH6HlHu5FnyZRezrkYyFZYmhXgHvoxhRNbjI-A7-mQuseBqW01-udBqCSgqj8hmJKdVqQtLv5LkmcrM8w9FTCvQpu72XFxXmybjDlLfnhIrYPXRk2gzf08hj2RImiXLbm9P0NHsNREJ5OuSUEspuUn3PPzYRruZO-svbovk_WjckcuwduBmrvVndiWRAku2MXz5lwnRznK5yOohOhcLNYJGj8muP-LmiH0A'}}
2017-06-18 21:47 DEBUG    thetvdb_lookup mytask    Error looking up tvdb series information for Misc Sports - 2017.06.18 - World Cup of Pool - Session 10 [ 2017 ] [ MKV | H.264 | HDTV | 720p | Scene | FastTorrent ] [ Uploader: Anonymous ]  [ World.Cup.Of.Pool.2017.Session.10.720p.HDTV.x264-GAMETiME ]: Unable to get search results for Misc Sports: 404 Client Error: Not Found for url: https://api.thetvdb.com/search/series?name=Misc+Sports
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Looking up tvdb information for World Fool News None
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Series <name=World Fool News,tvdb_id=None> information restored from cache.
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Looking up tvdb information for 20/20 None
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Series <name=20/20,tvdb_id=None> not found in cache, looking up from tvdb.
2017-06-18 21:47 DEBUG    utils.requests mytask    Fetching URL https://api.thetvdb.com/search/series with args () and kwargs {'json': None, 'params': {'name': u'20/20'}, u'timeout': 30, 'headers': {u'Accept-Language': u'en', u'Authorization': u'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTc5MDc1MzYsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDk3ODIxMTM2fQ.TvuNCb-sHb5tnQTvvxHxYKq42AITc-ZOrBKcDMsV0JpWEmYyV2jtmqZE6u1Jjj9JaK9WUu_tvT1BOv72bZ7qyP9UxH2cFBRncqfe0ej6hUIAwN998NzZH6HlHu5FnyZRezrkYyFZYmhXgHvoxhRNbjI-A7-mQuseBqW01-udBqCSgqj8hmJKdVqQtLv5LkmcrM8w9FTCvQpu72XFxXmybjDlLfnhIrYPXRk2gzf08hj2RImiXLbm9P0NHsNREJ5OuSUEspuUn3PPzYRruZO-svbovk_WjckcuwduBmrvVndiWRAku2MXz5lwnRznK5yOohOhcLNYJGj8muP-LmiH0A'}}
2017-06-18 21:47 ERROR    lazy_lookup   mytask    Unhandled error in lazy lookup plugin
2017-06-18 21:47 CRITICAL manager       mytask    An unexpected crash has occurred. Writing crash report to /home/myuser/.config/flexget/crash_report.2017.06.18.214724739325.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.61
2017-06-18 21:47 DEBUG    manager       mytask    Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 125, in lazy_series_lookup
    return self.series_lookup(entry, language, self.series_map)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 117, in series_lookup
    session=session
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 542, in lookup_series
    tvdb_id = find_series_id(name, language=language)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 457, in find_series_id
    title = split_title_year(n)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
2017-06-18 21:47 DEBUG    api_tvdb      mytask    Looking up tvdb information for World Fool News None
...
```
