### ISSUE TITLE
BUG: Unhandled error in plugin torrent_alive: u'announce'

### ISSUE THREAD

**Issue by jbroadway79** [Flexget/Flexget#1891]
### Expected behaviour:

Based on the logs torrents were accepted and should start downloading.

### Actual behaviour:
Task crashes and continues to the next one defined in config

### Steps to reproduce:
- Step 1: Run 'flexget execute'

#### Config:

https://pastebin.com/T4g42Ngj

  
#### Log:

Debug
https://pastebin.com/uwwk4EYD

### Additional information:

- FlexGet version: 2.10.64 (issue started) then again to 2.10.66 (issue remains)
- Python version: Python 2.7.12+
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety

- Link to crash log: https://pastebin.com/QETRGRAH

<!---
In config and debug/crash logs, remember to redact any personal or sensitive information such as passwords, API keys, private URLs and so on.

Please verify that the following data is present before submitting your issue:

- Link to a paste service or paste above the relevant config (preferably full config, including templates if present). Please make sure the paste does not expire, if possible.
- Link to a paste service or paste above debug-level logs of the relevant task/s (use `flexget -L debug execute --tasks <Task_name>`).
- FlexGet version (use `flexget -V` to get it).
- Full Python version, for example `2.7.11` (use `python -V` to get it). Note that FlexGet is not supported for use with Python v3.0, 3.1, 3.2 or 3.6.
- Installation method (pip, git install, etc).
- Whether or not you're running FlexGet as a daemon.
- OS and version.
- Attach crash log if one was generated, in addition to the debug-level log. It can be found in the directory with your config file.

**Comment by liiight** [comment]
I added debug logs, please rerun with debug and paste logs

**Comment by jbroadway79** [comment]
Here is the crash report running in debug mode. I'm not 100% sure specifically what your looking for. Let me know if you need more:

> 2017-07-17 14:51 DEBUG    modif_torrent get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi seems to be a torrent
2017-07-17 14:51 DEBUG    modif_torrent get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO seems to be a torrent
2017-07-17 14:51 DEBUG    modif_torrent get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi seems to be a torrent
2017-07-17 14:51 DEBUG    modif_torrent get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN seems to be a torrent
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  Страшные сказки (2015) HDRip avi files: [u'\u0421\u0442\u0440\u0430\u0448\u043d\u044b\u0435 \u0441\u043a\u0430\u0437\u043a\u0438 (2015) HDRip.avi']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  Экстрасенсы (2015) BDRip-AVC_ivanes20031987 mkv files: [u'\u042d\u043a\u0441\u0442\u0440\u0430\u0441\u0435\u043d\u0441\u044b (2015) BDRip-AVC_ivanes20031987.mkv']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  King Arthur Legend of the Sword 2017 1080p KORSUB HDRip x264 AAC2 0-STUTTERSHIT mp4 files: [u'King.Arthur.Legend.of.the.Sword.2017.1080p.KORSUB.HDRip.x264.AAC2.0-STUTTERSHIT.mp4']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  Personal Shopper 2016 DVDRiP x264 DUAL-SNERZ files: [u'Personalshopper-SNERZ.mkv', u'snerz-personalshopper-sample.mkv', u'Personalshopper-SNERZ.nfo']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  Shin Gojira 2016 BDRip Xvid_[tfile ru] avi files: [u'Shin.Gojira.2016.BDRip.Xvid_[tfile.ru].avi']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  Man Up 2015 CUSTOM 720p BluRay DD5 1 x264 HUN-AFTER files: [u'Sample/after-man.up.2015.720p.bluray-sample.mkv', u'after-man.up.2015.720p.bluray.mkv', u'after-man.up.2015.720p.bluray.nfo']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  The Whole Truth 2016 DVDRip x264-486 mkv files: [u'The.Whole.Truth.2016.DVDRip.x264-486.mkv']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi files: [u'Free.Fire.2016.BDRip.1.42Gb.MegaPeer.avi']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO files: [u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.avi', u'sample.avi', u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.srt', u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.nfo']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi files: [u'007.Spectr.2015.DUAL.BDRip.XviD.AC3.-HQ-ViDEO.avi']
2017-07-17 14:51 DEBUG    torrent_files get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN files: [u'jlfdm-din.mkv', u'jlfdm-din.nfo', u'sample.mkv']
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  Страшные сказки (2015) HDRip avi size: 2102.07617188 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  Экстрасенсы (2015) BDRip-AVC_ivanes20031987 mkv size: 744.418231964 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  King Arthur Legend of the Sword 2017 1080p KORSUB HDRip x264 AAC2 0-STUTTERSHIT mp4 size: 4033.86043262 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  Personal Shopper 2016 DVDRiP x264 DUAL-SNERZ size: 1353.17186832 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  Shin Gojira 2016 BDRip Xvid_[tfile ru] avi size: 1490.83789062 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  Man Up 2015 CUSTOM 720p BluRay DD5 1 x264 HUN-AFTER size: 6473.24866009 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  The Whole Truth 2016 DVDRip x264-486 mkv size: 1036.65104103 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi size: 1454.203125 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO size: 1436.58211899 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi size: 2972.97460938 MB
2017-07-17 14:51 DEBUG    torrent_size  get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN size: 724.779566765 MB
2017-07-17 14:51 DEBUG    content_filter get_new_movies  Страшные сказки (2015) HDRip avi files: [u'\u0421\u0442\u0440\u0430\u0448\u043d\u044b\u0435 \u0441\u043a\u0430\u0437\u043a\u0438 (2015) HDRip.avi']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  Экстрасенсы (2015) BDRip-AVC_ivanes20031987 mkv files: [u'\u042d\u043a\u0441\u0442\u0440\u0430\u0441\u0435\u043d\u0441\u044b (2015) BDRip-AVC_ivanes20031987.mkv']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  King Arthur Legend of the Sword 2017 1080p KORSUB HDRip x264 AAC2 0-STUTTERSHIT mp4 files: [u'King.Arthur.Legend.of.the.Sword.2017.1080p.KORSUB.HDRip.x264.AAC2.0-STUTTERSHIT.mp4']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  Personal Shopper 2016 DVDRiP x264 DUAL-SNERZ files: [u'Personalshopper-SNERZ.mkv', u'snerz-personalshopper-sample.mkv', u'Personalshopper-SNERZ.nfo']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  Shin Gojira 2016 BDRip Xvid_[tfile ru] avi files: [u'Shin.Gojira.2016.BDRip.Xvid_[tfile.ru].avi']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  Man Up 2015 CUSTOM 720p BluRay DD5 1 x264 HUN-AFTER files: [u'Sample/after-man.up.2015.720p.bluray-sample.mkv', u'after-man.up.2015.720p.bluray.mkv', u'after-man.up.2015.720p.bluray.nfo']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  The Whole Truth 2016 DVDRip x264-486 mkv files: [u'The.Whole.Truth.2016.DVDRip.x264-486.mkv']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi files: [u'Free.Fire.2016.BDRip.1.42Gb.MegaPeer.avi']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO files: [u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.avi', u'sample.avi', u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.srt', u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.nfo']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi files: [u'007.Spectr.2015.DUAL.BDRip.XviD.AC3.-HQ-ViDEO.avi']
2017-07-17 14:51 DEBUG    content_filter get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN files: [u'jlfdm-din.mkv', u'jlfdm-din.nfo', u'sample.mkv']
2017-07-17 14:51 DEBUG    content_size  get_new_movies  Страшные сказки (2015) HDRip avi size 2102.07617188 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  Экстрасенсы (2015) BDRip-AVC_ivanes20031987 mkv size 744.418231964 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  King Arthur Legend of the Sword 2017 1080p KORSUB HDRip x264 AAC2 0-STUTTERSHIT mp4 size 4033.86043262 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  Personal Shopper 2016 DVDRiP x264 DUAL-SNERZ size 1353.17186832 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  Shin Gojira 2016 BDRip Xvid_[tfile ru] avi size 1490.83789062 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  Man Up 2015 CUSTOM 720p BluRay DD5 1 x264 HUN-AFTER size 6473.24866009 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  The Whole Truth 2016 DVDRip x264-486 mkv size 1036.65104103 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi size 1454.203125 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO size 1436.58211899 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi size 2972.97460938 MB
2017-07-17 14:51 DEBUG    content_size  get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN size 724.779566765 MB
2017-07-17 14:51 DEBUG    torrent_alive get_new_movies  Checking for seeds for Страшные сказки (2015) HDRip avi:
2017-07-17 14:51 CRITICAL task          get_new_movies  BUG: Unhandled error in plugin torrent_alive: u'announce'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 243, in on_task_output
    tracker = torrent.content['announce']
KeyError: u'announce'

>

**Comment by liiight** [comment]
Bah, I should have said wait for the next release... or update from github

**Comment by jbroadway79** [comment]
I'm currently on 2.10.67. I'll run again next release. Thanks liiight.

**Comment by jbroadway79** [comment]
I manually added log.debug('started examining torrent: %s', torrent) to line 219 of flexget/plugins/filter/torrent_alive.py and ran 'flexget -L debug execute'. Here is the crash log. If I fubarred something up doing it manually let me know; I wasn't sure how to update from Github. Here is the crashlog:

> 2017-07-17 16:53 DEBUG    torrent_files get_new_movies  Страшные сказки (2015) HDRip avi files: [u'\u0421\u0442\u0440\u0430\u0448\u043d\u044b\u0435 \u0441\u043a\u0430\u0437\u043a\u0438 (2015) HDRip.avi']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  Экстрасенсы (2015) BDRip-AVC_ivanes20031987 mkv files: [u'\u042d\u043a\u0441\u0442\u0440\u0430\u0441\u0435\u043d\u0441\u044b (2015) BDRip-AVC_ivanes20031987.mkv']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  King Arthur Legend of the Sword 2017 1080p KORSUB HDRip x264 AAC2 0-STUTTERSHIT mp4 files: [u'King.Arthur.Legend.of.the.Sword.2017.1080p.KORSUB.HDRip.x264.AAC2.0-STUTTERSHIT.mp4']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  Personal Shopper 2016 DVDRiP x264 DUAL-SNERZ files: [u'Personalshopper-SNERZ.mkv', u'snerz-personalshopper-sample.mkv', u'Personalshopper-SNERZ.nfo']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  Shin Gojira 2016 BDRip Xvid_[tfile ru] avi files: [u'Shin.Gojira.2016.BDRip.Xvid_[tfile.ru].avi']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  Man Up 2015 CUSTOM 720p BluRay DD5 1 x264 HUN-AFTER files: [u'Sample/after-man.up.2015.720p.bluray-sample.mkv', u'after-man.up.2015.720p.bluray.mkv', u'after-man.up.2015.720p.bluray.nfo']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  The Whole Truth 2016 DVDRip x264-486 mkv files: [u'The.Whole.Truth.2016.DVDRip.x264-486.mkv']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi files: [u'Free.Fire.2016.BDRip.1.42Gb.MegaPeer.avi']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO files: [u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.avi', u'sample.avi', u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.srt', u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.nfo']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi files: [u'007.Spectr.2015.DUAL.BDRip.XviD.AC3.-HQ-ViDEO.avi']
2017-07-17 16:53 DEBUG    torrent_files get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN files: [u'jlfdm-din.mkv', u'jlfdm-din.nfo', u'sample.mkv']
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Dheepan 2015 BDRip 720p mkv size: 7709.88942146 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Страшные сказки (2015) HDRip avi size: 2102.07617188 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Экстрасенсы (2015) BDRip-AVC_ivanes20031987 mkv size: 744.418231964 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  King Arthur Legend of the Sword 2017 1080p KORSUB HDRip x264 AAC2 0-STUTTERSHIT mp4 size: 4033.86043262 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Personal Shopper 2016 DVDRiP x264 DUAL-SNERZ size: 1353.17186832 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Shin Gojira 2016 BDRip Xvid_[tfile ru] avi size: 1490.83789062 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Man Up 2015 CUSTOM 720p BluRay DD5 1 x264 HUN-AFTER size: 6473.24866009 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  The Whole Truth 2016 DVDRip x264-486 mkv size: 1036.65104103 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi size: 1454.203125 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO size: 1436.58211899 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi size: 2972.97460938 MB
2017-07-17 16:53 DEBUG    torrent_size  get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN size: 724.779566765 MB
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Dheepan 2015 BDRip 720p mkv files: [u'Dheepan.2015.BDRip.720p.mkv']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Страшные сказки (2015) HDRip avi files: [u'\u0421\u0442\u0440\u0430\u0448\u043d\u044b\u0435 \u0441\u043a\u0430\u0437\u043a\u0438 (2015) HDRip.avi']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Экстрасенсы (2015) BDRip-AVC_ivanes20031987 mkv files: [u'\u042d\u043a\u0441\u0442\u0440\u0430\u0441\u0435\u043d\u0441\u044b (2015) BDRip-AVC_ivanes20031987.mkv']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  King Arthur Legend of the Sword 2017 1080p KORSUB HDRip x264 AAC2 0-STUTTERSHIT mp4 files: [u'King.Arthur.Legend.of.the.Sword.2017.1080p.KORSUB.HDRip.x264.AAC2.0-STUTTERSHIT.mp4']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Personal Shopper 2016 DVDRiP x264 DUAL-SNERZ files: [u'Personalshopper-SNERZ.mkv', u'snerz-personalshopper-sample.mkv', u'Personalshopper-SNERZ.nfo']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Shin Gojira 2016 BDRip Xvid_[tfile ru] avi files: [u'Shin.Gojira.2016.BDRip.Xvid_[tfile.ru].avi']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Man Up 2015 CUSTOM 720p BluRay DD5 1 x264 HUN-AFTER files: [u'Sample/after-man.up.2015.720p.bluray-sample.mkv', u'after-man.up.2015.720p.bluray.mkv', u'after-man.up.2015.720p.bluray.nfo']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  The Whole Truth 2016 DVDRip x264-486 mkv files: [u'The.Whole.Truth.2016.DVDRip.x264-486.mkv']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi files: [u'Free.Fire.2016.BDRip.1.42Gb.MegaPeer.avi']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO files: [u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.avi', u'sample.avi', u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.srt', u'Going.in.Style.2017.HDRip.XviD.AC3-EVO.nfo']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi files: [u'007.Spectr.2015.DUAL.BDRip.XviD.AC3.-HQ-ViDEO.avi']
2017-07-17 16:53 DEBUG    content_filter get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN files: [u'jlfdm-din.mkv', u'jlfdm-din.nfo', u'sample.mkv']
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Dheepan 2015 BDRip 720p mkv size 7709.88942146 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Страшные сказки (2015) HDRip avi size 2102.07617188 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Экстрасенсы (2015) BDRip-AVC_ivanes20031987 mkv size 744.418231964 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  King Arthur Legend of the Sword 2017 1080p KORSUB HDRip x264 AAC2 0-STUTTERSHIT mp4 size 4033.86043262 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Personal Shopper 2016 DVDRiP x264 DUAL-SNERZ size 1353.17186832 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Shin Gojira 2016 BDRip Xvid_[tfile ru] avi size 1490.83789062 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Man Up 2015 CUSTOM 720p BluRay DD5 1 x264 HUN-AFTER size 6473.24866009 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  The Whole Truth 2016 DVDRip x264-486 mkv size 1036.65104103 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Free Fire 2016 BDRip 1 42Gb MegaPeer avi size 1454.203125 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Going in Style 2017 HDRip XviD AC3-EVO size 1436.58211899 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  007 Spectr 2015 DUAL BDRip XviD AC3 -HQ-ViDEO avi size 2972.97460938 MB
2017-07-17 16:53 DEBUG    content_size  get_new_movies  Juste la fin du monde 2016 BDRip x264-DiN size 724.779566765 MB
2017-07-17 16:53 DEBUG    torrent_alive get_new_movies  Checking for seeds for Dheepan 2015 BDRip 720p mkv:
2017-07-17 16:53 DEBUG    torrent_alive get_new_movies  started examining torrent: <Torrent instance. Files: [{u'path': u'', u'name': u'Dheepan.2015.BDRip.720p.mkv', u'size': 8084405010}]>
2017-07-17 16:53 CRITICAL task          get_new_movies  BUG: Unhandled error in plugin torrent_alive: u'announce'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/torrent_alive.py", line 244, in on_task_output
    tracker = torrent.content['announce']
KeyError: u'announce'

>

**Comment by liiight** [comment]
Try changing that line to `log.debug('started examining torrent: %s', torrent.content)`

**Comment by jbroadway79** [comment]
https://pastebin.com/2xKw9Yd5

**Comment by jbroadway79** [comment]
@liiight I've tested this and it looks like its not crashing now. Thanks for your help!

**Comment by liiight** [comment]
Np
