### ISSUE TITLE
BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by daurigi** [Flexget/Flexget#1892]
latest version of flexget and download-npo installed.

config.yml
```yaml
tasks:
tv-journaal:
npo_watchlist:
email: xxx
password: yyy
remove_accepted: yes
max_episode_age_days: 7
accept_all: yes
exec:
fail_entries: yes
auto_escape: yes
on_output:
for_accepted:
- /usr/local/bin/download-npo -o "/var/storage/queue/tvshows/NPO/{{series_name_plain}}" -f "{serie_titel} - {datum} {aflevering_titel} ({episode_id})" -t {{url}}
```
```
2017-07-05 20:31 CRITICAL task tv-journaal BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
return method(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in call
return self.func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 326, in on_task_input
entries += self._get_favorites_entries(task, config)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 318, in _get_favorites_entries
series_info = self._get_series_info(task, config, series_name, url)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/npo_watchlist.py", line 180, in _get_series_info
series_info['npo_url'] = tvseries.find('a', itemprop='url')['href']
AttributeError: 'NoneType' object has no attribute 'find'
```
Something changed on the NPO site?

**Comment by mfonville** [comment]
The npo.nl site has been completely overhauled. They dropped the schema.org/TVSeries data entries.
I wrote to the npo.nl developers if they could please re-add these entries to the webpage.
Meanwhile I will look at the new npo.nl account system as soon as I will have time available (https://github.com/Flexget/Flexget/issues/1893) though that probably will only be in August

**Comment by jeroenl** [comment]
I've rewritten the plug-in to work with the new site, see pull request #1901. I managed to add the series information even without the schema.org data. The only thing I couldn't find is the series language.

**Comment by daurigi** [comment]
THANK YOU very much!
