### ISSUE TITLE
BUG: Unhandled error in plugin series: unorderable types: Episode() < Episode()

### ISSUE THREAD

**Issue by gazhay** [Flexget/Flexget#1896]
Carried over from forums at request of devs
see : https://discuss.flexget.com/t/flexget-reporting-bug/3592
--
Related? (#1592)
--
Crash Log
```
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Stephen Colbert 2017-07-14 The best moments of the week, with a newly-recorded opening & monologue 720p` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Stephen Colbert 2017-07-13 Ashton Kutcher, Rob Corddry, the New Pornographers 720p` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `The Expanse S02E08 1080p WEB-DL 6CH HEVC x265-RMTeam` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `The Daily Show (2017) 07 12 James Davis 720p WEB x264 TBS` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `The Daily Show 2017-07-17 Regina Hall 720p` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `The Daily Show 2017 07 13 Illhan Omar 1080p WEB x264-TBS` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `The Blacklist Redemption S01E03 1080p WEB-DL DD5.1 HEVC x265-RMT` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `The.Americans.2013.S04E08.S02E16.720p.HEVC.x265-MeGusta` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `The.Amazing.Race.S29E12.720p.HDTV.x264-AVIDITY[rartv]` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Storage Wars Northern Treasures S01E23 480p x264-mSD` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Storage Wars Northern Treasures S01E22 720p WEB h264 CookieMonster` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Storage Wars Northern Treasures S01E21 WEB h264-CookieMonster[eztv] mkv` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Storage Wars Northern Treasures S01E20 480p x264-mSD` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Steve Harveys Funderdome S01E05 WEB x264-TBS[eztv] mkv` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Ransom.S01E03.The.Box.1080p.WEB-DL.DD5.1.H.264-ViSUM` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Outcast S01E04 720p HDTV x265 HEVC 275MB - ShAaNiG` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Seth Meyers 2017-07-17 Maya Rudolph, Matt Johnson 720p` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Jimmy Kimmel 2017 07 12 Jacob Batalon 720p WEB h264-TBS[rarbg]` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Jimmy Kimmel 2017-07-17 Billy Crystal, Chris Bianco, Casey James Salengo 720p` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Jimmy Kimmel (2017) 07 13 50 Cent 720p WEB x264 TBS rarbg` by series plugin because choosing best available quality
    2017-07-18 17:13 VERBOSE  series        download-shows  identified by is currently on `auto` for Game of Thrones. Multiple id types may be accepted until it locks in on the appropriate type.
    2017-07-18 17:13 VERBOSE  task          download-shows  ACCEPTED: `Game of Thrones S07E01 Dragonstone 1080p 10bit AMZN WEB-DL DD+5 1 x265 HEVC-MZABI mkv` by series plugin because choosing best available quality
    2017-07-18 17:13 ERROR    series        download-shows  cannot compare None with ep
    2017-07-18 17:13 ERROR    series        download-shows  cannot compare ep with None
    2017-07-18 17:13 CRITICAL task          download-shows  BUG: Unhandled error in plugin series: unorderable types: Episode() < Episode()
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/flexget/task.py", line 483, in __run_plugin
        return method(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in __call__
        return self.func(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/filter/series.py", line 1544, in on_task_filter
        self.process_series(task, series_entries, series_config)
      File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/filter/series.py", line 1652, in process_series
        if entity < entity.series.begin:
    TypeError: unorderable types: Episode() < Episode()

```
Config
```

templates:
  global:
    verify_ssl_certificates: no

  tv:
    set:
      ratio: 2
      path: /mnt/samba/TV/{{ series_name }}
      content_filename: "{{ series_name }} - {{ series_id }} {% if tvdb_ep_name|default(False) %} - {{ tvdb_ep_name }} {% endif %} - {{ quality|upper }} {% if proper_count %} - proper{% if proper_count > 1 %}{{ proper_count }}{% endif %}{% endif %}"
      quality: <=1080p !h265
      target: 720p
      timeframe: 3 hours
      identified_by: ep

    exists_series:
      path: '/mnt/samba/TV/{{series_name}}'
      #allow_different_qualities: better
    thetvdb_lookup: yes
    torrent_cache: yes
    torrent_alive: yes
    transmission:
      host: cassie.lan
      port: 9091
    content_filter:
      require: [ '*.avi', '*.m4v', '*.mkv', '*.mp4' ]
      reject:
        - '*.rar' # mostly fakes but too lazy to unrar
        - '*.exe' # fakes with "codec packs"
        - '*.nfo' # fakes/or shit I don't want to deal with
        - 'info.txt'       # fakes/or shit I don't want to deal with
        - '*.lnk' # fakes/shit

    series:
        shows:
          - "Jimmy Kimmel Live !":
             identified_by: date
             alternate_name: "Jimmy Kimmel"
          - "Late Night With Seth Meyers":
             identified_by: date
             alternate_name: "Seth Meyers"
          - "The Late Late Show with James Corden":
             identified_by: date
             alternate_name: "James Corden"
          - "The Late Show with Stephen Colbert":
             identified_by: date
             alternate_name: "Stephen Colbert"
          - "The Tonight Show with Jimmy Fallon":
             identified_by: date
             alternate_name: "Jimmy Fallon"
          - "The Daily Show with Trevor Noah":
             identified_by: date
             alternate_name: "The Daily Show"

tasks:


  other-shows:
    template: tv
    set_series_begin: yes
    configure_series:
      from:
        entry_list: "nextEpisode"
    inputs:
      - rss: https://showrss.info/other/shows.rss
      - rss: https://www.limetorrents.cc/rss/20/

  download-shows:
    template: tv
    configure_series:
      from:
        entry_list: "nextEpisode"

    discover:
      what:
        - next_series_episodes: yes
      from:
        - 1337x: yes
        - piratebay:
            category: video
            sort_by: date
        - search_rss: https://showrss.info/other/shows.rss
        - search_rss: https://www.limetorrents.cc/rss/20/
      interval: 1 hour  # Search for expected episodes again every hour

  load-shows:
    disable: [seen, retry_failed]
    rss:
      url: #redacted
    manipulate:
      - title:
          extract: ^([^\-]+)\-
      - description:
          extract: ^([^\|]+)\|
      - url:
          from: description
    accept_all: yes
    all_series: yes
    set_series_begin: yes
    list_add:
      - entry_list: "nextEpisode"

web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: yes

schedules:
  # Run every task once an hour
  - tasks: [other-shows, download-shows]
    interval:
      hours: 1
  - tasks: [load-shows]
    interval:
      hours: 3
```

**Comment by gazhay** [comment]
- FlexGet version: 2.10.43 (Although I notice an update has been pushed now)
- Python version: 3.5.2
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: ubuntu 16.04.2 LTS

**Comment by gazhay** [comment]
Seems like the update has squashed the bug.

**Comment by arthurwolf** [comment]
Very similar issue:

```
    │    └ <function Thread.run at 0x759ab26facb0>
    └ <Thread(task_queue, started daemon 129307177387712)>
  File "/home/arthur/.pyenv/versions/3.10.15/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 129307177387712)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 129307177387712)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x759aacadbf10>>
    └ <Thread(task_queue, started daemon 129307177387712)>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x759aaf8e0790>
    │    └ <flexget.task.Task object at 0x759aac74c5e0>
    └ <flexget.task_queue.TaskQueue object at 0x759aacadbf10>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 88, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x759aac74c5e0>
           └ <function Task.execute at 0x759aaf8e0700>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 717, in execute
    self._execute()
    │    └ <function Task._execute at 0x759aaf8e0670>
    └ <flexget.task.Task object at 0x759aac74c5e0>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 686, in _execute
    self.__run_task_phase(phase)
    │                     └ 'filter'
    └ <flexget.task.Task object at 0x759aac74c5e0>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 515, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x759aac74c5e0>, [{'Kaguya-Sama': {'alternate_name': ['Kaguya-sama wa Kokurasetai? Tensai-tachi...
               │                 │       └ 'filter'
               │                 └ <PluginInfo(name=series)>
               └ <flexget.task.Task object at 0x759aac74c5e0>
> File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/task.py", line 548, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x759aac74c5e0>, [{'Kaguya-Sama': {'alternate_name': ['Kaguya-sama wa Kokurasetai? Tensai-tachi...
             └ <Event(name=plugin.series.filter,func=on_task_filter,priority=128)>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/event.py", line 21, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x759aac74c5e0>, [{'Kaguya-Sama': {'alternate_name': ['Kaguya-sama wa Kokurasetai? Tensai-tachi...
           │    └ <bound method FilterSeries.on_task_filter of <flexget.components.series.series.FilterSeries object at 0x759aaca6e350>>
           └ <Event(name=plugin.series.filter,func=on_task_filter,priority=128)>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/components/series/series.py", line 590, in on_task_filter
    self.process_series(task, series_entries, series_config)
    │    │              │     │               └ {}
    │    │              │     └ <unprintable dict object>
    │    │              └ <flexget.task.Task object at 0x759aac74c5e0>
    │    └ <function FilterSeries.process_series at 0x759aacfe1630>
    └ <flexget.components.series.series.FilterSeries object at 0x759aaca6e350>
  File "/home/arthur/.flexget/lib/python3.10/site-packages/flexget/components/series/series.py", line 718, in process_series
    if entity < entity.series.begin:
       │        │      └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x759aacb972e0>
       │        └ <unprintable Episode object>
       └ <unprintable Episode object>
   
TypeError: '<' not supported between instances of 'Episode' and 'Episode'

```
