### ISSUE TITLE
Crash report log being generated. (Don't know why)

### ISSUE THREAD

**Issue by MoKoChino** [Flexget/Flexget#1948]
I'm getting a crash_report.log file each time flexget is executed.

Here's my config.yml file:

```
schedules:
  # Run every task once a day
  - tasks: '*'
    interval:
      days: 1
tasks:
  download-rss:
    version_checker: yes
    rss: http://showrss.info/user/*****.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    all_series: yes
    template: torrent
    thetvdb_lookup: yes
    set:
     tvdb_series_name: "{{ tvdb_series_name }}"
  sort-shows:
    filesystem:
      path: 
        - /home/pi/Downloads/Series/Descargados/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    metainfo_series: yes
    accept_all: yes
    disable: seen
    regexp:
      reject:
        - sample
    series:
      settings:
        group 1:
          parse_only: yes
      group 1:
        - Scandal (2012):
            alternate_name: Scandal US
        - Once Upon a Time (2011):
            alternate_name: Once Upon a Time
        - House of Cards (US):
            alternate_name: House of Cards 2013
        - Last Man Standing (2011):
            alternate_name: Last Man Standing US
        - South Park
        - Modern Family
        - The Middle
        - Game of Thrones
        - Homeland
        - Orange Is the New Black
        - The Fall
        - Better Call Saul
        - Luther
        - Silicon Valley
        - Community
        - True Detective
        - Ballers
        - Narcos
        - The X Files
        - Making a Murderer
        - American Crime Story
    thetvdb_lookup: yes
    set:                 
     tvdb_series_name: "{{ tvdb_series_name }}"
     tvdb_ep_id: "{{ tvdb_ep_id }}"
    move:
      to: /home/pi/Downloads/Series/OrdenadosSubs/{{ tvdb_series_name }}/
      rename: '{{ tvdb_series_name }}.{{ tvdb_ep_id }}'
      along:
        extensions:
          - sub
          - srt
    template: subtitles
templates:
  correo:
    notify:
      task:
        template: html
        via:
          - email:
              from: ******@gmail.com
              to: ******@gmail.com
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: ******@gmail.com
              smtp_password: ************
              smtp_tls: true
    template: subtitles
  torrent:
    deluge:
      path: /home/pi/Downloads/Series/Incompletos/
      movedone: /home/pi/Downloads/Series/Descargados/
      label: `{{trakt_series_network}}`
      queuetotop: yes
    template: tv
  rename-files:
    thetvdb_lookup: yes
    exists_series:
      - /home/pi/Downloads/Series/Descargados/{{ tvdb_series_name }}
    accept_all: yes
    seen: local
    set:
      path: 
        - /home/pi/Downloads/Series/Descargados/{{ tvdb_series_name }}
      main_file_only: yes
      content_filename: "{{ tvdb_series_name }} - {{ tvdb_season }}x{{ tvdb_episode|pad(2) }} - {{ tvdb_ep_name|default('Missing title') }}"
    move:
      to: /home/pi/Downloads/Series/OrdenadosSubs/{{ tvdb_series_name }}
    template: correo
  subtitles:
    filesystem:
      path: 
        - /home/pi/Downloads/Series/OrdenadosSubs
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    periscope:
      languages:
        - es
      alternatives:
        - en
      overwrite: yes
  tv:
    thetvdb_lookup: yes
    require_field: tvdb_series_name
    seen: local
    exists_series:
      - /home/pi/Downloads/Series/Descargados/{{ tvdb_series_name }}
    accept_all: yes
    set:
      path: 
        - /home/pi/Downloads/Series/OrdenadosSubs/{{ tvdb_series_name }}/
      filename: '{{ tvdb_series_name }} - {{ series_id }} - {{ tvdb_ep_name}}{{ location | pathext }}'
      clean_source: 100
      along:
        - mkv
        - mp4
        - avi
    template: rename-files
```
Here's the clean flexget.log file for just one execution:

```
2017-08-15 22:55 INFO     manager                       Daemonizing...
2017-08-15 22:55 INFO     manager                       Daemonize complete. New PID: 5206
2017-08-15 22:55 INFO     scheduler                     Starting scheduler
2017-08-17 17:39 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2017-08-17 17:39 WARNING  version_checker download-rss    You are not running latest Flexget Version. Current is 2.10.78 and latest is 2.10.81
2017-08-17 17:39 VERBOSE  filesystem    download-rss    Starting to scan folders.
2017-08-17 17:39 VERBOSE  filesystem    download-rss    Scanning folder /home/pi/Downloads/Series/OrdenadosSubs. Recursion is set to True.
2017-08-17 17:39 VERBOSE  backlog       download-rss    Added 2 entries from backlog
2017-08-17 17:39 VERBOSE  details       download-rss    Produced 25 entries.
2017-08-17 17:39 VERBOSE  task          download-rss    REJECTED: `Twin Peaks.S03E10` by retry_failed plugin because has already failed 4 times in the past. (failure reason: cannot find any subtitles for now.)
2017-08-17 17:39 VERBOSE  task          download-rss    REJECTED: `Shooter S02E04 HDTV x264 SVA` by seen plugin because entry with title `Shooter S02E04 HDTV x264 SVA` is already marked seen in the task download-rss at 2017-08-11 17:24
2017-08-17 17:39 VERBOSE  task          download-rss    REJECTED: `Wrecked S02E08 HDTV x264 LOL` by seen plugin because entry with title `Wrecked S02E08 HDTV x264 LOL` is already marked seen in the task download-rss at 2017-08-11 17:24
2017-08-17 17:39 VERBOSE  task          download-rss    REJECTED: `Rick and Morty S03E03 HDTV x264 BATV` by seen plugin because entry with title `Rick and Morty S03E03 HDTV x264 BATV` is already marked seen in the task download-rss at 2017-08-11 17:24
2017-08-17 17:39 VERBOSE  task          download-rss    REJECTED: `The Strain S04E04 HDTV x264 SVA` by seen plugin because entry with title `The Strain S04E04 HDTV x264 SVA` is already marked seen in the task download-rss at 2017-08-11 17:24
2017-08-17 17:39 VERBOSE  task          download-rss    REJECTED: `Game of Thrones S07E04 HDTV x264 SVA` by seen plugin because entry with title `Game of Thrones S07E04 HDTV x264 SVA` is already marked seen in the task download-rss at 2017-08-11 17:24
2017-08-17 17:39 VERBOSE  task          download-rss    REJECTED: `Twin Peaks S03E13 HDTV x264 SVA` by seen plugin because entry with title `Twin Peaks S03E13 HDTV x264 SVA` is already marked seen in the task download-rss at 2017-08-11 17:24
2017-08-17 17:39 VERBOSE  task          download-rss    ACCEPTED: `Wrecked S02E09 HDTV x264 LOL` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Twin Peaks S03E14 WEB h264 TBS` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    REJECTED: `The Strain S04E05 HDTV x264 SVA` by series plugin because nuked
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `The Strain S04E05 PROPER HDTV x264 FLEET` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Shooter S02E05 HDTV x264 SVA` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    REJECTED: `Shooter S02E04 PROPER WEBRip x264 RARBG` by series plugin because entity has already been downloaded
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Shadowhunters The Mortal Instruments S02E20 WEB x264 TBS` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    REJECTED: `Shadowhunters S02E19 WEBRip x264 RARBG` by series plugin because too much in the future from latest downloaded entity `S02E14`. See `--disable-tracking` if this should be downloaded.
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Rick and Morty S03E04 HDTV x264 BATV` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Game of Thrones S07E06 HDTV x264 AC3 Manning` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    REJECTED: `Game of Thrones S07E05 WEB h264 TBS` by series plugin because nuked
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Game of Thrones S07E05 REPACK WEB h264 TBS` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Dark Matter S03E11 HDTV x264 SVA` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Dark Matter S03E10 HDTV x264 KILLERS` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  task          download-rss    ACCEPTED: `Dark Matter S03E09 HDTV x264 AVSHIT` by series plugin because choosing best available quality
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Game of Thrones has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Game of Thrones S07E06 HDTV x264 AC3 Manning: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Shooter has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Shooter S02E05 HDTV x264 SVA: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Wrecked (2016) has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Wrecked S02E09 HDTV x264 LOL: (UndefinedError) 'location' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Shadowhunters The Mortal Instruments S02E20 WEB x264 TBS: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for The Strain has expired, refreshing from tvdb
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=The Strain,season=4,episode=5> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for The Strain S04E05 PROPER HDTV x264 FLEET: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Rick and Morty has expired, refreshing from tvdb
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Rick and Morty,season=3,episode=4> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Rick and Morty S03E04 HDTV x264 BATV: (UndefinedError) 'location' is undefined
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Game of Thrones,season=7,episode=5> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Game of Thrones S07E05 REPACK WEB h264 TBS: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Twin Peaks has expired, refreshing from tvdb
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Twin Peaks,season=3,episode=14> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Twin Peaks S03E14 WEB h264 TBS: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Dark Matter has expired, refreshing from tvdb
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Dark Matter,season=3,episode=11> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Dark Matter S03E11 HDTV x264 SVA: (UndefinedError) 'location' is undefined
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Dark Matter,season=3,episode=10> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Dark Matter S03E10 HDTV x264 KILLERS: (UndefinedError) 'location' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Sharknado5 Global Warming (2017): (UndefinedError) 'series_id' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set content_filename for Sharknado5 Global Warming (2017): (UndefinedError) 'tvdb_episode' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for ZombieShark: (UndefinedError) 'series_id' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set content_filename for ZombieShark: (UndefinedError) 'tvdb_episode' is undefined
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Dark Matter,season=3,episode=9> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Dark Matter S03E09 HDTV x264 AVSHIT: (UndefinedError) 'location' is undefined
2017-08-17 17:44 VERBOSE  details       download-rss    Summary - Accepted: 11 (Rejected: 11 Undecided: 0 Failed: 3)
2017-08-17 17:44 CRITICAL task          download-rss    BUG: Unhandled error in plugin nzb_size: 'NoneType' object has no attribute 'endswith'
2017-08-17 17:44 CRITICAL manager       download-rss    An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2017.08.17.174407859452.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.78
2017-08-17 17:44 WARNING  task          download-rss    Aborting task (plugin: nzb_size)
```

And here's the crash_report.log file generated:

```
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for The Strain has expired, refreshing from tvdb
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=The Strain,season=4,episode=5> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for The Strain S04E05 PROPER HDTV x264 FLEET: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Rick and Morty has expired, refreshing from tvdb
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Rick and Morty,season=3,episode=4> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Rick and Morty S03E04 HDTV x264 BATV: (UndefinedError) 'location' is undefined
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Game of Thrones,season=7,episode=5> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Game of Thrones S07E05 REPACK WEB h264 TBS: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Twin Peaks has expired, refreshing from tvdb
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Twin Peaks,season=3,episode=14> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Twin Peaks S03E14 WEB h264 TBS: (UndefinedError) 'location' is undefined
2017-08-17 17:40 VERBOSE  api_tvdb      download-rss    Data for Dark Matter has expired, refreshing from tvdb
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Dark Matter,season=3,episode=11> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Dark Matter S03E11 HDTV x264 SVA: (UndefinedError) 'location' is undefined
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Dark Matter,season=3,episode=10> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Dark Matter S03E10 HDTV x264 KILLERS: (UndefinedError) 'location' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Sharknado5 Global Warming (2017): (UndefinedError) 'series_id' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set content_filename for Sharknado5 Global Warming (2017): (UndefinedError) 'tvdb_episode' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for ZombieShark: (UndefinedError) 'series_id' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set content_filename for ZombieShark: (UndefinedError) 'tvdb_episode' is undefined
2017-08-17 17:40 INFO     api_tvdb      download-rss    Data for <TVDBEpisode series=Dark Matter,season=3,episode=9> has expired, refreshing from tvdb
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for Dark Matter S03E09 HDTV x264 AVSHIT: (UndefinedError) 'location' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set filename for None.None: (UndefinedError) 'series_id' is undefined
2017-08-17 17:40 ERROR    set           download-rss    Could not set content_filename for None.None: (UndefinedError) 'tvdb_episode' is undefined
2017-08-17 17:44 VERBOSE  details       download-rss    Summary - Accepted: 11 (Rejected: 11 Undecided: 0 Failed: 3)
2017-08-17 17:44 CRITICAL task          download-rss    BUG: Unhandled error in plugin nzb_size: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/nzb_size.py", line 35, in on_task_modify
    entry.get('filename', '').endswith('.nzb'):
AttributeError: 'NoneType' object has no attribute 'endswith'

```

Let me know if you need anything else. (Running this on a RaspberryPi3 with Raspbian Jessie)

[flexget_crash_issue.zip](https://github.com/Flexget/Flexget/files/1234056/flexget_crash_issue.zip)

**Comment by cvium** [comment]
Only local files have the location field set. This is not a bug.

**Comment by liiight** [comment]
Shouldn't crash like that though

**Comment by MoKoChino** [comment]
It's a local file, as you can see at the config.yml file. And as liiight commented, even it's not, it shouldn't generate a crash, just throw an error

**Comment by cvium** [comment]
Definitely not a local file. Your config is trying to do too much in a single task; you've basically included all your templates in download-rss. Anyway, it will no longer crash.

**Comment by MoKoChino** [comment]
Ok, I'll split the task. THX!
