### ISSUE TITLE
Unhandled error in plugin list_remove for imdb

### ISSUE THREAD

**Issue by programatix** [Flexget/Flexget#1955]
### Expected behaviour:
Remove item from IMDB list

### Actual behaviour:
Exception occurred

### Steps to reproduce:
- Step 1: Execute task 'clean-movies-queue'

#### Config:
```
templates:
  disable-seen-retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed
  movies-metainfo:
    metainfo_movie: yes
    tmdb_lookup: yes
    parsing:
      movie: guessit

tasks:
  clean-movies-queue:
    priority: 31
    template:
      - disable-seen-retry
      - movies-metainfo
    filesystem:
      path:
        - "/{? folder.root ?}{? folder.moviesDVD ?}"
        - "/{? folder.root ?}{? folder.moviesKids ?}"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    list_remove:
      - movie_list: movies
      - trakt_list:
          username: "{? trakt.username ?}"
          account: "{? trakt.account ?}"
          list: "{? trakt.list ?}"
          type: movies
      - imdb_list:
          login: '{? imdb.usr ?}'
          password: '{? imdb.pwd ?}'
          list: '{? imdb.list ?}'
```
  
#### Log:
```
2017-09-01 05:06 WARNING  imdb_list     clean-movies-queue tt4731008 is not in list ls058786234, cannot be removed
2017-09-01 05:06 VERBOSE  utils.requests clean-movies-queue Waiting 4.55 seconds until next request to imdb.com
2017-09-01 05:06 WARNING  imdb_list     clean-movies-queue tt6399158 is not in list ls058786234, cannot be removed
2017-09-01 05:06 VERBOSE  utils.requests clean-movies-queue Waiting 4.57 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt4080594 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.58 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt4217392 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.58 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt4438848 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.57 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt1124037 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.57 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt2567026 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.54 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt3410834 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.59 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt3450650 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.57 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt3896198 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.58 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt3682448 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.58 seconds until next request to imdb.com
2017-09-01 05:07 WARNING  imdb_list     clean-movies-queue tt1489889 is not in list ls058786234, cannot be removed
2017-09-01 05:07 VERBOSE  utils.requests clean-movies-queue Waiting 4.55 seconds until next request to imdb.com
2017-09-01 05:07 CRITICAL task          clean-movies-queue BUG: Unhandled error in plugin list_remove: 400 Client Error: Bad Request for url: http://www.imdb.com/list/_ajax/watchlist_has
Traceback (most recent call last):
  File "/opt/lib/python3.6/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/opt/lib/python3.6/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/opt/lib/python3.6/site-packages/flexget/plugins/output/list_remove.py", line 45, in on_task_output
    thelist -= task.accepted
  File "/_collections_abc.py", line 632, in __isub__
  File "/opt/lib/python3.6/site-packages/flexget/plugins/list/imdb_list.py", line 269, in discard
    cookies=self.cookies).json()
  File "/opt/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/lib/python3.6/site-packages/flexget/utils/requests.py", line 247, in request
    result.raise_for_status()
  File "/opt/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://www.imdb.com/list/_ajax/watchlist_has
```

### Additional information:

- FlexGet version: 2.10.83
- Python version: 3.6
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: merlin asuswrt

**Comment by liiight** [comment]
`imdb_list` is deprecated
