### ISSUE TITLE
sftp_list crash - 'utf8' codec can't decode byte 0xe9 in position 16: invalid continuation byte

### ISSUE THREAD

**Issue by 4oo4** [Flexget/Flexget#1957]
### Expected behaviour:
`sftp_list`/`sftp_download` plugins can download folders with non-ASCII characters.

### Actual behaviour:
`sftp_list` crashes when encountering files/directories with non-ASCII characters (file list here: https://pastebin.com/X6sVHD2d)

### Steps to reproduce:
- Step 1: Run flexget with below task config and file list (see pastebin), and flexget crashes (see crash log below).

#### Config:
```
  music-dl task:
    priority: 5
    accept_all: yes
    sftp_list:
      host: XXXXXXXXXXXXXXXX
      username: XXXXXXXXXXX
      port: 22
      private_key: ~/.ssh/id_rsa
      recursive: False
      get_size: True
      files_only: False
      dirs:
        - "/home/user/files/Music"
    exists:
        - "/storage/Music/"
        - "/downloads/music/"
    seen: local
    sftp_download:
      to: '/downloads/music'
    filesystem:
      path:  '/storage/Music'
      recursive: yes
    notify:
      entries:
        what: accepted
        title: "Accepted entries in task {{ task_name }}"
        message: "Entry {{ title }} accepted!"
        via:
          - pushbullet:
              api_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
locale:
 ```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

#### Log:
```
2017-09-01 21:20 CRITICAL task          music-dl task   BUG: Unhandled error in plugin sftp_list: 'utf8' codec can't decode byte 0xe9 in position 16: invalid continuation byte
2017-09-01 21:20 CRITICAL manager       music-dl task   An unexpected crash has occurred. Writing crash report to /home/user/.config/flexget/crash_report.2017.09.01.212053335417.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.83
2017-09-01 21:20 DEBUG    manager       music-dl task   Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/sftp.py", line 267, in on_task_input
    sftp.walktree(dir, handle_file, handle_dir, handle_unknown, recursive)
  File "/usr/local/lib/python2.7/dist-packages/pysftp.py", line 882, in walktree
    for entry in self._sftp.listdir(remotepath):
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 183, in listdir
    return [f.filename for f in self.listdir_attr(path)]
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 219, in listdir_attr
    filename = msg.get_text()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/message.py", line 178, in get_text
    return u(self.get_string())
  File "/usr/local/lib/python2.7/dist-packages/paramiko/py3compat.py", line 55, in u
    return s.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 16: invalid continuation byte
2017-09-01 21:20 WARNING  task          music-dl task   Aborting task (plugin: sftp_list)
2017-09-01 21:20 DEBUG    task_queue                    task music-dl task aborted: TaskAbort(reason=BUG: Unhandled error in plugin sftp_list: 'utf8' codec can't decode byte 0xe9 in position 16: invalid continuation byte, silent=False)
2017-09-01 21:20 DEBUG    task_queue                    task queue shut down
2017-09-01 21:20 INFO     ipc.rpyc                      listener closed
2017-09-01 21:20 INFO     ipc.rpyc                      server has terminated
2017-09-01 21:20 DEBUG    util.simple_persistence                 Flushing simple persistence for task None to db.
2017-09-01 21:20 DEBUG    manager                       Shutting down
2017-09-01 21:20 DEBUG    manager                       Removed /home/user/.config/flexget/.config-lock
```

### Additional information:

- FlexGet version: 2.10.83
- Python version: 2.7.12/3.5.1
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Ubuntu 16.04

Not sure if this would be the same issue as #1813 since different plugins are causing it. I made sure my locale was UTF-8, but that didn't seem to help. I wasn't seeing anything about flexget not being able to handle file/directory names with non-ASCII characters, so I'm hoping that there's a solution besides having to rename everything.

**Comment by 4oo4** [comment]
Did some more digging, this appears to be an upstream issue with the paramiko library.

Per [this](https://github.com/paramiko/paramiko/issues/546#issuecomment-267007288), I'm able to patch `/usr/local/lib/python2.7/dist-packages/paramiko/py3compat.py` and get it to run `sftp_list` without crashing. Once it finishes running I'll check and make sure it doesn't omit/corrupt any of the non-ASCII file/directory names.

**Comment by liiight** [comment]
Thanks for the investigation and updating on the issue!

**Comment by 4oo4** [comment]
Not sure if it's the same issue or not, but I ran into another folder name that caused flexget to end the task prematurely and silently (no errors whatsoever in flexget.log).  I'm still using the patch from above, but interestingly somehow the directory name got corrupted:

 * "Manu Chao - Si \B351rie\ M'\351tait Cont351ee (v0) "

I'm guessing had I not applied the patch that flexget would have crashed because of the underlying issue, it would be really interesting to know why nothing got logged.
