### ISSUE TITLE
BUG: Unhandled error in plugin list_add: 'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by icebal** [Flexget/Flexget#1963]
Before opening an issue, verify:

- Is this a feature request? no
- Did you recently upgrade? no upgrade, only fresh install of latest via pip install flexget
- Are you running FlexGet as a daemon? nope, cli only, no daemon
- Did you search to see if the issue already exists? searched, specific error doesnt pop up, nor others that fall under the same error types
- Did you fill out the issue template as completely as possible? i tried :)

The issue template is here because it helps to ensure you submitted all the necessary information the first time, and allows us to more quickly review issues. Please fill it out correctly and do not ignore it, no matter how irrelevant you think it may be. Thanks in advance for your help with this!
### Expected behaviour:

pull TV series from trakt "sonarr" list and add shows to sonarr.

### Actual behaviour:
pulls TV series from list, but will error out after accepting them and did not add to sonarr
### Steps to reproduce:
- Step 1: add the "import trakt to sonarr" cookbook config
- Step 2: run flexget execute
- Step 3: ???
- Step 4: not profit, cause it errors out. would be helpful if it listed the item it was on when it errored.

#### Config:
```
tasks:
  import trakt to sonarr:
    trakt_list:
username: icebal
account: icebal
list: sonarr
type: shows
    accept_all: yes
    list_add:
- sonarr_list:
base_url: sonarr_URL_redacted
port: 443
api_key: APIKEY_REDACTED
```
  
#### Log:
```
2017-09-12 10:16 DEBUG    managerFiguring out config load paths
2017-09-12 10:16 DEBUG    managerFound config: /home/icebal/.config/flexget/config.yml
2017-09-12 10:16 DEBUG    managerConfig file /home/icebal/.config/flexget/config.yml selected
2017-09-12 10:16 VERBOSE  task_queueThere are 1 tasks to execute. Shutdown will commence when they have completed.
2017-09-12 10:16 VERBOSE  input_cache   import trakt to sonarr Restored 13 entries from db cache
2017-09-12 10:16 VERBOSE  detailsimport trakt to sonarr Produced 13 entries.
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr REJECTED: `Salvation (2017)` by seen plugin because entry with title `Salvation (2017)` is already mark
ed seen in the task import trakt to sonarr at 2017-09-11 21:34
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr REJECTED: `Tin Star (2017)` by seen plugin because entry with title `Tin Star (2017)` is already marked
 seen in the task import trakt to sonarr at 2017-09-11 21:34
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr REJECTED: `The Leftovers (2014)` by seen plugin because entry with title `The Leftovers (2014)` is alre
ady marked seen in the task import trakt to sonarr at 2017-09-11 21:34
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr REJECTED: `Wynonna Earp (2016)` by seen plugin because entry with title `Wynonna Earp (2016)` is alread
y marked seen in the task import trakt to sonarr at 2017-09-11 21:34
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr REJECTED: `Murdoch Mysteries (2008)` by seen plugin because entry with title `Murdoch Mysteries (2008)`
 is already marked seen in the task import trakt to sonarr at 2017-09-11 21:34
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr REJECTED: `12 Monkeys (2015)` by seen plugin because entry with title `12 Monkeys (2015)` is already ma
rked seen in the task import trakt to sonarr at 2017-09-11 21:34
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr REJECTED: `Justified (2010)` by seen plugin because entry with title `Justified (2010)` is already mark
ed seen in the task import trakt to sonarr at 2017-09-11 21:34
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr REJECTED: `Stan Lee's Lucky Man (2016)` by seen plugin because entry with title `Stan Lee's Lucky Man (
2016)` is already marked seen in the task import trakt to sonarr at 2017-09-11 21:34
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr ACCEPTED: `Dexter (2006)` by accept_all plugin
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr ACCEPTED: `The Gifted (2017)` by accept_all plugin
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr ACCEPTED: `Marvel's The Punisher (2017)` by accept_all plugin
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr ACCEPTED: `Rellik (2017)` by accept_all plugin
2017-09-12 10:16 VERBOSE  taskimport trakt to sonarr ACCEPTED: `Children of the Whales (2017)` by accept_all plugin
2017-09-12 10:16 VERBOSE  detailsimport trakt to sonarr Summary - Accepted: 5 (Rejected: 8 Undecided: 0 Failed: 0)
2017-09-12 10:16 VERBOSE  list_add      import trakt to sonarr adding accepted entries into sonarr_list - {'base_url': 'https://SONARR_URL/', 'port': 443, 'api
_key': 'API_REDACTED', 'include_ended': True, 'only_monitored': True, 'include_data': False}
2017-09-12 10:16 CRITICAL taskimport trakt to sonarr BUG: Unhandled error in plugin list_add: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/flexget/task.py", line 486, in __run_plugin
return method(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/flexget/event.py", line 23, in __call__
return self.func(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/flexget/plugins/output/list_add.py", line 54, in on_task_output
    thelist |= task.accepted
  File "/usr/lib/python3.6/_collections_abc.py", line 606, in __ior__
    self.add(value)
  File "/usr/lib/python3.6/site-packages/flexget/plugins/list/sonarr_list.py", line 243, in add
    log.verbose('Successfully added show %s to Sonarr', show['title'])
TypeError: 'NoneType' object is not subscriptable
```
### Additional information:

- FlexGet version:2.10.89
- Python version:
Python 2.7.13
- Installation method: pip install
- Using daemon (yes/no): no
- OS and version: Arch, fully updated
- Link to crash log:

In config and debug/crash logs, remember to redact any personal or sensitive information such as passwords, API keys, private URLs and so on.

Please verify that the following data is present before submitting your issue:

- Link to a paste service or paste above the relevant config (preferably full config, including templates if present). Please make sure the paste does not expire, if possible.
- Link to a paste service or paste above debug-level logs of the relevant task/s (use `flexget -L debug execute --tasks <Task_name>`).
- FlexGet version (use `flexget -V` to get it).
- Full Python version, for example `2.7.11` (use `python -V` to get it). Note that FlexGet is not supported for use with Python v3.0, 3.1, 3.2 or 3.6.
- Installation method (pip, git install, etc).
- Whether or not you're running FlexGet as a daemon.
- OS and version.
- Attach crash log if one was generated, in addition to the debug-level log. It can be found in the directory with your config file.

**Comment by icebal** [comment]
after removing and re-adding each show, i have found it is Marvel's The Punisher (2017) that is causing the issue.

**Comment by icebal** [comment]
i was able to add Marvel's The Punisher manually to sonarr

**Comment by cvium** [comment]
> Python 2.7.13

Your logs say Python 3.6, which we do not support. Not that I think it's related to 3.6, but just fyi.

**Comment by icebal** [comment]
let me flip over to 2.7 and try it, it could very well be a 3 issue.

**Comment by liiight** [comment]
It's a 100% not a python3.6 issue, don't waste your time

**Comment by icebal** [comment]
the issue is a difference in what Trakt has, and what sonarr is pulling from tvdb. trakt has the title as Marvel's The Punisher (2017) and sonarr is getting Marvel's The Punisher from TVDB (no year in title). here is the debug log (pertinent part)

2017-09-12 12:52 DEBUG    sonarr_list   import trakt to sonarr searching for show match for <Entry(title=Marvel's The Punisher (2017),state=accepted)> using Sonarr
2017-09-12 12:52 DEBUG    sonarr_list   import trakt to sonarr Received series lookup request
2017-09-12 12:52 DEBUG    sonarr_list   import trakt to sonarr could not find series match to <Entry(title=Marvel's The Punisher (2017),state=accepted)>
2017-09-12 12:52 CRITICAL task          import trakt to sonarr BUG: Unhandled error in plugin list_add: 'NoneType' object has no attribute '__getitem__'
2017-09-12 12:52 CRITICAL manager       import trakt to sonarr An unexpected crash has occurred. Writing crash report to /home/icebal/.config/flexget/crash_report.201
7.09.12.125245358787.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flex
get.com/wiki/Plugins/version_checker. You are currently using version 2.10.89
2017-09-12 12:52 DEBUG    manager       import trakt to sonarr Traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/output/list_add.py", line 54, in on_task_output
    thelist |= task.accepted
  File "/usr/lib/python2.7/_abcoll.py", line 330, in __ior__
    self.add(value)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/list/sonarr_list.py", line 243, in add
    log.verbose('Successfully added show %s to Sonarr', show['title'])
TypeError: 'NoneType' object has no attribute '__getitem__'
