### ISSUE TITLE
Unhandled error in plugin series: can only concatenate list (not "int") to list

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#1970]
2017-09-25 05:04 VERBOSE  series        Series_Collection_DE_Stream Found different quality for `The.Fosters.**S04E14-E20**.German.DD+51.DL.1080p.AmazonHD.x264-TVS`. Was `1080p h264 dd+5.1`, overriding with$
2017-09-25 05:04 CRITICAL task          Series_Collection_DE_Stream BUG: Unhandled error in plugin series: can only concatenate list (not "int") to list
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1514, in on_task_metainfo
    self.parse_series(task.entries, series_name, series_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1640, in parse_series
    populate_entry_fields(entry, parsed, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1235, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_common.py", line 553, in pack_identifier
    return 'S%02dE%02d-E%02d' % (self.season, self.episode, self.episode + self.episodes - 1)
TypeError: can only concatenate list (not "int") to list

**Comment by liiight** [comment]
Please open a new issue and do not ignore the issue template this time
