### ISSUE TITLE
Unhandled error in lazy lookup plugin

### ISSUE THREAD

**Issue by lostsubstance** [Flexget/Flexget#1971]
python: 2.7.9
windows 10
flexget 2.10.94

```
2017-09-24 22:18 ERROR    lazy_lookup   fetch-series    Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\utils\lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "c:\python27\lib\site-packages\flexget\plugins\metainfo\thetvdb_lookup.py", line 125, in lazy_series_lookup
    return self.series_lookup(entry, language, self.series_map)
  File "c:\python27\lib\site-packages\flexget\utils\database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\metainfo\thetvdb_lookup.py", line 117, in series_lookup
    session=session
  File "c:\python27\lib\site-packages\flexget\utils\database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\internal\api_tvdb.py", line 529, in lookup_series
    _update_search_strings(series, session, search=name)
  File "c:\python27\lib\site-packages\flexget\plugins\internal\api_tvdb.py", line 476, in _update_search_strings
    search.lower()] if search else []
AttributeError: 'NoneType' object has no attribute 'lower'
```

config:
```
tasks:
  fetch-series:
    priority: 1
    disable: builtins
    trakt_list:
      username: '{? trakt.username ?}'
      account: '{? trakt.username ?}'
      list: ishows-added
      type: shows
    accept_all: yes
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    set:
      title: "{{tvdb_series_name|default(tvmaze_series_name)|default(series_name)}}"
    exec:
      # auto_escape: yes
      on_start:
        phase: del %USERPROFILE%\flexget\series.txt
      on_output:
        for_entries:
          - echo "{{title}}" >> %USERPROFILE%\flexget\series.txt
```

**Comment by lostsubstance** [comment]
i locally modified the line from the error to be:
```
search.lower()] if search and hasattr(search, 'lower') else []
```
and it got by... not sure what the non-string/not-none value of search is...

**Comment by bagobones** [comment]
I am getting this one with some frequency as well, about once a week or so. Any thing I can provide to help?

`2017-10-08 07:02 ERROR    lazy_lookup   TV_Private      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 158, in lazy_episode_lookup
    episode = lookup_episode(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 584, in lookup_episode
    series = lookup_series(name=name, tvdb_id=tvdb_id, only_cached=only_cached, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 527, in lookup_series
    updated_series = TVDBSeries(series.id, language)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 174, in __init__
    series = TVDBRequest().get('series/%s' % self.id, language=language)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 84, in get
    result = self._request('get', endpoint, **params)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 62, in _request
    headers = {'Authorization': 'Bearer %s' % self.get_auth_token(),
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_tvdb.py", line 39, in get_auth_token
    auth_token = session.query(TVDBTokens).filter(TVDBTokens.name == self.auth_key).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT tvdb_tokens.id AS tvdb_tokens_id, tvdb_tokens.name AS tvdb_tokens_name, tvdb_tokens.token AS tvdb_tokens_token, tvdb_tokens.refreshed AS tvdb_tokens_refreshed \nFROM tvdb_tokens \nWHERE tvdb_tokens.name = ?\n LIMIT ? OFFSET ?'] [parameters: (u'default', 1, 0)]
`

**Comment by liiight** [comment]
This is unrelated to the original issue
