### ISSUE TITLE
Unhandled error in plugin series: can only concatenate list (not "int") to list

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#1974]
### Steps to reproduce:
- Entries with multiple episodes: S04E14-E20 

#### Config:
```
https://github.com/crack00r/Flexget-Config/blob/master/config.yml
```
  
#### Log:
```
2017-09-25 05:04 VERBOSE series Series_Collection_DE_Stream Found different quality for The.Fosters.S04E14-E20.German.DD+51.DL.1080p.AmazonHD.x264-TVS. Was 1080p h264 dd+5.1, overriding with$
2017-09-25 05:04 CRITICAL task Series_Collection_DE_Stream BUG: Unhandled error in plugin series: can only concatenate list (not "int") to list
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
return method(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in call
return self.func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1514, in on_task_metainfo
self.parse_series(task.entries, series_name, series_config)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1640, in parse_series
populate_entry_fields(entry, parsed, config)
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1235, in populate_entry_fields
entry['series_id'] = parser.pack_identifier
File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_common.py", line 553, in pack_identifier
return 'S%02dE%02d-E%02d' % (self.season, self.episode, self.episode + self.episodes - 1)
TypeError: can only concatenate list (not "int") to list
```

### Additional information:

- FlexGet version: 2.10.94
- Python version: 2.7
- Installation method: pip, global
- Using daemon (yes/no): yes
- OS and version: ubuntu 16.04

**Comment by liiight** [comment]
A 6 ep pack, weird

**Comment by liiight** [comment]
I cant reproduce, I get `Series pack contains too many episodes (6). Rejecting` as expected.
Can you paste full task log please?

**Comment by snickers2k** [comment]
"Full Task log" .. how? :/

```
2017-10-20 14:31 VERBOSE  series        Series_Collection_DE_Stream Found different quality for `The.Last.Ship.S04E08-10.720p.AMZN.WEB-DL.DD+5.1.H.264-QOQ`. Was `720p webdl h264 dd+5.1`, overriding with `720p webdl h264`.
2017-10-20 14:31 CRITICAL task          Series_Collection_DE_Stream BUG: Unhandled error in plugin series: can only concatenate list (not "int") to list
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1516, in on_task_metainfo
    self.parse_series(task.entries, series_name, series_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1642, in parse_series
    populate_entry_fields(entry, parsed, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1237, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_common.py", line 553, in pack_identifier
    return 'S%02dE%02d-E%02d' % (self.season, self.episode, self.episode + self.episodes - 1)
TypeError: can only concatenate list (not "int") to list
```

This is the output from the .log file

**Comment by liiight** [comment]
paste the ENTIRE log, and run with `--debug` please

**Comment by topy** [comment]
```
2017-11-20 10:50 DEBUG    parser        Series_Watchlist NAME SUCCESS: ^(?:(?:\[[^\[\]]*\])|(?:HD.720p?:)|(?:HD.1080p?:)|(?:HD.2160p?:))?(?:[^\w&]|_)*(Fear(?:[^\w&]|_)*The(?:[^\w&]|_)*Walking(?:[^\w&]|_)*Dead)(?:\b|_)(?:[^\w&]|_)* matched to Fear.The.Walking.Dead.S03E14.German.1080p.WebHD.x264-AIDA
2017-11-20 10:50 DEBUG    parser_guessit Series_Watchlist Parsing series: `2.Broke.Girls.S06E17.And.The.Jessica.Shmessica.GERMAN.DUBBED.DL.720p.WebHD.x264-TVP` [options: {'identified_by': u'auto', 'name': None, 'allow_seasonless': False}]
2017-11-20 10:50 DEBUG    parser_guessit Series_Watchlist Parsing result: <GuessitParsedSerie(name=2 Broke Girls,id=17,season=6,episode=17,quality=720p webdl h264,proper=0,status=OK)> (in 16.547 ms)
2017-11-20 10:50 DEBUG    parser        Series_Watchlist NAME SUCCESS: ^(?:(?:\[[^\[\]]*\])|(?:HD.720p?:)|(?:HD.1080p?:)|(?:HD.2160p?:))?(?:[^\w&]|_)*(2(?:[^\w&]|_)*Broke(?:[^\w&]|_)*Girls)(?:\b|_)(?:[^\w&]|_)* matched to 2.Broke.Girls.S06E17.And.The.Jessica.Shmessica.GERMAN.DUBBED.DL.720p.WebHD.x264-TVP
2017-11-20 10:50 DEBUG    parser_guessit Series_Watchlist Parsing series: `Gotham.S03E21E22.GERMAN.DUBBED.DL.1080p.BluRay.x264-TVP` [options: {'identified_by': u'auto', 'name': None, 'allow_seasonless': False}]
2017-11-20 10:50 DEBUG    parser_guessit Series_Watchlist Parsing result: <GuessitParsedSerie(name=Gotham,id=[21, 22],season=3,episode=[21, 22],quality=1080p bluray h264,proper=0,status=OK)> (in 17.263 ms)
2017-11-20 10:50 CRITICAL task          Series_Watchlist BUG: Unhandled error in plugin metainfo_series: can only concatenate list (not "int") to list
Traceback (most recent call last):
  File "/home/jdownloader/flexget_py2.7/local/lib/python2.7/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/home/jdownloader/flexget_py2.7/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/jdownloader/flexget_py2.7/local/lib/python2.7/site-packages/flexget/plugins/metainfo/series.py", line 32, in on_task_metainfo
    self.guess_entry(entry)
  File "/home/jdownloader/flexget_py2.7/local/lib/python2.7/site-packages/flexget/plugins/metainfo/series.py", line 47, in guess_entry
    populate_entry_fields(entry, parsed, config)
  File "/home/jdownloader/flexget_py2.7/local/lib/python2.7/site-packages/flexget/plugins/filter/series.py", line 1307, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "/home/jdownloader/flexget_py2.7/local/lib/python2.7/site-packages/flexget/plugins/parsers/parser_common.py", line 553, in pack_identifier
    return 'S%02dE%02d-E%02d' % (self.season, self.episode, self.episode + self.episodes - 1)
TypeError: can only concatenate list (not "int") to list
```

But I upgraded guessit right before because of that:
`2017-11-19 17:03 CRITICAL task          Series_Watchlist BUG: Unhandled error in plugin metainfo_series: Series flagged invalid`

**Comment by cvium** [comment]
Any problems related to guessit will not be fixed.

**Comment by topy** [comment]
But maybe should flexget start supporting a newer version of guessit?

Passing "Gotham.S03E21E22.GERMAN.DUBBED.DL.1080p.BluRay.x264-TVP" to guessit manually, it comes up with the correct result:

```
$ guessit "Gotham.S03E21E22.GERMAN.DUBBED.DL.1080p.BluRay.x264-TVP"
For: Gotham.S03E21E22.GERMAN.DUBBED.DL.1080p.BluRay.x264-TVP
GuessIt found: {
    "title": "Gotham",
    "season": 3,
    "episode": [
        21,
        22
    ],
    "language": [
        "German",
        "Multiple languages"
    ],
    "screen_size": "1080p",
    "format": "BluRay",
    "video_codec": "h264",
    "release_group": "TVP",
    "type": "episode"
}

```

**Comment by liiight** [comment]
guessit plugin is a mess, its original developer abandoned it and no one else want to touch it. if anything, flexget will completely remove guessit

**Comment by topy** [comment]
okay, I do understand that. But the fix for that exact problem is quite easy. 

In guessit 2.0.4 (flexget version) the result of above string is:

```
GuessIt found: {
    "title": "Gotham",
    "season": 3,
    "episode": 21,
    "language": "German",
    "episode_title": "DUBBED",
    "screen_size": "1080p",
    "format": "BluRay",
    "video_codec": "h264",
    "release_group": "TVP",
    "type": "episode"
}
```

The episode is returned in a list if multiple episodes are detected. So
`return 'S%02dE%02d-E%02d' % (self.season, self.episode, self.episode + self.episodes - 1)`
just have to check if self.episode is a list or just an int.
