### ISSUE TITLE
Irc encoding - ascii

### ISSUE THREAD

**Issue by ZackEndboss** [Flexget/Flexget#1981]
Dear Flexget-Community,

first of all - nice tool.
But i have some issues with the **irc-plugin** i think

Until joining the announce channel, following occurs:
"**UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 0: ordinal not in range(128)**"
I think its the first char in the Topic: "**»**"

Until the Exception, the irc plugin crashes and retry joining the server and channel.
Any Ideas?

Hope someone could help.
Regards
Zack

Full Log-Part, Config and Infos:
https://pastebin.com/LCAuxaxi

#### Config:
```
web_server: yes
templates:
  download-it:
    myclient:...
irc:
  irc_tracker:
    tracker_file: '/config/trackers/...tracker'
    server: 'irc.dnc'
    port: 12345
    nickname: 'mynick'
    channels: ["#announce"]
    nickserv_password: 'mypw'
    passkey: 'mypasskey'
    task: get_entry
    use_ssl: True
tasks:
  get_entry:
    manual: yes
    accept_all: yes
    template: download-it
```
  
#### Log:
```
2017-10-08 23:30 INFO     irc_bot                       Joined channel #announce
2017-10-08 23:30 ERROR    irc_bot                       Unknown error occurred.
Traceback (most recent call last):
...
  File "/usr/local/lib/python2.7/dist-packages/irc_bot/irc_message.py", line 34, in __str__
    printable_arguments = printable_unicode_list(self.arguments)
  File "/usr/local/lib/python2.7/dist-packages/irc_bot/utils.py", line 7, in printable_unicode_list
    return '[{}]'.format(', '.join(str(x) for x in unicode_list))
  File "/usr/local/lib/python2.7/dist-packages/irc_bot/utils.py", line 7, in <genexpr>
    return '[{}]'.format(', '.join(str(x) for x in unicode_list))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 0: ordinal not in range(128)
2017-10-08 23:30 INFO     irc_bot                       Attempting to restart connection to (u'irc.dns', 19436) in 1 seconds.
```

#### Additional information:

Channel:
```
[23:36] * Now talking in #announce
[23:36] * Topic is '**»** Welcome to #announce «*» Enjoy your Stay «'
[23:36] * Set by .... on Mon Jan 01 01:01:01 2000
```
-----------------
 Character:
user@debian ~ % echo -e '\u00BB'
»
user@debian ~ % echo -e '\xC2\xBB'
»

**Comment by cvium** [comment]
This is a bug in irc_bot. It's not related to flexget.
