### ISSUE TITLE
Error 'str' object has no attribute 'items' (modif_torrent)

### ISSUE THREAD

**Issue by zilexa** [Flexget/Flexget#2008]
### Steps to reproduce:
- Step 1: Run a task with discover using the search plugins listed in the config below.

#### Config: https://github.com/zilexa/flexget_config/blob/master/config.yml 
relevant part:
```
##### Discover and download older episodes#
  download-series-discover:
    priority: 8
    template:
      - series
      - reject
      - torrents
      - transmission-series
      - series-metainfo
    magnets: yes
    convert_magnet:
      timeout: 120 seconds
    discover:
      release_estimations: strict
      interval: 15 minutes
      what:
        - next_series_seasons: yes
        - next_series_episodes: yes
      from:
        - piratebay:
            category: highres tv
        - limetorrents:
            category: tv
        - rarbg:
            category: [1, 18, 41, 49]
```
  
#### Log: [full crash log](https://pastebin.com/WKR3uQP8)
```
2017-11-12 19:46 DEBUG    modif_torrent download-series-discover The.series.name.S02E06.REAL.HDTV.x264-SVA[rartv] seems to be a torrent
2017-11-12 19:46 DEBUG    entry         download-series-discover trying to debug key `torrent` value threw exception: 'str' object has no attribute 'get'
2017-11-12 19:46 ERROR    modif_torrent download-series-discover 'str' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/osmc/flexget/lib/python3.4/site-packages/flexget/plugins/modify/torrent.py", line 61, in on_task_modify
    entry['torrent_info_hash'] = torrent.info_hash
  File "/home/osmc/flexget/lib/python3.4/site-packages/flexget/utils/bittorrent.py", line 297, in info_hash
    info_data = encode_dictionary(self.content['info'])
  File "/home/osmc/flexget/lib/python3.4/site-packages/flexget/utils/bittorrent.py", line 170, in encode_dictionary
    items = list(data.items())
AttributeError: 'str' object has no attribute 'items'
```

### Additional information:

- FlexGet version: 2.10.106
- Python version: 3.4
- Installation method: pip
- Using daemon (yes/no): no 
- OS and version: OSMC 2017-10 based on Debian Jessie upstream

**Comment by liiight** [comment]
I added trace level logs. Please wait for release/pull and try with `--loglevel trace`
