### ISSUE TITLE
BUG: Unhandled error in plugin discover: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by mainvoid** [Flexget/Flexget#2010]
### Expected behaviour:
Ignore unknown parameters, or better yet, only pass parameters that are supported.
Likely issue with the discover plugin rather then the api_bluray one.

### Actual behaviour:
Plugin crashed due to unsupported parameter.

### Configuration:

```
  watchlist:
    priority: 1
    trakt_list:
      username: mainlyvoid
      account: mainlyvoid
      list: watchlist
      type: movies
    accept_all: yes
    seen: local  # We don't want accepted movies on this feed to affect actual download feed
    list_add:
      - movie_list: watchlist  # you can call this whatever you want
  movies search:
    trakt_lookup: yes  # can also use imdb_lookup or tmdb_lookup
    priority: 10 # run after the movie queue fill task
    discover:
      what:
        - movie_list: watchlist
      from:
        - piratebay: yes
      release_estimations: ignore
    torrent_alive: 10 # Will reject results with less than 10 seeds
    quality: dvdrip+ # Make sure no screeners or cams are downloaded
    list_match:
      from:
        - movie_list: watchlist
```

### Steps to reproduce:
- Step 1: ...
  Movie exists in bluray.com
  Watchlist in trakt.tv

#### Log:
CLI Output:
```
2017-11-13 14:02 VERBOSE  task_queue                    There are 3 tasks to execute. Shutdown will commence when they have completed.
2017-11-13 14:02 VERBOSE  input_cache   watchlist       Restored 2 entries from db cache
2017-11-13 14:02 VERBOSE  details       watchlist       Produced 2 entries.
2017-11-13 14:02 VERBOSE  task          watchlist       REJECTED: `American Assassin (2017)` by seen plugin because entry with title `American Assassin (2017)` is already marked seen in the task watchlist at 2017-11-13 13:52
2017-11-13 14:02 VERBOSE  task          watchlist       REJECTED: `The Last Stand (2013)` by seen plugin because entry with title `The Last Stand (2013)` is already marked seen in the task watchlist at 2017-11-13 13:52
2017-11-13 14:02 VERBOSE  details       watchlist       Summary - Accepted: 0 (Rejected: 2 Undecided: 0 Failed: 0)
2017-11-13 14:02 VERBOSE  discover      movies search   Discovering 2 titles ...
2017-11-13 14:02 INFO     discover      movies search   Ignoring interval because of --discover-now
2017-11-13 14:02 VERBOSE  api_bluray    movies search   Searching from blu-ray.com `American Assassin`
2017-11-13 14:02 CRITICAL task          movies search   BUG: Unhandled error in plugin discover: __init__() got an unexpected keyword argument 'encoding'
2017-11-13 14:02 CRITICAL manager       movies search   An unexpected crash has occurred. Writing crash report to /home/anders/.flexget/crash_report.2017.11.13.140209763367.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.107
2017-11-13 14:02 WARNING  task          movies search   Aborting task (plugin: discover)
```

Crash report:
```
2017-11-13 14:02 CRITICAL task          movies search   BUG: Unhandled error in plugin discover: __init__() got an unexpected keyword argument 'encoding'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 289, in on_task_input
    entries = self.estimated(entries, estimation_mode)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 201, in estimated
    est_date = estimator.estimate(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released_movies_bluray.py", line 36, in estimate
    movie = lookup(title=movie_name, year=movie_year, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_bluray.py", line 228, in lookup
    movie = BlurayMovie(title=title, year=year)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_bluray.py", line 115, in __init__
    movie_info = get_soup(movie_info_response)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/soup.py", line 16, in get_soup
    return BeautifulSoup(obj, parser)
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 72, in feed
    doc = parser.parse(markup, **extra_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 235, in parse
    self._parse(stream, False, None, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 85, in _parse
    self.tokenizer = _tokenizer.HTMLTokenizer(stream, parser=self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/html5lib/_tokenizer.py", line 36, in __init__
    self.stream = HTMLInputStream(stream, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/html5lib/_inputstream.py", line 151, in HTMLInputStream
    return HTMLBinaryInputStream(source, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'
~```

### Additional information:

- FlexGet version: 2.10.107 && 2.10.108
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Debian 9 Stretch

**Comment by liiight** [comment]
the estimation part is really weird, this is very widely used. can you run this task with `--debug` flag please?

**Comment by mainvoid** [comment]
anders@desktop:~$ flexget execute --discover-now --debug
2017-11-15 19:05 INFO     performance                   Enabling plugin and SQLAlchemy performance debugging
2017-11-15 19:05 VERBOSE  task_queue                    There are 3 tasks to execute. Shutdown will commence when they have completed.
2017-11-15 19:05 VERBOSE  trakt_list    watchlist       Retrieving `movies` list `watchlist`
2017-11-15 19:05 VERBOSE  details       watchlist       Produced 20 entries.
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Last Stand (2013)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Thor: Ragnarok (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Baby Driver (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `A Bad Moms Christmas (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Nut Job 2: Nutty by Nature (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Batman v Superman: Dawn of Justice (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Secret Life of Pets (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Kingsman: The Secret Service (2015)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Hacksaw Ridge (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Now You See Me (2013)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Hunger Games: Catching Fire (2013)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Magnificent Seven (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Now You See Me 2 (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Hidden Figures (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Se7en (1995)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Great Wall (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Sully (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `War Dogs (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Murder on the Orient Express (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Blade Runner 2049 (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  details       watchlist       Summary - Accepted: 20 (Rejected: 0 Undecided: 0 Failed: 0)
2017-11-15 19:05 VERBOSE  list_add      watchlist       adding accepted entries into movie_list - watchlist
2017-11-15 19:05 VERBOSE  discover      movies search   Discovering 20 titles ...
2017-11-15 19:05 INFO     discover      movies search   Ignoring interval because of --discover-now
2017-11-15 19:05 VERBOSE  api_bluray    movies search   Searching from blu-ray.com `The Last Stand`
2017-11-15 19:05 CRITICAL task          movies search   BUG: Unhandled error in plugin discover: __init__() got an unexpected keyword argument 'encoding'
2017-11-15 19:05 CRITICAL manager       movies search   An unexpected crash has occurred. Writing crash report to /home/anders/crash_report.2017.11.15.190516668554.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.108
2017-11-15 19:05 WARNING  task          movies search   Aborting task (plugin: discover)
2017-11-15 19:05 VERBOSE  details       show_rss        Produced 16 entries.
[snip irrelevant task show_rss output]
2017-11-15 19:05 VERBOSE  details       show_rss        Summary - Accepted: 0 (Rejected: 16 Undecided: 0 Failed: 0)
2017-11-15 19:05 INFO     performance                   Performance results for task watchlist:
2017-11-15 19:05 INFO     performance                   seen            took 0.05 sec (20 queries)
2017-11-15 19:05 INFO     performance                   retry_failed    took 0.03 sec (20 queries)
2017-11-15 19:05 INFO     performance                   status          took 0.11 sec (3 queries)
2017-11-15 19:05 INFO     performance                   trakt_list      took 0.49 sec (24 queries)
2017-11-15 19:05 INFO     performance                   list_add        took 2.54 sec (302 queries)
2017-11-15 19:05 INFO     performance                   Performance results for task movies search:
2017-11-15 19:05 INFO     performance                   status          took 0.12 sec (3 queries)
2017-11-15 19:05 INFO     performance                   discover        took 1.40 sec (66 queries)
2017-11-15 19:05 INFO     performance                   Performance results for task show_rss:
2017-11-15 19:05 INFO     performance                   series          took 0.37 sec (58 queries)
2017-11-15 19:05 INFO     performance                   seen            took 0.06 sec (32 queries)
2017-11-15 19:05 INFO     performance                   retry_failed    took 0.02 sec (16 queries)
2017-11-15 19:05 INFO     performance                   status          took 1.04 sec (3 queries)
2017-11-15 19:05 INFO     performance                   rss             took 1.14 sec (0 queries)

And the crash log:

anders@desktop:~$ cat /home/anders/crash_report.2017.11.15.190516668554.log
2017-11-15 19:05 DEBUG    manager                       Figuring out config load paths
2017-11-15 19:05 DEBUG    manager                       Found config: /home/anders/config.yml
2017-11-15 19:05 DEBUG    manager                       Config file /home/anders/config.yml selected
2017-11-15 19:05 INFO     performance                   Enabling plugin and SQLAlchemy performance debugging
2017-11-15 19:05 VERBOSE  task_queue                    There are 3 tasks to execute. Shutdown will commence when they have completed.
2017-11-15 19:05 VERBOSE  trakt_list    watchlist       Retrieving `movies` list `watchlist`
2017-11-15 19:05 VERBOSE  details       watchlist       Produced 20 entries.
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Last Stand (2013)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Thor: Ragnarok (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Baby Driver (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `A Bad Moms Christmas (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Nut Job 2: Nutty by Nature (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Batman v Superman: Dawn of Justice (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Secret Life of Pets (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Kingsman: The Secret Service (2015)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Hacksaw Ridge (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Now You See Me (2013)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Hunger Games: Catching Fire (2013)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Magnificent Seven (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Now You See Me 2 (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Hidden Figures (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Se7en (1995)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `The Great Wall (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Sully (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `War Dogs (2016)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Murder on the Orient Express (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  task          watchlist       ACCEPTED: `Blade Runner 2049 (2017)` by accept_all plugin
2017-11-15 19:05 VERBOSE  details       watchlist       Summary - Accepted: 20 (Rejected: 0 Undecided: 0 Failed: 0)
2017-11-15 19:05 VERBOSE  list_add      watchlist       adding accepted entries into movie_list - watchlist
2017-11-15 19:05 VERBOSE  discover      movies search   Discovering 20 titles ...
2017-11-15 19:05 INFO     discover      movies search   Ignoring interval because of --discover-now
2017-11-15 19:05 VERBOSE  api_bluray    movies search   Searching from blu-ray.com `The Last Stand`
2017-11-15 19:05 CRITICAL task          movies search   BUG: Unhandled error in plugin discover: __init__() got an unexpected keyword argument 'encoding'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 289, in on_task_input
    entries = self.estimated(entries, estimation_mode)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 201, in estimated
    est_date = estimator.estimate(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/estimators/est_released_movies_bluray.py", line 36, in estimate
    movie = lookup(title=movie_name, year=movie_year, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_bluray.py", line 228, in lookup
    movie = BlurayMovie(title=title, year=year)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_bluray.py", line 115, in __init__
    movie_info = get_soup(movie_info_response)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/soup.py", line 16, in get_soup
    return BeautifulSoup(obj, parser)
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 72, in feed
    doc = parser.parse(markup, **extra_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 235, in parse
    self._parse(stream, False, None, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/html5lib/html5parser.py", line 85, in _parse
    self.tokenizer = _tokenizer.HTMLTokenizer(stream, parser=self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/html5lib/_tokenizer.py", line 36, in __init__
    self.stream = HTMLInputStream(stream, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/html5lib/_inputstream.py", line 151, in HTMLInputStream
    return HTMLBinaryInputStream(source, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by mainvoid** [comment]
And this auth stuff into trakt is deprecated too. Is this really the way that is recommended? It is the only thing I find for working through a watch list. It feels brittle.

**Comment by cvium** [comment]
What "auth stuff" is deprecated?

I can't reproduce this issue.

**Comment by mainvoid** [comment]
"flexget trakt auth -h"

usage: flexget trakt auth [-h] <account> [<pin>]

positional arguments:
  <account>   Local identifier which should be used in your config to refer
              these credentials
  <pin>       Get this by authorizing FlexGet to use your trakt account at
              https://trakt.tv/pin/346. WARNING: DEPRECATED.

**Comment by cvium** [comment]
https://flexget.com/Trakt_Authentication

**Comment by mainvoid** [comment]
So, the use of pin is deprecated. Ok. So, just figuring out the crash originally reported remaining. I've tried multiple versions and they all appear to crash on me. I've got my config and don't mind cleaning the slate if needed. Any thoughts on what to look for, ensuring everything gets tidied up? I'm particularly looking at the /usr/local/lib path and raising an eyebrow. Did I simply manage to get something confused and get multiple versions installed possibly causing some "cross contamination"?

**Comment by mainvoid** [comment]
Nope, looks like each of those are unique, and not existing in duplicate locations ...

**Comment by liiight** [comment]
This is super weird. Are you;re not using a different config? Did you restart daemon?

**Comment by mainvoid** [comment]
It is super weird. Nope, just that config on the whole system. Not running as daemon, but trigger via cron, so far. I wanted to get the config down first, so I could figure out any failures. This section is brand new for my config, with the trakt_list bit. I've previously used rss feed for TV episodes, and this movie section is completely new. The show_rss task I've had for quite some time now and worked well.

**Comment by mainvoid** [comment]
Right, finally had time to poke at this. Uninstalled and reinstalled html5lib, did no difference. However, once I uninstalled it again, and subsequently attempted a sudo pip install --upgrade Flexget it reinstalled html5lib and upgraded flexget to 2.10.108 and *now* the thing no longer blows up. Feel free to resolve! (Still, I find this odd, so so odd ...)

**Comment by liiight** [comment]
no backsies :)
