### ISSUE TITLE
Divxatope search bug

### ISSUE THREAD

**Issue by euod92** [Flexget/Flexget#2012]
### Expected behaviour:
Search in divxatope return results to dowload

### Actual behaviour:
Bug/Crash
### Steps to reproduce:
- Step 1: Search something with the divxatope plugin.

#### Config:
```
.........
tasks:  
  spanish task:
    disable:
    - retry_failed
    - seen
    - seen_info_hash
    rss: http://feeds2.feedburner.com/newpctorrent
    regexp:
      accept:
        - American horror story: {from: title}
      reject:
        - V.O.: {from: title}
    series:
      - La que se avecina:
          quality: 720p+
          propers: no
      - Modern Family:
          quality: 720p+
      - The walking dead:
          quality: 720p+
      - American horror story:
          quality: 720p+
    download: [path]
  subtitulado task:
    disable:
    - retry_failed
    - seen
    - seen_info_hash
    rss: http://feeds2.feedburner.com/newpctorrent
    series:
      - American horror story:
          quality: 720p+
    download: [path]
  paradescargaspanishname_movie_list:
    priority: 1
    imdb_watchlist:
      user_id: id
      list: list
      force_language: es-es # Optional - Force Specified Language
    accept_all: yes
    list_add:
      - movie_list: imdb_movies
    notify:
      task:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]
      abort:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]
`bajar_pelis_spainname:
    priority: 10
    disable:
      - seen
    discover:
      interval: 1000 minutes
      what:
        - movie_list: 
            list_name: imdb_movies
            strip_year: yes
#        - emit_movie_queue: yes
      from:
        - divxatope: yes
        - newpct: yes
#        - limetorrents: yes
#        - elitetorrent: yes
#            category: all
#        - torrentdownloadws: true
#        - kat: yes
#            category: movies
#            verified: no
        - piratebay:
            category: video
            sort_by: default
#        - torrentz: verified
#      interval: 1 hours
      release_estimations:
        optimistic: 7 days
    imdb_lookup: yes
    tmdb_lookup: yes
#    trakt_lookup: yes
    quality:
      1080p+
      remux|bluray
    content_size:
      min: 5000
    set:
      path: [path]
    download: [path]
#      - proxyy
    list_match:
      from:
        - movie_list: imdb_movies
    regexp:
      reject:
        - 'sub[s][\s\._]'
        - dublado
        - Dublado
        - DUBLADO
        - '[Ll]atino'
        - '[Ss]creener'
        - '[Ss]creener':
            from: url
        - Screeener
        - Screeener:
            from: url
        - 3D
      from: title
    notify:
      task:
        via:
          - telegram:
              bot_token:  [token]
              parse_mode: markdown
            #parse_mode: html
              recipients:
                - username: [username]
      abort:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]`
```
  
```
  
#### Log:
### DIVXATOPE:
`
`2017-11-13 18:26 CRITICAL task bajar_pelis_spainname BUG: Unhandled error in plugin discover: unsupported operand type(s) for +: 'Tag' and 'unicode'
2017-11-13 18:26 CRITICAL manager bajar_pelis_spainname An unexpected crash has occurred.`

##Crash log:
2017-11-13 18:26 VERBOSE discover bajar_pelis_spainname Searching for [movie_name] with plugin divxatope (1 of 6)
2017-11-13 18:26 CRITICAL task bajar_pelis_spainname BUG: Unhandled error in plugin discover: unsupported operand type(s) for +: 'Tag' and 'unicode'
Traceback (most recent call last):
File "c:\python27\lib\site-packages\flexget\task.py", line 486, in _runplugin
return method(*args, **kwargs)
File "c:\python27\lib\site-packages\flexget\event.py", line 23, in call
return self.func(*args, **kwargs)
File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 290, in on_task_input
return self.execute_searches(config, entries, task)
File "c:\python27\lib\site-packages\flexget\plugins\input\discover.py", line 155, in execute_searches
search_results = search.search(task=task, entry=entry, config=plugin_config)
File "c:\python27\lib\site-packages\flexget\plugins\sites\divxatope.py", line 104, in search
entry['title'] = entry_title + ' ' + entry_quality_lan
TypeError: unsupported operand type(s) for +: 'Tag' and 'unicode'`
```

### Additional information:

- FlexGet version: *2.10.109
- Python version: *2.7.14
- Using daemon (yes/no): no
- OS and version: W7

**Comment by paranoidi** [comment]
Domain inaccessible
