### ISSUE TITLE
APScheduler crashing at regularly irregular intervals

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#2025]
APScheduler keeps crashing with the following message. It doesn't do it every run, or even every day. But at least once a week I need to manually restart the flexget daemon to get everything running again.

#### Log:
```
Exception in thread APScheduler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 30, in _main_loop
    wait_seconds = self._process_jobs()
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 979, in _process_jobs
    jobstore.update_job(job)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 101, in update_job
    result = self.engine.execute(update)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2064, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1209, in _execute_context
    self._root._commit_impl(autocommit=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 726, in _commit_impl
    self.connection._reset_agent is self.__transaction:
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 351, in connection
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 349, in connection
    return self._revalidate_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 429, in _revalidate_connection
    raise exc.ResourceClosedError("This Connection is closed")
ResourceClosedError: This Connection is closed
```

### Additional information:

- FlexGet version: 2.11.4
- Python version: 2.7.12
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu 16.04.3 LTS

**Comment by cvium** [comment]
If someone can reproduce this consistently, it'd be a huge help. I have been unable to.

**Comment by lepinkainen** [comment]
This is 100% a race condition of some sort, but the regularity of its irregularity is baffling.

There really is no pattern to it, at least one that I can determine.
