### ISSUE TITLE
Unhandled error in plugin transmission

### ISSUE THREAD

**Issue by viggy96** [Flexget/Flexget#2055]
### Expected behaviour:
Flexget adds torrent to transmission and starts it.

### Actual behaviour:
Torrent is added, but is not started.

### Steps to reproduce:
Run flexget.

#### Config:
https://pastebin.com/Caj8pVTM
  
#### Log:
```
2018-01-05 13:05 INFO     download      nyaa            Downloading: Yuru Camp - 01 (1280x720 HEVC2 AAC).mkv
2018-01-05 13:05 INFO     download      nyaa            Downloading: Ramen Daisuki Koizumi-san - 01 (1280x720 HEVC2 AAC).mkv
2018-01-05 13:05 INFO     transmission  nyaa            "Yuru Camp - 01 (1280x720 HEVC2 AAC).mkv" torrent added to transmission
2018-01-05 13:05 CRITICAL task          nyaa            BUG: Unhandled error in plugin transmission: 'ascii' codec can't decode byte 0xe2 in position 35: ordinal not in range(128)
2018-01-05 13:05 CRITICAL manager       nyaa            An unexpected crash has occurred. Writing crash report to /home/box/.config/flexget/crash_report.2018.01.05.130509236016.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.11.20
2018-01-05 13:05 WARNING  task          nyaa            Aborting task (plugin: transmission)

```
```
2018-01-05 13:05 DEBUG    manager                       Figuring out config load paths
2018-01-05 13:05 DEBUG    manager                       Found config: /home/box/.config/flexget/config.yml
2018-01-05 13:05 DEBUG    manager                       Config file /home/box/.config/flexget/config.yml selected
2018-01-05 13:05 INFO     download      nyaa            Downloading: Yuru Camp - 01 (1280x720 HEVC2 AAC).mkv
2018-01-05 13:05 INFO     download      nyaa            Downloading: Ramen Daisuki Koizumi-san - 01 (1280x720 HEVC2 AAC).mkv
2018-01-05 13:05 INFO     transmission  nyaa            "Yuru Camp - 01 (1280x720 HEVC2 AAC).mkv" torrent added to transmission
2018-01-05 13:05 CRITICAL task          nyaa            BUG: Unhandled error in plugin transmission: 'ascii' codec can't decode byte 0xe2 in position 35: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/transmission.py", line 303, in on_task_output
    self.add_to_transmission(self.client, task, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/transmission.py", line 528, in add_to_transmission
    file_path = os.path.dirname(os.path.join(download_dir, fl[r.id][main_id]['name']))
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 35: ordinal not in range(128)
```
### Additional information:

- FlexGet version: 2.11.20
- Python version: 2.7.12
- Installation method: pip, global
- Using daemon (yes/no): no
- OS and version: Ubuntu Server 16.04.3
- Link to crash log: https://pastebin.com/ZdQLuJus

**Comment by viggy96** [comment]
I have found a way to mitigate the ascii error the transmission plugin throws, by adding some code to remove non-ascii characters in the transmission plugin's python file.

First, define the function:
```
def remove_non_ascii(text):
    return re.sub(r'[^\x00-\x7F]',' ', text)
```

Then edit line 530 as follows:
```
file_path = os.path.dirname(os.path.join(remove_non_ascii(download_dir), remove_non_ascii(fl[r.id][main_id]['name'])))
```

I have not been able to find a repository that is specific to the transmission plugin, so I am posting this here.

This solves the problem of the transmission plugin crashing upon encountering non-ascii characters.

**Comment by rinslee** [comment]
Thanks, was running into same issue, with the same show :)

**Comment by viggy96** [comment]
You're welcome. Glad it helped.

**Comment by plittlefield** [comment]
Same bug for me too.

Just changed install to the new virtualenv for Python3.

Pastbin below.

Thanks!

**Additional information:**
FlexGet version: 2.21.16
Python version: 3.5.2
Installation method: pip, virtualenv
Using daemon (yes/no): yes
OS and version: Ubuntu Server 16.04.6
Link to crash log: https://pastebin.com/hAM7Mf2y

**Comment by plittlefield** [comment]
I've just run it again after an update and I still get the same error...

`BUG: Unhandled error in plugin transmission: name 'TransmissionError' is not defined`

...so, FlexGet is effectively USELESS at this point.

Oh well.

**Comment by cvium** [comment]
You should READ the DOCUMENTATION, https://flexget.com/Plugins/transmission. It looks like transmissionrpc isn't installed in that virtualenv.

**Comment by plittlefield** [comment]
Alas, it is...

https://pastebin.com/fKs4bgvZ

...next.

;-)

Paully

**Comment by cvium** [comment]
`transmission` is not what you think it is.

Given that `transmissionrpc` is installed, I'm fairly certain this is a matter better suited for the forums as I don't think it's a bug -- and even if it is, this issue is definitely the wrong place.

Did you stop and start the Flexget daemon after installing `transmissionrpc` (if it was running)?

**Comment by plittlefield** [comment]
I now have it working.

* back up ~/.flexget/ config and database folder
* uninstall FlexGet Python 3 virtual environment
* uninstall FlexGet Python 2
* reinstall FlexGet Python 3 virtual environment + transmissionrpc
* reboot computer
* start FlexGet as daemon
* run tasks with --test
* run tasks without --test

Yay! It connects to Transmission and successfully adds torrent magnets.

Regards,

Paul

**Comment by paranoidi** [comment]
> You should READ the DOCUMENTATION, https://flexget.com/Plugins/transmission. It looks like transmissionrpc isn't installed in that virtualenv.

Although, using a plugin without required dependencies should never crash in this way ..

**Comment by plittlefield** [comment]
I can confirm that this issue is fixed for me. Thanks for everyone's input.

**Comment by gazpachoking** [comment]
Thinking this may be solved by our new transmission-rpc library.
