### ISSUE TITLE
Unicode error in daemon ipc

### ISSUE THREAD

**Issue by mb5** [Flexget/Flexget#2077]
The daemon IPC occasionally throws a unicode error when writing to the ipc buffer:

```
Traceback (most recent call last):
  File "/opt/flexget/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
  File "/opt/flexget/lib/python2.7/site-packages/flexget/ipc.py", line 44, in write
    self.buffer += text
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 73: ordinal not in range(128)
Logged from file logger.py, line 133
```

Flexget 2.12.0 on python 2.7

I'm willing to bet the same error will also pop up in `RemoteStream.flush()`

**Comment by gazpachoking** [comment]
Shouldn't be an issue in python 3 anymore
