### ISSUE TITLE
Can't start flexget on an Asuswrt Router

### ISSUE THREAD

**Issue by mundodisco8** [Flexget/Flexget#2103]
### Expected behaviour:
I've been running flexget for years in this router. I normally don't update it because that breaks things, but I recently updated my router, and it required an entware reinstall, so I reinstalled flexget too. At first I was presented with memoryErrors, but I managed to avoid them by activating a swap file. Still, can't run flexget.
I expect that running 'flexget execute' parses an RSS source for series and sends them to transmission

### Actual behaviour:
I get an error

### Steps to reproduce:
Fresh install of flexget

#### Config:
My config file starts with a comment to remind me that I don't have to do changes on a certain location as it will be deleted on restart. My transmission password is a string with spaces in it, something like "password with spaces". This file has been working for years on a previous version of Flexget, so I know it's OK, but I also understand that plugins change with time and it might be outdated. I also tried commenting areas like the web server, or the transmission bit, but nothing worked, still the same error.
```
# I will move this file to home on boot. Remember to edit the original
# located at /mnt/Router_Stuff/scripts/.flexget
# Cron will make copies back to the hard drive on each run to update
# databases and stuff.

parser:
  series: internal
tasks:
  SeriesTask:
    rss: http://showrss.info/user/77890.rss?magnets=true&namespaces=true&name=null&quality=anyhd&re=null
    all_series:
      path: /mnt/Router_Stuff/Torrent/Series/{{series_name}}
    transmission:
      host: localhost
      port: 9091
      username: MyRealUsername
      password: MyRealPassword
web_server:
  run_v2: true
```
  
#### Log:
```
(flexget) Joel@RT-AC56U:/tmp/mnt/Router_Stuff/swap# flexget -c ~/.flexget/config.yml execute
Traceback (most recent call last):
  File "/tmp/mnt/Router_Stuff/flexget/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/manager.py", line 330, in start
    self.initialize()
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/manager.py", line 217, in initialize
    fire_event('manager.startup', self)
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/event.py", line 106, in fire_event
    result = event(*args, **kwargs)
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/utils/simple_persistence.py", line 183, in load_taskless
    SimplePersistence.load()
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/utils/simple_persistence.py", line 145, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/utils/database.py", line 141, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/utils/json.py", line 112, in loads
    return json.loads(*args, **kwargs)
  File "/opt/lib/python2.7/json/__init__.py", line 352, in loads
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/utils/json.py", line 48, in decode
    return super(DTDecoder, self).decode(obj, **kwargs)
  File "/opt/lib/python2.7/json/decoder.py", line 364, in decode
TypeError: expected string or buffer
```

### Additional information:
Some commands work, like `flexget -V`, which returns the latest version, `flexget --help`, that prints the help or `flexget check` IF AND ONLY IF the config file is bad (if it's valid, it prints the same error).

- FlexGet version: latest, 2.13.6
- Python version: 2.7.14
- Installation method: described in this post in the forums (https://discuss.flexget.com/t/solved-cant-install-on-asuswrt-384-3/4043/3). Running on a virtualenv stored in an external HDD.
- Using daemon (yes/no): can't run as a daemon
- OS and version: Merlin's asuswrt 384. on an Asus RT-AC56U. 
 Running on a virtualenv stored in an external HDD.
- Link to crash log: 
```
2018-03-16 12:38 CRITICAL plugin                        Exception while loading plugin flexget.plugins.parsers.parser_guessit
Traceback (most recent call last):
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/plugin.py", line 396, in _load_plugins_from_dirs
    __import__(module_name)
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/flexget/plugins/parsers/parser_guessit.py", line 10, in <module>
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/guessit/__init__.py", line 6, in <module>
    from .api import guessit, GuessItApi
  File "/tmp/mnt/Router_Stuff/flexget/lib/python2.7/site-packages/guessit/api.py", line 151, in <module>
    default_api = GuessItAp2018-03-16 13:43 VERBOSE  check                         Pre-checked 19 configuration lines
2018-03-16 13:43 CRITICAL manager                       [/] The key `parser` is not valid here.
2018-03-16 13:43 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
2018-03-16 13:43 VERBOSE  check                         Pre-checked 17 configuration lines
2018-03-16 14:09 VERBOSE  check                         Pre-checked 17 configuration lines
2018-03-16 14:10 VERBOSE  check                         Pre-checked 17 configuration lines
2018-03-16 14:26 VERBOSE  check                         Pre-checked 17 configuration lines
```

**Comment by cvium** [comment]
I'm not exactly sure which error you're reporting here. The crash log you've included shows your config is invalid.

**Comment by mundodisco8** [comment]
The crash error was due to an invalid file, but as I said in my report, when the config file is invalid, flexget doesn't return any errors. When my config file is correct, as from 14h09 and onwards, I don't get any crash reports, but the error is like the one on my report: typeError expectedstring or buffer. That happens with `flexget execute`, but also with `flexget check` with a valid config file like the one I pasted and also with `flexget --help`

**Comment by mundodisco8** [comment]
Deleting all the sqlite files in the directory where my config is fixes it, though! THANKS!

**Comment by cvium** [comment]
Seems similar to #2031.
