### ISSUE TITLE
BUG: Unhandled error in plugin series: expected string or buffer

### ISSUE THREAD

**Issue by Tince1973** [Flexget/Flexget#2116]
i have just upgraded to latest version 2.13.7 and flexget now fails to run:
"BUG: Unhandled error in plugin series: expected string or buffer"

# /usr/local/bin/flexget --debug execute
(…)
2018-04-08 23:30 CRITICAL task          tv              BUG: Unhandled error in plugin series: expected string or buffer
2018-04-08 23:30 CRITICAL manager       tv              An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2018.04.08.233037564185.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.13.7
2018-04-08 23:30 DEBUG    manager       tv              Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1710, in on_task_filter
    quality=entry.get('quality'))
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 985, in store_parser
    filter(table.quality == quality). \
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/hybrid.py", line 867, in __get__
    return self._expr_comparator(owner)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/hybrid.py", line 1066, in expr_comparator
    owner, self.__name__, self, comparator(owner),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/hybrid.py", line 1055, in _expr
    return ExprComparator(cls, expr(cls), self)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 182, in getter
    return qualities.Quality(getattr(self, text_attr))
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/qualities.py", line 211, in __init__
    self.parse(text)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/qualities.py", line 225, in parse
    self.resolution = self._find_best(_resolutions, _UNKNOWNS['resolution'], False)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/qualities.py", line 241, in _find_best
    match = item.matches(search_in)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/qualities.py", line 45, in matches
    match = self.regexp.search(text)
TypeError: expected string or buffer
2018-04-08 23:30 WARNING  task          tv              Aborting task (plugin: series)
(…)

**Comment by Tince1973** [comment]
Related:
- https://github.com/Flexget/Flexget/issues/2058
- https://discuss.flexget.com/t/error-with-current-install/4038/2
- https://discuss.flexget.com/t/bug-with-recent-updates/3998

Fix:
- Downgrade to SQLAlchemy 1.1.14 https://github.com/Flexget/Flexget/issues/2058#issuecomment-359655289
