### ISSUE TITLE
support of guessit 3.0 and python-dateutil 2.7.3

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2160]
### Expected behaviour:
flexget 2.14.x to support guessit 3.0

### Actual behaviour:
```
flexget 2.14.1 has requirement guessit==2.1.4, but you'll have guessit 3.0.0 which is incompatible.
flexget 2.14.1 has requirement python-dateutil==2.6.1, but you'll have python-dateutil 2.7.3 which is incompatible.
```

### Steps to reproduce:
- Install newest flexget with guessit 3.0  and python-dateutil 2.7.3

### Logs:
```
2018-06-27 21:53 DEBUG    manager                       Figuring out config load paths
2018-06-27 21:53 DEBUG    manager                       Found config: /home/snikay/.flexget/config.yml
2018-06-27 21:53 DEBUG    manager                       Config file /home/snikay/.flexget/config.yml selected
2018-06-27 21:53 DEBUG    manager                       sys.defaultencoding: ascii
2018-06-27 21:53 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2018-06-27 21:53 DEBUG    manager                       flexget detected io encoding: utf-8
2018-06-27 21:53 DEBUG    manager                       os.path.supports_unicode_filenames: False
2018-06-27 21:53 DEBUG    plugin                        Trying to load plugins from: [u'/home/snikay/.flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2018-06-27 21:53 DEBUG    plugin                        (u'Plugin `%s` requires `%s` to load.', u'memusage', u'ext lib `guppy`')
2018-06-27 21:53 CRITICAL plugin                        Exception while loading plugin flexget.plugins.parsers.parser_guessit
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 396, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_guessit.py", line 38, in <module>
    guessit_api = GuessItApi(rebulk_builder().rebulk(_id_regexps))
TypeError: rebulk_builder() takes exactly 1 argument (0 given)
2018-06-27 21:53 DEBUG    manager                       Removed /home/snikay/.flexget/.config-lock
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 330, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 189, in initialize
    plugin.load_plugins(extra_dirs=[os.path.join(self.config_base, 'plugins')])
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 458, in load_plugins
    _load_plugins_from_dirs(extra_dirs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 396, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_guessit.py", line 38, in <module>
    guessit_api = GuessItApi(rebulk_builder().rebulk(_id_regexps))
TypeError: rebulk_builder() takes exactly 1 argument (0 given)
```

thanks

**Comment by snickers2k** [comment]
yeah i did that too. but as a result:

```
Installing collected packages: python-dateutil, guessit, flexget
  Found existing installation: python-dateutil 2.7.3
    Uninstalling python-dateutil-2.7.3:
      Successfully uninstalled python-dateutil-2.7.3
  Found existing installation: guessit 3.0.0
    Uninstalling guessit-3.0.0:
      Successfully uninstalled guessit-3.0.0
  Running setup.py install for guessit ... done
Successfully installed flexget-2.14.2 guessit-2.1.4 python-dateutil-2.6.1
```

So the request still stands: please support guessit 3.0 and dateutil 2.7.3

**Comment by justaddthc** [comment]
Running a check on Flexget on my system shows it wanting the older versions but playing just fine with the current ones.
`batman@storage:~$ pip check flexget
FlexGet 2.14.2 has requirement urllib3==1.21.1, but you have urllib3 1.23.
FlexGet 2.14.2 has requirement certifi==2017.4.17, but you have certifi 2018.4.16.
FlexGet 2.14.2 has requirement requests==2.16.5, but you have requests 2.19.1.
FlexGet 2.14.2 has requirement chardet==3.0.3, but you have chardet 3.0.4.
FlexGet 2.14.2 has requirement idna==2.5, but you have idna 2.7.
FlexGet 2.14.2 has requirement pytz==2017.2, but you have pytz 2018.5.
FlexGet 2.14.2 has requirement six==1.10.0, but you have six 1.11.0.
FlexGet 2.14.2 has requirement guessit==2.1.4, but you have guessit 3.0.0.
FlexGet 2.14.2 has requirement python-dateutil==2.6.1, but you have python-dateutil 2.7.3.
`

**Comment by paranoidi** [comment]
Library versions are pinned specifically in order to avoid these type of crashes and issues. This is not a bug, you're taking the risk if running any other versions than what we have specified. Please see into using virtualenv (which is officially recommended way to install) if you are running into problem that some python applications have conflicting requirements. We will update dependencies at some point.

**Comment by mfonville** [comment]
I do think that it might be a good idea to look at what has changed in the new guessit API and update flexget for it. To be able to take advantage of the improvements found in their new releases.

**Comment by cvium** [comment]
That's a feature request though. You're more than welcome to take a crack at it.
