### ISSUE TITLE
lazy lookup plugin crashes: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mfonville** [Flexget/Flexget#2161]
Not sure if caused by same error as #2159 

### Expected behaviour:
I expect the NPO-Watchlist plugin to download the latest Dutch episodes, and to match the series it finds with TVDB and Trakt.

### Actual behaviour:
After downloading the NPO-Watchlist episodes, before downloading the actual series, the `lazy_lookup` gives an error.

#### Config:
```
tasks:
  Series-NPO:
    npo_watchlist:
      email: 'xxxxxxxx'
      password: 'xxxxxxxxx'
      max_episode_age_days: 1
    plugin_priority:
      thetvdb_lookup: 500
      trakt_lookup: 250
    thetvdb_lookup: yes
    trakt_lookup:
      account: xxxxxxxxxx
      username: xxxxxxxxxxx
    accept_all: yes
    exec:
      fail_entries: yes
      auto_escape: yes
      on_output:
        for_accepted:
          - download-npo -s -o "/home/maarten/Series/{{trakt_series_name|default(series_name_plain)}}" -f "{serie_titel} - {datum} {aflevering_titel}.{{tvdb_ep_id|default('S00E00')}}" -t {{url}}
```

#### Log:
```
2018-06-29 02:34 VERBOSE  details       Series-NPO      Produced 1 entries.
2018-06-29 02:34 VERBOSE  task          Series-NPO      ACCEPTED: `Mensen, goden en technologie (VPWON_1276338)` by accept_all plugin
2018-06-29 02:34 VERBOSE  details       Series-NPO      Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2018-06-29 02:34 VERBOSE  api_trakt     Series-NPO      Received 88 records from trakt.tv for user xxxxxxxxxxxx from endpoint ratings/shows
2018-06-29 02:34 WARNING  api_trakt     Series-NPO      No collection data returned from trakt endpoint collection/shows.
2018-06-29 02:34 ERROR    lazy_lookup   Series-NPO      Unhandled error in lazy lookup plugin: 'NoneType' object is not iterable
2018-06-29 02:34 CRITICAL manager       Series-NPO      An unexpected crash has occurred. Writing crash report to /home/maarten/.flexget/crash_report.2018.06.29.023454977950.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.14.1
2018-06-29 02:34 VERBOSE  api_trakt     Series-NPO      Received 103 records from trakt.tv for user xxxxxxxxxxx from endpoint watched/shows
2018-06-29 02:35 VERBOSE  exec          Series-NPO      Executing: download-npo -s -o "/home/maarten/Series/Backlight" -f "{serie_titel} - {datum} {aflevering_titel}.S00E00" -t https://www.npostart.nl/vpro-tegenlicht/28-06-2018/VPWON_1276338
```

Detailed log
```
2018-06-29 02:34 VERBOSE  details       Series-NPO      Produced 1 entries.
2018-06-29 02:34 VERBOSE  task          Series-NPO      ACCEPTED: `Mensen, goden en technologie (VPWON_1276338)` by accept_all plugin
2018-06-29 02:34 VERBOSE  details       Series-NPO      Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2018-06-29 02:34 VERBOSE  api_trakt     Series-NPO      Received 88 records from trakt.tv for user xxxxxxxxxxxxx from endpoint ratings/shows
2018-06-29 02:34 WARNING  api_trakt     Series-NPO      No collection data returned from trakt endpoint collection/shows.
2018-06-29 02:34 ERROR    lazy_lookup   Series-NPO      Unhandled error in lazy lookup plugin: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 37, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/trakt_lookup.py", line 50, in __call__
    result = self.lookup_function(data_type=self.data_type, media_type=self.media_type, entry=entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/trakt_lookup.py", line 314, in _lazy_user_data_lookup
    return user_data_lookup(lookup(entry, session), entry['title'])
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_trakt.py", line 1242, in is_show_in_collection
    cache = user_cache.get_shows_collection(self.username, account=self.account)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_trakt.py", line 1103, in get_shows_collection
    return self._get_data('collection', 'shows', username=username, account=account)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_trakt.py", line 1094, in _get_data
    self.updaters[data_type](cache, media_type, username=username, account=account)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/internal/api_trakt.py", line 1064, in _update_collection_cache
    for media in collection:
TypeError: 'NoneType' object is not iterable
```

### Additional information:

- FlexGet version: 2.14.1
- Python version: Python 2.7.15rc1
- Installation method: pip

**Comment by mfonville** [comment]
I think, I might have spotted the root of the problem.
On trakt, I do not track any episodes/movies as 'collected'.
So `collection` might be empty, apparently resulting it in it being a `None`-object. Because there is an empty return statement: https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/internal/api_trakt.py#L1007

I think that the easiest fix (also for all other similar methods) is letting line 1007 return an empty list instead of None.
