### ISSUE TITLE
Flexget is incompatible with python 3.7

### ISSUE THREAD

**Issue by bertptrs** [Flexget/Flexget#2189]
### Expected behaviour:

I run `flexget --cron execute`, and it does its job and exits silently. It however fails to start because of a dependency error.

### Actual behaviour:

The program crashes during the import phase, since a dependency, `rpyc`, uses a newly reserved word in Python 3.7.

The actual fix is simple: bump the `rpyc` requirement to at least 4.0.0. In my own set-up, this appeared to fix it, but it did complain about package versions. It might be that some plugins do suffer, my config isn't that special.

### Steps to reproduce:
- Step 1: Run flexget with Python 3.7
- Stop 2: Observe crash

#### Config:
Config isn't relevant to this issue, running Python 3.7 is. Either way:
```
tasks:
    Arch Linux ISOs:
        rss: https://www.archlinux.org/feeds/releases/
        accept_all: yes
        transmission: SECRET CONFIG

schedules:
        - tasks: '*'
          interval:
                  hours: 1
```
  
#### Log:
```
Traceback (most recent call last):
  File "/var/lib/flexget/.local/bin/flexget", line 7, in <module>
    from flexget import main
  File "/var/lib/flexget/.local/lib/python3.7/site-packages/flexget/__init__.py", line 12, in <module>                                                                                          
    from flexget.manager import Manager
  File "/var/lib/flexget/.local/lib/python3.7/site-packages/flexget/manager.py", line 38, in <module>                                                                                           
    from flexget.ipc import IPCClient, IPCServer  # noqa
  File "/var/lib/flexget/.local/lib/python3.7/site-packages/flexget/ipc.py", line 10, in <module>                                                                                               
    import rpyc
  File "/var/lib/flexget/.local/lib/python3.7/site-packages/rpyc/__init__.py", line 50
    from rpyc.utils.helpers import async, timed, buffiter, BgServingThread, restricted
                                       ^
SyntaxError: invalid syntax
```

### Additional information:

- FlexGet version: 2.14.15
- Python version: 3.7.0
- Installation method: `pip install --user`
- Using daemon (yes/no): no
- OS and version: Arch Linux ARM

**Comment by arcresu** [comment]
This corresponds to tomerfiliba/rpyc#253

**Comment by pR0Ps** [comment]
Another issue with 3.7 is `PyYAML==3.12` not building. According to https://github.com/yaml/pyyaml/issues/126 where the bug was reported, v3.13 fixes this issue.

**Comment by liiight** [comment]
We need to add 3.7 tests to circleci
