### ISSUE TITLE
BUG: Unhandled error in plugin letterboxd

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#2213]
### Expected behaviour:
All the movies from a letterboxd list are mirrored on a trakt list.

### Actual behaviour:
Some movies are fetched from the letterboxd list and then an error occour.

### Steps to reproduce:
Simply run the task a few times

#### Config:
The full congif is here: https://github.com/effemmeffe/flexget/blob/master/config.yml

The task that fails is this:

```
  letterboxd-to-trakt:
    disable: seen
    letterboxd:
      username: "{? letterboxd.user ?}"
      list: $LETTERBOXD-LIST
    sort_by: added
    accept_all: yes
    list_add:
      - trakt_list:
          account: "{? trakt.account ?}"
          username: "{? trakt.user ?}"
          list: $TRAKT-LIST

```  
#### Log:
<details>
 <summary>Log (click to expand)</summary>

```
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/summer-1993/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt no tmdb configuration in memory, checking cache
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt no config cached or config expired, refreshing
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL https://api.themoviedb.org/3/configuration with args () and kwargs {u'allow_redirects': True, 'params': {u'api_key': u'bdfc018dbdb7c243dc7cb1454ff74b95'}, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=438634, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Summer 1993 information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/short-term-12-2013/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=169813, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Short Term 12 information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/big-fish/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=587, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Big Fish information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/hunt-for-the-wilderpeople/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=371645, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Hunt for the Wilderpeople information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/the-fall/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=14784, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie The Fall information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/boyhood/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=85350, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Boyhood information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/eternal-sunshine-of-the-spotless-mind/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=38, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Eternal Sunshine of the Spotless Mind information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/la-la-land/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=313369, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie La La Land information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/lean-on-pete/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=407890, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Lean on Pete information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/manchester-by-the-sea/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=334541, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Manchester by the Sea information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/the-place-beyond-the-pines/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=97367, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie The Place Beyond the Pines information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/the-perks-of-being-a-wallflower/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=84892, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie The Perks of Being a Wallflower information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/room-2015/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=264644, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Room information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/sing-street/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=369557, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Sing Street information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/captain-fantastic/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Looking up TMDb information for <title=None, year=None, tmdb_id=334533, imdb_id=None>
2018-10-04 11:39 DEBUG    api_tmdb      letterboxd-to-trakt Movie Captain Fantastic information restored from cache.
2018-10-04 11:39 DEBUG    utils.requests letterboxd-to-trakt GETing URL http://letterboxd.com/film/tully-2018/ with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2018-10-04 11:39 CRITICAL task          letterboxd-to-trakt BUG: Unhandled error in plugin letterboxd: Exceeded 30 redirects.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 148, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/letterboxd.py", line 132, in on_task_input
    entry = self.parse_film(film, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/letterboxd.py", line 95, in parse_film
    soup = get_soup(requests.get(url).content)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 536, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/requests.py", line 241, in request
    result = super(Session, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 523, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 138, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
TooManyRedirects: Exceeded 30 redirects.
```
</details>
https://pastebin.com/6mTFJRGg

### Additional information:

- FlexGet version:
2.14.25

- Python version:
Python 2.7.15rc1

- Installation method:
pip

- Using daemon (yes/no):
yes

- OS and version:
Ubuntu 18.04.1 LTS

**Comment by paranoidi** [comment]
We need the traceback / crashreport

**Comment by effemmeffe** [comment]
I slightly changed my config, but one task still fails:

```
  letterboxd-comedy: # task
    priority: 191
    disable: seen

    letterboxd:
      username: "{? letterboxd.user ?}"
      list: netflix-stand-up-comedy
    sort_by: added
    accept_all: yes
    list_add:
      - trakt_list:
          account: "{? trakt.account ?}"
          username: "{? trakt.user ?}"
          list: netflix-stand-up-comedy

```
```
fmf@kodi:~/.flexget$ cat flexget.log
2021-05-05 08:04:20 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2021-05-05 08:04:20 VERBOSE  letterboxd    letterboxd-comedy Looking for films in Letterboxd list: http://letterboxd.com/effemmeffe/list/netflix-stand-up-comedy/
2021-05-05 08:05:01 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
2021-05-05 08:05:01 CRITICAL manager                       An unexpected crash has occurred. Writing crash report to /home/fmf/.flexget/crash_report.2021.05.05.080501899110.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.117

```

```
fmf@kodi:~/.flexget$ cat crash_report.2021.05.05.080501899110.log
2021-05-05 08:04:19 DEBUG    manager                       New config data loaded.
2021-05-05 08:04:20 DEBUG    schema                        updating flexget version 3.1.117 in db
2021-05-05 08:04:20 DEBUG    parsing                       setting default movie parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7fa5fc409520>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7fa5fc4096a0>})
2021-05-05 08:04:20 DEBUG    parsing                       setting default series parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7fa5fc409520>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7fa5fc4096a0>})
2021-05-05 08:04:20 DEBUG    cron_env                      Encoding utf-8 stored
2021-05-05 08:04:20 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'utf-8'
2021-05-05 08:04:20 DEBUG    task_queue                    task queue shutdown requested
2021-05-05 08:04:20 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2021-05-05 08:04:20 DEBUG    task          letterboxd-comedy executing letterboxd-comedy
2021-05-05 08:04:20 DEBUG    template      letterboxd-comedy Merging template global into task letterboxd-comedy
2021-05-05 08:04:20 DEBUG    disable       letterboxd-comedy Disabled plugins: seen
2021-05-05 08:04:20 DEBUG    input_cache   letterboxd-comedy cache name: letterboxd_0b148faa86d3206f5b22e7266234fb59 (has: )
2021-05-05 08:04:20 DEBUG    input_cache   letterboxd-comedy storing entries to cache letterboxd_0b148faa86d3206f5b22e7266234fb59 
2021-05-05 08:04:20 VERBOSE  letterboxd    letterboxd-comedy Looking for films in Letterboxd list: http://letterboxd.com/effemmeffe/list/netflix-stand-up-comedy/
2021-05-05 08:04:20 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/effemmeffe/list/netflix-stand-up-comedy/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:22 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/iliza-shlesinger-elder-millennial/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:23 DEBUG    api_tmdb      letterboxd-comedy no tmdb configuration in memory, checking cache
2021-05-05 08:04:23 DEBUG    api_tmdb      letterboxd-comedy no config cached or config expired, refreshing
2021-05-05 08:04:23 DEBUG    utils.requests letterboxd-comedy GETing URL https://api.themoviedb.org/3/configuration with args () and kwargs {'params': {'api_key': 'bdfc018dbdb7c243dc7cb1454ff74b95'}, 'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:23 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=535340, imdb_id=None>
2021-05-05 08:04:23 DEBUG    api_tmdb      letterboxd-comedy Movie Iliza Shlesinger: Elder Millennial information restored from cache.
2021-05-05 08:04:23 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/chris-delia-no-pain/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:25 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=687136, imdb_id=None>
2021-05-05 08:04:25 DEBUG    api_tmdb      letterboxd-comedy Movie Chris D'Elia: No Pain information restored from cache.
2021-05-05 08:04:25 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/david-batra-elephant-in-the-room/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:25 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=688527, imdb_id=None>
2021-05-05 08:04:25 DEBUG    api_tmdb      letterboxd-comedy Movie David Batra: Elephant in The Room information restored from cache.
2021-05-05 08:04:25 DEBUG    utils.requests letterboxd-comedy Waiting 0.17 seconds until next request to letterboxd.com
2021-05-05 08:04:26 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/tom-segura-ball-hog/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:27 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=676601, imdb_id=None>
2021-05-05 08:04:27 DEBUG    api_tmdb      letterboxd-comedy Movie Tom Segura: Ball Hog information restored from cache.
2021-05-05 08:04:27 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/bert-kreischer-hey-big-boy/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:29 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=675267, imdb_id=None>
2021-05-05 08:04:29 DEBUG    api_tmdb      letterboxd-comedy Movie Bert Kreischer: Hey Big Boy information restored from cache.
2021-05-05 08:04:29 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/marc-maron-end-times-fun/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:30 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=675595, imdb_id=None>
2021-05-05 08:04:30 DEBUG    api_tmdb      letterboxd-comedy Movie Marc Maron: End Times Fun information restored from cache.
2021-05-05 08:04:30 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/amit-tandon-family-tandoncies/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:31 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=656566, imdb_id=None>
2021-05-05 08:04:31 DEBUG    api_tmdb      letterboxd-comedy Movie Amit Tandon: Family Tandoncies information restored from cache.
2021-05-05 08:04:31 DEBUG    utils.requests letterboxd-comedy Waiting 0.17 seconds until next request to letterboxd.com
2021-05-05 08:04:31 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/pete-davidson-alive-from-new-york/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:32 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=673768, imdb_id=None>
2021-05-05 08:04:32 DEBUG    api_tmdb      letterboxd-comedy Movie Pete Davidson: Alive from New York information restored from cache.
2021-05-05 08:04:32 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/bo-burnham-make-happy/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:33 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=400608, imdb_id=None>
2021-05-05 08:04:33 DEBUG    api_tmdb      letterboxd-comedy Movie Bo Burnham: Make Happy information restored from cache.
2021-05-05 08:04:33 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/mike-birbiglia-my-girlfriends-boyfriend/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:34 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=216652, imdb_id=None>
2021-05-05 08:04:34 DEBUG    api_tmdb      letterboxd-comedy Movie Mike Birbiglia: My Girlfriend's Boyfriend information restored from cache.
2021-05-05 08:04:34 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/oh-hello-on-broadway/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:37 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=460822, imdb_id=None>
2021-05-05 08:04:37 DEBUG    api_tmdb      letterboxd-comedy Movie Oh, Hello on Broadway information restored from cache.
2021-05-05 08:04:37 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/mike-birbiglia-the-new-one/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:40 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=642739, imdb_id=None>
2021-05-05 08:04:41 DEBUG    api_tmdb      letterboxd-comedy Movie Mike Birbiglia: The New One information restored from cache.
2021-05-05 08:04:41 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/neal-brennan-3-mics/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:42 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=435351, imdb_id=None>
2021-05-05 08:04:42 DEBUG    api_tmdb      letterboxd-comedy Movie Neal Brennan: 3 Mics information restored from cache.
2021-05-05 08:04:42 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/bill-burr-im-sorry-you-feel-that-way/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:43 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=308571, imdb_id=None>
2021-05-05 08:04:43 DEBUG    api_tmdb      letterboxd-comedy Movie Bill Burr: I'm Sorry You Feel That Way information restored from cache.
2021-05-05 08:04:43 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/bill-burr-you-people-are-all-the-same/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:44 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=191489, imdb_id=None>
2021-05-05 08:04:44 DEBUG    api_tmdb      letterboxd-comedy Movie Bill Burr: You People Are All The Same information restored from cache.
2021-05-05 08:04:44 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/mike-birbiglia-thank-god-for-jokes/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:45 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=442087, imdb_id=None>
2021-05-05 08:04:45 DEBUG    api_tmdb      letterboxd-comedy Movie Mike Birbiglia: Thank God for Jokes information restored from cache.
2021-05-05 08:04:45 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/nate-bargatze-the-tennessee-kid/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:47 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=590872, imdb_id=None>
2021-05-05 08:04:47 DEBUG    api_tmdb      letterboxd-comedy Movie Nate Bargatze: The Tennessee Kid information restored from cache.
2021-05-05 08:04:47 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/patton-oswalt-annihilation/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:48 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=479263, imdb_id=None>
2021-05-05 08:04:48 DEBUG    api_tmdb      letterboxd-comedy Movie Patton Oswalt: Annihilation information restored from cache.
2021-05-05 08:04:48 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/trevor-noah-son-of-patricia/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:49 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=558341, imdb_id=None>
2021-05-05 08:04:49 DEBUG    api_tmdb      letterboxd-comedy Movie Trevor Noah: Son of Patricia information restored from cache.
2021-05-05 08:04:49 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/jim-jefferies-bare/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:50 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=289333, imdb_id=None>
2021-05-05 08:04:50 DEBUG    api_tmdb      letterboxd-comedy Movie Jim Jefferies: Bare information restored from cache.
2021-05-05 08:04:51 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/tom-segura-disgraceful/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:52 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=497520, imdb_id=None>
2021-05-05 08:04:52 DEBUG    api_tmdb      letterboxd-comedy Movie Tom Segura: Disgraceful information restored from cache.
2021-05-05 08:04:52 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/adam-sandler-100-fresh/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:54 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=517596, imdb_id=None>
2021-05-05 08:04:54 DEBUG    api_tmdb      letterboxd-comedy Movie Adam Sandler: 100% Fresh information restored from cache.
2021-05-05 08:04:54 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/ricky-gervais-humanity/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:55 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=508933, imdb_id=None>
2021-05-05 08:04:55 DEBUG    api_tmdb      letterboxd-comedy Movie Ricky Gervais: Humanity information restored from cache.
2021-05-05 08:04:55 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/tig-notaro-happy-to-be-here/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:57 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=521512, imdb_id=None>
2021-05-05 08:04:57 DEBUG    api_tmdb      letterboxd-comedy Movie Tig Notaro: Happy To Be Here information restored from cache.
2021-05-05 08:04:57 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/sarah-silverman-a-speck-of-dust/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:58 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=459295, imdb_id=None>
2021-05-05 08:04:58 DEBUG    api_tmdb      letterboxd-comedy Movie Sarah Silverman: A Speck of Dust information restored from cache.
2021-05-05 08:04:58 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/bert-kreischer-secret-time/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:04:59 DEBUG    api_tmdb      letterboxd-comedy Looking up TMDb information for <title=None, year=None, tmdb_id=542694, imdb_id=None>
2021-05-05 08:05:00 DEBUG    api_tmdb      letterboxd-comedy Movie Bert Kreischer: Secret Time information restored from cache.
2021-05-05 08:05:00 DEBUG    utils.requests letterboxd-comedy GETing URL http://letterboxd.com/film/daniel-sloss-live-shows/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-05 08:05:01 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
  File "/usr/local/lib/python3.8/dist-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/flexget/task.py", line 722, in execute
    self._execute()
  File "/usr/local/lib/python3.8/dist-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
  File "/usr/local/lib/python3.8/dist-packages/flexget/task.py", line 517, in __run_task_phase
    for e in response:
  File "/usr/local/lib/python3.8/dist-packages/flexget/utils/cached_input.py", line 232, in __iter__
    for item in self.iterable:
  File "/usr/local/lib/python3.8/dist-packages/flexget/plugins/input/letterboxd.py", line 121, in on_task_input
    yield self.parse_film(film, config)
  File "/usr/local/lib/python3.8/dist-packages/flexget/plugins/input/letterboxd.py", line 84, in parse_film
    result = self.tmdb_lookup(soup.find(attrs={'data-tmdb-id': True}).get('data-tmdb-id'))
  File "/usr/local/lib/python3.8/dist-packages/flexget/plugins/input/letterboxd.py", line 70, in tmdb_lookup
    tmdb = plugin.get('api_tmdb', self).lookup(tmdb_id=search)
  File "/usr/local/lib/python3.8/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flexget/components/tmdb/api_tmdb.py", line 322, in lookup
    raise LookupError('No criteria specified for TMDb lookup')
LookupError: No criteria specified for TMDb lookup

```


### Additional information:

- FlexGet version:
3.1.117

- Python version:
python -V
Python 2.7.18
python3 -V
Python 3.8.5

- Installation method:
pip

- Using daemon (yes/no):
yes

- OS and version:
Ubuntu 20.04.2 LTS
