### ISSUE TITLE
crashes with flexget 2.17 and deluge-client

### ISSUE THREAD

**Issue by ksurl** [Flexget/Flexget#2233]
### Expected behaviour:

add magnet link to deluge. use option to rename file

### Actual behaviour:

does download file, but it retains original file name. also crashes when unhandled error occurs

### Steps to reproduce:
- Step 1: start daemon
- Step 2: flexget downloads on scheduler
- Step 3: file is not renamed

#### Config:
```
tasks:
  shows:
    rss:
      url: '{? feed ?}'
      all_entries: no
    include: shows.yml
    deluge:
      path: '{? downloads ?}'
      content_filename: "{{series_name}} {{series_id|pad(2)}}"
      movedone: '{? downloads ?}/temp/'

  move-shows:
    filesystem:
      recursive: yes
      retrieve: files
      regexp: '.*\.(mp4|mkv)$'
      path: '{? downloads ?}/temp/'
    accept_all: yes
    disable: builtins
    move:
      to: '{? downloads ?}/series/'
      clean_source: 100

schedules:
  - tasks: shows
    schedule:
      minute: "*/30"
  - tasks: move-shows
    schedule:
      minute: "*/15"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2018-10-18 22:30 INFO     deluge_client.client showrss         Connecting to localhost:58846
2018-10-18 22:30 CRITICAL task          showrss         BUG: Unhandled error in plugin deluge: 
Traceback (most recent call last):
  File "/home/$user/.venv/flexget/lib/python3.5/site-packages/deluge_client/client.py", line 214, in call
    return self._receive_response(self.deluge_version)
  File "/home/$user/.venv/flexget/lib/python3.5/site-packages/deluge_client/client.py", line 141, in _receive_response
    d = self._socket.recv(READ_SIZE)
  File "/usr/lib/python3.5/ssl.py", line 914, in recv
    return self.read(buflen)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 577, in read
    v = self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/$user/.venv/flexget/lib/python3.5/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/home/$user/.venv/flexget/lib/python3.5/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/$user/.venv/flexget/lib/python3.5/site-packages/flexget/plugins/clients/deluge.py", line 465, in on_task_output
    self._set_torrent_options(added_torrent, entry, modify_opts)
  File "/home/$user/.venv/flexget/lib/python3.5/site-packages/flexget/plugins/clients/deluge.py", line 585, in _set_torrent_options
    big_file_name = unused_name(big_file_name)
  File "/home/$user/.venv/flexget/lib/python3.5/site-packages/flexget/plugins/clients/deluge.py", line 541, in unused_name
    if self.client.call('is_localhost'):
  File "/home/$user/.venv/flexget/lib/python3.5/site-packages/deluge_client/client.py", line 218, in call
    raise FailedToReconnectException()
deluge_client.client.FailedToReconnectException

```
</details>

### Additional information:

- FlexGet version: 2.17
- Python version: 3.5.2
- Installation method: virtualenv pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu 16.04.5 LTS

more info:
I was using 2.14.20 with python 2.7.12 and virtualenv install using --system-site-packages for deluge compatibility
when I saw that 2.17 supported deluge-client, I switched to using python 3.5.2 (newest available on 16.04 LTS in default repo). it does download the file but doesn't rename it. looks like deluge options are broken/not supported in deluge-client.
I am going to try install python 3.6.5 and creating a new virtualenv install with that version. it does restart the daemon as the service is supposed to restart on crash and the download finishes, it moved to the folder, but just keeping the original name.

**Comment by ksurl** [comment]
confirmed today new entries are being renamed properly and daemon is not crashing. Flexget 2.17.1, python 3.5.2 with virtualenv.
