### ISSUE TITLE
BUG: Unhandled error in plugin clean_transmission: timed out

### ISSUE THREAD

**Issue by crytoncrossed** [Flexget/Flexget#2248]
### Expected behaviour:
Handle timeout error properly. 

### Actual behaviour:
Unhandled timeout error causes crash dump to be created. 

### Steps to reproduce:
- Step 1: Run flexget on one machine, and transmission on another (or in my case in different docker instances).
- Step 2: Have a network issue between flexget and transmission, such as stopping the transmission instance.
- Step 3, wait for flexget to run job with clean_transmisision plugin.

#### Config:
    clean_transmission:
      host: <transmission server ip>
      port: <port>
      username: <username>
      password: <password>
      min_ratio: 0
      finished_for: 7 days
  
#### Log:
2018-11-04 21:24 CRITICAL task          clean_other     BUG: Unhandled error in plugin clean_transmission: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/clients/transmission.py", line 651, in on_task_exit
    self.client = self.create_rpc_client(config)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/clients/transmission.py", line 75, in create_rpc_client
    cli = transmissionrpc.Client(config['host'], config['port'], user, password)
  File "/usr/local/lib/python2.7/site-packages/transmissionrpc/client.py", line 169, in __init__
    self.get_session()
  File "/usr/local/lib/python2.7/site-packages/transmissionrpc/client.py", line 828, in get_session
    self._request('session-get', timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/transmissionrpc/client.py", line 247, in _request
    http_data = self._http_query(query, timeout)
  File "/usr/local/lib/python2.7/site-packages/transmissionrpc/client.py", line 205, in _http_query
    result = self.http_handler.request(self.url, query, headers, timeout)
  File "/usr/local/lib/python2.7/site-packages/transmissionrpc/httphandler.py", line 65, in request
    response = self.http_opener.open(request, timeout=timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

### Additional information:

- FlexGet version: 2.14.21
- Python version: 2.7.14
- Installation method: docker instance.
- Using daemon (yes/no): yes.
- OS and version: Linux, https://hub.docker.com/r/anthonydahanne/flexget/
- Link to crash log:

**Comment by gazpachoking** [comment]
Going to close this out, since clean_transmission is now deprecated.
