### ISSUE TITLE
BUG: Unhandled error in plugin deluge: attempt to connect already-connected SSLSocket

### ISSUE THREAD

**Issue by girtsl** [Flexget/Flexget#2255]
### Expected behaviour:
Flexget downloads multiple sequential episodes in one run.

### Actual behaviour:
Crash on the second accepted episode.

### Steps to reproduce:
1. Add series that would produce multiple episodes.
2. Run a task that discovers episodes and adds them to deluge.

#### Config:
[config.txt](https://github.com/Flexget/Flexget/files/2594033/config.txt)
  
#### Log:
<details>
 <summary>BUG: Unhandled error in plugin deluge: attempt to connect already-connected SSLSocket!</summary>

```
2018-11-19 08:13 VERBOSE  task          download-shows  ACCEPTED: `Show S01E06` by series plugin because matches quality
2018-11-19 08:13 INFO     download      download-shows  Downloading: Show S01E06
2018-11-19 08:13 VERBOSE  details       download-shows  Summary - Accepted: 1 (Rejected: 7 Undecided: 15 Failed: 0)
2018-11-19 08:13 INFO     deluge_client.client download-shows  Connecting to localhost:58846
2018-11-19 08:13 INFO     deluge_client.client download-shows  Connecting to localhost:58846
2018-11-19 08:13 VERBOSE  deluge        download-shows  Adding Show S01E06 to deluge.
2018-11-19 08:13 INFO     deluge        download-shows  Show S01E06 successfully added to deluge.
2018-11-19 08:13 VERBOSE  notify        download-shows  Successfully sent a notification to `slack`
2018-11-19 08:13 INFO     task          download-shows  Rerunning the task in case better resolution can be achieved.
2018-11-19 08:13 VERBOSE  discover      download-shows  Discovering 21 titles ...

...

2018-11-19 08:14 VERBOSE  task          download-shows  ACCEPTED: `Show S01E07` by series plugin because matches quality
2018-11-19 08:14 INFO     download      download-shows  Downloading: Show S01E07
2018-11-19 08:14 VERBOSE  details       download-shows  Summary - Accepted: 1 (Rejected: 3 Undecided: 15 Failed: 0)
2018-11-19 08:14 INFO     deluge_client.client download-shows  Connecting to localhost:58846
2018-11-19 08:14 CRITICAL task          download-shows  BUG: Unhandled error in plugin deluge: attempt to connect already-connected SSLSocket!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/deluge.py", line 339, in on_task_output
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/clients/deluge.py", line 60, in connect
    self.client.connect()
  File "/usr/local/lib/python2.7/dist-packages/deluge_client/client.py", line 72, in connect
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/deluge_client/client.py", line 86, in _connect
    self._socket.connect((self.host, self.port))
  File "/usr/lib/python2.7/ssl.py", line 876, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python2.7/ssl.py", line 856, in _real_connect
    raise ValueError("attempt to connect already-connected SSLSocket!")
ValueError: attempt to connect already-connected SSLSocket!

```
</details>

### Additional information:

- FlexGet version: 2.7.12
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: osmc
- Link to crash log: [crash_report.2018.11.19.081426497701.log](https://github.com/Flexget/Flexget/files/2594036/crash_report.2018.11.19.081426497701.log)

**Comment by gazpachoking** [comment]
Thanks for this report, we weren't disconnecting properly with the new deluge client. Should be fixed in the next release.
