### ISSUE TITLE
Can't run CLI commands, or restart daemon. Working normally besides that?

### ISSUE THREAD

**Issue by jacobkossman** [Flexget/Flexget#2277]
### Expected behaviour:
flexget seems to be running properly (downloads etc working) but any command on cli crashes (except version checking)

### Actual behaviour:
```
There is a FlexGet process already running for this config, sending execution there.
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 339, in start
    client = IPCClient(ipc_info['port'], ipc_info['password'], sync_request_timeout=self.options.timeout)
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 171, in __init__
    channel, service=ClientService, config={'sync_request_timeout': sync_request_timeout})
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/factory.py", line 44, in connect_channel
    return service._connect(channel, config)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/service.py", line 100, in _connect
    self.on_connect(conn)
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 108, in on_connect
    daemon_version = self._conn.root.version()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 155, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 75, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 471, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/async_.py", line 97, in value
    raise self._obj
KeyError: '<flexget.ipc.DaemonService object at 0x7f232821ec68>'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    proxy = self._netref_factory(oid, clsname, modname)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 541, in _handle_getattr
    #
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 499, in _access_attr
    """Fetches the root object (service) of the other party"""
  File "/usr/local/lib/python2.7/dist-packages/rpyc/lib/colls.py", line 86, in __getitem__
    return self._dict[key][0]
KeyError: <flexget.ipc.DaemonService object at 0x7f232821ec68>
```
### Steps to reproduce:
- Step 1: 
flexget check

### Additional information:

- FlexGet version: 2.17.19
You are on the latest release.
- Python version: Python 2.7.12
- Installation method: managed seedbox (unsure)
- Using daemon (yes/no): yes
- OS and version: Ubuntu 16.04.4 LTS
- Link to crash log:

**Comment by liiight** [comment]
can you do `pip freeze | grep rpyc`?

**Comment by jacobkossman** [comment]
```
You are using pip version 8.1.2, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
rpyc==4.0.1
```

**Comment by erichlf** [comment]
I can't reproduce this.

**Comment by gazpachoking** [comment]
I think @chestm007 is probably right that your daemon needs to be restarted. This however probably won't work via the cli commands, as they cause the crash. You may need to kill the daemon then start it up again. In the future, it is good practice to shut down the daemon before doing a flexget upgrade.
