### ISSUE TITLE
Deluge plugin crashes with SSL error when run against Deluge 2.0

### ISSUE THREAD

**Issue by brandond** [Flexget/Flexget#2287]
### Expected behaviour:
Torrents uploaded to local Deluge 2.0 server

### Actual behaviour:
Crashes with `SSLError: ('The read operation timed out',)`

### Steps to reproduce:
Run flexget with deluge plugin enabled against Deluge 2.0 

#### Config:
```yaml
templates:
  global:
    verify_ssl_certificates: no
    deluge:
      automanaged: true
      addpaused: false
    retry_failed:
      retry_time: 5 minutes
      max_retries: 30
      retry_time_multiplier: 2
  thesite:
    rss:
      url: https://xxx
      all_entries: yes
      ascii: yes
  tv:
    set:
      label: tv
    all_series:
      assume_special: true
      set:
        movedone: '/mnt/media/TV/{{series_name}}/'
  fixups:
    manipulate:
      - title:
          replace:
            regexp: 'Part\.(\d+)'
            format: 'S01E\1'

tasks:
  TheSite-tv:
    priority: 1
    template:
      - thesite
      - tv
      - fixups
```
  
#### Log:
Flexget crash report:
```
2018-12-28 00:01 INFO     deluge_client.client TheSite-tv      Connecting to localhost:58846
2018-12-28 00:01 DEBUG    deluge_client.client TheSite-tv      Connected to Deluge, detecting daemon version
2018-12-28 00:01 DEBUG    deluge_client.client TheSite-tv      Calling reqid 2 method 'daemon.info' with args:() kwargs:{}
2018-12-28 00:01 DEBUG    deluge_client.client TheSite-tv      Calling reqid 3 method 'daemon.info' with args:() kwargs:{}
2018-12-28 00:01 CRITICAL task          TheSite-tv      BUG: Unhandled error in plugin deluge: ('The read operation timed out',)
Traceback (most recent call last):
  File "/home/kodi/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/home/kodi/flexget/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/kodi/flexget/local/lib/python2.7/site-packages/flexget/plugins/clients/deluge.py", line 325, in on_task_output
    self.client.connect()
  File "/home/kodi/flexget/local/lib/python2.7/site-packages/deluge_client/client.py", line 74, in connect
    self._detect_deluge_version()
  File "/home/kodi/flexget/local/lib/python2.7/site-packages/deluge_client/client.py", line 112, in _detect_deluge_version
    result = self._socket.recv(1)
  File "/usr/lib/python2.7/ssl.py", line 772, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 659, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)
```

Deluge daemon log:
```
00:01:31.894 [INFO    ][deluge.core.rpcserver         :0   ] Deluge Client connection made from: 127.0.0.1:50152
00:01:31.901 [WARNING ][deluge.transfer               :0   ] Error occurred when parsing message header: Received invalid protocol version: 120. PROTOCOL_VERSION is 1..
00:01:31.901 [WARNING ][deluge.transfer               :0   ] This version of Deluge cannot communicate with the sender of this data.
00:01:31.901 [WARNING ][deluge.transfer               :0   ] Failed to decompress (0 bytes) and load serialized data with rencode: Error -5 while decompressing data: incomplete                                     or truncated stream
00:01:31.944 [WARNING ][deluge.transfer               :0   ] Error occurred when parsing message header: Received invalid protocol version: 68. PROTOCOL_VERSION is 1..
00:01:31.944 [WARNING ][deluge.transfer               :0   ] This version of Deluge cannot communicate with the sender of this data.
00:01:31.945 [WARNING ][deluge.transfer               :0   ] Failed to decompress (0 bytes) and load serialized data with rencode: Error -5 while decompressing data: incomplete                                     or truncated stream
00:01:31.945 [WARNING ][deluge.transfer               :0   ] Error occurred when parsing message header: Received invalid protocol version: 120. PROTOCOL_VERSION is 1..
00:01:31.945 [WARNING ][deluge.transfer               :0   ] This version of Deluge cannot communicate with the sender of this data.
00:01:31.946 [WARNING ][deluge.transfer               :0   ] Failed to decompress (0 bytes) and load serialized data with rencode: Error -5 while decompressing data: incomplete                                     or truncated stream
00:01:52.142 [INFO    ][deluge.core.rpcserver         :0   ] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
```

### Additional information:

- Deluge version: 2.0.0.dev7395+b2e1956+201811221818~ubuntu18.04.1 (from PPA)
- FlexGet version: 2.17.22
- Python version: 2.7.15rc1
- Installation method: pip in virtualenv
- Using daemon (yes/no): no
- OS and version: Ubuntu 18.04.1 LTS / 4.20.0-042000-generic

**Comment by gazpachoking** [comment]
Added support for the latest deluge protocol to deluge-client here https://github.com/JohnDoee/deluge-client/pull/29, was waiting for a pypi release which I didn't realize already happened. Version 1.7 should connect to newer deluge 2.0 daemons now.
