### ISSUE TITLE
npo_watchlist - some shows error out with stripped_strings

### ISSUE THREAD

**Issue by solipsist01** [Flexget/Flexget#2300]
When i add shows like 'Wie is de Mol' or 'Boer zoekt Vrouw' to my watchlist, the script crashes.
See the logging below

2019-01-14 18:57 VERBOSE  search_npo    npo_task        Retrieving NPOStart profiles for account redacted
2019-01-14 18:57 VERBOSE  utils.requests npo_task        Waiting 7.95 seconds until next request to npostart.nl
2019-01-14 18:57 INFO     search_npo    npo_task        Retrieving favorites for profile Hoofdprofiel
2019-01-14 18:57 VERBOSE  search_npo    npo_task        Retrieving series info for KN_1678993
2019-01-14 18:57 VERBOSE  utils.requests npo_task        Waiting 7.79 seconds until next request to npostart.nl
2019-01-14 18:57 VERBOSE  utils.requests npo_task        Waiting 4.86 seconds until next request to npostart.nl
2019-01-14 18:57 VERBOSE  utils.requests npo_task        Waiting 7.69 seconds until next request to npostart.nl
2019-01-14 18:57 VERBOSE  utils.requests npo_task        Waiting 7.66 seconds until next request to npostart.nl
2019-01-14 18:57 VERBOSE  utils.requests npo_task        Waiting 7.70 seconds until next request to npostart.nl
2019-01-14 18:58 VERBOSE  utils.requests npo_task        Waiting 7.68 seconds until next request to npostart.nl
2019-01-14 18:58 VERBOSE  search_npo    npo_task        Retrieving series info for KN_1682194
2019-01-14 18:58 VERBOSE  utils.requests npo_task        Waiting 7.49 seconds until next request to npostart.nl
2019-01-14 18:58 VERBOSE  utils.requests npo_task        Waiting 5.62 seconds until next request to npostart.nl
2019-01-14 18:58 VERBOSE  utils.requests npo_task        Waiting 7.68 seconds until next request to npostart.nl
2019-01-14 18:58 VERBOSE  utils.requests npo_task        Waiting 7.70 seconds until next request to npostart.nl
2019-01-14 18:58 VERBOSE  search_npo    npo_task        Retrieving series info for VPWON_1290745
2019-01-14 18:58 VERBOSE  utils.requests npo_task        Waiting 7.65 seconds until next request to npostart.nl
2019-01-14 18:58 VERBOSE  utils.requests npo_task        Waiting 6.92 seconds until next request to npostart.nl
2019-01-14 18:59 VERBOSE  search_npo    npo_task        Retrieving series info for KN_1680708
2019-01-14 18:59 VERBOSE  utils.requests npo_task        Waiting 7.80 seconds until next request to npostart.nl
2019-01-14 18:59 VERBOSE  utils.requests npo_task        Waiting 6.57 seconds until next request to npostart.nl
2019-01-14 18:59 VERBOSE  utils.requests npo_task        Waiting 7.66 seconds until next request to npostart.nl
2019-01-14 18:59 VERBOSE  utils.requests npo_task        Waiting 7.71 seconds until next request to npostart.nl
2019-01-14 18:59 VERBOSE  search_npo    npo_task        Retrieving series info for KN_1679108
2019-01-14 18:59 VERBOSE  utils.requests npo_task        Waiting 7.83 seconds until next request to npostart.nl
2019-01-14 18:59 VERBOSE  utils.requests npo_task        Waiting 6.11 seconds until next request to npostart.nl
2019-01-14 18:59 VERBOSE  utils.requests npo_task        Waiting 7.75 seconds until next request to npostart.nl
2019-01-14 18:59 VERBOSE  utils.requests npo_task        Waiting 7.75 seconds until next request to npostart.nl
2019-01-14 19:00 VERBOSE  utils.requests npo_task        Waiting 7.63 seconds until next request to npostart.nl
2019-01-14 19:00 VERBOSE  utils.requests npo_task        Waiting 7.75 seconds until next request to npostart.nl
2019-01-14 19:00 VERBOSE  search_npo    npo_task        Retrieving series info for KN_1698945
2019-01-14 19:00 VERBOSE  utils.requests npo_task        Waiting 7.65 seconds until next request to npostart.nl
2019-01-14 19:00 VERBOSE  utils.requests npo_task        Waiting 6.03 seconds until next request to npostart.nl
2019-01-14 19:00 VERBOSE  search_npo    npo_task        Retrieving series info for KN_1683530
2019-01-14 19:00 VERBOSE  utils.requests npo_task        Waiting 7.74 seconds until next request to npostart.nl
2019-01-14 19:00 VERBOSE  utils.requests npo_task        Waiting 4.44 seconds until next request to npostart.nl
2019-01-14 19:00 CRITICAL task          npo_task        BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'stripped_strings'
2019-01-14 19:00 CRITICAL manager       npo_task        An unexpected crash has occurred. Writing crash report to /flexget/crash_report.2019.01.14.190052362224.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.18.2
2019-01-14 19:00 WARNING  task          npo_task        Aborting task (plugin: npo_watchlist)
2019-01-14 19:03 INFO     search_npo    npo_task        Retrieving favorites for profile Hoofdprofiel
2019-01-14 19:06 CRITICAL task          npo_task        BUG: Unhandled error in plugin npo_watchlist: 'NoneType' object has no attribute 'stripped_strings'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/input/npo_watchlist.py", line 259, in on_task_input
    entries = self._get_favourites_entries(task, config, profileId)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/input/npo_watchlist.py", line 127, in _get_favourites_entries
    entries += self._get_series_episodes(task, config, favourite['mediaId'])
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/input/npo_watchlist.py", line 156, in _get_series_episodes
    new_entries = self._parse_tiles(task, config, episodes['tiles'], series_info)
  File "/usr/local/lib/python2.7/site-packages/flexget/plugins/input/npo_watchlist.py", line 213, in _parse_tiles
    timer = next(list_item.find('div', class_='npo-asset-tile-timer').stripped_strings)
AttributeError: 'NoneType' object has no attribute 'stripped_strings'

**Comment by mfonville** [comment]
I am not sure what caused your error, because I can't reproduce this. Probably the running time was not yet added to the episode information it did find. Did you run the script shortly after the broadcast itself?

And if so, could you check if (when running it at the same hour next week) the episode was available for playback? Because then we can check whether to just skip the `timer` information or if this episode should be skipped if not watchable yet.

**Comment by solipsist01** [comment]
Hi Maarten,

I still have the problem, so i will do additional troubleshooting to see if i can see what is causing this.
i'm thinking of altering the script to raw output the variables, perhaps that can help us.

Also some other thing is the following.

If you go to url https://www.npostart.nl/typisch/BV_101386658 you can see that there are some episodes that are broadcasted tomorrow, the day after,, and the day after next. you can watch the episodes now (earlier) if you have a npostart subscribtion.

however, the npo script sees these episodes as regular episodes, and tries to download them. it fails, so it will come in the failed database of flexget
after a few tries it gets the permanent failed marker.
it won't try to download the episode again, when it's actually available, because it has failed to many times already.

i don't know if the api has information about availability

**Comment by mfonville** [comment]
Hi @solipsist01,

At the moment at the URL you shared I can't see any future episodes.
Next time when you see this at the page, could you please save the page (file -> save page as) so that I can take a look at the HTML.

And did these future tiles look exactly as those at https://www.npostart.nl/dynasties/POW_04005761 with "Exclusief op NPO Start Plus" but still including the running time on the tile?

Thanks!

**Comment by mfonville** [comment]
Ok, I have been able to reproduce the problem with an entry of "Zembla" that had no running time included. Also I am updating the support for (absence) of premium subscriptions

**Comment by mfonville** [comment]
I made a PR with a fix in #2309
