### ISSUE TITLE
Exception while loading plugin flexget.components.imdb.db

### ISSUE THREAD

**Issue by tomatosmoothie** [Flexget/Flexget#2328]
Getting the error below on 
flexget check
flexget execute
flexget --test execute
```

2019-02-06 14:28 CRITICAL plugin Exception while loading plugin flexget.components.imdb.db
Traceback (most recent call last):
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/plugin.py", line 392, in importplugin
import(module_name)
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/components/imdb/db.py", line 27, in
Index('ix_imdb_movie_genres', 'movie_id', 'genre_id'),
File "/home/htpc/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 438, in new
"existing Table object." % key)
InvalidRequestError: Table 'imdb_movie_genres' is already defined for this MetaData instance. Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
Traceback (most recent call last):
File "/usr/local/bin/flexget", line 11, in
sys.exit(main())
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/__init__.py", line 42, in main
manager.start()
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/manager.py", line 363, in start
self.initialize()
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/manager.py", line 221, in initialize
extra_components=[os.path.join(self.config_base, 'components')],
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/plugin.py", line 497, in load_plugins
loadcomponents_from_dirs(extra_components)
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/plugin.py", line 448, in loadcomponents_from_dirs
importplugin(package_name, component_path)
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/plugin.py", line 392, in importplugin
import(module_name)
File "/home/htpc/.local/lib/python2.7/site-packages/flexget/components/imdb/db.py", line 27, in
Index('ix_imdb_movie_genres', 'movie_id', 'genre_id'),
File "/home/htpc/.local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 438, in new
"existing Table object." % key)
sqlalchemy.exc.InvalidRequestError: Table 'imdb_movie_genres' is already defined for this MetaData instance. Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

```
Additional information:

    FlexGet version: 2.19.4
    Installation method: PIP
    Using daemon (yes/no): Yes (with reload arg)
    OS and version: Debian Stretch

**Comment by tomatosmoothie** [comment]
Restored an old image of my linux system, backed up and restored the database and got it working.

**Comment by gazpachoking** [comment]
Hmm. I wonder what was wrong and whether other people are going to run in to this...
