### ISSUE TITLE
discover bug >=2.19.2

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2331]
### Expected behaviour:
```
Successfully installed flexget-2.19.1
root@cloudBox:~# flexget execute --now --discover-now
2019-02-08 04:04 VERBOSE  task_queue                    There are 21 tasks to execute. Shutdown will commence when they have completed.
2019-02-08 04:04 VERBOSE  input_cache   Remove_Canceled Restored 6 entries from db cache
2019-02-08 04:04 VERBOSE  details       Remove_Canceled Produced 6 entries.
2019-02-08 04:04 VERBOSE  details       Remove_Canceled Summary - Accepted: 0 (Rejected: 0 Undecided: 6 Failed: 0)
```

### Actual behaviour:
```
Successfully installed flexget-2.19.2
root@cloudBox:~# flexget execute --now --discover-now
2019-02-08 04:04 CRITICAL plugin                        Plugin `flexget.plugins.SeriesSearch` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/home/snikay/.flexget/plugins/SeriesSearch.py", line 7, in <module>
    from flexget.utils.search import normalize_unicode
ImportError: No module named search
2019-02-08 04:04 CRITICAL plugin                        Plugin `flexget.plugins.MoviesSearch` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/home/snikay/.flexget/plugins/MoviesSearch.py", line 7, in <module>
    from .BaseSearchPlugin import BaseSearchPlugin, SearchResultEntry
  File "/home/snikay/.flexget/plugins/BaseSearchPlugin.py", line 7, in <module>
    from flexget.utils.search import normalize_unicode
ImportError: No module named search
2019-02-08 04:04 CRITICAL plugin                        Plugin `flexget.plugins.BaseSearchPlugin` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/home/snikay/.flexget/plugins/BaseSearchPlugin.py", line 7, in <module>
    from flexget.utils.search import normalize_unicode
ImportError: No module named search
2019-02-08 04:04 CRITICAL plugin                        Plugin `flexget.components.managed_lists.lists.entry_list.cli` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/managed_lists/lists/entry_list/cli.py", line 13, in <module>
    from . import db
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/managed_lists/lists/entry_list/db.py", line 4, in <module>
    from typing import MutableSet
ImportError: No module named typing
2019-02-08 04:04 CRITICAL plugin                        Plugin `flexget.components.managed_lists.lists.entry_list.api` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/managed_lists/lists/entry_list/api.py", line 21, in <module>
    from . import db
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/managed_lists/lists/entry_list/db.py", line 4, in <module>
    from typing import MutableSet
ImportError: No module named typing
2019-02-08 04:04 CRITICAL plugin                        Plugin `flexget.components.managed_lists.lists.entry_list.db` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/managed_lists/lists/entry_list/db.py", line 4, in <module>
    from typing import MutableSet
ImportError: No module named typing
2019-02-08 04:04 CRITICAL plugin                        Plugin `flexget.components.managed_lists.lists.entry_list.entry_list` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/managed_lists/lists/entry_list/entry_list.py", line 12, in <module>
    from . import db
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/managed_lists/lists/entry_list/db.py", line 4, in <module>
    from typing import MutableSet
ImportError: No module named typing
2019-02-08 04:04 CRITICAL manager                       [/templates/Discover-enable-Backfill/discover/from/0] The key `searchSerienjunkies` is not valid here. Only known plugin names are valid keys.
2019-02-08 04:04 CRITICAL manager                       [/templates/Discover-disable-Backfill/discover/from/0] The key `searchSerienjunkies` is not valid here. Only known plugin names are valid keys.
2019-02-08 04:04 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Main/discover/from/0] The key `searchHdarea` is not valid here. Only known plugin names are valid keys.
2019-02-08 04:04 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Main/discover/from/1] The key `searchHdworld` is not valid here. Only known plugin names are valid keys.
2019-02-08 04:04 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Main/discover/from/2] The key `searchMovieBlog` is not valid here. Only known plugin names are valid keys.
2019-02-08 04:04 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Low/discover/from/0] The key `searchHdarea` is not valid here. Only known plugin names are valid keys.
2019-02-08 04:04 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Low/discover/from/1] The key `searchHdworld` is not valid here. Only known plugin names are valid keys.
2019-02-08 04:04 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Low/discover/from/2] The key `searchMovieBlog` is not valid here. Only known plugin names are valid keys.
2019-02-08 04:04 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
Could not start manager: Did not pass schema validation.
root@cloudBox:~# sudo pip install --upgrade flexget==2.19.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/home/snikay/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/snikay/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting flexget==2.19.1
  Downloading https://files.pythonhosted.org/packages/4a/04/fa9d1efdd500a8bb57b799ea374800054110d189499f1390fb5029a3bf44/FlexGet-2.19.1-py2.py3-none-any.whl (6.4MB)
    100% |████████████████████████████████| 6.5MB 6.3MB/s 
Requirement already satisfied, skipping upgrade: future==0.16.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.16.0)
Requirement already satisfied, skipping upgrade: flask-login==0.4.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.4.0)
Requirement already satisfied, skipping upgrade: pytz==2017.2 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2017.2)
Requirement already satisfied, skipping upgrade: certifi==2017.4.17 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2017.4.17)
Requirement already satisfied, skipping upgrade: pyparsing==2.2.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2.2.0)
Requirement already satisfied, skipping upgrade: progressbar==2.5 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2.5)
Requirement already satisfied, skipping upgrade: cherrypy==10.2.2 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (10.2.2)
Requirement already satisfied, skipping upgrade: guessit==3.0.3 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (3.0.3)
Requirement already satisfied, skipping upgrade: html5lib==0.999999999 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.999999999)
Requirement already satisfied, skipping upgrade: importlib-metadata==0.8 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.8)
Requirement already satisfied, skipping upgrade: pynzb==0.1.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.1.0)
Requirement already satisfied, skipping upgrade: flask==1.0.2 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.0.2)
Requirement already satisfied, skipping upgrade: colorclass==2.2.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2.2.0)
Requirement already satisfied, skipping upgrade: itsdangerous==0.24 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.24)
Requirement already satisfied, skipping upgrade: aniso8601==1.2.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.2.1)
Requirement already satisfied, skipping upgrade: click==6.7 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (6.7)
Requirement already satisfied, skipping upgrade: rebulk==0.9.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.9.0)
Requirement already satisfied, skipping upgrade: six==1.10.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.10.0)
Requirement already satisfied, skipping upgrade: feedparser==5.2.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (5.2.1)
Requirement already satisfied, skipping upgrade: path.py==11.5.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (11.5.0)
Requirement already satisfied, skipping upgrade: webencodings==0.5.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.5.1)
Requirement already satisfied, skipping upgrade: pyrss2gen==1.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.1)
Requirement already satisfied, skipping upgrade: flask-restful==0.3.6 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.3.6)
Requirement already satisfied, skipping upgrade: flask-cors==3.0.2 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (3.0.2)
Requirement already satisfied, skipping upgrade: werkzeug==0.14.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.14.1)
Requirement already satisfied, skipping upgrade: terminaltables==3.1.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (3.1.0)
Requirement already satisfied, skipping upgrade: tzlocal==1.4 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.4)
Requirement already satisfied, skipping upgrade: apscheduler==3.5.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (3.5.0)
Requirement already satisfied, skipping upgrade: babelfish==0.5.5 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.5.5)
Requirement already satisfied, skipping upgrade: plumbum==1.6.3 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.6.3)
Requirement already satisfied, skipping upgrade: tempora==1.8 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.8)
Requirement already satisfied, skipping upgrade: markupsafe==1.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.0)
Requirement already satisfied, skipping upgrade: sqlalchemy==1.2.6 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.2.6)
Requirement already satisfied, skipping upgrade: python-dateutil==2.6.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2.6.1)
Requirement already satisfied, skipping upgrade: zipp==0.3.3 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.3.3)
Requirement already satisfied, skipping upgrade: pyyaml==3.13 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (3.13)
Requirement already satisfied, skipping upgrade: cheroot==5.5.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (5.5.0)
Requirement already satisfied, skipping upgrade: jinja2==2.10 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2.10)
Requirement already satisfied, skipping upgrade: jsonschema==2.6.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2.6.0)
Requirement already satisfied, skipping upgrade: flask-restplus==0.10.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (0.10.1)
Requirement already satisfied, skipping upgrade: requests==2.20.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2.20.1)
Requirement already satisfied, skipping upgrade: portend==1.8 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.8)
Requirement already satisfied, skipping upgrade: chardet==3.0.3 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (3.0.3)
Requirement already satisfied, skipping upgrade: urllib3==1.21.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.21.1)
Requirement already satisfied, skipping upgrade: rpyc==4.0.1 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (4.0.1)
Requirement already satisfied, skipping upgrade: flask-compress==1.4.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (1.4.0)
Requirement already satisfied, skipping upgrade: idna==2.5 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (2.5)
Requirement already satisfied, skipping upgrade: beautifulsoup4==4.6.0 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (4.6.0)
Requirement already satisfied, skipping upgrade: zxcvbn-python==4.4.15 in /usr/local/lib/python2.7/dist-packages (from flexget==2.19.1) (4.4.15)
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in /usr/local/lib/python2.7/dist-packages (from html5lib==0.999999999->flexget==2.19.1) (40.8.0)
Requirement already satisfied, skipping upgrade: configparser; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-metadata==0.8->flexget==2.19.1) (3.5.0)
Requirement already satisfied, skipping upgrade: contextlib2; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-metadata==0.8->flexget==2.19.1) (0.5.5)
Requirement already satisfied, skipping upgrade: pathlib2; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-metadata==0.8->flexget==2.19.1) (2.3.3)
Requirement already satisfied, skipping upgrade: backports.os; python_version == "2.7" and sys_platform == "linux2" in /usr/local/lib/python2.7/dist-packages (from path.py==11.5.0->flexget==2.19.1) (0.1.1)
Requirement already satisfied, skipping upgrade: funcsigs; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from apscheduler==3.5.0->flexget==2.19.1) (1.0.2)
Requirement already satisfied, skipping upgrade: futures; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from apscheduler==3.5.0->flexget==2.19.1) (3.2.0)
Requirement already satisfied, skipping upgrade: functools32; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from jsonschema==2.6.0->flexget==2.19.1) (3.2.3.post2)
Requirement already satisfied, skipping upgrade: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version < "3"->importlib-metadata==0.8->flexget==2.19.1) (1.9.0)
Installing collected packages: flexget
  Found existing installation: FlexGet 2.19.2
    Uninstalling FlexGet-2.19.2:
      Successfully uninstalled FlexGet-2.19.2
Successfully installed flexget-2.19.1
root@cloudBox:~# flexget execute --now --discover-now
2019-02-08 04:04 VERBOSE  task_queue                    There are 21 tasks to execute. Shutdown will commence when they have completed.
2019-02-08 04:04 VERBOSE  input_cache   Remove_Canceled Restored 6 entries from db cache
2019-02-08 04:04 VERBOSE  details       Remove_Canceled Produced 6 entries.
2019-02-08 04:04 VERBOSE  details       Remove_Canceled Summary - Accepted: 0 (Rejected: 0 Undecided: 6 Failed: 0)
```

### Steps to reproduce:
External scripts with discover

#### Config:
https://github.com/crack00r/Flexget-Config

**Comment by gazpachoking** [comment]
This was fixed in 2.19.3

**Comment by snickers2k** [comment]
still happening in x.5

```
2019-02-10 00:02 CRITICAL plugin                        Plugin `flexget.plugins.SeriesSearch` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/home/snikay/.flexget/plugins/SeriesSearch.py", line 7, in <module>
    from flexget.utils.search import normalize_unicode
ImportError: No module named search
2019-02-10 00:02 CRITICAL plugin                        Plugin `flexget.plugins.MoviesSearch` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/home/snikay/.flexget/plugins/MoviesSearch.py", line 7, in <module>
    from .BaseSearchPlugin import BaseSearchPlugin, SearchResultEntry
  File "/home/snikay/.flexget/plugins/BaseSearchPlugin.py", line 7, in <module>
    from flexget.utils.search import normalize_unicode
ImportError: No module named search
2019-02-10 00:02 CRITICAL plugin                        Plugin `flexget.plugins.BaseSearchPlugin` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 392, in _import_plugin
    __import__(module_name)
  File "/home/snikay/.flexget/plugins/BaseSearchPlugin.py", line 7, in <module>
    from flexget.utils.search import normalize_unicode
ImportError: No module named search
2019-02-10 00:02 CRITICAL manager                       [/templates/Discover-enable-Backfill/discover/from/0] The key `searchSerienjunkies` is not valid here. Only known plugin names are valid keys.
2019-02-10 00:02 CRITICAL manager                       [/templates/Discover-disable-Backfill/discover/from/0] The key `searchSerienjunkies` is not valid here. Only known plugin names are valid keys.
2019-02-10 00:02 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Main/discover/from/0] The key `searchHdarea` is not valid here. Only known plugin names are valid keys.
2019-02-10 00:02 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Main/discover/from/1] The key `searchHdworld` is not valid here. Only known plugin names are valid keys.
2019-02-10 00:02 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Main/discover/from/2] The key `searchMovieBlog` is not valid here. Only known plugin names are valid keys.
2019-02-10 00:02 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Low/discover/from/0] The key `searchHdarea` is not valid here. Only known plugin names are valid keys.
2019-02-10 00:02 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Low/discover/from/1] The key `searchHdworld` is not valid here. Only known plugin names are valid keys.
2019-02-10 00:02 CRITICAL manager                       [/tasks/Movies_Watchlist_Search_DE_Low/discover/from/2] The key `searchMovieBlog` is not valid here. Only known plugin names are valid keys.
2019-02-10 00:02 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
Could not start manager: Did not pass schema validation.
snikay@cloudBox:/etc/systemd/system$ flexget -V
2.19.5
You are on the latest release.
```

**Comment by gazpachoking** [comment]
@snickers2k Looks like your issue is from some custom plugins. We moved one of the imports they are using and they'll need updated. `from flexget.components.sites.utils import normalize_unicode`
