### ISSUE TITLE
descargas2020.py plugyn doesn't download ".torrent" file

### ISSUE THREAD

**Issue by pucelano7** [Flexget/Flexget#2332]
### Additional information:

- FlexGet version: 2.19.4
- Python version: 2.7.15rc1
- Installation method: pip
- Using daemon (yes/no): no 
- OS and version: Ubuntu 18.04

### Explanation of the problem:

Last days I have problems with "descargas2020" plugin:  It seems to recognize the new chapter but it can't find the '.torrent' file

The error log is the next:
If I execute "flexget check" the response is:

```
2019-02-08 12:54 VERBOSE  manager                       Creating new database /usr/local/bin/db-config.sqlite - DO NOT INTERU                                           PT ...
2019-02-08 12:54 VERBOSE  check                         Pre-checked 21 configuration lines
2019-02-08 12:54 VERBOSE  check                         Checking config file `/usr/local/bin/config.yml`
2019-02-08 12:54 VERBOSE  check                         Config passed check.
```

Then, when I execute "flexget --test execute" the error messages are:
```2019-02-08 12:54 INFO     manager                       Test mode, creating a copy from database ...
2019-02-08 12:54 INFO     manager                       Test database created
2019-02-08 12:54 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2019-02-08 12:54 WARNING  rss           some feed       Skipped 1 RSS-entries without required information (title, link or enclosures)
2019-02-08 12:54 VERBOSE  details       some feed       Produced 1000 entries.
2019-02-08 12:54 VERBOSE  series.db     some feed       identified by is currently on `auto` for Manifest. Multiple id types may be accepted until it locks in on the appropriate type.
2019-02-08 12:54 VERBOSE  flexget.components.series.series some feed       Ignored `Manifest - Temporada 1 [HDTV][Cap.114][Castellano][www.pctnew.com]`. Does not meet quality requirement `720p`.
2019-02-08 12:54 VERBOSE  flexget.components.series.series some feed       Ignored `Manifest - Temporada 1 [HDTV][Cap.113][Castellano][www.pctnew.com]`. Does not meet quality requirement `720p`.
2019-02-08 12:54 VERBOSE  flexget.components.series.series some feed       Ignored `Manifest - Temporada 1 [HDTV][Cap.112][Castellano][www.pctnew.com]`. Does not meet quality requirement `720p`.
2019-02-08 12:54 VERBOSE  task          some feed       ACCEPTED: `Manifest - Temporada 1 [HDTV 720p][Cap.114][AC3 5.1 Castellano][www.pctnew.com]` by series plugin because target quality
2019-02-08 12:54 VERBOSE  descargas2020 some feed       Descargas2020 URL: http://descargas2020.com/descargar/serie-en-hd/manifest/temporada-1/capitulo-14/
2019-02-08 12:54 ERROR    urlrewriter   some feed       'module' object has no attribute 'exceptions'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/urlrewriting.py", line 71, in url_rewrite
    urlrewriter.instance.url_rewrite(task, entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/sites/descargas2020.py", line 50, in url_rewrite
    entry['url'] = self.parse_download_page(entry['url'], task)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 119, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/sites/sites/descargas2020.py", line 58, in parse_download_page
    except requests.exceptions.RequestException as e:
AttributeError: 'module' object has no attribute 'exceptions'
2019-02-08 12:54 WARNING  urlrewriter   some feed       descargas2020: Internal error with url http://descargas2020.com/descargar/serie-en-hd/manifest/temporada-1/capitulo-14/
2019-02-08 12:54 ERROR    entry         some feed       Failed Manifest - Temporada 1 [HDTV 720p][Cap.114][AC3 5.1 Castellano][www.pctnew.com] (None)
2019-02-08 12:54 CRITICAL task          some feed       BUG: Unhandled error in plugin urlrewriting: year=378 is before 1900; the datetime strftime() methods require year >= 1900
2019-02-08 12:54 CRITICAL manager       some feed       An unexpected crash has occurred. Writing crash report to /usr/local/bin/crash_report.2019.02.08.125442376688.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.19.4
2019-02-08 12:54 WARNING  task          some feed       Aborting task (plugin: urlrewriting)
2019-02-08 12:54 CRITICAL task          some feed       BUG: Unhandled error in plugin backlog: year=1210 is before 1900; the datetime strftime() methods require year >= 1900
2019-02-08 12:54 CRITICAL manager       some feed       An unexpected crash has occurred. Writing crash report to /usr/local/bin/crash_report.2019.02.08.125442573262.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.19.4
2019-02-08 12:54 WARNING  task          some feed       Aborting task (plugin: backlog)
2019-02-08 12:54 ERROR    task          some feed       abort handlers aborted:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 628, in _execute
    self.__run_task_phase('abort')
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 465, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 530, in __run_plugin
    self.abort(msg, traceback=traceback)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 382, in abort
    raise TaskAbort(reason, silent=silent)
TaskAbort
```

My config.yml for doing the test is:
```templates:
  tv:
    series:
      settings:
        720p:
          quality: 720p
      720p:
        - The Magicians
    download: /usr/local/bin/torrents/

tasks:
  some feed:
    rss: http://feeds.feedburner.com/descargas2020
    template: tv
```

**Comment by gazpachoking** [comment]
Not certain if everything will work after that fix, but it will stop the current crash.
