### ISSUE TITLE
seen plugin missing forget module in db.py

### ISSUE THREAD

**Issue by therealmatey** [Flexget/Flexget#2333]
### Expected behaviour:
forget specified seen item

### Actual behaviour:
AttributeError: 'module' object has no attribute 'forget'

### Steps to reproduce:
- Step 1: flexget seen forget "movie name"

#### Config:
this is CLI issue
  
#### Log:
```
Traceback (most recent call last):
  File "c:\program files (x86)\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\program files (x86)\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Program Files (x86)\Python27\Scripts\flexget.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\flexget\__init__.py", line 42, in main
    manager.start()
  File "c:\program files (x86)\python27\lib\site-packages\flexget\manager.py", line 364, in start
    self.handle_cli()
  File "c:\program files (x86)\python27\lib\site-packages\flexget\manager.py", line 393, in handle_cli
    options.cli_command_callback(self, command_options)
  File "c:\program files (x86)\python27\lib\site-packages\flexget\components\seen\cli.py", line 21, in do_cli
    seen_forget(manager, options)
  File "c:\program files (x86)\python27\lib\site-packages\flexget\components\seen\cli.py", line 35, in seen_forget
    count, fcount = db.forget(forget_name)
AttributeError: 'module' object has no attribute 'forget'
```
### Additional information:

- FlexGet version: 2.19.3 and 2.19.4
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: windows 10 1809
- Link to crash log:

**Comment by paranoidi** [comment]
Thanks for reporting
