### ISSUE TITLE
BUG: Unhandled error in plugin discover: unorderable types: NoneType() < NoneType()

### ISSUE THREAD

**Issue by lamski** [Flexget/Flexget#2347]
Just noticed that a lot of crash logs have started occurring on Feb 1, 2019 on the Discovery plugin:
The error still happens on Flexget 2.20.10

### Expected behaviour:
No crash logs during normal usage (via daemon).

### Actual behaviour:
Produced 168 crash logs from Feb 1, 2019 to March 9, 2019

#### First Crash Log:
<details>
 <summary>(click to expand)</summary>

```
2019-02-01 08:47 CRITICAL task          discover_series BUG: Unhandled error in plugin discover: unorderable types: NoneType() < NoneType()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flexget/task.py", line 498, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/input/discover.py", line 250, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/input/discover.py", line 115, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugin.py", line 118, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/sites/piratebay.py", line 179, in search
    return sorted(entries, reverse=True, key=lambda x: x.get('search_sort'))
TypeError: unorderable types: NoneType() < NoneType()
```
</details>

#### Last Crash Log:
<details>
 <summary>(click to expand)</summary>

```
2019-03-09 05:36 CRITICAL task          discover_series BUG: Unhandled error in plugin discover: unorderable types: NoneType() < NoneType()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flexget/task.py", line 522, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/input/discover.py", line 293, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugins/input/discover.py", line 135, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
  File "/usr/local/lib/python3.4/dist-packages/flexget/plugin.py", line 126, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flexget/components/sites/sites/piratebay.py", line 187, in search
    return sorted(entries, reverse=True, key=lambda x: x.get('search_sort'))
TypeError: unorderable types: NoneType() < NoneType()
```
</details>

### Additional information:

- FlexGet version: 2.20.10
- Python version: 3.4.3
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu 14.04.6 LTS (server)
[crash_report.2019.02.01.084712535692.log](https://github.com/Flexget/Flexget/files/2947655/crash_report.2019.02.01.084712535692.log)
[crash_report.2019.03.09.053621723964.log](https://github.com/Flexget/Flexget/files/2947656/crash_report.2019.03.09.053621723964.log)

**Comment by lamski** [comment]
I think this is related to the changes in 2.19.0

**Comment by marp188** [comment]
Also noticed this:

flexget 2.21.2 running under python3.5

Discover returns the following error:

2019-05-29 09:02 CRITICAL task series_search BUG: Unhandled error in plugin discover: unorderable types: int() < NoneType()
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/flexget/task.py", line 522, in _runplugin
return method(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in call
return self.func(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/input/discover.py", line 281, in on_task_input
entries = aggregate_inputs(task, config['what'])
File "/usr/local/lib/python3.5/dist-packages/flexget/utils/tools.py", line 587, in aggregate_inputs
result = method(task, input_config)
File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in call
return self.func(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/flexget/components/series/next_series_episodes.py", line 136, in on_task_input
latest_season = db.get_latest_release(series, downloaded=check_downloaded)
File "/usr/local/lib/python3.5/dist-packages/flexget/components/series/db.py", line 1117, in get_latest_release
return max(latest_season, latest_ep)
File "/usr/lib/python3.5/functools.py", line 99, in gtfrom_lt
op_result = self.lt(other)
File "/usr/local/lib/python3.5/dist-packages/flexget/components/series/db.py", line 399, in lt
return self.season < other.season
TypeError: unorderable types: int() < NoneType()

Also, "flexget series lis" returns a similar error.

Thank you
