### ISSUE TITLE
error when checking... api-rottentomatoes...

### ISSUE THREAD

**Issue by bash64** [Flexget/Flexget#2353]
$ flexget check
2019-03-22 02:23 VERBOSE  check                         Pre-checked 6 configuration lines
2019-03-22 02:23 INFO     manager                       Database upgrade is required. Attempting now.
2019-03-22 02:23 CRITICAL schema                        A lower schema version was returned (None) from plugin api_rottentomatoes upgrade function than passed in (-1)
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/home/dad/.local/lib/python2.7/site-packages/flexget/__init__.py", line 47, in main
    manager.start()
  File "/home/dad/.local/lib/python2.7/site-packages/flexget/manager.py", line 399, in start
    self.initialize()
  File "/home/dad/.local/lib/python2.7/site-packages/flexget/manager.py", line 263, in initialize
    fire_event('manager.upgrade', self)
  File "/home/dad/.local/lib/python2.7/site-packages/flexget/event.py", line 113, in fire_event
    result = event(*args, **kwargs)
  File "/home/dad/.local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/home/dad/.local/lib/python2.7/site-packages/flexget/db_schema.py", line 180, in upgrade_wrapper
    manager.shutdown(finish_queue=False)
  File "/home/dad/.local/lib/python2.7/site-packages/flexget/manager.py", line 1042, in shutdown
    raise RuntimeError('Cannot shutdown manager that was never initialized.')
RuntimeError: Cannot shutdown manager that was never initialized.

**Comment by bash64** [comment]
System:    Host: msi-gt70-2pe Kernel: 4.15.0-45-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 Desktop: Cinnamon 4.0.9 
           Distro: Linux Mint 19.1 Tessa base: Ubuntu 18.04 bionic 

$ python -V
Python 2.7.15rc1

**Comment by paranoidi** [comment]
Your database is likely corrupted .. you can try resetting api_rottentomatoes plugin database but if that is problematic delete the database and start from scratch
