### ISSUE TITLE
maximum recursion error with cannot compare ep with sequence

### ISSUE THREAD

**Issue by vxcamiloxv** [Flexget/Flexget#2362]
### Expected behaviour:
Not should crash when the series plugin try to compare different identifiers

### Actual behaviour:
Crash when comparing different type of identifiers with a error loop
![screenshot-2019-04-11_13-02-18](https://user-images.githubusercontent.com/14242544/55984965-4d9b0200-5c64-11e9-9cb7-ebd9c86a9715.png)

### Steps to reproduce:
- Search something with `identified_by: sequence` and `discover` plugin returns something with `ep` identifier type

#### Config:
```
download-series-anime:
    priority: 10
    template:
      - common-sort
      - common-reject
    cfscraper: yes
    metainfo_series: yes
    trakt_lookup: yes
    parsing:
      series: internal
    domain_delay:
      nyaa: 20 seconds
    discover:
      what:
        - next_series_episodes:
            from_start: yes
            #backfill: yes -> has error with sequence (without season) anime
      from:
        - horriblesubs: yes
        - nyaa:
            category: anime raw
            filter: filter remakes
        - nyaa:
            category: anime eng
            filter: filter remakes
        - 1337x:
            order_by: seeders
        - limetorrents:
            category: anime
            order_by: seeds
      interval: 2 hours
      release_estimations: ignore
    manipulate:
      - title:
          replace:            
            regexp: '[^a-zA-Z0-9\-_.()\[\]\s]' # remove kanji to better parsing 
            format: ''
    torrent_alive: 2 
    magnets: no
    content_size:
      min: 20
      max: 25000
    include: anime.yml
    configure_series:
      from:
        entry_list: watchlist_series_anime
      settings:
        identified_by: sequence
        timeframe: 72 hours
        target: hr-720p hdtv+ !h265 !10bit !dts !dtshd
        qualities: 
          - dvdrip
          - 480p-720p webrip+ !h265 !10bit <=ac3
          - 480p-720p !cam !ts !bdscr !dvdscr !h265 !10bit !dts !dtshd !flac
          - webrip+ !h265 !10bit !dts !dtshd !flac
        upgrade: yes
        tracking: yes
        specials: yes
        begin: 01
        season_packs: always
        special_ids:
          - OVA
    require_field:
      - series_name
    transmission:
      <<: *transmission-secondary
      path: '{? paths.torrent_remote ?}/anime'
      add_paused: no
      main_file_only: no
      magnetization_timeout: 120
      include_subs: yes
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*[sS]ample*'
        - '*.txt'
        - '*.lnk'
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-04-11 11:55 ERROR    series.db     download-series-anime cannot compare ep with sequence 
2019-04-11 11:55 ERROR    series.db     download-series-anime cannot compare sequence with ep 
2019-04-11 11:55 ERROR    series.db     download-series-anime cannot compare ep with sequence
2019-04-11 11:55 ERROR    series.db     download-series-anime cannot compare sequence with ep
2019-04-11 11:55 ERROR    series.db     download-series-anime cannot compare ep with sequence
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 889, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/opt/flexget/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/opt/flexget/lib/python2.7/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/opt/flexget/lib/python2.7/linecache.py", line 132, in updatecache
    lines = fp.readlines()
RuntimeError: maximum recursion depth exceeded while calling a Python object
Logged from file db.py, line 378
2019-04-11 11:55 ERROR    series.db     download-series-anime cannot compare sequence with ep
```
</details>

### Additional information:

- FlexGet version: 2.20.18
- Python version: 2.7
- Installation method: pip
- Using daemon (yes/n/o): yes (but also run manually)
- OS and version: Gnu/Linux (Parabola)
- Link to crash log: https://pastebin.com/p1WEpz58

**Comment by vxcamiloxv** [comment]
To avoid the crash I just changed:  https://github.com/Flexget/Flexget/blob/develop/flexget/components/series/db.py#L379 to `False`

**Comment by snickers2k** [comment]
same here
