### ISSUE TITLE
feedparser.py error ?

### ISSUE THREAD

**Issue by Overseer486** [Flexget/Flexget#2374]
### Steps to reproduce:
- Step 1: just run flexget, eg 'flexget check'

#### Config:
```
web_server:
  bind: 0.0.0.0
  port: 3030
  web_ui: yes
  base_url: /foo
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-04-25 13:15 DEBUG    manager                       Figuring out config load paths
2019-04-25 13:15 DEBUG    manager                       Found config: /root/.config/flexget/config.yml
2019-04-25 13:15 DEBUG    manager                       Config file /root/.config/flexget/config.yml selected
2019-04-25 13:15 DEBUG    manager                       sys.defaultencoding: utf-8
2019-04-25 13:15 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2019-04-25 13:15 DEBUG    manager                       flexget detected io encoding: utf-8
2019-04-25 13:15 DEBUG    manager                       os.path.supports_unicode_filenames: False
2019-04-25 13:15 DEBUG    plugin                        Trying to load plugins from: ['/root/.config/flexget/plugins', '/usr/lib/python3.6/site-packages/flexget/plugins']
2019-04-25 13:15 DEBUG    plugin                        Plugin `memusage` requires plugin `ext lib `guppy`` to load.
2019-04-25 13:15 CRITICAL plugin                        Exception while loading plugin flexget.plugins.input.apple_trailers
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flexget/plugin.py", line 434, in _import_plugin
    import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/flexget/plugins/input/apple_trailers.py", line 7, in <module>
    import feedparser
  File "/usr/lib/python3.6/site-packages/feedparser.py", line 316
    raise KeyError, "object doesn't have key 'category'"
                  ^
SyntaxError: invalid syntax
2019-04-25 13:15 DEBUG    manager                       Removed /root/.config/flexget/.config-lock


```
</details>

### Additional information:

- FlexGet version: 2.20.21
- Python version: 3.6.5
- Installation method: pip
- Using daemon (yes/no): both
- OS and version: OpenWrt 18.06.2
- Link to crash log:

**Comment by gazpachoking** [comment]
Hmm, maybe try reinstalling feedparser with pip. It looks like somehow you got the python 2 version of feedparser installed instead of the python 3 one. The line in the traceback is how it looks in the raw source of feedparser, but when installing, 2to3 is supposed to automatically run and update that line for the python 3 syntax.

**Comment by Overseer486** [comment]
Yup, that did the trick. Thank you!
