### ISSUE TITLE
BUG: Unhandled error in plugin scan_imdb: expected string or buffer

### ISSUE THREAD

**Issue by girtsl** [Flexget/Flexget#2385]
### Expected behaviour:
Entries returned by `discover`/`torznab` are correctly parsed and handled.

### Actual behaviour:
It appears that flexget crashes on at least one entry.

### Steps to reproduce:
Not really sure how to reproduce this and what's the reason for this crash. flexget has been running with the current version and config for a couple days now. What might have triggered it - a new episode of a certain show has been found by jackett.

1. Configure flexget to have `torznab` as a search plugin for `discover`.
2. Add "The Simpsons" and "Game of Thrones" as the input for `series` or `configure_series` plugin.
3. Configure jackett with the following indexers:

![jackett](https://user-images.githubusercontent.com/6348534/57240929-7d0d1680-7038-11e9-8c2f-16839a93592e.jpg)

#### Config:
Probably not that relevant but can paste if it helps.
  
#### Log:
<details>
 <summary>BUG: Unhandled error in plugin scan_imdb: expected string or buffer (click to expand)</summary>

```
2019-05-06 18:37 VERBOSE  discover      download-shows  Searching for `The Simpsons (1989) S30E22` with plugin `torznab` (1 of 2)
2019-05-06 18:37 DEBUG    torznab       download-shows  Config: {u'website': u'http://localhost:9117/api/v2.0/indexers/all/results/torznab', u'searcher': u'tvsearch', u'apikey': u'apikey', u'categories': []}
2019-05-06 18:37 DEBUG    torznab       download-shows  Configured parameters: {u'apikey': u'apikey', 't': u'caps', u'extended': 1}
2019-05-06 18:37 DEBUG    utils.requests download-shows  GETing URL http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?apikey=apikey&t=caps&extended=1 with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2019-05-06 18:37 DEBUG    torznab       download-shows  Raw caps response <?xml version="1.0" encoding="UTF-8"?>\n<caps>\n  <server title="Jackett" />\n  <limits max="1000" default="1000" />\n  <searching>\n    <search available="yes" supportedParams="q" />\n   $
2019-05-06 18:37 DEBUG    torznab       download-shows  Searcher 'tv-search' set up with '[u'q', u'season', u'ep', u'imdbid']' parameters
2019-05-06 18:37 DEBUG    torznab       download-shows  Setting search categories to [5000, 5010, 5020, 5030, 5040, 5045, 5050, 5060, 5070, 5080]
2019-05-06 18:37 DEBUG    torznab       download-shows  Configured parameters: {u'q': u'The Simpsons (1989)', u'apikey': u'apikey', u't': u'tvsearch', u'season': 30, u'ep': 22, u'extended': 1, u'cat': u'5000,5010,5020,5030,5040,5045,505$
2019-05-06 18:37 INFO     torznab       download-shows  Fetching URL: http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?q=The+Simpsons+%281989%29&apikey=apikey&t=tvsearch&season=30&ep=22&extended=1&cat=5000%2C5010%2C5020%2$
2019-05-06 18:37 DEBUG    utils.requests download-shows  GETing URL http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?q=The+Simpsons+%281989%29&apikey=apikey&t=tvsearch&season=30&ep=22&extended=1&cat=5000%2C5010%2C5020%2C5$
2019-05-06 18:37 DEBUG    discover      download-shows  Discovered 2 entries from torznab
2019-05-06 18:37 VERBOSE  discover      download-shows  Searching for `Game of Thrones (2011) S08E04` with plugin `torznab` (2 of 2)
2019-05-06 18:37 DEBUG    torznab       download-shows  Config: {u'website': u'http://localhost:9117/api/v2.0/indexers/all/results/torznab', u'searcher': u'tvsearch', u'apikey': u'apikey', u'categories': []}
2019-05-06 18:37 DEBUG    torznab       download-shows  Configured parameters: {u'apikey': u'apikey', 't': u'caps', u'extended': 1}
2019-05-06 18:37 DEBUG    utils.requests download-shows  GETing URL http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?apikey=apikey&t=caps&extended=1 with args () and kwargs {'allow_redirects': True, u'timeout': 30}
2019-05-06 18:37 DEBUG    torznab       download-shows  Raw caps response <?xml version="1.0" encoding="UTF-8"?>\n<caps>\n  <server title="Jackett" />\n  <limits max="1000" default="1000" />\n  <searching>\n    <search available="yes" supportedParams="q" />\n   $
2019-05-06 18:37 DEBUG    torznab       download-shows  Searcher 'tv-search' set up with '[u'q', u'season', u'ep', u'imdbid']' parameters
2019-05-06 18:37 DEBUG    torznab       download-shows  Setting search categories to [5000, 5010, 5020, 5030, 5040, 5045, 5050, 5060, 5070, 5080]
2019-05-06 18:37 DEBUG    torznab       download-shows  Configured parameters: {u'q': u'Game of Thrones (2011)', u'apikey': u'apikey', u't': u'tvsearch', u'season': 8, u'ep': 4, u'extended': 1, u'cat': u'5000,5010,5020,5030,5040,5045,50$
2019-05-06 18:37 INFO     torznab       download-shows  Fetching URL: http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?q=Game+of+Thrones+%282011%29&apikey=apikey&t=tvsearch&season=8&ep=4&extended=1&cat=5000%2C5010%2C5020%$
2019-05-06 18:37 DEBUG    utils.requests download-shows  GETing URL http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?q=Game+of+Thrones+%282011%29&apikey=apikey&t=tvsearch&season=8&ep=4&extended=1&cat=5000%2C5010%2C5020%2C$
2019-05-06 18:37 DEBUG    discover      download-shows  Discovered 4 entries from torznab
2019-05-06 18:37 DEBUG    backlog.db    download-shows  0 entries purged from backlog
2019-05-06 18:37 VERBOSE  details       download-shows  Produced 6 entries.
2019-05-06 18:37 CRITICAL task          download-shows  BUG: Unhandled error in plugin scan_imdb: expected string or buffer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 522, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/components/imdb/imdb_url.py", line 33, in on_task_metainfo
    urls = re.findall(r'\bimdb.com/title/tt\d+\b', entry['description'])
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```
</details>

### Additional information:

- FlexGet version: 2.20.25
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: OSMC

**Comment by paranoidi** [comment]
Seems like entry description is not a string, likely has value None ...
