### ISSUE TITLE
Python 3.5 - "unorderable types: int() < NoneType()"

### ISSUE THREAD

**Issue by marp188** [Flexget/Flexget#2408]
flexget 2.21.2 running under python3.5

Discover returns the following error:
```
2019-05-29 09:02 CRITICAL task series_search BUG: Unhandled error in plugin discover: unorderable types: int() < NoneType()
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/flexget/task.py", line 522, in _runplugin
return method(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in call
return self.func(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/flexget/plugins/input/discover.py", line 281, in on_task_input
entries = aggregate_inputs(task, config['what'])
File "/usr/local/lib/python3.5/dist-packages/flexget/utils/tools.py", line 587, in aggregate_inputs
result = method(task, input_config)
File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in call
return self.func(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/flexget/components/series/next_series_episodes.py", line 136, in on_task_input
latest_season = db.get_latest_release(series, downloaded=check_downloaded)
File "/usr/local/lib/python3.5/dist-packages/flexget/components/series/db.py", line 1117, in get_latest_release
return max(latest_season, latest_ep)
File "/usr/lib/python3.5/functools.py", line 99, in gtfrom_lt
op_result = self.lt(other)
File "/usr/local/lib/python3.5/dist-packages/flexget/components/series/db.py", line 399, in lt
return self.season < other.season
TypeError: unorderable types: int() < NoneType()
```
Also, "flexget series lis" returns a similar error.

Thank you

**Comment by Piscinelove** [comment]
I noticed the same problem today : flexget v2.21.14
Any recent changes on IMDb ?
