### ISSUE TITLE
Getting ValueError here is my pastebin of the crashreport https://pastebin.com/iMyfgvnj

### ISSUE THREAD

**Issue by paulpoco** [Flexget/Flexget#2419]
Getting ValueError here is my pastebin of the crashreport https://pastebin.com/iMyfgvnj
```
2019-07-09 19:35 ERROR    set           karmorra        Could not set content_filename for Animal Kingdom US S04E07 720p HDTV x264 AVS: (UndefinedError) 'series_name' is undefined
2019-07-09 19:35 ERROR    set           karmorra        Could not set move_completed_path for Animal Kingdom US S04E07 720p HDTV x264 AVS: (UndefinedError) 'series_name' is undefined
2019-07-09 19:35 CRITICAL task          karmorra        BUG: Unhandled error in plugin deluge: Trying to render non string template or unrecognized template format, got None
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flexget/task.py", line 522, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/flexget/plugins/clients/deluge.py", line 377, in on_task_output
    entry.get('move_completed_path', config['move_completed_path'])
  File "/usr/lib/python3.7/site-packages/flexget/entry.py", line 300, in render
    % repr(template)
ValueError: Trying to render non string template or unrecognized template format, got None
```

I tried moving my content_filename & move_completed_path from the set section Deluge section but that just caused it download a whole bunch that already exist and it got the move_completed_path wrong and defaulted to the default deluge move completed location.

**Comment by crawln45** [comment]
without the config I'm not sure where to start with this.

**Comment by gazpachoking** [comment]
I suspect this is happening when setting a deluge option on the entry via the set plugin, and the rendering fails. Haven't tested yet though. Something like this:
```
set:
  move_completed_path: aoeu {{doesnt exist}}
deluge: yes
```
I think the failed set command will return None for entry['move_completed_path'] and the deluge plugin then tries to re-render that with jinja, causing the error.

**Comment by paulpoco** [comment]
Here is a pastebin of my sanitized config. https://pastebin.com/9rBrQUx0

Here is a pastebin of a new crash report. https://pastebin.com/PWh4cRxy

I moved the content_filename back into the deluge: section to see what happens, will report any differences later.

**Comment by paulpoco** [comment]
Good I found this error.
