### ISSUE TITLE
pathlib not installed via pip on 2.7

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/Flexget#2420]
### Expected behaviour:
Clean startup, as it was prior to 2.21.12
### Actual behaviour:
Traceback on log during every startup.
### Steps to reproduce:
- Update via pip on Python 2.7

#### Config:
- Not relevant
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-07-11 12:44 CRITICAL plugin                        Plugin `flexget.plugins.cli.debug_info` failed to import dependencies
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\plugin.py", line 434, in _import_plugin
    import_module(module_name)
  File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\python27\lib\site-packages\flexget\plugins\cli\debug_info.py", line 4, in <module>
    import pathlib
ImportError: No module named pathlib
2019-07-11 12:44 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
2019-07-11 12:44 INFO     web_server_daemon                 Initiating API
2019-07-11 12:44 INFO     web_server_daemon                 Registering WebUI v1
2019-07-11 12:44 INFO     web_server                    Web interface available at http://192.168.0.2:5050
2019-07-11 12:44 INFO     scheduler                     Starting scheduler
```
</details>

### Additional information:
_pathlib_ doesn't seem to be listed as a requirement for Python 2.7 anymore (removed on https://github.com/Flexget/Flexget/commit/1090d2e22f51ff6de3a6944cf5ea1c6000f9b309#diff-b4ef698db8ca845e5845c4618278f29aL33 ?), as indicated by `pip check flexget` returning `No broken requirements found.` instead of fetching pathlib
<details>
 <summary>pip show flexget</summary>

```
Name: FlexGet
Version: 2.21.13
Summary: FlexGet is a program aimed to automate downloading or processing content (torrents, podcasts, etc.) from different sources like RSS-feeds, html-pages, various sites and more.
Home-page: https://flexget.com
Author: Marko Koivusalo
Author-email: marko.koivusalo@gmail.com
License: MIT
Location: c:\python27\lib\site-packages
Requires: python-dateutil, zipp, cheroot, six, urllib3, webencodings, pyrss2gen, jsonschema, flask-restplus, progressbar, flask-cors, jinja2, rpyc, flask-compress, requests, idna, future, tempora, aniso8601, markupsafe, sqlalchemy, certifi, rebulk, pyyaml, tzlocal, terminaltables, guessit, pynzb, flask, portend, colorclass, chardet, itsdangerous, beautifulsoup4, flask-login, feedparser, pytz, path.py, pyparsing, plumbum, cherrypy, flask-restful, werkzeug, html5lib, importlib-metadata, apscheduler, babelfish, zxcvbn-python, click
Required-by:
```
</details>

- FlexGet version: 2.21.13
- Python version: 2.7.16
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Windows 10 x64 1903

**Comment by gazpachoking** [comment]
Thanks for the report, should be better now.
