### ISSUE TITLE
`series list` crashes depending on terminal size

### ISSUE THREAD

**Issue by fongd** [Flexget/Flexget#2431]
`flexget series list` crashes if the terminal window is narrow enough that at least two columns get removed from output.

### Expected behaviour:

Issuing the command should provide a table of all tracked series and corresponding information for each of them. Columns should be selectively removed from output if the terminal window is too narrow to accommodate all of them.

### Actual behaviour:

If the terminal window is wide enough such that `flexget series list` does not have to remove any columns or only one column has to be removed, the command works as expected:

<pre>
root@bf66f703e948:/config# flexget series list
There is a FlexGet process already running for this config, sending execution there.
Least important column `Downloaded` removed due terminal size

┌─────────────────────────────────────────┬────────┬──────────────────┬──────────┬───────────────┐
│ Name                                    │ Begin  │ Last Encountered │ Age      │ Identified By │
├─────────────────────────────────────────┼────────┼──────────────────┼──────────┼───────────────┤
│ Atlanta                                 │ -      │ S01E10           │ 1020d    │ ep            │
…
</pre>

However, if the terminal window is narrow enough such that two columns need to be removed, Flexget crashes:

<pre>
root@bf66f703e948:/config# flexget series list
There is a FlexGet process already running for this config, sending execution there.
Least important column `Downloaded` removed due terminal size
Least important column `Age` removed due terminal size
Traceback (most recent call last):
  File "/usr/bin/flexget", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/flexget/__init__.py", line 47, in main
    manager.start()
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 381, in start
    client.handle_cli(self.args)
  File "/usr/lib/python3.7/site-packages/rpyc/core/netref.py", line 199, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python3.7/site-packages/rpyc/core/netref.py", line 75, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 471, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/usr/lib/python3.7/site-packages/rpyc/core/async_.py", line 97, in value
    raise self._obj
TypeError: '<' not supported between instances of 'NoneType' and 'int'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/usr/lib/python3.7/site-packages/flexget/ipc.py", line 89, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 429, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/lib/python3.7/site-packages/flexget/components/series/cli.py", line 41, in do_cli
    display_summary(options)
  File "/usr/lib/python3.7/site-packages/flexget/components/series/cli.py", line 125, in display_summary
    options.table_type, table_data, wrap_columns=[3], drop_columns=[4, 3, 2]
  File "/usr/lib/python3.7/site-packages/flexget/terminal.py", line 84, in __init__
    self._init_table()
  File "/usr/lib/python3.7/site-packages/flexget/terminal.py", line 95, in _init_table
    self.table = self._resize_table()
  File "/usr/lib/python3.7/site-packages/flexget/terminal.py", line 203, in _resize_table
    self._drop_columns_with_wrap()
  File "/usr/lib/python3.7/site-packages/flexget/terminal.py", line 189, in _drop_columns_with_wrap
    if wrapped_width < self.MIN_WIDTH:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
</pre>

### Steps to reproduce:
- Step 1: Make your terminal window narrow enough so that two columns are removed from the output of `flexget series list`. (My default is 110 columns wide which appears to be narrow enough to trigger the crash, but YMMV.)

- Step 2: Execute `flexget series list`

#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-08-19 11:44 DEBUG    ipc.rpyc                      Exception caught
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/usr/lib/python3.7/site-packages/flexget/ipc.py", line 89, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 429, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/lib/python3.7/site-packages/flexget/components/series/cli.py", line 41, in do_cli
    display_summary(options)
  File "/usr/lib/python3.7/site-packages/flexget/components/series/cli.py", line 125, in display_summary
    options.table_type, table_data, wrap_columns=[3], drop_columns=[4, 3, 2]
  File "/usr/lib/python3.7/site-packages/flexget/terminal.py", line 84, in __init__
    self._init_table()
  File "/usr/lib/python3.7/site-packages/flexget/terminal.py", line 95, in _init_table
    self.table = self._resize_table()
  File "/usr/lib/python3.7/site-packages/flexget/terminal.py", line 203, in _resize_table
    self._drop_columns_with_wrap()
  File "/usr/lib/python3.7/site-packages/flexget/terminal.py", line 189, in _drop_columns_with_wrap
    if wrapped_width < self.MIN_WIDTH:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
2019-08-19 11:44 INFO     ipc.rpyc                      goodbye ('127.0.0.1', 40462)
```
</details>

### Additional information:

- FlexGet version: 2.21.16
- Python version: 3.7.4
- Installation method: Docker container (https://github.com/cpoppema/docker-flexget)
- Using daemon (yes/no): yes
- OS and version: Alpine 3.10

**Comment by paranoidi** [comment]
Verified

**Comment by chewy74** [comment]
I am also getting this error

Here is a Debug log if you need one

#### Log:
<details>
 <summary>(click to expand)</summary>

```
pi@pi4:~ $ source ~/flexget/bin/activate
(flexget) pi@pi4:~ $ flexget --debug series list
2019-10-04 13:35 DEBUG    manager                       Figuring out config load paths
2019-10-04 13:35 DEBUG    manager                       Adding virtualenv path
2019-10-04 13:35 DEBUG    manager                       Found config: /home/pi/flexget/config.yml
2019-10-04 13:35 DEBUG    manager                       Config file /home/pi/flexget/config.yml selected
2019-10-04 13:35 DEBUG    manager                       sys.defaultencoding: utf-8
2019-10-04 13:35 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2019-10-04 13:35 DEBUG    manager                       flexget detected io encoding: utf-8
2019-10-04 13:35 DEBUG    manager                       os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2019-10-04 13:35 DEBUG    manager                       Sending command to running FlexGet process: ['--debug', 'series', 'list']
2019-10-04 13:35 DEBUG    series.db                     latest episode for series <Series(id=699,name=Masterchef (2010))>, with downloaded set to True and season set to None
2019-10-04 13:35 DEBUG    series.db                     no season packs found for series `Masterchef (2010)` with parameters season: None, downloaded: True
2019-10-04 13:35 DEBUG    series.db                     latest episode for series <Series(id=478,name=Powers (2015))>, with downloaded set to True and season set to None
2019-10-04 13:35 DEBUG    series.db                     no season packs found for series `Powers (2015)` with parameters season: None, downloaded: True
2019-10-04 13:35 DEBUG    series.db                     latest episode for series <Series(id=587,name=Real Time with Bill Maher (2003))>, with downloaded set to True and season set to None
2019-10-04 13:35 DEBUG    series.db                     no season packs found for series `Real Time with Bill Maher (2003)` with parameters season: None, downloaded: True
2019-10-04 13:35 DEBUG    series.db                     latest episode for series <Series(id=546,name=Shameless (2011))>, with downloaded set to True and season set to None
2019-10-04 13:35 DEBUG    series.db                     no season packs found for series `Shameless (2011)` with parameters season: None, downloaded: True
Least important column `Downloaded` removed due terminal size
Least important column `Age` removed due terminal size
Traceback (most recent call last):
  File "/home/pi/flexget/bin/flexget", line 10, in <module>
    sys.exit(main())
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/__init__.py", line 47, in main
    manager.start()
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/manager.py", line 381, in start
    client.handle_cli(self.args)
  File "/home/pi/flexget/lib/python3.7/site-packages/rpyc/core/netref.py", line 199, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/pi/flexget/lib/python3.7/site-packages/rpyc/core/netref.py", line 75, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/pi/flexget/lib/python3.7/site-packages/rpyc/core/protocol.py", line 471, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/pi/flexget/lib/python3.7/site-packages/rpyc/core/async_.py", line 97, in value
    raise self._obj
TypeError: '<' not supported between instances of 'NoneType' and 'int'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/pi/flexget/lib/python3.7/site-packages/rpyc/core/protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/pi/flexget/lib/python3.7/site-packages/rpyc/core/protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/ipc.py", line 89, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/manager.py", line 429, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/components/series/cli.py", line 41, in do_cli
    display_summary(options)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/components/series/cli.py", line 125, in display_summary
    options.table_type, table_data, wrap_columns=[3], drop_columns=[4, 3, 2]
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/terminal.py", line 84, in __init__
    self._init_table()
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/terminal.py", line 95, in _init_table
    self.table = self._resize_table()
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/terminal.py", line 203, in _resize_table
    self._drop_columns_with_wrap()
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/terminal.py", line 189, in _drop_columns_with_wrap
    if wrapped_width < self.MIN_WIDTH:
TypeError: '<' not supported between instances of 'NoneType' and 'int'


```
</details>

**Comment by ksurl** [comment]
#### Log:
<details>
 <summary>(click to expand)</summary>

```
flexget series list
There is a FlexGet process already running for this config, sending execution there.
Least important column `Downloaded` removed due terminal size
Least important column `Age` removed due terminal size
Traceback (most recent call last):
  File "/home/USER/.venv/flexget/bin/flexget", line 8, in <module>
    sys.exit(main())
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/__init__.py", line 41, in main
    manager.start()
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/manager.py", line 343, in start
    client.handle_cli(self.args)
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/rpyc/core/netref.py", line 199, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/rpyc/core/netref.py", line 75, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/rpyc/core/protocol.py", line 471, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/rpyc/core/async_.py", line 97, in value
    raise self._obj
TypeError: '<' not supported between instances of 'NoneType' and 'int'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/rpyc/core/protocol.py", line 329, in _dispatch_request        res = self._HANDLERS[handler](self, *args)
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/rpyc/core/protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/ipc.py", line 95, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/manager.py", line 391, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/components/series/cli.py", line 38, in do_cli         display_summary(options)
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/components/series/cli.py", line 122, in display_summary
    options.table_type, table_data, wrap_columns=[3], drop_columns=[4, 3, 2]
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/terminal.py", line 86, in __init__
    self._init_table()
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/terminal.py", line 97, in _init_table
    self.table = self._resize_table()
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/terminal.py", line 205, in _resize_table
    self._drop_columns_with_wrap()
  File "/home/USER/.venv/flexget/lib/python3.7/site-packages/flexget/terminal.py", line 191, in _drop_columns_with_wrap    if wrapped_width < self.MIN_WIDTH:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
</details>

same for me

FlexGet version: 3.1.5
Python version: 3.6.8 and 3.7.5 (2 servers)
Installation method: virtualenv
Using daemon: yes
OS and version: Ubuntu 16.04.6 and Ubuntu 18.04.3 LTS (2 servers)

**Comment by numericOverflow** [comment]
Also happening for me on Win2012R2x64 using anaconda

```
(py37) C:\Users\Administrator>flexget --version
3.1.28
Latest release: 3.1.29

(py37) C:\Users\Administrator>python --version
Python 3.7.6

```

```
(py37) C:\Users\Administrator>flexget series list
Least important column `Downloaded` removed due terminal size
Least important column `Age` removed due terminal size
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\py37\lib\runpy.py", line 193, in _run_modu
le_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\py37\Scripts\flexget.exe\__main__.py", lin
e 7, in <module>
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\__init__.py
", line 41, in main
    manager.start()
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\manager.py"
, line 367, in start
    self.handle_cli()
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\manager.py"
, line 396, in handle_cli
    options.cli_command_callback(self, command_options)
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\components\
series\cli.py", line 38, in do_cli
    display_summary(options)
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\components\
series\cli.py", line 122, in display_summary
    options.table_type, table_data, wrap_columns=[3], drop_columns=[4, 3, 2]
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\terminal.py
", line 95, in __init__
    self._init_table()
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\terminal.py
", line 106, in _init_table
    self.table = self._resize_table()
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\terminal.py
", line 214, in _resize_table
    self._drop_columns_with_wrap()
  File "c:\programdata\anaconda3\envs\py37\lib\site-packages\flexget\terminal.py
", line 200, in _drop_columns_with_wrap
    if wrapped_width < self.MIN_WIDTH:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by numericOverflow** [comment]
NOTE: if I increase the terminal window's width, then it will run and output results as expected w/out error, so I'm guessing it's an issue with the logic to accommodate a smaller output area.

**Comment by liiight** [comment]
I'll start by adding logs to `TerminalTable` method because trying to figure out what's going on there is kinda tricky

**Comment by fongd** [comment]
FWIW, this is no longer crashing for me. I'm still running Flexget in the same Docker container:

```
root@a3fe03a7e9d0:/config# python3 -V
Python 3.7.5
root@a3fe03a7e9d0:/config# flexget -V
3.1.50
You are on the latest release.
```
