### ISSUE TITLE
if list_type != 'episode' and not item[list_type]['title']: KeyError: 'movie'

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2445]
log says "bug", so i hope i'm right posting the issue here. sorry if not.
i tried the same task but just changed the list (with only 20 items , instead of 2000). the small one works. the big one works for hundreds of movies, but then breaks.
so i guess there is some weird name in the big list. maybe with the translated title to german.

```
2019-09-25 19:09 VERBOSE  trakt_list    Sync_Movies_Flexget Found `de` translation for movie `Alice in Wonderland`: Alice in Wonderland
2019-09-25 19:09 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 48, in run
    self.current_task.execute()
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 80, in wrapper
    return func(self, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 693, in execute
    self._execute()
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 659, in _execute
    self.__run_task_phase(phase)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 492, in __run_task_phase
    for e in response:
  File "/usr/local/lib/python3.6/dist-packages/flexget/utils/cached_input.py", line 201, in __iter__
    for item in self.iterable:
  File "/usr/local/lib/python3.6/dist-packages/flexget/components/trakt/trakt_list.py", line 246, in get_items
    if list_type != 'episode' and not item[list_type]['title']:
KeyError: 'movie'

```

```
  Sync_Movies_Flexget: 
    priority: 3
    template: 
      - no_seen
      - no_global
    accept_all: yes 
    trakt_list:
      account: '{? trakt.acc ?}'
      list: watchlist
      type: movies
      language: de
      strip_dates: yes
    list_add:
      - movie_list: Default #save with unique-ID for explicit matches after searching with regexp
      - entry_list: Default #save with regexp (global-filter) so we get searchable titles
    list_remove:
      - trakt_list:
          account: '{? trakt.acc ?}'
          list: '{? movies.list.Importlist ?}'
          type: movies
```

### Additional information:

- FlexGet version: 2.21.19
- Python version: 3.6
- OS and version: ubuntu 18

**Comment by paranoidi** [comment]
I added some checks for the crash, please test version v2.21.23+ and report the warnings.
