### ISSUE TITLE
Series' from_group filter merging instead of overwriting values

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/Flexget#2453]
### Expected behaviour:
Setting a `from_group` filter under a grouped series entry to use only that value.

### Actual behaviour:
`from_group` tries to merge the [Settings Group](https://flexget.com/Plugins/series/per_group_settings) value with the specific show value.
If both the settings group's and shows' `from_group` are:
- Lists: the values are merged, meaning we can't exclude a release group defined in the settings group (_Show 2_ in the example below will match both _Group A_ and _Group B_. One would expect to only match _Group B_)
- Mixed: If the `from_group` values defined in the show and the setting group have different formats (_Show 3_ in the example below), Flexget crashes (see Log below)
- Single string: Works as intended, as in the specific value overrides the setting group's. Had I defined _Group B_ under _myshows_, _Show 1_ would match _Group B_, _Show 3_ would match _Group A_ as specifically defined (assuming _Show 2_ hadn't mixed formats to cause a crash as mentioned above)
### Steps to reproduce:
- Step 1: Have a series settings group
- Step 2: Define `from_group` in the settings
- Step 3: Assign a series to the settings group
- Step 4: refine the series' setting with its own `from_group`
#### Config:
```yaml
mytask:
  series:
    settings:
      myshows:
        from_group:
          - Group A
          - Group B
    myshows:
      - Show 1
      - Show 2:
          from_group:
            - Group B
      - Show 3:
          from_group: Group A
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-10-12 14:13 CRITICAL task          mytask BUG: Unhandled error in plugin configure_series: u"Merging key from_group failed, conflicting datatypes 'list' vs. 'unicode'."
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 522, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\components\series\configure_series.py", line 93, in on_task_prepare
    self.merge_config(task, series_config)
  File "c:\python27\lib\site-packages\flexget\components\series\series.py", line 327, in merge_config
    native_series = self.prepare_config(task.config.get('series', {}))
  File "c:\python27\lib\site-packages\flexget\components\series\series.py", line 294, in prepare_config
    config = self.apply_group_options(config)
  File "c:\python27\lib\site-packages\flexget\components\series\series.py", line 268, in apply_group_options
    merge_dict_from_to(group_settings, series_settings)
  File "c:\python27\lib\site-packages\flexget\utils\tools.py", line 181, in merge_dict_from_to
    % (k, type(v).__name__, type(d2[k]).__name__)
MergeException: u"Merging key from_group failed, conflicting datatypes 'list' vs. 'unicode'."
```
</details>

### Additional information:

- FlexGet version: 2.21.25
- Python version: 2.7.16
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: W10
- Link to crash log:

**Comment by BrutuZ** [comment]
## Example 1 👍 
Will overwrite the setting, accepting only GroupC.
The intended behavior as described in the wiki
> Series may override any settings specified in group settings.
### Config:
```yaml
  mytask:
    mock:
      - title: '[GroupA] Cool Show - 01 [1080p]'
      - title: '[GroupB] Cool Show - 01 [720p]'
      - title: '[GroupC] Cool Show - 01 [360p]'
    series:
      settings:
        my_shows:
          from_group: GroupB
      my_shows:
        - Cool Show:
            qualities: ['1080p', '720p', '360p']
            from_group: GroupC
```

### Log:
```
VERBOSE  details       mytask          Produced 3 entries.                                                               
VERBOSE  task          mytask          ACCEPTED: `[GroupC] Cool Show - 01 [360p]` by series plugin because quality wanted
VERBOSE  details       mytask          Summary - Accepted: 1 (Rejected: 0 Undecided: 2 Failed: 0)                        
WARNING  task          mytask          Task doesn't have any output plugins, you should add (at least) one!              
```

## Example 2 👎 
In list format, `from_group` settings are merged instead of overwritten.
### Config:
```diff
  mytask:
    mock:
      - title: '[GroupA] Cool Show - 01 [1080p]'
      - title: '[GroupB] Cool Show - 01 [720p]'
      - title: '[GroupC] Cool Show - 01 [360p]'
    series:
      settings:
        my_shows:
          identified_by: sequence
-          from_group: GroupB
+          from_group: 
+            - GroupB
      my_shows:
        - Cool Show:
            qualities: ['1080p', '720p', '360p']
-           from_group: GroupC
+           from_group:
+             - GroupC
```
### Log:
```
VERBOSE  details       mytask          Produced 3 entries.                                                               
VERBOSE  task          mytask          ACCEPTED: `[GroupB] Cool Show - 01 [720p]` by series plugin because quality wanted
VERBOSE  task          mytask          ACCEPTED: `[GroupC] Cool Show - 01 [360p]` by series plugin because quality wanted
VERBOSE  details       mytask          Summary - Accepted: 2 (Rejected: 0 Undecided: 1 Failed: 0)                        
```

## Example 3 ⚠️
Flexget crashes with mixed and matched value types.
## Config:
```diff
  mytask:
    mock:
      - title: '[GroupA] Cool Show - 01 [1080p]'
      - title: '[GroupB] Cool Show - 01 [720p]'
      - title: '[GroupC] Cool Show - 01 [360p]'
    series:
      settings:
        my_shows:
          identified_by: sequence
-         from_group: GroupB
+         from_group:
+           - GroupB
      my_shows:
        - Cool Show:
            qualities: ['1080p', '720p', '360p']
            from_group: GroupC
```
### Log:
```
CRITICAL task          mytask          BUG: Unhandled error in plugin series_db: u"Merging key from_group failed, conflicting datatypes 'list' vs. 'unicode'."
CRITICAL manager       mytask          An unexpected crash has occurred. Writing crash report to crash_report.2019.10.25.140923473000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.21.30
WARNING  task          mytask          Aborting task (plugin: series_db)
```
### Debug:
```
CRITICAL task          mytask          BUG: Unhandled error in plugin series_db: u"Merging key from_group failed, conflicting datatypes 'list' vs. 'unicode'."
Traceback (most recent call last):
  File "~\flexget\.install\lib\site-packages\flexget\task.py", line 522, in __run_plugin
    return method(*args, **kwargs)
  File "~\flexget\.install\lib\site-packages\flexget\event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "~\flexget\.install\lib\site-packages\flexget\components\series\series.py", line 1099, in on_task_start
    config = self.prepare_config(task.config['series'])
  File "~\flexget\.install\lib\site-packages\flexget\components\series\series.py", line 294, in prepare_config
    config = self.apply_group_options(config)
  File "~\flexget\.install\lib\site-packages\flexget\components\series\series.py", line 268, in apply_group_options
    merge_dict_from_to(group_settings, series_settings)
  File "~\flexget\.install\lib\site-packages\flexget\utils\tools.py", line 181, in merge_dict_from_to
    % (k, type(v).__name__, type(d2[k]).__name__)
MergeException: u"Merging key from_group failed, conflicting datatypes 'list' vs. 'unicode'."
```

**Comment by BrutuZ** [comment]
Adding `list` to these tuples solves the use-case above.
https://github.com/Flexget/Flexget/blob/ea11cdccce95c6513d8be9978bdd9d0baeb88b7b/flexget/utils/tools.py#L173-L174

Any immediate thoughts on what kind of issues this could incur on other plugins?
