### ISSUE TITLE
KeyError, "object doesn't have key 'category'" in feedparser

### ISSUE THREAD

**Issue by fiskhandlarn** [Flexget/Flexget#2463]
### Expected behaviour:

That flexget runs as daemon or at all.

### Actual behaviour:

Chokes on `raise KeyError, "object doesn't have key 'category'"`

### Steps to reproduce:

This happens with my old config before upgrading tonight, but for simplicity's sake I've tried with the config from https://github.com/Flexget/Flexget/issues/2374.

So, I run flexget like this:
``` bash
flexget check -c /tmp/test.yml
```

#### Config:
`test.yml`:
``` yml
web_server:
  bind: 0.0.0.0
  port: 3030
  web_ui: yes
  base_url: /tmp
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-10-20 21:22 CRITICAL plugin                        Exception while loading plugin flexget.plugins.input.rss
Traceback (most recent call last):
  File "/opt/lib/python3.6/site-packages/flexget/plugin.py", line 434, in _import_plugin
    import_module(module_name)
  File "/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/lib/python3.6/site-packages/flexget/plugins/input/rss.py", line 16, in <module>
    import feedparser
  File "/opt/lib/python3.6/site-packages/feedparser.py", line 316
    raise KeyError, "object doesn't have key 'category'"
                  ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/opt/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/opt/lib/python3.6/site-packages/flexget/__init__.py", line 47, in main
    manager.start()
  File "/opt/lib/python3.6/site-packages/flexget/manager.py", line 399, in start
    self.initialize()
  File "/opt/lib/python3.6/site-packages/flexget/manager.py", line 236, in initialize
    extra_components=[os.path.join(self.config_base, 'components')],
  File "/opt/lib/python3.6/site-packages/flexget/plugin.py", line 561, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
  File "/opt/lib/python3.6/site-packages/flexget/plugin.py", line 481, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
  File "/opt/lib/python3.6/site-packages/flexget/plugin.py", line 434, in _import_plugin
    import_module(module_name)
  File "/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/lib/python3.6/site-packages/flexget/plugins/input/rss.py", line 16, in <module>
    import feedparser
  File "/opt/lib/python3.6/site-packages/feedparser.py", line 316
    raise KeyError, "object doesn't have key 'category'"
                  ^
SyntaxError: invalid syntax
```
</details>

### Additional information:

I've tried reinstalling feedparser with pip3 as suggested in https://github.com/Flexget/Flexget/issues/2374#issuecomment-486667154 with but to no avail.

- FlexGet version: 2.21.28
- Python version: 3.6.2
- Installation method: 
``` bash
opkg install python3-lib2to3
pip3 install python-dotenv
pip3 install transmissionrpc
pip3 install flexget
```
- Using daemon (yes/no): yes (usually only daemon, in this example no)
- OS and version: 4.14.24-qnap
- Link to crash log:

**Comment by fqx** [comment]
I faced a similar bug with optware, to fix this, I did following things in this order:
1. install python3-lib2to3
2. make sure 2to3 works in command line
3. force reinstall feedparser with pip3
4. flexget check

**Comment by gazpachoking** [comment]
Yeah, we've seen this before, somehow feedparser gets installed improperly. Hopfully @fqx's instructions can get it fixed for you. It looks like there is a new version of feedparser in the works, this should be a thing of the past once feedparser 6.0 gets released.
