### ISSUE TITLE
Notify (Pushbullet) Plugin Error.

### ISSUE THREAD

**Issue by FeromonDE** [Flexget/Flexget#2507]
Hi, since last week i have this error in my log. Up to this point everything worked without problems.
```
2019-11-13 10:30 ERROR    notify_entry  NexBox    'x-ratelimit-reset'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flexget/components/notify/notify.py", line 104, in send_notification
    send_notification(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/components/notify/notification_framework.py", line 124, in send_notification
    title, message, rendered_config
  File "/usr/local/lib/python3.5/dist-packages/flexget/components/notify/notifiers/pushbullet.py", line 89, in notify
    self.send_push(key, title, message, config.get('url'), d, 'device_iden')
  File "/usr/local/lib/python3.5/dist-packages/flexget/components/notify/notifiers/pushbullet.py", line 130, in send_push
    int(response.headers['X-Ratelimit-Reset'])
  File "/usr/local/lib/python3.5/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-ratelimit-reset'
```
Flexget: 2.21.32
API: 1.5.0

Same with Flexget 3.0.8 and Python 3.8

**Comment by BrutuZ** [comment]
Having the same problem. The push message goes trough, but these errors show up in the log.
From a simple test manually sending the message, I did not get the `X-Ratelimit-` fields on the response header of a regular push. Could they be sending those only when reaching the rate limit?

If that's the case (can't test it while not rate limited) omitting the following debug message should be enough.
https://github.com/Flexget/Flexget/blob/00bba32cd38127f82e6ceb67ce73d147c1f37652/flexget/components/notify/notifiers/pushbullet.py#L128-L137

**Comment by FeromonDE** [comment]
> 
> 
> Having the same problem. The push message goes trough, but these errors show up in the log.
> From a simple test manually sending the message, I did not get the `X-Ratelimit-` fields on the response header of a regular push. Could they be sending those only when reaching the rate limit?
> 
> If that's the case (can't test it while not rate limited) omitting the following debug message should be enough.
> 
> https://github.com/Flexget/Flexget/blob/00bba32cd38127f82e6ceb67ce73d147c1f37652/flexget/components/notify/notifiers/pushbullet.py#L128-L137

No, it does not help.
```
2019-11-27 01:12 ERROR    notify_entry  Rutor_BDRip _1080p 'x-ratelimit-reset'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flexget/components/notify/notify.py", line 101, in send_notification
    send_notification(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flexget/components/notify/notification_framework.py", line 121, in send_notification
    notifier_plugin.notify(
  File "/usr/local/lib/python3.8/site-packages/flexget/components/notify/notifiers/pushbullet.py", line 88, in notify
    self.send_push(key, title, message, config.get('url'), d, 'device_iden')
  File "/usr/local/lib/python3.8/site-packages/flexget/components/notify/notifiers/pushbullet.py", line 129, in send_push
    #            int(response.headers['X-Ratelimit-Reset'])
  File "/usr/local/lib/python3.8/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-ratelimit-reset'
```

**Comment by liiight** [comment]
Accidentally "fixed" the wrong plugin 🤣

**Comment by gazpachoking** [comment]
Shouldn't we fix here too? https://github.com/Flexget/Flexget/blob/6d927bc779ec2c10f59bde6bb9d6b3a0ae2adda2/flexget/components/notify/notifiers/pushbullet.py#L128

**Comment by BrutuZ** [comment]
I'd think so
```
2019-11-30 16:03 ERROR    notify_entry  download-movies-1080p-discover 'x-ratelimit-reset'
Traceback (most recent call last):
  File ".\flexget\flexget\components\notify\notify.py", line 101, in send_notification
    send_notification(*args, **kwargs)
  File ".\flexget\flexget\components\notify\notification_framework.py", line 122, in send_notification
    title, message, rendered_config
  File ".\flexget\flexget\components\notify\notifiers\pushbullet.py", line 93, in notify
    self.send_push(key, title, message, config.get('url'))
  File ".\flexget\flexget\components\notify\notifiers\pushbullet.py", line 128, in send_push
    int(response.headers['X-Ratelimit-Reset'])
  File ".\flexget\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-ratelimit-reset'
```
