### ISSUE TITLE
Lazy lookup and tvdb lookup error 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#2515]
### Expected behaviour:
For lookup to return series name and create series folder name. 

### Actual behaviour:
Lookup fails and series name and folder created only named "none" 

This only appears to be happening to the series *Mr. Robot* only. 

### Steps to reproduce:
- Step 1: ...
Match series name Mr. Robot 

#### Config:

```
web_server: yes
variables: secret.yml
templates:
  global:
    no_entries_ok: yes
    notify:
      abort:
        via:
         - telegram:
             bot_token: '{? telegram.token ?}'
             parse_mode: markdown
             disable_previews: no
             recipients:
               - username: '{? telegram.usr ?}'


##################################################################
#    TV TEMPLATE
##################################################################

  vic_tv:
    set:
      path: /media/CHEWYHDD/CHEWY/Videos/temp
      move_completed_path: /media/CHEWYHDD/CHEWY/Videos/TV/NEW EPISODES/{{tvdb_series_name}}/Season {{tvdb_season}}/
      label: NEW EPISODES
    configure_series:
      from:
        trakt_list:
          username: '{? trak.usr ?}'
          account: '{? trak.acct ?}'
          list: vic tv
          type: shows
      settings:
        quality: 1080p
        propers: 16 hours
        specials: no
    verify_ssl_certificates: no
    thetvdb_lookup: yes
    series:
      - Shameless (2011):
          alternate_name: Shameless (US)
      - Powers (2015):
          alternate_name: Powers (US)
      - Real Time with Bill Maher (2003):
          identified_by: ep
      - Masterchef (2010):
          alternate_name: Masterchef (US)      
    deluge:
      host: localhost
      port: '{? deluge.port ?}'
      username: '{? deluge.usr ?}'
      password: '{? deluge.pwd ?}'

##################################################################
#    DOWNLOAD NOTIFICATION TEMPLATE
##################################################################


  telegram_notify:
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    notify:
      entries:
        title: 'flexget {{task}}'
        message: |+
          {% if series_name is defined -%}
          *{{series_name}}* - {{series_id}} - {{quality|d('')}}
          *{{tvmaze_ep_name|d(tvdb_ep_name)|d('')}}*
          *Air date:* {{tvdb_ep_air_date|d(tvmaze_episode_airdate)|d('')}}
          *Summary:* {{tvdb_ep_overview}}
          [Image]({{tvmaze_series_original_image|replace("_", "%5F")}})
          [Show page]({{tvmaze_series_url|replace("_", "%5F")}})
          {% elif imdb_name is defined -%}
          *{{imdb_name}}* - ({{imdb_year}})
          {{quality|d('')}}
          {{imdb_score}}/10 - {{imdb_votes}} votes
          {{imdb_genres|join(', ')|title}} 
          *Plot:* {{imdb_plot_outline}}
          [Image]({{tmdb_posters[0]|replace("_", "%5F")}})
          [Movie Page]({{imdb_url|d('')}})
          {% else -%}
          {{title}}
          {%- endif -%}
        via:
         - telegram:
             bot_token: '{? telegram.token ?}'
             parse_mode: markdown
             disable_previews: no
             recipients:
               - username: '{? telegram.usr ?}'



#################################################################
#    FILTERS TEMPLATES
##################################################################

  filters:
    regexp:
      reject:
        - \bmsd\b: {from: title}
        - \bgreek\b: {from: title}
        - \bgerman\b: {from: title}
        - \bfrench\b: {from: title}
        - \brussian\b: {from: title}
        - \bswedish\b: {from: title}
        - \bspanish\b: {from: title}
        - \bhindi\b: {from: title}
        - \barabic\b: {from: title}
        - \bitalian\b: {from: title}
        - \bpolish\b: {from: title}
        - \bromanian\b: {from: title}
        - \bdutch\b: {from: title}
        - \bczech\b: {from: title}
        - \bturkish\b: {from: title}
        - \brmvb\b: {from: title}
#        - \bkorean\b: {from: title}
        - \bwmv\b: {from: title}
#        - (s|d)ub(s|bed)?\b: {from: title}
        - \bFRENCH\b: {from: title}
        - \bSPANiSH\b: {from: title}
        - \bLatino\b: {from: title}
        - \btrailer\b: {from: title}
        - \bHDTC\b: {from: title} 
        - \bHDTS\b: {from: title}
        - \bHQTS\b: {from: title}
        - \bHDcam\b: {from: title} 
        - \bR5\b: {from: title}
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}                              # The following are groups with poor quality releases
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \bFLEET\b: {from: title}
        - \b0SEC\b: {from: title}
        - \[facepalm\]: {from: title}
        - FASTSUB: {from: title}
        - VOSTFR: {from: title}
        - Subtitulado: {from: title}
        - \bNORDiC\b: {from: title}
        - \biPad\b: {from: title}
#        - \b(ita|ger|fra|spa|swe|nor|nordic|fr|kor|uk|esp|nl|pl|spanish)\b: {from: title}
        - \bR6\b: {from: title}
        - \bTemporada\b: {from: title}
        - \bDual\b: {from: title}
        - \bTamil*\b: {from: title}
        - \bJapanese\b: {from: title}
        - \bJajji!\b: {from: title}
        - \bdragons.den.(ca|uk)\b: {from: title}
        - \bx265\b: {from: title}
#        - \HC\b: {from: title}
        - \b480p\b: {from: title}
        - \b.TamilRock*\b: {from: title}
        - \b1xbet\b: {from: title}
        - \bCAMRip\b: {from: title}
        - \bHDCAMRip\b: {from: title}


##################################################################
#    TASK SCHEDULES
##################################################################


schedules:

  - tasks: tv_shows
    interval:
      minutes: 5




##################################################################
#    TASKS 
##################################################################


tasks:

  tv_shows:
    priority: 1
    template:
      - vic_tv
      - telegram_notify
      - filters
    inputs:
      - rss: '{? btn.url ?}'
#      - rss: '{? mtv.url ?}'





```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-12-01 22:11 INFO     download      tv_shows        Downloading: Mr. Robot - S04E09 [ 2019 ] [ MKV | H.264 | WEB-DL | 1080p | Scene | FastTorrent ] [ Uploader: Anonymous ]  [ Mr.Robot.S04E09.1080p.WEB.h264-TBS ]
2019-12-01 22:11 INFO     deluge_client.client tv_shows        Connecting to localhost:xxxxx
2019-12-01 22:11 INFO     deluge_client.client tv_shows        Connecting to localhost:xxxxx
2019-12-01 22:11 ERROR    lazy_lookup   tv_shows        Unhandled error in lazy lookup plugin: DELETE statement on table 'tvdb_series_genres' expected to delete 1 row(s); Only 2 were matched.
2019-12-01 22:11 CRITICAL manager       tv_shows        An unexpected crash has occurred. Writing crash report to /home/pi/flexget/crash_report.2019.12.01.221108201368.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.0.12
2019-12-01 22:11 ERROR    lazy_lookup   tv_shows        Unhandled error in lazy lookup plugin: DELETE statement on table 'tvdb_series_genres' expected to delete 1 row(s); Only 2 were matched.
2019-12-01 22:11 CRITICAL manager       tv_shows        An unexpected crash has occurred. Writing crash report to /home/pi/flexget/crash_report.2019.12.01.221108201368.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.0.12
2019-12-01 22:11 ERROR    lazy_lookup   tv_shows        Unhandled error in lazy lookup plugin: DELETE statement on table 'tvdb_series_genres' expected to delete 1 row(s); Only 2 were matched.
Traceback (most recent call last):
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/lazy_dict.py", line 35, in __getitem__
    func(self.store)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/components/thetvdb/thetvdb_lookup.py", line 161, in lazy_episode_lookup
    episode = plugin_api_tvdb.lookup_episode(**lookupargs)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/components/thetvdb/api_tvdb.py", line 633, in lookup_episode
    series = lookup_series(name=name, tvdb_id=tvdb_id, only_cached=only_cached, session=session)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/components/thetvdb/api_tvdb.py", line 569, in lookup_series
    _update_search_strings(series, session, search=name)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/components/thetvdb/api_tvdb.py", line 509, in _update_search_strings
    search_strings = series.search_strings
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 710, in get
    value = self.callable_(state, passive)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 730, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 872, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 541, in all
    return list(self)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 439, in __iter__
    self.session._autoflush()
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1577, in _autoflush
    self.flush()
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2470, in flush
    self._flush(objects)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2608, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 540, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/dependency.py", line 1177, in process_saves
    uowcommit, secondary_insert, secondary_update, secondary_delete
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/dependency.py", line 1207, in _run_crud
    result.rowcount,
sqlalchemy.orm.exc.StaleDataError: DELETE statement on table 'tvdb_series_genres' expected to delete 1 row(s); Only 2 were matched.
  compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2568, in _flush
    flush_context.execute()
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/pi/flexget/lib/python3.7/s
```
</details>

### Additional information:

- FlexGet version: 3.0.12
- Python version: 3.7
- Installation method: pip - virtual environment 
- Using daemon (yes/no):yes
- OS and version: Raspberry Pi 4, buster 
- Link to crash log:

**Comment by snickers2k** [comment]
same here. cant match series "mr robot"
