### ISSUE TITLE
Deluge crashes

### ISSUE THREAD

**Issue by paranoidi** [Flexget/Flexget#2521]
#### Log:
<details>
 <summary>click</summary>

```
BUG: Unhandled error in plugin deluge: [Errno 111] Connection refused                                                                           Traceback (most recent call last):
  File "/home/paranoidi/apps/flexget/flexget/task.py", line 520, in __run_plugin
    result = method(*args, **kwargs)
  File "/home/paranoidi/apps/flexget/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/home/paranoidi/apps/flexget/flexget/plugins/clients/deluge.py", line 296, in on_task_output    client.connect()
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/deluge_client/client.py", line 78, in connect
    self._connect()
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/deluge_client/client.py", line 92, in _connect
    self._socket.connect((self.host, self.port))
  File "/usr/lib/python3.7/ssl.py", line 1172, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.7/ssl.py", line 1159, in _real_connect
    super().connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused
```
</details>

### Additional information:

- FlexGet version: latest

**Comment by gazpachoking** [comment]
Hmm, we need to catch that error and report properly, but it looks like your issue is just having the wrong port configured in deluge plugin.
