### ISSUE TITLE
Archive plugin crashes

### ISSUE THREAD

**Issue by soloam** [Flexget/Flexget#2534]
### Expected behaviour:
 The task should seems to stop on inserting entry to the archive, if some error is occurring it should not result in a crash.

### Actual behaviour:
The task is crashing and stoping to processe

### Steps to reproduce:
Don't konw if this can be reproduced outside my config, hope the log can help, if not please advice on possible ways to share scenario.

#### Config:
```yaml


templates:
  anime:
    manipulate:
      - title:
          extract: (.*)EP(.*)
    magnets: no
    thetvdb_lookup: yes
    exists_series: 
      - '{? system.root.server ?}/{? system.path.anime.path ?}/{? system.path.anime.dir_mask ?}/'
      - '{? system.root.server ?}/{? system.path.manual ?}/'
      - '{? system.root.downloaded ?}/downloaded/{? system.path.anime.path ?}/'
      - '{? system.root.downloaded ?}/downloaded/{? system.path.manual ?}/'
      - '{? system.root.extracted ?}/extracted/{? system.path.anime.path ?}/'
      - '{? system.root.extracted ?}/extracted/{? system.path.manual ?}/'
      - '{? system.root.downloading ?}/'
    transmission:
      host: '{? transmission.host ?}'
      path: '{? transmission.path ?}/{? system.path.anime.path ?}/'
      #content_filename: '{? system.path.anime.file_mask ?}'
    content_size:
      max: 15000
      min: 100

  anime720:
    configure_series:
      from:
        trakt_list:
          account: '{? trakt.user ?}'
          type: shows
          list: '{? trakt.animelist720 ?}'
          strip_dates: yes
      settings:
        quality: '{? system.quality.an2 ?}'
        timeframe: 4 hours
        target: '{? system.quality.an2b ?}'
        identified_by: sequence

tasks:
  Anime_720:
    template: 
      - anime
      - anime720
    rss: 
      url: 'http://tracker.com/?p=rss'
      all_entries: no
    archive: [anime, '720']
    priority: 16

```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-12-12 14:41 CRITICAL task          Anime_720 BUG: Unhandled error in plugin archive: Multiple rows were found for one()
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3275, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3253, in one_or_none
    "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flexget/task.py", line 522, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flexget/components/archive/archive.py", line 36, in on_task_learn
    tags.append(db.get_tag(tag_name, task.session))
  File "/usr/local/lib/python3.5/dist-packages/flexget/components/archive/db.py", line 143, in get_tag
    return session.query(ArchiveTag).filter(ArchiveTag.name == name).one()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3278, in one
    "Multiple rows were found for one()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

```
</details>

### Additional information:

- FlexGet version: 2.21.32
- Python version: Python 3.5.3
- Installation method: 
- Using daemon (yes/no): yes
- OS and version: Debian 9

**Comment by paranoidi** [comment]
By some magic you have managed to create to tags in database with same name. There's no easy way to resolve this, aside from manually executing queries or clearing whole archive plugin.

We should add unique restraint, database migration could rename the duplicate tag ...

**Comment by soloam** [comment]
No longer relevant, and not possible to test, open again if seen again
