### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace' plugin: newznab (with imdb_id)

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2543]
Additional information:

    FlexGet version: always up2date
    Python version: 3.6
    Installation method: pip
    Using daemon (yes/no): no
    OS and version: ubuntu 18.04
    Additional information: error happens after hundreds of successes .. but constantly.

```
2019-12-25 23:06:55 CRITICAL task          Usenet_movies_Search BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7f4842a289d8>
    -> <Thread(task_queue, started daemon 139948162770688)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x7f4842a287b8>
    -> <Thread(task_queue, started daemon 139948162770688)>
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(task_queue, started daemon 139948162770688)>
    |    |        |    -> ()
    |    |        -> <Thread(task_queue, started daemon 139948162770688)>
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f483952e3c8>>
    -> <Thread(task_queue, started daemon 139948162770688)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 45, in run
    self.current_task.execute()
    |    |            -> <function Task.execute at 0x7f483ce47c80>
    |    -> <flexget.task.Task object at 0x7f4838ec6da0>
    -> <flexget.task_queue.TaskQueue object at 0x7f483952e3c8>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 79, in wrapper
    return func(self, *args, **kw)
           |    |      |       -> {}
           |    |      -> ()
           |    -> <flexget.task.Task object at 0x7f4838ec6da0>
           -> <function Task.execute at 0x7f483ce47bf8>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 696, in execute
    self._execute()
    |    -> <function Task._execute at 0x7f483ce47b70>
    -> <flexget.task.Task object at 0x7f4838ec6da0>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 662, in _execute
    self.__run_task_phase(phase)
    |                     -> 'input'
    -> <flexget.task.Task object at 0x7f4838ec6da0>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 488, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               |                 |       |      -> (<flexget.task.Task object at 0x7f4838ec6da0>, {'what': [{'movie_list': 'Default'}], 'from': [{'newznab': {'website': 'https:...
               |                 |       -> 'input'
               |                 -> <PluginInfo(name=discover)>
               -> <flexget.task.Task object at 0x7f4838ec6da0>

> File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
             |       |       -> {}
             |       -> (<flexget.task.Task object at 0x7f4838ec6da0>, {'what': [{'movie_list': 'Default'}], 'from': [{'newznab': {'website': 'https:...
             -> <Event(name=plugin.discover.input,func=on_task_input,priority=128)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.task.Task object at 0x7f4838ec6da0>, {'what': [{'movie_list': 'Default'}], 'from': [{'newznab': {'website': 'https:...
           |    -> <bound method Discover.on_task_input of <flexget.plugins.input.discover.Discover object at 0x7f483bbdb4a8>>
           -> <Event(name=plugin.discover.input,func=on_task_input,priority=128)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/input/discover.py", line 290, in on_task_input
    return self.execute_searches(config, entries, task)
           |    |                |       |        -> <flexget.task.Task object at 0x7f4838ec6da0>
           |    |                |       -> [<Entry(title=The Professor (2019),state=undecided)>, <Entry(title=Das hält kein Jahr ..! (2013),state=undecided)>, <Entry(ti...
           |    |                -> {'what': [{'movie_list': 'Default'}], 'from': [{'newznab': {'website': 'https://scenenzb.com', 'apikey': '2cab77fa83b00a8775f...
           |    -> <function Discover.execute_searches at 0x7f483bf7fea0>
           -> <flexget.plugins.input.discover.Discover object at 0x7f483bbdb4a8>

  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/input/discover.py", line 132, in execute_searches
    search_results = search.search(task=task, entry=entry, config=plugin_config)
                     |      |           |           |             -> {'website': 'https://scenenzb.com', 'apikey': '2cab77fa83b00a8775f429406472f9f4', 'category': 'movie', 'url': 'https://scenen...
                     |      |           |           -> <Entry(title=The Lord of the Rings: The Two Towers (Extended) (2002),state=undecided)>
                     |      |           -> <flexget.task.Task object at 0x7f4838ec6da0>
                     |      -> <function Newznab.search at 0x7f4839f7c840>
                     -> <flexget.components.sites.sites.newznab.Newznab object at 0x7f483960e128>

  File "/usr/local/lib/python3.6/dist-packages/flexget/components/sites/sites/newznab.py", line 87, in search
    return self.do_search_movie(entry, task, config)
           |    |               |      |     -> {'website': 'https://scenenzb.com', 'apikey': '2cab77fa83b00a8775f429406472f9f4', 'category': 'movie', 'url': 'https://scenen...
           |    |               |      -> <flexget.task.Task object at 0x7f4838ec6da0>
           |    |               -> <Entry(title=The Lord of the Rings: The Two Towers (Extended) (2002),state=undecided)>
           |    -> <function Newznab.do_search_movie at 0x7f4839f7c950>
           -> <flexget.components.sites.sites.newznab.Newznab object at 0x7f483960e128>

  File "/usr/local/lib/python3.6/dist-packages/flexget/components/sites/sites/newznab.py", line 122, in do_search_movie
    imdb_id = arg_entry['imdb_id'].replace('tt', '')
              -> <Entry(title=The Lord of the Rings: The Two Towers (Extended) (2002),state=undecided)>

AttributeError: 'NoneType' object has no attribute 'replace'
2019-12-25 23:06:56 CRITICAL manager       Usenet_movies_Search An unexpected crash has occurred. Writing crash report to /home/snikay/.flexget/crash_report.2019.12.25.230656135181.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.0.23
2019-12-25 23:06:56 WARNING  task          Usenet_movies_Search Aborting task (plugin: discover)
```

**Comment by metaMMA** [comment]
Issue template was ignored by OP. Please fill it so we can help!

> The issue template is here because it helps to ensure you submitted all the necessary information the first time, and allows us to more quickly review issues. Please fill it out correctly and do not ignore it, no matter how irrelevant you think it may be. Thanks in advance for your help with this!


### Additional information:

- FlexGet version:
- Python version:
- Installation method:
- Using daemon (yes/no):
- OS and version:
- Link to crash log:

NOTES:
Please verify that the following data is present before submitting your issue:

- Link to a paste service or paste above the relevant config (preferably full config, including templates if present). Please make sure the paste does not expire, if possible.
- Link to a paste service or paste above debug-level logs of the relevant task/s (use `flexget -L debug execute --tasks <Task_name>`).
- FlexGet version (use `flexget -V` to get it).
- Full Python version, for example `2.7.11` (use `python -V` to get it). 
- Installation method (pip, git install, etc).
- Whether or not you're running FlexGet as a daemon.
- OS and version.
- Attach crash log if one was generated, in addition to the debug-level log. It can be found in the directory with your config file.
