### ISSUE TITLE
OperationalError: database is locked after upgrade from 2.21.32

### ISSUE THREAD

**Issue by soloam** [Flexget/Flexget#2544]
Hello I updated my flexget from 2.21.32 to the lates 3.0.25 and I had to update the python to 3.7.3 on debian 10. Now I can't start flexget, this is the error, even in flexget check

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 755, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 534, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 10, in <module>
    sys.exit(main())
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/__init__.py", line 41, in main
    manager.start()
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/manager.py", line 356, in start
    self.initialize()
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/manager.py", line 214, in initialize
    self.load_config()
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/manager.py", line 675, in load_config
    self.update_config(config)
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/manager.py", line 686, in update_config
    self.config = self.validate_config(config)
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/manager.py", line 742, in validate_config
    config = fire_event('manager.before_config_validate', config, self)
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/event.py", line 110, in fire_event
    result = event(*args, **kwargs)
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/components/variables/variables.py", line 86, in process_variables
    variables_to_db(variables)
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/components/variables/variables.py", line 61, in variables_to_db
    session.merge(variables)
  File "/home/downloader/.local/lib/python3.7/site-packages/flexget/utils/sqlalchemy_utils.py", line 138, in __exit__
    self.commit()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 498, in commit
    t[1].commit()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1727, in commit
    self._do_commit()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1758, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 757, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 755, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 534, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: http://sqlalche.me/e/e3q8)

```

What can I do to solve this?

**Comment by cvium** [comment]
I'm guessing you forgot to stop the service before upgrading. You will have to kill the old process.

**Comment by soloam** [comment]
I did it all, kill, reboot! Delete old data base and create new one, the error still exists!

**Comment by metaMMA** [comment]
Bunch of good suggestions on this post:
https://stackoverflow.com/questions/13895176/sqlalchemy-and-sqlite-database-is-locked

**Comment by soloam** [comment]
But this is all under the hood changes! I didn't change anything on the core flexget, only updated the python and flexget! Now I have this problem!

**Comment by metaMMA** [comment]
Ok. Did any of the suggestions in that post solve the issue?

**Comment by soloam** [comment]
No, i don't think the problem is in the database, I deleted the database
and flexget created a new one, only to give the same error on a newly
created database!

**Comment by metaMMA** [comment]
Well since you already deleted the database, you should try uninstalling an reinstalling sqlalchemy. There might be a lock file that you haven't deleted that is causing the issue. Possibly the database/flexget is running as a different user than the owner of the other.

**Comment by paranoidi** [comment]
@metaMMA what is your installation method? based on the paths in log it's not clear ..

Try installing into a new python virtualenv. It's pretty much guaranteed to be clean and working.

**Comment by metaMMA** [comment]
@paranoidi Not the OP

@siloam ^

**Comment by soloam** [comment]
I will try again! I ended up rolling back eventing because I didn't want to have the system stopped that long! I'll try to make the update again! I have the system installed outside the virtual ev! This is a good time to update to virtual env.

Thank you

**Comment by liiight** [comment]
is this still relevant?

**Comment by soloam** [comment]
Problem seem to be related on having the database on a shared smb folder! I used to have the config on a shared folder and then I had a symbolic link to link it to flexget folder! Since the upgrade this stopped working, I ended up moving the config outside of the share! Everything started working!

**Comment by liiight** [comment]
Good to hear. Closing this for now, reopen if relevant.
