### ISSUE TITLE
Daemon exits mysteriously if port is in use

### ISSUE THREAD

**Issue by paranoidi** [Flexget/Flexget#2562]
### Issue:

If web server is configured to a port which is already in use it should log an error and not just quit without explanation. Trying to use `--debug` does not improve situation.

#### Log:

```
$ flexget daemon start
2020-01-08 16:46:00 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
2020-01-08 16:46:00 INFO     web_server_daemon                 Initiating API
2020-01-08 16:46:00 INFO     web_server_daemon                 Registering WebUI v2
2020-01-08 16:46:00 CRITICAL webui                         Failed to start web ui, this can happen if you are running from GitHub version and forgot to run the web ui build, see http://flexget.com/wiki/Web-UI/v2 for instructions
2020-01-08 16:46:00 INFO     web_server                    Web interface available at http://127.0.0.1:5050
2020-01-08 16:46:00 INFO     scheduler                     Starting scheduler
$ _
```

**Comment by paranoidi** [comment]
Chaging flexget/webserver.py log.screen to True does produce extremely noisy explanation of port being reserved.

```
2020-01-08 18:31:08 INFO     scheduler                     Starting scheduler
[08/Jan/2020:18:31:09] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f708048fc10>>
Traceback (most recent call last):
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/portend.py", line 115, in free 
    Checker(timeout=0.1).assert_free(host, port)
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/portend.py", line 69, in assert_free
    list(itertools.starmap(self._connect, info))
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/portend.py", line 85, in _connect
    raise PortNotFree(tmpl.format(**locals()))
portend.PortNotFree: Port 0.0.0.0 is in use on 5050.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/cherrypy/process/servers.py", line 177, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/portend.py", line 119, in free 
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 5050 not free on 0.0.0.0. 

[08/Jan/2020:18:31:09] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/home/paranoidi/apps/flexget/lib/python3.7/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 5050 not free on 0.0.0.0.')

[08/Jan/2020:18:31:09] ENGINE Bus STOPPING
[08/Jan/2020:18:31:09] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5050)) already shut down
[08/Jan/2020:18:31:09] ENGINE Bus STOPPED
[08/Jan/2020:18:31:09] ENGINE Bus EXITING
[08/Jan/2020:18:31:09] ENGINE Bus EXITED
```

And when things start right it still logs unformated unwanted details, which is why it probably was disabled:

```
2020-01-08 18:32:56 INFO     scheduler                     Starting scheduler
[08/Jan/2020:18:32:56] ENGINE Serving on http://0.0.0.0:5052
[08/Jan/2020:18:32:56] ENGINE Bus STARTED
```
