### ISSUE TITLE
Errors on >=v3.0.32

### ISSUE THREAD

**Issue by 00lex** [Flexget/Flexget#2569]
Hi! I get the following error on every Flexget version greater v3.0.31 but my tasks seems to work. 
I downgraded Flexget (pip3 install --upgrade flexget==v3.0.31) and will wait.  

today latest version is v3.1.3

```
2020-01-12 13:03:15 CRITICAL plugin                        Plugin `flexget.components.sites.sites.hebits` failed to import dependencies



2020-01-12 13:03:15 CRITICAL plugin                        Plugin `flexget.components.sites.sites.hebits` failed to import dependencies
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 10, in <module>
    sys.exit(main())
    |   |    -> <function main at 0xb66af2b8>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>

  File "/usr/local/lib/python3.7/dist-packages/flexget/__init__.py", line 41, in main
    manager.start()
    |       -> <function Manager.start at 0xb5295618>
    -> <flexget.manager.Manager object at 0xb66ae370>

  File "/usr/local/lib/python3.7/dist-packages/flexget/manager.py", line 361, in start
    self.initialize()
    |    -> <function Manager.initialize at 0xb52954f8>
    -> <flexget.manager.Manager object at 0xb66ae370>

  File "/usr/local/lib/python3.7/dist-packages/flexget/manager.py", line 206, in initialize
    extra_components=[os.path.join(self.config_base, 'components')],
                      |  |    |    |    -> '/a'
                      |  |    |    -> <flexget.manager.Manager object at 0xb66ae370>
                      |  |    -> <function join at 0xb66fea50>
                      |  -> <module 'posixpath' from '/usr/lib/python3.7/posixpath.py'>
                      -> <module 'os' from '/usr/lib/python3.7/os.py'>

  File "/usr/local/lib/python3.7/dist-packages/flexget/plugin.py", line 555, in load_plugins
    _load_components_from_dirs(extra_components)
    |                          -> ['/a/components', '/usr/local/lib/python3.7/dist-packages/flexget/components']
    -> <function _load_components_from_dirs at 0xb54dd300>

  File "/usr/local/lib/python3.7/dist-packages/flexget/plugin.py", line 496, in _load_components_from_dirs
    _import_plugin(package_name, component_path)
    |              |             -> PosixPath('/usr/local/lib/python3.7/dist-packages/flexget/components/sites/sites/hebits.py')
    |              -> 'flexget.components.sites.sites.hebits'
    -> <function _import_plugin at 0xb553ddf8>

> File "/usr/local/lib/python3.7/dist-packages/flexget/plugin.py", line 425, in _import_plugin
    import_module(module_name)
    |             -> 'flexget.components.sites.sites.hebits'
    -> <function import_module at 0xb672ea50>

  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           |          |           |    |        |        -> 0
           |          |           |    |        -> None
           |          |           |    -> 0
           |          |           -> 'flexget.components.sites.sites.hebits'
           |          -> <function _gcd_import at 0xb6790ed0>
           -> <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/local/lib/python3.7/dist-packages/flexget/components/sites/sites/hebits.py", line 8, in <module>
    from requests_html import HTML, Element

  File "/usr/local/lib/python3.7/dist-packages/requests_html.py", line 11, in <module>
    from pyquery import PyQuery

  File "/usr/local/lib/python3.7/dist-packages/pyquery/__init__.py", line 7, in <module>
    from .pyquery import PyQuery  # NOQA

  File "/usr/local/lib/python3.7/dist-packages/pyquery/pyquery.py", line 11, in <module>
    from lxml import etree
```

**Comment by metaMMA** [comment]
@liiight I think you created the hebits plugin. When you get a chance, could you take a look at this?

**Comment by liiight** [comment]
hmm, what os and python version? also, that's not the full error

**Comment by 00lex** [comment]
> @liiight I think you created the hebits plugin. When you get a chance, could you take a look at this?

im using flexget for a very long time but I don't know what the hebits plugin is :)
but as I say, my yaml runs fine after the error above. 

> hmm, what os and python version? also, that's not the full error

Im on a up to date Raspbian Buster and Python v3.7.3. 
above is the full error. after the error only logs from my yaml are following. 

btw. flexget is not demonized. im running flexget periodically with: 

> runuser xyz -c 'flexget -c /home/xyz/Media.yml --logfile /tmp/flexmedia.log execute'

**Comment by 00lex** [comment]
@liiight 

SORRY! I missed the last line from the error.

`ImportError: libxslt.so.1: cannot open shared object file: No such file or directory`

**Comment by metaMMA** [comment]
Is that pastebin from v3.0.31? There is a hebits.py error present, but that plugin wasn't added until v3.1+

**Comment by 00lex** [comment]
@metaMMA yes. v3.1.2 - v3.1.4 output this error

**Comment by 00lex** [comment]
I installed the following package and the error is gone
https://packages.debian.org/buster/libxslt1.1

**Comment by liiight** [comment]
I'm going to refactor hebits to drop request_html and get rid of these dependency issues. I'll use this as the issue to follow.

**Comment by liiight** [comment]
Nm, I opened a new issue

**Comment by 00lex** [comment]
hi liiight, 
does it mean I can remove `libxslt1.1` again after the next update?

**Comment by liiight** [comment]
Not after the next update, after I'll close #2571

**Comment by 00lex** [comment]
Okay I will keep it in mind. 

Thank you!
