### ISSUE TITLE
'utf-8' codec can't encode character '\udcf6'

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2574]
```
--- Logging error in Loguru Handler #3 ---
Record was: {'elapsed': datetime.timedelta(0, 11, 922487), 'exception': (type=<class 'UnicodeEncodeError'>, value=UnicodeEncodeError('utf-8', 'Welche M\udcf6glichkeiten gibt es Eigenkapital f\udcfcr Immobilien zu besorgen_ S01E83_99 (720p_30fps_H264-192kbit_AAC)', 8, 9, 'surrogates not allowed'), traceback=<traceback object at 0x7f5188f0d888>), 'extra': {'task': 'Sorting-move-NBA', 'session_id': None, 'task_id': '249356'}, 'file': (name='task.py', path='/usr/local/lib/python3.6/dist-packages/flexget/task.py'), 'function': '__run_plugin', 'level': (name='CRITICAL', no=50, icon='☠️'), 'line': 561, 'message': "BUG: Unhandled error in plugin retry_failed: 'utf-8' codec can't encode character '\\udcf6' in position 8: surrogates not allowed", 'module': 'task', 'name': 'task', 'process': (id=25872, name='MainProcess'), 'thread': (id=139988164085504, name='task_queue'), 'time': datetime(2020, 1, 14, 23, 55, 40, 731703, tzinfo=datetime.timezone(datetime.timedelta(0, 3600), 'CET'))}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/components/failed/retry_failed.py", line 126, in on_task_filter
    .filter(db.FailedEntry.url == entry['original_url'])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 8: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/loguru/_handler.py", line 153, in emit
    self._sink.write(str_record)
  File "/usr/local/lib/python3.6/dist-packages/loguru/_file_sink.py", line 178, in write
    self._file.write(message)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 3833: surrogates not allowed
--- End of logging error ---
2020-01-14 23:55:40 CRITICAL task          Sorting-move-NBA BUG: Unhandled error in plugin retry_failed: 'utf-8' codec can't encode character '\udcf6' in position 8: surrogates not allowed
```

```
2020-01-15 00:01:13 WARNING  nfo_lookup    Sorting-move-NBA Entry Statistik Manipulation_ Wie die Inflationsrate sch?n gerechnet wird S01E53_99 (1080p_25fps_H264-128kbit_AAC) has no corresponding .nfo file
--- Logging error in Loguru Handler #3 ---
Record was: {'elapsed': datetime.timedelta(0, 10, 549742), 'exception': None, 'extra': {'task': 'Sorting-move-NBA', 'session_id': None, 'task_id': '246848'}, 'file': (name='nfo_lookup.py', path='/usr/local/lib/python3.6/dist-packages/flexget/plugins/metainfo/nfo_lookup.py'), 'function': 'on_task_metainfo', 'level': (name='WARNING', no=30, icon='⚠️'), 'line': 71, 'message': 'Entry Immobilienfinanzierung mit Annuit\udce4tendarlehen (Zins, Tilgung, Darlehensverlauf, Kredit) S01E25_99 (1080p_25fps_H264-128kbit_AAC) has no corresponding .nfo file', 'module': 'nfo_lookup', 'name': 'nfo_lookup', 'process': (id=27666, name='MainProcess'), 'thread': (id=139774008907520, name='task_queue'), 'time': datetime(2020, 1, 15, 0, 1, 13, 705523, tzinfo=datetime.timezone(datetime.timedelta(0, 3600), 'CET'))}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/loguru/_handler.py", line 153, in emit
    self._sink.write(str_record)
  File "/usr/local/lib/python3.6/dist-packages/loguru/_file_sink.py", line 178, in write
    self._file.write(message)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 99: surrogates not allowed
--- End of logging error ---
```

```
2020-01-15 00:05:46 CRITICAL task          Sorting-move-NBA BUG: Unhandled error in plugin retry_failed: 'utf-8' codec can't encode character '\udcf6' in position 8: surrogates not allowed
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7f07055cc9d8>
    -> <Thread(task_queue, started daemon 139667954140928)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x7f07055cc7b8>
    -> <Thread(task_queue, started daemon 139667954140928)>
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(task_queue, started daemon 139667954140928)>
    |    |        |    -> ()
    |    |        -> <Thread(task_queue, started daemon 139667954140928)>
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f06fb9bb8d0>>
    -> <Thread(task_queue, started daemon 139667954140928)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 45, in run
    self.current_task.execute()
    |    |            -> <function Task.execute at 0x7f06ff9f0e18>
    |    -> <flexget.task.Task object at 0x7f06fb33e780>
    -> <flexget.task_queue.TaskQueue object at 0x7f06fb9bb8d0>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 79, in wrapper
    return func(self, *args, **kw)
           |    |      |       -> {}
           |    |      -> ()
           |    -> <flexget.task.Task object at 0x7f06fb33e780>
           -> <function Task.execute at 0x7f06ff9f0d90>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 696, in execute
    self._execute()
    |    -> <function Task._execute at 0x7f06ff9f0d08>
    -> <flexget.task.Task object at 0x7f06fb33e780>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 662, in _execute
    self.__run_task_phase(phase)
    |                     -> 'filter'
    -> <flexget.task.Task object at 0x7f06fb33e780>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 488, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               |                 |       |      -> (<flexget.task.Task object at 0x7f06fb33e780>, {'retry_time': '60 seconds', 'retry_time_multiplier': 1, 'max_retries': 8})
               |                 |       -> 'filter'
               |                 -> <PluginInfo(name=retry_failed)>
               -> <flexget.task.Task object at 0x7f06fb33e780>

> File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
             |       |       -> {}
             |       -> (<flexget.task.Task object at 0x7f06fb33e780>, {'retry_time': '60 seconds', 'retry_time_multiplier': 1, 'max_retries': 8})
             -> <Event(name=plugin.retry_failed.filter,func=on_task_filter,priority=255)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.task.Task object at 0x7f06fb33e780>, {'retry_time': '60 seconds', 'retry_time_multiplier': 1, 'max_retries': 8})
           |    -> <bound method PluginFailed.on_task_filter of <flexget.components.failed.retry_failed.PluginFailed object at 0x7f06fba484e0>>
           -> <Event(name=plugin.retry_failed.filter,func=on_task_filter,priority=255)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/components/failed/retry_failed.py", line 126, in on_task_filter
    .filter(db.FailedEntry.url == entry['original_url'])
            |  |           |      -> <Entry(title=Welche M?glichkeiten gibt es Eigenkapital f?r Immobilien zu besorgen_ S01E83_99 (720p_30fps_H264-192kbit_AAC),st...
            |  |           -> <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f06fbbea6d0>
            |  -> <class 'flexget.components.failed.db.FailedEntry'>
            -> <module 'flexget.components.failed.db' from '/usr/local/lib/python3.6/dist-packages/flexget/components/failed/db.py'>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
               -> <sqlalchemy.orm.query.Query object at 0x7f06fb13b898>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
                -> <sqlalchemy.orm.query.Query object at 0x7f06fb13b860>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
           |    |                      -> <sqlalchemy.orm.query.QueryContext object at 0x7f06f9c3a678>
           |    -> <function Query._execute_and_instances at 0x7f070030a7b8>
           -> <sqlalchemy.orm.query.Query object at 0x7f06fb13b860>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
             |    |       |            |          |    -> immutabledict({})
             |    |       |            |          -> <sqlalchemy.orm.query.Query object at 0x7f06fb13b860>
             |    |       |            -> <member 'statement' of 'QueryContext' objects>
             |    |       -> <sqlalchemy.orm.query.QueryContext object at 0x7f06f9c3a678>
             |    -> <function Connection.execute at 0x7f0700b68620>
             -> <sqlalchemy.engine.base.Connection object at 0x7f06fb150240>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
           |    |     |            -> {}
           |    |     -> (immutabledict({}),)
           |    -> <sqlalchemy.engine.base.Connection object at 0x7f06fb150240>
           -> <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.selectable.Select at 0x7f06fb154828; Select object>>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
           |          |                      |     |            -> {}
           |          |                      |     -> (immutabledict({}),)
           |          |                      -> <sqlalchemy.sql.selectable.Select at 0x7f06fb154828; Select object>
           |          -> <function Connection._execute_clauseelement at 0x7f0700b68840>
           -> <sqlalchemy.engine.base.Connection object at 0x7f06fb150240>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
    -> [immutabledict({})]

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
       |          |           |       -> <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x7f06fb154908>
       |          |           -> <sqlite3.Cursor object at 0x7f06fade2810>
       |          -> ('Welche M\udcf6glichkeiten gibt es Eigenkapital f\udcfcr Immobilien zu besorgen_ S01E83_99 (720p_30fps_H264-192kbit_AAC)', '...
       -> 'SELECT failed.id AS failed_id, failed.title AS failed_title, failed.url AS failed_url, failed.tof AS failed_tof, failed.reas...

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
    |    |        -> (<class 'UnicodeEncodeError'>, UnicodeEncodeError('utf-8', 'Welche M\udcf6glichkeiten gibt es Eigenkapital f\udcfcr Immobilie...
    |    -> <function reraise at 0x7f0701335488>
    -> <module 'sqlalchemy.util' from '/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/__init__.py'>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
          -> UnicodeEncodeError('utf-8', 'Welche M\udcf6glichkeiten gibt es Eigenkapital f\udcfcr Immobilien zu besorgen_ S01E83_99 (720p_...

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
    |       |          |           -> <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x7f06fb154908>
    |       |          -> ('Welche M\udcf6glichkeiten gibt es Eigenkapital f\udcfcr Immobilien zu besorgen_ S01E83_99 (720p_30fps_H264-192kbit_AAC)', '...
    |       -> 'SELECT failed.id AS failed_id, failed.title AS failed_title, failed.url AS failed_url, failed.tof AS failed_tof, failed.reas...
    -> <sqlite3.Cursor object at 0x7f06fade2810>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
    |      |       |          -> ('Welche M\udcf6glichkeiten gibt es Eigenkapital f\udcfcr Immobilien zu besorgen_ S01E83_99 (720p_30fps_H264-192kbit_AAC)', '...
    |      |       -> 'SELECT failed.id AS failed_id, failed.title AS failed_title, failed.url AS failed_url, failed.tof AS failed_tof, failed.reas...
    |      -> <method 'execute' of 'sqlite3.Cursor' objects>
    -> <sqlite3.Cursor object at 0x7f06fade2810>

UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 8: surrogates not allowed
2020-01-15 00:05:46 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Exception in thread task_queue:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/components/failed/retry_failed.py", line 126, in on_task_filter
    .filter(db.FailedEntry.url == entry['original_url'])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 8: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 45, in run
    self.current_task.execute()
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 79, in wrapper
    return func(self, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 696, in execute
    self._execute()
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 662, in _execute
    self.__run_task_phase(phase)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 488, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 562, in __run_plugin
    traceback = self.manager.crash_report()
  File "/usr/local/lib/python3.6/dist-packages/flexget/manager.py", line 1037, in crash_report
    outfile.writelines(flexget.log.debug_buffer)
  File "/usr/lib/python3.6/codecs.py", line 724, in writelines
    return self.writer.writelines(list)
  File "/usr/lib/python3.6/codecs.py", line 384, in writelines
    self.write(''.join(list))
  File "/usr/lib/python3.6/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 106: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 53, in run
    self.current_task.manager.crash_report()
  File "/usr/local/lib/python3.6/dist-packages/flexget/manager.py", line 1037, in crash_report
    outfile.writelines(flexget.log.debug_buffer)
  File "/usr/lib/python3.6/codecs.py", line 724, in writelines
    return self.writer.writelines(list)
  File "/usr/lib/python3.6/codecs.py", line 384, in writelines
    self.write(''.join(list))
  File "/usr/lib/python3.6/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf6' in position 115: surrogates not allowed
```
### Additional information:

- FlexGet version: 3.1.6
- Python version: 3
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: ubuntu 18

**Comment by snickers2k** [comment]
sorry, configuration issue
