### ISSUE TITLE
Task not completing due to list_add

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/Flexget#2580]
### Expected behaviour:
Entries get added to the list, following behaviour up to v3.1.10
### Actual behaviour:
Task is interrupted, entries are not added to `entry-list`.
### Steps to reproduce:
Execute task below

#### Config:
```yaml
accept_all: true
anilist:
  format:
    - tv
    - tv_short
  release_status: releasing
  username: BrutuZ
disable:
  - seen
  - seen_info_hash
  - retry_failed
list_add:
  - entry_list: myanimelist-series
no_entries_ok: true
set:
  series_name: "{{mal_name|d(series_name)|d(title)|re_replace('[\u0E00-\uFAFF]','\
    \ ')|re_replace('  +',' ')}}"
  title: "{{title|re_replace('[\u0E00-\uFAFF]',' ')|re_replace('  +',' ')}}"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-01-24 14:10:12 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2020-01-24 14:10:13 VERBOSE  details       fill-anime-series-list Produced 13 entries.
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Boku no Hero Academia 4` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Toaru Kagaku no Railgun T` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Murenase! Seton Gakuen` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Ishuzoku Reviewers` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Plunderer` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Somali to Mori no Kamisama` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Jibaku Shounen Hanako-kun` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Darwin's Game` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `pet` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Mairimashita! Iruma-kun` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Hatena Illusion` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Fate/Grand Order: Zettai Majuu Sensen Babylonia` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  task          fill-anime-series-list ACCEPTED: `Dorohedoro` by accept_all plugin
2020-01-24 14:10:13 VERBOSE  details       fill-anime-series-list Summary - Accepted: 13 (Rejected: 0 Undecided: 0 Failed: 0)
2020-01-24 14:10:13 VERBOSE  list_add      fill-anime-series-list adding accepted entries into entry_list - myanimelist-series
2020-01-24 14:10:13 CRITICAL task          fill-anime-series-list BUG: Unhandled error in plugin list_add: Object of type object is not JSON serializable
Traceback (most recent call last):

  File "c:\python37\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x000002CF08E229D8>
    -> <Thread(task_queue, started daemon 6680)>

  File "c:\python37\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x000002CF08E22798>
    -> <Thread(task_queue, started daemon 6680)>

  File "c:\python37\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(task_queue, started daemon 6680)>
    |    |        |    -> ()
    |    |        -> <Thread(task_queue, started daemon 6680)>
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x000002CF0FDDCB88>>
    -> <Thread(task_queue, started daemon 6680)>

  File "c:\users\brutuz\documents\github\flexget\flexget\task_queue.py", line 45, in run
    self.current_task.execute()
    |    |            -> <function Task.execute at 0x000002CF0B555708>
    |    -> <flexget.task.Task object at 0x000002CF101FF788>
    -> <flexget.task_queue.TaskQueue object at 0x000002CF0FDDCB88>

  File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 79, in wrapper
    return func(self, *args, **kw)
           |    |      |       -> {}
           |    |      -> ()
           |    -> <flexget.task.Task object at 0x000002CF101FF788>
           -> <function Task.execute at 0x000002CF0B555678>

  File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 696, in execute
    self._execute()
    |    -> <function Task._execute at 0x000002CF0B5555E8>
    -> <flexget.task.Task object at 0x000002CF101FF788>

  File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 662, in _execute
    self.__run_task_phase(phase)
    |                     -> 'output'
    -> <flexget.task.Task object at 0x000002CF101FF788>

  File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 488, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               |                 |       |      -> (<flexget.task.Task object at 0x000002CF101FF788>, [{'entry_list': 'myanimelist-series'}])
               |                 |       -> 'output'
               |                 -> <PluginInfo(name=list_add)>
               -> <flexget.task.Task object at 0x000002CF101FF788>

> File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
             |       |       -> {}
             |       -> (<flexget.task.Task object at 0x000002CF101FF788>, [{'entry_list': 'myanimelist-series'}])
             -> <Event(name=plugin.list_add.output,func=on_task_output,priority=0)>

  File "c:\users\brutuz\documents\github\flexget\flexget\event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.task.Task object at 0x000002CF101FF788>, [{'entry_list': 'myanimelist-series'}])
           |    -> <bound method ListAdd.on_task_output of <flexget.components.managed_lists.list_add.ListAdd object at 0x000002CF0F7FD248>>
           -> <Event(name=plugin.list_add.output,func=on_task_output,priority=0)>

  File "c:\users\brutuz\documents\github\flexget\flexget\components\managed_lists\list_add.py", line 53, in on_task_output
    thelist |= task.accepted
    |          |    -> <property object at 0x000002CF0B554368>
    |          -> <flexget.task.Task object at 0x000002CF101FF788>
    -> <flexget.components.managed_lists.lists.entry_list.db.DBEntrySet object at 0x000002CF103600C8>

  File "c:\users\brutuz\documents\github\flexget\lib\_collections_abc.py", line 606, in __ior__
    self.add(value)
    |    |   -> <Entry(title=Boku no Hero Academia 4,state=accepted)>
    |    -> <function DBEntrySet.add at 0x000002CF0EEB3C18>
    -> <flexget.components.managed_lists.lists.entry_list.db.DBEntrySet object at 0x000002CF103600C8>

  File "c:\users\brutuz\documents\github\flexget\flexget\components\managed_lists\lists\entry_list\db.py", line 157, in add
    stored_entry = EntryListEntry(entry=entry, entry_list_id=self._db_list(session).id)
                   |                    |                    |    |        -> <sqlalchemy.orm.session.ContextSession object at 0x000002CF10360CC8>
                   |                    |                    |    -> <function DBEntrySet._db_list at 0x000002CF0EEB3558>
                   |                    |                    -> <flexget.components.managed_lists.lists.entry_list.db.DBEntrySet object at 0x000002CF103600C8>
                   |                    -> <Entry(title=Boku no Hero Academia 4,state=accepted)>
                   -> <class 'flexget.components.managed_lists.lists.entry_list.db.EntryListEntry'>

  File "<string>", line 4, in __init__

  File "c:\users\brutuz\documents\github\flexget\lib\site-packages\sqlalchemy\orm\state.py", line 441, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
    |       |        |            |     |     -> {}
    |       |        |            |     -> (<Entry(title=Boku no Hero Academia 4,state=accepted)>, 1)
    |       |        |            -> <sqlalchemy.orm.state.InstanceState object at 0x000002CF10349AC8>
    |       |        -> <member 'init_failure' of 'InstanceEventsDispatch' objects>
    |       -> <sqlalchemy.event.base.InstanceEventsDispatch object at 0x000002CF0EEA34C8>
    -> <ClassManager of <class 'flexget.components.managed_lists.lists.entry_list.db.EntryListEntry'> at 2cf0eeaa348>

  File "c:\users\brutuz\documents\github\flexget\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
    |      |       |         |          -> <traceback object at 0x000002CF1034A4C8>
    |      |       |         -> TypeError('Object of type object is not JSON serializable')
    |      |       -> <class 'TypeError'>
    |      -> <function reraise at 0x000002CF0A0E35E8>
    -> <module 'sqlalchemy.util.compat' from 'c:\\users\\brutuz\\documents\\github\\flexget\\lib\\site-packages\\sqlalchemy\\util\\c...

  File "c:\users\brutuz\documents\github\flexget\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
          -> TypeError('Object of type object is not JSON serializable')

  File "c:\users\brutuz\documents\github\flexget\lib\site-packages\sqlalchemy\orm\state.py", line 438, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           |       |              |            -> {}
           |       |              -> (<sqlalchemy.orm.state.InstanceState object at 0x000002CF10349AC8>, <EntryListEntry,title=Boku no Hero Academia 4,original_ur...
           |       -> <function EntryListEntry.__init__ at 0x000002CF0EEA3708>
           -> <ClassManager of <class 'flexget.components.managed_lists.lists.entry_list.db.EntryListEntry'> at 2cf0eeaa348>

  File "c:\users\brutuz\documents\github\flexget\flexget\components\managed_lists\lists\entry_list\db.py", line 80, in __init__
    self.entry = entry
    |    |       -> <Entry(title=Boku no Hero Academia 4,state=accepted)>
    |    -> <sqlalchemy.orm.attributes.create_proxied_attribute.<locals>.Proxy object at 0x000002CF0EEAA4C8>
    -> <EntryListEntry,title=Boku no Hero Academia 4,original_url=https://anilist.co/anime/104276>

  File "<string>", line 1, in __set__

  File "c:\users\brutuz\documents\github\flexget\flexget\utils\database.py", line 94, in setter
    setattr(self, name, serialization.dumps(entry))
            |     |     |             |     -> <Entry(title=Boku no Hero Academia 4,state=accepted)>
            |     |     |             -> <function dumps at 0x000002CF0B175E58>
            |     |     -> <module 'flexget.utils.serialization' from 'c:\\users\\brutuz\\documents\\github\\flexget\\flexget\\utils\\serialization.py'>
            |     -> '_json'
            -> <EntryListEntry,title=Boku no Hero Academia 4,original_url=https://anilist.co/anime/104276>

  File "c:\users\brutuz\documents\github\flexget\flexget\utils\serialization.py", line 53, in dumps
    return json.dumps(serialize(value))
           |    |     |         -> <Entry(title=Boku no Hero Academia 4,state=accepted)>
           |    |     -> <function serialize at 0x000002CF0B1705E8>
           |    -> <function dumps at 0x000002CF0B178AF8>
           -> <module 'flexget.utils.json' from 'c:\\users\\brutuz\\documents\\github\\flexget\\flexget\\utils\\json.py'>

  File "c:\users\brutuz\documents\github\flexget\flexget\utils\json.py", line 89, in dumps
    return json.dumps(*args, **kwargs)
           |    |      |       -> {}
           |    |      -> ({'serializer': 'Entry', 'version': 1, 'value': {'fields': {'original_title': 'Boku no Hero Academia 4', 'al_title': {'romaji...
           |    -> <function dumps at 0x000002CF09D75AF8>
           -> <module 'json' from 'c:\\python37\\Lib\\json\\__init__.py'>

  File "c:\python37\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           |                |      -> {'serializer': 'Entry', 'version': 1, 'value': {'fields': {'original_title': 'Boku no Hero Academia 4', 'al_title': {'romaji'...
           |                -> <function JSONEncoder.encode at 0x000002CF09D75DC8>
           -> <json.encoder.JSONEncoder object at 0x000002CF09D6B3C8>

  File "c:\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
             |    |          -> {'serializer': 'Entry', 'version': 1, 'value': {'fields': {'original_title': 'Boku no Hero Academia 4', 'al_title': {'romaji'...
             |    -> <function JSONEncoder.iterencode at 0x000002CF09D75E58>
             -> <json.encoder.JSONEncoder object at 0x000002CF09D6B3C8>

  File "c:\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
           |           -> {'serializer': 'Entry', 'version': 1, 'value': {'fields': {'original_title': 'Boku no Hero Academia 4', 'al_title': {'romaji'...
           -> <_json.Encoder object at 0x000002CF1022BDD8>

  File "c:\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type object is not JSON serializable
2020-01-24 14:10:14 CRITICAL manager       fill-anime-series-list An unexpected crash has occurred. Writing crash report to C:\Users\BrutuZ\flexget\crash_report.2020.01.24.141014084720.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.12.dev
2020-01-24 14:10:14 WARNING  task          fill-anime-series-list Aborting task (plugin: list_add)
```
</details>

### Additional information:

- FlexGet version: 3.1.11 and 3.1.12.dev
- Python version: 3.7
- Installation method: git
- Using daemon (yes/no): either
- OS and version: Win10
- Link to crash log: https://pastebin.com/raw/hdeg0Pjr

**Comment by BrutuZ** [comment]
Output after 58dc192 as requested in chat: https://dpaste.org/ixiH
