### ISSUE TITLE
[BUG] no entries in web-UI "Entry List"

### ISSUE THREAD

**Issue by mami7880** [Flexget/Flexget#2582]
### Expected behaviour:
Entries will show in an entry-list. It was like that until the last update

### Actual behaviour:
Since the last update, no entries have been shown in the "entry lists",
The entries are displayed via CLI

### Steps to reproduce:
- Step 1: Fill the entry-list with task FILL-SERIES-LIST
- Step 2: open a entryList in WebUi

#### Config:
```yaml
--- config from task: FILL-SERIES-LIST
accept_all: true
disable:
  - seen
  - seen_info_hash
  - retry_failed
list_add:
  - entry_list: traktserien
list_clear:
  phase: start
  what:
    - entry_list: traktserien
pathscrub: windows
plugin_priority:
  set: 100
priority: 5
set:
  series_name: '{% if tvdb_series_name is defined %}{{tvdb_series_name}}{% endif %}'
  title: "{% if tvdb_series_name is defined %}{{ tvdb_series_name|replace('\xE4','ae')|replace('\xF6\
    ','oe')|replace('\xFC','ue')|pathscrub }}{% endif %}"
template:
  - series-lookup
  - disable-seen-retry
thetvdb_lookup:
  accept_languages:
    - de
  language: de
trakt_list:
  account: xxxxxxx
  list: get_series_flexget
  strip_dates: false
  type: shows
  username: xxxxxxx

---

```

#### Screenshots:
![image](https://user-images.githubusercontent.com/33033685/73217642-97ec6180-4158-11ea-99d8-6a577dd139d7.png)
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-01-27 19:27:21 ERROR    flask.app                     Exception on /entry_list/1/entries [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0xb6580198>
    └ <WorkerThread(CP Server Thread-11, started 2858398816)>
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0xb23da6f0>
    └ <WorkerThread(CP Server Thread-11, started 2858398816)>

  File "/usr/local/lib/python3.7/dist-packages/cheroot/workers/threadpool.py", line 125, in run
    keep_conn_open = conn.communicate()
                     │    └ <function HTTPConnection.communicate at 0xb23dd588>
                     └ <cheroot.server.HTTPConnection object at 0xa5f61e10>

  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1280, in communicate
    req.respond()
    │   └ <function HTTPRequest.respond at 0xb23dd3d8>
    └ <cherrypy._cpwsgi_server.CPWSGIHTTPRequest object at 0xb4e0e4f0>

  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1083, in respond
    self.server.gateway(self).respond()
    │    │      │       └ <cherrypy._cpwsgi_server.CPWSGIHTTPRequest object at 0xb4e0e4f0>
    │    │      └ <class 'cheroot.wsgi.Gateway_10'>
    │    └ <cherrypy._cpwsgi_server.CPWSGIServer object at 0xb0d5d5f0>
    └ <cherrypy._cpwsgi_server.CPWSGIHTTPRequest object at 0xb4e0e4f0>

  File "/usr/local/lib/python3.7/dist-packages/cheroot/wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
               │    │   │      │        │    │    │    └ <function Gateway.start_response at 0xb0b7d420>
               │    │   │      │        │    │    └ <cheroot.wsgi.Gateway_10 object at 0xae566b10>
               │    │   │      │        │    └ {'ACTUAL_SERVER_PROTOCOL': 'HTTP/1.1', 'PATH_INFO': '/api/entry_list/1/entries', 'QUERY_STRING': 'page=1&per_page=30&sort_by=...
               │    │   │      │        └ <cheroot.wsgi.Gateway_10 object at 0xae566b10>
               │    │   │      └ <cherrypy._cptree.Tree object at 0xb23879d0>
               │    │   └ <cherrypy._cpwsgi_server.CPWSGIServer object at 0xb0d5d5f0>
               │    └ <cherrypy._cpwsgi_server.CPWSGIHTTPRequest object at 0xb4e0e4f0>
               └ <cheroot.wsgi.Gateway_10 object at 0xae566b10>

  File "/usr/local/lib/python3.7/dist-packages/cherrypy/_cptree.py", line 302, in __call__
    return app(environ, start_response)
           │   │        └ <bound method Gateway.start_response of <cheroot.wsgi.Gateway_10 object at 0xae566b10>>
           │   └ {'ACTUAL_SERVER_PROTOCOL': 'HTTP/1.1', 'PATH_INFO': '/entry_list/1/entries', 'QUERY_STRING': 'page=1&per_page=30&sort_by=adde...
           └ <Flask 'flexget.api.app'>

  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <bound method Gateway.start_response of <cheroot.wsgi.Gateway_10 object at 0xae566b10>>
           │    │        └ {'ACTUAL_SERVER_PROTOCOL': 'HTTP/1.1', 'PATH_INFO': '/entry_list/1/entries', 'QUERY_STRING': 'page=1&per_page=30&sort_by=adde...
           │    └ <function Flask.wsgi_app at 0xb256f5d0>
           └ <Flask 'flexget.api.app'>

  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0xb256f150>
               └ <Flask 'flexget.api.app'>

> File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0xb256f108>
         └ <Flask 'flexget.api.app'>

  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
           │    │              │    │           │   └ {'list_id': 1}
           │    │              │    │           └ <Request 'http://192.168.xxx.xxx:5050/api/entry_list/1/entries?page=1&per_page=30&sort_by=added&order=desc' [GET]>
           │    │              │    └ 'entry_list_entry_list_entries_api'
           │    │              └ <Rule '/entry_list/<list_id>/entries/' (GET, HEAD, OPTIONS, POST) -> entry_list_entry_list_entries_api>
           │    └ {'static': <bound method _PackageBoundObject.send_static_file of <Flask 'flexget.api.app'>>, 'specs': <function View.as_view....
           └ <Flask 'flexget.api.app'>

  File "/usr/local/lib/python3.7/dist-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
           │         │       └ {'list_id': 1}
           │         └ ()
           └ <function View.as_view.<locals>.view at 0xb1648d68>

  File "/usr/local/lib/python3.7/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
           │    │                 │       └ {'list_id': 1}
           │    │                 └ ()
           │    └ <function Resource.dispatch_request at 0xb24e7a98>
           └ <flexget.components.managed_lists.lists.entry_list.api.EntryListEntriesAPI object at 0xaef7e830>

  File "/usr/local/lib/python3.7/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
           │     │       └ {'list_id': 1}
           │     └ ()
           └ <function with_session.<locals>.decorator.<locals>.wrapper at 0xa4b858e8>

  File "/usr/local/lib/python3.7/dist-packages/flexget/api/app.py", line 74, in wrapped
    rv = f(*args, **kwargs)
         │  │       └ {'list_id': 1}
         │  └ ()
         └ <function with_session.<locals>.decorator.<locals>.wrapper at 0xa4b85468>

  File "/usr/local/lib/python3.7/dist-packages/flexget/utils/database.py", line 29, in wrapper
    return func(*args, **kwargs)
           │     │       └ {'list_id': 1, 'session': <sqlalchemy.orm.session.ContextSession object at 0xa423f730>}
           │     └ ()
           └ <bound method EntryListEntriesAPI.get of <flexget.components.managed_lists.lists.entry_list.api.EntryListEntriesAPI object at...

  File "/usr/local/lib/python3.7/dist-packages/flexget/api/app.py", line 367, in wrapped
    rv = method(*args, **kwargs)
         │       │       └ {'list_id': 1, 'session': <sqlalchemy.orm.session.ContextSession object at 0xa423f730>}
         │       └ (<flexget.components.managed_lists.lists.entry_list.api.EntryListEntriesAPI object at 0xaef7e830>,)
         └ <function EntryListEntriesAPI.get at 0xb1648d20>

  File "/usr/local/lib/python3.7/dist-packages/flexget/components/managed_lists/lists/entry_list/api.py", line 221, in get
    rsp = jsonify(entries)
          │       └ [{'id': 280, 'list_id': 1, 'added_on': datetime.datetime(2020, 1, 27, 16, 39, 25, 781211), 'title': 'The Expanse', 'original_...
          └ <function jsonify at 0xb2547108>

  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
    │     │            │                  └ (', ', ': ')
    │     │            └ 2
    │     └ [{'id': 280, 'list_id': 1, 'added_on': datetime.datetime(2020, 1, 27, 16, 39, 25, 781211), 'title': 'The Expanse', 'original_...
    └ <function dumps at 0xb254cf18>

  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
         │     │     │      └ {'indent': 2, 'separators': (', ', ': '), 'cls': <class 'flask.json.JSONEncoder'>, 'sort_keys': True}
         │     │     └ [{'id': 280, 'list_id': 1, 'added_on': datetime.datetime(2020, 1, 27, 16, 39, 25, 781211), 'title': 'The Expanse', 'original_...
         │     └ <function dumps at 0xb5fd62b8>
         └ <module 'json' from '/usr/lib/python3.7/json/__init__.py'>

  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
      │          └ [{'id': 280, 'list_id': 1, 'added_on': datetime.datetime(2020, 1, 27, 16, 39, 25, 781211), 'title': 'The Expanse', 'original_...
      └ {}
  File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
                  └ <generator object _make_iterencode.<locals>._iterencode at 0xa61c94b0>
  File "/usr/lib/python3.7/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
               │                │  └ 0
               │                └ [{'id': 280, 'list_id': 1, 'added_on': datetime.datetime(2020, 1, 27, 16, 39, 25, 781211), 'title': 'The Expanse', 'original_...
               └ <function _make_iterencode.<locals>._iterencode_list at 0xa4151930>
  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
               └ <generator object _make_iterencode.<locals>._iterencode_dict at 0xa5f4d630>
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
               └ <generator object _make_iterencode.<locals>._iterencode_dict at 0xa5f4d4f0>
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
               └ <generator object _make_iterencode.<locals>._iterencode at 0xa5f4d6b0>
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
        │        └ <Quality(resolution=unknown,source=unknown,codec=unknown,audio=unknown)>
        └ <bound method JSONEncoder.default of <flask.json.JSONEncoder object at 0xb0d63ad0>>

  File "/usr/local/lib/python3.7/dist-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
           │     │           │       │     └ <Quality(resolution=unknown,source=unknown,codec=unknown,audio=unknown)>
           │     │           │       └ <flask.json.JSONEncoder object at 0xb0d63ad0>
           │     │           └ <function JSONEncoder.default at 0xb5fd6198>
           │     └ <class 'json.encoder.JSONEncoder'>
           └ <module 'json' from '/usr/lib/python3.7/json/__init__.py'>

  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type Quality is not JSON serializable
```
</details>

### Additional information:

- FlexGet version: 3.1.13
- Installation method: pip
- OS and version: 
Linux 4.19.93-v7l+ #1290 SMP Fri Jan 10 16:45:11 GMT 2020 armv7l GNU/Linux 
Raspian BUSTER
Python 3.7.3
- Browser Verson: Google Chrome Version 79.0.3945.130 (Offizieller Build) (64-Bit)
- reset Database without success

**Comment by mami7880** [comment]
> We'll need to update this line so that it makes sure to return something json serializable:
> 
> https://github.com/Flexget/Flexget/blob/10646fd7f8b47c361faaac8cca3da1992f622fe6/flexget/components/managed_lists/lists/entry_list/db.py#L93
> 
> Probably something recursive that steps through data structures, and if the variable isn't json serializable just calls `str()` on it.

That will be right what you say.
Thank you very much
