### ISSUE TITLE
Pluging Medusa List - HTTPError: 401 Client Error

### ISSUE THREAD

**Issue by luciofsl** [Flexget/Flexget#2585]
Hi,

I'm trying to use the pluging medusa, but is crashing with the following error.
The user and password are correct, I can login with success.

```
2020-01-31 16:23:13 DEBUG    manager                       Config file /srv/flexget/config.yml selected
2020-01-31 16:23:13 DEBUG    manager                       sys.defaultencoding: utf-8
2020-01-31 16:23:13 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2020-01-31 16:23:13 DEBUG    manager                       flexget detected io encoding: utf-8
2020-01-31 16:23:13 DEBUG    manager                       os.path.supports_unicode_filenames: False
2020-01-31 16:23:13 DEBUG    manager                       Config file /srv/flexget/config.yml selected
2020-01-31 16:23:13 DEBUG    manager                       sys.defaultencoding: utf-8
2020-01-31 16:23:13 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2020-01-31 16:23:13 DEBUG    manager                       flexget detected io encoding: utf-8
2020-01-31 16:23:13 DEBUG    manager                       os.path.supports_unicode_filenames: False
2020-01-31 16:23:13 DEBUG    plugin                        Trying to load plugins from: ['/srv/flexget/plugins', '/srv/flexget/lib/python3.6/site-packages/flexget/plugins']
2020-01-31 16:23:13 DEBUG    plugin                        Plugin `memusage` requires plugin `ext lib `guppy`` to load.
2020-01-31 16:23:13 DEBUG    plugin                        Trying to load components from: ['/srv/flexget/components', '/srv/flexget/lib/python3.6/site-packages/flexget/components']
2020-01-31 16:23:14 DEBUG    plugin                        Plugins took 1.17 seconds to load. 302 plugins in registry.
2020-01-31 16:23:14 DEBUG    manager                       Connecting to: sqlite:////srv/flexget/db-config.sqlite
2020-01-31 16:23:14 DEBUG    manager                       config_name: config
2020-01-31 16:23:14 DEBUG    manager                       config_base: /srv/flexget
2020-01-31 16:23:14 DEBUG    manager                       New config data loaded.
2020-01-31 16:23:14 DEBUG    schema                        current flexget version already exist in db 3.1.15
2020-01-31 16:23:14 DEBUG    parsing                       setting default movie parser to internal. (options: {'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7fa93eb74978>, 'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7fa93eb749e8>})
2020-01-31 16:23:14 DEBUG    parsing                       setting default series parser to internal. (options: {'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7fa93eb74978>, 'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7fa93eb749e8>})
2020-01-31 16:23:14 DEBUG    cron_env                      Encoding utf-8 stored
2020-01-31 16:23:14 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'utf-8'
2020-01-31 16:23:14 DEBUG    task_queue                    task queue shutdown requested
2020-01-31 16:23:14 VERBOSE  task_queue                    There are 3 tasks to execute. Shutdown will commence when they have completed.
2020-01-31 16:23:14 DEBUG    task          torrentleech    executing torrentleech
2020-01-31 16:23:14 DEBUG    template      torrentleech    Merging template p2p_program into task torrentleech
2020-01-31 16:23:14 DEBUG    template      torrentleech    Merging template serielist into task torrentleech
2020-01-31 16:23:14 DEBUG    utils.requests torrentleech    POSTing URL http://192.168.17.204:8081/api/v2/authenticate with args () and kwargs {'data': None, 'json': {'username': 'medusa', 'password': 'medusa'}, 'timeout': 30}
2020-01-31 16:23:14 DEBUG    utils.requests torrentleech    GETing URL http://192.168.17.204:8081/api/v2/series with args () and kwargs {'params': {'limit': 1000}, 'headers': {'authorization': "Bearer b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNZWR1c2EgMC4zLjEwIiwiaWF0IjoxNTgwNDg3Nzk0LCJqdGkiOiJPUlJVTXQ5WEhoZDByalR5S0lnVyIsImV4cCI6MTU4MDU3NDE5NCwidXNlcm5hbWUiOiJtZWR1c2EiLCJhcGlLZXkiOiI3NWVhYWM4ZTY3YzRhNWIyODQ5MmZmZjk3ODRjNDZhMCJ9.1e0Ys-BQ228M6cCkM-V8vW9PumrwLQKZdWFY9iYisOE'"}, 'allow_redirects': True, 'timeout': 30}
2020-01-31 16:23:14 CRITICAL task          torrentleech    BUG: Unhandled error in plugin configure_series: 401 Client Error: Unauthorized for url: http://192.168.17.204:8081/api/v2/series?limit=1000
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fa9455499d8>
    └ <Thread(task_queue, started daemon 140364869048064)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fa9455497b8>
    └ <Thread(task_queue, started daemon 140364869048064)>
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140364869048064)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140364869048064)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fa93eb61fd0>>
    └ <Thread(task_queue, started daemon 140364869048064)>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/task_queue.py", line 45, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7fa9416cf1e0>
    │    └ <flexget.task.Task object at 0x7fa93e2c30b8>
    └ <flexget.task_queue.TaskQueue object at 0x7fa93eb61fd0>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/task.py", line 79, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7fa93e2c30b8>
           └ <function Task.execute at 0x7fa9416cf158>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/task.py", line 696, in execute
    self._execute()
    │    └ <function Task._execute at 0x7fa9416cf0d0>
    └ <flexget.task.Task object at 0x7fa93e2c30b8>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/task.py", line 662, in _execute
    self.__run_task_phase(phase)
    │                     └ 'prepare'
    └ <flexget.task.Task object at 0x7fa93e2c30b8>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/task.py", line 488, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7fa93e2c30b8>, {'from': {'medusa': {'base_url': 'http://192.168.17.204', 'port': 8081, 'usern...
               │                 │       └ 'prepare'
               │                 └ <PluginInfo(name=configure_series)>
               └ <flexget.task.Task object at 0x7fa93e2c30b8>
> File "/srv/flexget/lib/python3.6/site-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7fa93e2c30b8>, {'from': {'medusa': {'base_url': 'http://192.168.17.204', 'port': 8081, 'usern...                  └ <Event(name=plugin.configure_series.prepare,func=on_task_prepare,priority=128)>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7fa93e2c30b8>, {'from': {'medusa': {'base_url': 'http://192.168.17.204', 'port': 8081, 'usern...               │    └ <bound method ConfigureSeries.on_task_prepare of <flexget.components.series.configure_series.ConfigureSeries object at 0x7fa9...
           └ <Event(name=plugin.configure_series.prepare,func=on_task_prepare,priority=128)>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/components/series/configure_series.py", line 53, in on_task_prepare
    result = method(task, input_config)
             │      │     └ {'base_url': 'http://192.168.17.204', 'port': 8081, 'username': 'medusa', 'password': 'medusa', 'only_monitored': False, 'inc...             │      └ <flexget.task.Task object at 0x7fa93e2c30b8>
             └ <Event(name=plugin.medusa.input,func=on_task_input,priority=128)>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7fa93e2c30b8>, {'base_url': 'http://192.168.17.204', 'port': 8081, 'username': 'medusa', 'pas...               │    └ <bound method Medusa.on_task_input of <flexget.plugins.input.medusa.Medusa object at 0x7fa93f3e2c18>>
           └ <Event(name=plugin.medusa.input,func=on_task_input,priority=128)>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/plugins/input/medusa.py", line 81, in on_task_input
    '{}/series'.format(base_url), params=params, headers=headers
                       │                 │               └ {'authorization': "Bearer b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNZWR1c2EgMC4zLjEwIiwiaWF0IjoxNTgwNDg3Nzk0LCJqdGki...
                       │                 └ {'limit': 1000}
                       └ 'http://192.168.17.204:8081/api/v2'
  File "/srv/flexget/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
           │    │              │      └ {'params': {'limit': 1000}, 'headers': {'authorization': "Bearer b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNZWR1c2EgM...
           │    │              └ 'http://192.168.17.204:8081/api/v2/series'
           │    └ <function Session.request at 0x7fa94172d268>
           └ <flexget.utils.requests.Session object at 0x7fa93e2c31d0>
  File "/srv/flexget/lib/python3.6/site-packages/flexget/utils/requests.py", line 257, in request
    result.raise_for_status()
    │      └ <function Response.raise_for_status at 0x7fa94253b268>
    └ <Response [401]>
  File "/srv/flexget/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
          │         │                        └ <Response [401]>
          │         └ '401 Client Error: Unauthorized for url: http://192.168.17.204:8081/api/v2/series?limit=1000'
          └ <class 'requests.exceptions.HTTPError'>

requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://192.168.17.204:8081/api/v2/series?limit=1000
Traceback (most recent call last):
  File "/srv/flexget/lib/python3.6/site-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
  File "/srv/flexget/lib/python3.6/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/srv/flexget/lib/python3.6/site-packages/flexget/components/series/configure_series.py", line 53, in on_task_prepare
    result = method(task, input_config)
  File "/srv/flexget/lib/python3.6/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/srv/flexget/lib/python3.6/site-packages/flexget/plugins/input/medusa.py", line 81, in on_task_input
    '{}/series'.format(base_url), params=params, headers=headers
  File "/srv/flexget/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/srv/flexget/lib/python3.6/site-packages/flexget/utils/requests.py", line 257, in request
    result.raise_for_status()
  File "/srv/flexget/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://192.168.17.204:8081/api/v2/series?limit=1000
```

**Comment by luciofsl** [comment]
I made a network capture, to show the issue.
```
#############Request#############
POST /api/v2/authenticate HTTP/1.1
Host: 192.168.17.204:8081
User-Agent: FlexGet/3.1.15 (www.flexget.com)
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 46
Content-Type: application/json

{"username": "medusa", "password": "password"}

#############Response#############
HTTP/1.1 200 OK
Server: TornadoServer/5.1.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 06 Feb 2020 15:58:10 GMT
X-Medusa-Server: 0.3.11
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, Accept, Authorization, Content-Type, X-Requested-With, X-CSRF-Token, X-Api-Key, X-Medusa-Server
Access-Control-Allow-Methods: OPTIONS, POST
Content-Length: 297
Vary: Accept-Encoding

{"token": "b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNZWR1c2EgMC4zLjExIiwiaWF0IjoxNTgxMDA0NjkwLCJqdGkiOiJwZ25rdXI2WDZrOEdRZjBleGc1OCIsImV4cCI6MTU4MTA5MTA5MCwidXNlcm5hbWUiOiJtZWR1c2EiLCJhcGlLZXkiOiI3NWVhYWM4ZTY3YzRhNWIyODQ5MmZmZjk3ODRjNDZhMCJ9.LU7fdfIU9wFVvg_nsJpPzUgOUQ8juPR0t6_uACfr3Zc'"}




#############Request#############
GET /api/v2/series?limit=1000 HTTP/1.1
Host: 192.168.17.204:8081
User-Agent: FlexGet/3.1.15 (www.flexget.com)
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
authorization: Bearer b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNZWR1c2EgMC4zLjExIiwiaWF0IjoxNTgxMDA0NjkwLCJqdGkiOiJwZ25rdXI2WDZrOEdRZjBleGc1OCIsImV4cCI6MTU4MTA5MTA5MCwidXNlcm5hbWUiOiJtZWR1c2EiLCJhcGlLZXkiOiI3NWVhYWM4ZTY3YzRhNWIyODQ5MmZmZjk3ODRjNDZhMCJ9.LU7fdfIU9wFVvg_nsJpPzUgOUQ8juPR0t6_uACfr3Zc'

#############Response#############
HTTP/1.1 401 Unauthorized
Server: TornadoServer/5.1.1
Content-Type: application/json; charset=UTF-8
Date: Thu, 06 Feb 2020 15:58:10 GMT
X-Medusa-Server: 0.3.11
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, Accept, Authorization, Content-Type, X-Requested-With, X-CSRF-Token, X-Api-Key, X-Medusa-Server
Access-Control-Allow-Methods: OPTIONS, GET, POST, PATCH, DELETE
Content-Length: 27
Vary: Accept-Encoding

{"error": "Invalid token."}

**Comment by putyn** [comment]
for some reason, the requests (which is actually a subclass of the requests session class) [implementation](https://github.com/Flexget/Flexget/blob/7e32250bc82a45ac1b5f8c48cd4bdf94bd19251d/flexget/utils/requests.py#L171) in flexget sets raise_for_status to True, this means that any status_code other than 2xx will rise a HTTPError exception

You can stop this behavior and deal with the different status_code by passing the raise_status=False to your requests.

I have discovered this working on a search plugin where the API also responds with different error codes, but couldn't really find a reason why raise_for_status is enabled by default, maybe one of the core developers can explain the motivation

**Comment by gazpachoking** [comment]
> I have discovered this working on a search plugin where the API also responds with different error codes, but couldn't really find a reason why raise_for_status is enabled by default, maybe one of the core developers can explain the motivation

When we transitioned to requests from urllib, it made things easier. I wouldn't do it the same again now though. I wouldn't be against switching that default, but we'd have to be careful to change the flag for any plugins relying on that behavior.

**Comment by luciofsl** [comment]
I just change the medusa pluging "/lib/python3.6/site-packages/flexget/plugins/input/medusa.py".
And now is working.

```
        api_key = task.requests.post('{}/authenticate'.format(base_url), json=body_auth).json()[
            'token'
        ]
        api_key = api_key[2:-1]

        headers = {'authorization': 'Bearer ' + api_key}
```
https://github.com/pymedusa/Medusa/issues/7777

**Comment by p0psicles** [comment]
TBH it should not give you back the binary literal string. So if you want to add a workaround. I would check if the b' is in there before slicing it.
