### ISSUE TITLE
 'utf-8' codec can't encode character '\udce4' 

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2588]
flexget version 3.1.15
ubuntu, python3

```
2020-02-01 02:47:40 VERBOSE  manipulate    Library-Sorting-move-series Field `title` is now `One Piece - S17E54 - Durchbruch der feindlichen Linien - Ruffy und Zorros Gegenangriff beginnt - JAP [81797]`
2020-02-01 02:47:40 VERBOSE  manipulate    Library-Sorting-move-series Modified 498 entries.
--- Logging error in Loguru Handler #3 ---
Record was: {'elapsed': datetime.timedelta(0, 31, 407024), 'exception': (type=<class 'UnicodeEncodeError'>, value=UnicodeEncodeError('utf-8', "One Piece - Aus Beauregard wird K\udce4pt'n Black EP206.One.Piece.Nur.fliegen.ist.schoener.", 33, 34, 'surrogates not allowed'), traceback=<traceback object at 0x7f010e916a88>), 'extra': {'task': 'Library-Sorting-move-series', 'session_id': None, 'task_id': '055713'}, 'file': (name='task.py', path='/usr/local/lib/python3.6/dist-packages/flexget/task.py'), 'function': '__run_plugin', 'level': (name='CRITICAL', no=50, icon='☠️'), 'line': 561, 'message': "BUG: Unhandled error in plugin retry_failed: 'utf-8' codec can't encode character '\\udce4' in position 33: surrogates not allowed", 'module': 'task', 'name': 'task', 'process': (id=18124, name='MainProcess'), 'thread': (id=139642541631232, name='task_queue'), 'time': datetime(2020, 2, 1, 2, 48, 6, 189325, tzinfo=datetime.timezone(datetime.timedelta(0, 3600), 'CET'))}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/components/failed/retry_failed.py", line 126, in on_task_filter
    .filter(db.FailedEntry.url == entry['original_url'])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/cli/performance.py", line 57, in monkeypatched
    return orig_execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 33: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/loguru/_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "/usr/local/lib/python3.6/dist-packages/loguru/_file_sink.py", line 179, in write
    self._file.write(message)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 3870: surrogates not allowed
--- End of logging error ---
2020-02-01 02:48:06 CRITICAL task          Library-Sorting-move-series BUG: Unhandled error in plugin retry_failed: 'utf-8' codec can't encode character '\udce4' in position 33: surrogates not allowed
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7f011a6ffc80>
    -> <Thread(task_queue, started daemon 139642541631232)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x7f011a6ffa60>
    -> <Thread(task_queue, started daemon 139642541631232)>
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(task_queue, started daemon 139642541631232)>
    |    |        |    -> ()
    |    |        -> <Thread(task_queue, started daemon 139642541631232)>
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f0110e61198>>
    -> <Thread(task_queue, started daemon 139642541631232)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 45, in run
    self.current_task.execute()
    |    |            -> <function Task.execute at 0x7f0114a9fea0>
    |    -> <flexget.task.Task object at 0x7f0110817978>
    -> <flexget.task_queue.TaskQueue object at 0x7f0110e61198>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 79, in wrapper
    return func(self, *args, **kw)
           |    |      |       -> {}
           |    |      -> ()
           |    -> <flexget.task.Task object at 0x7f0110817978>
           -> <function Task.execute at 0x7f0114a9fe18>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 696, in execute
    self._execute()
    |    -> <function Task._execute at 0x7f0114a9fd90>
    -> <flexget.task.Task object at 0x7f0110817978>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 662, in _execute
    self.__run_task_phase(phase)
    |                     -> 'filter'
    -> <flexget.task.Task object at 0x7f0110817978>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 488, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               |                 |       |      -> (<flexget.task.Task object at 0x7f0110817978>, {'retry_time': '60 seconds', 'retry_time_multiplier': 1, 'max_retries': 8})
               |                 |       -> 'filter'
               |                 -> <PluginInfo(name=retry_failed)>
               -> <flexget.task.Task object at 0x7f0110817978>

> File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
             |       |       -> {}
             |       -> (<flexget.task.Task object at 0x7f0110817978>, {'retry_time': '60 seconds', 'retry_time_multiplier': 1, 'max_retries': 8})
             -> <Event(name=plugin.retry_failed.filter,func=on_task_filter,priority=255)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.task.Task object at 0x7f0110817978>, {'retry_time': '60 seconds', 'retry_time_multiplier': 1, 'max_retries': 8})
           |    -> <bound method PluginFailed.on_task_filter of <flexget.components.failed.retry_failed.PluginFailed object at 0x7f0110ee0c88>>
           -> <Event(name=plugin.retry_failed.filter,func=on_task_filter,priority=255)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/components/failed/retry_failed.py", line 126, in on_task_filter
    .filter(db.FailedEntry.url == entry['original_url'])
            |  |           |      -> <Entry(title=One Piece - Aus Beauregard wird K?pt'n Black EP206.One.Piece.Nur.fliegen.ist.schoener.,state=undecided)>
            |  |           -> <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f011110d308>
            |  -> <class 'flexget.components.failed.db.FailedEntry'>
            -> <module 'flexget.components.failed.db' from '/usr/local/lib/python3.6/dist-packages/flexget/components/failed/db.py'>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
               -> <sqlalchemy.orm.query.Query object at 0x7f010e9b06d8>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
                -> <sqlalchemy.orm.query.Query object at 0x7f010e9b0550>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
           |    |                      -> <sqlalchemy.orm.query.QueryContext object at 0x7f01102b4888>
           |    -> <function Query._execute_and_instances at 0x7f01153c91e0>
           -> <sqlalchemy.orm.query.Query object at 0x7f010e9b0550>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
             |    |       |            |          |    -> immutabledict({})
             |    |       |            |          -> <sqlalchemy.orm.query.Query object at 0x7f010e9b0550>
             |    |       |            -> <member 'statement' of 'QueryContext' objects>
             |    |       -> <sqlalchemy.orm.query.QueryContext object at 0x7f01102b4888>
             |    -> <function startup.<locals>.monkeypatched at 0x7f01104ba488>
             -> <sqlalchemy.engine.base.Connection object at 0x7f010e99d860>

  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/cli/performance.py", line 57, in monkeypatched
    return orig_execute(*args, **kwargs)
           |             |       -> {}
           |             -> (<sqlalchemy.engine.base.Connection object at 0x7f010e99d860>, <sqlalchemy.sql.selectable.Select at 0x7f010e9a73c8; Select ob...
           -> <function Connection.execute at 0x7f0115ea6048>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
           |    |     |            -> {}
           |    |     -> (immutabledict({}),)
           |    -> <sqlalchemy.engine.base.Connection object at 0x7f010e99d860>
           -> <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.selectable.Select at 0x7f010e9a73c8; Select object>>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
           |          |                      |     |            -> {}
           |          |                      |     -> (immutabledict({}),)
           |          |                      -> <sqlalchemy.sql.selectable.Select at 0x7f010e9a73c8; Select object>
           |          -> <function Connection._execute_clauseelement at 0x7f0115ea6268>
           -> <sqlalchemy.engine.base.Connection object at 0x7f010e99d860>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
    -> [immutabledict({})]

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
       |          |           |       -> <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x7f010e9c72b0>
       |          |           -> <sqlite3.Cursor object at 0x7f01102a5030>
       |          -> ("One Piece - Aus Beauregard wird K\udce4pt'n Black EP206.One.Piece.Nur.fliegen.ist.schoener.", 'file:///mnt/media/Anime/One%...
       -> 'SELECT failed.id AS failed_id, failed.title AS failed_title, failed.url AS failed_url, failed.tof AS failed_tof, failed.reas...

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
    |    |        -> (<class 'UnicodeEncodeError'>, UnicodeEncodeError('utf-8', "One Piece - Aus Beauregard wird K\udce4pt'n Black EP206.One.Piece...
    |    -> <function reraise at 0x7f0116476e18>
    -> <module 'sqlalchemy.util' from '/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/__init__.py'>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
          -> UnicodeEncodeError('utf-8', "One Piece - Aus Beauregard wird K\udce4pt'n Black EP206.One.Piece.Nur.fliegen.ist.schoener.", 33...

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
    |       |          |           -> <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x7f010e9c72b0>
    |       |          -> ("One Piece - Aus Beauregard wird K\udce4pt'n Black EP206.One.Piece.Nur.fliegen.ist.schoener.", 'file:///mnt/media/Anime/One%...
    |       -> 'SELECT failed.id AS failed_id, failed.title AS failed_title, failed.url AS failed_url, failed.tof AS failed_tof, failed.reas...
    -> <sqlite3.Cursor object at 0x7f01102a5030>

  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
    |      |       |          -> ("One Piece - Aus Beauregard wird K\udce4pt'n Black EP206.One.Piece.Nur.fliegen.ist.schoener.", 'file:///mnt/media/Anime/One%...
    |      |       -> 'SELECT failed.id AS failed_id, failed.title AS failed_title, failed.url AS failed_url, failed.tof AS failed_tof, failed.reas...
    |      -> <method 'execute' of 'sqlite3.Cursor' objects>
    -> <sqlite3.Cursor object at 0x7f01102a5030>

UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 33: surrogates not allowed
2020-02-01 02:48:06 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Exception in thread task_queue:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 521, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/components/failed/retry_failed.py", line 126, in on_task_filter
    .filter(db.FailedEntry.url == entry['original_url'])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3265, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3043, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/cli/performance.py", line 57, in monkeypatched
    return orig_execute(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1478, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 33: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 45, in run
    self.current_task.execute()
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 79, in wrapper
    return func(self, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 696, in execute
    self._execute()
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 662, in _execute
    self.__run_task_phase(phase)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 488, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 562, in __run_plugin
    traceback = self.manager.crash_report()
  File "/usr/local/lib/python3.6/dist-packages/flexget/manager.py", line 1035, in crash_report
    outfile.writelines(flexget.log.debug_buffer)
  File "/usr/lib/python3.6/codecs.py", line 724, in writelines
    return self.writer.writelines(list)
  File "/usr/lib/python3.6/codecs.py", line 384, in writelines
    self.write(''.join(list))
  File "/usr/lib/python3.6/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 25401: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 53, in run
    self.current_task.manager.crash_report()
  File "/usr/local/lib/python3.6/dist-packages/flexget/manager.py", line 1035, in crash_report
    outfile.writelines(flexget.log.debug_buffer)
  File "/usr/lib/python3.6/codecs.py", line 724, in writelines
    return self.writer.writelines(list)
  File "/usr/lib/python3.6/codecs.py", line 384, in writelines
    self.write(''.join(list))
  File "/usr/lib/python3.6/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 25163: surrogates not allowed
```

**Comment by paranoidi** [comment]
I have a suspicion that you are trying to sort files from filesystem and since linux filesystem has no enforced encoding (excluding zfs master race) it has a file with Japanese encoding which breaks when utf-8 encoding is expected.

If you can give us example config & filename (in raw bytes) we might be able to add better error handling ..

It still won't work, it will fail the entry, but at least it would not crash and cause whole task to be aborted.

**Comment by snickers2k** [comment]
i'm sorry. this is not a flexget bug. filebot had the same issue. but gave the output "file does not exist". seems like a problem with my utf8 enviroment_variables. "ü" "ä" "ö" "ß" etc. are not recognized at all.
