### ISSUE TITLE
Failed to upgrade database for plugin input cache (won't run) 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#2590]
### Expected behaviour:
For database to be updated and flexget to run tasks

### Actual behaviour:
After upgrading, the database tries to update for the imdb_watchlist plugin and I get the error 

### Steps to reproduce:
- Step 1: start daemon, or execute task

#### Config:
<details>
 <summary>(click to expand)</summary>

```
web_server: yes
variables: secret.yml
templates:
  global:
    no_entries_ok: yes
    notify:
      abort:
        via:
          - telegram:
              bot_token: '{? telegram.token ?}'
              parse_mode: markdown
              disable_previews: no
              recipients:
                - username: '{? telegram.usr ?}'


##################################################################
#    TV TEMPLATE
##################################################################

  vic_tv:
    set:
      path: /media/CHEWYHDD/CHEWY/Videos/temp
      move_completed_path: /media/CHEWYHDD/CHEWY/Videos/TV/NEW EPISODES/{{tvdb_series_name}}/Season {{tvdb_season}}/
      label: NEW EPISODES
    configure_series:
      from:
        trakt_list:
          username: '{? trak.usr ?}'
          account: '{? trak.acct ?}'
          list: vic tv
          type: shows
      settings:
        quality: 1080p
        propers: 16 hours
        specials: no
    verify_ssl_certificates: no
    thetvdb_lookup: yes
    series:
      - Shameless (2011):
          alternate_name: Shameless (US)
      - Tell Me a Story (2018):
          alternate_name: Tell Me a Story (US)
      - Real Time with Bill Maher (2003):
          identified_by: ep
      - Masterchef (2010):
          alternate_name: Masterchef (US)      
    deluge:
      host: localhost
      port: '{? deluge.port ?}'
      username: '{? deluge.usr ?}'
      password: '{? deluge.pwd ?}'

##################################################################
#    DOWNLOAD NOTIFICATION TEMPLATE
##################################################################


  telegram_notify:
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    notify:
      entries:
        title: 'flexget {{task}}'
        message: |+
          {% if series_name is defined -%}
          *{{series_name}}* - {{series_id}} - {{quality|d('')}}
          *{{tvmaze_ep_name|d(tvdb_ep_name)|d('')}}*
          *Air date:* {{tvdb_ep_air_date|d(tvmaze_episode_airdate)|d('')}}
          *Summary:* {{tvdb_ep_overview}}
          [Image]({{tvmaze_series_original_image|replace("_", "%5F")}})
          [Show page]({{tvmaze_series_url|replace("_", "%5F")}})
          {% elif imdb_name is defined -%}
          *{{imdb_name}}* - ({{imdb_year}})
          {{quality|d('')}}
          {{imdb_score}}/10 - {{imdb_votes}} votes
          {{imdb_genres|join(', ')|title}} 
          *Plot:* {{imdb_plot_outline}}
          [Image]({{tmdb_posters[0]|replace("_", "%5F")}})
          [Movie Page]({{imdb_url|d('')}})
          {% else -%}
          {{title}}
          {%- endif -%}
        via:
          - telegram:
              bot_token: '{? telegram.token ?}'
              parse_mode: markdown
              disable_previews: no
              recipients:
                - username: '{? telegram.usr ?}'


##################################################################
#   MOVIE TEMPLATE
##################################################################

  movie:
    tmdb_lookup: yes 
    proper_movies: no
    content_size:
      max: 5000
      strict: no
    content_filter: 
      reject:
        - '*.zip'
        - '*.wmv'
        - '*.wma'
        - '*[cC]odec*'
        - '*[rR]eadme*'
    exists_movie:
      - /media/CHEWYHDD/CHEWY/Videos/Movies
      - /media/CHEWYHDD/CHEWY/Videos/Addison/Addison Movies


#################################################################
#    FILTERS TEMPLATES
##################################################################

  filters:
    regexp:
      reject:
        - \bmsd\b: {from: title}
        - \bgreek\b: {from: title}
        - \bgerman\b: {from: title}
        - \bfrench\b: {from: title}
        - \brussian\b: {from: title}
        - \bswedish\b: {from: title}
        - \bspanish\b: {from: title}
        - \bhindi\b: {from: title}
        - \barabic\b: {from: title}
        - \bitalian\b: {from: title}
        - \bpolish\b: {from: title}
        - \bromanian\b: {from: title}
        - \bdutch\b: {from: title}
        - \bczech\b: {from: title}
        - \bturkish\b: {from: title}
        - \brmvb\b: {from: title}
#        - \bkorean\b: {from: title}
        - \bwmv\b: {from: title}
#        - (s|d)ub(s|bed)?\b: {from: title}
        - \bFRENCH\b: {from: title}
        - \bSPANiSH\b: {from: title}
        - \bLatino\b: {from: title}
        - \btrailer\b: {from: title}
        - \bHDTC\b: {from: title} 
        - \bHDTS\b: {from: title}
        - \bHQTS\b: {from: title}
        - \bHDcam\b: {from: title} 
        - \bR5\b: {from: title}
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}                              # The following are groups with poor quality releases
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \bFLEET\b: {from: title}
        - \b0SEC\b: {from: title}
        - \[facepalm\]: {from: title}
        - FASTSUB: {from: title}
        - VOSTFR: {from: title}
        - Subtitulado: {from: title}
        - \bNORDiC\b: {from: title}
        - \biPad\b: {from: title}
#        - \b(ita|ger|fra|spa|swe|nor|nordic|fr|kor|uk|esp|nl|pl|spanish)\b: {from: title}
        - \bR6\b: {from: title}
        - \bTemporada\b: {from: title}
        - \bDual\b: {from: title}
        - \bTamil*\b: {from: title}
        - \bJapanese\b: {from: title}
        - \bJajji!\b: {from: title}
        - \bdragons.den.(ca|uk)\b: {from: title}
        - \bx265\b: {from: title}
#        - \HC\b: {from: title}
        - \b480p\b: {from: title}
        - \b.TamilRock*\b: {from: title}
        - \b1xbet\b: {from: title}
        - \bCAMRip\b: {from: title}
        - \bHDCAMRip\b: {from: title}


##################################################################
#    TASK SCHEDULES
##################################################################


schedules:

  - tasks: tv_shows
    interval:
      minutes: 5

  - tasks: IMDB
    interval:
      minutes: 30

  - tasks: list_cleanup
    interval:
      weeks: 1


  - tasks: passthepopcorn
    interval: 
      hours: 2

  - tasks: movies
    interval:
      hours: 1


##################################################################
#    TASKS 
##################################################################


tasks:

  tv_shows:
    priority: 1
    template:
      - vic_tv
      - telegram_notify
      - filters
    inputs:
      - rss: '{? btn.url ?}'
#      - rss: '{? mtv.url ?}'


  IMDB:
    imdb_list:
      login: '{? imdb.usr ?}'
      password: '{? imdb.pwd ?}'
      list: watchlist
    accept_all: yes
    seen: 
      fields: [title]
    list_add:
      - movie_list: vic_movies
    priority: 2


  list_cleanup:
    movie_list: vic_movies
    crossmatch:
      from:
        - imdb_list:
            login: '{? imdb.usr ?}'
            password: '{? imdb.pwd ?}'
            list: watchlist
      action: reject
      fields: [imdb_id]
    accept_all: yes
    list_remove:
      - movie_list: vic_movies
    seen: no



  passthepopcorn:
    priority: 4
    template:
      - movie
      - telegram_notify
      - filters
    quality: hdrip+
    imdb_lookup: yes
    list_match:
      from:
        - movie_list: vic_movies
    list_add:
      - entry_list: downloaded_movies
    verify_ssl_certificates: no
    inputs:
      - rss: '{? ptp.url ?}'
    set:
      path: /media/CHEWYHDD/CHEWY/Videos/temp
      move_completed_path: /media/CHEWYHDD/CHEWY/Videos/Movies/
    deluge:
      host: localhost
      port: '{? deluge.port ?}'
      username: '{? deluge.usr ?}'
      password: '{? deluge.pwd ?}'
      label: Movies

  movies:
    priority: 5
    template:
      - movie
      - telegram_notify
      - filters
    discover:
      release_estimations: 
        optimistic: 60 days
      what:
        - movie_list: vic_movies
      from:
        - yts: yes
        - rarbg:
            category: [14, 15, 16, 17, 21, 22, 42, 44, 45, 46, 47, 48]
        - 1337x: yes
        - piratebay:
            category: movies
    interval: 1 hour
    quality: 720p+
    list_match:
      from:
        - movie_list: vic_movies
    list_add:
      - entry_list: downloaded_movies
    torrent_alive: 10
    verify_ssl_certificates: no
    set:
      path: /media/CHEWYHDD/CHEWY/Videos/temp
      move_completed_path: /media/CHEWYHDD/CHEWY/Videos/Movies/
    deluge:
      host: localhost
      port: '{? deluge.port ?}'
      username: '{? deluge.usr ?}'
      password: '{? deluge.pwd ?}'
      ratio: .01
      label: Public      


```
</details>
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
(flexget) pi@pi4:~ $ flexget daemon start -d             2020-02-01 11:18:55 INFO     manager                       Database upgrade is required. Attempting now.
2020-02-01 11:18:55 ERROR    schema                        Failed to upgrade database for plugin input_cache: the JSON object must be str, bytes or bytearray, not NoneTypeTraceback (most recent call last):
  File "/home/pi/flexget/bin/flexget", line 8, in <module>
    sys.exit(main())
    |   |    -> <function main at 0xb667fa98>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/__init__.py", line 41, in main
    manager.start()
    |       -> <function Manager.start at 0xb521f030>
    -> <flexget.manager.Manager object at 0xb57dfa90>
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/manager.py", line 359, in start
    self.initialize()
    |    -> <function Manager.initialize at 0xb521ded0>
    -> <flexget.manager.Manager object at 0xb57dfa90>
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/manager.py", line 231, in initialize
    fire_event('manager.upgrade', self)
    |                             -> <flexget.manager.Manager object at 0xb57dfa90>
    -> <function fire_event at 0xb5794660>
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/event.py", line 110, in fire_event
    result = event(*args, **kwargs)
             |      |       -> {}
             |      -> (<flexget.manager.Manager object at 0xb57dfa90>,)
             -> <Event(name=manager.upgrade,func=upgrade_wrapper,priority=128)>
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.manager.Manager object at 0xb57dfa90>,)
           |    -> <function upgrade.<locals>.upgrade_decorator.<locals>.upgrade_wrapper at 0xb21ee078>
           -> <Event(name=manager.upgrade,func=upgrade_wrapper,priority=128)>
> File "/home/pi/flexget/lib/python3.7/site-packages/flexget/db_schema.py", line 152, in upgrade_wrapper
    new_ver = upgrade_func(current_ver, session)
              |            |            -> <sqlalchemy.orm.session.ContextSession object at 0xb0dd6150>
              |            -> 1
              -> <function upgrade at 0xb21dafa8>
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/cached_input.py", line 44, in upgrade
    e = Entry(json.loads(row['json'], decode_datetime=True))
        |     |    |     -> (44232, None)
        |     |    -> <function loads at 0xb54ec930>
        |     -> <module 'flexget.utils.json' from '/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/json.py'>
        -> <class 'flexget.entry.Entry'>
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/json.py", line 109, in loads
    return json.loads(*args, **kwargs)
           |    |      |       -> {'object_hook': <function _datetime_decoder at 0xb54ec810>, 'cls': <class 'flexget.utils.json.DTDecoder'>}
           |    |      -> (None,)
           |    -> <function loads at 0xb6021e88>
           -> <module 'json' from '/usr/lib/python3.7/json/__init__.py'>

  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '

TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/db_schema.py", line 152, in upgrade_wrapper
    new_ver = upgrade_func(current_ver, session)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/cached_input.py", line 44, in upgrade
    e = Entry(json.loads(row['json'], decode_datetime=True))
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/json.py", line 109, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/flexget/bin/flexget", line 8, in <module>
    sys.exit(main())
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/__init__.py", line 41, in main
    manager.start()
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/manager.py", line 359, in start
    self.initialize()
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/manager.py", line 231, in initialize
    fire_event('manager.upgrade', self)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/event.py", line 110, in fire_event
    result = event(*args, **kwargs)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/db_schema.py", line 163, in upgrade_wrapper
    manager.shutdown(finish_queue=False)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/manager.py", line 1002, in shutdown
    raise RuntimeError('Cannot shutdown manager that was never initialized.')
RuntimeError: Cannot shutdown manager that was never initialized.
(flexget) pi@pi4:~ $
```
</details>

### Additional information:

- FlexGet version: 3.1.16
- Python version: 3.7
- Installation method: Raspberry Pi 4 virtualenv
- Using daemon (yes/no): yes
- OS and version: raspbian buster
- Link to crash log:

**Comment by gazpachoking** [comment]
Hmm. No idea how this could happen, but I'll change the upgrade function so that it just drops stuff instead of crashes in this case.
