### ISSUE TITLE
Not able to intall in FreeBSD jail - FreeNas

### ISSUE THREAD

**Issue by soloam** [Flexget/Flexget#2598]
### Expected behaviour:

I would like to intstall flexget in a freebsd jail (freenas). Freebsd 11.3

### Actual behaviour:

I install python on the jail( tried with pkg install python and pkg install pyton37) and installed pip (pkg install py37-pip)
Made a symb link from /usr/local/bin from python to python3.7

Tried to install flexget both in the venv or in core system, also with root (I destroid the jail and made a new one for every try, to start new) and in all of them I get the error:
```

ERROR: Command errored out with exit status 1:
     command: /home/flexget/flexget/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-shexrsg0/rebulk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-shexrsg0/rebulk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-shexrsg0/rebulk/
    Complete output (25 lines):
    Download error on https://pypi.org/simple/pytest-runner/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076) -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076) -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-shexrsg0/rebulk/setup.py", line 62, in <module>
        setup(**args)
      File "/home/flexget/flexget/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/flexget/flexget/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/flexget/flexget/lib/python3.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/flexget/flexget/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/flexget/flexget/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/flexget/flexget/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/flexget/flexget/lib/python3.7/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/flexget/flexget/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

It seams that it gives a error on getting rebulk. If I try to install rebulk I get the same error.

What can it be the problem?

Thank You

**Comment by paranoidi** [comment]
Hard to say, we do not have experience or instructions on this so you are unfortunately on your own. FlexGet is pretty standard python application without any dependencies that require compilation environment so it should be easier than some other python apps.

Feel free to write installation tutorial in the wiki if you manage to get it up and running :)
