### ISSUE TITLE
Trying to render non string template or unrecognized template format, got 1917

### ISSUE THREAD

**Issue by FeromonDE** [Flexget/Flexget#2640]
```
2020-03-26 10:05:44 DEBUG    util.simple_persistence Clean           Flushing simple persistence for task Clean to db.
2020-03-26 10:05:44 DEBUG    util.simple_persistence Clean           Flushing simple persistence for task None to db.
2020-03-26 10:05:44 DEBUG    manager       Clean_Qnap      Not running db cleanup, last run 2020-03-21 17:16:55
2020-03-26 10:05:44 DEBUG    scheduler                     task finished executing: Clean_Qnap
2020-03-26 10:05:44 DEBUG    task          Clean_Qnap      executing Clean_Qnap
2020-03-26 10:05:44 DEBUG    disable       Clean_Qnap      Disabled built-in plugin(s): seen, seen_info_hash
2020-03-26 10:05:44 DEBUG    backlog       Clean_Qnap      0 entries purged from backlog
2020-03-26 10:05:44 VERBOSE  details       Clean_Qnap      Task didn't produce any entries.
2020-03-26 10:05:44 DEBUG    urlrewriter   Clean_Qnap      Checking 0 entries
2020-03-26 10:05:44 VERBOSE  details       Clean_Qnap      Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)
2020-03-26 10:05:44 DEBUG    disable       Clean_Qnap      Re-enabled builtin plugin(s): seen, seen_info_hash
2020-03-26 10:05:44 DEBUG    util.simple_persistence Clean_Qnap      Flushing simple persistence for task Clean_Qnap to db.
2020-03-26 10:05:44 DEBUG    util.simple_persistence Clean_Qnap      Flushing simple persistence for task None to db.
2020-03-26 10:05:44 DEBUG    manager       NexBox          Not running db cleanup, last run 2020-03-21 17:16:55
2020-03-26 10:05:44 DEBUG    scheduler                     task finished executing: NexBox
2020-03-26 10:05:44 DEBUG    task          NexBox          executing NexBox
2020-03-26 10:05:44 DEBUG    template      NexBox          Merging template Trans_Pause_Nexbox into task NexBox
2020-03-26 10:05:44 DEBUG    template      NexBox          Merging template Notify_UHD_BDRemux_2160p into task NexBox
2020-03-26 10:05:44 DEBUG    template      NexBox          Merging template Notify_UHD_BDRemux_2160p_T into task NexBox
2020-03-26 10:05:44 DEBUG    urlrewrite    NexBox          Added rewrite rutor
2020-03-26 10:05:44 DEBUG    input_cache   NexBox          cache name: rss_b3523be9953ec1cc1b5cd9b5ee4f1079 (has: rss_63c573fac8f9eb0a546a265967e0594f, rss_b497d8b708a5453c2472caa0d544e141, rss_4edaf0540bae69a65f832caefb800d76, rss_2bb0e5e0350b0a225bbf6539d55de6e8)
2020-03-26 10:05:44 DEBUG    rss           NexBox          Requesting task `NexBox` url `https://xxxxxxxxxxxx/tt-rss/public.php?op=rss&id=-1029&key=cgbh275a38291f840e8`
2020-03-26 10:05:44 DEBUG    utils.requests NexBox          GETing URL https://xxxxxxxxxxxx/tt-rss/public.php?op=rss&id=-1029&key=cgbh275a38291f840e8 with args () and kwargs {'timeout': 60, 'headers': {'User-Agent': 'FlexGet/3.1.45 (www.flexget.com)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}, 'auth': None, 'allow_redirects': True}
2020-03-26 10:05:44 DEBUG    rss           NexBox          encoding utf-8
2020-03-26 10:05:44 DEBUG    rss           NexBox          Not grabbing blank field %s from rss for %s.
2020-03-26 10:05:44 DEBUG    rss           NexBox          Not grabbing blank field %s from rss for %s.
2020-03-26 10:05:44 DEBUG    rss           NexBox          Not grabbing blank field %s from rss for %s.
2020-03-26 10:05:44 DEBUG    rss           NexBox          Saving location in rss feed.
2020-03-26 10:05:44 DEBUG    util.simple_persistence NexBox          setting key b3523be9953ec1cc1b5cd9b5ee4f1079_last_entry value '1917 / 1917 (2019) UHD BDRemux 2160p от селезень | 4K | HDR | Dolby Vision | iTunestag:xxxxxxxxxxxx.spdns.de,2020-03-25:/206545'
2020-03-26 10:05:44 DEBUG    input_cache   NexBox          storing entries to cache rss_b3523be9953ec1cc1b5cd9b5ee4f1079 
2020-03-26 10:05:44 DEBUG    backlog       NexBox          0 entries purged from backlog
2020-03-26 10:05:44 VERBOSE  details       NexBox          Produced 3 entries.
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field: `title` from_field: `title` field_value: `1917 / 1917 (2019) UHD BDRemux 2160p от селезень | 4K | HDR | Dolby Vision | iTunes`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field `title` after replace: `1917`
2020-03-26 10:05:44 VERBOSE  manipulate    NexBox          Field `title` is now `1917`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field: `title` from_field: `title` field_value: `1917`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field `title` after replace: `1917`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field: `title` from_field: `title` field_value: `1917 / 1917 (2019) UHD BDRemux 2160p от селезень | 4K | HDR | Dolby Vision TV | iTunes`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field `title` after replace: `1917`
2020-03-26 10:05:44 VERBOSE  manipulate    NexBox          Field `title` is now `1917`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field: `title` from_field: `title` field_value: `1917`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field `title` after replace: `1917`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field: `title` from_field: `title` field_value: `1917 / 1917 (2019) UHD BDRemux 2160p от селезень | 4K | HDR | iTunes`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field `title` after replace: `1917`
2020-03-26 10:05:44 VERBOSE  manipulate    NexBox          Field `title` is now `1917`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field: `title` from_field: `title` field_value: `1917`
2020-03-26 10:05:44 DEBUG    manipulate    NexBox          field `title` after replace: `1917`
2020-03-26 10:05:44 VERBOSE  manipulate    NexBox          Modified 3 entries.
2020-03-26 10:05:44 VERBOSE  task          NexBox          ACCEPTED: `1917` by accept_all plugin
2020-03-26 10:05:44 VERBOSE  task          NexBox          ACCEPTED: `1917` by accept_all plugin
2020-03-26 10:05:44 VERBOSE  task          NexBox          ACCEPTED: `1917` by accept_all plugin
2020-03-26 10:05:44 DEBUG    urlrewriter   NexBox          Checking 3 entries
2020-03-26 10:05:44 DEBUG    urlrewriter   NexBox          Url rewriting http://6tor.net/torrent/749525
2020-03-26 10:05:44 DEBUG    urlrewrite    NexBox          Regexp resolving http://6tor.net/torrent/749525 with rutor
2020-03-26 10:05:44 INFO     urlrewriter   NexBox          Entry '1917' URL rewritten to http://6tor.net/download/749525 (with urlrewrite)
2020-03-26 10:05:44 DEBUG    urlrewriter   NexBox          Url rewriting http://6tor.net/torrent/749491
2020-03-26 10:05:44 DEBUG    urlrewrite    NexBox          Regexp resolving http://6tor.net/torrent/749491 with rutor
2020-03-26 10:05:44 INFO     urlrewriter   NexBox          Entry '1917' URL rewritten to http://6tor.net/download/749491 (with urlrewrite)
2020-03-26 10:05:44 DEBUG    urlrewriter   NexBox          Url rewriting http://6tor.net/torrent/749481
2020-03-26 10:05:44 DEBUG    urlrewrite    NexBox          Regexp resolving http://6tor.net/torrent/749481 with rutor
2020-03-26 10:05:44 INFO     urlrewriter   NexBox          Entry '1917' URL rewritten to http://6tor.net/download/749481 (with urlrewrite)
2020-03-26 10:05:44 INFO     download      NexBox          Downloading: 1917
2020-03-26 10:05:44 DEBUG    download      NexBox          Downloading url 'http://6tor.net/download/749525'
2020-03-26 10:05:44 DEBUG    utils.requests NexBox          GETing URL http://6tor.net/download/749525 with args () and kwargs {'auth': None, 'headers': {'User-Agent': 'FlexGet/3.1.45 (www.flexget.com)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}, 'allow_redirects': True, 'timeout': 30}
2020-03-26 10:05:45 DEBUG    download      NexBox          1917 field file set to: /tmp/tmp650n0nvx/73eb5a848ef541f1bd52cca2e3db92ab
2020-03-26 10:05:45 DEBUG    download      NexBox          Found filename from headers: [rutor.is]1917.2019.BDREMUX.2160p.HDR.DV.seleZen.torrent
2020-03-26 10:05:45 DEBUG    download      NexBox          Mimetype guess for application/x-bittorrent is ['.torrent'] 
2020-03-26 10:05:45 DEBUG    download      NexBox          Filename [rutor.is]1917.2019.BDREMUX.2160p.HDR.DV.seleZen.torrent extension matches to mime-type
2020-03-26 10:05:45 DEBUG    download      NexBox          Finishing download_entry() with filename [rutor.is]1917.2019.BDREMUX.2160p.HDR.DV.seleZen.torrent
2020-03-26 10:05:45 DEBUG    download      NexBox          Successfully retrieved 1917 from http://6tor.net/download/749525
2020-03-26 10:05:45 INFO     download      NexBox          Downloading: 1917
2020-03-26 10:05:45 DEBUG    download      NexBox          Downloading url 'http://6tor.net/download/749491'
2020-03-26 10:05:45 DEBUG    utils.requests NexBox          GETing URL http://6tor.net/download/749491 with args () and kwargs {'auth': None, 'headers': {'User-Agent': 'FlexGet/3.1.45 (www.flexget.com)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}, 'allow_redirects': True, 'timeout': 30}
2020-03-26 10:05:45 DEBUG    download      NexBox          1917 field file set to: /tmp/tmpcprvfbp5/12ef95a533b799ab893ceb23863a23e0
2020-03-26 10:05:45 DEBUG    download      NexBox          Found filename from headers: [rutor.is]1917.2019.BDREMUX.2160p.HDR.DV-TV.seleZen.torrent
2020-03-26 10:05:45 DEBUG    download      NexBox          Mimetype guess for application/x-bittorrent is ['.torrent'] 
2020-03-26 10:05:45 DEBUG    download      NexBox          Filename [rutor.is]1917.2019.BDREMUX.2160p.HDR.DV-TV.seleZen.torrent extension matches to mime-type
2020-03-26 10:05:45 DEBUG    download      NexBox          Finishing download_entry() with filename [rutor.is]1917.2019.BDREMUX.2160p.HDR.DV-TV.seleZen.torrent
2020-03-26 10:05:45 DEBUG    download      NexBox          Successfully retrieved 1917 from http://6tor.net/download/749491
2020-03-26 10:05:45 INFO     download      NexBox          Downloading: 1917
2020-03-26 10:05:45 DEBUG    download      NexBox          Downloading url 'http://6tor.net/download/749481'
2020-03-26 10:05:45 DEBUG    utils.requests NexBox          GETing URL http://6tor.net/download/749481 with args () and kwargs {'auth': None, 'headers': {'User-Agent': 'FlexGet/3.1.45 (www.flexget.com)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}, 'allow_redirects': True, 'timeout': 30}
2020-03-26 10:05:45 DEBUG    download      NexBox          1917 field file set to: /tmp/tmpeqaj06nn/ff0d07c94523edffc7fd774958ced875
2020-03-26 10:05:45 DEBUG    download      NexBox          Found filename from headers: [rutor.is]1917.2019.BDREMUX.2160p.HDR.seleZen.mkv.torrent
2020-03-26 10:05:45 DEBUG    download      NexBox          Mimetype guess for application/x-bittorrent is ['.torrent'] 
2020-03-26 10:05:45 DEBUG    download      NexBox          Filename [rutor.is]1917.2019.BDREMUX.2160p.HDR.seleZen.mkv.torrent extension matches to mime-type
2020-03-26 10:05:45 DEBUG    download      NexBox          Finishing download_entry() with filename [rutor.is]1917.2019.BDREMUX.2160p.HDR.seleZen.mkv.torrent
2020-03-26 10:05:45 DEBUG    download      NexBox          Successfully retrieved 1917 from http://6tor.net/download/749481
2020-03-26 10:05:45 VERBOSE  details       NexBox          Summary - Accepted: 3 (Rejected: 0 Undecided: 0 Failed: 0)
2020-03-26 10:05:45 DEBUG    modif_torrent NexBox          1917 seems to be a torrent
2020-03-26 10:05:45 DEBUG    modif_torrent NexBox          1917 seems to be a torrent
2020-03-26 10:05:45 DEBUG    modif_torrent NexBox          1917 seems to be a torrent
2020-03-26 10:05:45 DEBUG    torrent_files NexBox          1917 files: ['BDMV/AUXDATA/AUXDATA', 'BDMV/BACKUP/BDJO/BDJO', 'BDMV/BACKUP/JAR/JAR', 'BDMV/BDJO/BDJO', 'BDMV/JAR/JAR', 'BDMV/STREAM/00000.m2ts', 'BDMV/BACKUP/CLIPINF/00000.clpi', 'BDMV/index.bdmv', 'BDMV/BACKUP/PLAYLIST/00000.mpls', 'BDMV/BACKUP/index.bdmv', 'BDMV/CLIPINF/00000.clpi', 'BDMV/BACKUP/MovieObject.bdmv', 'BDMV/META/DL/1917_Jacket_LRG_v2.jpg', 'BDMV/META/DL/1917_Jacket_SML_v2.jpg', 'BDMV/META/DL/bdmt_eng.xml', 'BDMV/PLAYLIST/00000.mpls', 'BDMV/MovieObject.bdmv']
2020-03-26 10:05:45 DEBUG    torrent_files NexBox          1917 files: ['1917.2019.BDREMUX.2160p.HDR.DV-TV.seleZen.mp4', '1917.2019.BDREMUX.2160p.HDR.DV-TV.seleZen.srt']
2020-03-26 10:05:45 DEBUG    torrent_files NexBox          1917 files: ['1917.2019.BDREMUX.2160p.HDR.seleZen.mkv']
2020-03-26 10:05:45 DEBUG    torrent_size  NexBox          1917 size: 73948.04738140106 MB
2020-03-26 10:05:45 DEBUG    torrent_size  NexBox          1917 size: 66192.2393245697 MB
2020-03-26 10:05:45 DEBUG    torrent_size  NexBox          1917 size: 63680.02987957001 MB
2020-03-26 10:05:45 DEBUG    transmission  NexBox          Successfully connected to transmission.
2020-03-26 10:05:45 CRITICAL task          NexBox          BUG: Unhandled error in plugin transmission: Trying to render non string template or unrecognized template format, got 1917
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x758e0c90>
    └ <Thread(task_queue, stopped daemon 1759482976)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x758e0b70>
    └ <Thread(task_queue, stopped daemon 1759482976)>
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, stopped daemon 1759482976)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, stopped daemon 1759482976)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x70642c50>>
    └ <Thread(task_queue, stopped daemon 1759482976)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x741f94f8>
    │    └ <flexget.task.Task object at 0x6f9fd8d0>
    └ <flexget.task_queue.TaskQueue object at 0x70642c50>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 80, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x6f9fd8d0>
           └ <function Task.execute at 0x741f94b0>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 697, in execute
    self._execute()
    │    └ <function Task._execute at 0x741f9468>
    └ <flexget.task.Task object at 0x6f9fd8d0>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 663, in _execute
    self.__run_task_phase(phase)
    │                     └ 'output'
    └ <flexget.task.Task object at 0x6f9fd8d0>

  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 489, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x6f9fd8d0>, {'host': '192.168.2.11', 'port': 9094, 'username': 'xxxxxxxxxxxx', 'password': 'xxxxxxxxxxxx...
               │                 │       └ 'output'
               │                 └ <PluginInfo(name=transmission)>
               └ <flexget.task.Task object at 0x6f9fd8d0>

> File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 522, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x6f9fd8d0>, {'host': '192.168.2.11', 'port': 9094, 'username': 'xxxxxxxxxxxx', 'password': 'xxxxxxxxxxxx...
             └ <Event(name=plugin.transmission.output,func=on_task_output,priority=135)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x6f9fd8d0>, {'host': '192.168.2.11', 'port': 9094, 'username': 'xxxxxxxxxxxx', 'password': 'xxxxxxxxxxxx...
           │    └ <bound method PluginTransmission.on_task_output of <flexget.plugins.clients.transmission.PluginTransmission object at 0x71314...
           └ <Event(name=plugin.transmission.output,func=on_task_output,priority=135)>

  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/clients/transmission.py", line 369, in on_task_output
    options = self._make_torrent_options_dict(config, entry)
              │    │                          │       └ <Entry(title=1917,state=accepted)>
              │    │                          └ {'host': '192.168.2.11', 'port': 9094, 'username': 'xxxxxxxxxxxx', 'password': 'xxxxxxxxxxxx4', 'add_paused': True, 'enabled': True, 'm...
              │    └ <function PluginTransmission._make_torrent_options_dict at 0x737577c8>
              └ <flexget.plugins.clients.transmission.PluginTransmission object at 0x71314c30>

  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/clients/transmission.py", line 730, in _make_torrent_options_dict
    post['content_filename'] = entry.render(opt_dic['content_filename'])
    │                          │     │      └ {'path': '/share/My_Book/UltraHD_Films/', 'add_paused': True, 'main_file_only': False, 'main_file_ratio': 0.9, 'magnetization...
    │                          │     └ <function Entry.render at 0x743308e8>
    │                          └ <Entry(title=1917,state=accepted)>
    └ {'paused': True, 'main_file_only': False, 'main_file_ratio': 0.9, 'magnetization_timeout': 0, 'include_subs': False}

  File "/usr/local/lib/python3.6/dist-packages/flexget/entry.py", line 309, in render
    % repr(template)
           └ 1917

ValueError: Trying to render non string template or unrecognized template format, got 1917
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flexget/task.py", line 522, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/clients/transmission.py", line 369, in on_task_output
    options = self._make_torrent_options_dict(config, entry)
  File "/usr/local/lib/python3.6/dist-packages/flexget/plugins/clients/transmission.py", line 730, in _make_torrent_options_dict
    post['content_filename'] = entry.render(opt_dic['content_filename'])
  File "/usr/local/lib/python3.6/dist-packages/flexget/entry.py", line 309, in render
    % repr(template)
ValueError: Trying to render non string template or unrecognized template format, got 1917
```

**Comment by liiight** [comment]
The issue template is there for a reason, please do not ignore it or your issue will be ignored.
