### ISSUE TITLE
sftp_download fails, you have not specified a password or key

### ISSUE THREAD

**Issue by ksurl** [Flexget/Flexget#2692]
### Expected behaviour:

successful sftp connection with version flexget 3.1.60.

### Actual behaviour:

successfully connects for sftp_list to get new entries
fails to download file

### Steps to reproduce:
- Step 1: create ssh key: `ssh-keygen -t rsa -b 2048`
- Step 2: `flexget --loglevel debug execute sync`

#### Config:
```yaml
sync:
  sftp_list:
    host: '{? sftp.host ?}'
    port: '{? sftp.port ?}'
    username: '{? sftp.username ?}'
    private_key: '{? sftp.private_key ?}'
    private_key_pass: '{? sftp.private_key_pass ?}'
    dirs:
      - '{? remote.downloads ?}/'
    recursive: true
  regexp:
    accept:
      -  '.*\.mkv$'
  free_space:
    <<: *free_space
    space: 1500
  sftp_download:
    to: '{? local.downloads ?}/'
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-06-03 09:45:07 VERBOSE  sftp_client   sync      Connected to 176.223.141.52
2020-06-03 09:45:10 VERBOSE  details       sync      Produced 1 entries.
2020-06-03 09:45:10 VERBOSE  task          sync      ACCEPTED: `$FILE.mkv` by regexp plugin because regexp '.*\.mkv$' matched field 'title'
2020-06-03 09:45:10 WARNING  sftp_client   sync      Failed to connect to $IP_ADDRESS; waiting 15 seconds before retrying.
2020-06-03 09:45:50 VERBOSE  task          sync      REJECTED: `$FILE.mkv` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Failed to connect to $IP_ADDRESS (You have not specified a password or key.))
```
</details>

### Additional information:

- FlexGet version: 3.1.60
- Python version: 3.6.9
- Installation method: virtualenv
- Using daemon (yes/no): yes
- OS and version: Ubuntu 18.04.4
- Other info: I have tried using a key with and without a password, with and without specifying the password in the config. reverting to 3.1.51 works fine. pysftp version 0.2.8 (0.2.9 still fails to connect for me with nondescript error). remote host is set to accept pub key auth only. no password login. regular ssh login works fine

**Comment by ksurl** [comment]
re-ran the test on 3.1.57 which was the big sftp re-write. here is crash log output for the command:

`flexget --test execute --tasks sync`

username, ip and port changed for privacy.

#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-06-03 17:43:25 DEBUG    manager                       Figuring out config load paths
2020-06-03 17:43:25 DEBUG    manager                       Found config: /home/ksurl/.config/flexget/config.yml
2020-06-03 17:43:25 DEBUG    manager                       Config file /home/ksurl/.config/flexget/config.yml selected
2020-06-03 17:43:25 DEBUG    manager                       sys.defaultencoding: utf-8
2020-06-03 17:43:25 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2020-06-03 17:43:25 DEBUG    manager                       flexget detected io encoding: utf-8
2020-06-03 17:43:25 DEBUG    manager                       os.path.supports_unicode_filenames: False
2020-06-03 17:43:25 DEBUG    manager                       Figuring out config load paths
2020-06-03 17:43:25 DEBUG    manager                       Found config: /home/ksurl/.config/flexget/config.yml
2020-06-03 17:43:25 DEBUG    manager                       Config file /home/ksurl/.config/flexget/config.yml selected
2020-06-03 17:43:25 DEBUG    manager                       sys.defaultencoding: utf-8
2020-06-03 17:43:25 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2020-06-03 17:43:25 DEBUG    manager                       flexget detected io encoding: utf-8
2020-06-03 17:43:25 DEBUG    manager                       os.path.supports_unicode_filenames: False
2020-06-03 17:43:25 INFO     manager                       Test mode, creating a copy from database ...
2020-06-03 17:43:25 INFO     manager                       Test database created
2020-06-03 17:43:25 DEBUG    plugin                        Trying to load plugins from: ['/home/ksurl/.config/flexget/plugins', '/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/plugins']
2020-06-03 17:43:25 DEBUG    plugin                        Plugin `memusage` requires plugin `ext lib `guppy`` to load.
2020-06-03 17:43:26 DEBUG    plugin                        Trying to load components from: ['/home/ksurl/.config/flexget/components', '/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components']
2020-06-03 17:43:27 DEBUG    plugin                        Plugins took 1.28 seconds to load. 305 plugins in registry.
2020-06-03 17:43:27 DEBUG    manager                       Connecting to: sqlite:////home/ksurl/.config/flexget/test-config.sqlite
2020-06-03 17:43:27 DEBUG    manager                       config_name: config
2020-06-03 17:43:27 DEBUG    manager                       config_base: /home/ksurl/.config/flexget
2020-06-03 17:43:27 DEBUG    variables                     trying to load variables from file
2020-06-03 17:43:27 DEBUG    variables                     updating DB with variable file contents
2020-06-03 17:43:27 DEBUG    manager                       New config data loaded.
2020-06-03 17:43:27 DEBUG    schema                        updating flexget version 3.1.57 in db
2020-06-03 17:43:27 DEBUG    parsing                       setting default movie parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7f7b6511dd68>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7f7b6511ddd8>})
2020-06-03 17:43:27 DEBUG    parsing                       setting default series parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7f7b6511dd68>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7f7b6511ddd8>})
2020-06-03 17:43:27 DEBUG    cron_env                      Encoding utf-8 stored
2020-06-03 17:43:27 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'utf-8'
2020-06-03 17:43:27 DEBUG    task_queue                    task queue shutdown requested
2020-06-03 17:43:27 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2020-06-03 17:43:27 DEBUG    task          sync-test       executing sync-test
2020-06-03 17:43:27 DEBUG    template      sync-test       Merging template global into task sync-test
2020-06-03 17:43:27 DEBUG    remember_rej  sync-test       Task config has changed since last run, purging remembered entries.
2020-06-03 17:43:27 DEBUG    sftp_client   sync-test       Connecting to $IP_ADDRESS
2020-06-03 17:43:27 DEBUG    sftp_client   sync-test       Caught exception: No hostkey for host $IP_ADDRESS found.
2020-06-03 17:43:27 WARNING  sftp_client   sync-test       Failed to connect to $IP_ADDRESS; waiting 15 seconds before retrying.
2020-06-03 17:43:42 DEBUG    sftp_client   sync-test       Caught exception: No hostkey for host $IP_ADDRESS found.
2020-06-03 17:43:42 WARNING  sftp_client   sync-test       Failed to connect to $IP_ADDRESS; waiting 20 seconds before retrying.
2020-06-03 17:44:02 CRITICAL task          sync-test       BUG: Unhandled error in plugin sftp_list: No hostkey for host $IP_ADDRESS found.
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7b6e5c18c8>
    └ <Thread(task_queue, started daemon 140167943489280)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f7b6e5c16a8>
    └ <Thread(task_queue, started daemon 140167943489280)>
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140167943489280)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140167943489280)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f7b650b5780>>
    └ <Thread(task_queue, started daemon 140167943489280)>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f7b69f3a950>
    │    └ <flexget.task.Task object at 0x7f7b64865978>
    └ <flexget.task_queue.TaskQueue object at 0x7f7b650b5780>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/task.py", line 80, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f7b64865978>
           └ <function Task.execute at 0x7f7b69f3a8c8>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/task.py", line 697, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f7b69f3a840>
    └ <flexget.task.Task object at 0x7f7b64865978>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/task.py", line 663, in _execute
    self.__run_task_phase(phase)
    │                     └ 'input'
    └ <flexget.task.Task object at 0x7f7b64865978>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/task.py", line 489, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f7b64865978>, {'host': '$IP_ADDRESS', 'port': 2222, 'username': 'ksurl', 'private_key': '...
               │                 │       └ 'input'
               │                 └ <PluginInfo(name=sftp_list)>
               └ <flexget.task.Task object at 0x7f7b64865978>
> File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/task.py", line 522, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7f7b64865978>, {'host': '$IP_ADDRESS', 'port': 2222, 'username': 'ksurl', 'private_key': '...
             └ <Event(name=plugin.sftp_list.input,func=on_task_input,priority=128)>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7f7b64865978>, {'host': '$IP_ADDRESS', 'port': 2222, 'username': 'ksurl', 'private_key': '...
           │    └ <bound method SftpList.on_task_input of <class 'flexget.components.ftp.sftp.SftpList'>>
           └ <Event(name=plugin.sftp_list.input,func=on_task_input,priority=128)>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp.py", line 117, in on_task_input
    sftp: SftpClient = sftp_connect(sftp_config, socket_timeout_sec, connection_tries)
                       │            │            │                   └ 3
                       │            │            └ 15
                       │            └ SftpConfig(host='$IP_ADDRESS', port=2222, username='ksurl', password=None, private_key='/home/ksurl/.ssh/flexget-rsa', pri...
                       └ <function sftp_connect at 0x7f7b653c7620>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp.py", line 363, in sftp_connect
    connection_tries=connection_tries,
                     └ 3
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp_client.py", line 56, in __init__
    self._sftp: 'pysftp.Connection' = self._connect(connection_tries)
    │                                 │    │        └ 3
    │                                 │    └ <function SftpClient._connect at 0x7f7b653de268>
    │                                 └ <flexget.components.ftp.sftp_client.SftpClient object at 0x7f7b647de780>
    └ <flexget.components.ftp.sftp_client.SftpClient object at 0x7f7b647de780>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp_client.py", line 242, in _connect
    raise e
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp_client.py", line 236, in _connect
    private_key_pass=self.private_key_pass,
                     │    └ 'fl847libp'
                     └ <flexget.components.ftp.sftp_client.SftpClient object at 0x7f7b647de780>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/pysftp/__init__.py", line 132, in __init__
    self._tconnect['hostkey'] = self._cnopts.get_hostkey(host)
    │    │                      │    │       │           └ '$IP_ADDRESS'
    │    │                      │    │       └ <function CnOpts.get_hostkey at 0x7f7b65655d90>
    │    │                      │    └ <pysftp.CnOpts object at 0x7f7b647fd940>
    │    │                      └ <pysftp.Connection object at 0x7f7b6a6ba2b0>
    │    └ {'username': 'ksurl', 'password': None, 'hostkey': None, 'pkey': None}
    └ <pysftp.Connection object at 0x7f7b6a6ba2b0>
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/pysftp/__init__.py", line 71, in get_hostkey
    raise SSHException("No hostkey for host %s found." % host)
          │                                              └ '$IP_ADDRESS'
          └ <class 'paramiko.ssh_exception.SSHException'>

paramiko.ssh_exception.SSHException: No hostkey for host $IP_ADDRESS found.
Traceback (most recent call last):
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/task.py", line 522, in __run_plugin
    result = method(*args, **kwargs)
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp.py", line 117, in on_task_input
    sftp: SftpClient = sftp_connect(sftp_config, socket_timeout_sec, connection_tries)
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp.py", line 363, in sftp_connect
    connection_tries=connection_tries,
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp_client.py", line 56, in __init__
    self._sftp: 'pysftp.Connection' = self._connect(connection_tries)
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp_client.py", line 242, in _connect
    raise e
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/flexget/components/ftp/sftp_client.py", line 236, in _connect
    private_key_pass=self.private_key_pass,
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/pysftp/__init__.py", line 132, in __init__
    self._tconnect['hostkey'] = self._cnopts.get_hostkey(host)
  File "/home/ksurl/.venv/flexget/lib/python3.6/site-packages/pysftp/__init__.py", line 71, in get_hostkey
    raise SSHException("No hostkey for host %s found." % host)
paramiko.ssh_exception.SSHException: No hostkey for host $IP_ADDRESS found.
```

**Comment by ksurl** [comment]
just did a clean install of ubuntu 20.04 with python 3.8.2, flexget 3.1.61, pysftp 0.2.8 and it still has the fail on sftp_download only (you have not specified a password or key). 

it is just really odd it does not use the same config as from sftp_list. since that phase succeeded in accepting entries

**Comment by ianstalk** [comment]
Actually you're right; this is a regression. 😩 I'll have a fix up shortly.

**Comment by ksurl** [comment]
confirmed it works now on 3.1.64 with the new fix.
