### ISSUE TITLE
From_Transmission removal failing

### ISSUE THREAD

**Issue by specie77** [Flexget/Flexget#2707]
### Expected behaviour:
Remove old torrents from transmission.

### Actual behaviour:
Flexget log shows critical error with Python error statements, torrent not removed from transmission.

### Steps to reproduce:
flexget --test execute --tasks "Trans_Clean_Up" --dump

#### Config:
C:\Users\User>flexget execute --task "Trans_Clean_Up" --dump-config
2020-07-02 10:01:22 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
--- config from task: Trans_Clean_Up
disable:
  - seen
  - seen_info_hash
from_transmission:
  host: ****
  password: ****
  port: ****
  username: ****
if:
  - transmission_progress == 100: accept
transmission:
  action: remove
  host: ****
  password: ****
  port: ****
  username: ****
---
  
#### Log:
[flexget.log](https://github.com/Flexget/Flexget/files/4864846/flexget.log)

Attached and below:

<details>
 <summary>(click to expand)</summary>

```
2020-07-02 10:06:20 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2020-07-02 10:06:22 CRITICAL task          Trans_Clean_Up  BUG: Unhandled error in plugin from_transmission: [Errno 22] Invalid argument
Traceback (most recent call last):

  File "c:\users\user\appdata\local\programs\python\python36\lib\threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000000EB8F806D90>
    └ <Thread(task_queue, started daemon 4720)>

  File "c:\users\user\appdata\local\programs\python\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000000EB8F806B70>
    └ <Thread(task_queue, started daemon 4720)>

  File "c:\users\user\appdata\local\programs\python\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 4720)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 4720)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x000000EB94B7EF98>>
    └ <Thread(task_queue, started daemon 4720)>

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x000000EB91EEF598>
    │    └ <flexget.task.Task object at 0x000000EB95D730B8>
    └ <flexget.task_queue.TaskQueue object at 0x000000EB94B7EF98>

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\task.py", line 80, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x000000EB95D730B8>
           └ <function Task.execute at 0x000000EB91EEF510>

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\task.py", line 710, in execute
    self._execute()
    │    └ <function Task._execute at 0x000000EB91EEF488>
    └ <flexget.task.Task object at 0x000000EB95D730B8>

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\task.py", line 676, in _execute
    self.__run_task_phase(phase)
    │                     └ 'input'
    └ <flexget.task.Task object at 0x000000EB95D730B8>

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\task.py", line 502, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x000000EB95D730B8>, {'host': '****', 'port': ****, 'username': ...
               │                 │       └ 'input'
               │                 └ <PluginInfo(name=from_transmission)>
               └ <flexget.task.Task object at 0x000000EB95D730B8>

> File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\task.py", line 535, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x000000EB95D730B8>, {'host': '****', 'port': ****, 'username': ...
             └ <Event(name=plugin.from_transmission.input,func=on_task_input,priority=128)>

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\event.py", line 22, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x000000EB95D730B8>, {'host': '****', 'port': ****, 'username': ...
           │    └ <bound method PluginTransmissionInput.on_task_input of <flexget.plugins.clients.transmission.PluginTransmissionInput object a...
           └ <Event(name=plugin.from_transmission.input,func=on_task_input,priority=128)>

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\plugins\clients\transmission.py", line 196, in on_task_input
    seed_ratio_ok, idle_limit_ok = self.check_seed_limits(torrent, session)
    │                              │    │                 │        └ <transmissionrpc.session.Session object at 0x000000EB9619F358>
    │                              │    │                 └ <Torrent 17>
    │                              │    └ <function TransmissionBase.check_seed_limits at 0x000000EB93089620>
    │                              └ <flexget.plugins.clients.transmission.PluginTransmissionInput object at 0x000000EB94A17B70>
    └ True

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\flexget\plugins\clients\transmission.py", line 118, in check_seed_limits
    torrent.date_active + timedelta(minutes=session.idle_seeding_limit)
    │       │             │                 └ <transmissionrpc.session.Session object at 0x000000EB9619F358>
    │       │             └ <class 'datetime.timedelta'>
    │       └ <property object at 0x000000EB93082318>
    └ <Torrent 17>

  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\transmissionrpc\torrent.py", line 215, in date_active
    return datetime.datetime.fromtimestamp(self._fields['activityDate'].value)
           │        │        │             │    └ {'activityDate': Field(value=0, dirty=False), 'addedDate': Field(value=1591069664, dirty=False), 'bandwidthPriority': Field(v...
           │        │        │             └ <Torrent 17>
           │        │        └ <method 'fromtimestamp' of 'datetime.datetime' objects>
           │        └ <class 'datetime.datetime'>
           └ <module 'datetime' from 'c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\datetime.py'>

OSError: [Errno 22] Invalid argument
2020-07-02 10:06:22 CRITICAL manager       Trans_Clean_Up  An unexpected crash has occurred. Writing crash report to C:\Users\user\flexget\crash_report.2020.07.02.100622455469.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.66
2020-07-02 10:06:22 WARNING  task          Trans_Clean_Up  Aborting task (plugin: from_transmission)

```
</details>

### Additional information:

- FlexGet version: 3.1.66
- Python version: 3.6.0
- Installation method: pip
- Using daemon (yes/no): Error occurs with and without daemon
- OS and version: Windows Server 2012 R2 Standard
- Link to crash log: 
[crash_report.2020.07.02.100622455469.log](https://github.com/Flexget/Flexget/files/4864838/crash_report.2020.07.02.100622455469.log)

**Comment by specie77** [comment]
Migrated to new host, installed transmissionrpc, seems to have resolved the problem.
