### ISSUE TITLE
BUG: Unhandled error in plugin convert_magnet: 'dict' object has no attribute 'url'

### ISSUE THREAD

**Issue by kauffman214** [Flexget/Flexget#2848]
### Expected behaviour:
Conversion of magnet link not occurring.  

### Actual behaviour:
No conversion.  BUG alert thrown.

### Steps to reproduce:
convert_magnet: true

> flexget execute

#### Log:
2021-02-11 08:45:55 CRITICAL task          showrss-tv      BUG: Unhandled error in plugin convert_magnet: 'dict' object has no attribute 'url'
AttributeError: 'dict' object has no attribute 'url'
2021-02-11 08:45:55 CRITICAL manager       showrss-tv      An unexpected crash has occurred. Writing crash report to /etc/flexget/crash_report.2021.02.11.084555350759.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.102

### Additional information:

- FlexGet version: 3.1.102
- Python version: 3.6.9
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Description:	Ubuntu 18.04.5 LTS

**Comment by bewell** [comment]
I'm getting the same error. Here's more detailed error log:

```
2021-02-21 20:00:29 CRITICAL task          imdb_movies     BUG: Unhandled error in plugin convert_magnet: 'dict' object has no attribute 'url'
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6aabcb4160>
    └ <Thread(task_queue, started daemon 140096041178880)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6aabcb1e50>
    └ <Thread(task_queue, started daemon 140096041178880)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140096041178880)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140096041178880)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f6aa7191250>>
    └ <Thread(task_queue, started daemon 140096041178880)>
  File "/home/user/.local/lib/python3.8/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f6aa9bb8790>
    │    └ <flexget.task.Task object at 0x7f6aa6cb7be0>
    └ <flexget.task_queue.TaskQueue object at 0x7f6aa7191250>
  File "/home/user/.local/lib/python3.8/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f6aa6cb7be0>
           └ <function Task.execute at 0x7f6aa9bb8700>
  File "/home/user/.local/lib/python3.8/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f6aa9bb8670>
    └ <flexget.task.Task object at 0x7f6aa6cb7be0>
  File "/home/user/.local/lib/python3.8/site-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
    │                     └ 'download'
    └ <flexget.task.Task object at 0x7f6aa6cb7be0>
  File "/home/user/.local/lib/python3.8/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f6aa6cb7be0>, True)
               │                 │       └ 'download'
               │                 └ <PluginInfo(name=convert_magnet)>
               └ <flexget.task.Task object at 0x7f6aa6cb7be0>
> File "/home/user/.local/lib/python3.8/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7f6aa6cb7be0>, True)
             └ <Event(name=plugin.convert_magnet.download,func=on_task_download,priority=130)>
  File "/home/user/.local/lib/python3.8/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7f6aa6cb7be0>, True)
           │    └ <bound method ConvertMagnet.on_task_download of <flexget.components.bittorrent.convert_magnet.ConvertMagnet object at 0x7f6aa...
           └ <Event(name=plugin.convert_magnet.download,func=on_task_download,priority=130)>
  File "/home/user/.local/lib/python3.8/site-packages/flexget/components/bittorrent/convert_magnet.py", line 99, in on_task_download
    torrent_file = self.magnet_to_torrent(entry['url'], converted_path, timeout)
                   │    │                 │             │               └ 30.0
                   │    │                 │             └ '/home/user/.flexget/converted'
                   │    │                 └ <Entry(title=No.Safe.Spaces.2019.1080p.AMZN.WEBRip.DDP5.1.x264-iKA,state=accepted)>
                   │    └ <function ConvertMagnet.magnet_to_torrent at 0x7f6aa8149ca0>
                   └ <flexget.components.bittorrent.convert_magnet.ConvertMagnet object at 0x7f6aa71e2fa0>
  File "/home/user/.local/lib/python3.8/site-packages/flexget/components/bittorrent/convert_magnet.py", line 41, in magnet_to_torrent
    params.url = magnet_uri
    │            └ 'magnet:?xt=urn:btih:cda6b38a388db7c1ff30344109bf56ac96355c99&dn=No.Safe.Spaces.2019.1080p.AMZN.WEBRip.DDP5.1.x264-iKA&tr=htt...
    └ {'ti': None, 'trackers': ['http://tracker.trackerfix.com:80/announce', 'udp://9.rarbg.me:2720', 'udp://9.rarbg.to:2880'], 'dh...

AttributeError: 'dict' object has no attribute 'url'
```

**Comment by Diederikjh** [comment]
I think this might be caused by the change #2797 (via #2424).  The failure seems to be at line 99 of convert_magnet.py where it is expecting to lookup a dict entry (`params['url']`) but the referenced change sets the url as `params.url `.  

Changing line 41 to `params['url'] = magnet_uri` seems to fix it.

**Comment by ray73864** [comment]
Can confirm that this has fixed my issue too.

Changed line 41 in /usr/local/lib/python3.7/dist-packages/flexget/components/bittorrent/convert_magnet.py
Then shutdown the existing flexget daemon and started it up again, then ran 'flexget execute'.

**Comment by wooltar** [comment]
could you please merge the PR. We have the issue in the last version of fleget
`2021-06-05 12:56:01 CRITICAL task          showrss         BUG: Unhandled error in plugin convert_magnet: 'dict' object has no attribute 'url'
Traceback (most recent call last):

  File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7fd7b3689c20>
    -> <Thread(task_queue, started daemon 140564296656640)>
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x7fd7b36899e0>
    -> <Thread(task_queue, started daemon 140564296656640)>
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(task_queue, started daemon 140564296656640)>
    |    |        |    -> ()
    |    |        -> <Thread(task_queue, started daemon 140564296656640)>
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fd7ad29c750>>
    -> <Thread(task_queue, started daemon 140564296656640)>
  File "/home/kike/.local/lib/python3.7/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    |    |            -> <function Task.execute at 0x7fd7b0351680>
    |    -> <flexget.task.Task object at 0x7fd7acf943d0>
    -> <flexget.task_queue.TaskQueue object at 0x7fd7ad29c750>
  File "/home/kike/.local/lib/python3.7/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           |    |      |       -> {}
           |    |      -> ()
           |    -> <flexget.task.Task object at 0x7fd7acf943d0>
           -> <function Task.execute at 0x7fd7b03515f0>
  File "/home/kike/.local/lib/python3.7/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    |    -> <function Task._execute at 0x7fd7b0351560>
    -> <flexget.task.Task object at 0x7fd7acf943d0>
  File "/home/kike/.local/lib/python3.7/site-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
    |                     -> 'download'
    -> <flexget.task.Task object at 0x7fd7acf943d0>
  File "/home/kike/.local/lib/python3.7/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               |                 |       |      -> (<flexget.task.Task object at 0x7fd7acf943d0>, {'timeout': '60 seconds', 'force': False})
               |                 |       -> 'download'
               |                 -> <PluginInfo(name=convert_magnet)>
               -> <flexget.task.Task object at 0x7fd7acf943d0>
> File "/home/kike/.local/lib/python3.7/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             |       |       -> {}
             |       -> (<flexget.task.Task object at 0x7fd7acf943d0>, {'timeout': '60 seconds', 'force': False})
             -> <Event(name=plugin.convert_magnet.download,func=on_task_download,priority=130)>
  File "/home/kike/.local/lib/python3.7/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.task.Task object at 0x7fd7acf943d0>, {'timeout': '60 seconds', 'force': False})
           |    -> <bound method ConvertMagnet.on_task_download of <flexget.components.bittorrent.convert_magnet.ConvertMagnet object at 0x7fd7a...
           -> <Event(name=plugin.convert_magnet.download,func=on_task_download,priority=130)>
  File "/home/kike/.local/lib/python3.7/site-packages/flexget/components/bittorrent/convert_magnet.py", line 99, in on_task_download
    torrent_file = self.magnet_to_torrent(entry['url'], converted_path, timeout)
                   |    |                 |             |               -> 60.0
                   |    |                 |             -> '/home/kike/.flexget/converted'
                   |    |                 -> <Entry(title=Greys Anatomy S17E17 1080p WEB H264 STRONTiUM,state=accepted)>
                   |    -> <function ConvertMagnet.magnet_to_torrent at 0x7fd7adba1170>
                   -> <flexget.components.bittorrent.convert_magnet.ConvertMagnet object at 0x7fd7ad36c150>
  File "/home/kike/.local/lib/python3.7/site-packages/flexget/components/bittorrent/convert_magnet.py", line 41, in magnet_to_torrent
    params.url = magnet_uri
    |            -> 'magnet:?xt=urn:btih:FC1EC04357E69CBEF2EC5CC290A09DD563482415&dn=Greys+Anatomy+S17E17+1080p+WEB+H264+STRONTiUM&tr=udp%3A%2F%2...
    -> {'ti': None, 'trackers': ['udp://tracker.coppersurfer.tk:6969/announce', 'udp://tracker.leechers-paradise.org:6969/announce',...

AttributeError: 'dict' object has no attribute 'url'`
