### ISSUE TITLE
season_packs doesn't reject episodes if in the same feed and with target and timeframe

### ISSUE THREAD

**Issue by soloam** [Flexget/Flexget#2849]
### Expected behaviour:

According to the documentation, season_packs: yes, should accept seasons packs if no other episode is downloaded, and reject episodes if the season pack is downloaded.

### Actual behaviour:

This works if the season pack and the episode are not both in the same input feed and not with timeframe and target.

If both appear at the same time, **and the series contains timeframe and target**, they are both accepted. Flexget should only accept one of them.

### Steps to reproduce:
- Step 1: Test That Works with normal series configuration
`      flexget --debug execute --task "xTV_Test_season_pack_1" --inject "Lost S01 720p hdtv h264" --inject "Lost S01E01 720 hdtv h264"`
    
```
2021-02-11 16:49:22 DEBUG    series        xTV_Test_season_pack_1 current: <Season(id=54,identifier=S01,season=1,completed=False)>
2021-02-11 16:49:22 VERBOSE  task          xTV_Test_season_pack_1 ACCEPTED: `Lost S01 720p hdtv h264` by series plugin because matches quality
2021-02-11 16:49:22 DEBUG    series        xTV_Test_season_pack_1 adding season number `1` to accepted seasons for this task
2021-02-11 16:49:22 DEBUG    series        xTV_Test_season_pack_1 start with entities: ['Lost S01E01 720 hdtv h264']
2021-02-11 16:49:22 VERBOSE  task          xTV_Test_season_pack_1 REJECTED: `Lost S01E01 720 hdtv h264` by series plugin because already accepted season pack for season `1` in this task

```

- Step 2: Forget the Season
  flexget series forget "Lost (2004)"

- Step 3: Test with timeframe and target

`      flexget --debug execute --task "xTV_Test_season_pack_2" --inject "Lost S01 720p hdtv h264" --inject "Lost S01E01 720 hdtv h264"`

```
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 Accepted by series. `Lost S01 720p hdtv h264` meets quality requirement `720p webrip+ h264+`.
2021-02-11 16:50:50 VERBOSE  task          xTV_Test_season_pack_2 ACCEPTED: `Lost S01 720p hdtv h264` by series plugin because target quality
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 start with entities: ['Lost S01E01 720 hdtv h264']
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 current entities: ['Lost S01E01 720 hdtv h264']
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 quality req: 720p|1080p webrip+
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 -------------------- process_propers -->
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 propers - downloaded qualities: {}
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 continuing w. entities: ['Lost S01E01 720 hdtv h264']
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 best entity is: `Lost S01E01 720 hdtv h264`
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 -------------------- tracking -->
2021-02-11 16:50:50 DEBUG    series.db     xTV_Test_season_pack_2 no episodes found for series `Lost (2004)` with parameters season: None, downloaded: True
2021-02-11 16:50:50 DEBUG    series.db     xTV_Test_season_pack_2 no season packs found for series `Lost (2004)` with parameters season: None, downloaded: True
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 latest download: None
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 current: <Episode(id=6159,identifier=S01E01,season=1,number=1)>
2021-02-11 16:50:50 DEBUG    series        xTV_Test_season_pack_2 Accepted by series. `Lost S01E01 720 hdtv h264` meets quality requirement `720p webrip+ h264+`.
2021-02-11 16:50:50 VERBOSE  task          xTV_Test_season_pack_2 ACCEPTED: `Lost S01E01 720 hdtv h264` by series plugin because target quality
```

#### Config:
```yaml
  xTV_Test_season_pack_1:
    disable:
      - remember_rejected
      - seen
      - retry_failed
      - seen_info_hash
    series:
      - Lost (2004):
          identified_by: ep
          quality: 720p|1080p webrip+     
          season_packs: true
    thetvdb_lookup: true
    trakt_lookup: true



  xTV_Test_season_pack_2:
    disable:
      - remember_rejected
      - seen
      - retry_failed
      - seen_info_hash
    series:
      - Lost (2004):
          identified_by: ep
          quality: 720p|1080p webrip+
          timeframe: 4 hours
          target: 720p webrip+ h264+      
          season_packs: true
    thetvdb_lookup: true
    trakt_lookup: true
```
</details>

### Additional information:

- FlexGet version: 3.1.102
- Python version: Python 3.7.3
- Installation method: VENV
- Using daemon (yes/no): yes (but tested also without daemon)
- OS and version: Debian 10

**Comment by liiight** [comment]
Nice catch on this, I see the root cause. Accepting the entity using the timeframe accept the entry at a separate code path, one that doesn't add its season to accepted season list.

**Comment by soloam** [comment]
Thank You for the PR! When it's merged I'll check it out!

**Comment by soloam** [comment]
I tried the push request and got an error

```
2021-02-11 22:54:48 CRITICAL task          xTV_Test_season_pack_2 BUG: Unhandled error in plugin series: _exclude_season_on_accept() got multiple values for argument 'series_entity'
Traceback (most recent call last):

  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7fea69b0ce18>
    -> <Thread(task_queue, started daemon 140644677314304)>
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x7fea69b0cbf8>
    -> <Thread(task_queue, started daemon 140644677314304)>
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(task_queue, started daemon 140644677314304)>
    |    |        |    -> ()
    |    |        -> <Thread(task_queue, started daemon 140644677314304)>
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fea64965080>>
    -> <Thread(task_queue, started daemon 140644677314304)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    |    |            -> <function Task.execute at 0x7fea67d610d0>
    |    -> <flexget.task.Task object at 0x7fea64795a20>
    -> <flexget.task_queue.TaskQueue object at 0x7fea64965080>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           |    |      |       -> {}
           |    |      -> ()
           |    -> <flexget.task.Task object at 0x7fea64795a20>
           -> <function Task.execute at 0x7fea67d61048>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    |    -> <function Task._execute at 0x7fea67d60f28>
    -> <flexget.task.Task object at 0x7fea64795a20>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
    |                     -> 'filter'
    -> <flexget.task.Task object at 0x7fea64795a20>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               |                 |       |      -> (<flexget.task.Task object at 0x7fea64795a20>, [{'Lost (2004)': {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'tim...
               |                 |       -> 'filter'
               |                 -> <PluginInfo(name=series)>
               -> <flexget.task.Task object at 0x7fea64795a20>
> File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             |       |       -> {}
             |       -> (<flexget.task.Task object at 0x7fea64795a20>, [{'Lost (2004)': {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'tim...
             -> <Event(name=plugin.series.filter,func=on_task_filter,priority=128)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.task.Task object at 0x7fea64795a20>, [{'Lost (2004)': {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'tim...
           |    -> <bound method FilterSeries.on_task_filter of <flexget.components.series.series.FilterSeries object at 0x7fea64a541d0>>
           -> <Event(name=plugin.series.filter,func=on_task_filter,priority=128)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/components/series/series.py", line 562, in on_task_filter
    self.process_series(task, series_entries, series_config)
    |    |              |     |               -> {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'timeframe': '4 hours', 'target': '720p webrip+ h264+', 'season_pack...
    |    |              |     -> <unprintable dict object>
    |    |              -> <flexget.task.Task object at 0x7fea64795a20>
    |    -> <function FilterSeries.process_series at 0x7fea64cb8a60>
    -> <flexget.components.series.series.FilterSeries object at 0x7fea64a541d0>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/components/series/series.py", line 782, in process_series
    if self.process_timeframe_target(config, entries, downloaded):
       |    |                        |       |        -> []
       |    |                        |       -> [<Entry(title=Lost S01 720p hdtv h264,state=accepted)>]
       |    |                        -> {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'timeframe': '4 hours', 'target': '720p webrip+ h264+', 'season_pack...
       |    -> <function FilterSeries.process_timeframe_target at 0x7fea64cb8b70>
       -> <flexget.components.series.series.FilterSeries object at 0x7fea64a541d0>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/components/series/series.py", line 876, in process_timeframe_target
    entry.accept('target quality')
    |     -> <function Entry.accept at 0x7fea67f467b8>
    -> <Entry(title=Lost S01 720p hdtv h264,state=accepted)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/entry.py", line 177, in accept
    self.run_hooks('accept', reason=reason, **kwargs)
    |    |                          |         -> {}
    |    |                          -> 'target quality'
    |    -> <function Entry.run_hooks at 0x7fea67f46488>
    -> <Entry(title=Lost S01 720p hdtv h264,state=accepted)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/entry.py", line 118, in run_hooks
    func(self, **kwargs)
    |    |       -> {'reason': 'target quality'}
    |    -> <Entry(title=Lost S01 720p hdtv h264,state=accepted)>
    -> <unprintable partial object>

TypeError: _exclude_season_on_accept() got multiple values for argument 'series_entity'
2021-02-11 22:54:48 CRITICAL manager       xTV_Test_season_pack_2 An unexpected crash has occurred. Writing crash report to /home/downloader/.config/flexget/crash_report.2021.02.11.225448995537.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.89
2021-02-11 22:54:48 DEBUG    manager       xTV_Test_season_pack_2 Traceback:
Traceback (most recent call last):

  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7fea69b0ce18>
    -> <Thread(task_queue, started daemon 140644677314304)>
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x7fea69b0cbf8>
    -> <Thread(task_queue, started daemon 140644677314304)>
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(task_queue, started daemon 140644677314304)>
    |    |        |    -> ()
    |    |        -> <Thread(task_queue, started daemon 140644677314304)>
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fea64965080>>
    -> <Thread(task_queue, started daemon 140644677314304)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    |    |            -> <function Task.execute at 0x7fea67d610d0>
    |    -> <flexget.task.Task object at 0x7fea64795a20>
    -> <flexget.task_queue.TaskQueue object at 0x7fea64965080>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           |    |      |       -> {}
           |    |      -> ()
           |    -> <flexget.task.Task object at 0x7fea64795a20>
           -> <function Task.execute at 0x7fea67d61048>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    |    -> <function Task._execute at 0x7fea67d60f28>
    -> <flexget.task.Task object at 0x7fea64795a20>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
    |                     -> 'filter'
    -> <flexget.task.Task object at 0x7fea64795a20>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               |                 |       |      -> (<flexget.task.Task object at 0x7fea64795a20>, [{'Lost (2004)': {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'tim...
               |                 |       -> 'filter'
               |                 -> <PluginInfo(name=series)>
               -> <flexget.task.Task object at 0x7fea64795a20>
> File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             |       |       -> {}
             |       -> (<flexget.task.Task object at 0x7fea64795a20>, [{'Lost (2004)': {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'tim...
             -> <Event(name=plugin.series.filter,func=on_task_filter,priority=128)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.task.Task object at 0x7fea64795a20>, [{'Lost (2004)': {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'tim...
           |    -> <bound method FilterSeries.on_task_filter of <flexget.components.series.series.FilterSeries object at 0x7fea64a541d0>>
           -> <Event(name=plugin.series.filter,func=on_task_filter,priority=128)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/components/series/series.py", line 562, in on_task_filter
    self.process_series(task, series_entries, series_config)
    |    |              |     |               -> {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'timeframe': '4 hours', 'target': '720p webrip+ h264+', 'season_pack...
    |    |              |     -> <unprintable dict object>
    |    |              -> <flexget.task.Task object at 0x7fea64795a20>
    |    -> <function FilterSeries.process_series at 0x7fea64cb8a60>
    -> <flexget.components.series.series.FilterSeries object at 0x7fea64a541d0>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/components/series/series.py", line 782, in process_series
    if self.process_timeframe_target(config, entries, downloaded):
       |    |                        |       |        -> []
       |    |                        |       -> [<Entry(title=Lost S01 720p hdtv h264,state=accepted)>]
       |    |                        -> {'identified_by': 'ep', 'quality': '720p|1080p webrip+', 'timeframe': '4 hours', 'target': '720p webrip+ h264+', 'season_pack...
       |    -> <function FilterSeries.process_timeframe_target at 0x7fea64cb8b70>
       -> <flexget.components.series.series.FilterSeries object at 0x7fea64a541d0>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/components/series/series.py", line 876, in process_timeframe_target
    entry.accept('target quality')
    |     -> <function Entry.accept at 0x7fea67f467b8>
    -> <Entry(title=Lost S01 720p hdtv h264,state=accepted)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/entry.py", line 177, in accept
    self.run_hooks('accept', reason=reason, **kwargs)
    |    |                          |         -> {}
    |    |                          -> 'target quality'
    |    -> <function Entry.run_hooks at 0x7fea67f46488>
    -> <Entry(title=Lost S01 720p hdtv h264,state=accepted)>
  File "/home/downloader/flexget/lib/python3.7/site-packages/flexget/entry.py", line 118, in run_hooks
    func(self, **kwargs)
    |    |       -> {'reason': 'target quality'}
    |    -> <Entry(title=Lost S01 720p hdtv h264,state=accepted)>
    -> <unprintable partial object>

TypeError: _exclude_season_on_accept() got multiple values for argument 'series_entity'

```

**Comment by soloam** [comment]
Probably to soon and still not completed :)

**Comment by soloam** [comment]
Thank you for the time spend on this!
