### ISSUE TITLE
irc bot fails to connect

### ISSUE THREAD

**Issue by dialectichex** [Flexget/Flexget#2884]
### Expected behaviour:
flexget bot connects to irc channels

### Actual behaviour:
irc channels are recognised as alive, bot continuously attempts to connect without success giving: 
> AttributeError: 'HTMLParser' object has no attribute 'unescape' 
### Steps to reproduce:
- Step 1: ...
start the flexget service
#### Config:

http://ix.io/2Tfb  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2021-03-17 18:44:36 INFO     irc_bot                       Connecting to ('irc.passthepopcorn.me', 7000)
2021-03-17 18:44:37 INFO     irc_bot                       Connected to server irc.passthepopcorn.me
2021-03-17 18:44:37 ERROR    irc_bot                       Unknown error occurred.
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7fee33081280>
    -> <Thread(PassThePopcorn, started daemon 140660841637440)>
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x7fee3307df70>
    -> <Thread(PassThePopcorn, started daemon 140660841637440)>
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(PassThePopcorn, started daemon 140660841637440)>
    |    |        |    -> ()
    |    |        -> <Thread(PassThePopcorn, started daemon 140660841637440)>
    |    -> <bound method SimpleIRCBot.start of <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>>
    -> <Thread(PassThePopcorn, started daemon 140660841637440)>
  File "/home/user/virtualenv/flexget/lib/python3.9/site-packages/irc_bot/simple_irc_bot.py", line 406, in start
    asyncore.poll(timeout=10, map={self.socket: self})
    |        |                     |    |       -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
    |        |                     |    -> <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.2>
    |        |                     -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
    |        -> <function poll at 0x7fee2df6e280>
    -> <module 'asyncore' from '/usr/lib/python3.9/asyncore.py'>
  File "/usr/lib/python3.9/asyncore.py", line 150, in poll
    read(obj)
    |    -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
    -> <function read at 0x7fee2df6e040>
> File "/usr/lib/python3.9/asyncore.py", line 83, in read
    obj.handle_read_event()
    |   -> <function dispatcher.handle_read_event at 0x7fee2df6eee0>
    -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
  File "/usr/lib/python3.9/asyncore.py", line 420, in handle_read_event
    self.handle_read()
    |    -> <function SimpleIRCBot.handle_read at 0x7fee2df884c0>
    -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
  File "/home/user/virtualenv/flexget/lib/python3.9/site-packages/irc_bot/simple_irc_bot.py", line 129, in handle_read
    asynchat.async_chat.handle_read(self)
    |        |          |           -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
    |        |          -> <function async_chat.handle_read at 0x7fee2df70280>
    |        -> <class 'asynchat.async_chat'>
    -> <module 'asynchat' from '/usr/lib/python3.9/asynchat.py'>
  File "/usr/lib/python3.9/asynchat.py", line 167, in handle_read
    self.collect_incoming_data(self.ac_in_buffer[:index])
    |    |                     |    |             -> 71
    |    |                     |    -> b':Persona.passthepopcorn.me NOTICE Auth :*** Looking up your hostname...\r\n:Persona.passthepopcorn.me NOTICE Aut>
    |    |                     -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
    |    -> <function SimpleIRCBot.collect_incoming_data at 0x7fee2df88af0>
    -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
  File "/home/user/virtualenv/flexget/lib/python3.9/site-packages/irc_bot/simple_irc_bot.py", line 227, in collect_incoming_data
    self.buffer += decode_html(strip_irc_colors(strip_invisible(data)))
    |    |         |           |                |               -> ':Persona.passthepopcorn.me NOTICE Auth :*** Looking up your hostname...'
    |    |         |           |                -> <function strip_invisible at 0x7fee2df81e50>
    |    |         |           -> <function strip_irc_colors at 0x7fee2df81dc0>
    |    |         -> <function decode_html at 0x7fee2df81ee0>
    |    -> ''
    -> <flexget.components.irc.irc.IRCConnection connected at 0x7fee2ca60610>
  File "/home/user/virtualenv/flexget/lib/python3.9/site-packages/irc_bot/utils.py", line 48, in decode_html
    return h.unescape(data)
           |          -> ':Persona.passthepopcorn.me NOTICE Auth :*** Looking up your hostname...'
           -> <html.parser.HTMLParser object at 0x7fee2dfe9550>
AttributeError: 'HTMLParser' object has no attribute 'unescape'
2021-03-17 18:49:45 INFO     irc_bot                       Attempting to restart connection to ('irc.passthepopcorn.me', 7000) in 300 seconds.

```
</details>

### Additional information:

- FlexGet version: 3.1.106
- Python version: 3.9.2
- Installation method: pip (virtualenv)
- Using daemon (yes/no): yes
- OS and version: arch linux 5.11.6
- Link to crash log:

**Comment by MrBamse** [comment]
+1

**Comment by cvium** [comment]
`irc_bot` is not compatible with Python 3.9 and I'm not really maintaining it anymore. It's unfortunate that neither six nor future have updated to fix the deprecation.

https://github.com/cvium/irc_bot/issues/5

**Comment by cvium** [comment]
Try with version 1.0.40
