### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by marp188** [Flexget/Flexget#2888]
Plugin series crashes with the error in the title. See below the details:

 ~ $ flexget -V
3.1.106
You are on the latest release.
~ $

 ~ $ flexget series list
2021-03-25 15:41:20 ERROR    stevedore.extension                 Could not load 'addic7ed': unexpected indent (addic7ed.py, line 234)
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/flexget/__init__.py", line 44, in main
    manager.start()
  File "/usr/local/lib/python3.7/dist-packages/flexget/manager.py", line 384, in start
    self.handle_cli()
  File "/usr/local/lib/python3.7/dist-packages/flexget/manager.py", line 413, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python3.7/dist-packages/flexget/components/series/cli.py", line 38, in do_cli
    display_summary(options)
  File "/usr/local/lib/python3.7/dist-packages/flexget/components/series/cli.py", line 94, in display_summary
    latest = db.get_latest_release(series)
  File "/usr/local/lib/python3.7/dist-packages/flexget/components/series/db.py", line 1114, in get_latest_release
    return max(latest_season, latest_ep)
  File "/usr/lib/python3.7/functools.py", line 93, in _gt_from_lt
    op_result = self.__lt__(other)
  File "/usr/local/lib/python3.7/dist-packages/flexget/components/series/db.py", line 396, in __lt__
    return self.season < other.season
TypeError: '<' not supported between instances of 'int' and 'NoneType'
 ~ $ ^C
 ~ $

 ~ $ flexget --debug series list
2021-03-25 15:40:15 DEBUG    manager                       Config file /mnt/usb/.flexget/config.yml selected
2021-03-25 15:40:15 DEBUG    manager                       sys.defaultencoding: utf-8
2021-03-25 15:40:15 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2021-03-25 15:40:15 DEBUG    manager                       flexget detected io encoding: utf-8
2021-03-25 15:40:15 DEBUG    manager                       os.path.supports_unicode_filenames: False
2021-03-25 15:40:15 DEBUG    plugin                        Trying to load plugins from: ['/mnt/usb/.flexget/plugins', '/usr/local/lib/python3.7/dist-packages/flexget/plugins']
2021-03-25 15:40:15 DEBUG    stevedore._cache                 reading /home//.cache/python-entrypoints/044a70707d42995fef1ced332bba8e40de6afe508c0050cd08f42e50a0bee7a8
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='addic7ed', value='subliminal.providers.addic7ed:Addic7edProvider', group='subliminal.providers')
2021-03-25 15:40:15 ERROR    stevedore.extension                 Could not load 'addic7ed': unexpected indent (addic7ed.py, line 234)
Traceback (most recent call last):

  File "/usr/local/bin/flexget", line 10, in <module>
    sys.exit(main())
    |   |    -> <function main at 0xb668e7c8>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>

  File "/usr/local/lib/python3.7/dist-packages/flexget/__init__.py", line 44, in main
    manager.start()
    |       -> <function Manager.start at 0xb4f09fa8>
    -> <flexget.manager.Manager object at 0xb500ee70>

  File "/usr/local/lib/python3.7/dist-packages/flexget/manager.py", line 383, in start
    self.initialize()
    |    -> <function Manager.initialize at 0xb4f09e88>
    -> <flexget.manager.Manager object at 0xb500ee70>

  File "/usr/local/lib/python3.7/dist-packages/flexget/manager.py", line 225, in initialize
    extra_components=[os.path.join(self.config_base, 'components')],
                      |  |    |    |    -> '/mnt/usb/.flexget'
                      |  |    |    -> <flexget.manager.Manager object at 0xb500ee70>
                      |  |    -> <function join at 0xb66e6a50>
                      |  -> <module 'posixpath' from '/usr/lib/python3.7/posixpath.py'>
                      -> <module 'os' from '/usr/lib/python3.7/os.py'>

  File "/usr/local/lib/python3.7/dist-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    |                       -> ['/mnt/usb/.flexget/plugins', '/usr/local/lib/python3.7/dist-packages/flexget/plugins']
    -> <function _load_plugins_from_dirs at 0xb518ddf8>

  File "/usr/local/lib/python3.7/dist-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    |              |            -> PosixPath('/usr/local/lib/python3.7/dist-packages/flexget/plugins/output/subtitles_subliminal.py')
    |              -> 'flexget.plugins.output.subtitles_subliminal'
    -> <function _import_plugin at 0xb518dfa8>

  File "/usr/local/lib/python3.7/dist-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    |             -> 'flexget.plugins.output.subtitles_subliminal'
    -> <function import_module at 0xb6717a50>

  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           |          |           |    |        |        -> 0
           |          |           |    |        -> None
           |          |           |    -> 0
           |          |           -> 'flexget.plugins.output.subtitles_subliminal'
           |          -> <function _gcd_import at 0xb6778ed0>
           -> <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/local/lib/python3.7/dist-packages/flexget/plugins/output/subtitles_subliminal.py", line 15, in <module>
    from subliminal.extensions import provider_manager

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/local/lib/python3.7/dist-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/local/lib/python3.7/dist-packages/subliminal/core.py", line 16, in <module>
    from .extensions import provider_manager, default_providers, refiner_manager

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/local/lib/python3.7/dist-packages/subliminal/extensions.py", line 99, in <module>
    'tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider'

  File "/usr/local/lib/python3.7/dist-packages/subliminal/extensions.py", line 30, in __init__
    super(RegistrableExtensionManager, self).__init__(namespace, **kwargs)
          |                            |              |            -> {}
          |                            |              -> 'subliminal.providers'
          |                            -> <subliminal.extensions.RegistrableExtensionManager object at 0xb4c2d910>
          -> <class 'subliminal.extensions.RegistrableExtensionManager'>

  File "/usr/local/lib/python3.7/dist-packages/stevedore/extension.py", line 136, in __init__
    verify_requirements)
    -> False

> File "/usr/local/lib/python3.7/dist-packages/stevedore/extension.py", line 225, in _load_plugins
    verify_requirements,
    -> False

  File "/usr/local/lib/python3.7/dist-packages/stevedore/extension.py", line 255, in _load_one_plugin
    plugin = ep.load()
             |  -> <function EntryPoint.load at 0xb53838a0>
             -> EntryPoint(name='addic7ed', value='subliminal.providers.addic7ed:Addic7edProvider', group='subliminal.providers')

  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
             |             |     -> <method 'group' of 're.Match' objects>
             |             -> <re.Match object; span=(0, 46), match='subliminal.providers.addic7ed:Addic7edProvider'>
             -> <function import_module at 0xb6717a50>

  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           |          |           |    |        |        -> 0
           |          |           |    |        -> None
           |          |           |    -> 0
           |          |           -> 'subliminal.providers.addic7ed'
           |          -> <function _gcd_import at 0xb6778ed0>
           -> <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/local/lib/python3.7/dist-packages/subliminal/providers/addic7ed.py", line 234
    r = self.session.get(self.server_url + 'show/%d' % show_id, params={'season': season}, timeout=10)
    ^

IndentationError: unexpected indent
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='argenteam', value='subliminal.providers.argenteam:ArgenteamProvider', group='subliminal.providers')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='legendastv', value='subliminal.providers.legendastv:LegendasTVProvider', group='subliminal.providers')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='opensubtitles', value='subliminal.providers.opensubtitles:OpenSubtitlesProvider', group='subliminal.providers')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='podnapisi', value='subliminal.providers.podnapisi:PodnapisiProvider', group='subliminal.providers')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='shooter', value='subliminal.providers.shooter:ShooterProvider', group='subliminal.providers')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='thesubdb', value='subliminal.providers.thesubdb:TheSubDBProvider', group='subliminal.providers')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='tvsubtitles', value='subliminal.providers.tvsubtitles:TVsubtitlesProvider', group='subliminal.providers')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint.parse('opensubtitlesvip = subliminal.providers.opensubtitles:OpenSubtitlesVipProvider')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='hash', value='subliminal.refiners.hash:refine', group='subliminal.refiners')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='metadata', value='subliminal.refiners.metadata:refine', group='subliminal.refiners')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='omdb', value='subliminal.refiners.omdb:refine', group='subliminal.refiners')
2021-03-25 15:40:15 DEBUG    stevedore.extension                 found extension EntryPoint(name='tvdb', value='subliminal.refiners.tvdb:refine', group='subliminal.refiners')
2021-03-25 15:40:16 DEBUG    plugin                        Plugin `memusage` requires plugin `ext lib `guppy`` to load.
2021-03-25 15:40:17 DEBUG    plugin                        Trying to load components from: ['/mnt/usb/.flexget/components', '/usr/local/lib/python3.7/dist-packages/flexget/components']
2021-03-25 15:40:19 DEBUG    plugin                        Plugins took 4.23 seconds to load. 308 plugins in registry.
2021-03-25 15:40:19 DEBUG    manager                       Connecting to: sqlite:////mnt/usb/.flexget/db-config.sqlite
2021-03-25 15:40:19 DEBUG    manager                       config_name: config
2021-03-25 15:40:19 DEBUG    manager                       config_base: /mnt/usb/.flexget
2021-03-25 15:40:19 DEBUG    manager                       New config data loaded.
2021-03-25 15:40:20 DEBUG    schema                        current flexget version already exist in db 3.1.106
2021-03-25 15:40:20 DEBUG    parsing                       setting default movie parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0xb0b9dfd0>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0xb0b9df90>})
2021-03-25 15:40:24 DEBUG    parsing                       setting default series parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0xb0b9dfd0>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0xb0b9df90>})
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `3001- The Final Odyssey` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `3001- The Final Odyssey` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Are You Sleeping` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Are You Sleeping` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Babylon Berlin` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Babylon Berlin` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Baghdad Central` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Baghdad Central` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Barbarians` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Barbarians` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Becoming Elizabeth` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Becoming Elizabeth` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Black Mirror` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Black Mirror` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Bodyguard` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Bodyguard` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `COBRA` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `COBRA` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Code 404` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Code 404` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Death Comes as the End` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Death Comes as the End` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     latest episode for series <Series(id=49,name=Debris)>, with downloaded set to True and season set to None
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Debris` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Dimension 404` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Dimension 404` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `DMZ` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `DMZ` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Electric Dreams` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Electric Dreams` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Endeavour` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Endeavour` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no episodes found for series `Fahrenheit 451` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     no season packs found for series `Fahrenheit 451` with parameters season: None, downloaded: True
2021-03-25 15:40:24 DEBUG    series.db                     latest episode for series <Series(id=31,name=For All Mankind)>, with downloaded set to True and season set to None
2021-03-25 15:40:24 DEBUG    series.db                     latest season pack for series <Series(id=31,name=For All Mankind)>, with downloaded set to True and season set to None
2021-03-25 15:40:24 DEBUG    manager                       Removed /mnt/usb/.flexget/.config-lock
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/flexget/__init__.py", line 44, in main
    manager.start()
  File "/usr/local/lib/python3.7/dist-packages/flexget/manager.py", line 384, in start
    self.handle_cli()
  File "/usr/local/lib/python3.7/dist-packages/flexget/manager.py", line 413, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python3.7/dist-packages/flexget/components/series/cli.py", line 38, in do_cli
    display_summary(options)
  File "/usr/local/lib/python3.7/dist-packages/flexget/components/series/cli.py", line 94, in display_summary
    latest = db.get_latest_release(series)
  File "/usr/local/lib/python3.7/dist-packages/flexget/components/series/db.py", line 1114, in get_latest_release
    return max(latest_season, latest_ep)
  File "/usr/lib/python3.7/functools.py", line 93, in _gt_from_lt
    op_result = self.__lt__(other)
  File "/usr/local/lib/python3.7/dist-packages/flexget/components/series/db.py", line 396, in __lt__
    return self.season < other.season
TypeError: '<' not supported between instances of 'int' and 'NoneType'
 ~ $

**Comment by gazpachoking** [comment]
@marp188 Is there a crash log that has the more detailed traceback? Are you using internal parser, or guessit? Do you know what series this might be from, it would be good to see the list of episodes in the database using `flexget series show <showname here>` command.

It seems like somehow there is an episode in the database with an 'ep' (having a season and episode number) style, that somehow doesn't have a season number. Either that, or there is a season in the database without a season number.

**Comment by marp188** [comment]
I recreated from scartch the database and the isse seemed corrected by itself somehow

**Comment by soloam** [comment]
That is expected, the error was in a value that was in the db :)

Without more log details it's complicated to understand the root of this problem

I think if there is no more problems for you, the issue can be closed!
