### ISSUE TITLE
CRITICAL plugin                        Plugin `flexget.plugins.cli.explain_sql` failed to import dependencies

### ISSUE THREAD

**Issue by Groodles** [Flexget/Flexget#2964]
Even though Flexget throw this error on start-up, execution appears to function normally.

```
Traceback (most recent call last):

  File "/usr/local/bin/flexget", line 8, in <module>
    sys.exit(main())
    |   |    -> <function main at 0x7f3d9c62fb80>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>

  File "/usr/local/lib/python3.8/dist-packages/flexget/__init__.py", line 44, in main
    manager.start()
    |       -> <function Manager.start at 0x7f3d998fea60>
    -> <flexget.manager.Manager object at 0x7f3d998fd580>

  File "/usr/local/lib/python3.8/dist-packages/flexget/manager.py", line 383, in start
    self.initialize()
    |    -> <function Manager.initialize at 0x7f3d998fe820>
    -> <flexget.manager.Manager object at 0x7f3d998fd580>

  File "/usr/local/lib/python3.8/dist-packages/flexget/manager.py", line 223, in initialize
    plugin.load_plugins(
    |      -> <function load_plugins at 0x7f3d99e37280>
    -> <module 'flexget.plugin' from '/usr/local/lib/python3.8/dist-packages/flexget/plugin.py'>

  File "/usr/local/lib/python3.8/dist-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    |                       -> ['/home/deluge/.flexget/plugins', '/usr/local/lib/python3.8/dist-packages/flexget/plugins']
    -> <function _load_plugins_from_dirs at 0x7f3d99e370d0>

  File "/usr/local/lib/python3.8/dist-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    |              |            -> PosixPath('/usr/local/lib/python3.8/dist-packages/flexget/plugins/cli/explain_sql.py')
    |              -> 'flexget.plugins.cli.explain_sql'
    -> <function _import_plugin at 0x7f3d99e37040>

> File "/usr/local/lib/python3.8/dist-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    |             -> 'flexget.plugins.cli.explain_sql'
    -> <function import_module at 0x7f3d9c6f49d0>

  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           |          |           |    |        |        -> 0
           |          |           |    |        -> None
           |          |           |    -> 0
           |          |           -> 'flexget.plugins.cli.explain_sql'
           |          -> <function _gcd_import at 0x7f3d9c827430>
           -> <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/local/lib/python3.8/dist-packages/flexget/plugins/cli/explain_sql.py", line 7, in <module>
    from sqlalchemy.sql.expression import ClauseElement, Executable, _literal_as_text
                                          |              -> <class 'sqlalchemy.sql.base.Executable'>
                                          -> <class 'sqlalchemy.sql.elements.ClauseElement'>

ImportError: cannot import name '_literal_as_text' from 'sqlalchemy.sql.expression' (/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/expression.py)
```

**Comment by gazpachoking** [comment]
Fixed in https://github.com/Flexget/Flexget/commit/6818298b553b034ad0ee5bf4fe97314241a861ec
Fix will be included in today's release
