### ISSUE TITLE
BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by terrellgf** [Flexget/Flexget#3034]
Version 3.1.120

2021-06-06 19:52:00 CRITICAL task          M-Team-Movies   BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f9ac623eee0>
    └ <Thread(task_queue, started daemon 140302600940344)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f9ac623ec10>
    └ <Thread(task_queue, started daemon 140302600940344)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140302600940344)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140302600940344)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f9abfc4c790>>
    └ <Thread(task_queue, started daemon 140302600940344)>
  File "/usr/lib/python3.8/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f9ac367a430>
    │    └ <flexget.task.Task object at 0x7f9ab769e6d0>
    └ <flexget.task_queue.TaskQueue object at 0x7f9abfc4c790>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f9ab769e6d0>
           └ <function Task.execute at 0x7f9ac367a3a0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f9ac367a310>
    └ <flexget.task.Task object at 0x7f9ab769e6d0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
    │                     └ 'filter'
    └ <flexget.task.Task object at 0x7f9ab769e6d0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f9ab769e6d0>, {'min_year': 2000, 'min_score': 7, 'reject_genres': ['documentary', 'musical',...
               │                 │       └ 'filter'
               │                 └ <PluginInfo(name=imdb)>
               └ <flexget.task.Task object at 0x7f9ab769e6d0>
> File "/usr/lib/python3.8/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7f9ab769e6d0>, {'min_year': 2000, 'min_score': 7, 'reject_genres': ['documentary', 'musical',...
             └ <Event(name=plugin.imdb.filter,func=on_task_filter,priority=120)>
  File "/usr/lib/python3.8/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7f9ab769e6d0>, {'min_year': 2000, 'min_score': 7, 'reject_genres': ['documentary', 'musical',...
           │    └ <bound method FilterImdb.on_task_filter of <flexget.components.imdb.imdb.FilterImdb object at 0x7f9abfd3f970>>
           └ <Event(name=plugin.imdb.filter,func=on_task_filter,priority=120)>
  File "/usr/lib/python3.8/site-packages/flexget/components/imdb/imdb.py", line 117, in on_task_filter
    lookup(entry)
    │      └ <Entry(title=U-571 2000 BD-Remux 1080p VC-1 DTS-HD 5Audio-19977,state=undecided)>
    └ <bound method internet.__call__.<locals>.wrapped_func of <flexget.components.imdb.imdb_lookup.ImdbLookup object at 0x7f9abfd3...
  File "/usr/lib/python3.8/site-packages/flexget/plugin.py", line 126, in wrapped_func
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<flexget.components.imdb.imdb_lookup.ImdbLookup object at 0x7f9abfd3fa90>, <Entry(title=U-571 2000 BD-Remux 1080p VC-1 DTS-H...
           └ <function with_session.<locals>.decorator.<locals>.wrapper at 0x7f9ac4471940>
  File "/usr/lib/python3.8/site-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
           │     │       └ {'session': <sqlalchemy.orm.session.ContextSession object at 0x7f9ab93f48b0>}
           │     └ (<flexget.components.imdb.imdb_lookup.ImdbLookup object at 0x7f9abfd3fa90>, <Entry(title=U-571 2000 BD-Remux 1080p VC-1 DTS-H...
           └ <function ImdbLookup.lookup at 0x7f9ac4471790>
  File "/usr/lib/python3.8/site-packages/flexget/components/imdb/imdb_lookup.py", line 222, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
            │    │                │                  └ <sqlalchemy.orm.session.ContextSession object at 0x7f9ab93f48b0>
            │    │                └ <Entry(title=U-571 2000 BD-Remux 1080p VC-1 DTS-HD 5Audio-19977,state=undecided)>
            │    └ <function ImdbLookup._parse_new_movie at 0x7f9ac44719d0>
            └ <flexget.components.imdb.imdb_lookup.ImdbLookup object at 0x7f9abfd3fa90>
  File "/usr/lib/python3.8/site-packages/flexget/components/imdb/imdb_lookup.py", line 267, in _parse_new_movie
    parser.parse(imdb_url)
    │      │     └ 'https://www.imdb.com/title/tt0141926/'
    │      └ <function ImdbParser.parse at 0x7f9ac171fee0>
    └ <flexget.components.imdb.utils.ImdbParser object at 0x7f9ab93f4ca0>
  File "/usr/lib/python3.8/site-packages/flexget/components/imdb/utils.py", line 327, in parse
    original_name_elem = title_wrapper.find('div', {'class': 'originalTitle'})
                         └ None

AttributeError: 'NoneType' object has no attribute 'find'
2021-06-06 19:52:00 CRITICAL manager       M-Team-Movies   An unexpected crash has occurred. Writing crash report to /config/crash_report.2021.06.06.195200676102.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.120
2021-06-06 19:52:00 WARNING  task          M-Team-Movies   Aborting task (plugin: imdb)

**Comment by terrellgf** [comment]
Fixed it by updating from  3.1.120 to  3.1.130. It seems that the old version is not supported due to the movie title format change of imdb site.

**Comment by BrutuZ** [comment]
As mentioned, fixed on [3.1.129](https://flexget.com/ChangeLog#31129-2021-05-27). Issue can be closed
