### ISSUE TITLE
Jellyfin not working after version 3.1.120

### ISSUE THREAD

**Issue by arbuilder** [Flexget/Flexget#3078]
Earlier jellyfin was working in 3.1.120 version. but now it is giving me errors when i use it to get movies and shows. it would be nice if i could get it to work again since jellyfin is also open sourced and free.

### Steps to reproduce:
run the config and error shows up

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

variables: variables.yml

tasks:
  get_jellyfin_list:
    emby_list:
        server:
            host: "http://xxx.xx.x.x:8096"
            username: xxxx
            password: xxxx
            return_host: lan
        list: movies
    list_add:
      - entry_list: jellyfin_movie_list 

schedules: false


```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
root@xxxxxxxxxxxxxx:/config# flexget -L debug execute --tasks get_jellyfin_list
2021-07-13 13:51:57 DEBUG    manager                       Figuring out config load paths
2021-07-13 13:51:57 DEBUG    manager                       Found config: /config/config.yml
2021-07-13 13:51:57 DEBUG    manager                       Config file /config/config.yml selected
2021-07-13 13:51:57 DEBUG    manager                       sys.defaultencoding: utf-8
2021-07-13 13:51:57 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2021-07-13 13:51:57 DEBUG    manager                       flexget detected io encoding: utf-8
2021-07-13 13:51:57 DEBUG    manager                       os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2021-07-13 13:51:57 DEBUG    manager                       Sending command to running FlexGet process: ['-L', 'debug', 'execute', '--tasks', 'get_jellyfin_list']
2021-07-13 13:51:57 DEBUG    cron_env                      Encoding utf-8 stored
2021-07-13 13:51:57 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'utf-8'
2021-07-13 13:51:57 DEBUG    task          get_jellyfin_list executing get_jellyfin_list
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Users/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx with args () and kwargs {'params': {}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Restored emby token from database
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/System/Info with args () and kwargs {'params': {}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Saving emby token to database
2021-07-13 13:51:57 DEBUG    util.simple_persistence get_jellyfin_list setting key token_data value {'host': 'http://xxx.xx.x.x:8096', 'username': 'flexget', 'userid': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'serverid': 'd3e16a7d41e843f086ac79dd2b15267b', 'token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'connect_username': '', 'login_type': None}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Search Library name list with: {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IsHidden': False}
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Library/MediaFolders with args () and kwargs {'params': {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IsHidden': False}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list List is a library
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Search Library name list with: {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IsHidden': False}
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Library/MediaFolders with args () and kwargs {'params': {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IsHidden': False}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Search library with: {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IncludeItemTypes': 'Episode,Movie', 'ParentId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Users/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Items with args () and kwargs {'params': {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IncludeItemTypes': 'Episode,Movie', 'ParentId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Limit': 10, 'StartIndex': 0}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Search movie with: {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'Ids': '00e7116bacd9c913ec71436c9f8128af', 'IncludeItemTypes': 'Movie'}
2021-07-13 13:51:58 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Users/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Items with args () and kwargs {'params': {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'Ids': '00e7116bacd9c913ec71436c9f8128af', 'IncludeItemTypes': 'Movie'}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:58 CRITICAL task          get_jellyfin_list BUG: Unhandled error in plugin emby_list: can't set attribute
AttributeError: can't set attribute
2021-07-13 13:51:58 CRITICAL manager       get_jellyfin_list An unexpected crash has occurred. Writing crash report to /config/crash_report.2021.07.13.135158087565.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.131
2021-07-13 13:51:58 DEBUG    manager       get_jellyfin_list Traceback:
AttributeError: can't set attribute
2021-07-13 13:51:58 WARNING  task          get_jellyfin_list Aborting task (plugin: emby_list)
```
</details>

#### Crash Log:
<details>
 <summary>(click to expand)</summary>

```
2021-07-13 13:51:08 DEBUG    manager                       Config file /config/config.yml selected
2021-07-13 13:51:08 DEBUG    manager                       sys.defaultencoding: utf-8
2021-07-13 13:51:08 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2021-07-13 13:51:08 DEBUG    manager                       flexget detected io encoding: utf-8
2021-07-13 13:51:08 DEBUG    manager                       os.path.supports_unicode_filenames: False
2021-07-13 13:51:08 DEBUG    manager                       Config file /config/config.yml selected
2021-07-13 13:51:08 DEBUG    manager                       sys.defaultencoding: utf-8
2021-07-13 13:51:08 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2021-07-13 13:51:08 DEBUG    manager                       flexget detected io encoding: utf-8
2021-07-13 13:51:08 DEBUG    manager                       os.path.supports_unicode_filenames: False
2021-07-13 13:51:08 DEBUG    plugin                        Trying to load plugins from: ['/config/plugins', '/usr/lib/python3.8/site-packages/flexget/plugins']
2021-07-13 13:51:08 DEBUG    plugin                        Plugin `memusage` requires plugin `ext lib `guppy`` to load.
2021-07-13 13:51:09 DEBUG    plugin                        Trying to load components from: ['/config/components', '/usr/lib/python3.8/site-packages/flexget/components']
2021-07-13 13:51:09 DEBUG    plugin                        Plugins took 1.62 seconds to load. 314 plugins in registry.
2021-07-13 13:51:09 DEBUG    manager                       Connecting to: sqlite:////config/db-config.sqlite
2021-07-13 13:51:10 DEBUG    manager                       config_name: config
2021-07-13 13:51:10 DEBUG    manager                       config_base: /config
2021-07-13 13:51:10 DEBUG    variables                     trying to load variables from file
2021-07-13 13:51:10 DEBUG    variables                     updating DB with variable file contents
2021-07-13 13:51:10 DEBUG    manager                       New config data loaded.
2021-07-13 13:51:10 DEBUG    schema                        current flexget version already exist in db 3.1.131
2021-07-13 13:51:10 DEBUG    parsing                       setting default movie parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7fc05ddbb550>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7fc05ddbb6d0>})
2021-07-13 13:51:10 DEBUG    parsing                       setting default series parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7fc05ddbb550>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7fc05ddbb6d0>})
2021-07-13 13:51:10 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
2021-07-13 13:51:10 INFO     web_server_daemon                 Initiating API
2021-07-13 13:51:10 INFO     web_server_daemon                 Registering WebUI v2
2021-07-13 13:51:10 INFO     web_server                    Web server started at http://xxx.xx.x.xx:5050
2021-07-13 13:51:10 INFO     web_server                    API available at http://xxx.xx.x.xx:5050/api
2021-07-13 13:51:10 INFO     web_server                    WebUI (v2) available at http://xxx.xx.x.xx:5050/
2021-07-13 13:51:10 DEBUG    irc                           No irc connections defined in the config
2021-07-13 13:51:57 VERBOSE  ipc                           Running command `-L debug execute --tasks get_jellyfin_list` for client.
2021-07-13 13:51:57 DEBUG    cron_env                      Encoding utf-8 stored
2021-07-13 13:51:57 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'utf-8'
2021-07-13 13:51:57 DEBUG    task          get_jellyfin_list executing get_jellyfin_list
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Users/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx with args () and kwargs {'params': {}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Restored emby token from database
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/System/Info with args () and kwargs {'params': {}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Saving emby token to database
2021-07-13 13:51:57 DEBUG    util.simple_persistence get_jellyfin_list setting key token_data value {'host': 'http://xxx.xx.x.x:8096', 'username': 'flexget', 'userid': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'serverid': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'connect_username': '', 'login_type': None}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Search Library name list with: {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IsHidden': False}
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Library/MediaFolders with args () and kwargs {'params': {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IsHidden': False}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list List is a library
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Search Library name list with: {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IsHidden': False}
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Library/MediaFolders with args () and kwargs {'params': {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IsHidden': False}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Search library with: {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IncludeItemTypes': 'Episode,Movie', 'ParentId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
2021-07-13 13:51:57 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Users/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Items with args () and kwargs {'params': {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'IncludeItemTypes': 'Episode,Movie', 'ParentId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Limit': 10, 'StartIndex': 0}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:57 DEBUG    api_emby      get_jellyfin_list Search movie with: {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'Ids': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'IncludeItemTypes': 'Movie'}
2021-07-13 13:51:58 DEBUG    utils.requests get_jellyfin_list GETing URL http://xxx.xx.x.x:8096/emby/Users/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/Items with args () and kwargs {'params': {'Recursive': True, 'Fields': 'DateCreated,Path,ProviderIds,PremiereDate,MediaSources,Video3DFormat,Overview', 'IsMissing': False, 'Ids': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'IncludeItemTypes': 'Movie'}, 'headers': {'X-Emby-Authorization': 'Emby UserId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Client=Flexget, Device=Flexget Plugin, DeviceId=flexget_plugin, Version=3.1.131', 'accept': 'application/json', 'X-Emby-Token': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}, 'allow_redirects': True, 'verify': False, 'timeout': 30}
2021-07-13 13:51:58 CRITICAL task          get_jellyfin_list BUG: Unhandled error in plugin emby_list: can't set attribute
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fc06443aee0>
    └ <Thread(task_queue, started daemon 140464167377720)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fc06443ac10>
    └ <Thread(task_queue, started daemon 140464167377720)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140464167377720)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140464167377720)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fc05dd4af40>>
    └ <Thread(task_queue, started daemon 140464167377720)>
  File "/usr/lib/python3.8/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7fc0617c8940>
    │    └ <flexget.task.Task object at 0x7fc05ca991f0>
    └ <flexget.task_queue.TaskQueue object at 0x7fc05dd4af40>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7fc05ca991f0>
           └ <function Task.execute at 0x7fc0617c88b0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    │    └ <function Task._execute at 0x7fc0617c8820>
    └ <flexget.task.Task object at 0x7fc05ca991f0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
    │                     └ 'input'
    └ <flexget.task.Task object at 0x7fc05ca991f0>
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7fc05ca991f0>, {'server': {'host': 'http://xxx.xx.x.x:8096', 'username': 'flexget', 'password...
               │                 │       └ 'input'
               │                 └ <PluginInfo(name=emby_list)>
               └ <flexget.task.Task object at 0x7fc05ca991f0>
> File "/usr/lib/python3.8/site-packages/flexget/task.py", line 550, in __run_plugin
    result = list(result)
                  └ <generator object PluginEmbyList.on_task_input at 0x7fc05ca27430>
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/emby_list.py", line 60, in on_task_input
    for s_list in s_lists:
                  └ <generator object EmbyApi.search_list at 0x7fc05ca27c10>
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 2686, in search_list
    for list_obj in mlist:
                    └ <generator object EmbyApiLibrary.get_items at 0x7fc05ca27b30>
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 798, in get_items
    media_obj = EmbyApiMedia.cast(auth=self.auth, **media)
                │            │         │    │       └ {'Name': 'The Lazarus Effect', 'ServerId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Dat...
                │            │         │    └ <flexget.components.emby.api_emby.EmbyAuth object at 0x7fc05d960f10>
                │            │         └ <flexget.components.emby.api_emby.EmbyApiLibrary object at 0x7fc05ca1fd90>
                │            └ <staticmethod object at 0x7fc05f05b460>
                └ <class 'flexget.components.emby.api_emby.EmbyApiMedia'>
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 1586, in cast
    return EmbyApiMovie.search(**kwargs)
           │            │        └ {'auth': <flexget.components.emby.api_emby.EmbyAuth object at 0x7fc05d960f10>, 'Name': 'The Lazarus Effect', 'ServerId': 'd3e...
           │            └ <staticmethod object at 0x7fc05f05b850>
           └ <class 'flexget.components.emby.api_emby.EmbyApiMovie'>
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 2536, in search
    movie_api = EmbyApiMovie(auth=auth, **movie)
                │                 │       └ {'Name': 'The Lazarus Effect', 'ServerId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Dat...
                │                 └ <flexget.components.emby.api_emby.EmbyAuth object at 0x7fc05d960f10>
                └ <class 'flexget.components.emby.api_emby.EmbyApiMovie'>
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 2392, in __init__
    EmbyApiMedia.__init__(self, field_map=EmbyApiMovie.field_map_up, **kwargs)
    │            │        │               │            │               └ {'auth': <flexget.components.emby.api_emby.EmbyAuth object at 0x7fc05d960f10>, 'Name': 'The Lazarus Effect', 'ServerId': 'd3e...
    │            │        │               │            └ {'id': 'movie_id', 'base_name': 'movie_name', 'imdb_id': 'movie_imdb_id', 'tmdb_id': 'movie_tmdb_id', 'tvdb_id': 'movie_tvdb_...
    │            │        │               └ <class 'flexget.components.emby.api_emby.EmbyApiMovie'>
    │            │        └ <flexget.components.emby.api_emby.EmbyApiMovie object at 0x7fc05c8d4d30>
    │            └ <function EmbyApiMedia.__init__ at 0x7fc05f0613a0>
    └ <class 'flexget.components.emby.api_emby.EmbyApiMedia'>
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 1322, in __init__
    EmbyApiBase.update_using_map(self, EmbyApiMedia.field_map, kwargs)
    │           │                │     │            │          └ {'field_map': {'id': 'movie_id', 'base_name': 'movie_name', 'imdb_id': 'movie_imdb_id', 'tmdb_id': 'movie_tmdb_id', 'tvdb_id'...
    │           │                │     │            └ {'mtype': ['emby_mtype', 'mtype', 'Type'], 'id': ['emby_id', 'id', 'Id'], 'search_string': ['emby_search_string', 'search_str...
    │           │                │     └ <class 'flexget.components.emby.api_emby.EmbyApiMedia'>
    │           │                └ <flexget.components.emby.api_emby.EmbyApiMovie object at 0x7fc05c8d4d30>
    │           └ <staticmethod object at 0x7fc05f048e20>
    └ <class 'flexget.components.emby.api_emby.EmbyApiBase'>
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 127, in update_using_map
    setattr(target, field, val)
            │       │      └ 2015
            │       └ 'year'
            └ <flexget.components.emby.api_emby.EmbyApiMovie object at 0x7fc05c8d4d30>

AttributeError: can't set attribute
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flexget/task.py", line 550, in __run_plugin
    result = list(result)
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/emby_list.py", line 60, in on_task_input
    for s_list in s_lists:
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 2686, in search_list
    for list_obj in mlist:
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 798, in get_items
    media_obj = EmbyApiMedia.cast(auth=self.auth, **media)
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 1586, in cast
    return EmbyApiMovie.search(**kwargs)
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 2536, in search
    movie_api = EmbyApiMovie(auth=auth, **movie)
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 2392, in __init__
    EmbyApiMedia.__init__(self, field_map=EmbyApiMovie.field_map_up, **kwargs)
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 1322, in __init__
    EmbyApiBase.update_using_map(self, EmbyApiMedia.field_map, kwargs)
  File "/usr/lib/python3.8/site-packages/flexget/components/emby/api_emby.py", line 127, in update_using_map
    setattr(target, field, val)
AttributeError: can't set attribute

```
</details>

### Additional information:

- FlexGet version: 3.1.131
- Installation method: using docker image (ghcr.io/wiserain/flexget)
- OS and version: Win 10 home 2004

**Comment by lamski** [comment]
The indentation of the emby_list properties seem inconsistent with the rest of the config file. Try changing the indentation to 2 spaces like in the other areas.

**Comment by arbuilder** [comment]
> The indentation of the emby_list properties seem inconsistent with the rest of the config file. Try changing the indentation to 2 spaces like in the other areas.

I don't think that is the issue, otherwise flexget won't save config file and run, also i use that indentation for better readability

**Comment by arbuilder** [comment]
i have used 3.1.120 code to add jellyfin plugin functionality
