### ISSUE TITLE
[Bug] Flexget > Notifiers > Xmpp > sleekxmpp - Not working 

### ISSUE THREAD

**Issue by open-recipes-app** [Flexget/Flexget#3156]
### Expected behaviour:

Running Flexget on Linux Debian.
On notification expected behaviour is to get notified via xmpp

### Actual behaviour:
No notification is received 

### Steps to reproduce:
- Step 1: execute flexget with some task that has a xmpp notification at the completion of the task
- Step 2: wait for the xmpp notification to arrive 

#### Config:
```
  download:
    priority: 1
    rss: 'http://showrss.info/user/148.rss?magnets=true&namespaces=true&name=null&quality=null&re=null'
    all_series: yes
    transmission:
      host: localhost
      port: 9091
      path: '/home/htpc/Downloads/temp/tvshows'
    notify:
      entries:
        title: 'Downloading - {% if author is defined -%} {{author}} {% elif name is defined -%} {{name}} {% elif title is defined -%} {{title}} {% else %} {{url}} {%endif%}'
        template: html-custom.template
        via:
          - xmpp:
              sender: test-bot@jabber.de
              password: yipee-ka-yay
              recipients: test@jabber.de                

```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
<DependencyError(issued_by='xmpp',missing='dnspython',message="dnspython module required. ImportError: No module named 'dnspython'",silent=False)>
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/flexget/components/notify/notifiers/xmpp.py", line 55, in notify
    import dns  # noqa

ModuleNotFoundError: No module named 'dns'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/flexget/components/notify/notifiers/xmpp.py", line 58, in notify
    import dnspython  # noqa

ModuleNotFoundError: No module named 'dnspython'
```
</details>

### Additional information:

- FlexGet version: 3.1.137
- Python version: 3
- Installation method: terminal
- Using daemon (yes/no): yes
- OS and version: Debian Bullseye

**Comment by open-recipes-app** [comment]
Managed to fix the bug using the following:

`sudo pip3 uninstall sleekxmpp
sudo pip3 install sleekxmpp==1.3.1`
and
`pip install dnspython`

Installation of the latest sleekxmpp version gives another error "CERT: Invalid certificate trust chain." sleekxmpp version 1.3.1 works fine if installed with dnspython.

Update the flexget docs maybe https://flexget.com/Plugins/Notifiers/xmpp
