### ISSUE TITLE
`sort_by` can't handle fields with colons

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/Flexget#3307]
### Expected behaviour:
Properly sort entries from RSS feed with custom fields

### Actual behaviour:
Crash

#### Config:
```yaml
  test:
    mock:
      - title: "[Flexget] Amazing Show - s01e01"
        "colons:field": 123
    sort_by:
      - field: "colons:field"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2022-01-08 15:14:02 VERBOSE  details       test            Produced 1 entries.
2022-01-08 15:14:02 CRITICAL task          test            BUG: Unhandled error in plugin sort_by: chunk after expression
Traceback (most recent call last):

  File "c:\python37\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001470EB78318>
    └ <Thread(task_queue, started daemon 2736)>

  File "c:\python37\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001470EB780D8>
    └ <Thread(task_queue, started daemon 2736)>

  File "c:\python37\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 2736)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 2736)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x0000014716646AC8>>
    └ <Thread(task_queue, started daemon 2736)>

  File "c:\users\brutuz\documents\github\flexget\flexget\task_queue.py", line 47, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x0000014711B049D8>
    │    └ <flexget.task.Task object at 0x00000147168AB208>
    └ <flexget.task_queue.TaskQueue object at 0x0000014716646AC8>

  File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x00000147168AB208>
           └ <function Task.execute at 0x0000014711B04948>

  File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 727, in execute
    self._execute()
    │    └ <function Task._execute at 0x0000014711B048B8>
    └ <flexget.task.Task object at 0x00000147168AB208>

  File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 696, in _execute
    self.__run_task_phase(phase)
    │                     └ 'filter'
    └ <flexget.task.Task object at 0x00000147168AB208>

  File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x00000147168AB208>, [{'field': 'colons:field'}])
               │                 │       └ 'filter'
               │                 └ <PluginInfo(name=sort_by)>
               └ <flexget.task.Task object at 0x00000147168AB208>

> File "c:\users\brutuz\documents\github\flexget\flexget\task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x00000147168AB208>, [{'field': 'colons:field'}])
             └ <Event(name=plugin.sort_by.filter,func=on_task_filter,priority=255)>

  File "c:\users\brutuz\documents\github\flexget\flexget\event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x00000147168AB208>, [{'field': 'colons:field'}])
           │    └ <bound method PluginSortBy.on_task_filter of <flexget.plugins.modify.sort_by.PluginSortBy object at 0x000001471585D8C8>>
           └ <Event(name=plugin.sort_by.filter,func=on_task_filter,priority=255)>

  File "c:\users\brutuz\documents\github\flexget\flexget\plugins\modify\sort_by.py", line 85, in on_task_filter
    task.all_entries.sort(key=sort_key, reverse=reverse)
    │    │                    │                 └ False
    │    │                    └ <function PluginSortBy.on_task_filter.<locals>.sort_key at 0x0000014716938C18>
    │    └ <property object at 0x0000014711B039F8>
    └ <flexget.task.Task object at 0x00000147168AB208>

  File "c:\users\brutuz\documents\github\flexget\flexget\plugins\modify\sort_by.py", line 79, in sort_key
    val = evaluate_expression(field, entry)
          │                   │      └ <Entry(title=[Flexget] Amazing Show - s01e01,state=undecided)>
          │                   └ 'colons:field'
          └ <function evaluate_expression at 0x00000147117404C8>

  File "c:\users\brutuz\documents\github\flexget\flexget\utils\template.py", line 345, in evaluate_expression
    compiled_expr = environment.compile_expression(expression)
                    │           │                  └ 'colons:field'
                    │           └ <function Environment.compile_expression at 0x00000147116C95E8>
                    └ <flexget.utils.template.FlexGetEnvironment object at 0x00000147166CAEC8>

  File "c:\users\brutuz\documents\github\flexget\lib\site-packages\jinja2\environment.py", line 798, in compile_expression
    self.handle_exception(source=source)
    │    │                       └ 'colons:field'
    │    └ <function Environment.handle_exception at 0x00000147116C9798>
    └ <flexget.utils.template.FlexGetEnvironment object at 0x00000147166CAEC8>

  File "c:\users\brutuz\documents\github\flexget\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
          │                              └ 'colons:field'
          └ <function rewrite_traceback_stack at 0x0000014716953438>

  File "<unknown>", line 1, in template

jinja2.exceptions.TemplateSyntaxError: chunk after expression
```
</details>

### Additional information:

- FlexGet version: latest
- Python version: 3.7
- Installation method: git
- Using daemon (yes/no): yes
- OS and version: W10
- Link to crash log: xxx

**Comment by gazpachoking** [comment]
Hmm. Jinja variables have to follow the same rules as python identifiers, which is the reason this isn't working. Our entry fields of course don't, so this might be a bit confusing. Not sure of what a good workaround might be.

**Comment by BrutuZ** [comment]
I did manage to find a workaround
```yaml
manipulate:
  colons_field:
    from: colons:field
```
Opened the issue kind of hoping the extra step wouldn't be necessary

**Comment by gazpachoking** [comment]
I'm assuming you don't have control over how the field is created? What plugin is the field coming from? We could switch sort_by back to regular text for field selection, but that would mean things like `quality.resolution` or `title|lower` wouldn't work anymore, which isn't desirable.

**Comment by BrutuZ** [comment]
> I'm assuming you don't have control over how the field is created?

Correct, they're RSS tags imported with
```yaml
rss:
  url: xxx
  other_fields:
    - "colons:field"
```

**Comment by gazpachoking** [comment]
I believe rss other_fields allows remapping the name right there, which would be easier than using manipulate, and probably the best answer.
```yaml
rss:
  url: xxx
  other_fields:
    - "colons:field": no_colons_field
```

**Comment by gazpachoking** [comment]
I believe feedparser also replaces colons internally, so this probably works also:
rss:
  url: xxx
  other_fields:
    - colons_field

**Comment by BrutuZ** [comment]
Both worked apparently. Would never have guessed those from https://flexget.com/Plugins/rss 😅

**Comment by gazpachoking** [comment]
Yeah, that is underdocumented... I added a bit to the wiki about that.
