### ISSUE TITLE
Unable to launch updating from 3.3.5 to 3.3.6

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/Flexget#3409]
### What Happens:
Tried to update (daily script) from v3.3.5 to v3.3.6. This time Flexget couldn't launch throwing a dependency error instead
#### Config:
Doesn't get to it
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
$ git pull upstream master&&pip install -r dev-requirements.txt&&pip install --upgrade -e .&&flexget execute --task download-anime-series-rss
From github.com:Flexget/Flexget
 * branch                master     -> FETCH_HEAD
Already up to date.
Requirement already satisfied: alabaster==0.7.12 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 7)) (0.7.12)
Requirement already satisfied: astroid==2.11.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 9)) (2.11.2)
Requirement already satisfied: atomicwrites==1.4.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 11)) (1.4.0)
Requirement already satisfied: attrs==21.4.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 13)) (21.4.0)
Requirement already satisfied: babel==2.9.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 17)) (2.9.1)
Requirement already satisfied: black==22.3.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 19)) (22.3.0)
Requirement already satisfied: bleach==4.1.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 21)) (4.1.0)
Requirement already satisfied: boto3==1.21.28 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 23)) (1.21.28)
Requirement already satisfied: botocore==1.24.28 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 25)) (1.24.28)
Requirement already satisfied: certifi==2021.10.8 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 29)) (2021.10.8)
Requirement already satisfied: cfgv==3.3.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 33)) (3.3.1)
Requirement already satisfied: charset-normalizer==2.0.12 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 35)) (2.0.12)
Requirement already satisfied: click==8.0.4 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 39)) (8.0.4)
Requirement already satisfied: codacy-coverage==1.3.11 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 45)) (1.3.11)

Requirement already satisfied: colorama==0.4.4 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 47)) (0.4.4)
Requirement already satisfied: coverage[toml]==6.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 56)) (6.2)
Requirement already satisfied: dill==0.3.4 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 60)) (0.3.4)
Requirement already satisfied: distlib==0.3.4 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 62)) (0.3.4)
Requirement already satisfied: docutils==0.17.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 64)) (0.17.1)
Requirement already satisfied: execnet==1.9.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 68)) (1.9.0)
Requirement already satisfied: filelock==3.4.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 70)) (3.4.1)
Requirement already satisfied: gitdb==4.0.9 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 72)) (4.0.9)
Requirement already satisfied: gitpython==3.1.18 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 74)) (3.1.18)
Requirement already satisfied: identify==2.4.4 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 76)) (2.4.4)
Requirement already satisfied: idna==3.3 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 78)) (3.3)
Requirement already satisfied: imagesize==1.3.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 83)) (1.3.0)
Requirement already satisfied: importlib-metadata==4.8.3 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 85)) (4.8.3)
Requirement already satisfied: iniconfig==1.1.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 89)) (1.1.1)
Requirement already satisfied: isort==5.10.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 91)) (5.10.1)
Requirement already satisfied: jinja2==3.0.3 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 95)) (3.0.3)
Requirement already satisfied: jmespath==0.10.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 99)) (0.10.0)
Requirement already satisfied: keyring==23.4.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 103)) (23.4.1)
Requirement already satisfied: lazy-object-proxy==1.7.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 105)) (1.7.1)
Requirement already satisfied: markupsafe==2.0.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 107)) (2.0.1)
Requirement already satisfied: mccabe==0.7.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 111)) (0.7.0)
Requirement already satisfied: multidict==5.2.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 113)) (5.2.0)
Requirement already satisfied: mypy==0.942 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 115)) (0.942)
Requirement already satisfied: mypy-extensions==0.4.3 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 117)) (0.4.3) Requirement already satisfied: nodeenv==1.6.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 121)) (1.6.0)
Requirement already satisfied: packaging==21.3 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 123)) (21.3)
Requirement already satisfied: pathspec==0.9.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 128)) (0.9.0)
Requirement already satisfied: pep517==0.12.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 130)) (0.12.0)
Requirement already satisfied: pip-tools==6.4.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 132)) (6.4.0)
Requirement already satisfied: pkginfo==1.8.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 134)) (1.8.2)
Requirement already satisfied: platformdirs==2.4.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 136)) (2.4.0)
Requirement already satisfied: pluggy==1.0.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 141)) (1.0.0)
Requirement already satisfied: pre-commit==2.17.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 143)) (2.17.0)
Requirement already satisfied: py==1.11.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 145)) (1.11.0)
Requirement already satisfied: pygments==2.11.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 149)) (2.11.2)
Requirement already satisfied: pylint==2.13.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 154)) (2.13.2)
Requirement already satisfied: pyparsing==3.0.7 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 156)) (3.0.7)
Requirement already satisfied: pytest==6.2.5 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 160)) (6.2.5)
Requirement already satisfied: pytest-cov==3.0.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 166)) (3.0.0)
Requirement already satisfied: pytest-forked==1.4.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 168)) (1.4.0)
Requirement already satisfied: pytest-runner==5.3.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 170)) (5.3.2)
Requirement already satisfied: pytest-xdist==2.4.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 172)) (2.4.0)
Requirement already satisfied: python-dateutil==2.8.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 174)) (2.8.2) Requirement already satisfied: pytz==2022.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 178)) (2022.1)
Requirement already satisfied: pyyaml==6.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 182)) (6.0)
Requirement already satisfied: readme-renderer==34.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 187)) (34.0)
Requirement already satisfied: requests==2.27.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 189)) (2.27.1)
Requirement already satisfied: requests-toolbelt==0.9.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 196)) (0.9.1)
Requirement already satisfied: rfc3986==1.5.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 198)) (1.5.0)
Requirement already satisfied: s3transfer==0.5.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 200)) (0.5.2)
Requirement already satisfied: six==1.16.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 202)) (1.16.0)
Requirement already satisfied: smmap==5.0.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 209)) (5.0.0)
Requirement already satisfied: snowballstemmer==2.2.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 211)) (2.2.0) Requirement already satisfied: sphinx==4.3.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 213)) (4.3.2)
Requirement already satisfied: sphinxcontrib-applehelp==1.0.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 215)) (1.0.2)
Requirement already satisfied: sphinxcontrib-devhelp==1.0.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 217)) (1.0.2)
Requirement already satisfied: sphinxcontrib-htmlhelp==2.0.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 219)) (2.0.0)
Requirement already satisfied: sphinxcontrib-jsmath==1.0.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 221)) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp==1.0.3 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 223)) (1.0.3)
Requirement already satisfied: sphinxcontrib-serializinghtml==1.1.5 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 225)) (1.1.5)
Requirement already satisfied: sqlalchemy-stubs==0.4 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 227)) (0.4)
Requirement already satisfied: toml==0.10.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 229)) (0.10.2)
Requirement already satisfied: tomli==1.2.3 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 233)) (1.2.3)
Requirement already satisfied: tqdm==4.63.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 240)) (4.63.1)
Requirement already satisfied: twine==3.6.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 242)) (3.6.0)
Requirement already satisfied: typing-extensions==4.1.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 244)) (4.1.1)
Requirement already satisfied: urllib3==1.26.9 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 248)) (1.26.9)
Requirement already satisfied: vcrpy==4.1.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 253)) (4.1.1)
Requirement already satisfied: virtualenv==20.14.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 255)) (20.14.0)
Requirement already satisfied: webencodings==0.5.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 257)) (0.5.1)
Requirement already satisfied: wheel==0.37.1 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 261)) (0.37.1)
Requirement already satisfied: wrapt==1.14.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 265)) (1.14.0)
Requirement already satisfied: yarl==1.7.2 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 269)) (1.7.2)
Requirement already satisfied: zipp==3.6.0 in .\github\flexget\lib\site-packages (from -r dev-requirements.txt (line 271)) (3.6.0)
Requirement already satisfied: typed-ast<2.0,>=1.4.0 in .\github\flexget\lib\site-packages (from astroid==2.11.2->-r dev-requirements.txt (line 9)) (1.4.3)
Requirement already satisfied: setuptools>=20.0 in .\github\flexget\lib\site-packages (from astroid==2.11.2->-r dev-requirements.txt (line 9)) (47.1.1)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1 in .\github\flexget\lib\site-packages (from keyring==23.4.1->-r dev-requirements.txt (line 103)) (0.2.0)
Requirement already satisfied: pip>=21.2 in .\github\flexget\lib\site-packages (from pip-tools==6.4.0->-r dev-requirements.txt (line 132)) (22.0.4)
Obtaining file:///./Flexget
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pynzb==0.1.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.1.0)
Requirement already satisfied: greenlet==1.1.2 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.1.2)
Requirement already satisfied: html5lib==1.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.1)
Requirement already satisfied: psutil==5.9.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (5.9.0)
Requirement already satisfied: requests==2.27.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.27.1)
Requirement already satisfied: zc-lockfile==2.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.0)
Requirement already satisfied: jaraco-classes==3.2.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.2.1)
Requirement already satisfied: pygments==2.11.2 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.11.2)
Requirement already satisfied: six==1.16.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.16.0)
Requirement already satisfied: tzlocal==4.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (4.1)
Requirement already satisfied: beautifulsoup4==4.10.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (4.10.0)
Requirement already satisfied: babelfish==0.6.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.6.0)
Requirement already satisfied: plumbum==1.7.2 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.7.2)
Requirement already satisfied: tempora==4.1.2 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (4.1.2)
Requirement already satisfied: colorama==0.4.4 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.4.4)
Requirement already satisfied: flask-cors==3.0.10 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.0.10)
Requirement already satisfied: jaraco-text==3.7.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.7.0)
Requirement already satisfied: loguru==0.6.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.6.0)
Requirement already satisfied: werkzeug==2.0.3 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.0.3)
Requirement already satisfied: idna==3.3 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.3)
Requirement already satisfied: jaraco-collections==3.4.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.4.0)
Requirement already satisfied: guessit==3.4.3 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.4.3)
Requirement already satisfied: pyyaml==6.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (6.0)
Requirement already satisfied: feedparser==6.0.8 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (6.0.8)
Requirement already satisfied: pytz-deprecation-shim==0.1.0.post0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.1.0.post0)
Requirement already satisfied: aniso8601==9.0.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (9.0.1)
Requirement already satisfied: flask-restx==0.5.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.5.1)
Requirement already satisfied: click==8.0.4 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (8.0.4)
Requirement already satisfied: cherrypy==18.6.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (18.6.1)
Requirement already satisfied: jsonschema==3.2.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.2.0)
Requirement already satisfied: pyrss2gen==1.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.1)
Requirement already satisfied: pytz==2022.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2022.1)
Requirement already satisfied: markupsafe==2.0.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.0.1)
Requirement already satisfied: tzdata==2022.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2022.1)
Requirement already satisfied: brotli==1.0.9 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.0.9)
Requirement already satisfied: pyparsing==3.0.7 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.0.7)
Requirement already satisfied: zxcvbn-python==4.4.24 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (4.4.24)
Requirement already satisfied: rebulk==3.1.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.1.0)
Requirement already satisfied: itsdangerous==2.0.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.0.1)
Requirement already satisfied: sqlalchemy==1.4.32 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.4.32)
Requirement already satisfied: cheroot==8.6.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (8.6.0)
Requirement already satisfied: sgmllib3k==1.0.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.0.0)
Requirement already satisfied: rich==12.0.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (12.0.1)
Requirement already satisfied: soupsieve==2.3.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.3.1)
Requirement already satisfied: attrs==21.4.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (21.4.0)
Requirement already satisfied: flask==2.0.3 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.0.3)
Requirement already satisfied: apscheduler==3.9.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.9.1)
Requirement already satisfied: commonmark==0.9.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.9.1)
Requirement already satisfied: flask-restful==0.3.9 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.3.9)
Requirement already satisfied: pyrsistent==0.18.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.18.0)
Requirement already satisfied: portend==3.0.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.0.0)
Requirement already satisfied: charset-normalizer==2.0.12 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.0.12)
Requirement already satisfied: jinja2==3.0.3 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.0.3)
Requirement already satisfied: flask-login==0.5.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.5.0)
Requirement already satisfied: python-dateutil==2.8.2 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2.8.2)
Requirement already satisfied: jaraco-context==4.1.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (4.1.1)
Requirement already satisfied: flask-compress==1.11 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.11)
Requirement already satisfied: rpyc==5.0.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (5.0.1)
Requirement already satisfied: urllib3==1.26.9 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (1.26.9)
Requirement already satisfied: webencodings==0.5.1 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (0.5.1)
Requirement already satisfied: jaraco-functools==3.4.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (3.4.0)
Requirement already satisfied: certifi==2021.10.8 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (2021.10.8)
Requirement already satisfied: more-itertools==8.12.0 in .\github\flexget\lib\site-packages (from FlexGet==3.3.6) (8.12.0)
Requirement already satisfied: setuptools>=0.7 in .\github\flexget\lib\site-packages (from apscheduler==3.9.1->FlexGet==3.3.6) (47.1.1)
Requirement already satisfied: pywin32>=227 in .\github\flexget\lib\site-packages (from cherrypy==18.6.1->FlexGet==3.3.6) (227)
Requirement already satisfied: importlib-metadata in .\github\flexget\lib\site-packages (from click==8.0.4->FlexGet==3.3.6) (4.8.3)
Requirement already satisfied: importlib-resources in .\github\flexget\lib\site-packages (from guessit==3.4.3->FlexGet==3.3.6) (5.2.2)
Requirement already satisfied: win32-setctime>=1.0.0 in .\github\flexget\lib\site-packages (from loguru==0.6.0->FlexGet==3.3.6) (1.0.1)
Requirement already satisfied: backports.zoneinfo in .\github\flexget\lib\site-packages (from pytz-deprecation-shim==0.1.0.post0->FlexGet==3.3.6) (0.2.1)
Requirement already satisfied: typing-extensions<5.0,>=3.7.4 in .\github\flexget\lib\site-packages (from rich==12.0.1->FlexGet==3.3.6) (4.1.1)

Requirement already satisfied: zipp>=0.5 in .\github\flexget\lib\site-packages (from importlib-metadata->click==8.0.4->FlexGet==3.3.6) (3.6.0)

Installing collected packages: FlexGet
  Attempting uninstall: FlexGet
    Found existing installation: FlexGet 3.3.6
    Uninstalling FlexGet-3.3.6:
      WARNING: Cannot remove entries from nonexistent file .\github\flexget\lib\site-packages\easy-install.pth
      Successfully uninstalled FlexGet-3.3.6
  Running setup.py develop for FlexGet
Successfully installed FlexGet
Traceback (most recent call last):
  File ".\GitHub\Flexget\Scripts\flexget-script.py", line 33, in <module>
    sys.exit(load_entry_point('FlexGet', 'console_scripts', 'flexget')())
  File ".\GitHub\Flexget\Scripts\flexget-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File ".\GitHub\Flexget\lib\site-packages\importlib_metadata\__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File ".\GitHub\Flexget\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\GitHub\Flexget\flexget\__init__.py", line 11, in <module>
    from flexget.manager import Manager  # noqa
  File ".\GitHub\Flexget\flexget\manager.py", line 38, in <module>
    from flexget.config_schema import ConfigError
  File ".\GitHub\Flexget\flexget\config_schema.py", line 15, in <module>
    from flexget.utils import qualities, template
  File ".\GitHub\Flexget\flexget\utils\qualities.py", line 8, in <module>
    from flexget.utils.serialization import Serializer
  File ".\GitHub\Flexget\flexget\utils\serialization.py", line 8, in <module>
    from flexget.utils import json
  File ".\GitHub\Flexget\flexget\utils\json.py", line 12, in <module>
    from flexget.plugin import DependencyError
  File ".\GitHub\Flexget\flexget\plugin.py", line 12, in <module>
    import pkg_resources
  File ".\GitHub\Flexget\lib\site-packages\pkg_resources\__init__.py", line 3261, in <module>
    @_call_aside
  File ".\GitHub\Flexget\lib\site-packages\pkg_resources\__init__.py", line 3245, in _call_aside
    f(*args, **kwargs)
  File ".\GitHub\Flexget\lib\site-packages\pkg_resources\__init__.py", line 3274, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File ".\GitHub\Flexget\lib\site-packages\pkg_resources\__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File ".\GitHub\Flexget\lib\site-packages\pkg_resources\__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File ".\GitHub\Flexget\lib\site-packages\pkg_resources\__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zc-lockfile==2.0' distribution was not found and is required by FlexGet
```
</details>

### Additional information:

- FlexGet version: 3.5.5-6
- Python version: 3.7
- Installation method: git
- Using daemon (yes/no): Trying to
- OS and version: W10
- Link to crash log: N/A

**Comment by TauPan** [comment]
requirement was changed to zc-lockfile again in 2f4dd25282bbd1edfe13fcfd4abe6e6013eae93f causing the same error.

**Comment by grr** [comment]
2f4dd25282bbd1edfe13fcfd4abe6e6013eae93f reverted the fixes and broke the dependencies again.

**Comment by aidan-** [comment]
The issue isn't really with the `requirements.in` but with your version of `setuptools`.  There were some awkward changes to how packages with `.`'s were handled which are now resolved in newer versions.

**Comment by paranoidi** [comment]
Yeah, the instructions have been updated to include upgrading setuptools along with pip

**Comment by gazpachoking** [comment]
This was a change that happened in pypi and setuptools. A recent version of
setuptools is now required for install
