### ISSUE TITLE
Task scheduler and UI manual task execution not working starting v3.3.6

### ISSUE THREAD

**Issue by jeanfabrice** [Flexget/Flexget#3423]
### Expected behaviour:

Flexget UI & Daemon able to launch tasks either manually or via scheduler

### Steps to reproduce:
- Build Docker image with Dockerfile from v3.3.5 GitHub tag
- Configure UI password and run container with `flexget daemon start` and a simple configuration
- Access UI > tasks, select an existing task and  execute 'Now'.
- Task is being executed and UI shows: `Current Status: complete Phase: Finished - status`
- In the meantime, scheduler is never executed
- Running `flexget execute` from the CLI works as expected

Do the same with image v3.3.6 with Dockerfile from v3.3.6 GitHub tag
- Task gets stuck in queue, UI shows: `Current Status: Phase: Processing -`
- Homepage, Tasks panel shows: `1 in Queue`
- Scheduler is executed according to config

#### Config:

```yaml
---
schedules:
- tasks: '*'
  interval:
    hours: 1
tasks:
  CleanTransmission:
    disable:
    - seen
    - seen_info_hash
    from_transmission:
      host: transmission.transmission
      port: 9091
    if:
    - transmission_progress == 100: accept
    - not transmission_seed_ratio_ok: reject
    - not transmission_idle_limit_ok: reject
    transmission:
      action: remove
      host: transmission.transmission
      port: 9091
templates:
  series:
    thetvdb_lookup: true
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes
  base_url: /


```
  
#### Log:
v3.3.6 non working logs:
<details>
 <summary>v3.3.6 (click to expand)</summary>

```
flexget-d9558949c-6fvcv flexget 2022-04-25 14:38:04 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
flexget-d9558949c-6fvcv flexget 2022-04-25 14:38:04 INFO     web_server_daemon                 Initiating API
flexget-d9558949c-6fvcv flexget 2022-04-25 14:38:04 INFO     web_server_daemon                 Registering WebUI v2
flexget-d9558949c-6fvcv flexget /usr/local/lib/python3.9/site-packages/tzlocal/unix.py:177: UserWarning: Can not find any timezone configuration, defaulting to UTC.
flexget-d9558949c-6fvcv flexget   warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
flexget-d9558949c-6fvcv flexget Traceback (most recent call last):
flexget-d9558949c-6fvcv flexget   File "/usr/local/bin/flexget", line 8, in <module>
flexget-d9558949c-6fvcv flexget     sys.exit(main())
flexget-d9558949c-6fvcv flexget   File "/usr/local/lib/python3.9/site-packages/flexget/__init__.py", line 44, in main
flexget-d9558949c-6fvcv flexget 2022-04-25 14:38:04 INFO     web_server                    Web server started at http://10.233.121.60:5050
flexget-d9558949c-6fvcv flexget     manager.start()
flexget-d9558949c-6fvcv flexget   File "/usr/local/lib/python3.9/site-packages/flexget/manager.py", line 383, in start
flexget-d9558949c-6fvcv flexget     self.handle_cli()
flexget-d9558949c-6fvcv flexget   File "/usr/local/lib/python3.9/site-packages/flexget/manager.py", line 409, in handle_cli
flexget-d9558949c-6fvcv flexget 2022-04-25 14:38:04 INFO     web_server                    API available at http://10.233.121.60:5050/api
flexget-d9558949c-6fvcv flexget     self.daemon_command(command_options)
flexget-d9558949c-6fvcv flexget   File "/usr/local/lib/python3.9/site-packages/flexget/manager.py", line 506, in daemon_command
flexget-d9558949c-6fvcv flexget     run_daemon()
flexget-d9558949c-6fvcv flexget   File "/usr/local/lib/python3.9/site-packages/flexget/manager.py", line 487, in run_daemon
flexget-d9558949c-6fvcv flexget     fire_event('manager.daemon.started', self)
flexget-d9558949c-6fvcv flexget   File "/usr/local/lib/python3.9/site-packages/flexget/event.py", line 109, in fire_event
flexget-d9558949c-6fvcv flexget 2022-04-25 14:38:04 INFO     web_server                    WebUI (v2) available at http://10.233.121.60:5050/
flexget-d9558949c-6fvcv flexget     result = event(*args, **kwargs)
flexget-d9558949c-6fvcv flexget   File "/usr/local/lib/python3.9/site-packages/flexget/event.py", line 20, in __call__
flexget-d9558949c-6fvcv flexget     return self.func(*args, **kwargs)
flexget-d9558949c-6fvcv flexget   File "/usr/local/lib/python3.9/site-packages/flexget/components/scheduler/scheduler.py", line 129, in setup_scheduler
flexget-d9558949c-6fvcv flexget     if timezone.zone == 'local':
flexget-d9558949c-6fvcv flexget AttributeError: 'datetime.timezone' object has no attribute 'zone'
```
</details>

v3.3.5 working logs:
<details>
 <summary>v3.3.5 (click to expand)</summary>

```
flexget-768cc7d7bc-dn8hm flexget 2022-04-25 14:36:42 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
flexget-768cc7d7bc-dn8hm flexget 2022-04-25 14:36:42 INFO     web_server_daemon                 Initiating API
flexget-768cc7d7bc-dn8hm flexget 2022-04-25 14:36:42 INFO     web_server_daemon                 Registering WebUI v2
flexget-768cc7d7bc-dn8hm flexget /usr/local/lib/python3.9/site-packages/tzlocal/unix.py:158: UserWarning: Can not find any timezone configuration, defaulting to UTC.
flexget-768cc7d7bc-dn8hm flexget   warnings.warn('Can not find any timezone configuration, defaulting to UTC.')
flexget-768cc7d7bc-dn8hm flexget 2022-04-25 14:36:42 INFO     web_server                    Web server started at http://10.233.121.82:5050
flexget-768cc7d7bc-dn8hm flexget 2022-04-25 14:36:42 INFO     scheduler                     Starting scheduler
flexget-768cc7d7bc-dn8hm flexget 2022-04-25 14:36:42 INFO     web_server                    API available at http://10.233.121.82:5050/api
flexget-768cc7d7bc-dn8hm flexget 2022-04-25 14:36:42 INFO     web_server                    WebUI (v2) available at http://10.233.121.82:5050/
```
</details>

### Additional information:

- FlexGet version: 3.3.6 (and above)
- Python version: Python 3.9.10
- Installation method: Container with Docker images built using upstream  Github Dockerfile
- Using daemon (yes/no): yes
- OS and version: 
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by dylanratcliffe** [comment]
Same issue here using the docker image `wiserain/flexget`, downgrading to 3.3.4 works immediately
