### ISSUE TITLE
BUG: Unhandled error in plugin torrent_files: sequence item 1: expected str instance, bytes found

### ISSUE THREAD

**Issue by MewX** [Flexget/Flexget#3427]
### Expected behaviour:

The path should be a string not a byte sequence.

### Actual behaviour:

Crashes during the "torrent_files" stage.

### Steps to reproduce:

Downloading rss from a certain site?

#### Config:
```yaml
 xxxx:
    rss: https://......
    accept_all: yes
    download:
      path: /root/path/to/downloads
      overwrite: no
      filename: "{{guid}}.torrent"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2022-04-29 19:57:34 CRITICAL task          xxxx            BUG: Unhandled error in plugin torrent_files: sequence item 1: expected str instance, bytes found
Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f38959833a0>
    └ <Thread(task_queue, started daemon 139880903853824)>
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f38959830d0>
    └ <Thread(task_queue, started daemon 139880903853824)>
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 139880903853824)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 139880903853824)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f388fc7be50>>
    └ <Thread(task_queue, started daemon 139880903853824)>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f38927da820>
    │    └ <flexget.task.Task object at 0x7f388f965cd0>
    └ <flexget.task_queue.TaskQueue object at 0x7f388fc7be50>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f388f965cd0>
           └ <function Task.execute at 0x7f38927da790>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 727, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f38927da700>
    └ <flexget.task.Task object at 0x7f388f965cd0>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 696, in _execute
    self.__run_task_phase(phase)
    │                     └ 'modify'
    └ <flexget.task.Task object at 0x7f388f965cd0>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f388f965cd0>, None)
               │                 │       └ 'modify'
               │                 └ <PluginInfo(name=torrent_files)>
               └ <flexget.task.Task object at 0x7f388f965cd0>

> File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7f388f965cd0>, None)
             └ <Event(name=plugin.torrent_files.modify,func=on_task_modify,priority=200)>

  File "/usr/local/lib/python3.9/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7f388f965cd0>, None)
           │    └ <bound method TorrentFiles.on_task_modify of <flexget.components.bittorrent.torrent_files.TorrentFiles object at 0x7f388fcfd1...
           └ <Event(name=plugin.torrent_files.modify,func=on_task_modify,priority=200)>

  File "/usr/local/lib/python3.9/dist-packages/flexget/components/bittorrent/torrent_files.py", line 20, in on_task_modify
    for item in entry['torrent'].get_filelist()
                └ <Entry(title=Sayika.ArtWorks.2019.-.2022.04.Collection.PICS&Anime&Game,state=accepted)>

  File "/usr/local/lib/python3.9/dist-packages/flexget/utils/bittorrent.py", line 253, in get_filelist
    t = {'path': '/'.join(path[:-1]), 'name': path[-1], 'size': item['length']}
                          │                   │                 └ {'length': 4684848, 'path': ['Various Rewards', b'\xe3\x83\x97...
                          │                   └ ['Various Rewards', b'\xe3\x83\x97...', 'プ...
                          └ ['Various Rewards', b'\xe3\x83\x97...', 'プ...

TypeError: sequence item 1: expected str instance, bytes found
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flexget/components/bittorrent/torrent_files.py", line 20, in on_task_modify
    for item in entry['torrent'].get_filelist()
  File "/usr/local/lib/python3.9/dist-packages/flexget/utils/bittorrent.py", line 253, in get_filelist
    t = {'path': '/'.join(path[:-1]), 'name': path[-1], 'size': item['length']}
TypeError: sequence item 1: expected str instance, bytes found
```
</details>

### Additional information:

- FlexGet version: 3.3.8
- Python version: 3.9.2
- Installation method: pip install -g
- Using daemon (yes/no): no
- OS and version: debian 10
- Link to crash log: N/A

**Comment by yanyuechuixue** [comment]
Same error, looking for help

**Comment by paranoidi** [comment]
Disabling builtin `torrent_files` is a viable workaround if not using what it provides (torrent content information). We would need an example of problematic torrent, and it should be legal to provide to investigate this.
