### ISSUE TITLE
Lazy lookup error 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#3432]
### Expected behaviour:
Task to run, match and fill Metadata 

### Actual behaviour:
Tasks run fine, but crashes while importing Metadata 
### Steps to reproduce:
- Step 1: ...
Run task
#### Config:
```yaml
web_server: yes
variables: secret.yml
templates:
  global:
    no_entries_ok: yes
    notify:
      abort:
        via:
          - telegram:
              bot_token: '{? telegram.token ?}'
              parse_mode: markdown
              disable_previews: no
              recipients:
                - username: '{? telegram.usr ?}'

##################################################################
#   MOVIE TEMPLATE
##################################################################

  movie:
    tmdb_lookup: yes 
    imdb_lookup: yes
    proper_movies: no
#    content_size:
#      max: 5000
#      strict: no
    content_filter:
      require:
        -  '*.mkv'
        -  '*.mp4'
        -  '*.avi'
      reject:
        - '*.zip'
#        - '*.avi'
        - '*.wmv'
        - '*.wma'
        - '*[cC]odec*'
        - '*[rR]eadme*'
#        - '*.txt'
#    exists_movie:
#      - /media/CHEWYHDD/CHEWY/Videos/Movies
#      - /media/CHEWYHDD/CHEWY/Videos/Addison/Addison Movies


#################################################################
#    FILTERS TEMPLATES
##################################################################

  filters:
    regexp:
      reject:
        - \bmsd\b: {from: title}
        - \bwmv\b: {from: title}
        - \bLatino\b: {from: title}
        - \btrailer\b: {from: title}
        - \bHDTC\b: {from: title} 
        - \bHDTS\b: {from: title}
        - \bHQTS\b: {from: title}
        - \bHDcam\b: {from: title} 
        - \bR5\b: {from: title}
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}                              # The following are groups with poor quality releases
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \bFLEET\b: {from: title}
        - \b0SEC\b: {from: title}
        - \[facepalm\]: {from: title}
        - FASTSUB: {from: title}
        - VOSTFR: {from: title}
        - Subtitulado: {from: title}
        - \bNORDiC\b: {from: title}
        - \biPad\b: {from: title}
#        - \b(ita|ger|fra|spa|swe|nor|nordic|fr|kor|uk|esp|nl|pl|spanish)\b: {from: title}
        - \bR6\b: {from: title}
        - \bTemporada\b: {from: title}
        - \bDual\b: {from: title}
        - \bTamil*\b: {from: title}
#        - \bJapanese\b: {from: title}
        - \bJajji!\b: {from: title}
#        - \HC\b: {from: title}
        - \b480p\b: {from: title}
        - \b.TamilRock*\b: {from: title}
        - \b1xbet\b: {from: title}
        - \bCAMRip\b: {from: title}
        - \bHDCAMRip\b: {from: title}


##################################################################
#    TASK SCHEDULES
##################################################################


schedules:

  - tasks: IMDB
    interval:
      minutes: 30

  - tasks: movies
    interval:
      hours: 1


##################################################################
#    TASKS 
##################################################################


tasks:

  IMDB:
    cfscraper: yes
    seen_info_hash: local
    imdb_list:
      login: '{? imdb.usr ?}'
      cookies: '{? imdb.cookie ?}'
      list: watchlist
    accept_all: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    list_add:
      - movie_list: movies
    priority: 2

  
  movies:
    priority: 5
    cfscraper: yes
    seen_info_hash: local
    template:
      - movie
      - telegram_notify
      - filters
    discover:
      release_estimations: ignore
#        optimistic: 90 days
      what:
        - movie_list: movies
      from:
        - yts: yes
        - rarbg:
            category: [14, 15, 16, 17, 21, 22, 42, 44, 45, 46, 47, 48]
        - 1337x: yes
#        - piratebay:
#            category: movies
    interval: 1 hour
    quality: 1080p
#    torrent_alive: 5
    list_match:
      from:
        - movie_list: movies
    list_add:
      - entry_list: downloaded_movies
    list_remove:
      - imdb_list:
          login: '{? imdb.usr ?}'
          cookies: '{? imdb.cookie ?}'
          list: watchlist
    verify_ssl_certificates: no
    set:
      path: /media/CHEWYHDD/CHEWY/Videos/temp
      move_completed_path: /media/CHEWYHDD/CHEWY/Videos/Movies/
    deluge:
      host: localhost
      port: '{? deluge.port ?}'
      username: '{? deluge.usr ?}'
      password: '{? deluge.pwd ?}'
      ratio: .01
      label: Public      


```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2022-04-10 16:19:15 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO imdb_search (title, url, fails, queried) VALUES (?, ?, ?, ?)]
[parameters: ('Deliver Us from Evil (2014) 1080p BrRip x264 - YIFY', 'https://www.imdb.com/title/tt2377322/', 0, '2022-04-10 16:19:05.391262')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/lazy_dict.py", line 41, in __getitem__
    callee.func(self.store, *(callee.args or []), **(callee.kwargs or {}))
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/components/imdb/imdb_lookup.py", line 69, in lazy_loader
    self.lookup(entry)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/plugin.py", line 126, in wrapped_func
    return func(*args, **kwargs)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/flexget/lib/python3.7/site-packages/flexget/components/imdb/imdb_lookup.py", line 183, in lookup
    session.commit()
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 633, in execute
    uow,
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 249, in save_obj
    insert,
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1240, in _emit_insert_statements
    execution_options=execution_options,
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1620, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1497, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1852, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2033, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/flexget/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO imdb_search (title, url, fails, queried) VALUES (?, ?, ?, ?)]
[parameters: ('Deliver Us from Evil (2014) 1080p BrRip x264 - YIFY', 'https://www.imdb.com/title/tt2377322/', 0, '2022-04-10 16:19:05.391262')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```
</details>

### Additional information:

- FlexGet version: 3.3.8
- Python version: 3.7.3
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: raspbian buster
- Link to crash log:

**Comment by gazpachoking** [comment]
Hmm. I wonder why the traceback doesn't go back far enough to show us what was causing the lazy lookup. What are the log lines that immediately precede the error?

**Comment by chewy74** [comment]
> Hmm. I wonder why the traceback doesn't go back far enough to show us what was causing the lazy lookup. What are the log lines that immediately precede the error?

Here is the complete crash log
https://www.dropbox.com/s/69lyhvx7cdxm27w/crash_report.2022.05.14.134253706011.log?dl=0

**Comment by gazpachoking** [comment]
Oh, that's a totally different error. And probably one that's easier to debug and fix.

**Comment by chewy74** [comment]
> Oh, that's a totally different error. And probably one that's easier to debug and fix.

I don't think that was the correct log for the reoccurring crashes I've been getting.

I think this is the correct one
https://www.dropbox.com/s/usnwjqwnzrdcdbn/crash_report.2022.05.14.221641075722.log?dl=0

Sorry for the confusion

**Comment by crawln45** [comment]
@chewy74 that's basically the same error. Duplicate entries for posters is what it looks like.

**Comment by chewy74** [comment]
Ahhh OK thanks for the clarification

**Comment by chewy74** [comment]
Getting way less crash logs, but still getting some

**Comment by chewy74** [comment]
Seems to have been resolved. Thanks
