### ISSUE TITLE
Unable to start flexget after installing the development requirements because pyparsing version conflict

### ISSUE THREAD

**Issue by shadycuz** [Flexget/Flexget#3479]
### Expected behaviour:

I'm able to start flexget while developing new features without errors about package dependnecies. 

### Actual behaviour:

```
(.venv) vscode@16590719adec:/workspaces/Flexget$ flexget --help
Traceback (most recent call last):
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyparsing 3.0.7 (/workspaces/Flexget/.venv/lib/python3.9/site-packages), Requirement.parse('pyparsing==2.4.7'), {'FlexGet'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/Flexget/.venv/bin/flexget", line 33, in <module>
    sys.exit(load_entry_point('FlexGet', 'console_scripts', 'flexget')())
  File "/workspaces/Flexget/.venv/bin/flexget", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/vscode/.pyenv/versions/3.9.12/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/vscode/.pyenv/versions/3.9.12/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/workspaces/Flexget/flexget/__init__.py", line 11, in <module>
    from flexget.manager import Manager  # noqa
  File "/workspaces/Flexget/flexget/manager.py", line 38, in <module>
    from flexget.config_schema import ConfigError
  File "/workspaces/Flexget/flexget/config_schema.py", line 15, in <module>
    from flexget.utils import qualities, template
  File "/workspaces/Flexget/flexget/utils/qualities.py", line 8, in <module>
    from flexget.utils.serialization import Serializer
  File "/workspaces/Flexget/flexget/utils/serialization.py", line 8, in <module>
    from flexget.utils import json
  File "/workspaces/Flexget/flexget/utils/json.py", line 12, in <module>
    from flexget.plugin import DependencyError
  File "/workspaces/Flexget/flexget/plugin.py", line 12, in <module>
    import pkg_resources
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/workspaces/Flexget/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyparsing==2.4.7' distribution was not found and is required by FlexGet
```

### Steps to reproduce:
- Step 1: Create a virtual environment  
```
python3 -m venv .venv
```
- Step 2: Activate it
```
. .venv/bin/activate
```
- Step 3: Install flexget according to the developer [getting started guide](https://flexget.readthedocs.io/en/latest/develop/index.html#how-do-i-get-started).
```
pip3 install -e .
```
- Step 4: Install the developer requirements according to the getting started guide.
```
pip3 install -r dev-requirements.txt
```
- Step 5. Try to run flexget
```
flexget --help
```

#### Config:
N/A
  
#### Log:
N/A

### Additional information:

- FlexGet version: Master branch
- Python version: 3.9
- Installation method: Devcontainer #3478 
- Using daemon (yes/no): not sure
- OS and version: Ubuntu 20.04
- Link to crash log: Pasted Above

From what I can see the `dev-requirements.txt` shows this:
```
pyparsing==3.0.7
    # via
    #   -c requirements.txt
    #   packaging
```

But I dont see packaging in any of the `requirements.txt` or `.in` files. 

It is however further up in the `dev-requirements.txt` file:
```
packaging==21.3
    # via
    #   bleach
    #   pytest
    #   sphinx
```

**Comment by gazpachoking** [comment]
New dependency management should take care of this from now on
