### ISSUE TITLE
dependency colorama missing

### ISSUE THREAD

**Issue by amefs** [Flexget/Flexget#3499]
### Description
missing `colorama` on v3.3.20

### Steps to reproduce:
- install flexget using pip command
```
pip install flexget
```
- run version check
```
flexget -V
```
### Log:
<details>
 <summary> ModuleNotFoundError: No module named 'colorama' (click to expand)</summary>

```
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 6, in <module>
    from flexget import main
  File "/usr/local/lib/python3.9/site-packages/flexget/__init__.py", line 10, in <module>
    from flexget import log  # noqa
  File "/usr/local/lib/python3.9//site-packages/flexget/log.py", line 15, in <modul>
    import colorama
ModuleNotFoundError: No module named 'colorama'
```
</details>

**Comment by ksurl** [comment]
Same issue here. I confirmed `pip-compile` on the current version of `requirements.in` excludes `colorama` from `requirements.txt`. Is this an upstream issue?
