### ISSUE TITLE
from_piratebay plugin needs update

### ISSUE THREAD

**Issue by redchilis** [Flexget/Flexget#3538]
https://www.flexget.com/Plugins/from_piratebay

Example:
```
from_piratebay:
  category: HD - Movies
```
The above, works fine, however, if any customization is added, like below
```
from_piratebay:
  url: https://apibay.org
  category: HD - Movies
  list: top
  rank: all
```
The plugin crashes. Using any of the given options of 'list' and 'rank' causes a crash.

From my limited knowledge I've gathered, the plugin is looking for the object 'member' however in thepiratebay the object is currently being referred to as 'user'

crash report is below:
[https://pastebin.com/raw/XX74Xh2g](https://pastebin.com/raw/XX74Xh2g)

**Comment by paranoidi** [comment]
Your example is working correctly. Maybe something was broken server side?

**Comment by redchilis** [comment]
try

```
    from_piratebay:
      category: HD - Movies
      list: recent
      rank: trusted
```

it fails, running latest flexget 3.3.33

```
2022-10-10 07:32:17 CRITICAL task          magnet          BUG: Unhandled error in plugin from_piratebay: 'member' is not in list
Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f378337ee50>
    └ <Thread(task_queue, started daemon 139876299486976)>
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f378337eb80>
    └ <Thread(task_queue, started daemon 139876299486976)>
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 139876299486976)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 139876299486976)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f377d562e50>>
    └ <Thread(task_queue, started daemon 139876299486976)>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f3780360160>
    │    └ <flexget.task.Task object at 0x7f377d2663a0>
    └ <flexget.task_queue.TaskQueue object at 0x7f377d562e50>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f377d2663a0>
           └ <function Task.execute at 0x7f37803600d0>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 727, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f3780360040>
    └ <flexget.task.Task object at 0x7f377d2663a0>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 696, in _execute
    self.__run_task_phase(phase)
    │                     └ 'input'
    └ <flexget.task.Task object at 0x7f377d2663a0>

  File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f377d2663a0>, {'category': 'HD - Movies', 'list': 'recent', 'rank': 'trusted', 'url': 'https...
               │                 │       └ 'input'
               │                 └ <PluginInfo(name=from_piratebay)>
               └ <flexget.task.Task object at 0x7f377d2663a0>

> File "/usr/local/lib/python3.9/dist-packages/flexget/task.py", line 550, in __run_plugin
    result = list(result)
                  └ <generator object FromPirateBay.on_task_input at 0x7f3777b60510>

  File "/usr/local/lib/python3.9/dist-packages/flexget/plugins/input/from_piratebay.py", line 162, in on_task_input
    if RANKS.index(result['status'].lower()) < rank:
       │     │     │                           └ 2
       │     │     └ {'id': '62993565', 'name': 'Lobos de Guerra (2022) 720p WEB-DL [Dublado Portugues] MOSTBET', 'info_hash': '1F790B19BB7E9E3DDE...
       │     └ <method 'index' of 'list' objects>
       └ ['all', 'user', 'trusted', 'vip', 'helper', 'moderator', 'supermod']

ValueError: 'member' is not in list
2022-10-10 07:32:17 CRITICAL manager       magnet          An unexpected crash has occurred. Writing crash report to /home/red/.config/flexget/crash_report.2022.10.10.073217587547.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.3.33
2022-10-10 07:32:17 WARNING  task          magnet          Aborting task (plugin: from_piratebay)
```
