### ISSUE TITLE
Crash during daemon scheduled task

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/Flexget#3562]
### Description:
Daemon tried to run a task marked as `manual: yes` and the task crashed.
I have several tasks with the `-discover` suffix and recently marked one of them as manual. The daemon has been stopped and restarted several times since then, so shouldn't be a persistence issue.

#### Config:
```yaml
schedules:
  - tasks:
      - '*-discover'
    schedule:
      hour: '1-23/2'

tasks:
  download-anime-series-discover:
    priority: 150
    manual: yes
    template:
      - anime-series
      - anime-reject
      - torrents
      - torrent-anime-series
      - series-guessit
    magnets: yes
    convert_magnet: no
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - next_series_episodes:
            from_start: yes
            backfill: no
        - entry_list: anime-series
      from:
        - nyaa: anime eng
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2022-10-10 17:04:13 DEBUG    log_filter    download-anime-series-discover Log filter added (config: [{'message': 'too small', 'task': 'download-anime-series-discover'}, {'message': 'New quality', 'task': 'download-anime-series-discover'}, {'message': 'is already configured in series plugin', 'task': 'download-anime-series-discover'}])
2022-10-10 17:04:13 DEBUG    manual        download-anime-series-discover Disabling task download-anime-series-discover, task can only run in manual mode (via API/CLI)
2022-10-10 17:04:13 DEBUG    task          download-anime-series-discover Aborting task (plugin: manual)
2022-10-10 17:04:13 DEBUG    p_priority    download-anime-series-discover nothing changed, aborting restore
2022-10-10 17:04:13 DEBUG    sequence      download-anime-series-discover Running plugin notify
2022-10-10 17:04:13 DEBUG    sequence      download-anime-series-discover Running plugin notify
2022-10-10 17:04:13 CRITICAL task          download-anime-series-discover BUG: Unhandled error in plugin parsing: pop from empty list
Traceback (most recent call last):

  File "<repo_clone>\flexget\task.py", line 696, in _execute
    self.__run_task_phase(phase)
    │                     └ 'start'
    └ <flexget.task.Task object at 0x00000219CB612208>

  File "<repo_clone>\flexget\task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x00000219CB612208>, True)
               │                 │       └ 'start'
               │                 └ <PluginInfo(name=manual)>
               └ <flexget.task.Task object at 0x00000219CB612208>

  File "<repo_clone>\flexget\task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x00000219CB612208>, True)
             └ <Event(name=plugin.manual.start,func=on_task_start,priority=255)>

  File "<repo_clone>\flexget\event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x00000219CB612208>, True)
           │    └ <bound method ManualTask.on_task_start of <flexget.plugins.operate.manual.ManualTask object at 0x000002199B056048>>
           └ <Event(name=plugin.manual.start,func=on_task_start,priority=255)>

  File "<repo_clone>\flexget\plugins\operate\manual.py", line 29, in on_task_start
    task.abort('manual task not specified in --tasks', silent=True)
    │    └ <function Task.abort at 0x0000021996F3E0D8>
    └ <flexget.task.Task object at 0x00000219CB612208>

  File "<repo_clone>\flexget\task.py", line 422, in abort
    raise TaskAbort(reason, silent=silent)
          │         │              └ True
          │         └ 'manual task not specified in --tasks'
          └ <class 'flexget.task.TaskAbort'>

flexget.task.TaskAbort: manual task not specified in --tasks


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\python37\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000021993DFD9D8>
    └ <Thread(task_queue, started daemon 12952)>

  File "c:\python37\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000021993DFD798>
    └ <Thread(task_queue, started daemon 12952)>

  File "c:\python37\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 12952)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 12952)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x000002199B338908>>
    └ <Thread(task_queue, started daemon 12952)>

  File "<repo_clone>\flexget\task_queue.py", line 47, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x0000021996F3E708>
    │    └ <flexget.task.Task object at 0x00000219CB612208>
    └ <flexget.task_queue.TaskQueue object at 0x000002199B338908>

  File "<repo_clone>\flexget\task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x00000219CB612208>
           └ <function Task.execute at 0x0000021996F3E678>

  File "<repo_clone>\flexget\task.py", line 727, in execute
    self._execute()
    │    └ <function Task._execute at 0x0000021996F3E5E8>
    └ <flexget.task.Task object at 0x00000219CB612208>

  File "<repo_clone>\flexget\task.py", line 702, in _execute
    self.__run_task_phase('abort')
    └ <flexget.task.Task object at 0x00000219CB612208>

  File "<repo_clone>\flexget\task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x00000219CB612208>, {'series': 'guessit'})
               │                 │       └ 'abort'
               │                 └ <PluginInfo(name=parsing)>
               └ <flexget.task.Task object at 0x00000219CB612208>

> File "<repo_clone>\flexget\task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x00000219CB612208>, {'series': 'guessit'})
             └ <Event(name=plugin.parsing.abort,func=on_task_exit,priority=128)>

  File "<repo_clone>\flexget\event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x00000219CB612208>, {'series': 'guessit'})
           │    └ <bound method PluginParsing.on_task_exit of <flexget.components.parsing.plugin_parsing.PluginParsing object at 0x0000021999D8...
           └ <Event(name=plugin.parsing.abort,func=on_task_exit,priority=128)>

  File "<repo_clone>\flexget\components\parsing\plugin_parsing.py", line 63, in on_task_exit
    selected_parsers.pop()
    │                └ <method 'pop' of 'list' objects>
    └ []

IndexError: pop from empty list
Traceback (most recent call last):
  File "<repo_clone>\flexget\task.py", line 696, in _execute
    self.__run_task_phase(phase)
  File "<repo_clone>\flexget\task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
  File "<repo_clone>\flexget\task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
  File "<repo_clone>\flexget\event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "<repo_clone>\flexget\plugins\operate\manual.py", line 29, in on_task_start
    task.abort('manual task not specified in --tasks', silent=True)
  File "<repo_clone>\flexget\task.py", line 422, in abort
    raise TaskAbort(reason, silent=silent)
flexget.task.TaskAbort: manual task not specified in --tasks

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<repo_clone>\flexget\task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
  File "<repo_clone>\flexget\event.py", line 20, in __call__
    return self.func(*args, **kwargs)
  File "<repo_clone>\flexget\components\parsing\plugin_parsing.py", line 63, in on_task_exit
    selected_parsers.pop()
IndexError: pop from empty list

```
</details>

### Additional information:

- FlexGet version: 3.3.34
- Python version: 3.7
- Installation method: git
- Using daemon (yes/no): yes
- OS and version: W10

**Comment by Anian-igor** [comment]
I setup version 3.5.15
Schedules works fine on this version

**Comment by gazpachoking** [comment]
For posterity, this crash was fixed already. 5539691f991ebdb6930a9a2c1c3ca7a4fdd9a20d
