### ISSUE TITLE
Flexget crashes when restoring entries for my movie search that have passed delay

### ISSUE THREAD

**Issue by OmegaZero** [Flexget/Flexget#3620]
### Expected behaviour:

I guess restoring the entries for my movie search that have passed delay

### Actual behaviour:
It crashes

### Steps to reproduce:
flexget execute

#### Config:
[flexget bug.zip](https://github.com/Flexget/Flexget/files/10114460/flexget.bug.zip)
  
#### Log:
[flexget bug.zip](https://github.com/Flexget/Flexget/files/10114460/flexget.bug.zip)

**Relevant:**
2022-11-27 22:48:45 VERBOSE  delay         movie_search_720p Restoring 1020 entries that have passed delay.
2022-11-27 22:48:45 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Traceback (most recent call last):
  File "/home/pi/flexget/lib/python3.10/site-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
  File "/home/pi/flexget/lib/python3.10/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
  File "/home/pi/flexget/lib/python3.10/site-packages/flexget/task.py", line 727, in execute
    self._execute()
  File "/home/pi/flexget/lib/python3.10/site-packages/flexget/task.py", line 696, in _execute
    self.__run_task_phase(phase)
  File "/home/pi/flexget/lib/python3.10/site-packages/flexget/task.py", line 518, in __run_task_phase
    e.task = self
AttributeError: 'dict' object has no attribute 'task'

### Additional information:
Flexget Version 3.5.5
Python Version 3.10
Installation method: venv with pip by following the installation guide on the flexget website
Using daemon: no, I just use a cron
OS :  Raspbian buster

**Comment by OmegaZero** [comment]
This may go without saying but if I comment out 

delay: 5 weeks

under movie_search_720p then the error goes away. It's clearly some bug with the delay feature
