### ISSUE TITLE
Failure to connect to Transmission causes unhandled exception

### ISSUE THREAD

**Issue by mrnoname1000** [Flexget/Flexget#3839]
### Expected behaviour:
If connection to Transmission fails, log it somewhere and remove Transmission from the output plugins.

### Actual behaviour:
Logging the failure fails due to indexing something an empty tuple.

### Steps to reproduce:
1. Configure bogus transmission credentials and any task that will add a torrent
2. Run `flexget execute`

#### Config:
```yaml
tasks:
  test:
    transmission:  # make sure this is wrong
      host: localhost
      port: 9091
    # insert torrent task here
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2023-09-09 15:49:54 DEBUG    transmission  nyaa            Connecting to http://localhost:9091/transmission/
2023-09-09 15:49:54 CRITICAL task          nyaa            BUG: Unhandled error in plugin transmission: tuple index out of range
Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           │          └ <function create_connection at 0x7fb48c09e200>
           └ <module 'urllib3.util.connection' from '/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py'>
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
          └ ConnectionRefusedError(111, 'Connection refused')
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
    │            └ ('127.0.0.1', 9091)
    └ None

ConnectionRefusedError: [Errno 111] Connection refused


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fb48c112660>
                       └ <urllib3.connectionpool.HTTPConnectionPool object at 0x7fb484fcae50>
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
    │    │       │       │      └ {'body': b'{"tag": 0, "method": "session-get", "arguments": {}}', 'headers': {'User-Agent': 'python-requests/2.31.0', 'Accept...
    │    │       │       └ '/transmission/rpc'
    │    │       └ 'POST'
    │    └ <function HTTPConnection.request at 0x7fb48c0f9b20>
    └ <urllib3.connection.HTTPConnection object at 0x7fb484650350>
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
          │               │             │       │         │             └ {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive',...
          │               │             │       │         └ b'{"tag": 0, "method": "session-get", "arguments": {}}'
          │               │             │       └ '/transmission/rpc'
          │               │             └ 'POST'
          │               └ <urllib3.connection.HTTPConnection object at 0x7fb484650350>
          └ <class 'urllib3.connection.HTTPConnection'>
  File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
    │    │             │       │    │     │        └ False
    │    │             │       │    │     └ {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive',...
    │    │             │       │    └ b'{"tag": 0, "method": "session-get", "arguments": {}}'
    │    │             │       └ '/transmission/rpc'
    │    │             └ 'POST'
    │    └ <function HTTPConnection._send_request at 0x7fb48c22a700>
    └ <urllib3.connection.HTTPConnection object at 0x7fb484650350>
  File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
    │    │          │                    └ False
    │    │          └ b'{"tag": 0, "method": "session-get", "arguments": {}}'
    │    └ <function HTTPConnection.endheaders at 0x7fb48c22a5c0>
    └ <urllib3.connection.HTTPConnection object at 0x7fb484650350>
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    │    │            │                            └ False
    │    │            └ b'{"tag": 0, "method": "session-get", "arguments": {}}'
    │    └ <function HTTPConnection._send_output at 0x7fb48c22a160>
    └ <urllib3.connection.HTTPConnection object at 0x7fb484650350>
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
    │    │    └ b'POST /transmission/rpc HTTP/1.1\r\nHost: localhost:9091\r\nUser-Agent: python-requests/2.31.0\r\nAccept-Encoding: gzip, def...
    │    └ <function HTTPConnection.send at 0x7fb48c229f80>
    └ <urllib3.connection.HTTPConnection object at 0x7fb484650350>
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
    │    └ <function HTTPConnection.connect at 0x7fb48c0f9940>
    └ <urllib3.connection.HTTPConnection object at 0x7fb484650350>
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           │    └ <function HTTPConnection._new_conn at 0x7fb48c0f9760>
           └ <urllib3.connection.HTTPConnection object at 0x7fb484650350>
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
          └ <class 'urllib3.exceptions.NewConnectionError'>

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errno 111] Connection refused


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fb48c1128e0>
           └ <urllib3.connectionpool.HTTPConnectionPool object at 0x7fb484fcae50>
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fb48c0c47c0>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errn...
          │             │      └ '/transmission/rpc'
          │             └ <urllib3.connectionpool.HTTPConnectionPool object at 0x7fb484fcae50>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errno 111] Connection refused'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 189, in _http_query
    r = self._http_session.post(
        │    │             └ <function Session.post at 0x7fb48be6e0c0>
        │    └ <requests.sessions.Session object at 0x7fb48534a610>
        └ <transmission_rpc.client.Client object at 0x7fb48461e390>
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           │    │               │         │          │       └ {'headers': {'x-transmission-session-id': '0'}, 'timeout': 30}
           │    │               │         │          └ {'tag': 0, 'method': <RpcMethod.SessionGet: 'session-get'>, 'arguments': {}}
           │    │               │         └ None
           │    │               └ 'http://localhost:9091/transmission/rpc'
           │    └ <function Session.request at 0x7fb48be6de40>
           └ <requests.sessions.Session object at 0x7fb48534a610>
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 30, 'allow_redirects': True, 'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
           │    │    └ <PreparedRequest [POST]>
           │    └ <function Session.send at 0x7fb48be6e340>
           └ <requests.sessions.Session object at 0x7fb48534a610>
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'timeout': 30, 'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
        │       │    └ <PreparedRequest [POST]>
        │       └ <function HTTPAdapter.send at 0x7fb48be6d6c0>
        └ <requests.adapters.HTTPAdapter object at 0x7fb4847e6010>
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
          │                          └ <PreparedRequest [POST]>
          └ <class 'requests.exceptions.ConnectionError'>

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errno 111] Connection refused'))


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py", line 89, in create_rpc_client
    cli = transmission_rpc.Client(
          │                └ <class 'transmission_rpc.client.Client'>
          └ <module 'transmission_rpc' from '/usr/local/lib/python3.11/site-packages/transmission_rpc/__init__.py'>
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 131, in __init__
    self.get_session()
    │    └ <function Client.get_session at 0x7fb4898979c0>
    └ <transmission_rpc.client.Client object at 0x7fb48461e390>
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 842, in get_session
    self._request(RpcMethod.SessionGet, timeout=timeout)
    │    │        │         │                   └ None
    │    │        │         └ <RpcMethod.SessionGet: 'session-get'>
    │    │        └ <enum 'RpcMethod'>
    │    └ <function Client._request at 0x7fb489896c00>
    └ <transmission_rpc.client.Client object at 0x7fb48461e390>
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 236, in _request
    http_data = self._http_query(query, timeout)
                │    │           │      └ None
                │    │           └ {'tag': 0, 'method': <RpcMethod.SessionGet: 'session-get'>, 'arguments': {}}
                │    └ <function Client._http_query at 0x7fb489896b60>
                └ <transmission_rpc.client.Client object at 0x7fb48461e390>
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 198, in _http_query
    raise TransmissionConnectError(f"can't connect to transmission daemon: {e!s}") from e
          └ <class 'transmission_rpc.error.TransmissionConnectError'>

transmission_rpc.error.TransmissionConnectError: can't connect to transmission daemon: HTTPConnectionPool(host='localhost', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errno 111] Connection refused'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb48ebf1300>
    └ <Thread(task_queue, started daemon 140413316393784)>
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb48ebf0fe0>
    └ <Thread(task_queue, started daemon 140413316393784)>
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140413316393784)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140413316393784)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fb4867d3690>>
    └ <Thread(task_queue, started daemon 140413316393784)>
  File "/usr/local/lib/python3.11/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7fb48b50b2e0>
    │    └ <flexget.task.Task object at 0x7fb48464cfd0>
    └ <flexget.task_queue.TaskQueue object at 0x7fb4867d3690>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7fb48464cfd0>
           └ <function Task.execute at 0x7fb48b50b240>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    │    └ <function Task._execute at 0x7fb48b50b1a0>
    └ <flexget.task.Task object at 0x7fb48464cfd0>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 691, in _execute
    self.__run_task_phase(phase)
    │                     └ 'output'
    └ <flexget.task.Task object at 0x7fb48464cfd0>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7fb48464cfd0>, {'host': 'localhost', 'port': 9091, 'enabled': True, 'main_file_ratio': 0.9, '...
               │                 │       └ 'output'
               │                 └ <PluginInfo(name=transmission)>
               └ <flexget.task.Task object at 0x7fb48464cfd0>
> File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7fb48464cfd0>, {'host': 'localhost', 'port': 9091, 'enabled': True, 'main_file_ratio': 0.9, '...
             └ <Event(name=plugin.transmission.output,func=on_task_output,priority=135)>
  File "/usr/local/lib/python3.11/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7fb48464cfd0>, {'host': 'localhost', 'port': 9091, 'enabled': True, 'main_file_ratio': 0.9, '...
           │    └ <bound method PluginTransmission.on_task_output of <flexget.plugins.clients.transmission.PluginTransmission object at 0x7fb48...
           └ <Event(name=plugin.transmission.output,func=on_task_output,priority=135)>
  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py", line 400, in on_task_output
    client = self.create_rpc_client(config)
             │    │                 └ {'host': 'localhost', 'port': 9091, 'enabled': True, 'main_file_ratio': 0.9, 'action': 'add', 'path': '', 'main_file_only': F...
             │    └ <function TransmissionBase.create_rpc_client at 0x7fb489a45080>
             └ <flexget.plugins.clients.transmission.PluginTransmission object at 0x7fb4896aedd0>
  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py", line 105, in create_rpc_client
    raise plugin.PluginError("Error connecting to transmission: %s" % e.args[0].reason)
          │      └ <class 'flexget.plugin.PluginError'>
          └ <module 'flexget.plugin' from '/usr/local/lib/python3.11/site-packages/flexget/plugin.py'>

IndexError: tuple index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 189, in _http_query
    r = self._http_session.post(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py", line 89, in create_rpc_client
    cli = transmission_rpc.Client(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 131, in __init__
    self.get_session()
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 842, in get_session
    self._request(RpcMethod.SessionGet, timeout=timeout)
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 236, in _request
    http_data = self._http_query(query, timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 198, in _http_query
    raise TransmissionConnectError(f"can't connect to transmission daemon: {e!s}") from e
transmission_rpc.error.TransmissionConnectError: can't connect to transmission daemon: HTTPConnectionPool(host='localhost', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb484650350>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py", line 400, in on_task_output
    client = self.create_rpc_client(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/transmission.py", line 105, in create_rpc_client
    raise plugin.PluginError("Error connecting to transmission: %s" % e.args[0].reason)
                                                                      ~~~~~~^^^
IndexError: tuple index out of range
```
</details>

### Additional information:

- FlexGet version: 3.9.7
- Python version: 3.11.5
- Installation method: Docker
- Using daemon (yes/no): yes
- OS and version: Debian 12

**Comment by gazpachoking** [comment]
Ahh, yeah looks like the error properties changed we were trying to read. Thanks for reporting, will try to take a peek unless someone wants to send a PR
