### ISSUE TITLE
pendulum-3.0.0 Dependency

### ISSUE THREAD

**Issue by flexyboooy** [Flexget/Flexget#3905]
While updating my flexget pyenv today I got this error:

```Collecting pendulum==3.0.0 (from flexget)
  Downloading pendulum-3.0.0.tar.gz (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 kB 846.9 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Python 3.9.2
pip 23.3.2
flexget 3.10.7
Latest release: 3.11.0

Is this to be expected? Do we need to install Rust/Cargo now?

**Comment by gazpachoking** [comment]
Hmm, there should be precompiled wheels available. What platform are you on?

**Comment by gazpachoking** [comment]
you could also try to set the environment variable `PENDULUM_EXTENSIONS=0` before building. Either way, report back your platform. If this is a common issue I'd like to make installation go more smoothly somehow.

**Comment by flexyboooy** [comment]
I tried again while setting ```PENDULUM_EXTENSIONS=0``` before updating but got the same error.

This is on a Raspbian GNU/Linux 11.8 (bullseye) on ARMv7 (armv7l).

**Comment by gazpachoking** [comment]
I built pendulum 3.0 without the rust extensions. Try to grab this version, remove the `.zip` extension, then in your virtualenv run `pip install path/to/downloaded/pendulum-3.0.0-py3-none-any.whl`
[pendulum-3.0.0-py3-none-any.whl.zip](https://github.com/Flexget/Flexget/files/13782910/pendulum-3.0.0-py3-none-any.whl.zip)

This isn't a permanent solution, but might work before we figure a better way.

**Comment by gazpachoking** [comment]
Here's the pendulum ticket for this issue. https://github.com/sdispater/pendulum/issues/784

**Comment by flexyboooy** [comment]
I tried that and it let me upgrade to flexget v3.11.2 but unfortunately then flexget failed to start.

```
Dec 28 14:53:49 hostmachine systemd[1]: Started FlexGet Daemon.
Dec 28 14:53:52 hostmachine flexget[26349]: Traceback (most recent call last):
Dec 28 14:53:52 hostmachine flexget[26349]:   File "/hostpath/flexget/bin/flexget", line 5, in <module>
Dec 28 14:53:52 hostmachine flexget[26349]:     from flexget import main
Dec 28 14:53:52 hostmachine flexget[26349]:   File "/hostpath/flexget/lib/python3.9/site-packages/flexget/__init__.py", line 11, in <module>
Dec 28 14:53:52 hostmachine flexget[26349]:     from flexget.manager import Manager
Dec 28 14:53:52 hostmachine flexget[26349]:   File "/hostpath/flexget/lib/python3.9/site-packages/flexget/manager.py", line 37, in <module>
Dec 28 14:53:52 hostmachine flexget[26349]:     from flexget.config_schema import ConfigError
Dec 28 14:53:52 hostmachine flexget[26349]:   File "/hostpath/flexget/lib/python3.9/site-packages/flexget/config_schema.py", line 15, in <module>
Dec 28 14:53:52 hostmachine flexget[26349]:     from flexget.utils import qualities, template
Dec 28 14:53:52 hostmachine flexget[26349]:   File "/hostpath/flexget/lib/python3.9/site-packages/flexget/utils/template.py", line 12, in <module>
Dec 28 14:53:52 hostmachine flexget[26349]:     import pendulum
Dec 28 14:53:52 hostmachine flexget[26349]: ModuleNotFoundError: No module named 'pendulum'
Dec 28 14:53:52 hostmachine systemd[1]: flexget.service: Main process exited, code=exited, status=1/FAILURE
Dec 28 14:53:52 hostmachine systemd[1]: flexget.service: Failed with result 'exit-code'.

```

I am going back to a fresh install of flexget==3.10.7 for now and wait it out.

Thank you!

**Comment by gazpachoking** [comment]
Oops, sorry about that, I made a broken one at first and turns out I uploaded that accidentally. You could run `pip uninstall pendulum` in your virtualenv, then try again with the same procedure with this one.
[pendulum-3.0.0-py3-none-any.whl.zip](https://github.com/Flexget/Flexget/files/13787215/pendulum-3.0.0-py3-none-any.whl.zip)

**Comment by gazpachoking** [comment]
Can everyone having this issue please post what platform you are on here? (what processor and OS) Is everybody with this issue on a 32 bit OS?

**Comment by SpaceRat42** [comment]
I'm experiencing the same or similar problem using Raspberry Pi OS () / 64 bit (Linux raspberryPi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64  / Raspbian GNU/Linux 11 (bullseye)).

After setting PENDULUM_EXTENSIONS=0, "pip install --upgrade flexget" results in:

Collecting pendulum==3.0.0 (from flexget)
  Using cached pendulum-3.0.0.tar.gz (84 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      error: failed to parse manifest at `/tmp/pip-install-8nis1tmv/pendulum_ccb8c1e74cd34af4be45e580ac0b8b8a/rust/Cargo.toml`
      
      Caused by:
        invalid type: unit variant, expected string only for key `profile.release.strip`
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-7zb2146g', '--interpreter', '/usr/bin/python3']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-7zb2146g --interpreter /usr/bin/python3`
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


I also downgrade to 3.10.7 for the moment.

Big thanks for your great work and support!

**Comment by flexyboooy** [comment]
> Oops, sorry about that, I made a broken one at first and turns out I uploaded that accidentally. You could run `pip uninstall pendulum` in your virtualenv, then try again with the same procedure with this one. [pendulum-3.0.0-py3-none-any.whl.zip](https://github.com/Flexget/Flexget/files/13787215/pendulum-3.0.0-py3-none-any.whl.zip)

Ah, this one did it, I was able to upgrade and start Flexget: 3.11.2.

Again, thank you!

**Comment by SpaceRat42** [comment]
Just wantet to add, that my problem might be related to the mssion virtal environment. On a second Raspberry Pi (Raspberry Pi Bookworm / 64 bit), flexgte is installed in an virtual environment I was able to update to 3.11.3 without problems.

**Comment by Roburetto** [comment]
> Can everyone having this issue please post what platform you are on here? (what processor and OS) Is everybody with this issue on a 32 bit OS?

Building of Pendulum 3.0.0 failing on:
Debian 8.11 armhf
Python 3.11.5
rustc 1.73.0
cargo 1.73.0

**Comment by abugher** [comment]
Processor:  armv7l (ARMv7 Processor rev 3)
OS:  Debian 12, bookworm (Armbian)
cargo:  0.66.0 (OS package)
rustc:  1.63.0 (OS package)
python:  3.11.2 (OS package)

The problem I observed matched the general description:  Installing or updating flexget depends on pendulum, causing an attempt to build, which fails.  The pre-built wheels file worked around the problem for me as well.  (Thank you.)

The specific error looks different.  I don't see mention of variable type definitions or bit widths, but I do see noise about unstable features. 

```
$ virtualenv flexget
$ flexget/bin/pip3 install flexget
```
...
```
  Building wheel for pendulum (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pendulum (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Running `maturin pep517 build-wheel -i /home/ansible/flexget/bin/python --compatibility off`
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.11 at /home/ansible/flexget/bin/python
         Compiling target-lexicon v0.12.6
         Compiling python3-dll-a v0.2.9
         Compiling libc v0.2.139
         Compiling autocfg v1.1.0
         Compiling proc-macro2 v1.0.51
         Compiling once_cell v1.17.1
         Compiling unicode-ident v1.0.6
         Compiling quote v1.0.23
         Compiling syn v1.0.109
         Compiling parking_lot_core v0.9.7
         Compiling cc v1.0.79
         Compiling smallvec v1.10.0
         Compiling lock_api v0.4.9
         Compiling memoffset v0.9.0
         Compiling scopeguard v1.1.0
         Compiling cfg-if v1.0.0
         Compiling indoc v1.0.9
         Compiling unindent v0.1.11
         Compiling pyo3-build-config v0.19.1
         Compiling libmimalloc-sys v0.1.35
         Compiling parking_lot v0.12.1
         Compiling pyo3-ffi v0.19.1
         Compiling pyo3 v0.19.1
         Compiling mimalloc v0.1.39
         Compiling pyo3-macros-backend v0.19.1
         Compiling pyo3-macros v0.19.1
         Compiling _pendulum v3.0.0 (/tmp/pip-install-qyk6hnsh/pendulum_7973b75bd3c14f22bf64cdd2bcfe4c67/rust)
      error[E0658]: `let...else` statements are unstable
         --> src/parsing.rs:817:9
          |
      817 | /         let Some(mut value) = self.current.to_digit(10) else {
      818 | |             return Err(self.parse_error("Invalid number in duration".to_string()));
      819 | |         };
          | |__________^
          |
          = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information
      
      For more information about this error, try `rustc --explain E0658`.
      error: could not compile `_pendulum` due to previous error
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/home/ansible/flexget/bin/python" PYTHON_SYS_EXECUTABLE="/home/ansible/flexget/bin/python" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/tmp/pip-install-qyk6hnsh/pendulum_7973b75bd3c14f22bf64cdd2bcfe4c67/rust/Cargo.toml" "--release" "--lib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/ansible/flexget/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pendulum
```

**Comment by Spannerman0162** [comment]
Sincerely hoping this section is still open and the right place for my question. I am attempting to install the latest Flexget on my Truenas 13.0 system recently built although I have used Flexget successfully before on and older FreeNAS. Python 3.9 is already installed. Following the step-by-step guidance on the Flexget site installing in a virtual environment updating setup tools etc in the venv I am almost reaching a successful conclusion I think, but also hitting a pendulum related issue as below log shows:

Collecting pendulum==3.0.0 (from flexget)
  Using cached pendulum-3.0.0.tar.gz (84 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      Collecting maturin<2.0,>=1.0
        Using cached maturin-1.7.0.tar.gz (188 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting tomli>=1.1.0 (from maturin<2.0,>=1.0)
        Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
      Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Building wheels for collected packages: maturin
        Building wheel for maturin (pyproject.toml): started
        Building wheel for maturin (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for maturin (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [34 lines of output]
            /var/tmp/pip-build-env-bxjugttr/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py:79: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
              corresp(dist, value, root_dir)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.freebsd-13.1-RELEASE-p9-amd64-cpython-39
            creating build/lib.freebsd-13.1-RELEASE-p9-amd64-cpython-39/maturin
            copying maturin/__main__.py -> build/lib.freebsd-13.1-RELEASE-p9-amd64-cpython-39/maturin
            copying maturin/__init__.py -> build/lib.freebsd-13.1-RELEASE-p9-amd64-cpython-39/maturin
            running egg_info
            creating maturin.egg-info
            writing maturin.egg-info/PKG-INFO
            writing dependency_links to maturin.egg-info/dependency_links.txt
            writing requirements to maturin.egg-info/requires.txt
            writing top-level names to maturin.egg-info/top_level.txt
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            warning: no files found matching '*.json' under directory 'src/python_interpreter'
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            running build_ext
            running build_rust
            error: can't find Rust compiler

            If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

            To update pip, run:

                pip install --upgrade pip

            and then retry package installation.

            If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
      Failed to build maturin
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (maturin)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
root@truenas[~]#

I tried the instruction already listed in this forum to uninstall pendulum, within the venv, but received a message saying pendulum doesn't exist, so maybe I am performing that task in the wrong place or using the wrong command? Also tried an older version of Flexget (3.10.7) as someone else did and received the same error relating to pendulum as in the log above. Tried manually loading the listed download whl file: pendulum-3.0.0-py3-none-any.whl.zip. I had left that file in my downloads (accessing as root via SSH) and provided that path but that path was not recognised - should I be moving that file to a more accessible location first? So maybe I am missing something more basic relating to the starting point for Flexget? For example should I be logging in to a different part of my TrueNAS installation. Appreciate any help, comments or guidance please. As you can tell I am not the most experienced in the installation but in the past I was successful, and really enjoyed the benefits of Flexget, and would like to do so again. Thanks.

**Comment by Spannerman0162** [comment]
As a follow-on to the preceding post I successfully managed to load the pendulum-3.0.0-py3-none-any.whl file which did not help, I also updated pip which also did not help. Then tried installing rust compiler as suggested in the error messages but that also failed. Also went back through a few legacy flexget versions but all came up with errors. I suspect now I need to remove rust compiler too but for now I attach the entire install log in the hope someone can advise? Could be I need to post this in the more general Flexget help forum too as I am no longer sure its a pendulum dependency, but this is way beyond my ability to analyse it now. See attached file for log. Thanks.
[Flexget Install Errors.txt](https://github.com/user-attachments/files/16323173/Flexget.Install.Errors.txt)

**Comment by Spannerman0162** [comment]
Apologies I meant to add my system versions in more detail: Python 3.9.16 and Pip 24.1.2. Truenas is TrueNAS-13.0-U6.2

**Comment by pedro-MD11** [comment]
> As a follow-on to the preceding post I successfully managed to load the pendulum-3.0.0-py3-none-any.whl file which did not help, I also updated pip which also did not help. Then tried installing rust compiler as suggested in the error messages but that also failed. Also went back through a few legacy flexget versions but all came up with errors. I suspect now I need to remove rust compiler too but for now I attach the entire install log in the hope someone can advise? Could be I need to post this in the more general Flexget help forum too as I am no longer sure its a pendulum dependency, but this is way beyond my ability to analyse it now. See attached file for log. Thanks. [Flexget Install Errors.txt](https://github.com/user-attachments/files/16323173/Flexget.Install.Errors.txt)

I also have the same issue on an entware router. 
The last version that works for me is 3.9.19

**Comment by jahutchi** [comment]
Just to mention that I have just encountered this same issue.
On Platform: Arch Linux x86_64 using the latest zen kernel

I bumped my packages and kernel today.
Kernel was bumped from: 6.12.4-zen1-1-zen -> 6.12.8-zen1-1-zen
Python was bumped as part of the packages upgrade as follows:

[2025-01-06T11:13:11+0000] [ALPM] upgraded python (3.12.7-1 -> 3.13.1-1)

Following this, flexget would no longer start - so noticing the bump of python I tried an inline upgrade of the python virtualenv:

python3 -m venv --upgrade /opt/flexget

And got the same errors reported here regarding pendulum:

```
Collecting pendulum==3.0.0 (from flexget)
  Downloading pendulum-3.0.0.tar.gz (84 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
As I am running in a virtualenv I tried simply deleting my virtualenv (/opt/flexget folder) and then ran the usual instructions for re-creating it from scratch:

```
python3 -m venv /opt/flexget
/opt/flexget/bin/pip install --upgrade pip setuptools
/opt/flexget/bin/pip install flexget
```

And the exact same errors regarding the pendulum installation occurred  🤔

I was able to fix with the "workaround in full using pipx" above 👍

Not sure if it makes any difference or helps... but today I also installed iotop via system pacman which appears to be what bumped my python version from 3.12->3.13. iotop  as it seems to have some dependencies on python.

Anyhow, glad I found this thread as I'm back up and running now.

**Comment by gazpachoking** [comment]
Yeah, there are no built wheels available for python 3.13 yet, so the rust toolchain is required to install it. Pretty annoying. There was a bit more activity over at the pendulum repository recently, so I have some hope that it might start being maintained more actively again. In the mean time, I think the easiest method for installing flexget now might be with `uv`, where it is easy to have the virtualenv set up for you automatically, as well as specify the version of python to use. e.g.
`uv tool install flexget --python 3.12` will install flexget into its own python 3.12 venv, and add the binary to the PATH.

**Comment by gazpachoking** [comment]
Pendulum finally released a 3.13 wheel and a pure python wheel, hopefully our woes are finished now.
