### ISSUE TITLE
Scheduler crashing in latest version ( Cannot pickle a ZoneInfo file from a file stream )

### ISSUE THREAD

**Issue by diogosena** [Flexget/Flexget#3954]
### Expected behaviour:

Should start in daemon without any error

### Actual behaviour:

Scheduler crash and doesn't work, webui works.

### Steps to reproduce:
- Step 1: just start daemon mode in a new install with any config with scheduler 

#### Config:
```yaml
web_server: yes

tasks:

  dummy-task:
    priority: 1

```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
flexget -L debug -c /media/sda1/flexget/flexget/config.yml daemon start
2024-03-17 18:30:12 DEBUG    manager                       Config file /media/sda1/flexget/flexget/config.yml selected
2024-03-17 18:30:12 DEBUG    manager                       sys.defaultencoding: utf-8
2024-03-17 18:30:12 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2024-03-17 18:30:12 DEBUG    manager                       flexget detected io encoding: utf-8
2024-03-17 18:30:12 DEBUG    manager                       os.path.supports_unicode_filenames: False
2024-03-17 18:30:12 DEBUG    plugin                        Trying to load plugins from: ['/media/sda1/flexget/flexget/plugins', '/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/plugins']
2024-03-17 18:30:16 DEBUG    plugin                        Plugin `memusage` requires plugin `guppy3` to load.
2024-03-17 18:30:16 DEBUG    plugin                        Trying to load components from: ['/media/sda1/flexget/flexget/components', '/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/components']
2024-03-17 18:30:19 DEBUG    plugin                        Plugins took 6.98 seconds to load. 324 plugins in registry.
2024-03-17 18:30:20 DEBUG    manager                       Connecting to: sqlite:////media/sda1/flexget/flexget/db-config.sqlite
2024-03-17 18:30:20 DEBUG    manager                       config_name: config
2024-03-17 18:30:20 DEBUG    manager                       config_base: /media/sda1/flexget/flexget
2024-03-17 18:30:20 DEBUG    manager                       New config data loaded.
2024-03-17 18:30:20 DEBUG    schema                        current flexget version already exist in db 3.11.24
2024-03-17 18:30:20 DEBUG    parsing                       setting default movie parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0xb32316e8>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0xb32317a8>})
2024-03-17 18:30:20 DEBUG    parsing                       setting default series parser to internal. (options: {'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0xb32316e8>, 'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0xb32317a8>})
2024-03-17 18:30:20 INFO     web_server_daemon                 Running web server at IP 0.0.0.0:5050
2024-03-17 18:30:20 INFO     web_server_daemon                 Initiating API
2024-03-17 18:30:20 INFO     web_server_daemon                 Registering WebUI v2
2024-03-17 18:30:20 WARNING  web_server                    No password set for web server, create one by using `flexget web passwd <password>`
2024-03-17 18:30:20 DEBUG    irc                           No irc connections defined in the config
2024-03-17 18:30:20 DEBUG    tzlocal                       No explicit setting existed. Use localtime
2024-03-17 18:30:20 INFO     scheduler                     No schedules defined in config. Defaulting to run all tasks on a 1 hour interval.
2024-03-17 18:30:20 INFO     scheduler                     Starting scheduler
2024-03-17 18:30:20 INFO     apscheduler.scheduler                 Scheduler started
2024-03-17 18:30:20 DEBUG    manager                       Removed /media/sda1/flexget/flexget/.config-lock
Traceback (most recent call last):
  File "/media/sda1/python/flexget_venv/bin/flexget", line 8, in <module>
    sys.exit(main())
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/__init__.py", line 55, in main
    manager.start()
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/manager.py", line 366, in start
    self.handle_cli()
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/manager.py", line 392, in handle_cli
    self.daemon_command(command_options)
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/manager.py", line 489, in daemon_command
    run_daemon()
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/manager.py", line 470, in run_daemon
    fire_event('manager.daemon.started', self)
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/event.py", line 109, in fire_event
    result = event(*args, **kwargs)
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/event.py", line 21, in __call__
    return self.func(*args, **kwargs)
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/components/scheduler/scheduler.py", line 128, in setup_scheduler
    setup_jobs(manager)
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/flexget/components/scheduler/scheduler.py", line 171, in setup_jobs
    scheduler.add_job(
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 457, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 881, in _real_add_job
    store.add_job(job)
  File "/media/sda1/python/flexget_venv/lib/python3.10/site-packages/apscheduler/jobstores/sqlalchemy.py", line 97, in add_job
    'job_state': pickle.dumps(job.__getstate__(), self.pickle_protocol)
_pickle.PicklingError: Cannot pickle a ZoneInfo file from a file stream.
2024-03-17 18:30:20 INFO     web_server                    Web server started at http://127.0.0.1:5050
2024-03-17 18:30:20 INFO     web_server                    API available at http://127.0.0.1:5050/api
2024-03-17 18:30:20 INFO     web_server                    WebUI (v2) available at http://127.0.0.1:5050/
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:


```
</details>

### Additional information:

- FlexGet version: 3.11.24
- Python version: 3.11.8
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu armhf 22.04

**Comment by diogosena** [comment]
a full reinstall in ubuntu 23.10 solved the issue
