### ISSUE TITLE
Flexget crashes on missing Telegram module

### ISSUE THREAD

**Issue by mfonville** [Flexget/Flexget#4008]
### Expected behaviour:

I am not using the telegram plugin in my flexget configuration. I expect Flexget to run without requiring the telegram python module.

### Actual behaviour:

Since June 19 Flexget crashes that it cannot find the telegram module

### Steps to reproduce:
Run flexget task

#### Config:
```yaml
  Series-Trakt:
    cfscraper: yes
    configure_series:
      settings:
        quality: h264+ <=1080p #720p+ webrip+
        path: /var/lib/plexmediaserver/Series/{{series_name}}/ 
      from:
        trakt_calendar:
          account: xxxxx
          start_day: -7
          days: 8
          strip_dates: yes
          type: shows
    discover:
      what:
        - next_series_episodes: yes
      from: [redacted]
    trakt_lookup:
      account: xxxx
      username: xxxxx
    if:
      - "trakt_watched": reject
    exec:
      on_output:
        for_accepted:
          - mkdir -p "{{path}}"
#    convert_magnet: yes
    transmission:
      magnetization_timeout: 60
      main_file_only: Yes
      include_subs: Yes
      add_paused: No
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2024-06-19 12:13:10 CRITICAL plugin                        Plugin `flexget.components.notify.notifiers.telegram` failed to import dependencies
Traceback (most recent call last):

  File "/home/maarten/.local/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7a30ce1e4fe0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/__init__.py", line 55, in main
    manager.start()
    │       └ <function Manager.start at 0x7a30cb7a5080>
    └ <flexget.manager.Manager object at 0x7a30cb777770>
  File "/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/manager.py", line 365, in start
    self.initialize()
    │    └ <function Manager.initialize at 0x7a30cb7a4e00>
    └ <flexget.manager.Manager object at 0x7a30cb777770>
  File "/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/manager.py", line 211, in initialize
    plugin.load_plugins(
    │      └ <function load_plugins at 0x7a30cbf35580>
    └ <module 'flexget.plugin' from '/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/plugin.py'>
  File "/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/plugin.py", line 549, in load_plugins
    _load_components_from_dirs(extra_components)
    │                          └ ['/home/maarten/.flexget/components', '/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/components']
    └ <function _load_components_from_dirs at 0x7a30cbf35440>
  File "/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/plugin.py", line 488, in _load_components_from_dirs
    _import_plugin(package_name, component_path)
    │              │             └ PosixPath('/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/components/notify/notifiers/telegram....
    │              └ 'flexget.components.notify.notifiers.telegram'
    └ <function _import_plugin at 0x7a30cbf35300>
> File "/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.components.notify.notifiers.telegram'
    └ <function import_module at 0x7a30ce122fc0>
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.components.notify.notifiers.telegram'
           │          └ <function _gcd_import at 0x7a30ceb800e0>
           └ <module '_frozen_importlib' (frozen)>
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/maarten/.local/pipx/venvs/flexget/lib/python3.12/site-packages/flexget/components/notify/notifiers/telegram.py", line 1, in <module>
    import telegram

ModuleNotFoundError: No module named 'telegram'
```
</details>

### Additional information:

- FlexGet version: 3.11.38
- Python version: 3.12.3
- Installation method: pipx
- OS and version: Ubuntu Noble

**Comment by gazpachoking** [comment]
This was fixed by #4007 and is included in today's release. Thanks for the report!
