### ISSUE TITLE
deluge and from_deluge: Unhandled error in plugin from_deluge: module 'ssl' has no attribute 'wrap_socket'

### ISSUE THREAD

**Issue by atajsic** [Flexget/Flexget#4012]
### Expected behaviour:

Successful connection to deluge

### Actual behaviour:

Fails on module ssl with no attribute wrap_socket

### Steps to reproduce:
- Step 1: install flexget 3.11.38 or 3.11.39
- Step 2: try and connect to deluge via the deluge or from_deluge plugin
- Step 3: critical crash

#### Config:
```yaml
deluge:
    deluge:
      host: '{? deluge.host ?}'
      username: '{? deluge.username ?}'
      password: '{? deluge.password ?}'
      path: '{? deluge.path ?}'
      label: '{? deluge.label ?}'

  from_deluge:
    from_deluge:
      host: '{? deluge.host ?}'
      username: '{? deluge.username ?}'
      password: '{? deluge.password ?}'
      filter:
        label: '{? deluge.label ?}'
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2024-06-25 14:06:57 CRITICAL task          my-task BUG: Unhandled error in plugin from_deluge: module 'ssl' has no attribute 'wrap_socket'
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f10600cad40>
    └ <Thread(task_queue, started daemon 139708153867064)>
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f10600caa20>
    └ <Thread(task_queue, started daemon 139708153867064)>
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 139708153867064)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 139708153867064)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f1057ded3d0>>
    └ <Thread(task_queue, started daemon 139708153867064)>
  File "/lsiopy/lib/python3.12/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f105c2cbba0>
    │    └ <flexget.task.Task object at 0x7f10574d5370>
    └ <flexget.task_queue.TaskQueue object at 0x7f1057ded3d0>
  File "/lsiopy/lib/python3.12/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f10574d5370>
           └ <function Task.execute at 0x7f105c2cbb00>
  File "/lsiopy/lib/python3.12/site-packages/flexget/task.py", line 716, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f105c2cba60>
    └ <flexget.task.Task object at 0x7f10574d5370>
  File "/lsiopy/lib/python3.12/site-packages/flexget/task.py", line 685, in _execute
    self.__run_task_phase(phase)
    │                     └ 'start'
    └ <flexget.task.Task object at 0x7f10574d5370>
  File "/lsiopy/lib/python3.12/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f10574d5370>, {'host': '<<redacted>>', 'username': ''<<redacted>>', 'password': ''<<redacted>>', 'filter':...
               │                 │       └ 'start'
               │                 └ <PluginInfo(name=from_deluge)>
               └ <flexget.task.Task object at 0x7f10574d5370>
> File "/lsiopy/lib/python3.12/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7f10574d5370>, {'host': ''<<redacted>>', 'username': ''<<redacted>>', 'password': ''<<redacted>>', 'filter':...
             └ <Event(name=plugin.from_deluge.start,func=on_task_start,priority=128)>
  File "/lsiopy/lib/python3.12/site-packages/flexget/event.py", line 21, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7f10574d5370>, {'host': ''<<redacted>>', 'username': ''<<redacted>>', 'password': ''<<redacted>>', 'filter':...
           │    └ <bound method InputDeluge.on_task_start of <flexget.plugins.clients.deluge.InputDeluge object at 0x7f10579bd910>>
           └ <Event(name=plugin.from_deluge.start,func=on_task_start,priority=128)>
  File "/lsiopy/lib/python3.12/site-packages/flexget/plugins/clients/deluge.py", line 138, in on_task_start
    super().on_task_start(task, config)
                          │     └ {'host': ''<<redacted>>', 'username': ''<<redacted>>', 'password': ''<<redacted>>', 'filter': {'label': 'flexget'}, 'port': 58846}
                          └ <flexget.task.Task object at 0x7f10574d5370>
  File "/lsiopy/lib/python3.12/site-packages/flexget/plugins/clients/deluge.py", line 25, in on_task_start
    self.setup_client(config)
    │    │            └ {'host': ''<<redacted>>', 'username': ''<<redacted>>', 'password': ''<<redacted>>', 'filter': {'label': 'flexget'}, 'port': 58846}
    │    └ <function DelugePlugin.setup_client at 0x7f1059c40d60>
    └ <flexget.plugins.clients.deluge.InputDeluge object at 0x7f10579bd910>
  File "/lsiopy/lib/python3.12/site-packages/flexget/plugins/clients/deluge.py", line 51, in setup_client
    return DelugeRPCClient(
           └ <class 'deluge_client.client.DelugeRPCClient'>
  File "/lsiopy/lib/python3.12/site-packages/deluge_client/client.py", line 71, in __init__
    self._create_socket()
    │    └ <function DelugeRPCClient._create_socket at 0x7f1057556480>
    └ <deluge_client.client.DelugeRPCClient object at 0x7f10574d5280>
  File "/lsiopy/lib/python3.12/site-packages/deluge_client/client.py", line 77, in _create_socket
    self._socket = ssl.wrap_socket(socket.socket(socket.AF_INET, socket.SOCK_STREAM))
    │              │               │      │      │      │        │      └ <SocketKind.SOCK_STREAM: 1>
    │              │               │      │      │      │        └ <module 'socket' from '/usr/lib/python3.12/socket.py'>
    │              │               │      │      │      └ <AddressFamily.AF_INET: 2>
    │              │               │      │      └ <module 'socket' from '/usr/lib/python3.12/socket.py'>
    │              │               │      └ <class 'socket.socket'>
    │              │               └ <module 'socket' from '/usr/lib/python3.12/socket.py'>
    │              └ <module 'ssl' from '/usr/lib/python3.12/ssl.py'>
    └ <deluge_client.client.DelugeRPCClient object at 0x7f10574d5280>

AttributeError: module 'ssl' has no attribute 'wrap_socket'
```
</details>

### Additional information:

- FlexGet version: 3.11.39
- Python version: 3.12
- Installation method: docker linuxserver/flexget
- Using daemon (yes/no): yes
- OS and version: docker
- Link to crash log: as above

**Comment by atajsic** [comment]
I'm speculating,
However it could be the change in python verison

https://github.com/linuxserver/docker-flexget/commit/624a2767ecbf681be2b15b0f90fdaa1ee899fd3b#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R65

the last working linuxserver/flexget is 3.11.37 which uses python 3.11
