### ISSUE TITLE
Crash in RSS plugin running: `Unhandled error in plugin rss: 'NoneType' object has no attribute 'replace'`

### ISSUE THREAD

**Issue by ssssam** [Flexget/Flexget#4036]
### Expected behaviour:

Download RSS feed 

At first I thought the failure was just with `--test` but seems to happen in all cases.

### Actual behaviour:

Crash:

```
 File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 1814, in _datetime_to_timestamp
    return (dt.replace(tzinfo=None) - EPOCH).total_seconds()
            ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

Full log: 
[crash_report.2024.08.26.202445448984.log](https://github.com/user-attachments/files/16752870/crash_report.2024.08.26.202445448984.log)

### Steps to reproduce:
- Step 1: Set config as documented
- Step 2: Run `~/flexget.venv/bin/flexget --test execute --tasks 'chisme-corporativa'`

#### Config:
```yaml
accept_all: true                                                                                                                        
download:                                                                                                                               
  fail_html: true                                                                                                                       
  filename: '{{title}}.mp3'                                                                                                             
  overwrite: false                                                                                                                      
  path: /home/sam/Podcasts/                                                                                                             
limit_new: 1                                                                                                                            
rss: https://anchor.fm/s/f39fde9c/podcast/rss                                                                                           
template: podcast              
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
> cat /home/sam/.config/flexget/crash_report.2024.08.26.202445448984.log
2024-08-26 20:24:41 DEBUG    manager                       Figuring out config load paths
2024-08-26 20:24:41 DEBUG    manager                       Found config: /home/sam/.config/flexget/config.yml
2024-08-26 20:24:41 DEBUG    manager                       Config file /home/sam/.config/flexget/config.yml selected
2024-08-26 20:24:41 DEBUG    manager                       sys.defaultencoding: utf-8
2024-08-26 20:24:41 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2024-08-26 20:24:41 DEBUG    manager                       flexget detected io encoding: utf-8
2024-08-26 20:24:41 DEBUG    manager                       os.path.supports_unicode_filenames: False
2024-08-26 20:24:41 DEBUG    manager                       Figuring out config load paths
2024-08-26 20:24:41 DEBUG    manager                       Found config: /home/sam/.config/flexget/config.yml
2024-08-26 20:24:41 DEBUG    manager                       Config file /home/sam/.config/flexget/config.yml selected
2024-08-26 20:24:41 DEBUG    manager                       sys.defaultencoding: utf-8
2024-08-26 20:24:41 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2024-08-26 20:24:41 DEBUG    manager                       flexget detected io encoding: utf-8
2024-08-26 20:24:41 DEBUG    manager                       os.path.supports_unicode_filenames: False
2024-08-26 20:24:41 INFO     manager                       Test mode, creating a copy from database ...
2024-08-26 20:24:41 INFO     manager                       Test database created
2024-08-26 20:24:41 DEBUG    plugin                        Trying to load plugins from: ['/home/sam/.config/flexget/plugins', '/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/plugins']
2024-08-26 20:24:42 DEBUG    plugin                        Plugin `memusage` requires plugin `guppy3` to load.
2024-08-26 20:24:43 DEBUG    plugin                        Trying to load components from: ['/home/sam/.config/flexget/components', '/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/components']
2024-08-26 20:24:44 DEBUG    plugin                        Plugins took 2.43 seconds to load. 324 plugins in registry.
2024-08-26 20:24:44 DEBUG    manager                       Connecting to: sqlite:////home/sam/.config/flexget/test-config.sqlite
2024-08-26 20:24:44 DEBUG    manager                       config_name: config
2024-08-26 20:24:44 DEBUG    manager                       config_base: /home/sam/.config/flexget
2024-08-26 20:24:44 DEBUG    manager                       New config data loaded.
2024-08-26 20:24:44 DEBUG    schema                        updating flexget version 3.11.43 in db
2024-08-26 20:24:44 DEBUG    parsing                       setting default movie parser to internal. (options: {'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7ffbe5c6e510>, 'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7ffbe5c6e570>})
2024-08-26 20:24:44 DEBUG    parsing                       setting default series parser to internal. (options: {'guessit': <flexget.components.parsing.parsers.parser_guessit.ParserGuessit object at 0x7ffbe5c6e510>, 'internal': <flexget.components.parsing.parsers.parser_internal.ParserInternal object at 0x7ffbe5c6e570>})
2024-08-26 20:24:44 DEBUG    cron_env                      Encoding utf-8 stored
2024-08-26 20:24:44 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'utf-8'
2024-08-26 20:24:44 DEBUG    task_queue                    task queue shutdown requested
2024-08-26 20:24:44 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2024-08-26 20:24:44 DEBUG    task          chisme-corporativa executing chisme-corporativa
2024-08-26 20:24:44 DEBUG    template      chisme-corporativa Merging template podcast into task chisme-corporativa
2024-08-26 20:24:44 DEBUG    input_cache   chisme-corporativa cache name: rss_657c6b09159b9af7776c2fd1c9a33cbb (has: )
2024-08-26 20:24:44 DEBUG    rss           chisme-corporativa Requesting task `chisme-corporativa` url `https://anchor.fm/s/f39fde9c/podcast/rss`
2024-08-26 20:24:44 DEBUG    utils.requests chisme-corporativa GETing URL https://anchor.fm/s/f39fde9c/podcast/rss with args () and kwargs {'timeout': 60, 'headers': {'User-Agent': 'FlexGet/3.11.43 (www.flexget.com)', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive'}, 'auth': None, 'allow_redirects': True}
2024-08-26 20:24:45 DEBUG    rss           chisme-corporativa encoding utf-8
2024-08-26 20:24:45 CRITICAL task          chisme-corporativa BUG: Unhandled error in plugin rss: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):

  File "/usr/lib64/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7ffbeb4a3920>
    └ <Thread(task_queue, started daemon 140719863891648)>
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7ffbeb4a3600>
    └ <Thread(task_queue, started daemon 140719863891648)>
  File "/usr/lib64/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140719863891648)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140719863891648)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7ffbe5fdd580>>
    └ <Thread(task_queue, started daemon 140719863891648)>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7ffbe8891f80>
    │    └ <flexget.task.Task object at 0x7ffbe588e3c0>
    └ <flexget.task_queue.TaskQueue object at 0x7ffbe5fdd580>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/task.py", line 88, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7ffbe588e3c0>
           └ <function Task.execute at 0x7ffbe8891ee0>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/task.py", line 717, in execute
    self._execute()
    │    └ <function Task._execute at 0x7ffbe8891e40>
    └ <flexget.task.Task object at 0x7ffbe588e3c0>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/task.py", line 686, in _execute
    self.__run_task_phase(phase)
    │                     └ 'input'
    └ <flexget.task.Task object at 0x7ffbe588e3c0>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/task.py", line 515, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7ffbe588e3c0>, 'https://anchor.fm/s/f39fde9c/podcast/rss')
               │                 │       └ 'input'
               │                 └ <PluginInfo(name=rss)>
               └ <flexget.task.Task object at 0x7ffbe588e3c0>
> File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/task.py", line 548, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7ffbe588e3c0>, 'https://anchor.fm/s/f39fde9c/podcast/rss')
             └ <Event(name=plugin.rss.input,func=wrapped_func,priority=128)>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/event.py", line 21, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7ffbe588e3c0>, 'https://anchor.fm/s/f39fde9c/podcast/rss')
           │    └ <bound method cached.__call__.<locals>.wrapped_func of <flexget.plugins.input.rss.InputRSS object at 0x7ffbe82acb60>>
           └ <Event(name=plugin.rss.input,func=wrapped_func,priority=128)>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/utils/cached_input.py", line 161, in wrapped_func
    response = func(*args, **kwargs)
               │     │       └ {}
               │     └ (<flexget.plugins.input.rss.InputRSS object at 0x7ffbe82acb60>, <flexget.task.Task object at 0x7ffbe588e3c0>, 'https://anchor...
               └ <function internet.__call__.<locals>.wrapped_func at 0x7ffbe8433100>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/plugin.py", line 126, in wrapped_func
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<flexget.plugins.input.rss.InputRSS object at 0x7ffbe82acb60>, <flexget.task.Task object at 0x7ffbe588e3c0>, 'https://anchor...
           └ <function InputRSS.on_task_input at 0x7ffbe8433060>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/plugins/input/rss.py", line 565, in on_task_input
    add_entry(e)
    │         └ <Entry(title=1. Herbalife: Network marketing, controversias y la guerra de Bill Ackman vs. Carl Icahn.,state=undecided)>
    └ <function InputRSS.on_task_input.<locals>.add_entry at 0x7ffbe592dbc0>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/plugins/input/rss.py", line 497, in add_entry
    ea['rss_pubdate'] = pendulum.parse(entry.published, tz="UTC", strict=False)
    │                   │        │     └ {'title': '1. Herbalife: Network marketing, controversias y la guerra de Bill Ackman vs. Carl Icahn.', 'title_detail': {'type...
    │                   │        └ <function parse at 0x7ffbe8e228e0>
    │                   └ <module 'pendulum' from '/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/__init__.py'>
    └ <Entry(title=1. Herbalife: Network marketing, controversias y la guerra de Bill Ackman vs. Carl Icahn.,state=undecided)>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
           │      │       └ {'tz': 'UTC', 'strict': False, 'now': None}
           │      └ 'Tue, 26 Mar 2024 06:00:00 GMT'
           └ <function _parse at 0x7ffbe8e558a0>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/parser.py", line 46, in _parse
    return pendulum.datetime(
           │        └ <function datetime at 0x7ffbe8c4a480>
           └ <module 'pendulum' from '/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/__init__.py'>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/__init__.py", line 143, in datetime
    return DateTime.create(
           │        └ <classmethod(<function DateTime.create at 0x7ffbe8e51120>)>
           └ <class 'pendulum.datetime.DateTime'>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/datetime.py", line 103, in create
    tz = pendulum._safe_timezone(tz)
         │        │              └ tzlocal()
         │        └ <function _safe_timezone at 0x7ffbe8c4a3e0>
         └ <module 'pendulum' from '/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/__init__.py'>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/__init__.py", line 112, in _safe_timezone
    elif obj.tzname(None) == "UTC":
         │   └ <function tzlocal.tzname at 0x7ffbe8dd8a40>
         └ tzlocal()
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 238, in tzname
    return self._tznames[self._isdst(dt)]
           │    │        │    │      └ None
           │    │        │    └ <function tzlocal._isdst at 0x7ffbe8dd8c20>
           │    │        └ tzlocal()
           │    └ ('GMT', 'BST')
           └ tzlocal()
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 291, in _isdst
    dstval = self._naive_is_dst(dt)
             │    │             └ None
             │    └ <function tzlocal._naive_is_dst at 0x7ffbe8dd8b80>
             └ tzlocal()
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 259, in _naive_is_dst
    timestamp = _datetime_to_timestamp(dt)
                │                      └ None
                └ <function _datetime_to_timestamp at 0x7ffbe8ddb1a0>
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 1814, in _datetime_to_timestamp
    return (dt.replace(tzinfo=None) - EPOCH).total_seconds()
            │                         └ datetime.datetime(1970, 1, 1, 0, 0)
            └ None

AttributeError: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/task.py", line 548, in __run_plugin
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/event.py", line 21, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/utils/cached_input.py", line 161, in wrapped_func
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/plugin.py", line 126, in wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/plugins/input/rss.py", line 565, in on_task_input
    add_entry(e)
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/flexget/plugins/input/rss.py", line 497, in add_entry
    ea['rss_pubdate'] = pendulum.parse(entry.published, tz="UTC", strict=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/parser.py", line 30, in parse
    return _parse(text, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/parser.py", line 46, in _parse
    return pendulum.datetime(
           ^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/__init__.py", line 143, in datetime
    return DateTime.create(
           ^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/datetime.py", line 103, in create
    tz = pendulum._safe_timezone(tz)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/pendulum/__init__.py", line 112, in _safe_timezone
    elif obj.tzname(None) == "UTC":
         ^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 238, in tzname
    return self._tznames[self._isdst(dt)]
                         ^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 291, in _isdst
    dstval = self._naive_is_dst(dt)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 259, in _naive_is_dst
    timestamp = _datetime_to_timestamp(dt)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/flexget.venv/lib64/python3.12/site-packages/dateutil/tz/tz.py", line 1814, in _datetime_to_timestamp
    return (dt.replace(tzinfo=None) - EPOCH).total_seconds()
            ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```
</details>

### Additional information:

- FlexGet version: 3.11.43
- Python version: 3.12
- Installation method: pip install into venv
- Using daemon (yes/no): no
- OS and version: Fedora Linux 40
- Link to crash log: [crash_report.2024.08.26.202445448984.log](https://github.com/user-attachments/files/16752870/crash_report.2024.08.26.202445448984.log)

Thanks a lot for Flexget !

**Comment by ssssam** [comment]
It seems that the rss pubdate field is not used for much in the flexget codebase. I have commented lines 496 and 497 in `plugins/input/rss.py` to work around the issue.

**Comment by ssssam** [comment]
Doesn't reproduce with Python 3.13 and flexget 3.13.25. Closing. Thanks stalebot.

**Comment by ssssam** [comment]
This happened again today. Flexget 3.15.2, Python 3.13.1

**Comment by ghost** [comment]
I still see this issue occurring from time to time.

**Comment by vivodi** [comment]
The changes in https://github.com/Flexget/Flexget/pull/4635 happened to resolve this issue. @ssssam Please test with v3.18.9 or later to see if it still occurs.

Also, please don’t close the issue in the pendulum repository, as the problem still exists there.

**Comment by ghost** [comment]
Hello! Just did a `--test` run with flexget 3.18.16 (and pendulum 3.1.0); no errors so far. Let's close this, I will reopen if I see the problem reoccur at some point. Thanks!
