### ISSUE TITLE
Flexget failing after upgrading (from ancient version, sorry)

### ISSUE THREAD

**Issue by Zhongz0r** [Flexget/Flexget#4056]
flexget database reset-plugin backlog
2024-10-12 10:27:32 INFO     manager                       Database upgrade is required. Attempting now.
2024-10-12 10:27:32 ERROR    schema                        Failed to upgrade database for plugin backlog: tuple indices must be integers or slices, not str
Traceback (most recent call last):

  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Program Files\Python310\Sc...
           │         └ <code object <module> at 0x000001F993107D60, file "C:\Program Files\Python310\Scripts\flexget.exe\__main__.py", line 1>
           └ <function _run_code at 0x000001F9930F0D30>

  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Program Files\Python310\Sc...
         └ <code object <module> at 0x000001F993107D60, file "C:\Program Files\Python310\Scripts\flexget.exe\__main__.py", line 1>

  File "C:\Program Files\Python310\Scripts\flexget.exe\__main__.py", line 7, in <module>

  File "C:\Program Files\Python310\lib\site-packages\flexget\__init__.py", line 55, in main
    manager.start()
    │       └ <function Manager.start at 0x000001F9974DF5B0>
    └ <flexget.manager.Manager object at 0x000001F9974B9420>

  File "C:\Program Files\Python310\lib\site-packages\flexget\manager.py", line 370, in start
    self.initialize()
    │    └ <function Manager.initialize at 0x000001F9974DF370>
    └ <flexget.manager.Manager object at 0x000001F9974B9420>

  File "C:\Program Files\Python310\lib\site-packages\flexget\manager.py", line 239, in initialize
    fire_event('manager.upgrade', self)
    │                             └ <flexget.manager.Manager object at 0x000001F9974B9420>
    └ <function fire_event at 0x000001F996B8CEE0>

  File "C:\Program Files\Python310\lib\site-packages\flexget\event.py", line 109, in fire_event
    result = event(*args, **kwargs)
             │      │       └ {}
             │      └ (<flexget.manager.Manager object at 0x000001F9974B9420>,)
             └ <Event(name=manager.upgrade,func=upgrade_wrapper,priority=128)>

  File "C:\Program Files\Python310\lib\site-packages\flexget\event.py", line 21, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.manager.Manager object at 0x000001F9974B9420>,)
           │    └ <function upgrade.<locals>.upgrade_decorator.<locals>.upgrade_wrapper at 0x000001F99A6C6E60>
           └ <Event(name=manager.upgrade,func=upgrade_wrapper,priority=128)>

> File "C:\Program Files\Python310\lib\site-packages\flexget\db_schema.py", line 157, in upgrade_wrapper
    new_ver = upgrade_func(current_ver, session)
              │            │            └ <sqlalchemy.orm.session.ContextSession object at 0x000001F99B7A7A00>
              │            └ 2
              └ <function upgrade at 0x000001F99A6C6D40>

  File "C:\Program Files\Python310\lib\site-packages\flexget\components\backlog\db.py", line 74, in upgrade
    if not row['json']:
           └ (1, '{"description": "Uploader: XSbot / Category: TV-SD / Seeders: 19 / Leechers: 0 / Size: 275.48 MB / Snatched: 18 x times<...

  File "lib\\sqlalchemy\\cyextension\\resultproxy.pyx", line 54, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__

TypeError: tuple indices must be integers or slices, not str

**Comment by Zhongz0r** [comment]
ok removed the one line in the backlog table using db browser. 👯
