### ISSUE TITLE
Trakt_lookup crash?

### ISSUE THREAD

**Issue by leetwanker** [Flexget/Flexget#667]
2015-12-01 00:00 DEBUG    manager                       Figuring out config load paths
2015-12-01 00:00 DEBUG    manager                       Found config: /home/osmc/.flexget/config.yml
2015-12-01 00:00 DEBUG    manager                       Config file /home/osmc/.flexget/config.yml selected
2015-12-01 00:01 INFO     series        HDTV-Shows      Timeframe expired, releasing quality restriction.
2015-12-01 00:01 INFO     series        HDTV-Shows      identified_by has locked in to type `ep` for Superstore (2016)
2015-12-01 00:01 INFO     parser_internal HDTV-Shows      Title `Superstore (2016)` looks like series `Superstore (2016)` but cannot find any series numbering.
2015-12-01 00:02 INFO     download      HDTV-Shows      Downloading: Fargo.S02E08.HDTV.x264-FLEET.mp4
2015-12-01 00:02 INFO     download      HDTV-Shows      Downloading: Legends.2014.S02E04.HDTV.x264-KILLERS.mp4
2015-12-01 00:02 INFO     download      HDTV-Shows      Downloading: Superstore.S01E02.HDTV.x264-FLEET.mp4
2015-12-01 00:03 INFO     deluge        HDTV-Shows      Connecting to daemon at localhost:58846..
2015-12-01 00:03 INFO     deluge        HDTV-Shows      Connected to daemon at 127.0.0.1:58846..
2015-12-01 00:03 INFO     deluge        HDTV-Shows      Fargo.S02E08.HDTV.x264-FLEET.mp4 successfully added to deluge.
2015-12-01 00:03 INFO     deluge        HDTV-Shows      Legends.2014.S02E04.HDTV.x264-KILLERS.mp4 successfully added to deluge.
2015-12-01 00:03 INFO     deluge        HDTV-Shows      Superstore.S01E02.HDTV.x264-FLEET.mp4 successfully added to deluge.
2015-12-01 00:03 INFO     deluge        HDTV-Shows      Connection lost to daemon at localhost:58846 reason: Connection was closed cleanly.
2015-12-01 00:03 INFO     exec          HDTV-Shows      Stdout: Sending action: Notification(HDTV-Shows: ACCEPTED,Fargo (2014) - S02E08 - Loplop,30000,/home/osmc/flex.png)\n
2015-12-01 00:03 INFO     exec          HDTV-Shows      Stdout: Sending action: Notification(HDTV-Shows: ACCEPTED,Legends (2014) - S02E04 - The Legend of Ilyana Zakayeva,30000,/home/osmc/flex.png)\n
2015-12-01 00:03 ERROR    lazy_lookup   HDTV-Shows      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/trakt_lookup.py", line 190, in lazy_episode_lookup
    episode = series.get_episode(entry['series_season'], entry['series_episode'])
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_trakt.py", line 394, in get_episode
    episode = TraktEpisode(data)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_trakt.py", line 288, in __init__
    self.update(trakt_episode)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_trakt.py", line 300, in update
    self.first_aired = dateutil_parse(trakt_episode.get('first_aired'), ignoretz=True)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 392, in parse
    res = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 492, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 174, in split
    return list(cls(s))
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 171, in next
    return self.__next__()  # Python 2.x support
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 164, in __next__
    token = self.get_token()
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 82, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by gazpachoking** [comment]
Just found this right as you were posting. Should be fixed in 33375ff
