### ISSUE TITLE
Unhandled error in TMDB lookup

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#671]
Unhandled error in case a crappy title was received (due to my magical title manipulations)
```
2015-12-03 09:54 VERBOSE  imdb_lookup   download-movie-task Imdb lookup failed for '' 1995   \ jumanji.1995.720.hebits
2015-12-03 09:54 ERROR    lazy_lookup   download-movie-task Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flexget\utils\lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\tmdb_lookup.py", line 60, in lazy_loader
    session=session)
  File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 304, in lookup
    result = _first_result(tmdb3.tmdb_api.searchMovie(title.lower(), adult=True, year=year))
  File "C:\Python27\lib\site-packages\tmdb3\tmdb_api.py", line 133, in searchMovie
    return MovieSearchResult(Request('search/movie', **kwargs), locale=locale)
  File "C:\Python27\lib\site-packages\tmdb3\tmdb_api.py", line 162, in __init__
    lambda x: Movie(raw=x, locale=locale))
  File "C:\Python27\lib\site-packages\tmdb3\pager.py", line 109, in __init__
    super(PagedRequest, self).__init__(self._getpage(1), 20)
  File "C:\Python27\lib\site-packages\tmdb3\pager.py", line 62, in __init__
    self._data = list(iterable)
  File "C:\Python27\lib\site-packages\tmdb3\pager.py", line 113, in _getpage
    res = req.readJSON()
  File "C:\Python27\lib\site-packages\tmdb3\cache.py", line 131, in __call__
    data = self.func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\tmdb3\request.py", line 118, in readJSON
    data = json.load(self.open())
  File "C:\Python27\lib\site-packages\tmdb3\request.py", line 104, in open
    return urllib2.urlopen(self)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11001] getaddrinfo failed>
```

**Comment by crawln45** [comment]
Seems like a DNS issue.

**Comment by liiight** [comment]
Yeah, I'm having some weird dns stuff with my network lately, raising up all kinds of shit.

**Comment by crawln45** [comment]
Yeah not sure what to do there. Might be able to put a catch in there for that. But dunno.

**Comment by liiight** [comment]
Yeah,  that's what I was thinking. Doesn't require something fancier than that IMO.

**Comment by gazpachoking** [comment]
Feels like maybe the tmdb library should be capturing any network issues itself.

**Comment by crawln45** [comment]
I agree @gazpachoking. But most packages I've seen don't. So I've come to the resolution check it yourself.

**Comment by niawag** [comment]
Hi, it seems I'm having the same kind of error from time to time, here is my log: 
```
2016-01-19 17:48 ERROR    lazy_lookup   movie_auto_dl_h264_h Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/metainfo/tmdb_lookup.py", line 60, in lazy_loader
    session=session)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tmdb.py", line 298, in lookup
    ApiTmdb.get_movie_details(movie, session)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/flexget/plugins/api_tmdb.py", line 345, in get_movie_details
    posters = result.posters
  File "/usr/local/flexget/env/lib/python2.7/site-packages/tmdb3/util.py", line 152, in __get__
    self.poller.__get__(inst, owner)()
  File "/usr/local/flexget/env/lib/python2.7/site-packages/tmdb3/util.py", line 80, in __call__
    self.apply(req.readJSON())
  File "/usr/local/flexget/env/lib/python2.7/site-packages/tmdb3/cache.py", line 131, in __call__
    data = self.func(*args, **kwargs)
  File "/usr/local/flexget/env/lib/python2.7/site-packages/tmdb3/request.py", line 118, in readJSON
    data = json.load(self.open())
  File "/usr/local/flexget/env/lib/python2.7/site-packages/tmdb3/request.py", line 104, in open
    return urllib2.urlopen(self)
  File "/usr/local/python/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/python/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/python/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/local/python/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/python/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```
If I get it correctly this is a network problem on my side, should it result in a crash or just an Error in the log file?

**Comment by crawln45** [comment]
If there's no crash. there's no crash log.
