### ISSUE TITLE
Tvmaze lookup crashes when show is not found

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#674]
2015-12-04 02:46 ERROR lazy_lookup Series-Premieres Unhandled error in lazy lookup plugin
2015-12-04 02:46 CRITICAL manager Series-Premieres An unexpected crash has occurred. Writing crash report to /home/wolfgang/.download/flexget/crash_report.2015.12.04.024644542354.log
2015-12-04 02:46 DEBUG manager Series-Premieres Traceback:
Traceback (most recent call last):
File "/home/wolfgang/.download/flexget/flexget/utils/lazy_dict.py", line 36, in getitem
func(self.store)
File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/tvmaze_lookup.py", line 133, in lazy_series_lookup
entry.update_using_map(self.series_map, series)
File "/home/wolfgang/.download/flexget/flexget/entry.py", line 262, in update_using_map
v = value(source_item)
File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/tvmaze_lookup.py", line 85, in 
'tvmaze_series_airdays': lambda show: show.schedule.get('days'),
AttributeError: 'NoneType' object has no attribute 'schedule'

**Comment by liiight** [comment]
2015-12-04 02:46 ERROR    lazy_lookup   Series-Premieres Unhandled error in lazy lookup plugin
2015-12-04 02:46 CRITICAL manager       Series-Premieres An unexpected crash has occurred. Writing crash report to /home/wolfgang/.download/flexget/crash_report.2015.12.04.024644542354.log
2015-12-04 02:46 DEBUG    manager       Series-Premieres Traceback:
Traceback (most recent call last):
  File "/home/wolfgang/.download/flexget/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/tvmaze_lookup.py", line 133, in lazy_series_lookup
    entry.update_using_map(self.series_map, series)
  File "/home/wolfgang/.download/flexget/flexget/entry.py", line 262, in update_using_map
    v = value(source_item)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/tvmaze_lookup.py", line 85, in <lambda>
    'tvmaze_series_airdays': lambda show: show.schedule.get('days'),
AttributeError: 'NoneType' object has no attribute 'schedule'

**Comment by liiight** [comment]
Not fully fixed yet.
