### ISSUE TITLE
Tvmaze api crash on certain shows

### ISSUE THREAD

**Issue by marcoacarvalho** [Flexget/Flexget#698]
2015-12-11 22:35 DEBUG    est_released  search series   The Last Ship S03E01
2015-12-11 22:35 DEBUG    est_movies    search series   Unable to check release for The Last Ship S03E01, tmdb_release field is not defined
2015-12-11 22:35 DEBUG    est_series_tvmaze search series   Searching TVMaze for airdate of The Last Ship season 3 episode 1
2015-12-11 22:35 DEBUG    est_series_tvmaze search series   series_episode: 1
2015-12-11 22:35 DEBUG    est_series_tvmaze search series   show_name: The Last Ship
2015-12-11 22:35 DEBUG    est_series_tvmaze search series   series_name: The Last Ship
2015-12-11 22:35 DEBUG    est_series_tvmaze search series   series_season: 3
2015-12-11 22:35 DEBUG    api_tvmaze    search series   searching db tvmaze_series for the values [(u'tvdb_id', None), (u'tvmaze_id', None), (u'name', u'The Last Ship'), (u'tvrage_id', None)]
2015-12-11 22:35 DEBUG    api_tvmaze    search series   series The Last Ship is expired: False
2015-12-11 22:35 DEBUG    api_tvmaze    search series   returning series The Last Ship from cache
2015-12-11 22:35 DEBUG    api_tvmaze    search series   searching for episode of show The Last Ship in cache
2015-12-11 22:35 DEBUG    api_tvmaze    search series   fetching episode 1 season 3 for series_id 21 for tvmaze
2015-12-11 22:35 DEBUG    api_tvmaze    search series   creating new episode for show The Last Ship
2015-12-11 22:35 CRITICAL task          search series   BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'read'
2015-12-11 22:35 CRITICAL manager       search series   An unexpected crash has occurred. Writing crash report to /home/marco/.flexget/crash_report.2015.12.11.223523795098.log
2015-12-11 22:35 DEBUG    manager       search series   Traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 268, in on_task_input
    entries = self.estimated(entries)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 190, in estimated
    est_date = estimator.estimate(entry)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 52, in estimate
    episode = lookup(**kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/api_tvmaze.py", line 397, in episode_lookup
    episode = TVMazeEpisodes(pytvmaze_episode, series.tvmaze_id)
  File "<string>", line 4, in __init__
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/api_tvmaze.py", line 159, in __init__
    self.update(episode)
  File "/usr/lib/python2.7/site-packages/flexget/plugins/api_tvmaze.py", line 176, in update
    self.airstamp = parser.parse(episode.airstamp)
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 392, in parse
    res = self._parse(timestr, **kwargs)
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 492, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 174, in split
    return list(cls(s))
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 171, in next
    return self.__next__()  # Python 2.x support
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 164, in __next__
    token = self.get_token()
  File "/usr/lib/python2.7/site-packages/dateutil/parser.py", line 82, in get_token
    nextchar = self.instream.read(1)
AttributeError: 'NoneType' object has no attribute 'read'
2015-12-11 22:35 WARNING  task          search series   Aborting task (plugin: discover)

**Comment by crawln45** [comment]
Mind making sure this is the newest version of flexget. As I feel we addressed this already in the newer version. If not let us know.

**Comment by marcoacarvalho** [comment]
[marco@archdesktop ~]$ flexget -V
1.2.401
Latest release: 1.2.405

**Comment by crawln45** [comment]
Yes please upgrade to the latest. should fix your issue.

**Comment by marcoacarvalho** [comment]
I just relized that is not only with cancelled shows, it's something else....

2015-12-11 22:54 DEBUG    est_released  search series   The Americans S04E01
2015-12-11 22:54 DEBUG    est_movies    search series   Unable to check release for The Americans S04E01, tmdb_release field is not defined
2015-12-11 22:54 DEBUG    est_series_tvmaze search series   Searching TVMaze for airdate of The Americans season 4 episode 1
2015-12-11 22:54 DEBUG    est_series_tvmaze search series   series_episode: 1
2015-12-11 22:54 DEBUG    est_series_tvmaze search series   show_name: The Americans
2015-12-11 22:54 DEBUG    est_series_tvmaze search series   series_name: The Americans
2015-12-11 22:54 DEBUG    est_series_tvmaze search series   series_season: 4
2015-12-11 22:54 DEBUG    api_tvmaze    search series   searching db tvmaze_series for the values [(u'tvdb_id', None), (u'tvmaze_id', None), (u'name', u'The Americans'), (u'tvrage_id', None)]
2015-12-11 22:54 DEBUG    api_tvmaze    search series   series The Americans is expired: False
2015-12-11 22:54 DEBUG    api_tvmaze    search series   returning series The Americans from cache
2015-12-11 22:54 DEBUG    api_tvmaze    search series   searching for episode of show The Americans in cache
2015-12-11 22:54 DEBUG    api_tvmaze    search series   fetching episode 1 season 4 for series_id 157 for tvmaze
2015-12-11 22:54 DEBUG    api_tvmaze    search series   creating new episode for show The Americans
2015-12-11 22:54 CRITICAL task          search series   BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'read'

**Comment by marcoacarvalho** [comment]
Ok, as it's late night here, I will do that tomorrow and let you know.

**Comment by marcoacarvalho** [comment]
As stated by crawln45, tha latest version (1.2.405) corrects this problem.
Closing the issue.
