### ISSUE TITLE
rTorrent plugin error with scgi uri

### ISSUE THREAD

**Issue by m-hume** [Flexget/Flexget#706]
https://github.com/Flexget/Flexget/commit/1f4ef0e1db1928acbe623877f7f7a37f2a05b8f5
this commit produces the following error with a rtorrent uri in the config like
```
    rtorrent:
      uri: scgi://localhost:5000  
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_rtorrent.py", line 405, in on_task_start
    if client.version < [0, 9, 2]:
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_rtorrent.py", line 262, in version
    return [int(v) for v in self._server.system.client_version().split('.')]
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_rtorrent.py", line 147, in __request
    response = self.__transport.request(self.__host, self.__handler, request, verbose=self.__verbose)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_rtorrent.py", line 63, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_rtorrent.py", line 80, in single_request
    addr_info = socket.getaddrinfo(host, int(port), socket.AF_INET, socket.SOCK_STREAM)
TypeError: int() argument must be a string or a number, not 'NoneType'
```
This error occurs due to `urlparse()` being run on just the hostname on line 76 of `def single_request`
as there is no scheme, port etc. this fails

**Comment by stevezau** [comment]
Hmm, I i'll fix this shortly.

**Comment by stevezau** [comment]
That should fix it.. Good to see someone using the rtorrent plugin :+1:

**Comment by m-hume** [comment]
Nice one!
Just checked out your fix and it wasn't far off how i patched it (though you did it as a oneliner!)
Once i'm a bit more familiar with the source i'll start providing fixes rather than just raising issues hopefully.
Do you know of any info on setting up the development branch and being able to run the tests?

**Comment by stevezau** [comment]
take a look at http://flexget.com/wiki/GitHubInstall

if you join the irc channel we can help you out.
