### ISSUE TITLE
Unhandled error in plugin discover: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by marcoacarvalho** [Flexget/Flexget#733]
(flexget)[marco@archdesktop ~]$ flexget -V
1.2.413
You are on the latest release.

Same error occur with version 1.2.405
```
2015-12-20 19:25 DEBUG    est_released  search series   The Vampire Diaries S07E10
2015-12-20 19:25 DEBUG    est_movies    search series   Unable to check release for The Vampire Diaries S07E10, tmdb_release field is not defined
2015-12-20 19:25 DEBUG    est_series_tvmaze search series   Searching TVMaze for airdate of The Vampire Diaries season 7 episode 10
2015-12-20 19:25 DEBUG    est_series_tvmaze search series   series_episode: 10
2015-12-20 19:25 DEBUG    est_series_tvmaze search series   show_name: The Vampire Diaries
2015-12-20 19:25 DEBUG    est_series_tvmaze search series   series_name: The Vampire Diaries
2015-12-20 19:25 DEBUG    est_series_tvmaze search series   series_season: 7
2015-12-20 19:25 DEBUG    api_tvmaze    search series   returning search params for series lookup: {u'tvdb_id': None, u'tvmaze_id': None, u'name': u'The Vampire Diaries', u'tvrage_id': None}
2015-12-20 19:25 DEBUG    api_tvmaze    search series   searching db tvmaze_series for the values [(u'tvdb_id', None), (u'tvmaze_id', None), (u'name', u'The Vampire Diaries'), (u'tvrage_id', None)]
2015-12-20 19:25 DEBUG    api_tvmaze    search series   series The Vampire Diaries is expired: True
2015-12-20 19:25 DEBUG    api_tvmaze    search series   trying to fetch series The Vampire Diaries from pytvmaze
2015-12-20 19:25 DEBUG    api_tvmaze    search series   series The Vampire Diaries is already in cache, checking for expiration
2015-12-20 19:25 DEBUG    api_tvmaze    search series   series The Vampire Diaries is expired: True
2015-12-20 19:25 DEBUG    api_tvmaze    search series   searching for episode of show The Vampire Diaries in cache
2015-12-20 19:25 DEBUG    api_tvmaze    search series   episode 10, season 7 for series 63 is expired.days overdue for update: True
2015-12-20 19:25 DEBUG    api_tvmaze    search series   fetching episode 10 season 7 for series_id 63 for tvmaze
2015-12-20 19:25 DEBUG    api_tvmaze    search series   found expired episode 488561 in cache, refreshing data.
2015-12-20 19:25 CRITICAL task          search series   BUG: Unhandled error in plugin discover: can't compare offset-naive and offset-aware datetimes
2015-12-20 19:25 CRITICAL manager       search series   An unexpected crash has occurred. Writing crash report to /home/marco/.flexget/crash_report.2015.12.20.192523165360.log
2015-12-20 19:25 DEBUG    manager       search series   Traceback:
Traceback (most recent call last):
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 268, in on_task_input
    entries = self.estimated(entries)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 190, in estimated
    est_date = estimator.estimate(entry)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 52, in estimate
    episode = lookup(**kwargs)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/flexget/utils/sqlalchemy_utils.py", line 137, in __exit__
    self.commit()
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 813, in commit
    self.transaction.commit()
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 632, in _emit_update_statements
    lambda rec: (
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 461, in _collect_update_commands
    value, state.committed_state[propkey]) is not True:
  File "/home/marco/.virtualenvs/flexget/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 279, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
2015-12-20 19:25 WARNING  task          search series   Aborting task (plugin: discover)
```

**Comment by liiight** [comment]
Please test this after the next release and notify me if it fixes the issue.

**Comment by lildadou** [comment]
@liiight It fixes my case, thanks

**Comment by marcoacarvalho** [comment]
Yes, it's fixed!
Thanks @liiight

**Comment by lepinkainen** [comment]
You could use pytz and make flexget time timezone-aware instead?

**Comment by liiight** [comment]
It'll be inconsistent with other plugins like Trakt. Why do you want it aware?
