### ISSUE TITLE
Aborted Task because 'Unhandled error in plugin rtorrent: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by jarrekmaar** [Flexget/Flexget#736]
My summary email gives me the error mentioned in the title for all my tasks which use the rtorrent plugin. It says that Flexget downloaded the relevant entries, but they do not appear in rtorrent.

**Comment by stevezau** [comment]
Can you please attach the crash report? I need the stack trace.

**Comment by stevezau** [comment]
also what version of flexget are you on? 

flexget -V

**Comment by jarrekmaar** [comment]
Crash Report (This is just the end - the rest of the file has sensitive URLs):
```
2015-12-21 19:54 VERBOSE  details       bB Freeleech    Summary - Accepted: 13 (Rejected: 0 Undecided: 0 Failed: 13)
2015-12-21 19:54 CRITICAL task          bB Freeleech    BUG: Unhandled error in plugin rtorrent: 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "/media/sdaj/jarrekmaar/private/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/media/sdaj/jarrekmaar/private/flexget/local/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/media/sdaj/jarrekmaar/private/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 471, in on_task_output
    self.add_entry(client, entry, options, start=config['start'], mkdir=config['mkdir'])
  File "/media/sdaj/jarrekmaar/private/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 574, in add_entry
    if client.torrent(entry['torrent_info_hash']):
  File "/media/sdaj/jarrekmaar/private/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 299, in torrent
    fields = self._clean_fields(fields)
  File "/media/sdaj/jarrekmaar/private/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 255, in _clean_fields
    fields[fields.index(field)] = field.replace('_', '.')
TypeError: 'tuple' object does not support item assignment
```
Flexget Version
```
flexget -V
1.2.414
You are on the latest release.
```

**Comment by stevezau** [comment]
That should fix it.. new Flexget version will be auto built and released at midnight.

In the meantime you can checkout the source from git and test.

**Comment by jarrekmaar** [comment]
It did - many thanks!
