### ISSUE TITLE
Unhandled error in plugin proper_movies

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#737]
2015-12-22 13:47 CRITICAL task          HD720P          BUG: Unhandled error in plugin proper_movies: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flexget\task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\filter\proper_movies.py", line 95, in on_task_filter
    imdb_id = imdb_lookup.imdb_id_lookup(movie_title=parser.name, raw_title=entry['title'])
  File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\imdb_lookup.py", line 273, in imdb_id_lookup
    self.lookup(fake_entry)
  File "C:\Python27\lib\site-packages\flexget\plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "C:\Python27\lib\site-packages\flexget\utils\imdb.py", line 244, in parse
    self.year = int(name_elem.find('a').text)
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by crack00r** [comment]
2015-12-22 14:04 INFO     imdb          FullHD1080P     Didn't accept `Men & Chicken` because of rule(s) min_score (6.7 < 8.5)
2015-12-22 14:04 VERBOSE  imdb_lookup   FullHD1080P     Parsing imdb for `Escobar.-.Paradise Lost 2014 1080p DTSHD BluRay AVC Remux pmHD`
2015-12-22 14:04 CRITICAL task          FullHD1080P     BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'text'
2015-12-22 14:04 CRITICAL manager       FullHD1080P     An unexpected crash has occurred. Writing crash report to C:\Python27\Scripts\crash_report.2015.12.22.140405695000.log
2015-12-22 14:04 WARNING  task          FullHD1080P     Aborting task (plugin: imdb)

**Comment by liiight** [comment]
what flexget ver you on?
`flexget -V`

**Comment by crack00r** [comment]
C:\Python27\Scripts>flexget -V
1.2.414
Latest release: 1.2.415

C:\Python27\Scripts>

**Comment by gazpachoking** [comment]
Believe this was fixed in 1.2.415

**Comment by crack00r** [comment]
I give it a try

**Comment by crack00r** [comment]
helps... thx!
