### ISSUE TITLE
Unhandled error in lazy lookup plugin

### ISSUE THREAD

**Issue by lostsubstance** [Flexget/Flexget#738]
Flexget v1.2.415

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flexget\utils\lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\imdb_lookup.py", line 235, in lazy_loader
    self.lookup(entry)
  File "C:\Python27\lib\site-packages\flexget\plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "C:\Python27\lib\site-packages\flexget\utils\imdb.py", line 244, in parse
    self.year = int(name_elem.find('a').text)
AttributeError: 'NoneType' object has no attribute 'text'
```

and

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flexget\utils\lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\tmdb_lookup.py", line 60, in lazy_loader
    session=session)
  File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 298, in lookup
    ApiTmdb.get_movie_details(movie, session)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 341, in get_movie_details
    movie.update_from_object(result)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 120, in update_from_object
    self.translated = len(update_object.translations) > 0
  File "C:\Python27\lib\site-packages\tmdb3\util.py", line 152, in __get__
    self.poller.__get__(inst, owner)()
  File "C:\Python27\lib\site-packages\tmdb3\util.py", line 80, in __call__
    self.apply(req.readJSON())
  File "C:\Python27\lib\site-packages\tmdb3\cache.py", line 131, in __call__
    data = self.func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\tmdb3\request.py", line 118, in readJSON
    data = json.load(self.open())
  File "C:\Python27\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by gazpachoking** [comment]
That traceback looks like from before version 215 https://github.com/Flexget/Flexget/blob/1.2.415/flexget/utils/imdb.py#L244 This error was addressed in that version.

**Comment by lostsubstance** [comment]
i captured the trace on 414, but it crashed again on 415.

**Comment by lostsubstance** [comment]
this is one from 415
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flexget\utils\lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\tmdb_lookup.py", line 60, in lazy_loader
    session=session)
  File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 298, in lookup
    ApiTmdb.get_movie_details(movie, session)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 341, in get_movie_details
    movie.update_from_object(result)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 120, in update_from_object
    self.translated = len(update_object.translations) > 0
  File "C:\Python27\lib\site-packages\tmdb3\util.py", line 152, in __get__
    self.poller.__get__(inst, owner)()
  File "C:\Python27\lib\site-packages\tmdb3\util.py", line 80, in __call__
    self.apply(req.readJSON())
  File "C:\Python27\lib\site-packages\tmdb3\cache.py", line 131, in __call__
    data = self.func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\tmdb3\request.py", line 118, in readJSON
    data = json.load(self.open())
  File "C:\Python27\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by liiight** [comment]
does still still happens to you?

**Comment by tarzasai** [comment]
on my production server flexget was still at 1.2.297, now with 1.2.424 the movie search task fails with this (on all titles):
```
2016-01-09 23:35 VERBOSE  imdb_lookup   get_movies      Found http://www.imdb.com/title/tt1336006/?ref_=fn_ft_tt_2
2016-01-09 23:35 VERBOSE  imdb_lookup   get_movies      Parsing imdb for `The Revenant 2009 1080p BluRay x264 aAF`
2016-01-09 23:35 ERROR    lazy_lookup   get_movies      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget-1.2.424-py2.7.egg\flexget\utils\lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "c:\python27\lib\site-packages\flexget-1.2.424-py2.7.egg\flexget\plugins\metainfo\imdb_lookup.py", line 235, in lazy_loader
    self.lookup(entry)
  File "c:\python27\lib\site-packages\flexget-1.2.424-py2.7.egg\flexget\plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget-1.2.424-py2.7.egg\flexget\utils\database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget-1.2.424-py2.7.egg\flexget\plugins\metainfo\imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "c:\python27\lib\site-packages\flexget-1.2.424-py2.7.egg\flexget\plugins\metainfo\imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "c:\python27\lib\site-packages\flexget-1.2.424-py2.7.egg\flexget\utils\imdb.py", line 243, in parse
    self.name = name_elem.find(text=True, recursive=False).strip()
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by crawln45** [comment]
This was fixed today.

**Comment by tarzasai** [comment]
1.2.425? duh, I'll wait.

**Comment by PhoneixS** [comment]
I have tested it with 1.2.426 and the problem seems to be fixed. I had the same problem before upgrading flexget.

**Comment by crawln45** [comment]
Not added some more checks in recently. Not sure if they've been pushed to master. Should keep it from crashing with people try to lookup movies that haven't aired yet, and series which they shouldn't be using imdb for anyway.

**Comment by liiight** [comment]
I guess this can be closed now?

**Comment by lostsubstance** [comment]
1.2.429:

```
2016-01-17 22:54 ERROR    lazy_lookup   getMovies       Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flexget\utils\lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\tmdb_lookup.py", line 60, in lazy_loader
    session=session)
  File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 298, in lookup
    ApiTmdb.get_movie_details(movie, session)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 341, in get_movie_details
    movie.update_from_object(result)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 120, in update_from_object
    self.translated = len(update_object.translations) > 0
  File "C:\Python27\lib\site-packages\tmdb3\util.py", line 152, in __get__
    self.poller.__get__(inst, owner)()
  File "C:\Python27\lib\site-packages\tmdb3\util.py", line 80, in __call__
    self.apply(req.readJSON())
  File "C:\Python27\lib\site-packages\tmdb3\cache.py", line 131, in __call__
    data = self.func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\tmdb3\request.py", line 118, in readJSON
    data = json.load(self.open())
  File "C:\Python27\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by crawln45** [comment]
@lostsubstance That has nothing to do with this ticket. Please make another. And seems that tmdb probably timed out on the request.

**Comment by lostsubstance** [comment]
its the same error i opened this ticket on. this error is filling my directory with hundreds of these crash reports.

**Comment by crawln45** [comment]
What movie is it crashing on. I can't see that in the logs.

**Comment by lostsubstance** [comment]
seems like all the movies in the queue do this, i import from a imdb watch list.


ex:

```
2016-01-17 23:32 TRACE    entry         getMovies       ENTRY SET: title = u'Evangelion: 2.0 You Can (Not) Advance'                                                                             2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 DEBUG    headers       getMovies       Adding Referer: http://torcache.net/                                                                                                    2016-01-17 23:32 DEBUG    headers       getMovies       Adding Accept-Encoding: deflate, gzip                                                                                                   2016-01-17 23:32 DEBUG    headers       getMovies       Adding User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36         2016-01-17 23:32 ERROR    lazy_lookup   getMovies       Unhandled error in lazy lookup plugin                                                                                                   2016-01-17 23:32 CRITICAL manager       getMovies       An unexpected crash has occurred. Writing crash report to C:\Users\Jonathan\flexget\crash_report.2016.01.17.233237530000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently usingversion 1.2.429                                                                                                                                                                                  2016-01-17 23:32 DEBUG    manager       getMovies       Traceback:                                                                                                                              Traceback (most recent call last):                                                                                                                                                                File "C:\Python27\lib\site-packages\flexget\utils\lazy_dict.py", line 36, in __getitem__                                                                                                          func(self.store)                                                                                                                                                                              File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\tmdb_lookup.py", line 60, in lazy_loader                                                                                             session=session)                                                                                                                                                                              File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 27, in wrapper                                                                                                               return func(*args, **kwargs)                                                                                                                                                                  File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 298, in lookup                                                                                                             ApiTmdb.get_movie_details(movie, session)                                                                                                                                                     File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 341, in get_movie_details                                                                                                  movie.update_from_object(result)                                                                                                                                                              File "C:\Python27\lib\site-packages\flexget\plugins\api_tmdb.py", line 120, in update_from_object                                                                                                 self.translated = len(update_object.translations) > 0                                                                                                                                         File "C:\Python27\lib\site-packages\tmdb3\util.py", line 152, in __get__                                                                                                                          self.poller.__get__(inst, owner)()                                                                                                                                                            File "C:\Python27\lib\site-packages\tmdb3\util.py", line 80, in __call__                                                                                                                          self.apply(req.readJSON())                                                                                                                                                                    File "C:\Python27\lib\site-packages\tmdb3\cache.py", line 131, in __call__                                                                                                                        data = self.func(*args, **kwargs)                                                                                                                                                             File "C:\Python27\lib\site-packages\tmdb3\request.py", line 118, in readJSON                                                                                                                      data = json.load(self.open())                                                                                                                                                                 File "C:\Python27\lib\json\__init__.py", line 290, in load                                                                                                                                        **kw)                                                                                                                                                                                         File "C:\Python27\lib\json\__init__.py", line 338, in loads                                                                                                                                       return _default_decoder.decode(s)                                                                                                                                                             File "C:\Python27\lib\json\decoder.py", line 366, in decode                                                                                                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                                             File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode                                                                                                                                   raise ValueError("No JSON object could be decoded")                                                                                                                                         ValueError: No JSON object could be decoded                                                                                                                                                     2016-01-17 23:32 DEBUG    emit_movie_queue getMovies       Added title and IMDB id to new entry: Evangelion: 2.0 You Can (Not) Advance - tt0860906                                              
```

**Comment by lostsubstance** [comment]
i took out the headers config and the crashes went away...

```
headers:
      User-Agent: 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36'
      Referer: "http://torcache.net/"
      Accept-Encoding: "deflate, gzip"
```

this was to workaround torcache serving html pages instead of torrent files... wonder if its still needed.

**Comment by crawln45** [comment]
Well setting the headers to that could cause some issues. Mainly using the Encoding. 2. for torcache all you need is user-agent set to mozilla/5.0

**Comment by lostsubstance** [comment]
Thanks
