### ISSUE TITLE
Plugin series crash: 'NoneType' object has no attribute 'node_idx'

### ISSUE THREAD

**Issue by xathin** [Flexget/Flexget#745]
This has been crashing for the past few days, updated to 415 with no change.

```
2015-12-24 09:00 CRITICAL task          download-series-discover BUG: Unhandled error in plugin series: 'NoneType' object has no attribute 'node_idx'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 976, in on_task_metainfo
    self.parse_series(task.entries, series_name, series_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1092, in parse_series
    parsed = get_plugin_by_name('parsing').instance.parse_series(entry['title'], name=series_name, **params)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/plugin_parsing.py", line 70, in parse_series
    return parser.parse_series(data, name=name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_guessit.py", line 318, in parse_series
    guess_result = guessit.guess_file_info(data, options=guessit_options, type=parse_type)
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 291, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 111, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 118, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=options, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/transfo/guess_bonus_features.py", line 68, in process
    if same_group(series, season[0]):
  File "/usr/local/lib/python2.7/dist-packages/guessit/transfo/guess_bonus_features.py", line 46, in same_group
    return g1.node_idx[:2] == g2.node_idx[:2]
AttributeError: 'NoneType' object has no attribute 'node_idx'
```

**Comment by xathin** [comment]
Is this being looked into?

**Comment by crawln45** [comment]
Seems to be an issue with guessit. Just for expediency you can cross post
this issue on the guessit github referencing this post.

**Comment by xathin** [comment]
Is it possible that a newer version of guessit may correct the problem? Currently the newest version is 1.0.2, but Flexget has a requirement of guessit<0.10.4,>=0.9.3, which installs version 0.10.3. Unfortunately I am not savvy enough to make the necessary changes myself, but if someone would be willing to let me know what needs to be changed to test other versions of guessit, I would be willing to see if a newer version would be capable of correcting the error.

**Comment by xathin** [comment]
I'm not sure why or how it makes any difference, but when I run the task through the daemon (as scheduled or from cli), it fails every time. However, when I run the task when the daemon is **not** running, the task seems to run just fine with no errors.

**Comment by crawln45** [comment]
@gazpachoking Got any thoughts in this matter.

**Comment by liiight** [comment]
Did you try this with the new version of guessit?

**Comment by cvium** [comment]
I don't think this issue is relevant anymore as we now use guessit 2.0.4. Update and re-open if it continues to fail.
