### ISSUE TITLE
[tvmaze]  IDNotFound crashing

### ISSUE THREAD

**Issue by bagobones** [Flexget/Flexget#749]
Was trying to use TVMaze lookup in addition to TVDB and trakt to check if a series had ended.

TVMaze is the only one to have an issue.
```
2015-12-26 21:52 ERROR    lazy_lookup   Series_End      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/tvmaze_lookup.py", line 130, in lazy_series_lookup
    series = series_lookup(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 394, in series_lookup
    pytvmaze_show = get_show(**prepared_params)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 399, in get_show
    return show_main_info(lookup_tvdb(tvdb_id).id, embed=embed)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 532, in lookup_tvdb
    raise IDNotFound('TVdb id ' + str(tvdb_id) + ' not found')
IDNotFound: u'TVdb id 299652 not found'
```
@liiight

**Comment by liiight** [comment]
Hmm. Any chance running this with debug logging please?

**Comment by bagobones** [comment]
'''
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      returning search params for series lookup: {u'tvdb_id': 263011, u'tvmaze_id': None, u'name': u'Holme$
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      searching db tvmaze_series for the values [(u'tvdb_id', 263011), (u'tvmaze_id', None), (u'name', u'H$
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      did not find exact match for series Holmes Makes It Right in cache, looking in search table
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      searching lookup table using title Holmes Makes It Right
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      trying to fetch series Holmes Makes It Right from pytvmaze
2015-12-26 23:11 ERROR    lazy_lookup   Series_End      Unhandled error in lazy lookup plugin
2015-12-26 23:11 CRITICAL manager       Series_End      An unexpected crash has occurred. Writing crash report to /home/flexget/.flexget/crash_report.2015.1$
2015-12-26 23:11 DEBUG    manager       Series_End      Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/tvmaze_lookup.py", line 130, in lazy_series_lookup
    series = series_lookup(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 394, in series_lookup
    pytvmaze_show = get_show(**prepared_params)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 399, in get_show
    return show_main_info(lookup_tvdb(tvdb_id).id, embed=embed)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 532, in lookup_tvdb
    raise IDNotFound('TVdb id ' + str(tvdb_id) + ' not found')
IDNotFound: u'TVdb id 263011 not found'
'''
'''
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      returning search params for series lookup: {u'tvdb_id': 299681, u'tvmaze_id': None, u'name': u'Building The Ancient City', u'tvrage_id': None}
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      searching db tvmaze_series for the values [(u'tvdb_id', 299681), (u'tvmaze_id', None), (u'name', u'Building The Ancient City'), (u'tvrage_id', None)]
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      did not find exact match for series Building The Ancient City in cache, looking in search table
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      searching lookup table using title Building The Ancient City
2015-12-26 23:11 DEBUG    api_tvmaze    Series_End      trying to fetch series Building The Ancient City from pytvmaze
2015-12-26 23:11 ERROR    lazy_lookup   Series_End      Unhandled error in lazy lookup plugin
2015-12-26 23:11 CRITICAL manager       Series_End      An unexpected crash has occurred. Writing crash report to /home/flexget/.flexget/crash_report.2015.12.26.231139292193.log
2015-12-26 23:11 DEBUG    manager       Series_End      Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/tvmaze_lookup.py", line 130, in lazy_series_lookup
    series = series_lookup(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 394, in series_lookup
    pytvmaze_show = get_show(**prepared_params)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 399, in get_show
    return show_main_info(lookup_tvdb(tvdb_id).id, embed=embed)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 532, in lookup_tvdb
    raise IDNotFound('TVdb id ' + str(tvdb_id) + ' not found')
IDNotFound: u'TVdb id 299681 not found'
'''

**Comment by liiight** [comment]
Yeah, I see what the problem is. This might require a fix with pytvmaze, i'll push some there soon
