### ISSUE TITLE
A call to "APITVMaze.series_lookup" in api_tvmaze.py caused UnicodeDecodeError exception

### ISSUE THREAD

**Issue by programatix** [Flexget/Flexget#759]
Hi,

I'm using an ASUS router and I think it's fixed to "ascii' locale (or I do not know how to change it to utf-8). Anyway, recently I'm getting a number of error as below,
```
2016-01-03 06:30 CRITICAL task          NyaaTorrents    BUG: Unhandled error in plugin discover: 'ascii' codec can't decode byte 0xe2 in position 33: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 268, in on_task_input
    entries = self.estimated(entries)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/input/discover.py", line 190, in estimated
    est_date = estimator.estimate(entry)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/estimators/est_released.py", line 28, in estimate
    estimate = estimator(entry)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/estimators/est_release_series_tvmaze.py", line 52, in estimate
    episode = lookup(**kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/api_tvmaze.py", line 442, in episode_lookup
    series = APITVMaze.series_lookup(session=session, only_cached=only_cached, **lookup_params)
  File "/opt/lib/python2.7/site-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/opt/lib/python2.7/site-packages/flexget/plugins/api_tvmaze.py", line 393, in series_lookup
    pytvmaze_show = get_show(**prepared_params)
  File "/opt/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 416, in get_show
    show_web_channel, embed=embed)
  File "/opt/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 470, in _get_show_by_search
    return show_single_search(show=show_name, embed=embed)
  File "/opt/lib/python2.7/site-packages/pytvmaze/tvmaze.py", line 532, in show_single_search
    raise ShowNotFound('show name ' + '"' + string + '"' + ' not found')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 33: ordinal not in range(128)
```

I wish I could fix this myself but my knowledge on Linux + Python is really shallow. I hope someone out there pick this up and fix it.

Thanks in advance.

**Comment by liiight** [comment]
@gazpachoking do we even support devices with only ascii support?

**Comment by crawln45** [comment]
@liiight this has nothing to do with it being set to ascii but with the tvmaze package.

**Comment by liiight** [comment]
Right, I see that now. There's another issue open on this bug, I'll push a fix to pytvmaze asap

**Comment by programatix** [comment]
As of FlexGet 1.2.424 and pytvmaze 1.4.4, this issue has been fixed. Thanks @liiight.
