### ISSUE TITLE
TvMaze plugin fails when no tvdb id is found

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#765]
```
2015-12-31 00:13 WARNING  tmdb_lookup   MYTASK-tv       TMDB lookup failed for Great Barrier Reef with David Attenborough S01E01 720p HDTV x264-FTP
2015-12-31 00:13 ERROR    lazy_lookup   MYTASK-tv       Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/tvmaze_lookup.py", line 130, in lazy_series_lookup
    series = series_lookup(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvmaze.py", line 394, in series_lookup
    pytvmaze_show = get_show(**prepared_params)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 399, in get_show
    return show_main_info(lookup_tvdb(tvdb_id).id, embed=embed)
  File "/usr/local/lib/python2.7/dist-packages/pytvmaze/tvmaze.py", line 532, in lookup_tvdb
    raise IDNotFound('TVdb id ' + str(tvdb_id) + ' not found')
IDNotFound: u'TVdb id 304953 not found'
```

If pytvmaze doesn't find a TVdb ID it throws an exception(!) and the tvmaze_lookup plugin crashes.

**Comment by liiight** [comment]
what ver of pytvmaze you on? and flexget? this should not exist in latest code...

**Comment by lepinkainen** [comment]
Just updated last night, will see if this reappears.

**Comment by liiight** [comment]
yep, that is latest... weird
checking

**Comment by gazpachoking** [comment]
@lepinkainen Your traceback looks funny. It's still showing the line numbers from the old code, but displaying that line from the new code. Perhaps your .pyc somehow are out of sync? Try clearing those for pytvmaze and see if it helps.

**Comment by lepinkainen** [comment]
Fixed by updating flexget and pytvmaze, I'll reopen if this appears again.
