### ISSUE TITLE
[imdb] BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by DigitalConceptions** [Flexget/Flexget#773]
```
# flexget --version
1.2.425.dev
Latest release: 1.2.424
```

```
2016-01-08 23:31 DEBUG    imdb_lookup   Movies-Filtered movie `Eat the Rich: The Cannibal Murders` age 16 expires in 82 days
2016-01-08 23:31 DEBUG    imdb          Movies-Filtered Didn't accept `Eat the Rich: The Cannibal Murders` because of rule(s) min_score (2.6 < 5.5), min_votes (36 < 500)
2016-01-08 23:31 DEBUG    imdb_lookup   Movies-Filtered No title passed. Lookup for tt1762233
2016-01-08 23:31 VERBOSE  imdb_lookup   Movies-Filtered Parsing imdb for `Enchanted Kingdom 3D [2013] by Patrick Morris and Neil Nightingale - BD50 / Blu-ray / ISO / 1080p / 3D`
2016-01-08 23:31 DEBUG    requests      Movies-Filtered Fetching http://www.imdb.com/title/tt1762233/
2016-01-08 23:31 CRITICAL task          Movies-Filtered BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'
2016-01-08 23:31 CRITICAL manager       Movies-Filtered An unexpected crash has occurred. Writing crash report to /home/wolfgang/.download/flexget/crash_report.2016.01.08.233118907817.log
2016-01-08 23:31 DEBUG    manager       Movies-Filtered Traceback:
Traceback (most recent call last):
  File "/home/wolfgang/.download/flexget/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/home/wolfgang/.download/flexget/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/wolfgang/.download/flexget/flexget/plugins/filter/imdb.py", line 106, in on_task_filter
    lookup(entry)
  File "/home/wolfgang/.download/flexget/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/home/wolfgang/.download/flexget/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/home/wolfgang/.download/flexget/flexget/utils/imdb.py", line 243, in parse
    self.name = name_elem.find(text=True, recursive=False).strip()
AttributeError: 'NoneType' object has no attribute 'find'
2016-01-08 23:31 WARNING  task          Movies-Filtered Aborting task (plugin: imdb)
2016-01-08 23:31 DEBUG    cookies       Movies-Filtered Removing urllib2 opener
2016-01-08 23:31 DEBUG    backlog       Movies-Filtered Remembering all entries to backlog because of task abort.
```

**Comment by lepinkainen** [comment]
I'm having the exact same issue, maybe an another layout change in IMDb?

**Comment by alneven** [comment]
I have with version 1.2.422 also the same...

*# flexget -V
1.2.422
Latest release: 1.2.424*

**Comment by antivirtel** [comment]
Same here with the latest version: ```2016-01-09 09:04 ERROR    lazy_lookup   nC_movie-HUN    Unhandled error in lazy lookup plugin
2016-01-09 09:04 CRITICAL manager       nC_movie-HUN    An unexpected crash has occurred. Writing crash report to /home/osmc/.flexget/crash_report.2016.01.09.090402425088.log
2016-01-09 10:24 ERROR    lazy_lookup   nC_movie-HUN    Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 235, in lazy_loader
    self.lookup(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/imdb.py", line 243, in parse
    self.name = name_elem.find(text=True, recursive=False).strip()
AttributeError: 'NoneType' object has no attribute 'find'```

**Comment by crack00r** [comment]
same here, waitingfor update :)

**Comment by alneven** [comment]
Thanks for the quick fix, installed from github and it's working.

**Comment by alneven** [comment]
OMG
I have this again now...

'''
2016-01-23 18:57 ERROR    lazy_lookup   get_favmoviesremux Unhandled error in lazy lookup plugin
2016-01-23 18:57 CRITICAL manager       get_favmoviesremux An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.01.23.185711908021.log
2016-01-23 18:57 ERROR    lazy_lookup   get_favmoviesremux Unhandled error in lazy lookup plugin
2016-01-23 18:57 CRITICAL manager       get_favmoviesremux An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.01.23.185714707263.log
2016-01-23 18:57 ERROR    lazy_lookup   get_favmoviesremux Unhandled error in lazy lookup plugin
2016-01-23 18:57 CRITICAL manager       get_favmoviesremux An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.01.23.185717670299.log
2016-01-23 18:57 CRITICAL task          get_movies   BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'
2016-01-23 18:57 CRITICAL manager       get_movies   An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.01.23.185723206231.log
2016-01-23 18:57 WARNING  task          get_movies   Aborting task (plugin: imdb)
2016-01-23 18:57 CRITICAL task          get_movies BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'
2016-01-23 18:57 CRITICAL manager       get_movies An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2016.01.23.185726324497.log
2016-01-23 18:57 WARNING  task          get_movies Aborting task (plugin: imdb)
2016-01-23 19:04 INFO     remember_rej  emailtask       Remembering rejection of `Hawaii.Five-0.2010.S06E13`
2016-01-23 19:04 INFO     remember_rej  emailtask       Remembering rejection of `The.Intern.2015`
2016-01-23 19:10 WARNING  details       drop_series     Task didn't produce any entries. This is likely due to a mis-configured or non-functional input.
2016-01-23 19:10 WARNING  details       drop_series_seasons Task didn't produce any entries. This is likely due to a mis-configured or non-functional input.
2016-01-23 19:10 WARNING  details       drop_movies     Task didn't produce any entries. This is likely due to a mis-configured or non-functional input.
'''

**Comment by alneven** [comment]
End of the crash report log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/imdb.py", line 106, in on_task_filter
    lookup(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/imdb.py", line 243, in parse
    self.name = name_elem.find(text=True, recursive=False).strip()
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by antivirtel** [comment]
Do you have the latest version? It doesn't look like you have... Check with `flexget -V`

**Comment by alneven** [comment]
oh, a kudos for you!

you are right

somehow today morning the normal flexget installed systemwide was started:
```root      4231  1.1  6.2 371916 255600 ?       Sl   09:08   7:04 /usr/bin/python /usr/local/bin/flexget daemon start --daemonize```
and not the git version
```root     24187  0.2  1.1  83876 46268 ?        Sl   19:39   0:00 /root/flexget-dev/bin/python /root/flexget-dev/bin/flexget daemon start --daemonize```


now it sould be fixed, thanks for the good catch

sorry for the false alarm ;-)
