### ISSUE TITLE
IMDB: BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by bhcopeland** [Flexget/Flexget#774]
```
2016-01-09 10:19 VERBOSE  imdb_lookup   YIFY            Parsing imdb for `The Last Stand 2013`
2016-01-09 10:19 CRITICAL task          YIFY            BUG: Unhandled error in plugin imdb: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/opt/flexget/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/opt/flexget/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/opt/flexget/lib/python2.7/site-packages/flexget/plugins/filter/imdb.py", line 106, in on_task_filter
    lookup(entry)
  File "/opt/flexget/lib/python2.7/site-packages/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/opt/flexget/lib/python2.7/site-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/opt/flexget/lib/python2.7/site-packages/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/opt/flexget/lib/python2.7/site-packages/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/opt/flexget/lib/python2.7/site-packages/flexget/utils/imdb.py", line 243, in parse
    self.name = name_elem.find(text=True, recursive=False).strip()
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by liiight** [comment]
Duplicate #773
