### ISSUE TITLE
Still - 'NoneType' object has no attribute 'find' - latest git

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#777]
manuel@PC-Manuel ~/flexget-dev $ bin/flexget  -V
1.2.425.dev
Latest release: 1.2.424
manuel@PC-Manuel ~/flexget-dev $ 

2016-01-09 22:31 VERBOSE  imdb_lookup   HD720P          Parsing imdb for `Sinatra.-.All.or.Nothing.at.all.Complete.German.DOKU.720p.WebHD.x264-RAiNDEER`
2016-01-09 22:31 CRITICAL task          HD720P          BUG: Unhandled error in plugin proper_movies: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/home/manuel/flexget-dev/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/home/manuel/flexget-dev/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/manuel/flexget-dev/flexget/plugins/filter/proper_movies.py", line 95, in on_task_filter
    imdb_id = imdb_lookup.imdb_id_lookup(movie_title=parser.name, raw_title=entry['title'])
  File "/home/manuel/flexget-dev/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/home/manuel/flexget-dev/flexget/plugins/metainfo/imdb_lookup.py", line 273, in imdb_id_lookup
    self.lookup(fake_entry)
  File "/home/manuel/flexget-dev/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/home/manuel/flexget-dev/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/home/manuel/flexget-dev/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/home/manuel/flexget-dev/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/home/manuel/flexget-dev/flexget/utils/imdb.py", line 245, in parse
    year = title_overview.find(attrs={'class': 'nobr'}).find('a', href=True)
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by tarzasai** [comment]
for now you can just overwrite your flexget_1.2.424_path/flexget/utils/imdb.py with [this](https://github.com/Flexget/Flexget/blob/develop/flexget/utils/imdb.py) as I did.

**Comment by crack00r** [comment]
its the latest git pull... so its up2date

**Comment by crawln45** [comment]
@crack00r Yeah I see that page doesn't have the year as a link like all the others only the class.

**Comment by crack00r** [comment]
So i think the lookup needs a fallback on " no year " :)

**Comment by crawln45** [comment]
well when I parsed it. it return 0 as the year.

**Comment by crawln45** [comment]
This is my first time actually working with BS4 so I'm still working on learning how to make it do what I want. Took me 2 hours to get the latest revision working properly with 99% now of the pages. I'm still working on the others.

**Comment by tarzasai** [comment]
I'm trying with the imdb.py from 1.2.425 without getting any error. Here:
```
  ut2:
    imdb_lookup: yes
    mock:
      - { title: 'Sinatra.-.All.or.Nothing.at.all.Complete.German.DOKU.720p.WebHD.x264-RAiNDEER' }
      - { title: 'Sinatra: All or nothing at all' }

[output]
$ flexget -L verbose execute --task ut2 --now
2016-01-10 17:45 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-01-10 17:45 VERBOSE  details       ut2             Produced 2 entries.
2016-01-10 17:45 WARNING  task          ut2             Task does not have any filter plugins to accept entries. You need at least one to accept the entries you  want.
2016-01-10 17:45 VERBOSE  details       ut2             Summary - Accepted: 0 (Rejected: 0 Undecided: 2 Failed: 0)
2016-01-10 17:45 WARNING  task          ut2             Task doesn't have any output plugins, you should add (at least) one!
```
It cannot find anything btw, but it doesn't crashes. Can you post your config?

**Comment by crawln45** [comment]
@tarzasai Here's the config. I also just updated the parser to actually find the year for that movie as well.
```  
tasks:
  testing:
    mock:
      #- {'title': 'Sinatra: All or nothing at all', 'imdb_id': 'tt3838978'}
      #- {'title': '22 Bullets', 'imdb_id': 'tt1167638'}
      - {'title': 'A Good Year', 'imdb_id': 'tt0401445'}
    accept_all: yes
    imdb_lookup: yes
    disable: builtins
    exec: echo 'IMDB_NAME':' {{imdb_name}} - IMDB YEAR':' {{imdb_year}}' 
```

**Comment by crack00r** [comment]
http://nopaste.linux-dev.org/?928285

**Comment by crawln45** [comment]
Well that's not a movie. So I'm not sure on that part.

**Comment by crack00r** [comment]
yes, but it should have a fallback like - cant reconize - and not just crash :dancer:

**Comment by tarzasai** [comment]
I don't know, no errors here:
```
2016-01-10 23:04 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-01-10 23:04 VERBOSE  details       ut2             Produced 2 entries.
2016-01-10 23:04 WARNING  task          ut2             Task does not have any filter plugins to accept entries. You need at least one to accept the entries you  want.
2016-01-10 23:04 VERBOSE  details       ut2             Summary - Accepted: 0 (Rejected: 0 Undecided: 2 Failed: 0)
2016-01-10 23:04 WARNING  task          ut2             Task doesn't have any output plugins, you should add (at least) one!
-- Undecided: --------------------------
title            : Sinatra: All or nothing at all
url              : mock://localhost/mock/799115649
original_url     : mock://localhost/mock/799115649
2016-01-10 23:04 VERBOSE  imdb_lookup   ut2             Parsing imdb for `Sinatra: All or nothing at all`
imdb_actors      : {u'nm0615386': u'Edward R. Murrow', u'nm0001654': u'Ronald Reagan', u'nm0101876': u'Pattie Boyd', u'nm0000069': u'Frank Sinatra', u'nm0232942': u'Donovan', u'nm0365600': u'George Harrison', u'nm0725765': u'Nelson Riddle', u'nm0001257': u'Ava Gardner', u'nm0001078': u'Bing Crosby', u'nm0948343': u'Maharishi Mahesh Yogi', u'nm0000896': u'Harry Belafonte', u'nm0006168': u'John Lennon', u'nm0005434': u'Nancy Sinatra', u'nm0002035': u'Sammy Davis Jr.', u'nm2440596': u'Phil Kuntz', u'nm0038870': u'Jane Asher', u'nm0000038': u'Grace Kelly', u'nm0502031': u'Cynthia Lennon', u'nm0481620': u'John Lahr', u'nm0522385': u'Mike Love', u'nm2701590': u'Nancy Barbato', u'nm0005200': u'Paul McCartney', u'nm0001362': u'Bob Hope', u'nm0001201': u'Mia Farrow', u'nm0357687': u'Pete Hamill', u'nm1269230': u'Alan Livingston', u'nm0000007': u'Humphrey Bogart', u'nm0801537': u'Tina Sinatra', u'nm0004864': u'Nancy Reagan'}
imdb_directors   : {}
imdb_genres      : [documentary]
imdb_id          : tt3838978
imdb_languages   : [english]
imdb_mpaa_rating : 
imdb_name        : Sinatra: All or Nothing at All
imdb_original_name: None
imdb_photo       : http://ia.media-imdb.com/images/M/MV5BNTY5NDE3MDM4Nl5BMl5BanBnXkFtZTgwODczODIxNTE@._V1_SY317_CR0,0,214,317_AL_.jpg
imdb_plot_outline: SINATRA: All or Nothing at All is an up-close and personal examination of the life, music and career of the legendary entertainer. Told in his own words from hours of archived interviews, along with commentary from those closest to him, the documentary weaves the music and images from Sinatra's life together with rarely seen footage of Sinatra's famous 1971 "Retirement Concert" in Los Angeles. The film's narrative is shaped by Sinatra's song choices for that concert, which Gibney interprets as the singer's personal guide through his own life.
imdb_score       : 8.0
imdb_url         : http://www.imdb.com/title/tt3838978/
imdb_votes       : 660
imdb_year        : 0
movie_name       : Sinatra: All or Nothing at All
movie_year       : 0
quality          : unknown
task             : ut2

title            : A Good Year
url              : mock://localhost/mock/-1703530692
original_url     : mock://localhost/mock/-1703530692
2016-01-10 23:04 VERBOSE  imdb_lookup   ut2             Parsing imdb for `A Good Year`
imdb_actors      : {u'nm0383603': u'Freddie Highmore', u'nm2374595': u'Ali Rhodes', u'nm1071157': u'Lionel Briand', u'nm1638095': u'Stephen Hudson', u'nm1245863': u'Rafe Spall', u'nm1171145': u'Patrick Kennedy', u'nm1782150': u'Nila Aalia', u'nm0264857': u'Giannina Facio-Scott', u'nm0390903': u'Tom Hollander', u'nm2241142': u'Ben Righton', u'nm0185404': u'Richard Coyle', u'nm0000128': u'Russell Crowe', u'nm0990547': u'Daniel Mays', u'nm0659544': u'Archie Panjabi', u'nm0001215': u'Albert Finney'}
imdb_directors   : {u'nm0000631': u'Ridley Scott'}
imdb_genres      : [comedy, drama, romance]
imdb_id          : tt0401445
imdb_languages   : [english, french, russian]
imdb_mpaa_rating : PG-13
imdb_name        : A Good Year
imdb_original_name: None
imdb_photo       : http://ia.media-imdb.com/images/M/MV5BODE4NDY3MjUxNV5BMl5BanBnXkFtZTYwMTMwODI3._V1_SY317_CR7,0,214,317_AL_.jpg
imdb_plot_outline: After years of no contact with his Uncle Henry, London banker and bond trader Max Skinner learns that Henry has died intestate, so Max inherits a château and vineyard in Provence. Max spent part of his childhood there, learning maxims and how to win and lose, and honing his killer instinct (at chess, which serves him well in finance). Max goes to France intent on selling the property. He spends a few days there, getting the property ready to show. Memories, a beautiful woman, and a young American who says she's Henry's illegitimate daughter interrupt his plans. Did Max the boy know things that Max the man has forgotten?
imdb_score       : 6.9
imdb_url         : http://www.imdb.com/title/tt0401445/
imdb_votes       : 67770
imdb_year        : 2006
movie_name       : A Good Year
movie_year       : 2006
quality          : unknown
task             : ut2
```

**Comment by tarzasai** [comment]
PS: did you tried with no_global? I'd like to see your debug log of this test if you can:
```
  test:
    template:
      - no_global
    imdb_lookup: yes
    mock:
      - { title: 'A Good Year' }
      - { title: 'Sinatra: All or nothing at all' }
```

**Comment by crack00r** [comment]
latest git pill works perfect!
Thx!
