### ISSUE TITLE
Flexget version 1.2.424 - Unhandled error in lazy lookup plugin

### ISSUE THREAD

**Issue by acordill** [Flexget/Flexget#779]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 235, in lazy_loader
    self.lookup(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/imdb.py", line 243, in parse
    self.name = name_elem.find(text=True, recursive=False).strip()
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by gazpachoking** [comment]
Fixed by #778
