### ISSUE TITLE
[imdb] ValueError: invalid literal for int() with base 10: 'See full cast and crew'

### ISSUE THREAD

**Issue by DigitalConceptions** [Flexget/Flexget#785]
```
# flexget --version
1.2.427.dev
Latest release: 1.2.426
```

```
2016-01-12 07:37 VERBOSE  imdb_lookup   Movies-Filtered Parsing imdb for `Supernatural [2005] - BTN / Blu-ray / 720p / mkv / x264 / AC-3`
2016-01-12 07:37 DEBUG    requests      Movies-Filtered Waiting 0.93 seconds until next request to imdb.com
2016-01-12 07:37 DEBUG    requests      Movies-Filtered Fetching http://www.imdb.com/title/tt3569164/
2016-01-12 07:37 ERROR    imdb_lookup   Movies-Filtered invalid literal for int() with base 10: 'See full cast and crew'
Traceback (most recent call last):
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/home/wolfgang/.download/flexget/flexget/utils/imdb.py", line 251, in parse
    self.year = int(year.a.text)
ValueError: invalid literal for int() with base 10: 'See full cast and crew'
2016-01-12 07:37 VERBOSE  imdb          Movies-Filtered Skipping Supernatural [2005] - BTN / Blu-ray / 720p / mkv / x264 / AC-3 because of an error: Invalid parameter: http://www.imdb.com/title/tt3569164/?ref_=fn_ft_tt_4
2016-01-12 07:37 VERBOSE  imdb          Movies-Filtered Skipping Supernatural [2005] - BTN / Blu-ray / 720p / mkv / x264 / AC-3 because of an error: Invalid parameter: http://www.imdb.com/title/tt3569164/?ref_=fn_ft_tt_4
```

**Comment by crawln45** [comment]
Umm I'm not exactly sure about this since there is no class='nobr' so there is no year. so there should not be an error at all.

**Comment by crawln45** [comment]
@DigitalConceptions Isn't supernatural a TV series why is imdb being used. very confused btw lol

**Comment by DigitalConceptions** [comment]
@crawln45  Yes, it is.. I think it was in one of the public movie feeds that I have set.

**Comment by crawln45** [comment]
It was from BTN. `Supernatural [2005] - BTN / Blu-ray / 720p / mkv / x264 / AC-3`

**Comment by crawln45** [comment]
I did find the movie on imdb btw. But the url your getting back is not it lol. No biggie though. I'm not exactly sure what it's returning seeing as it should be returning something very specific. Internet should be back up on thurs maybe friday I'll look at it then.

**Comment by DigitalConceptions** [comment]
yes, I see it has the BTN tag on it, but that is certainly not a genuine BTN release.. looks like none I have every gotten directly from BTN; also, I don't use btn feeds in my movie lookups. ;p

**Comment by crawln45** [comment]
Well I have no clue what movie they are talking about because a quick search of google reveals no movie named that.

**Comment by crawln45** [comment]
To make matters worse. The particular phrase it's reporting 'See full cast and crew.' is not in the class nobr, And it's not even in the right div layer as title-overview. So I have absolutely no idea how it's returning that.

**Comment by DigitalConceptions** [comment]
Well, apparently the offending entry is not in the feed anymore, so I am not even getting this error/crash anymore.. I guess I could be closed...

**Comment by crawln45** [comment]
@DigitalConceptions in case your wondering. Here's the log I get from pycharm when I do a search for your show.  
```
2016-01-15 00:03 DEBUG    exec          testing         running phase_name: on_output operation: for_accepted entries: 1
2016-01-15 00:03 DEBUG    imdb_lookup   testing         lookup for Supernatural [2005]
2016-01-15 00:03 VERBOSE  imdb_lookup   testing         Searching from imdb `Supernatural [2005]`
2016-01-15 00:03 DEBUG    parser_internal testing         Parsing movie: `Supernatural [2005]` kwargs: {}
2016-01-15 00:03 DEBUG    movieparser   testing         parts: [u'Supernatural', u'2005'], cut is: 2005
2016-01-15 00:03 DEBUG    movieparser   testing         after parts check, cut data would be: `Supernatural` abs_cut: 12
2016-01-15 00:03 DEBUG    movieparser   testing         data cut to `Supernatural` - this will be the name
2016-01-15 00:03 DEBUG    parser_internal testing         Parsing result: <MovieParser(name=Supernatural,year=2005,quality=unknown)> (in 2.229 ms)
2016-01-15 00:03 DEBUG    utils.imdb    testing         smart_match name=Supernatural year=2005
2016-01-15 00:03 DEBUG    utils.imdb    testing         Searching: Supernatural
2016-01-15 00:03 DEBUG    utils.imdb    testing         Serch query: u'http://www.imdb.com/find'
2016-01-15 00:03 DEBUG    requests      testing         Fetching http://www.imdb.com/find
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Supernatural url: http://www.imdb.com/title/tt3508984/?ref_=fn_ft_tt_1
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 0 `http://www.imdb.com/title/tt3508984/?ref_=fn_ft_tt_1`: 1.1
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Supernatural url: http://www.imdb.com/title/tt0024631/?ref_=fn_ft_tt_2
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 1 `http://www.imdb.com/title/tt0024631/?ref_=fn_ft_tt_2`: 1.05
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Sobrenatural url: http://www.imdb.com/title/tt0083101/?ref_=fn_ft_tt_3
2016-01-15 00:03 DEBUG    utils.imdb    testing         - aka `Supernatural` matches better to `Supernatural` ratio 1.0 (weighted to 0.95)
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 2 `http://www.imdb.com/title/tt0083101/?ref_=fn_ft_tt_3`: 1.03333333333
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Act Super Naturally url: http://www.imdb.com/title/tt3569164/?ref_=fn_ft_tt_4
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 3 `http://www.imdb.com/title/tt3569164/?ref_=fn_ft_tt_4`: 1.025
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: The Supernaturals url: http://www.imdb.com/title/tt0092030/?ref_=fn_ft_tt_5
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 4 `http://www.imdb.com/title/tt0092030/?ref_=fn_ft_tt_5`: 1.02
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Supernatural Activity url: http://www.imdb.com/title/tt1832516/?ref_=fn_ft_tt_6
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 5 `http://www.imdb.com/title/tt1832516/?ref_=fn_ft_tt_6`: 1.01666666667
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Soupernatural url: http://www.imdb.com/title/tt0818172/?ref_=fn_ft_tt_7
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 6 `http://www.imdb.com/title/tt0818172/?ref_=fn_ft_tt_7`: 1.01428571429
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: The Supernatural url: http://www.imdb.com/title/tt3690364/?ref_=fn_ft_tt_8
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 7 `http://www.imdb.com/title/tt3690364/?ref_=fn_ft_tt_8`: 1.0125
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Tales of the Supernatural 2 url: http://www.imdb.com/title/tt2296979/?ref_=fn_ft_tt_9
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 8 `http://www.imdb.com/title/tt2296979/?ref_=fn_ft_tt_9`: 1.01111111111
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Supernaturalz: Weird, Creepy & Random url: http://www.imdb.com/title/tt2172079/?ref_=fn_ft_tt_10
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 9 `http://www.imdb.com/title/tt2172079/?ref_=fn_ft_tt_10`: 1.01
2016-01-15 00:03 DEBUG    utils.imdb    testing         processing name: Supernatural Seekers url: http://www.imdb.com/title/tt4995944/?ref_=fn_ft_tt_11
2016-01-15 00:03 DEBUG    utils.imdb    testing         - prioritizing based on position 10 `http://www.imdb.com/title/tt4995944/?ref_=fn_ft_tt_11`: 1.00909090909
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing Supernatural - http://www.imdb.com/title/tt3508984/?ref_=fn_ft_tt_1 (wrong year: 2014)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing Supernatural - http://www.imdb.com/title/tt0024631/?ref_=fn_ft_tt_2 (wrong year: 1933)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing Sobrenatural - http://www.imdb.com/title/tt0083101/?ref_=fn_ft_tt_3 (wrong year: 1983)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing Soupernatural - http://www.imdb.com/title/tt0818172/?ref_=fn_ft_tt_7 (wrong year: 2010)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing The Supernatural - http://www.imdb.com/title/tt3690364/?ref_=fn_ft_tt_8 (wrong year: 2013)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing The Supernaturals - http://www.imdb.com/title/tt0092030/?ref_=fn_ft_tt_5 (wrong year: 1986)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing Supernatural Seekers - http://www.imdb.com/title/tt4995944/?ref_=fn_ft_tt_11 (wrong year: in development)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing Supernatural Activity - http://www.imdb.com/title/tt1832516/?ref_=fn_ft_tt_6 (wrong year: 2012)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing Tales of the Supernatural 2 - http://www.imdb.com/title/tt2296979/?ref_=fn_ft_tt_9 (wrong year: 2017)
2016-01-15 00:03 DEBUG    utils.imdb    testing         best_match removing Supernaturalz: Weird, Creepy & Random - http://www.imdb.com/title/tt2172079/?ref_=fn_ft_tt_10 (wrong year: 2012)
2016-01-15 00:03 DEBUG    utils.imdb    testing         SUCCESS: only one movie remains
2016-01-15 00:03 VERBOSE  imdb_lookup   testing         Found http://www.imdb.com/title/tt3569164/?ref_=fn_ft_tt_4
2016-01-15 00:03 VERBOSE  imdb_lookup   testing         Parsing imdb for `Supernatural [2005]`
2016-01-15 00:03 DEBUG    requests      testing         Fetching http://www.imdb.com/title/tt3569164/
2016-01-15 00:03 INFO     imdb_lookup   testing         Invalid parameter: http://www.imdb.com/title/tt3569164/?ref_=fn_ft_tt_4
2016-01-15 00:03 DEBUG    exec          testing         phase_name: on_output operation: for_accepted cmd: echo 'IMDB_NAME':' None - IMDB YEAR':' None'
2016-01-15 00:03 VERBOSE  exec          testing         Executing: echo 'IMDB_NAME':' None - IMDB YEAR':' None'
2016-01-15 00:03 INFO     exec          testing         Stdout: IMDB_NAME: None - IMDB YEAR: None\n
2016-01-15 00:03 DEBUG    exec          testing         phase on_exit not configured
2016-01-15 00:03 DEBUG    disable       testing         Re-enabled builtin plugin(s): entry_operations, nzb_size, scan_imdb, torrent_files, backlog, dump, include, change_warn, template, retry_failed, remember_rejected, torrent_cache, torrent_size, metainfo_content_size, history, urlrewriting, verbose, urlfix, seen_info_hash, torrent, proxy, seen, details, dump_config, series_db, --try-regexp, metainfo_task, metainfo_quality, magnet_btih
2016-01-15 00:03 DEBUG    util.simple_persistence testing         Flushing simple persistence for task testing to db.
2016-01-15 00:03 DEBUG    task_queue                    task queue shut down
2016-01-15 00:03 INFO     ipc.rpyc                      server has terminated
2016-01-15 00:03 INFO     ipc.rpyc                      listener closed
2016-01-15 00:03 DEBUG    util.simple_persistence                 Flushing simple persistence for task None to db.
2016-01-15 00:03 DEBUG    manager                       Shutting down
2016-01-15 00:03 DEBUG    manager                       Removed /home/crawln/git/Flexget/.config-lock  
```

**Comment by DigitalConceptions** [comment]
Strange... See thing is, this is my movie task, was really just a fluke that there was a TV show in it to begin with.

Relevant config:

```
secrets: secrets.yml

templates:
  movie-inputs:
    inputs:
      - filesystem: ~/.download/manual/movies/
      - rss: '{{ secrets.input_rss.ahd }}'
      - rss: '{{ secrets.input_rss.tehcon }}'
      - rss: '{{ secrets.input_rss.ptp }}'

  movie-global:
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title}
        - \bR5\b: {from: title}
        - \bWEBSCR\b: {from: title}
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \[facepalm\]: {from: title}
        - \bASAP\b: {from: title}
    manipulate:
      - title:
          extract: MOVIE:(.*)
    content_size:
      min: 300
      max: 9292
    quality: <=1080p dvdrip+
    delay: 3 hours
    exists_movie:
      type: files
      path:
        - /home/wolfgang/Media/Movies/
        - /home/wolfgang/Media/UnSorted/Movies/Good/
    download: yes

tasks:
  Movies-Filtered:
    priority: 110
    template: [movie-inputs, movie-global]
    seen_movies:
      scope: local
    imdb_required: yes
    require_field: [imdb_votes, imdb_score]
    imdb:
      min_score: 5.5
      min_votes: 500
      accept_languages:
        - english
      reject_genres: [documentary, biography, history]
    if:
      - imdb_year < 2000 and imdb_score < 7.0: reject
      - imdb_year < 1980 and imdb_score < 8.5: reject
      - imdb_year < 1960: reject
    download: ~/.download/fgdata/movies/
```

And now I seems to be getting a similar, yet different error/crash:

```
2016-01-15 05:31 VERBOSE  task          Movies-Filtered REJECTED: `The Benefactor [2015] by Andrew Renzi - H.264 / WEB / MKV / 1080p` by quality plugin because 1080p h264 does not match quality requirement [<Requirements(<=1080p dvdrip+)>]
2016-01-15 05:31 DEBUG    imdb_lookup   Movies-Filtered No title passed. Lookup for tt1528309
2016-01-15 05:31 DEBUG    imdb_lookup   Movies-Filtered movie `A Little Closer` age 5 expires in 27 days
2016-01-15 05:31 DEBUG    imdb          Movies-Filtered Didn't accept `A Little Closer` because of rule(s) min_votes (230 < 500)
2016-01-15 05:31 DEBUG    imdb_lookup   Movies-Filtered No title passed. Lookup for tt0095018
2016-01-15 05:31 VERBOSE  imdb_lookup   Movies-Filtered Parsing imdb for `A cena col vampiro AKA Dinner with a Vampire [1987] by Lamberto Bava - x264 / DVD / MKV / Other`
2016-01-15 05:31 ERROR    imdb_lookup   Movies-Filtered invalid literal for int() with base 10: 'Season 1, Episode 4         '
Traceback (most recent call last):
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/home/wolfgang/.download/flexget/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/home/wolfgang/.download/flexget/flexget/utils/imdb.py", line 249, in parse
    self.year = int(year.text.strip('()'))
ValueError: invalid literal for int() with base 10: 'Season 1, Episode 4         '
2016-01-15 05:31 VERBOSE  imdb          Movies-Filtered Skipping A cena col vampiro AKA Dinner with a Vampire [1987] by Lamberto Bava - x264 / DVD / MKV / Other because of an error: Invalid parameter: http://www.imdb.com/title/tt0095018/
2016-01-15 05:31 VERBOSE  imdb          Movies-Filtered Skipping A cena col vampiro AKA Dinner with a Vampire [1987] by Lamberto Bava - x264 / DVD / MKV / Other because of an error: Invalid parameter: http://www.imdb.com/title/tt0095018/
```

So I really have no idea whats happening.

More logs, details, and config available if needed..

**Comment by liiight** [comment]
Probably a duplicate of #797. Check on next release please.

**Comment by crawln45** [comment]
New release is out. Upgrade for the fix.

**Comment by DigitalConceptions** [comment]
I've gotten no more errors since the update.
I will keep checking, but will close this issue out for now.
