### ISSUE TITLE
Running 'flexget check' throws screen full of errors

### ISSUE THREAD

**Issue by mpompey** [Flexget/Flexget#792]
I'm trying to diagnose why my flexget install has stopped running. I've been trying to methodically go through the steps on the sites. But when I try the first step to verify which version of flexget is installed I get the following:

flexget check
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 9, in <module>
    load_entry_point('FlexGet==1.2.415', 'console_scripts', 'flexget')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 11, in <module>
    from flexget.manager import Manager
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 32, in <module>
    from flexget.ipc import IPCClient, IPCServer # noqa
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 12, in <module>
    from flexget.options import get_parser, ParserError
  File "/usr/local/lib/python2.7/dist-packages/flexget/options.py", line 18, in <module>
    from flexget.utils import requests
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/requests.py", line 28, in <module>
    requests.packages.urlib3.disable_warnings()
AttributeError: 'module' object has no attribute 'urlib3'
mpompey@ubuntupvr:~/.config/flexget$

**Comment by gazpachoking** [comment]
Do you have requests installed via ubuntu package manager? They do funny stuff that breaks things sometimes. Try installing and running FlexGet from a virtualenv.

**Comment by cvium** [comment]
Closing this issue as it doesn't seem to be related to Flexget, but rather a package manager breaking stuff. Install Python packages with `pip` instead.
