### ISSUE TITLE
send_telegram fails ungracefully on connection timeouts

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#794]
```
2016-01-15 03:15 CRITICAL task          bitmetv         BUG: Unhandled error in plugin send_telegram: <urlopen error timed out>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/send_telegram.py", line 202, in on_task_exit
    chat_ids = self._real_init(session, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/send_telegram.py", line 214, in _real_init
    self._init_bot()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/send_telegram.py", line 258, in _init_bot
    self._check_token()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/send_telegram.py", line 262, in _check_token
    self._bot.getMe()
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telegram/bot.py", line 176, in getMe
    result = request.get(url)
  File "/usr/local/lib/python2.7/dist-packages/telegram/utils/request.py", line 65, in get
    result = urlopen(url).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
```

Timeouts should be handled by the plugin, not a cause a crash.

**Comment by crawln45** [comment]
Honestly timeouts cause crashes in all plugins that I'm aware of.

**Comment by liiight** [comment]
I agree that this is a bug, wide spread as it is. When I refactored pushover I took special notice for request exceptions, no reason this shouldn't be the case here as well

**Comment by crawln45** [comment]
Not exactly sure how to handle a crash of an external import in the plugin. Have to think on it.

**Comment by crawln45** [comment]
Eh I don't use telegraph so @liiight will have to wrap that in a try function and see if that fixes
