### ISSUE TITLE
run loop crash - latest git pull

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#800]
Aquarius.S01E01.Jeder.traegt.seine.Buerde.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP.crawljob"
2016-01-19 17:29 VERBOSE  exec          Series_Collection_DE Executing: echo "downloadFolder=/mnt/Daten/Downloads/Archiv/Aquarius.S01E01.Jeder.traegt.seine.Buerde.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP/" >> "/mnt/Daten/jd2/folderwatch/Aquarius.S01E01.Jeder.traegt.seine.Buerde.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP.crawljob"
2016-01-19 17:29 VERBOSE  exec          Series_Collection_DE Executing: echo "autoStart=TRUE" >> "/mnt/Daten/jd2/folderwatch/Aquarius.S01E01.Jeder.traegt.seine.Buerde.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP.crawljob"
2016-01-19 17:29 VERBOSE  exec          Series_Collection_DE Executing: echo "forcedStart=TRUE" >> "/mnt/Daten/jd2/folderwatch/Aquarius.S01E01.Jeder.traegt.seine.Buerde.GERMAN.DUBBED.DL.720p.BluRay.x264-TVP.crawljob"
2016-01-19 17:29 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Traceback (most recent call last):
  File "/home/manuel/flexget-dev/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
  File "/home/manuel/flexget-dev/flexget/task.py", line 69, in wrapper
    return func(self, *args, **kw)
  File "/home/manuel/flexget-dev/flexget/task.py", line 578, in execute
    self._execute()
  File "/home/manuel/flexget-dev/flexget/task.py", line 557, in _execute
    entry.complete()
  File "/home/manuel/flexget-dev/flexget/entry.py", line 163, in complete
    self.run_hooks('complete', **kwargs)
  File "/home/manuel/flexget-dev/flexget/entry.py", line 78, in run_hooks
    func(self, **kwargs)
  File "/home/manuel/flexget-dev/flexget/plugins/input/discover.py", line 178, in entry_complete
    search_results.remove(entry)
KeyError: <Entry(title=Continuum.S03E00.Sneak.Peek.720p.WEB.DL.AAC2.0.H264 (300 MB 10 min),state=rejected)>

**Comment by crack00r** [comment]
I dont get it working... anyone know some help?

2016-01-22 08:25 VERBOSE  exec          Series_Watchlist Executing: echo "autoConfirm=TRUE" >> "/mnt/Daten/jd2/folderwatch/Narcos.S01E03.GERMAN.DL.DUBBED.720p.WebHD.x264-TVP.crawljob"
2016-01-22 08:25 VERBOSE  exec          Series_Watchlist Executing: echo "priority=LOWER" >> "/mnt/Daten/jd2/folderwatch/Narcos.S01E03.GERMAN.DL.DUBBED.720p.WebHD.x264-TVP.crawljob"
2016-01-22 08:25 VERBOSE  exec          Series_Watchlist Executing: echo "packageName=Narcos.S01E03.GERMAN.DL.DUBBED.720p.WebHD.x264-TVP" >> "/mnt/Daten/jd2/folderwatch/Narcos.S01E03.GERMAN.DL.DUBBED.720p.WebHD.x264-TVP.crawljob"
2016-01-22 08:25 VERBOSE  exec          Series_Watchlist Executing: echo "downloadFolder=/mnt/Daten/Downloads/zuChecken/Narcos.S01E03.GERMAN.DL.DUBBED.720p.WebHD.x264-TVP/" >> "/mnt/Daten/jd2/folderwatch/Narcos.S01E03.GERMAN.DL.DUBBED.720p.WebHD.x264-TVP.crawljob"
2016-01-22 08:25 VERBOSE  exec          Series_Watchlist Executing: echo "autoStart=TRUE" >> "/mnt/Daten/jd2/folderwatch/Narcos.S01E03.GERMAN.DL.DUBBED.720p.WebHD.x264-TVP.crawljob"
2016-01-22 08:25 VERBOSE  exec          Series_Watchlist Executing: echo "forcedStart=TRUE" >> "/mnt/Daten/jd2/folderwatch/Narcos.S01E03.GERMAN.DL.DUBBED.720p.WebHD.x264-TVP.crawljob"
2016-01-22 08:25 INFO     trakt_remove  Series_Watchlist Successfully deleted to/from list watchlist: 0 movie(s), 0 show(s), 0 episode(s).
2016-01-22 08:25 INFO     task          Series_Watchlist Plugin exec has requested task to be ran again after execution has completed.
2016-01-22 08:25 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 69, in wrapper
    return func(self, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 578, in execute
    self._execute()
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 557, in _execute
    entry.complete()
  File "/usr/local/lib/python2.7/dist-packages/flexget/entry.py", line 163, in complete
    self.run_hooks('complete', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/entry.py", line 78, in run_hooks
    func(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 178, in entry_complete
    search_results.remove(entry)
KeyError: <Entry(title=Die.Sopranos.S01E12.Die.schoene.Isabella.DL.FS.DVDRiP.XviD,state=rejected)>

**Comment by liiight** [comment]
can you run in debug please?

**Comment by liiight** [comment]
I think this is the same as #847
