### ISSUE TITLE
Multiple trakt lookup crashes

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#811]
@Flexget/trakt Got several trakt lookup crashed, I think all can be trace to same source issue so i'm combining them:
```
2016-01-21 09:54 VERBOSE  task          download_tv_shows ACCEPTED: `The.Flash.2014.S02E10.720p.HDTV.X264-DIMENSION` by series plugin because quality wanted
2016-01-21 09:54 INFO     download      download_tv_shows Downloading: The.Flash.2014.S02E10.720p.HDTV.X264-DIMENSION
2016-01-21 09:54 VERBOSE  details       download_tv_shows Summary - Accepted: 1 (Rejected: 0 Undecided: 19 Failed: 0)
2016-01-21 09:54 ERROR    lazy_lookup   download_tv_shows Unhandled error in lazy lookup plugin
2016-01-21 09:54 CRITICAL manager       download_tv_shows An unexpected crash has occurred. Writing crash report to C:\Users\orcar_000\Dropbox\Flexget Data\crash_report.2016.01.21.095445374000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.432
2016-01-21 09:54 ERROR    lazy_lookup   download_tv_shows Unhandled error in lazy lookup plugin
2016-01-21 09:54 CRITICAL manager       download_tv_shows An unexpected crash has occurred. Writing crash report to C:\Users\orcar_000\Dropbox\Flexget Data\crash_report.2016.01.21.095446460000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.432
2016-01-21 09:54 ERROR    lazy_lookup   download_tv_shows Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flexget\utils\lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\trakt_lookup.py", line 190, in lazy_episode_lookup
    episode = series.get_episode(entry['series_season'], entry['series_episode'])
  File "C:\Python27\lib\site-packages\flexget\plugins\api_trakt.py", line 387, in get_episode
    episode = self.episodes.filter(TraktEpisode.season == season).filter(TraktEpisode.number == number).first()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2634, in first
    ret = list(self[0:1])
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2457, in __getitem__
    return list(res)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2735, in __iter__
    self.session._autoflush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1315, in _autoflush
    util.raise_from_cause(e)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1305, in _autoflush
    self.flush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2027, in flush
    self._flush(objects)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2109, in _flush
    flush_context.execute()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    uow
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) column search is not unique [SQL: u'INSERT INTO trakt_show_search_results (search, series_id) VALUES (?, ?)'] [parameters: (u'The Flash (2014)', 60300)]
```
And:
```
016-01-21 09:54 VERBOSE  task          download_tv_shows ACCEPTED: `The.Flash.2014.S02E10.720p.HDTV.X264-DIMENSION` by series plugin because quality wanted
2016-01-21 09:54 INFO     download      download_tv_shows Downloading: The.Flash.2014.S02E10.720p.HDTV.X264-DIMENSION
2016-01-21 09:54 VERBOSE  details       download_tv_shows Summary - Accepted: 1 (Rejected: 0 Undecided: 19 Failed: 0)
2016-01-21 09:54 ERROR    lazy_lookup   download_tv_shows Unhandled error in lazy lookup plugin
2016-01-21 09:54 CRITICAL manager       download_tv_shows An unexpected crash has occurred. Writing crash report to C:\Users\orcar_000\Dropbox\Flexget Data\crash_report.2016.01.21.095445374000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.432
2016-01-21 09:54 ERROR    lazy_lookup   download_tv_shows Unhandled error in lazy lookup plugin
2016-01-21 09:54 CRITICAL manager       download_tv_shows An unexpected crash has occurred. Writing crash report to C:\Users\orcar_000\Dropbox\Flexget Data\crash_report.2016.01.21.095446460000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.432
2016-01-21 09:54 ERROR    lazy_lookup   download_tv_shows Unhandled error in lazy lookup plugin
2016-01-21 09:54 CRITICAL manager       download_tv_shows An unexpected crash has occurred. Writing crash report to C:\Users\orcar_000\Dropbox\Flexget Data\crash_report.2016.01.21.095446860000.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.432
2016-01-21 09:54 ERROR    lazy_lookup   download_tv_shows Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flexget\utils\lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "C:\Python27\lib\site-packages\flexget\plugins\metainfo\trakt_lookup.py", line 263, in lazy_watched_lookup
    item = lookup(**lookupargs)
  File "C:\Python27\lib\site-packages\flexget\utils\database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\flexget\plugins\api_trakt.py", line 670, in lookup_series
    if series and title.lower() == series.title.lower():
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by cvium** [comment]
The second one seems easy enough to fix, although I don't get why it happens.

**Comment by cvium** [comment]
I guess the first one is because the show data expired.

**Comment by liiight** [comment]
I have similar code in tvmaze and I thought the same thing but it wasn't it.  I ended up just adding a lookup to search table before adding to verify it's a new entry.
Not very pretty but it works (i hope...)

**Comment by cvium** [comment]
Are you fixing this one then?

**Comment by liiight** [comment]
I can, but thoguht I'd leave it to you.
