### ISSUE TITLE
Using guessit for series parsing is slow and crash

### ISSUE THREAD

**Issue by lildadou** [Flexget/Flexget#817]
Version : 1.2.434

The error appears only when guessit is used. Moreover, the task is pretty long (notice timestamp in the crashlog).

config.yml:
```
templates:
  global:
    parsing:
      series: guessit

  tv-shows:
    exists_series:
      path: "/home/xbmc/.flexget/shows/{{ series_name }}/{{'S%02d'|format(series_season)}}"
      allow_different_qualities: better

    configure_series:
      settings:
        upgrade: yes
        target: 1080p webdl
        quality: 720p+
        timeframe: 1 week
      from:
        filesystem: "/home/xbmc/.flexget/shows/"
    deluge:
      movedone: "/home/xbmc/.flexget/shows/{{ series_name }}/{{'S%02d'|format(series_season)}}"
      label: tv

tasks:
  dl-series:
    template: tv-shows
    discover:
      what:
        - filesystem:
            path: "/home/xbmc/.flexget/shows/"
            retrieve: dirs
            recursive: False
      from:
        - t411:
            category: Série TV
            terms:
              - VOSTFR
              - HDrip 1080
              - Web-Dl 1080
              - TVripHD 1080
              - HDrip 720
              - Web-Dl 720
              - TVripHD 720
        - kat:
            category: tv
```

crashlog :
```
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 720p hdrip xvid, overriding with 720p hdtv xvid.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:41 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl, overriding with 1080p webdl dd5.1.
2016-01-22 13:42 ERROR    task_queue                    Got ctrl-c, shutting down after running task (if any) completes
2016-01-22 13:43 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h265, overriding with 1080p webdl h265 dd5.1.
2016-01-22 13:43 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h265, overriding with 1080p webdl h265 dd5.1.
2016-01-22 13:43 VERBOSE  series        dl-series       Found different quality for ****. Was 720p webdl h264 dd5.1, overriding with 720p webdl h264.
2016-01-22 13:43 VERBOSE  series        dl-series       Found different quality for ****. Was 720p webdl h264 dd5.1, overriding with 720p webdl h264.
2016-01-22 13:43 VERBOSE  series        dl-series       Found different quality for ****. Was 720p webdl h264 dd5.1, overriding with 720p webdl h264.
2016-01-22 13:43 VERBOSE  series        dl-series       Found different quality for ****. Was 720p webdl h264 dd5.1, overriding with 720p webdl h264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:44 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h 264.
2016-01-22 13:45 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p hdtv h265, overriding with 1080p hdtv h265 dd5.1.
2016-01-22 13:47 VERBOSE  series        dl-series       Found different quality for ****. Was 720p webdl h264 dd5.1, overriding with 720p webdl h 264.
2016-01-22 13:47 VERBOSE  series        dl-series       Found different quality for ****. Was 720p webdl h264 dd5.1, overriding with 720p webdl h 264.
2016-01-22 13:47 VERBOSE  series        dl-series       Found different quality for ****. Was 720p webdl h264 dd5.1, overriding with 720p webdl h 264.
2016-01-22 13:47 VERBOSE  series        dl-series       Found different quality for ****. Was 1080p webdl h264 dd5.1, overriding with 1080p webdl h264.
2016-01-22 13:47 CRITICAL task          dl-series       BUG: Unhandled error in plugin series: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1109, in on_task_metainfo
    self.parse_series(task.entries, series_name, series_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1231, in parse_series
    populate_entry_fields(entry, parsed, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 856, in populate_entry_fields
    entry['series_id'] = parser.pack_identifier
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_common.py", line 548, in pack_identifier
    return self.identifier
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_common.py", line 539, in identifier
    return self.identifiers[0]
IndexError: list index out of range
```

**Comment by liiight** [comment]
The crash actually appears to have nothing to do with guessit

**Comment by liiight** [comment]
is this still relevant?
