### ISSUE TITLE
series begin results in error if series name has a hyphen

### ISSUE THREAD

**Issue by y** [Flexget/Flexget#820]
I added "The X-Files" to my series config and then attempted to set the first episode so flexget advancement wouldn't skip it. If I remove the hyphen from the series name it works, but it always fails if the hyphen is in there, even when the series name is properly quoted.

    $ flexget series begin 'the x-files' s10e01
    Traceback (most recent call last):
    File "/Users/y/bin/flexget", line 9, in <module>
        load_entry_point('FlexGet', 'console_scripts', 'flexget')()
    File "/Users/y/flexget/flexget/__init__.py", line 37, in main
        manager.start()
    File "/Users/y/flexget/flexget/manager.py", line 300, in start
        self.handle_cli()
    File "/Users/y/flexget/flexget/manager.py", line 327, in handle_cli
        options.cli_command_callback(self, command_options)
    File "/Users/y/flexget/flexget/plugins/cli/series.py", line 28, in do_cli
        begin(manager, options)
    File "/Users/y/flexget/flexget/plugins/cli/series.py", line 103, in begin
        series = shows_by_name(series_name, session)[0]
    IndexError: list index out of range

    $ flexget --version
    1.2.435

**Comment by liiight** [comment]
Duplicate #814
