### ISSUE TITLE
IMDB parser needs updating

### ISSUE THREAD

**Issue by luiscvtomas** [Flexget/Flexget#824]
Hi,

Since today I'm receiving this error while executing my tasks with imdb plugin:

ERROR    utils.imdb    task     Possible IMDB parser needs updating, Please report on Github.

In the plugin i have the following conditions:

    imdb:
      min_score: 6.5
      min_votes: 5000
      min_year: 2010
      reject_genres:
        - horror
        - documentary
        - musical
        - music

Can you help me?

Thanks in advance,
Luís Tomás

**Comment by luiscvtomas** [comment]
I've already reinstalled pip (because of ImportError: cannot import name IncompleteRead) and updated flexget to the last version (1.2.438)

**Comment by Tskmst** [comment]
I am getting the same error.

Example 1:
imdb_lookup    MOVIES    Parsing imdb for `Holland Road 2015 720p WEBRIP x264 AC3-NoHaTE`
utils.imdb    MOVIES          Possible IMDB parser needs updating, Please report on Github.
imdb_lookup   MOVIES          Unable to set imdb_name for tt2369740 from http://www.imdb.com/title/tt2369740/

Example:2

imdb_lookup MOVIES Parsing imdb for `Freaks Of Nature 2015 LIMITED 720p BluRay x264-SNOW`
utils.imdb    MOVIES    Possible IMDB parser needs updating, Please report on Github.
imdb_lookup MOVIES Unable to set imdb_name for tt1817771 from http://www.imdb.com/title/tt1817771/

pip 8.0.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
Flexget Version: 1.2.438

**Comment by chewy74** [comment]
Same here.  Crash log :

2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for tom and jerry mouse trouble 2014 dvdrip xvid ac3 acab
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for mickey mouse clubhouse: minnie rella 2014 dvdrip x264 ac3 titan
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for buddy hutchins - falling down again 2015 bdrip x264-noscreens
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for buddy.hutchins-falling.down.again.2015.720p.brrip.x264.aac-etrg
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for buddy hutchins - falling down again 2015 bdrip x264-noscreens
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for buddy.hutchins-falling.down.again.2015.1080p.brrip.x264.aac-etrg
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for natures.microworlds.series.2.1of6.canadas.coastal.forests.576p.hdtv.x264.aac .mp4
2016-01-27 11:00 VERBOSE  tmdb_lookup   movies          TMDB lookup failed for Natures.Microworlds.Series.2.1of6.Canadas.Coastal.Forests.576p.HDTV.x264.AAC .mp4
2016-01-27 11:00 VERBOSE  movie_queue   movies          IMDB and TMDB lookups failed for Natures.Microworlds.Series.2.1of6.Canadas.Coastal.Forests.576p.HDTV.x264.AAC .mp4.
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for wild.australia.4of4.koala.forest.720p.hdtv.x264.aac .mp4
2016-01-27 11:00 VERBOSE  tmdb_lookup   movies          TMDB lookup failed for Wild.Australia.4of4.Koala.Forest.720p.HDTV.x264.AAC .mp4
2016-01-27 11:00 VERBOSE  movie_queue   movies          IMDB and TMDB lookups failed for Wild.Australia.4of4.Koala.Forest.720p.HDTV.x264.AAC .mp4.
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for the shuttered room - [thriller] - (1967) - dvdrip -  [=faith=]
2016-01-27 11:00 VERBOSE  tmdb_lookup   movies          TMDB lookup failed for The Shuttered Room - [Thriller] - (1967) - DVDRip -  [=Faith=]
2016-01-27 11:00 VERBOSE  movie_queue   movies          IMDB and TMDB lookups failed for The Shuttered Room - [Thriller] - (1967) - DVDRip -  [=Faith=].
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Imdb lookup failed for shut.your.facebook.720p.hdtv.x264-barge
2016-01-27 11:00 VERBOSE  tmdb_lookup   movies          TMDB lookup failed for Shut.Your.Facebook.720p.HDTV.x264-BARGE
2016-01-27 11:00 VERBOSE  movie_queue   movies          IMDB and TMDB lookups failed for Shut.Your.Facebook.720p.HDTV.x264-BARGE.
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Parsing imdb for `The Forsaken (2001) DvdRip Xvid {1337x}-Noir`
2016-01-27 11:00 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin
2016-01-27 11:00 CRITICAL manager       movies          An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2016.01.27.110044487345.log
2016-01-27 11:00 INFO     imdb_lookup   movies          Imdb lookup failed for prophecy forsaken2005 dvdrip xvid ac35 1eng-hlawoun
2016-01-27 11:00 VERBOSE  tmdb_lookup   movies          TMDB lookup failed for Prophecy Forsaken2005 Dvdrip Xvid AC35 1Eng-hlawoun
2016-01-27 11:00 VERBOSE  movie_queue   movies          IMDB and TMDB lookups failed for Prophecy Forsaken2005 Dvdrip Xvid AC35 1Eng-hlawoun.
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Searching from imdb `By The Sea 2015 HC WEBRip XviD-FGT`
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Found http://www.imdb.com/title/tt3707106/?ref_=fn_ft_tt_1
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Parsing imdb for `By The Sea 2015 HC WEBRip XviD-FGT`
2016-01-27 11:00 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin
2016-01-27 11:00 CRITICAL manager       movies          An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2016.01.27.110051744482.log
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Searching from imdb `By.the.Sea.2015.HC.HDRip.XviD.AC3-EVO`
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Found http://www.imdb.com/title/tt3707106/?ref_=fn_ft_tt_1
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Parsing imdb for `By.the.Sea.2015.HC.HDRip.XviD.AC3-EVO`
2016-01-27 11:00 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin
2016-01-27 11:00 CRITICAL manager       movies          An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2016.01.27.110059123788.log
2016-01-27 11:00 VERBOSE  imdb_lookup   movies          Searching from imdb `By the Sea (2015) 720p HC HDRip 900MB - MkvCage`
2016-01-27 11:01 VERBOSE  imdb_lookup   movies          Found http://www.imdb.com/title/tt3707106/?ref_=fn_ft_tt_1
2016-01-27 11:01 VERBOSE  imdb_lookup   movies          Parsing imdb for `By the Sea (2015) 720p HC HDRip 900MB - MkvCage`
2016-01-27 11:01 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin
2016-01-27 11:01 CRITICAL manager       movies          An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2016.01.27.110106125266.log
2016-01-27 11:01 VERBOSE  imdb_lookup   movies          Parsing imdb for `By the Sea 2015 HDRip XviD AC3-iFT`
2016-01-27 11:01 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin
2016-01-27 11:01 CRITICAL manager       movies          An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2016.01.27.110109878944.log
2016-01-27 11:01 VERBOSE  imdb_lookup   movies          Parsing imdb for `By the Sea 2015 HDRip XviD AC3-EVO`
2016-01-27 11:01 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin
2016-01-27 11:01 CRITICAL manager       movies          An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2016.01.27.110114219925.log
2016-01-27 11:01 VERBOSE  imdb_lookup   movies          Parsing imdb for `By the Sea 2015 HDRip XviD AC3-EVO`
2016-01-27 11:01 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin
2016-01-27 11:01 CRITICAL manager       movies          An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2016.01.27.110118034975.log
2016-01-27 11:01 VERBOSE  imdb_lookup   movies          Parsing imdb for `By the Sea (2015) HC - 720p WEBRiP - 1GB - ShAaNiG`
2016-01-27 11:01 ERROR    lazy_lookup   movies          Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 235, in lazy_loader
    self.lookup(entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 374, in lookup
    movie = self._parse_new_movie(entry['imdb_url'], session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/imdb_lookup.py", line 405, in _parse_new_movie
    parser.parse(imdb_url)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/imdb.py", line 245, in parse
    log.error('Possible IMDB parser needs updating, Please report on Github.')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by alneven** [comment]
I guess this will be fixed very soon. ;-)

**Comment by Kerwood** [comment]
Got same issue.. Guess its a general thing
```
Possible IMDB parser needs updating, Please report on Github.
```

**Comment by crack00r** [comment]
Same here, waiting for update.  :)
