### ISSUE TITLE
series_premiere BUG

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#828]
```
2016-01-28 08:30 VERBOSE  series        premieren       Found different quality for The.Leftovers.S02E05.Kein.Platz.in.der.Herberge.German.DD51.Dubbed.DL.720p.HDTV.x264-TVS. Was 720p hdtv h264 dd5.1, overriding with 720p hdtv h264.
2016-01-28 08:30 CRITICAL task          premieren       BUG: Unhandled error in plugin series_premiere: 'latin-1' codec can't encode character u'\u2013' in position 23: ordinal not in range(256)
Traceback (most recent call last):
  File "/home/manuel/flexget-dev/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/home/manuel/flexget-dev/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/manuel/flexget-dev/flexget/plugins/filter/series_premiere.py", line 62, in on_task_metainfo
    if guess_entry(entry, allow_seasonless=allow_seasonless, config=group_settings):
  File "/home/manuel/flexget-dev/flexget/plugins/metainfo/series.py", line 43, in guess_entry
    allow_seasonless=allow_seasonless)
  File "/home/manuel/flexget-dev/flexget/plugins/parsers/plugin_parsing.py", line 70, in parse_series
    return parser.parse_series(data, name=name, **kwargs)
  File "/home/manuel/flexget-dev/flexget/plugins/parsers/parser_guessit.py", line 315, in parse_series
    guess_result = guessit_api.guessit(data, options=guessit_options)
  File "/home/manuel/flexget-dev/local/lib/python2.7/site-packages/guessit/api.py", line 71, in guessit
    string = string.encode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2013' in position 23: ordinal not in range(256)
```

**Comment by crack00r** [comment]
seams to be a python problem
http://stackoverflow.com/questions/24358361/removing-u2018-and-u2019-character
how to fix this?

**Comment by crack00r** [comment]
found it,it comes from rss 
DC’s.Legends.of.Tomorrow.S01E01.Pilot.Part.1.720p.WEB-DL.DD5.1.H.264-LoT
http://serienjunkies.org/dcs-legends-of-tomorrow/dcs-legends-of-tomorrow-season-1-hdtv-1080p/

**Comment by crack00r** [comment]
it seams to crash on u'\u2013'  u'\u2018'  u'\u2019' thats all crashs i have till now

**Comment by liiight** [comment]
Try not to use guessit, see if that works

**Comment by crack00r** [comment]
this works, but didnt find much on imdb :D

**Comment by liiight** [comment]
Why imdb? Use tvmaze lookup

**Comment by crack00r** [comment]
Didnt find anything too... 
So, guessit is the Problem for latin Error?

**Comment by liiight** [comment]
No way tvmaze didn't find anything. And yeah, this is definitely a guessit issue but with all other issues it's experiencing currently, it's of no use to even try to address this. 
The problem is that we have conflicting dependencies since we require v2 of guessit but subliminal requires a lower version so it downgrades it during installation. 
Once this business is resolved it would be possible to address guessit issues again. 
Until then I suggest we pick this up in the forums, tvmaze should work.

**Comment by crack00r** [comment]
Ok,  hope for fast fix :) 
Thx

**Comment by crack00r** [comment]
https://github.com/guessit-io/guessit/issues/263#issuecomment-177129718

**Comment by liiight** [comment]
Requirements updated here too, thanks for reporting
