### ISSUE TITLE
Cannot upgrade flexget to 1.2.440 this happens.

### ISSUE THREAD

**Issue by puhoh** [Flexget/Flexget#829]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pivIGC/flexget/setup.py", line 10, in <module>
        paver.tasks.main()
      File "paver-minilib.zip/paver/tasks.py", line 878, in main
      File "paver-minilib.zip/paver/tasks.py", line 858, in _launch_pavement
      File "paver-minilib.zip/paver/tasks.py", line 809, in _process_commands
      File "paver-minilib.zip/paver/setuputils.py", line 173, in __call__
      File "paver-minilib.zip/paver/setuputils.py", line 58, in _dispatch_setuptools_install
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 613, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/install_data.py", line 74, in run
        (out, _) = self.copy_file(data, dir)
      File "/usr/lib/python2.7/distutils/cmd.py", line 365, in copy_file
        dry_run=self.dry_run)
      File "/usr/lib/python2.7/distutils/file_util.py", line 110, in copy_file
        "can't copy '%s': doesn't exist or not a regular file" % src)
    distutils.errors.DistutilsFileError: can't copy 'extras/bash_completion/flexget': doesn't exist or not a regular file
    
    ----------------------------------------
    Rolling back uninstall of FlexGet
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-pivIGC/flexget/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-X1sGBW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-pivIGC/flexget

**Comment by puhoh** [comment]
I have just tried to clean the dist-packages in /usr/local/lib/python2.7/dist-packages/flexget/* and reinstalled it, same error but now i can run flexget check and -V.

**Comment by subterfugium** [comment]
This is happening to me too.

**Comment by Kerwood** [comment]
Can confirm, same issue.

**Comment by stevezau** [comment]
confirmed bug in the package process. @gazpachoking  is the only one how has access to re-run it and hes MIA at the moment. The next release will run in 24hrs worst case.

**Comment by stevezau** [comment]
fixed in release 1.2.442
