### ISSUE TITLE
Series begin sqlite3 error

### ISSUE THREAD

**Issue by wtluke** [Flexget/Flexget#835]
This is related to but different from https://github.com/Flexget/Flexget/issues/814 - as mentioned by Bouke:

`flexget series begin "The X-Files (1993)" S10E01
There is a FlexGet process already running for this config, sending execution there.
Series not yet in database, adding The X-Files (1993)`

`Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 9, in <module>
    load_entry_point('FlexGet==1.2.441', 'console_scripts', 'flexget')()
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 283, in start
    client.handle_cli(self.args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
rpyc.core.vinegar/sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 75, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 327, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/series.py", line 28, in do_cli
    begin(manager, options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/series.py", line 112, in begin
    set_series_begin(series, ep_id)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 691, in set_series_begin
    filter(Episode.identifier == str(ep_id)).first())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2735, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1315, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1305, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO series (name, name_lower, identified_by, begin_episode_id) VALUES (?, ?, ?, ?)'] [parameters: (u'The X-Files (1993)', u'the x files 1993', u'ep', None)]
`

I'm on 1.2.441

**Comment by scottwallacesh** [comment]
I'm seeing something similar.  If I leave the parentheses out, it works.

**Comment by liiight** [comment]
Locked db isn't supposed to happen. Try rebooting

**Comment by wtluke** [comment]
I should have elaborated: the series is already in the database so it shouldn't need to be re-added.

**Comment by liiight** [comment]
It's not being readded, you're not getting a unique constrain violation you're getting a db lock

**Comment by wtluke** [comment]
OK. It just seems as though it is trying to re-add it, perhaps because it is unable to cope with the punctuation (hyphen) when looking it up:

`flexget series begin "The X-Files (1993)" S10E01
Series not yet in database, adding The X-Files (1993)`

**Comment by liiight** [comment]
Yeah, I see the problem now, fixing.
