### ISSUE TITLE
Daemon hangs on apscheduler error

### ISSUE THREAD

**Issue by liiight** [Flexget/Flexget#846]
Daemon appears to sometimes hang on apscheduler error:

`2016-02-01 13:03 WARNING  apscheduler.scheduler                 Execution of job "scan* (trigger: interval[0:05:00], next run at: 2016-02-01 13:03:50 IST)" skipped: maximum number of running instances reached (1)`

Even weirder, when running daemon in the foreground and hitting any key on that error, daemon operation seems to pick up again.

**Comment by lepinkainen** [comment]
I have the same issue. Sometimes it hangs with no message, but the latest hang was that message repeated over and over again.

**Comment by kolyagora** [comment]
Looks like I have the same problem, missed few episodes recently because tasks didn't start on schedule.

**Comment by gazpachoking** [comment]
I have added some debug log lines to help determine where things are going wrong. If someone can capture these lines on the last successful run of a schedule perhaps that will help debug.

ce0c57eb26faf87dbafc3fe6a35c3365d89697a1

**Comment by gazpachoking** [comment]
I've now added `list_add` plugin, which is an output plugin that can add to any list implementing my 2nd list interface prototype.

**Comment by liiight** [comment]
From #976:
> I'm not entirely sure if this is an issue for flexget, or if it's something that the APScheduler program should address, but I have noticed for some time that while running flexget through an UpStart daemon on Ubuntu (currently version 14.04), it will stop running tasks. I am needing to then restart the daemon (sudo restart flexget) which gets it working again for some time. Sometimes it will continue working for days, other times I will need to restart it multiple times throughout the day. After digging around, I found the following exception in the UpStart log file (/var/log/upstart/flexget.log), which does not appear in the ~/.flexget/flexget.log file. Every time flexget stops working recently with the scheduler, this exception has shown up in the log file. I have not noticed any other indications that it has stopped working. It appears to finish the current set of tasks that were triggered, but no further tasks will run after this.

```
Exception in thread APScheduler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 27, in _main_loop
    wait_seconds = self._process_jobs()
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 828, in _process_jobs
    jobstore.update_job(job)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 93, in update_job
    result = self.engine.execute(update)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) database is locked [SQL: u'UPDATE apscheduler_jobs SET next_run_time=?, job_state=? WHERE apscheduler_jobs.id = ?'] [parameters: (1459051243.056874, <read-only buffer for 0x7fbfac013ff0, size -1, offset 0 at 0x7fbfb013cdb0>, '7eb4c4245467539fd3b9baa4fecb8cdc20487ea9')]
```

**Comment by xathin** [comment]
For me, it appears to happen mostly when a task overruns another task (takes too long when another should start). It doesn't seem to happen every time tasks overrun however.

I have updated my config to execute an echo line on start and stop of each task, and echo a "Still working" line every 30 minutes to see if it can be narrowed down any further also.

**Comment by Nihim** [comment]
Ya same for me was running it with -L debug daemon start -d and after a crash with APscheduler it fully froze.

```
2016-03-28 21:14 INFO     apscheduler.executors.default                 Job "Horrible (trigger: interval[0:01:00], next run at: 2016-03-28 21:15:22 CEST)" executed successfully
Traceback (most recent call last):
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 69, in wrapper
    return func(self, *args, **kw)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 579, in execute
    self._execute()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 511, in _execute
    last_hash = session.query(TaskConfigHash).filter(TaskConfigHash.task == self.name).first()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT feed_config_hash.name AS feed_config_hash_name, feed_config_hash.id AS feed_config_hash_id, feed_config_hash.hash AS feed_config_hash_hash \nFROM feed_config_hash \nWHERE feed_config_hash.name = ?\n LIMIT ? OFFSET ?'] [parameters: (u'Horrible', 1, 0)]

```

Full part from the log:

```

2016-03-28 21:13 VERBOSE  details       Horrible        Summary - Accepted: 0 (Rejected: 20 Undecided: 0 Failed: 0)
2016-03-28 21:13 DEBUG    util.simple_persistence Horrible        Flushing simple persistence for task Horrible to db.
2016-03-28 21:13 DEBUG    util.simple_persistence Horrible        Flushing simple persistence for task None to db.
2016-03-28 21:13 DEBUG    scheduler                     all tasks in schedule finished executing
2016-03-28 21:13 INFO     apscheduler.executors.default                 Job "Horrible (trigger: interval[0:01:00], next run at: 2016-03-28 21:14:22 CEST)" executed successfully
2016-03-28 21:14 DEBUG    apscheduler.scheduler                 Looking for jobs to run
2016-03-28 21:14 INFO     apscheduler.executors.default                 Running job "Horrible (trigger: interval[0:01:00], next run at: 2016-03-28 21:14:22 CEST)" (scheduled at 2016-03-28 21:14:22.261848+02:00)
2016-03-28 21:14 DEBUG    scheduler                     executing tasks: [u'Horrible']
2016-03-28 21:14 DEBUG    scheduler                     task finished executing: Horrible
2016-03-28 21:14 DEBUG    manager       Horrible        Not running db cleanup, last run 2016-03-24 09:23:29
2016-03-28 21:14 DEBUG    task          Horrible        executing Horrible
2016-03-28 21:14 DEBUG    scheduler                     all tasks in schedule finished executing
2016-03-28 21:14 INFO     apscheduler.executors.default                 Job "Horrible (trigger: interval[0:01:00], next run at: 2016-03-28 21:15:22 CEST)" executed successfully
2016-03-28 21:14 CRITICAL task_queue                    Database error while running a task. Attempting to recover.
2016-03-28 21:14 DEBUG    apscheduler.scheduler                 Next wakeup is due at 2016-03-28 21:15:00.107046+02:00 (in 37.457476 seconds)
2016-03-28 21:14 CRITICAL manager                       An unexpected crash has occurred. Writing crash report to /home/nihim/.flexget/crash_report.2016.03.28.211434604601.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.495
2016-03-28 21:14 DEBUG    manager                       Traceback:
Traceback (most recent call last):
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 69, in wrapper
    return func(self, *args, **kw)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 579, in execute
    self._execute()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 511, in _execute
    last_hash = session.query(TaskConfigHash).filter(TaskConfigHash.task == self.name).first()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'SELECT feed_config_hash.name AS feed_config_hash_name, feed_config_hash.id AS feed_config_hash_id, feed_config_hash.hash AS feed_config_hash_hash \nFROM feed_config_hash \nWHERE feed_config_hash.name = ?\n LIMIT ? OFFSET ?'] [parameters: (u'Horrible', 1, 0)]
2016-03-28 21:15 DEBUG    apscheduler.scheduler                 Looking for jobs to run
2016-03-28 21:15 INFO     apscheduler.executors.default                 Running job "rest,Hor_mag (trigger: interval[0:02:00], next run at: 2016-03-28 21:15:00 CEST)" (scheduled at 2016-03-28 21:15:00.107046+02:00)
2016-03-28 21:15 DEBUG    scheduler                     executing tasks: [u'rest', u'Hor_mag']
2016-03-28 21:15 DEBUG    scheduler                     task finished executing: rest
2016-03-28 21:15 DEBUG    manager       rest            Not running db cleanup, last run 2016-03-24 09:23:29
2016-03-28 21:15 DEBUG    task          rest            executing rest
2016-03-28 21:15 DEBUG    apscheduler.scheduler                 Next wakeup is due at 2016-03-28 21:15:22.261848+02:00 (in 9.793882 seconds)
2016-03-28 21:15 DEBUG    template      rest            Merging template glopr into task rest
2016-03-28 21:15 DEBUG    input_cache   rest            cache name: rss_ (has: rss_, rss_, rss_)
2016-03-28 21:15 VERBOSE  input_cache   rest            Restored 100 entries from cache
2016-03-28 21:15 DEBUG    backlog       rest            0 entries purged from backlog
2016-03-28 21:15 VERBOSE  details       rest            Produced 100 entries.


FILES REJECTED

2016-03-28 21:15 DEBUG    urlrewriter   rest            Checking 0 entries
2016-03-28 21:15 VERBOSE  details       rest            Summary - Accepted: 0 (Rejected: 67 Undecided: 33 Failed: 0)
2016-03-28 21:15 DEBUG    util.simple_persistence rest            Flushing simple persistence for task rest to db.
2016-03-28 21:15 DEBUG    apscheduler.scheduler                 Looking for jobs to run
2016-03-28 21:16 DEBUG    util.simple_persistence rest            Flushing simple persistence for task None to db.
2016-03-28 21:16 DEBUG    scheduler                     task finished executing: Hor_mag
2016-03-28 21:16 DEBUG    manager       Hor_mag         Not running db cleanup, last run 2016-03-24 09:23:29
2016-03-28 21:16 DEBUG    task          Hor_mag         executing Hor_mag
2016-03-28 21:16 DEBUG    template      Hor_mag         Merging template glopr into task Hor_mag
2016-03-28 21:16 DEBUG    input_cache   Hor_mag         cache name: rss_ (has: rss_, rss_, rss_)
2016-03-28 21:16 VERBOSE  input_cache   Hor_mag         Restored 25 entries from cache
2016-03-28 21:16 DEBUG    backlog       Hor_mag         0 entries purged from backlog
2016-03-28 21:16 VERBOSE  details       Hor_mag         Produced 25 entries.

FILES REJECTED

2016-03-28 21:16 DEBUG    urlrewriter   Hor_mag         Checking 0 entries
2016-03-28 21:16 VERBOSE  details       Hor_mag         Summary - Accepted: 0 (Rejected: 25 Undecided: 0 Failed: 0)
2016-03-28 21:16 DEBUG    util.simple_persistence Hor_mag         Flushing simple persistence for task Hor_mag to db.
2016-03-28 21:16 DEBUG    util.simple_persistence Hor_mag         Flushing simple persistence for task None to db.
2016-03-28 21:16 DEBUG    scheduler                     all tasks in schedule finished executing
2016-03-28 21:16 INFO     apscheduler.executors.default                 Job "rest,Hor_mag (trigger: interval[0:02:00], next run at: 2016-03-28 21:17:00 CEST)" executed successfully
```
And it's dead after that.

**Comment by antivirtel** [comment]
I'm still getting this (v1.2.499): 
```
2016-04-01 22:53 WARNING  apscheduler.scheduler                 Execution of job "* (trigger: interval[0:16:00], next run at: 2016-04-01 22:51:26 CEST)" skipped: maximum number of running instances reached (1)
```

My schedule is for * (all) tasks:
```
  - tasks: '*'
    interval:
      minutes: 16
```

Can I do something, to avoid this? It seems it is skipping some executions, while I scheduled the tasks to run every 16 minutes... It doesn't seem to bee possible.

**Comment by cvium** [comment]
Reopen if still relevant.

**Comment by yolob2112** [comment]
is it supposed to be fixed? I am running flexget 2.10.75, I occasionally get the apscheduler error as mentioned in the title of the thread

**Comment by antivirtel** [comment]
Me too, if there is high load, then it could be received.

**Comment by rdpdo** [comment]
Same issue here !

**Comment by guptarohit** [comment]
Any solution for this??

**Comment by cvium** [comment]
We can't reliably reproduce it, so we can't really fix it.

**Comment by santorototdrei** [comment]
Any update solution for this problem.

**Comment by superfunkminister** [comment]
+1

**Comment by uwings** [comment]
Any update solution for this problem.

**Comment by Arturoe1** [comment]
Same issue here, when it gets some errors while sending to deluge the daemon hangs like it have a running instance. I do believe if we could setup the maximum runtime by a parameter for any instance  and close it/ ignore it if the time has pass it would solve this issue.
