### ISSUE TITLE
Problem downloading via t411

### ISSUE THREAD

**Issue by pedro2d10** [Flexget/Flexget#853]
Hello everyone,

I have a problem with flex get and the t411 plugging (i guess). Flex get can't retrieve the url to download.
Here my log
```
2016-02-04 17:56 DEBUG urlrewriter download2 Checking 3 entries 
2016-02-04 17:56 INFO download download2 Downloading: The Big Bang Theory S07E25 
2016-02-04 17:56 DEBUG download download2 Downloading url '' 
2016-02-04 17:56 DEBUG requests No adaptor, passing off to urllib 
2016-02-04 17:56 WARNING download download2 ValueError unknown url type: 
2016-02-04 17:56 DEBUG download download2 ValueError unknown url type: 
Traceback (most recent call last): 
File "/opt/local/lib/python2.7/site-packages/flexget/plugins/output/download.py", line 195, in process_entry self.download_entry(task, entry, url, tmp_path) 
File "/opt/local/lib/python2.7/site-packages/flexget/plugins/output/download.py", line 232, in download_entry response = task.requests.get(url, auth=auth, raise_status=False) 
File "/opt/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get return self.request('GET', url, **kwargs) 
File "/opt/local/lib/python2.7/site-packages/flexget/utils/requests.py", line 149, in request return _wrap_urlopen(url, timeout=kwargs['timeout']) 
File "/opt/local/lib/python2.7/site-packages/flexget/utils/requests.py", line 77, in _wrap_urlopen raw = urllib2.urlopen(url, timeout=timeout) 
File "/opt/lib/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) 
File "/opt/lib/python2.7/urllib2.py", line 423, in open protocol = req.get_type() File "/opt/lib/python2.7/urllib2.py", line 285, in get_type raise ValueError, "unknown url type: %s" % self.__original ValueError: unknown url type:
```
Thank you for your help.

**Comment by liiight** [comment]
can you paste your config please?
