### ISSUE TITLE
lazy lookup: timeout: timed out

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#858]
Hi! I've just got this with version 1.2.450.

```
2016-02-09 21:05 CRITICAL manager       nC_movie-HUN    An unexpected crash has occurred. Writing crash report to /home/osmc/.flexget/crash_rep
ort.2016.02.09.210527668896.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version
_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.450
2016-02-09 21:05 WARNING  movie_queue   nC_movie-HUN    IMDB and TMDB lookups failed for The.Intern.2015.BD25.AVC.DTSHD.HUN-HDPhoenix.
2016-02-09 21:05 ERROR    lazy_lookup   nC_movie-HUN    Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/tmdb_lookup.py", line 62, in lazy_loader
    session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tmdb.py", line 309, in lookup
    result = _first_result(tmdb3.tmdb_api.searchMovie(title.lower(), adult=True))
  File "/usr/local/lib/python2.7/dist-packages/tmdb3/tmdb_api.py", line 133, in searchMovie
    return MovieSearchResult(Request('search/movie', **kwargs), locale=locale)
  File "/usr/local/lib/python2.7/dist-packages/tmdb3/tmdb_api.py", line 162, in __init__
    lambda x: Movie(raw=x, locale=locale))
  File "/usr/local/lib/python2.7/dist-packages/tmdb3/pager.py", line 109, in __init__
    super(PagedRequest, self).__init__(self._getpage(1), 20)
  File "/usr/local/lib/python2.7/dist-packages/tmdb3/pager.py", line 62, in __init__
    self._data = list(iterable)
  File "/usr/local/lib/python2.7/dist-packages/tmdb3/pager.py", line 113, in _getpage
    res = req.readJSON()
  File "/usr/local/lib/python2.7/dist-packages/tmdb3/cache.py", line 131, in __call__
    data = self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tmdb3/request.py", line 118, in readJSON
    data = json.load(self.open())
  File "/usr/local/lib/python2.7/dist-packages/tmdb3/request.py", line 104, in open
    return urllib2.urlopen(self)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```

**Comment by liiight** [comment]
Related #671

**Comment by gazpachoking** [comment]
Looks like the tmdb3 library we are using tries to partially abstract away network errors, but doesn't do it completely. Perhaps it's worth switching to a different library. This one https://github.com/celiao/tmdbsimple is built on requests and doesn't try to abstract away the network errors at all, might be nicer to use that and just trow the api calls in a `RequestException` try block.
