### ISSUE TITLE
Apple_trailers chokes on missing genre

### ISSUE THREAD

**Issue by KronK0321** [Flexget/Flexget#865]
I've had this issue since mid-January.

```
jordan@claire:~/test-flexget$ flexget -V
1.2.452
You are on the latest release.
```

config.yml:
```
tasks:
  appletrailers:
    apple_trailers:
      quality: 720p
      genres:
        - all
    accept_all: yes
    download: ~/
```

debug log:
```
2016-02-13 22:24 DEBUG    manager                       Figuring out config load paths
2016-02-13 22:24 DEBUG    manager                       Found config: /home/jordan/test-flexget/./config.yml
2016-02-13 22:24 DEBUG    manager                       Config file /home/jordan/test-flexget/./config.yml selected
2016-02-13 22:24 DEBUG    manager                       sys.defaultencoding: ascii
2016-02-13 22:24 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-02-13 22:24 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-02-13 22:24 DEBUG    plugin                        Trying to load plugins from: [u'/home/jordan/test-flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2016-02-13 22:24 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-02-13 22:24 DEBUG    plugin                        Plugins took 2.49 seconds to load
2016-02-13 22:24 DEBUG    manager                       Connecting to: sqlite:////home/jordan/test-flexget/db-config.sqlite
2016-02-13 22:24 DEBUG    manager                       config_name: config
2016-02-13 22:24 DEBUG    manager                       config_base: /home/jordan/test-flexget
2016-02-13 22:24 DEBUG    manager                       New config data loaded.
2016-02-13 22:24 DEBUG    cron_env                      Encoding UTF-8 stored
2016-02-13 22:24 DEBUG    util.simple_persistence                 setting key terminal_encoding value 'UTF-8'
2016-02-13 22:24 DEBUG    task_queue                    task queue shutdown requested
2016-02-13 22:24 INFO     ipc.rpyc                      server started on [127.0.0.1]:38529
2016-02-13 22:24 DEBUG    task          appletrailers   executing appletrailers
2016-02-13 22:24 DEBUG    template      appletrailers   Merging template global into task appletrailers
2016-02-13 22:24 DEBUG    headers       appletrailers   headers to add: {u'User-Agent': u'Quicktime/7.7'}
2016-02-13 22:24 DEBUG    headers       appletrailers   Creating new opener and installing it
2016-02-13 22:24 DEBUG    input_cache   appletrailers   cache name: apple_trailers_bc865a7d4cee06565b4c37fd23207b65 (has: )
2016-02-13 22:24 DEBUG    input_cache   appletrailers   cache name: rss_b69cadf846488414b4898550ed7ae64b (has: )
2016-02-13 22:24 DEBUG    rss           appletrailers   Requesting task `appletrailers` url `http://trailers.apple.com/trailers/home/rss/newtrailers.rss`
2016-02-13 22:24 DEBUG    requests                      Fetching http://trailers.apple.com/trailers/home/rss/newtrailers.rss
2016-02-13 22:24 DEBUG    util.simple_persistence appletrailers   setting key 1119626039_etag value '"9a75-52b9b710a9f00"'
2016-02-13 22:24 DEBUG    rss           appletrailers   etag "9a75-52b9b710a9f00" saved for task appletrailers
2016-02-13 22:24 DEBUG    util.simple_persistence appletrailers   setting key 1119626039_modified value 'Fri, 12 Feb 2016 23:58:20 GMT'
2016-02-13 22:24 DEBUG    rss           appletrailers   last modified Fri, 12 Feb 2016 23:58:20 GMT saved for task appletrailers
2016-02-13 22:24 DEBUG    rss           appletrailers   encoding iso-8859-1
2016-02-13 22:24 DEBUG    rss           appletrailers   Saving location in rss feed.
2016-02-13 22:24 DEBUG    util.simple_persistence appletrailers   setting key 1119626039_last_entry value u'Road Games - Trailer'
2016-02-13 22:24 DEBUG    input_cache   appletrailers   storing to cache rss_b69cadf846488414b4898550ed7ae64b 20 entries
2016-02-13 22:24 DEBUG    requests                      Fetching http://trailers.apple.com/trailers/ifcfilms/thepreppieconnection/#gallery-film-info-details
2016-02-13 22:24 DEBUG    apple_trailers appletrailers   genre(s) not found
2016-02-13 22:24 CRITICAL task          appletrailers   BUG: Unhandled error in plugin apple_trailers: 'NoneType' object has no attribute 'next_sibling'
2016-02-13 22:24 CRITICAL manager       appletrailers   An unexpected crash has occurred. Writing crash report to /home/jordan/test-flexget/crash_report.2016.02.13.222426707720.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.452
2016-02-13 22:24 DEBUG    manager       appletrailers   Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 140, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/apple_trailers.py", line 107, in on_task_input
    for genre_name in genre_head.next_sibling.contents:
AttributeError: 'NoneType' object has no attribute 'next_sibling'
2016-02-13 22:24 WARNING  task          appletrailers   Aborting task (plugin: apple_trailers)
2016-02-13 22:24 DEBUG    headers       appletrailers   Removing urllib2 default opener
2016-02-13 22:24 DEBUG    task_queue                    task appletrailers aborted: TaskAbort(reason=BUG: Unhandled error in plugin apple_trailers: 'NoneType' object has no attribute 'next_sibling', silent=False)
2016-02-13 22:24 DEBUG    task_queue                    task queue shut down
2016-02-13 22:24 INFO     ipc.rpyc                      listener closed
2016-02-13 22:24 DEBUG    util.simple_persistence                 Flushing simple persistence for task None to db.
2016-02-13 22:24 INFO     ipc.rpyc                      server has terminated
2016-02-13 22:24 DEBUG    manager                       Shutting down
2016-02-13 22:24 DEBUG    manager                       Removed /home/jordan/test-flexget/.config-lock
```

**Comment by liiight** [comment]
looks like the current layout has nothing to do with our parsing of it anymore. needs updating

**Comment by cvium** [comment]
This issue has been fixed and `apple_trailers` should be fully functional in the next release. You can re-open this issue if the problem persists.
