### ISSUE TITLE
Upgrade 1.2.456 BROKEN

### ISSUE THREAD

**Issue by matthieugoua** [Flexget/Flexget#872]
encoder@sd-39044:~$ flexget -V
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3141, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3127, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 642, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 655, in _build_from_requirements
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 828, in resolve
pkg_resources.DistributionNotFound: The 'FlexGet==1.2.455' distribution was not found and is required by the application

**Comment by gazpachoking** [comment]
How did you install/upgrade?

**Comment by matthieugoua** [comment]
pip install --upgrade flexget

**Comment by gazpachoking** [comment]
And pip reported that the install was successful? It seems like the flexget script you are running isn't the one from your latest flexget install.

**Comment by matthieugoua** [comment]
yes reported successful

**Comment by matthieugoua** [comment]
force reinstall 1.2.455 and it's work
pip install --upgrade --force-reinstall FlexGet==1.2.455

1.2.455
Latest release: 1.2.456

no possible upgrade
