### ISSUE TITLE
flexget service install windoes 10 - No module named win32file

### ISSUE THREAD

**Issue by rlantigua1** [Flexget/Flexget#873]
I'm getting this error trying to flexget service install on a fresh windows 10 machine. any ideas.?

c:\python27\Scripts\flexget service install --username #### --password #####
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\Scripts\flexget.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\flexget\__init__.py", line 37, in main
    manager.start()
  File "C:\Python27\lib\site-packages\flexget\manager.py", line 300, in start
    self.handle_cli()
  File "C:\Python27\lib\site-packages\flexget\manager.py", line 327, in handle_cli
    options.cli_command_callback(self, command_options)
  File "C:\Python27\lib\site-packages\flexget\plugins\cli\win32_service.py", line 50, in do_cli
    import win32file
ImportError: No module named win32file

C:\Users\john\Desktop>pause
Press any key to continue . . .

My config file check ok. If I run flexget I get this error

c:\python27\Scripts\flexget -c

Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\Scripts\flexget.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\flexget\__init__.py", line 23, in main
    manager = Manager(args)
  File "C:\Python27\lib\site-packages\flexget\manager.py", line 137, in __init__
    self.options, extra = manager_parser.parse_known_args(args)
  File "C:\Python27\lib\site-packages\flexget\options.py", line 313, in parse_known_args
    namespace, args = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "C:\Python27\Lib\argparse.py", line 1740, in parse_known_args
    self.error(str(err))
  File "C:\Python27\lib\site-packages\flexget\options.py", line 291, in error
    raise ParserError(msg, self)
flexget.options.ParserError

**Comment by liiight** [comment]
http://flexget.com/wiki/Plugins/cli/service
