### ISSUE TITLE
Parser error fresh windows 10. 

### ISSUE THREAD

**Issue by rlantigua1** [Flexget/Flexget#875]
C:\Users\john\Desktop>c:\python27\Scripts\flexget  -c --test
Traceback (most recent call last):
  File "c:\python27\Scripts\flexget-script.py", line 9, in <module>
    load_entry_point('FlexGet==1.2.458', 'console_scripts', 'flexget')()
  File "C:\Python27\lib\site-packages\flexget\__init__.py", line 23, in main
    manager = Manager(args)
  File "C:\Python27\lib\site-packages\flexget\manager.py", line 137, in __init__
    self.options, extra = manager_parser.parse_known_args(args)
  File "C:\Python27\lib\site-packages\flexget\options.py", line 313, in parse_known_args
    namespace, args = super(ArgumentParser, self).parse_known_args(args, namespace)
  File "C:\Python27\Lib\argparse.py", line 1727, in parse_known_args
    self.error(str(err))
  File "C:\Python27\lib\site-packages\flexget\options.py", line 291, in error
    raise ParserError(msg, self)
flexget.options.ParserError

followed this instructions
http://flexget.com/wiki/InstallWizard/Windows

**Comment by liiight** [comment]
You need to put config file after - c and a command like execute. Weird that you didn't get a better error though

**Comment by rlantigua1** [comment]
Thanks that Helps!! 

c:\python27\Scripts\flexget execute -c config.YML --test
