### ISSUE TITLE
Upgrade to 1.2.458 with setuptools 20.2.1 fails, breaks Flexget

### ISSUE THREAD

**Issue by Perrylicious** [Flexget/Flexget#881]
Greetings,

upgrading from 1.2.456 to 1.2.458 on Ubuntu 14.04 with Python 2.7.6 via Pip (upgraded to latest setuptools beforehand) failed with the following error:

`Collecting flexget
Downloading FlexGet-1.2.458.tar.gz (2.1MB)
    100% |████████████████████████████████| 2.1MB 239kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6nxdMa/flexget/setup.py", line 10, in <module>
        paver.tasks.main()
      File "paver-minilib.zip/paver/tasks.py", line 878, in main
      File "paver-minilib.zip/paver/tasks.py", line 858, in _launch_pavement
      File "paver-minilib.zip/paver/tasks.py", line 797, in _process_commands
      File "paver-minilib.zip/paver/tasks.py", line 716, in _parse_command_line
      File "paver-minilib.zip/paver/tasks.py", line 672, in _preparse
      File "paver-minilib.zip/paver/tasks.py", line 120, in get_task
      File "paver-minilib.zip/paver/setuputils.py", line 191, in get_task
      File "paver-minilib.zip/paver/setuputils.py", line 221, in _get_distribution
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 132, in check_requirements
        raise DistutilsSetupError(tmpl.format(attr=attr, error=error))
    distutils.errors.DistutilsSetupError: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'!=0.9.0,'"`

    ----------------------------------------
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6nxdMa/flexget`

Flexget check or any attempt to interact with flexget now returns

`~$ flexget check
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2912, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2898, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 838, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2462, in requires
    dm = self._dep_map
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2457, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2762, in parse_requirements
    req = packaging.requirements.Requirement(line)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'!=0.9.0,'"`

Another user on the forums with the same issue from today:

http://discuss.flexget.com/t/upgraded-to-latest-and-now-errors-with---init---py/2071

Edit: Downgrading setuptools to 20.1 fixes this and enables installation of 1.2.458

**Comment by mgaulton** [comment]
This appears to have occurred on Opensuse Leap as well.

**Comment by Perrylicious** [comment]
Downgrading setuptools to 20.1 by running
`sudo pip install setuptools==20.1`
then
`sudo pip install --upgrade flexget`
successfully upgraded flexget to latest and restored functionality with me, so the issue is probably with the latest setuptools (but the upgrade guide on the flexget page advises to upgrade setuptools before upgrading flexget so at the moment you upgrade to an incompatible version of setuptools)

**Comment by grantland** [comment]
I ran into this problem as well. After downgrading setuptools to 20.1 and upgrading flexget, you have to re-downgrade setuptools to 20.1 since flexget's upgrade updates setuptools to 20.2.1:

```
grantland@ubuntu:~$ sudo pip install setuptools==20.1
The directory '/home/grantland/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/grantland/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting setuptools==20.1
  Downloading setuptools-20.1-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 475kB 708kB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 20.2.1
    Uninstalling setuptools-20.2.1:
      Successfully uninstalled setuptools-20.2.1
Successfully installed setuptools-20.1
grantland@ubuntu:~$ sudo pip install --upgrade flexget
The directory '/home/grantland/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/grantland/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: flexget in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: FeedParser>=5.2.1 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: SQLAlchemy!=0.9.0,<1.999,>=0.7.5 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: PyYAML in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: beautifulsoup4!=4.2.0,<4.5,>=4.1 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: html5lib>=0.11 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: PyRSS2Gen in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: pynzb in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: progressbar in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: rpyc in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: jinja2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: requests!=2.4.0,<2.99,>=1.0 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: python-dateutil!=2.0,!=2.2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: jsonschema>=2.0 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: tmdb3 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: path.py in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: guessit>=2.0.3 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: apscheduler in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: pytvmaze>=1.4.5 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: ordereddict>=1.1 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: cherrypy>=3.7.0 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask>=0.7 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-restful>=0.3.3 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-restplus==0.8.6 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-compress>=1.2.1 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-login>=0.3.2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: flask-cors>=2.1.2 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: pyparsing>=2.0.3 in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: Safe in /usr/local/lib/python2.7/dist-packages (from flexget)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from html5lib>=0.11->flexget)
Collecting setuptools (from pynzb->flexget)
  Downloading setuptools-20.2.1-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 544kB/s 
Requirement already up-to-date: plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc->flexget)
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python2.7/dist-packages (from jinja2->flexget)
Requirement already up-to-date: functools32 in /usr/local/lib/python2.7/dist-packages (from jsonschema>=2.0->flexget)
Requirement already up-to-date: rebulk>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from guessit>=2.0.3->flexget)
Requirement already up-to-date: babelfish>=0.5.5 in /usr/local/lib/python2.7/dist-packages (from guessit>=2.0.3->flexget)
Requirement already up-to-date: futures in /usr/local/lib/python2.7/dist-packages (from apscheduler->flexget)
Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from apscheduler->flexget)
Requirement already up-to-date: tzlocal in /usr/local/lib/python2.7/dist-packages (from apscheduler->flexget)
Requirement already up-to-date: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from flask>=0.7->flexget)
Requirement already up-to-date: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from flask>=0.7->flexget)
Requirement already up-to-date: aniso8601>=0.82 in /usr/local/lib/python2.7/dist-packages (from flask-restful>=0.3.3->flexget)
Installing collected packages: setuptools
  Found existing installation: setuptools 20.1
    Uninstalling setuptools-20.1:
      Successfully uninstalled setuptools-20.1
Successfully installed setuptools-20.2.1
grantland@ubuntu:~$ flexget --version
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2912, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2898, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 838, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2462, in requires
    dm = self._dep_map
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2457, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2762, in parse_requirements
    req = packaging.requirements.Requirement(line)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'!=0.9.0,'"
grantland@ubuntu:~$ setuptools --version
setuptools: command not found
grantland@ubuntu:~$ sudo pip install setuptools==20.1
The directory '/home/grantland/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/grantland/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting setuptools==20.1
  Downloading setuptools-20.1-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 475kB 539kB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 20.2.1
    Uninstalling setuptools-20.2.1:
      Successfully uninstalled setuptools-20.2.1
Successfully installed setuptools-20.1
grantland@ubuntu:~$ flexget --version
1.2.459
You are on the latest release.
```

**Comment by liiight** [comment]
This should be resolved since that version of setuptools has been pulled: https://github.com/basho/riak-python-client/issues/439.

I'm closing this as this shouldn't happen anymore. If it does, downgrade setuptools and wait for a new fixed release.
