### ISSUE TITLE
Unhandled error in plugin email: Template not found: html.template (email)

### ISSUE THREAD

**Issue by mathieumart1** [Flexget/Flexget#902]
Got this error since a couple of days (see crash report below), flexget is up to date : v 1.2.465
CRITICAL task          download-series BUG: Unhandled error in plugin email: Template not found: html.template (email)

Email plugin config below:
```
    email:
      from: xxx@gmail.com
      to: 
        - xxx@gmail.com 
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: xxx@gmail.com
      smtp_password: xxx 
      smtp_tls: yes
      template: html
```
Crash report :
```
2016-03-01 08:31 DEBUG    manager                       Figuring out config load paths
2016-03-01 08:31 DEBUG    manager                       Adding virtualenv path
2016-03-01 08:31 DEBUG    manager                       Found config: /home/mm/.flexget/config.yml
2016-03-01 08:31 DEBUG    manager                       Config file /home/mm/.flexget/config.yml selected
2016-03-01 08:31 INFO     scheduler                     Starting scheduler
2016-03-01 08:31 INFO     webui                         Not starting webui as it's disabled or not set in the config
2016-03-01 08:31 VERBOSE  check                         Checking config file `/home/mm/.flexget/config.yml`
2016-03-01 08:31 WARNING  check                         Config line 317 is likely missing ':' at the end
2016-03-01 08:31 WARNING  check                         Config line 320 is likely missing ':' at the end
2016-03-01 08:31 VERBOSE  check                         Pre-checked 326 configuration lines
2016-03-01 08:31 VERBOSE  check                         Config passed check.
2016-03-01 08:31 VERBOSE  emit_series   download-series Series `twin peaks` has no history. Set begin option, or use CLI `series begin` subcommand to set first episode to emit
2016-03-01 08:31 VERBOSE  discover      download-series Discovering 9 titles ...
2016-03-01 08:31 INFO     task          download-series Plugin discover has requested task to be ran again after execution has completed.
2016-03-01 08:31 VERBOSE  discover      download-series Discover interval of 5 hours not met for 7 entries. Use --discover-now to override.
2016-03-01 08:31 VERBOSE  discover      download-series Searching for `the walking dead S00E148` with plugin `kat` (1 of 1)
2016-03-01 08:31 VERBOSE  discover      download-series Searching for `the walking dead S00E148` with plugin `t411` (1 of 1)
2016-03-01 08:31 ERROR    discover      download-series Error searching with t411: No JSON object could be decoded
2016-03-01 08:31 VERBOSE  discover      download-series No search results for `the walking dead S00E148`
2016-03-01 08:31 VERBOSE  details       download-series Task didn't produce any entries.
2016-03-01 08:31 VERBOSE  details       download-series Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)
2016-03-01 08:31 CRITICAL task          download-series BUG: Unhandled error in plugin email: Template not found: html.template (email)
Traceback (most recent call last):
  File "/home/mm/virtualenv/flexget/lib/python2.7/site-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/home/mm/virtualenv/flexget/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/mm/virtualenv/flexget/lib/python2.7/site-packages/flexget/plugins/output/send_email.py", line 259, in on_task_output
    content = render_from_task(get_template(config['template'], 'email'), task)
  File "/home/mm/virtualenv/flexget/lib/python2.7/site-packages/flexget/utils/template.py", line 174, in get_template
    raise ValueError('Template not found: %s (%s)' % (templatename, pluginname))
ValueError: Template not found: html.template (email)
```

**Comment by stevezau** [comment]
duplicate #901
