### ISSUE TITLE
Unable to upgrade flexget to 1.2.467 with pip

### ISSUE THREAD

**Issue by xathin** [Flexget/Flexget#909]
When trying to upgrade to flexget 1.2.467, the following error occurs. This does not happen with 1.2.466 and everything installs correctly (sudo -H pip install --upgrade -I flexget==1.2.466 causes no errors and installs normally).

```
$ sudo -H pip install --upgrade flexget
Collecting flexget
  Downloading FlexGet-1.2.467.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vF2DUv/flexget/setup.py", line 39, in <module>
        install_requires=load_requirements('requirements.txt'),
      File "/tmp/pip-build-vF2DUv/flexget/setup.py", line 20, in load_requirements
        with io.open(filename, encoding='utf-8') as reqfile:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vF2DUv/flexget
```

**Comment by stevezau** [comment]
Pushed a commit to fix this, give me 10mins before u try again

**Comment by stevezau** [comment]
fixed
