### ISSUE TITLE
Cannot clean database

### ISSUE THREAD

**Issue by mlinfoot** [Flexget/Flexget#917]
Flexget version 1.2.469

`flexget database clean` fails with an error:
```
OperationalError: (pysqlite2.dbapi2.OperationalError) cannot VACUUM from within a transaction [SQL: u'VACUUM']
```

This error is preventing the flexget daemon from executing any tasks because it attempts a database cleanup first and crashes. This is an excerpt from the crash log:
```
2016-03-03 11:46 INFO     manager       rarbg           Running database cleanup.
2016-03-03 11:46 INFO     db_vacuum     rarbg           Running VACUUM on database to improve performance and decrease db size.
2016-03-03 11:46 CRITICAL task_queue                    Database error while running a task. Attempting to recover.
2016-03-03 11:46 CRITICAL manager                       An unexpected crash has occurred. Writing crash report to ...
```

Here is the full trace from running `flexget database clean`
```
2016-03-03 13:49 INFO     manager                       Running database cleanup.
2016-03-03 13:49 INFO     db_vacuum                     Running VACUUM on database to improve performance and decrease db size.
Traceback (most recent call last):
  File "/home/marshal/.local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/manager.py", line 283, in start
    client.handle_cli(self.args)
  File "/home/marshal/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/marshal/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/home/marshal/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
rpyc.core.vinegar/sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) cannot VACUUM from within a transaction

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/marshal/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/marshal/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/ipc.py", line 75, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/manager.py", line 327, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/plugins/cli/database.py", line 13, in do_cli
    cleanup(manager)
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/plugins/cli/database.py", line 23, in cleanup
    manager.db_cleanup(force=True)
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/manager.py", line 835, in db_cleanup
    fire_event('manager.db_cleanup', self, session)
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/event.py", line 103, in fire_event
    result = event(*args, **kwargs)
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/marshal/.local/lib/python2.7/site-packages/flexget/plugins/generic/db_vacuum.py", line 19, in on_cleanup
    session.execute('VACUUM')
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1034, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/marshal/.local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) cannot VACUUM from within a transaction [SQL: u'VACUUM']
```

**Comment by magicknot** [comment]
Same here, with version 1.2.436

**Comment by mlinfoot** [comment]
Problem still there in the latest version, 1.2.473.

**Comment by liiight** [comment]
I cannot reproduce it. Please paste full log and config

**Comment by mlinfoot** [comment]
Here's the output from running a config check:
````
home[~] > flexget check
There is a FlexGet process already running for this config, sending execution there.
2016-03-07 09:55 VERBOSE  check                         Checking config file `/home/marshal/.flexget/config.yml`
2016-03-07 09:55 WARNING  check                         Config line 3 is likely missing ':' at the end
2016-03-07 09:55 VERBOSE  check                         Pre-checked 85 configuration lines
2016-03-07 09:55 VERBOSE  check                         Config passed check.
````
And my config file with the tv show names removed:
````
home[~] > cat .flexget/config.yml
schedules:
  # Run every task once every 30 minutes
  - tasks: '*'
    interval:
      minutes: 30

templates:
  transmissionrpc:
    transmission:
      path: /home/marshal/Desktop/TV/{{series_name}} - Season {{series_season}}
      addpaused: No
    clean_transmission:
      finished_for: 10 minutes
      min_ratio: 1
  tv-shows:
    series:
      settings:
        track:
          tracking: no
      track:
        - <tv show names>
tasks:
  eztv:
    rss: 
      url: https://eztv.ag/ezrss.xml
      link:
        - magneturi
        - link
    template:
      - transmissionrpc
      - tv-shows
    priority: 10

  showrss:
    rss: 
      url: http://showrss.info/feeds/all.rss
      link:
        - magneturi
        - link
    template:
      - transmissionrpc
      - tv-shows
    priority: 10
    regexp:
      reject: 
        - 720p
        
  rarbg:
    rss: 
      url: http://rarbg.com/rssdd.php?category=18
      link:
        - magneturi
        - link
    template:
      - transmissionrpc
      - tv-shows
    priority: 10
````

The trace of what happens when I try to run `flexget database clean` is in my post above. What log file(s) do you want to see?

I wouldn't care if this is fixed or not if there was a way to prevent the daemon from trying to run the database clean every time.

**Comment by mlinfoot** [comment]
Workaround so the daemon won't crash on db cleanup:

Comment out line 838 in manager.py
`     #    fire_event('manager.db_cleanup', self, session) `

**Comment by liiight** [comment]
what happens if you stop your daemon and then execute commands?

**Comment by mlinfoot** [comment]
Same result with daemon stopped or daemon running.

**Comment by Cromigon** [comment]
@mlinfoot I had the exact same problem after an upgrade.

What I did was that I uninstalled flexget and it's dependencies (_was running it inside of an virtualenv so I just removed it_) and then installed it again (_created a new virtualenv, installed flexget and ran it_).

Both `flexget database check` and `flexget database vacuum` worked both when I was running a daemon and outside afterwards.

So try to uninstall it completely and then install it again. (Make sure that you back up your database, config etc.) and then see if an reinstall helps.

**Comment by magicknot** [comment]
My problem was due to having /var full.

**Comment by mlinfoot** [comment]
Don't know what caused the problem on my system, but installed fresh on a new laptop, copied config and database from the old system, and everything is working fine. I'm going to close this since it doesn't seem to be anything internal to flexget.
