### ISSUE TITLE
Issues with SQLite and TMDB plugin, crashes 1.2.477

### ISSUE THREAD

**Issue by Perrylicious** [Flexget/Flexget#933]
Greetings,

on Ubuntu (fully updated) with Python 2.7.6 and latest flexget (1.2.477) getting a crash from lazylookup when TMDB info is pulled, mostly related to TMDB colums missing.

Examples: 

2016-03-09 06:24 ERROR    lazy_lookup   taskname     Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/tmdb_lookup.py", line 62, in lazy_loader
    session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tmdb.py", line 250, in lookup
    movie = session.merge(movie)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1709, in merge
    load=load, _recursive=_recursive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1805, in _merge
    load, _recursive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py", line 1459, in merge
    dest_state.get_impl(self.key).get(dest_state, dest_dict)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 583, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 532, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 602, in _emit_lazyload
    result = q.all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2588, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such column: tmdb_posters.id [SQL: u'SELECT tmdb_posters.id AS tmdb_posters_id, tmdb_posters.movie_id AS tmdb_posters_movie_id, tmdb_posters.file_path AS tmdb_posters_file_path, tmdb_posters.width AS tmdb_posters_width, tmdb_posters.height AS tmdb_posters_height, (...) tmdb_posters.vote_count AS tmdb_posters_vote_count, tmdb_posters.iso_639_1 AS tmdb_posters_iso_639_1 \nFROM tmdb_posters \nWHERE ? = tmdb_posters.movie_id'] [parameters: (75629,)]

or (last line only)

IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: tmdb_search_results.search [SQL: u'INSERT INTO tmdb_search_results (search, movie_id) VALUES (?, ?)'] [parameters: (u'Hapax Legomena III Critical Mass (1971)', 151002)]

Was asked on the forum to raise an issue to see if this is just local.

**Comment by stevezau** [comment]
@gazpachoking could this be related to the recent changes?

**Comment by Perrylicious** [comment]
Here's a grab bag of crash reports from earlier today if that helps any since I don't seem to get formatting right.
https://dl.dropboxusercontent.com/u/40616/crashreports.zip

**Comment by liiight** [comment]
Fixed with https://github.com/Flexget/Flexget/commit/d103d3f896f65504fd437f3f179a845eae04c413
