### ISSUE TITLE
Integrity errors on 1.2.477 with TMDB plugin even after resetting DB

### ISSUE THREAD

**Issue by Perrylicious** [Flexget/Flexget#940]
Hi,
please cf my previous ticket for more info. Issue happens after task is run once against empty db on every subsequent execution of task

2016-03-09 19:49 DEBUG    manager                       Figuring out config load paths
2016-03-09 19:49 DEBUG    manager                       Found config: /home/perry/.flexget/config.yml
2016-03-09 19:49 DEBUG    manager                       Config file /home/perry/.flexget/config.yml selected
2016-03-09 19:49 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have co$
2016-03-09 19:49 VERBOSE  details       mov_sd_dog      Produced 100 entries.
2016-03-09 19:49 VERBOSE  imdb_lookup   mov_sd_dog      Imdb lookup failed for magellan.at.the.gates.of.death.part.i.the.red.g$
2016-03-09 19:49 ERROR    lazy_lookup   mov_sd_dog      Unhandled error in lazy lookup plugin
2016-03-09 19:49 CRITICAL manager       mov_sd_dog      An unexpected crash has occurred. Writing crash report to /home/perry/$
2016-03-09 19:49 WARNING  movie_queue   mov_sd_dog      IMDB and TMDB lookups failed for Magellan.At.the.Gates.of.Death.Part.I$
2016-03-09 19:49 VERBOSE  imdb_lookup   mov_sd_dog      Imdb lookup failed for the.birth.of.magellan.cadenza.i.1977.bdrip.x264$
2016-03-09 19:49 ERROR    lazy_lookup   mov_sd_dog      Unhandled error in lazy lookup plugin
2016-03-09 19:49 CRITICAL manager       mov_sd_dog      An unexpected crash has occurred. Writing crash report to /home/perry/$
2016-03-09 19:49 WARNING  movie_queue   mov_sd_dog      IMDB and TMDB lookups failed for The.Birth.of.Magellan.Cadenza.I.1977.$
2016-03-09 19:49 VERBOSE  imdb_lookup   mov_sd_dog      Imdb lookup failed for hapax.legomena.ii.poetic.justice.1972.bdrip.x26$
2016-03-09 19:50 ERROR    lazy_lookup   mov_sd_dog      Unhandled error in lazy lookup plugin
2016-03-09 19:50 CRITICAL manager       mov_sd_dog      An unexpected crash has occurred. Writing crash report to /home/perry/$
2016-03-09 19:50 WARNING  movie_queue   mov_sd_dog      IMDB and TMDB lookups failed for Hapax.Legomena.II.Poetic.Justice.1972$
2016-03-09 19:50 VERBOSE  imdb_lookup   mov_sd_dog      Imdb lookup failed for hapax.legomena.iii.critical.mass.1971.bdrip.x26$
2016-03-09 19:50 ERROR    lazy_lookup   mov_sd_dog      Unhandled error in lazy lookup plugin
2016-03-09 19:50 CRITICAL manager       mov_sd_dog      An unexpected crash has occurred. Writing crash report to /home/perry/$
2016-03-09 19:50 WARNING  movie_queue   mov_sd_dog      IMDB and TMDB lookups failed for Hapax.Legomena.III.Critical.Mass.1971$
2016-03-09 19:50 VERBOSE  imdb_lookup   mov_sd_dog      Imdb lookup failed for hapax.legomena.i.nostalgia.1971.bdrip.x264-vomit
2016-03-09 19:50 ERROR    lazy_lookup   mov_sd_dog      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/tmdb_lookup.py", line 62, in lazy_loader
    session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tmdb.py", line 250, in lookup
    movie = session.merge(movie)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1700, in merge
    self._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: tmdb_search_results.search [SQL: u'INSERT INTO tmdb_search_results (search, movie_id) VALUES (?, ?)'] [parameters: (u'Hapax Legomena I Nostalgia (1971)', 132161)]

**Comment by cmtec** [comment]
I'm having the same problem

**Comment by liiight** [comment]
Please check in dev or wait for next release and report if it works.

**Comment by Perrylicious** [comment]
Manually committed diff above and first tasks after restart have no crash incidents against fully restored db. Will report back after overnight testing. Thank you for your help!

**Comment by gazpachoking** [comment]
Thanks for reporting and testing!
