### ISSUE TITLE
BUG: Unhandled error in plugin discover: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#941]
```
fmf@kodi:~$ python -V
Python 2.7.6
fmf@kodi:~$
fmf@kodi:~$ flexget -V
1.2.478
You are on the latest release.
```

Got this in my log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 275, in on_task_input
    return self.execute_searches(config, entries, task)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/discover.py", line 146, in execute_searches
    search_results = search.search(entry, plugin_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/search_rss.py", line 24, in search
    for s in entry.get('search_strings', [entry['title']])]
AttributeError: 'unicode' object has no attribute 'get'

```

**Comment by cvium** [comment]
Config?

**Comment by effemmeffe** [comment]
Sorry, forgot that: https://github.com/effemmeffe/flexget/blob/master/config.yml

**Comment by cvium** [comment]
eh, which task fails and do you have any logs? The traceback doesn't say much.

**Comment by effemmeffe** [comment]
I cleaned the log fiule and did a fresh run and that issued 23 crash logs!
I'll enclose all the logs to this message, I hope it's ok.
[crash.zip](https://github.com/Flexget/Flexget/files/167418/crash.zip)

**Comment by cvium** [comment]
What is the output of `flexget movie-queue list` and `flexget series list`?

**Comment by effemmeffe** [comment]
movie-queue:
```
-------------------------------------------------------------------------------
IMDB id    TMDB id Title                                 Quality
-------------------------------------------------------------------------------
tt2354851  214253  World's End                           any
tt0462335  254302  High-Rise                             any
tt0801526  16725   The Tracey Fragments                  any
tt1355683  261023  Black Mass                            any
tt1546653  52249   The Red Chapel                        any
tt3612616  265177  Mommy                                 any
tt3691740  267935  The BFG                               any
tt3235888  270303  It Follows                            any
tt3108158  251981  The World of Kanako                   any
tt4537842  364067  A Very Murray Christmas               any
tt4034354  347031  Swiss Army Man                        any
tt0359715  10614   My Best Friend's Birthday             any
tt0075987  28325   Emmanuelle Around the World           any
tt0435224  142689  Changing Destiny                      any
tt3029626  231020  My Class                              any
tt3890914  286306  Senza nessuna pietà                   any
tt3520564  290695  Melbourne                             any
tt2852432  186975  Norte, the End of History             any
tt2304933  299687  The 5th Wave                          any
tt3614802  271395  The Fantastic Four 2                  any
tt0109770  22059   The Fantastic Four                    any
tt3385516  246655  X-Men: Apocalypse                     any
tt3498820  271110  Captain America: Civil War            any
tt4154858  299538  Inhumans                              any
tt2316204  126889  Alien: Covenant                       any
tt4154796  299534  Avengers: Infinity War - Part II      any
tt4154756  299536  Avengers: Infinity War - Part I       any
tt0475290  270487  Hail, Caesar!                         any
tt2975590  209112  Batman v Superman: Dawn of Justice    any
tt0666194  261581  Louis C.K.: One Night Stand           any
tt1235425  55988   Glory at Sea                          any
tt1592281  86555   Take This Waltz                       any
tt1431045  293660  Deadpool                              any
tt3092552  226437  Life Feels Good                       any
tt4598606  335080  Ameluk                                any
tt3729594  316027  Gambit                                any
tt1211837  284052  Doctor Strange                        any
tt3896198  283995  Guardians of the Galaxy Vol. 2        any
tt3501632  284053  Thor Ragnarok                         any
tt1825683  284054  Black Panther                         any
tt4154664  299537  Captain Marvel                        any
tt1386697  297761  Suicide Squad                         any
tt0451279  297762  Wonder Woman                          any
tt3439676  241224  Wonder Woman                          any
tt0974015  141052  Justice League                        any
tt0439572  298618  The Flash                             any
tt1477834  297802  Aquaman                               any
tt0448115  287947  Shazam!                               any
tt4121026  298619  Justice League: Part 2                any
tt4123436  298622  Cyborg                                any
tt4120636  297797  Green Lantern                         any
tt3655522  266082  Girlhood                              any
tt0073869  46696   Private Vices, Public Virtues         any
tt2404435  333484  The Magnificent Seven                 any
tt1791682  252512  While We're Young                     any
tt0110395  15477   Love and a .45                        any
tt4500922  336843  Maze Runner: The Death Cure           any
tt1800351  287915  One Night in Istanbul                 any
tt2660888  188927  Star Trek Beyond                      any
None       91161   Cockasian                             any
tt1608290  329833  Zoolander 2                           any
tt3592542  328087  Javier Zanetti capitano da Buenos Aires any
tt3110958  291805  Now You See Me 2                      any
tt2446980  274479  Joy                                   any
tt2737050  221902  Two Days, One Night                   any
tt3775086  364433  Lo chiamavano Jeeg Robot              any
tt2948356  269149  Zootopia                              any
tt0478024  13127   Kill Zone - S.P.L.                    any
tt4009278  333674  Intruders                             any
tt3268458  250658  The Internet's Own Boy: The Story of Aaron Swartz any
tt3733774  301608  The Trust                             any
tt1612774  45649   Rubber                                any
-------------------------------------------------------------------------------

```

series:
```
-------------------------------------------------------------------------------
 Name                           Latest     Age        Downloaded          
-------------------------------------------------------------------------------
 11.22.63                       S01E04 +1  3d 6h      720p hdtv h264      
>American Crime                 S02E10     7h         720p hdtv h264      
 Animals                        S01E05     6d 7h      720p hdtv h264      
 Billions                       S01E07     12d 1h     720p hdtv h264      
 Black Mirror                   N/A        N/A        N/A                 
 Bloodline                      S01E13     41d 13h    720p webrip h264    
 Boris                          S03E14     42d 4h     xvid                
 Bosch                          S01E10     41d 13h    720p webrip h264-proper
 Boy Meets Girl                 N/A        N/A        N/A                 
 Chefs Table                    S01E06     42d 4h     720p                
 Code Black                     S01E18     14d 11h    720p hdtv h264      
 Colony                         S01E08     6d 11h     720p hdtv h264      
 Fargo                          S02E10     6d 7h      720p webdl h264 dd5.1
 Friday Night Lights            S05E13     42d 4h     unknown             
 Gomorrah                       N/A        N/A        N/A                 
 Greys Anatomy                  S12E12     6d 14h     720p hdtv h264      
 Hap and Leonard                S01E01 +2  7d 8h      720p webdl h264 dd5.1
>Happy Valley                   S02E05     7h         720p hdtv h264      
 House of Cards                 S04E13     5d 1h      720p webrip h264    
 House of Cards (US)            S04E13     4d 2h      720p webrip h264    
 Life in Pieces                 S01E19     6d 13h     720p hdtv h264      
 Louie                          N/A        N/A        N/A                 
 Luther                         S03E04 +1  42d 4h     1080p bluray h265 ac3
 Mad Dogs (US)                  S01E10 +1  42d 4h     720p hdtv h264      
 Making a Murderer              S01E10     42d 4h     720p webrip h265    
 Marvels Daredevil              S01E13     41d 2h     720p webrip h264    
 Marvels Jessica Jones          N/A        N/A        N/A                 
 Marvels Luke Cage              N/A        N/A        N/A                 
 Marvels The Defenders          N/A        N/A        N/A                 
 Murder                         N/A        N/A        N/A                 
 Narcos                         S01E10     31d 18h    720p webrip h264    
 Orange Is the New Black        S03E13     42d 4h     webrip h264         
 Orphan Black                   N/A        N/A        N/A                 
 Sense8                         S01E12     41d 2h     720p webrip h264    
 Shameless                      S06E08 +1  12d 1h     720p hdtv h264      
 Shameless (US)                 S06E08     17d 8h     720p hdtv h264      
 Sherlock                       N/A        N/A        N/A                 
 Sports Night                   S02E22     42d 4h     unknown             
 Suits                          S05E16 +1  7d 11h     720p hdtv h264      
 The Big Bang Theory            S09E17 +1  13d 14h    720p hdtv h264, 720p hdtv h264-proper
 The Circus: Inside the Grea... N/A        N/A        N/A                 
 The Code                       N/A        N/A        N/A                 
 The Get Down                   N/A        N/A        N/A                 
 The Good Wife                  S07E16     3d 12h     720p hdtv h264      
 The Night Manager              N/A        N/A        N/A                 
 The Walking Dead               S06E12 +1  3d 12h     720p hdtv h264      
 The West Wing                  S07E22     24d 14h    unknown             
 The Wire                       S05E10     42d 4h     unknown             
 Transparent                    S02E10     42d 4h     720p webrip h264    
 Vinyl                          S01E04     3d 12h     720p hdtv h264      
-------------------------------------------------------------------------------

```

**Comment by cvium** [comment]
I couldn't reproduce it organically... but I've found the problem nonetheless.
