### ISSUE TITLE
TMDB error back (not critical), isolated and in a new exciting variety ("New instance conflicts with persistent instance")

### ISSUE THREAD

**Issue by Perrylicious** [Flexget/Flexget#950]
If I could just disable TMDB lookups I would, but apparently setting either "disable: tmdb_lookup" or setting "tmdb_lookup: no", or both at the same time, even in the same template, still calls TMDB lookups. This is nothing compared to the previous errors that crashed multiple times per task, this just fails once per hour on a specific task and might even be local. Just thought I'd report it for posterity. Have not tested against empty DB yet but tested with latest (1.2.481).

```
2016-03-14 22:00 CRITICAL manager       task_name      An unexpected crash has occurred. Writing crash report to /home/perry/.flexget/crash_report.2016.03.14.220054373493.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.481
2016-03-14 22:00 ERROR    lazy_lookup   task_name      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/tmdb_lookup.py", line 62, in lazy_loader
    session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tmdb.py", line 217, in lookup
    movie.update_from_tmdb()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tmdb.py", line 110, in update_from_tmdb
    self.posters = [TMDBPoster(**p) for p in movie['images']['posters'][:5]]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1027, in set
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1047, in _set_iterable
    old = self.get(state, dict_, passive=PASSIVE_ONLY_PERSISTENT)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 583, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 532, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 602, in _emit_lazyload
    result = q.all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2588, in all
    return list(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2735, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 149, in save_obj
    base_mapper, states, uowtransaction
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 301, in _organize_states_for_save
    state_str(existing)))
FlushError: New instance <TMDBGenre at 0x7f676b010e90> with identity key (<class 'flexget.plugins.api_tmdb.TMDBGenre'>, (18,)) conflicts with persistent instance <TMDBGenre at 0x7f676b000e10>
```

**Comment by liiight** [comment]
looks like something to do with how `session.merge` is done: http://docs.sqlalchemy.org/en/latest/orm/session_state_management.html#merge-tips

**Comment by gazpachoking** [comment]
I'm fairly confident I understood and fixed the problem. Somebody re-open if not.
