### ISSUE TITLE
Cache time expired exception from configure_series plugin

### ISSUE THREAD

**Issue by bbeck** [Flexget/Flexget#951]
Hello,

I'm running Flexget 1.2.481 and received the following crash report:
```
2016-03-14 23:19 CRITICAL task         <task name>         BUG: Unhandled error in plugin configure_series: (u'trakt_list_77ef1f69b4d443524da29986991b3510', u'cache time expired')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_configure_series.py", line 69, in on_task_start
    result = method(task, input_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 115, in wrapped_func
    for entry in self.cache[cache_name]:
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/tools.py", line 428, in __getitem__
    self._last_prune = datetime.now()
KeyError: (u'trakt_list_77ef1f69b4d443524da29986991b3510', u'cache time expired')
```

Here's what I believe to be the relevant portion of my config file:

```yaml
templates:
  tv:
    # Discover which TV series should be downloaded from trakt.tv.
    configure_series:
      settings:
        quality: "720p+ hdtv+"
        identified_by: "ep"
        propers: no

      from:
        trakt_list:
          username: "{{ secrets.trakt.username }}"
          account: "{{ secrets.trakt.username }}"
          list: "{{ secrets.trakt.list }}"
          type: "shows"

          # Don't include the year at the end of series names.
          strip_dates: yes
```

**Comment by bbeck** [comment]
After deeper investigation it appears that this happens due to a race condition inside of the `cached` decorator.  On line [111](https://github.com/Flexget/Flexget/blob/develop/flexget/utils/cached_input.py#L111) it does a `cache_name in self.cache` call, but on line [115](https://github.com/Flexget/Flexget/blob/develop/flexget/utils/cached_input.py#L115) it does a `self.cache[cache_name]` lookup.  There's a small chance, that between those two calls, the entry in the cache expires and the `cache_name in self.cache` call returns true, but the `self.cache[cache_name]` call throws an exception.  That appears to be the situation that I ran into.

To fix this, I made the interaction with the cache atomic.  Instead of checking if the item exists in the cache and then later looking it up, I made the code instead look up the item, remember it, and then check to see if it was found.  If it was then it gets used, if it wasn't then move on.  This should eliminate the race condition and the possibility of that particular bug coming back again.
