### ISSUE TITLE
TypeError: can't compare datetime.datetime to unicode

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#955]
Hello,

I got this after upgrading to v1.2.487.

```
2016-03-16 13:03 CRITICAL manager                       An unexpected crash has occurred. Writing crash report to /home/osmc/.flexget/crash_report.2016.03.16.130329038603.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.487
2016-03-16 13:03 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 69, in wrapper
    return func(self, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 576, in execute
    self.manager.db_cleanup()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 833, in db_cleanup
    expired = self.persist.get('last_cleanup', datetime(1900, 1, 1)) < datetime.now() - DB_CLEANUP_INTERVAL
TypeError: can't compare datetime.datetime to unicode
```

Please fix this, thanks!

**Comment by Mirgolth** [comment]
Is present since v1.2.484 for me.

**Comment by antivirtel** [comment]
Yeah, a triage is to downgrade to 1.2.483.

Bortnyák Roland

**Comment by liiight** [comment]
It won't work, since this was caused by a DB upgrade. Hang tight, a fix will probably come soon enough

**Comment by antivirtel** [comment]
You may right, but I didn't get that crash after the downgrade, maybe that part of the code wasn't run yet...

**Comment by stevezau** [comment]
please try again
