### ISSUE TITLE
TypeError: can't compare datetime.datetime to unicode

### ISSUE THREAD

**Issue by dj-nitehawk** [Flexget/Flexget#956]
on the latest version `1.2.487`  

    djnitehawk@v:~$ flexget database cleanup
    2016-03-16 08:23 WARNING  manager Your locale declares ascii as the filesystem encoding. Any plugins reading filenames from disk will not work properly for filenames containing non-ascii characters. Make sure your locale env variables are set up correctly for the environment which is launching FlexGet.
    There is a FlexGet process already running for this config, sending execution there.
    Traceback (most recent call last):
      File "/usr/local/bin/flexget", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
        manager.start()
      File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 286, in start
        client.handle_cli(self.args)
      File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
        return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
      File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
        return conn.sync_request(handler, oid, *args)
      File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
        raise obj
    TypeError: can't compare datetime.datetime to unicode

    ========= Remote Traceback (1) =========
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
        res = self._HANDLERS[handler](self, *args)
      File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
        return self._local_objects[oid](*args, **dict(kwargs))
      File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 79, in exposed_handle_cli
        self.manager.handle_cli(options)
      File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 330, in handle_cli
        options.cli_command_callback(self, command_options)
      File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/database.py", line 13, in do_cli
        cleanup(manager)
      File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/cli/database.py", line 23, in cleanup
        manager.db_cleanup(force=True)
      File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 833, in db_cleanup
        expired = self.persist.get('last_cleanup', datetime(1900, 1, 1)) < datetime.now() - DB_CLEANUP_INTERVAL
    TypeError: can't compare datetime.datetime to unicode

similar errors are logged in daemon crash logs:

    2016-03-16 08:28 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/flexget/task_queue.py", line 47, in run
        self.current_task.execute()
      File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 69, in wrapper
        return func(self, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 576, in execute
        self.manager.db_cleanup()
      File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 833, in db_cleanup
        expired = self.persist.get('last_cleanup', datetime(1900, 1, 1)) < datetime.now() - DB_CLEANUP_INTERVAL
    TypeError: can't compare datetime.datetime to unicode

**Comment by liiight** [comment]
Duplicate #955
