### ISSUE TITLE
decoder.py: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#959]
Hi, 

I got this after upgrading to 1.2.491, then. checking config & starting flexget daemon:
```
2016-03-18 09:03 WARNING  check                         Config line 4 is likely missing ':' at the end
2016-03-18 09:03 WARNING  check                         Config line 10 is likely missing ':' at the end
2016-03-18 09:03 VERBOSE  check                         Pre-checked 401 configuration lines
Could not start manager: No JSON object could be decoded
2016-03-18 09:03 ERROR    main                          No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 302, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 202, in initialize
    fire_event('manager.startup', self)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 103, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/simple_persistence.py", line 172, in load_taskless
    SimplePersistence.load()
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/simple_persistence.py", line 135, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 138, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/json.py", line 105, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/json.py", line 41, in decode
    return super(DTDecoder, self).decode(obj, **kwargs)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Isn't #955 related? Or its commit: 9bf8668?

**Comment by stevezau** [comment]
please paste full debug log

**Comment by antivirtel** [comment]
The command I ran after stopping flexget:
```
sudo pip install -U flexget && flexget -L debug check && flexget -L debug daemon start
```
The output:
```
[...]
Installing collected packages: flexget
  Found existing installation: FlexGet 1.2.483
    Uninstalling FlexGet-1.2.483:
      Successfully uninstalled FlexGet-1.2.483
Successfully installed flexget-1.2.491
2016-03-18 11:02 DEBUG    manager                       Figuring out config load paths
2016-03-18 11:02 DEBUG    manager                       Found config: /home/osmc/.flexget/config.yml
2016-03-18 11:02 DEBUG    manager                       Config file /home/osmc/.flexget/config.yml selected
2016-03-18 11:02 DEBUG    manager                       sys.defaultencoding: ascii
2016-03-18 11:02 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-03-18 11:02 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-03-18 11:02 DEBUG    plugin                        Trying to load plugins from: [u'/home/osmc/.flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2016-03-18 11:02 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-03-18 11:02 DEBUG    plugin                        Plugin `memusage` requires `ext lib `guppy`` to load.
2016-03-18 11:02 DEBUG    plugin                        Plugins took 22.78 seconds to load
2016-03-18 11:02 DEBUG    manager                       Connecting to: sqlite:////home/osmc/.flexget/db-config.sqlite
2016-03-18 11:02 WARNING  check                         Config line 4 is likely missing ':' at the end
2016-03-18 11:02 WARNING  check                         Config line 10 is likely missing ':' at the end
2016-03-18 11:02 VERBOSE  check                         Pre-checked 401 configuration lines
2016-03-18 11:02 DEBUG    manager                       config_name: config
2016-03-18 11:02 DEBUG    manager                       config_base: /home/osmc/.flexget
2016-03-18 11:02 DEBUG    manager                       New config data loaded.
2016-03-18 11:03 DEBUG    manager                       Removed /home/osmc/.flexget/.config-lock
Could not start manager: No JSON object could be decoded
2016-03-18 11:03 ERROR    main                          No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 302, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 202, in initialize
    fire_event('manager.startup', self)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 103, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/simple_persistence.py", line 172, in load_taskless
    SimplePersistence.load()
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/simple_persistence.py", line 135, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 138, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/json.py", line 105, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/json.py", line 41, in decode
    return super(DTDecoder, self).decode(obj, **kwargs)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by stevezau** [comment]
This is due to an older version of requests..

I've updated in dev, new release will go out today.

**Comment by stevezau** [comment]
Ignore that, it's not fixed yet

**Comment by stevezau** [comment]
@antivirtel I think this was due to the database failing to upgrade properly or in the middle of broken flexget versions.

Can you run the below and try again

```
 flexget database reset-plugin simple_persistence
```

**Comment by antivirtel** [comment]
I'm getting the same traceback with the latest version (1.2.493):

`$ flexget -L debug database reset-plugin simple_persistence`
```
2016-03-22 07:38 DEBUG    manager                       Figuring out config load paths
2016-03-22 07:38 DEBUG    manager                       Found config: /home/osmc/.flexget/config.yml
2016-03-22 07:38 DEBUG    manager                       Config file /home/osmc/.flexget/config.yml selected
2016-03-22 07:38 DEBUG    manager                       sys.defaultencoding: ascii
2016-03-22 07:38 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-03-22 07:38 DEBUG    manager                       os.path.supports_unicode_filenames: False
2016-03-22 07:38 DEBUG    plugin                        Trying to load plugins from: [u'/home/osmc/.flexget/plugins', '/usr/local/lib/python2.7/dist-packages/flexget/plugins']
2016-03-22 07:38 DEBUG    safe                          Reading from cache file /tmp/safe-0.4.words.cache
2016-03-22 07:38 DEBUG    plugin                        Plugin `memusage` requires `ext lib `guppy`` to load.
2016-03-22 07:38 DEBUG    plugin                        Plugins took 22.38 seconds to load
2016-03-22 07:39 DEBUG    manager                       Connecting to: sqlite:////home/osmc/.flexget/db-config.sqlite
2016-03-22 07:39 DEBUG    manager                       config_name: config
2016-03-22 07:39 DEBUG    manager                       config_base: /home/osmc/.flexget
2016-03-22 07:39 DEBUG    manager                       New config data loaded.
2016-03-22 07:39 DEBUG    manager                       Removed /home/osmc/.flexget/.config-lock
Could not start manager: No JSON object could be decoded
2016-03-22 07:39 ERROR    main                          No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 302, in start
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 202, in initialize
    fire_event('manager.startup', self)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 103, in fire_event
    result = event(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/simple_persistence.py", line 172, in load_taskless
    SimplePersistence.load()
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/simple_persistence.py", line 135, in load
    cls.class_store[task][skv.plugin][skv.key] = skv.value
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 293, in __get__
    return self.descriptor.__get__(instance, owner)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 138, in getter
    return json.loads(getattr(self, name), decode_datetime=True)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/json.py", line 105, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/json.py", line 41, in decode
    return super(DTDecoder, self).decode(obj, **kwargs)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

After I've rolled back to 1.2.483 (the last working version I could run), I was able to run that command:
`$ flexget -L debug database reset-plugin simple_persistence`
```
2016-03-22 07:50 DEBUG    manager                       Figuring out config load paths
2016-03-22 07:50 DEBUG    manager                       Found config: /home/osmc/.flexget/config.yml
2016-03-22 07:50 DEBUG    manager                       Config file /home/osmc/.flexget/config.yml selected
2016-03-22 07:50 DEBUG    manager                       sys.defaultencoding: ascii
2016-03-22 07:50 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2016-03-22 07:50 DEBUG    manager                       os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2016-03-22 07:50 DEBUG    manager                       Sending command to running FlexGet process: [u'-L', u'debug', u'database', u'reset-plugin', u'simple_persistence']
2016-03-22 07:51 DEBUG    schema                        Initializing plugin simple_persistence schema version to 2
The database for `simple_persistence` has been reset.
```

After it, I was upgraded to the latest version, and now it seems to be working. Was that only a database issue? Couldn't it be prevented by catching that exception? Thanks!

**Comment by liiight** [comment]
That exception was due to a previous issue.
