### ISSUE TITLE
Unhandled error in lazy lookup plugin.

### ISSUE THREAD

**Issue by shotfirer** [Flexget/Flexget#961]
Since update from 1.2.481 to 1.2.489 i'm getting this kind of error with every tvdb lookup. Update to 1.2.491 didn't fix the problem.
```
2016-03-18 19:29 ERROR    lazy_lookup   KICKASS         Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/plugins/metainfo/thetvdb_lookup.py", line 109, in lazy_series_lookup
    return self.series_lookup(entry, self.series_map)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/plugins/metainfo/thetvdb_lookup.py", line 102, in series_lookup
    tvdb_id=entry.get('tvdb_id', eval_lazy=False), session=session)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/plugins/api_tvdb.py", line 407, in lookup_series
    series.update(session)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/plugins/api_tvdb.py", line 153, in update
    series = TVDBRequest().get('series/%s' % self.id)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/plugins/api_tvdb.py", line 72, in get
    result = self._request('get', endpoint, **params)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/plugins/api_tvdb.py", line 55, in _request
    headers = {'Authorization': 'Bearer %s' % self.get_auth_token()}
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/plugins/api_tvdb.py", line 49, in get_auth_token
    tokens[self.auth_key] = requests.post(TVDBRequest.BASE_URL + 'login', json=data).json().get('token')
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/utils/requests.py", line 277, in post
    return request('post', url, data=data, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/utils/requests.py", line 247, in request
    return s.request(method=method, url=url, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/FlexGet-1.2.491-py2.7.egg/flexget/utils/requests.py", line 232, in request
    result = requests.Session.request(self, method, url, *args, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by stevezau** [comment]
This is because your requests version is too old.

I've just fixed this, new release will go out today sometime.
