### ISSUE TITLE
Tvdb lookup when no posters are present

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#968]
```
2016-03-21 23:31 ERROR    flexget.api                   Exception on /tvdb/series/Sex House/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api/tvdb_lookup.py", line 90, in get
    return jsonify(result.to_dict())
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 242, in to_dict
    'overview': self.overview,
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 200, in posters
    return self.get_actors()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 220, in get_posters
    try:
LookupError: Error updating posters from tvdb: 404 Client Error: Not Found for url: https://api-beta.thetvdb.com/series/260844/images/query?keyType=poster
```

This issue occurs when a series does not have any posters on tvdb. This return a 404 error, instead of an empty array. Bad implementation on tvdb side, but anyways, we probably can catch that error, making it so that other metadata for the show is returned.

**Comment by liiight** [comment]
Also happens to me with actors:
```
2016-03-23 11:13 ERROR    flexget.api                   Exception on /tvdb/series/The Blacklist/ [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\flask_restful\__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "c:\python27\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "c:\python27\lib\site-packages\flask_restplus\resource.py", line 42, in dispatch_request
    resp = meth(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\utils\database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\api\tvdb_lookup.py", line 90, in get
    return jsonify(result.to_dict())
  File "c:\python27\lib\site-packages\flexget\plugins\api_tvdb.py", line 248, in to_dict
    'actors': self.actors,
  File "c:\python27\lib\site-packages\flexget\plugins\api_tvdb.py", line 200, in actors
    return self.get_actors()
  File "c:\python27\lib\site-packages\flexget\plugins\api_tvdb.py", line 213, in get_actors
    raise LookupError('Error updating actors from tvdb: %s' % e)
LookupError: Error updating actors from tvdb: 404 Client Error: Not Found for url: https://api-beta.thetvdb.com/series/266189/actors
```
I think it's probably a timeout issue
