### ISSUE TITLE
APScheduler exception causes flexget to no longer run in daemon mode

### ISSUE THREAD

**Issue by xathin** [Flexget/Flexget#976]
I'm not entirely sure if this is an issue for flexget, or if it's something that the APScheduler program should address, but I have noticed for some time that while running flexget through an UpStart daemon on Ubuntu (currently version 14.04), it will stop running tasks. I am needing to then restart the daemon (sudo restart flexget) which gets it working again for some time. Sometimes it will continue working for days, other times I will need to restart it multiple times throughout the day. After digging around, I found the following exception in the UpStart log file (/var/log/upstart/flexget.log), which does not appear in the ~/.flexget/flexget.log file. Every time flexget stops working recently with the scheduler, this exception has shown up in the log file. I have not noticed any other indications that it has stopped working. It appears to finish the current set of tasks that were triggered, but no further tasks will run after this.

```
Exception in thread APScheduler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 27, in _main_loop
    wait_seconds = self._process_jobs()
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 828, in _process_jobs
    jobstore.update_job(job)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 93, in update_job
    result = self.engine.execute(update)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) database is locked [SQL: u'UPDATE apscheduler_jobs SET next_run_time=?, job_state=? WHERE apscheduler_jobs.id = ?'] [parameters: (1459051243.056874, <read-only buffer for 0x7fbfac013ff0, size -1, offset 0 at 0x7fbfb013cdb0>, '7eb4c4245467539fd3b9baa4fecb8cdc20487ea9')]
```

**Comment by liiight** [comment]
Thanks for the info, duplicate #846. Discussion will continue there.
