### ISSUE TITLE
BUG: Unhandled error in plugin series: (sqlite3.OperationalError) ambiguous column name: first_seen

### ISSUE THREAD

**Issue by gsstark** [Flexget/Flexget#979]
`2016-03-27 19:09 CRITICAL task          torrent-day     BUG: Unhandled error in plugin series: (sqlite3.OperationalError) ambiguous column name: first_seen [SQL: u'SELECT series_episodes.id AS series_episodes_id, series_episodes.identifier AS series_episodes_identifier, series_episodes.season AS series_episodes_season, series_episodes.number AS series_episodes_number, series_episodes.identified_by AS series_episodes_identified_by, series_episodes.series_id AS series_episodes_series_id \nFROM series_episodes JOIN episode_releases ON series_episodes.id = episode_releases.episode_id JOIN series ON series.id = series_episodes.series_id \nWHERE series.id = ? AND episode_releases.downloaded = 1 ORDER BY first_seen DESC\n LIMIT ? OFFSET ?'] [parameters: (87, 1, 0)]`

And indeed... both these tables listed in the query above have a "first_seen" column in them:

```
sqlite> .schema series_episodes
CREATE TABLE series_episodes (
        id INTEGER NOT NULL, 
        identifier VARCHAR, 
        first_seen DATETIME, 
        season INTEGER, 
        number INTEGER, 
        series_id INTEGER NOT NULL, identified_by VARCHAR, 
        PRIMARY KEY (id), 
        FOREIGN KEY(series_id) REFERENCES series (id)
);
sqlite> .schema episode_releases
CREATE TABLE episode_releases (
        id INTEGER NOT NULL, 
        episode_id INTEGER NOT NULL, 
        quality VARCHAR, 
        downloaded BOOLEAN, 
        proper_count INTEGER, 
        title VARCHAR, first_seen DATETIME, 
        PRIMARY KEY (id), 
        FOREIGN KEY(episode_id) REFERENCES series_episodes (id), 
        CHECK (downloaded IN (0, 1))
);
```

So the ORDER BY is ambiguous (though technically in SQL only columns listed in the target list are valid in the ORDER BY list but I guess sqlite is liberal about this).

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 435, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1041, in on_task_filter
    self.process_series(task, series_entries, series_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1203, in process_series
    if self.process_episode_tracking(ep, entries, grace=len(series_entries) + 2, backfill=backfill):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 1329, in process_episode_tracking
    latest = get_latest_release(episode.series)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/filter/series.py", line 503, in get_latest_release
    latest_release = releases.order_by(desc(Episode.first_seen)).first()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
```

**Comment by liiight** [comment]
Can you paste full debug log please? I wonder what triggered this error

**Comment by gsstark** [comment]
Fwiw this went away when I updated 1.2.495.

I was on 1.2.336 previously.
