### ISSUE TITLE
BUG: Unhandled error in plugin transmission: Trying to render non string template, got None

### ISSUE THREAD

**Issue by cerberii** [Flexget/Flexget#981]
Running latest version of flexget, using content renaming plugin example from flexget wiki for transmission in config.yml  .  

When null is returned form tvdbplugin creates unhanlded error in transmission plugin, causing general protection fault in transmission

2016-03-27 09:01 ERROR    set           rarbgtv         Could not set content_filename for Bering.Sea.Gold.S06.Digging.Deep.Special.720p.HDTV.x264-W4F[rartv]: (UndefinedError) 'tvdb_episode' is undefined
2016-03-27 09:01 CRITICAL task          rarbgtv         BUG: Unhandled error in plugin transmission: Trying to render non string template, got None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_transmission.py", line 36, in new_f
    f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_transmission.py", line 311, in on_task_output
    self.add_to_transmission(self.client, task, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_transmission.py", line 397, in add_to_transmission
    options = self._make_torrent_options_dict(config, entry)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_transmission.py", line 378, in _make_torrent_options_dict
    post['content_filename'] = entry.render(opt_dic['content_filename'])
  File "/usr/local/lib/python2.7/dist-packages/flexget/entry.py", line 281, in render
    raise ValueError('Trying to render non string template, got %s' % repr(template))
ValueError: Trying to render non string template, got None

**Comment by crawln45** [comment]
That would be a render error. And They are there for a reason. Any field not returned is returned as None. The only way to eliminate this is to use default or if statements when rendering a field.

**Comment by crawln45** [comment]
Also there is no "Episode" in a season pack. Closing ticket.
