### ISSUE TITLE
Plugin `flexget.plugins.parsers.parser_guessit` failed to import dependencies. No module named rules

### ISSUE THREAD

**Issue by gsstark** [Flexget/Flexget#983]
Now that I've updated to 1.2.495 I'm getting a new error. I've done a pip update so I ought to have all the required modules:

```
2016-03-27 23:00 CRITICAL plugin                        Plugin `flexget.plugins.parsers.parser_guessit` failed to import dependencies
2016-03-27 23:00 ERROR    plugin                        No module named rules
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 381, in _load_plugins_from_dirs
    __import__(module_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/parsers/parser_guessit.py", line 8, in <module>
    from guessit.rules import rebulk_builder
ImportError: No module named rules
```

**Comment by stevezau** [comment]
weird.. https://github.com/guessit-io/guessit/blob/master/guessit/rules/__init__.py#L37

something may of went wrong with your guessit install..

maybe try 

```
pip install --upgrade guessit
```

**Comment by gsstark** [comment]
```
root@zzz:/home/stark# pip install --upgrade guessit
Downloading/unpacking guessit from https://pypi.python.org/packages/source/g/guessit/guessit-2.0.4.tar.gz#md5=2fc60912f7a12ca9573e265de23556d6
  Downloading guessit-2.0.4.tar.gz (73kB): 73kB downloaded
  Running setup.py (path:/tmp/user/0/pip-build-nWBLcd/guessit/setup.py) egg_info for package guessit
    
    Installed /tmp/user/0/easy_install-SIJO9v/pytest-runner-2.7/.eggs/setuptools_scm-1.10.1-py2.7.egg
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/user/0/pip-build-nWBLcd/guessit/.eggs/pytest_runner-2.7-py2.7.egg
    
    warning: no files found matching '*.ini' under directory 'guessit'
    warning: no previously-included files matching '*.pyc' found under directory 'guessit'
Requirement already up-to-date: rebulk>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from guessit)
Downloading/unpacking babelfish>=0.5.5 (from guessit)
  Downloading babelfish-0.5.5.tar.gz (90kB): 90kB downloaded
  Running setup.py (path:/tmp/user/0/pip-build-nWBLcd/babelfish/setup.py) egg_info for package babelfish
    
Downloading/unpacking python-dateutil from https://pypi.python.org/packages/any/p/python-dateutil/python_dateutil-2.5.2-py2.py3-none-any.whl#md5=50283d17f1a5c5919886af456afe4db1 (from guessit)
  Downloading python_dateutil-2.5.2-py2.py3-none-any.whl (201kB): 201kB downloaded
Requirement already up-to-date: six in /usr/lib/python2.7/dist-packages (from rebulk>=0.7.0->guessit)
Installing collected packages: guessit, babelfish, python-dateutil
  Found existing installation: guessit 0.11.0
    Not uninstalling guessit at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for guessit
    
    warning: no files found matching '*.ini' under directory 'guessit'
    warning: no previously-included files matching '*.pyc' found under directory 'guessit'
    Installing guessit script to /usr/local/bin
  Found existing installation: babelfish 0.5.4
    Not uninstalling babelfish at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for babelfish
    
  Found existing installation: python-dateutil 2.4.2
    Not uninstalling python-dateutil at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed guessit babelfish python-dateutil
```

**Comment by gsstark** [comment]
Hm. I did  `apt-get remove guessit` and now I don't get that error.

So there seems to be some version incompatibility with guessit 0.11.0 and the dependency isn't checked correctly?

**Comment by cvium** [comment]
It's generally a bad idea to install python packages from apt. Always use `pip` if possible.

**Comment by cvium** [comment]
> Not uninstalling guessit at /usr/lib/python2.7/dist-packages, owned by OS

This very line is the reason you should avoid installing Python packages with package managers that are not pip or easy_install. pip does not have the authority to uninstall/upgrade Python packages that are owned by the OS.
