### ISSUE TITLE
Input plugin: ftp_list path error

### ISSUE THREAD

**Issue by Meliox** [Flexget/Flexget#986]
There is some issues in ftp_list, which actually breaks the plugin completely (if my config is correct).

Version: 1.2.495
Config:
```
tasks:
  ftpauto:
    ftp_list:
      config:
        name: asdasdasdsa
        username: sdfdsfsdfdsfd
        password: '_dghfsgdsgsdg'
        host: ssdfsdfdsfdsfs
        port: 27sdfsd01sd6
        files-only: no
        recursive: no
        use-ssl: yes
        encoding: auto
      dirs:
        - /TV/
    series:
      - Girls
    ftp_download:
      use-ssl: yes
      ftp_tmp_path: C:\Users\Administrator\Desktop\autodl\tmp
    download: C:\Users\Administrator\Desktop\autodl\complete
```

1) Normally you write dirs as "/dir/". It seems like only "/dir" or "dir" works. Debug here:
```
2016-03-28 17:19 DEBUG    manager                       Figuring out config load paths
2016-03-28 17:19 DEBUG    manager                       Found config: C:\Users\Administrator\flexget\config.yml
2016-03-28 17:19 DEBUG    manager                       Config file C:\Users\Administrator\flexget\config.yml selected
2016-03-28 17:19 INFO     performance                   Enabling plugin and SQLAlchemy performance debugging
2016-03-28 17:19 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-03-28 17:19 CRITICAL task          ftpauto         BUG: Unhandled error in plugin ftp_list: 550 '/TV///TV/The.Deep.AU.S01E06.720p.HDTV.x264-RDVAS' cannot be listed
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\input\ftp_list.py", line 115, in on_task_input
    self._handle_path(entries, ftp, baseurl, path, mlst_supported, files_only, recursive, get_size, encoding)
  File "c:\python27\lib\site-packages\flexget\plugins\input\ftp_list.py", line 134, in _handle_path
    mlst_output = ftp.sendcmd('MLST ' + path + '/' + p)
  File "c:\python27\lib\ftplib.py", line 249, in sendcmd
    return self.getresp()
  File "c:\python27\lib\ftplib.py", line 224, in getresp
    raise error_perm, resp
error_perm: 550 '/TV///TV/The.Deep.AU.S01E06.720p.HDTV.x264-RDVAS' cannot be listed
```

2) Then there's this error: 
```
2016-03-28 18:13 DEBUG    manager                       Figuring out config load paths
2016-03-28 18:13 DEBUG    manager                       Found config: C:\Users\Administrator\flexget\config.yml
2016-03-28 18:13 DEBUG    manager                       Config file C:\Users\Administrator\flexget\config.yml selected
2016-03-28 18:13 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-03-28 18:13 INFO     ftp_list      ftpauto         Accepting entry "/TV/The.Deep.AU.S01E06.720p.HDTV.x264-RDVAS" [dir]
2016-03-28 18:13 CRITICAL task          ftpauto         BUG: Unhandled error in plugin ftp_list: 450 /TV/The.Deep.AU.S01E06.720p.HDTV.x264-RDVAS/the.deep.au.s01e06.720p.hdtv.x264-rdvas.r03//TV/The.Deep.AU.S01E06.720p.HDTV.x264-RDVAS/the.deep.au.s01e06.720p.hdtv.x264-rdvas.r03: Not a directory
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flexget\task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "c:\python27\lib\site-packages\flexget\plugins\input\ftp_list.py", line 115, in on_task_input
    self._handle_path(entries, ftp, baseurl, path, mlst_supported, files_only, recursive, get_size, encoding)
  File "c:\python27\lib\site-packages\flexget\plugins\input\ftp_list.py", line 161, in _handle_path
    entry['content_size'] = self.get_folder_size(ftp, path, p)
  File "c:\python27\lib\site-packages\flexget\plugins\input\ftp_list.py", line 204, in get_folder_size
    size += self.get_folder_size(ftp, path + '/' + p, filename)
  File "c:\python27\lib\site-packages\flexget\plugins\input\ftp_list.py", line 204, in get_folder_size
    size += self.get_folder_size(ftp, path + '/' + p, filename)
  File "c:\python27\lib\site-packages\flexget\plugins\input\ftp_list.py", line 197, in get_folder_size
    dirs = self.list_directory(ftp, path + '/' + p)
  File "c:\python27\lib\site-packages\flexget\plugins\input\ftp_list.py", line 185, in list_directory
    dirs = ftp.nlst(path)
  File "c:\python27\lib\ftplib.py", line 518, in nlst
    self.retrlines(cmd, files.append)
  File "c:\python27\lib\ftplib.py", line 735, in retrlines
    conn = self.transfercmd(cmd)
  File "c:\python27\lib\ftplib.py", line 376, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "c:\python27\lib\ftplib.py", line 710, in ntransfercmd
    conn, size = FTP.ntransfercmd(self, cmd, rest)
  File "c:\python27\lib\ftplib.py", line 339, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "c:\python27\lib\ftplib.py", line 249, in sendcmd
    return self.getresp()
  File "c:\python27\lib\ftplib.py", line 222, in getresp
    raise error_temp, resp
error_temp: 450 /TV/The.Deep.AU.S01E06.720p.HDTV.x264-RDVAS/the.deep.au.s01e06.720p.hdtv.x264-rdvas.r03//TV/The.Deep.AU.S01E06.720p.HDTV.x264-RDVAS/the.deep.au.s01e06.720p.hdtv.x264-rdvas.r03: Not a directory
```

 when using "/dir". First of all double baseurl, but also it is looking at the files. Is that a part of the get_folder_size?

Error could possible originate from this line: https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/input/ftp_list.py#L130

**Comment by liiight** [comment]
I'll take a look at this soon, need to familiarize myself with the plugin

**Comment by liiight** [comment]
did this ever work for you? that plugin looks kinda weird...

**Comment by Meliox** [comment]
Nope. It's completely broken.
Den 4. maj 2016 2.10 PM skrev "Or Carmi" <notifications@github.com>:

**Comment by liiight** [comment]
i think the paths under `dirs` should be relative to base. i have no ftp server to experiment with but try sending just `/` or something.

**Comment by Meliox** [comment]
The paths I provide are relative to base. Flexget actually finds the
subdirectories correctly, but merges base url with the found url.

I can provide an ftp account for you if that helps.
Den 4. maj 2016 3.25 PM skrev "Or Carmi" <notifications@github.com>:

**Comment by liiight** [comment]
yes that would. 
if you could join our [gitter](https://gitter.im/Flexget/Flexget) you could pm me the details
