### ISSUE TITLE
ERROR    lazy_lookup     Unhandled error in lazy lookup plugin

### ISSUE THREAD

**Issue by leetwanker** [Flexget/Flexget#990]
Been noticing a lot of episodes failing to get renamed lately. This is the first crash report I've seen, though. 

```
2016-03-29 21:01 INFO     download      HDTV-Shows      Downloading: Fresh.Off.the.Boat.S02E18.HDTV.x264-FLEET.mp4
2016-03-29 21:01 INFO     deluge        HDTV-Shows      Connecting to daemon at localhost:58846..
2016-03-29 21:01 INFO     deluge        HDTV-Shows      Connected to daemon at 127.0.0.1:58846..
2016-03-29 21:01 ERROR    lazy_lookup   HDTV-Shows      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 140, in lazy_episode_lookup
    episode = lookup_episode(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 470, in lookup_episode
    series = lookup_series(name=name, tvdb_id=tvdb_id, only_cached=only_cached, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 407, in lookup_series
    series.update()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 176, in update
    self._genres = get_db_genres(series['genre'])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1027, in set
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1062, in _set_iterable
    collections.bulk_replace(new_values, old_collection, new_collection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 791, in bulk_replace
    new_adapter.append_with_event(member)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 654, in append_with_event
    self._data()._sa_appender(item, _sa_initiator=initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1073, in append
    item = __set(self, item, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1045, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 717, in fire_append_event
    item, initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 941, in fire_append_event
    initiator or self._append_token or self._init_append_token())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 46, in append
    sess._save_or_update_state(item_state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1600, in _save_or_update_state
    self._save_or_update_impl(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1861, in _save_or_update_impl
    self._update_impl(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1854, in _update_impl
    self.identity_map.add(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/identity.py", line 132, in add
    % (key, ))
AssertionError: A conflicting state is already present in the identity map for key (<class 'flexget.plugins.api_tvdb.TVDBGenre'>, (8,))

```

**Comment by stevezau** [comment]
what version are you on

**Comment by leetwanker** [comment]
1.2.496

Sorry, forgot to include. I just upgraded to the latest after I posted the issue to see if it had been fixed in latest version.

**Comment by leetwanker** [comment]
No, same problem with 1.2.497. 

```
2016-03-29 23:02 INFO     download      HDTV-Shows      Downloading: Marvels.Agents.of.S.H.I.E.L.D.S03E14.HDTV.x264-FLEET.mp4
2016-03-29 23:02 INFO     deluge        HDTV-Shows      Connecting to daemon at localhost:58846..
2016-03-29 23:02 INFO     deluge        HDTV-Shows      Connected to daemon at 127.0.0.1:58846..
2016-03-29 23:02 ERROR    lazy_lookup   HDTV-Shows      Unhandled error in lazy lookup plugin
2016-03-29 23:02 CRITICAL manager       HDTV-Shows      An unexpected crash has occurred. Writing crash report to /home/osmc/.flexget/crash_report.2016.03.29.230226316233.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.497
2016-03-29 23:02 ERROR    lazy_lookup   HDTV-Shows      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 140, in lazy_episode_lookup
    episode = lookup_episode(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 470, in lookup_episode
    series = lookup_series(name=name, tvdb_id=tvdb_id, only_cached=only_cached, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 407, in lookup_series
    series.update()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 176, in update
    self._genres = get_db_genres(series['genre'])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1027, in set
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1062, in _set_iterable
    collections.bulk_replace(new_values, old_collection, new_collection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 791, in bulk_replace
    new_adapter.append_with_event(member)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 654, in append_with_event
    self._data()._sa_appender(item, _sa_initiator=initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1073, in append
    item = __set(self, item, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1045, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 717, in fire_append_event
    item, initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 941, in fire_append_event
    initiator or self._append_token or self._init_append_token())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 46, in append
    sess._save_or_update_state(item_state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1600, in _save_or_update_state
    self._save_or_update_impl(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1861, in _save_or_update_impl
    self._update_impl(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1854, in _update_impl
    self.identity_map.add(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/identity.py", line 132, in add
    % (key, ))
AssertionError: A conflicting state is already present in the identity map for key (<class 'flexget.plugins.api_tvdb.TVDBGenre'>, (2,))
```

**Comment by chewy74** [comment]
Got the same error... I believe it's tvdb_lookup related 
Version 1.2.497
```

2016-03-30 00:05 INFO     download      tv_shows        Downloading: New.Girl.S05E13.720p.HDTV.x264-AVS
2016-03-30 00:05 VERBOSE  details       tv_shows        Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2016-03-30 00:05 VERBOSE  api_tvdb      tv_shows        Data for New Girl has expired, refreshing from tvdb
2016-03-30 00:05 ERROR    lazy_lookup   tv_shows        Unhandled error in lazy lookup plugin
2016-03-30 00:05 CRITICAL manager       tv_shows        An unexpected crash has occurred. Writing crash report to /home/pi/.flexget/crash_report.2016.03.30.000517374875.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.497
2016-03-30 00:05 VERBOSE  api_tvdb      tv_shows        Data for New Girl has expired, refreshing from tvdb
2016-03-30 00:05 ERROR    lazy_lookup   tv_shows        Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 140, in lazy_episode_lookup
    episode = lookup_episode(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 470, in lookup_episode
    series = lookup_series(name=name, tvdb_id=tvdb_id, only_cached=only_cached, session=session)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 407, in lookup_series
    series.update()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 176, in update
    self._genres = get_db_genres(series['genre'])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1027, in set
    lambda adapter, i: adapter.adapt_like_to_iterable(i))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1062, in _set_iterable
    collections.bulk_replace(new_values, old_collection, new_collection)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 791, in bulk_replace
    new_adapter.append_with_event(member)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 654, in append_with_event
    self._data()._sa_appender(item, _sa_initiator=initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1073, in append
    item = __set(self, item, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1045, in __set
    item = executor.fire_append_event(item, _sa_initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 717, in fire_append_event
    item, initiator)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 941, in fire_append_event
    initiator or self._append_token or self._init_append_token())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 46, in append
    sess._save_or_update_state(item_state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1600, in _save_or_update_state
    self._save_or_update_impl(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1861, in _save_or_update_impl
    self._update_impl(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1854, in _update_impl
    self.identity_map.add(state)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/identity.py", line 132, in add
    % (key, ))
AssertionError: A conflicting state is already present in the identity map for key (<class 'flexget.plugins.api_tvdb.TVDBGenre'>, (5,))
```

**Comment by stevezau** [comment]
just pushed a change that might fix this.. should get pushed to a new release later today. please let me know.

**Comment by leetwanker** [comment]
> Upgraded Flexget-1.2.497 to Flexget-1.2.498 on Thu Mar 31 09:12:31 EDT 2016

```
2016-03-31 14:02 INFO     download      720P-Shows      Downloading: house.of.cards.2013.s04e08.720p.hdtv.x264-fleet.mkv
2016-03-31 14:02 INFO     deluge        720P-Shows      Connecting to daemon at localhost:58846..
2016-03-31 14:02 INFO     deluge        720P-Shows      Connected to daemon at 127.0.0.1:58846..
2016-03-31 14:02 ERROR    lazy_lookup   720P-Shows      Unhandled error in lazy lookup plugin
2016-03-31 14:02 CRITICAL manager       720P-Shows      An unexpected crash has occurred. Writing crash report to /home/osmc/.flexget/crash_report.2016.03.31.140233625789.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.498
2016-03-31 14:02 ERROR    lazy_lookup   720P-Shows      Unhandled error in lazy lookup plugin
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/lazy_dict.py", line 36, in __getitem__
    func(self.store)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/metainfo/thetvdb_lookup.py", line 140, in lazy_episode_lookup
    episode = lookup_episode(**lookupargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 499, in lookup_episode
    episode = episode.first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2735, in __iter__
    self.session._autoflush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1293, in _autoflush
    self.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 149, in save_obj
    base_mapper, states, uowtransaction
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 301, in _organize_states_for_save
    state_str(existing)))
FlushError: New instance <TVDBGenre at 0x75261e10> with identity key (<class 'flexget.plugins.api_tvdb.TVDBGenre'>, (4,)) conflicts with persistent instance <TVDBGenre at 0x752d0870>
```

**Comment by leetwanker** [comment]
I got this tonight. Related?

`2016-04-01 23:02 WARNING  api_tvdb      HDTV-Shows      Error while updating from tvdb (Error updating data from tvdb: HTTPSConnectionPool(host='api-beta.thetvdb.com', port=443): Read timed out. (read timeout=30)), using cached data.`
