### ISSUE TITLE
Bug since version 1.2.484

### ISSUE THREAD

**Issue by averissimo** [Flexget/Flexget#993]
Traced back this error to version 1.2.484 as in 1.2.483 it did not appear.

```
2016-03-31 15:42 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
Traceback (most recent call last):
  File "/opt/flexget-dev/flexget/task_queue.py", line 47, in run
    self.current_task.execute()
  File "/opt/flexget-dev/flexget/task.py", line 69, in wrapper
    return func(self, *args, **kw)
  File "/opt/flexget-dev/flexget/task.py", line 592, in execute
    fire_event('task.execute.completed', self)
  File "/opt/flexget-dev/flexget/event.py", line 103, in fire_event
    result = event(*args, **kwargs)
  File "/opt/flexget-dev/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/opt/flexget-dev/flexget/utils/simple_persistence.py", line 189, in flush_task
    SimplePersistence.flush(task.name)
  File "/opt/flexget-dev/flexget/utils/simple_persistence.py", line 152, in flush
    updated = query.update({'value': value}, synchronize_session=False)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2851, in update
    update_op.exec_()
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 897, in exec_
    self._do_exec()
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/persistence.py", line 995, in _do_exec
    update_stmt, params=self.query._params)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1021, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 931, in _execute_clauseelement
    inline=len(distilled_params) > 1)
  File "<string>", line 1, in <lambda>
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 493, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/elements.py", line 499, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/compiler.py", line 395, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/compiler.py", line 199, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/compiler.py", line 222, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/visitors.py", line 80, in _compiler_dispatch
    return meth(self, **kw)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/compiler.py", line 1814, in visit_update
    colparams = self._get_colparams(update_stmt, **kw)
  File "/opt/flexget-dev/lib/python2.7/site-packages/SQLAlchemy-0.9.9-py2.7-linux-x86_64.egg/sqlalchemy/sql/compiler.py", line 2225, in _get_colparams
    (", ".join("%s" % c for c in check))
CompileError: Unconsumed column names: value
```

**Comment by cvium** [comment]
Could you try updating Flexget and see if it has been fixed?

**Comment by averissimo** [comment]
Same thing happens and it actually generates two crashes, attachments below.

Is there a benchmark configuration file that I can test? (couldn't find one in the source tree)

[crash_report.2016.04.12.144834244953.txt](https://github.com/Flexget/Flexget/files/215127/crash_report.2016.04.12.144834244953.txt)
[crash_report.2016.04.12.144842224425.txt](https://github.com/Flexget/Flexget/files/215128/crash_report.2016.04.12.144842224425.txt)

**Comment by stevezau** [comment]
hmm, i think there were issues when we converted to json storage rather then pickle.. You might of upgraded when there was a bug..

Resetting simple_persistence should solve your issue. However, it will clear that table but usually nothing important is stored in there..

```
flexget database reset-plugin simple_persistence
```

**Comment by averissimo** [comment]
Same error after resetting. I tested this removing the database file and error exists.

Nevertheless the files are downloaded

[crash_report.2016.04.19.164906888271.txt](https://github.com/Flexget/Flexget/files/226261/crash_report.2016.04.19.164906888271.txt)

**Comment by averissimo** [comment]
Yay!! Just had a clean run, **solution:**

Upgrade pip packages to a later version

    bin/pip install --upgrade .

I had to run this multiple times and when flexget -V gave me errors of missing packages, I installed them manually

    bin/pip install <missing package>

**Comment by vincentbernat** [comment]
Upgrading to a more recent version of SQLAlchemy also solved the problem for me:

```
./bin/pip install --upgrade 'SQLAlchemy!=0.9.0,<1.999,>=0.7.5'
```
