### ISSUE TITLE
tvdb_favorites creating bug

### ISSUE THREAD

**Issue by ridoline** [Flexget/Flexget#994]
After a recent update, tvdb_favorites no longer works.  This is the current iteration of not working.

> 2016-03-31 18:23 DEBUG    manager                       Figuring out config load paths
2016-03-31 18:23 DEBUG    manager                       Found config: /home/user/.flexget/config.yml
2016-03-31 18:23 DEBUG    manager                       Config file /home/user/.flexget/config.yml selected
2016-03-31 18:23 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-03-31 18:23 VERBOSE  api_tvdb      filefeed_tv     Data for Modern Family has expired, refreshing from tvdb
2016-03-31 18:23 CRITICAL task          filefeed_tv     BUG: Unhandled error in plugin configure_series: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO tvdb_genres (name) VALUES (?)'] [parameters: (u'Comedy',)]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_configure_series.py", line 69, in on_task_start
    result = method(task, input_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 142, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/thetvdb_favorites.py", line 108, in on_task_input
    series = lookup_series(tvdb_id=series_id)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 412, in lookup_series
    series.update()
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 190, in update
    genres = _get_db_genres(series['genre'])
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/api_tvdb.py", line 116, in _get_db_genres
    session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO tvdb_genres (name) VALUES (?)'] [parameters: (u'Comedy',)]

**Comment by stevezau** [comment]
what version are you on

**Comment by ridoline** [comment]
1.2.498

**Comment by ridoline** [comment]
That error was generated after I deleted everything out of tvdb_genres.  After reverting to a previous version of the database, the error I see is:

2016-03-31 18:53 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-03-31 18:53 VERBOSE  api_tvdb      filefeed_tv     Data for Modern Family has expired, refreshing from tvdb
2016-03-31 18:53 CRITICAL task          filefeed_tv     BUG: Unhandled error in plugin configure_series: New instance <TVDBGenre at 0x7faf5d916650> with identity key (<class 'flexget.plugins.api_tvdb.TVDBGenre'>, (1,)) conflicts with persistent instance <TVDBGenre at 0x7faf5d926190>
2016-03-31 18:53 CRITICAL manager       filefeed_tv     An unexpected crash has occurred. Writing crash report to /home/deluge/.flexget/crash_report.2016.03.31.185359247973.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 1.2.498
2016-03-31 18:53 WARNING  task          filefeed_tv     Aborting task (plugin: configure_series)

`2016-03-31 18:53 DEBUG    manager                       Figuring out config load paths
2016-03-31 18:53 DEBUG    manager                       Found config: /home/user/.flexget/config.yml
2016-03-31 18:53 DEBUG    manager                       Config file /home/user/.flexget/config.yml selected
2016-03-31 18:53 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-03-31 18:53 VERBOSE  api_tvdb      filefeed_tv     Data for Modern Family has expired, refreshing from tvdb
2016-03-31 18:53 CRITICAL task          filefeed_tv     BUG: Unhandled error in plugin configure_series: New instance <TVDBGenre at 0x7faf5d916650> with identity key (<class 'flexget.plugins.api_tvdb.TVDBGenre'>, (1,)) conflicts with persistent instance <TVDBGenre at 0x7faf5d926190>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/task.py", line 438, in __run_plugin
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/plugin_configure_series.py", line 69, in on_task_start
    result = method(task, input_config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/cached_input.py", line 142, in wrapped_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugin.py", line 124, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/input/thetvdb_favorites.py", line 108, in on_task_input
    series = lookup_series(tvdb_id=series_id)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/sqlalchemy_utils.py", line 137, in __exit__
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 149, in save_obj
    base_mapper, states, uowtransaction
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 301, in _organize_states_for_save
    state_str(existing)))
FlushError: New instance <TVDBGenre at 0x7faf5d916650> with identity key (<class 'flexget.plugins.api_tvdb.TVDBGenre'>, (1,)) conflicts with persistent instance <TVDBGenre at 0x7faf5d926190>
`

**Comment by stevezau** [comment]
You manually deleted stuff from the db? Or did you use db reset?

**Comment by ridoline** [comment]
The last crashreport would be after running:
flexget database plugin-reset tvdb_favorites

The first would be after manually deleting genres from the database using sqllite.

I have since reverted to an earlier backup of the database.

commenting out 
 genres = _get_db_genres(series['genre'])
 self._genres = [TVDBGenre(**g) for g in genres]

 allowed the task to complete, which I guess will hold me over until the next time the data expires.

**Comment by stevezau** [comment]
It's very hard to read your log.. can you paste it properly with markup?

**Comment by ridoline** [comment]
Changed it from code to quote.  Is that sufficient?

**Comment by stevezau** [comment]
yeah.. taking a look now.

**Comment by stevezau** [comment]
are you on dev? I just committed a change that might fix it. Let me know.

**Comment by stevezau** [comment]
actually that won't fix it. nevermind

**Comment by stevezau** [comment]
please test again.

**Comment by ridoline** [comment]
I am on 1.2.499 now, although as I said earlier.  I havent received the provided errors since my previous comment.  I tried flexget database reset-plugin tvdb_favorites, however it didnt produce the desired result, and it doesnt appears this plugin is influenced by the no-cache  cli option
